(function(root){
'use strict';
const O=root.OFU=root.OFU||{},R=O.waveIVScaleRuntime,P=O.v1Providers,X=O.pxProduct;
if(!R||!P||!X)return;
const VERSION='ofu-v1-systemic-audio-1',SURFACE=new Set(['global_surface','regional_surface','local_surface','human']),state={enabled:false,muted:true,context:null,master:null,ambience:[],updates:0,last:null};
function world(){try{const s=R.snapshot().selectedCanonicalTarget;return s?.canonicalKey?P.worldFor(X.captured(s.canonicalKey).selection):null}catch{return null}}
function contextFor(scale,w){const surface=SURFACE.has(scale),atmosphere=surface&&Number(w?.planetology?.atmosphere?.inventoryUnits||0)>0,water=surface&&Number(w?.planetology?.hydrosphere?.waterAreaPpm||0)>5000,biosphere=surface&&w?.biology?.occupancy?.state==='MODELED_BIOSPHERE',civilization=surface&&w?.civilization?.state==='MODELED_CIVILIZATION';return Object.freeze({scale,surface,vacuum:!surface,atmosphere,water,biosphere,civilization,environmentalAudioAllowed:surface&&atmosphere,authority:'PRESENTATION_ONLY',naturalVacuumAcousticsClaim:false});}
function stopAmbience(){for(const n of state.ambience)try{n.stop?.();n.disconnect?.()}catch{}state.ambience=[]}
function ensureContext(){if(state.context)return state.context;const A=root.AudioContext||root.webkitAudioContext;if(!A)throw new Error('Web Audio unavailable');const c=new A(),g=c.createGain();g.gain.value=0;g.connect(c.destination);state.context=c;state.master=g;return c}
function oscillator(freq,gain){const c=ensureContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(state.master);o.start();state.ambience.push(o,g);return o}
function sync(){state.updates++;const cfg=contextFor(R.snapshot().semanticScale,world());state.last=cfg;if(!state.context)return cfg;stopAmbience();state.master.gain.setTargetAtTime(state.enabled&&!state.muted?.045:0,state.context.currentTime,.04);if(!state.enabled||state.muted||!cfg.environmentalAudioAllowed)return cfg;oscillator(cfg.water?74:58,.12);if(cfg.biosphere)oscillator(310,.018);if(cfg.civilization)oscillator(122,.012);return cfg}
function enable(){const c=ensureContext();state.enabled=true;state.muted=false;const resumed=c.resume?.();sync();return resumed||Promise.resolve()}
function setMuted(v){state.muted=!!v;sync();return snapshot()}
function uiTone(){if(!state.enabled||state.muted)return false;const c=ensureContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.setValueAtTime(.025,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.055);o.connect(g);g.connect(state.master);o.start();o.stop(c.currentTime+.06);return true}
function ensureControl(){if(typeof document==='undefined'||document.getElementById('v1-audio-toggle'))return;const panel=document.querySelector('[data-workspace-panel="lab"]')||document.body,b=document.createElement('button');b.id='v1-audio-toggle';b.type='button';b.className='action-button secondary';b.textContent='Enable sound';b.setAttribute('aria-pressed','false');b.addEventListener('click',async()=>{try{if(!state.enabled)await enable();else setMuted(!state.muted);b.textContent=state.muted?'Enable sound':'Mute sound';b.setAttribute('aria-pressed',state.muted?'false':'true')}catch(e){b.title=String(e?.message||e)}});const host=document.createElement('section');host.className='section';const h=document.createElement('h3');h.textContent='Systemic audio';const p=document.createElement('p');p.className='semantic-note';p.textContent='Disabled until user activation. Environmental ambience is presentation-only and remains silent in vacuum; interface tones are not natural propagation claims.';host.append(h,p,b);panel.append(host)}
function snapshot(){return Object.freeze({version:VERSION,enabled:state.enabled,muted:state.muted,updates:state.updates,last:state.last,authority:'PRESENTATION_ONLY',autoplay:false,naturalVacuumAcousticsClaim:false});}
R.on?.('scaleChanged',sync);R.on?.('selectionChanged',sync);if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensureControl();sync()},{once:true});else{ensureControl();sync()}}
O.v1Audio=Object.freeze({VERSION,contextFor,enable,setMuted,uiTone,sync,snapshot});
})(globalThis);
