(function(root){
'use strict';
const O=root.OFU=root.OFU||{};if(typeof document==='undefined')return;const R=O.waveIVScaleRuntime,C=O.planetRenderCore;if(!R||!C)throw new Error('Wave IV input router requires scale runtime 2.x and camera core');
const VERSION='ofu-wave-iv-input-router-3',INTENT_CONTRACT='ofu-wave-iv-input-intent-2',LOCAL_SURFACE=new Set(['regional_surface','local_surface','human']);
const state={version:VERSION,contract:INTENT_CONTRACT,initialized:false,providerReady:false,surfaceProviderReady:false,stageCommands:0,wheelCommands:0,pointerIntents:0,keyboardIntents:0,viewportUpdates:0,lastIntent:null,lastStage:null,lastWheelDirection:null,pointerActive:false,globalSurfaceRenderer:'planet-webgl'};
const canvas=()=>document.getElementById('planet-view'),preview=()=>root.__OFU_PLANET_PREVIEW__,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function settle(P){if(P?.camera&&P.reducedMotion){P.camera.distanceM=Math.max(P.camera.minDistanceM,P.camera.targetDistanceM);P.camera.direction=P.camera.targetDirection}}
function cameraTarget(P,{distanceRadii=null,direction=null}={}){if(!P?.camera||!P.radius)return false;C.setCameraTarget(P.camera,{distanceM:distanceRadii===null?P.camera.targetDistanceM:P.radius*Number(distanceRadii),direction:direction||P.camera.targetDirection});settle(P);return true}
function refreshPlanetAnchors(source='projection-framing'){const nav=O.v08ExploreNavigation,P=preview();if(!P?.radius)return false;for(const b of ['system','orbit','approach']){const f=nav?.framingFor?.(b);if(f&&Number(f.distanceM)>0)try{R.configureAnchor(b,f.distanceM/P.radius,{source})}catch{}}try{R.configureAnchor('global_surface',2.16,{source:'global-spherical-handoff'})}catch{}return true}
function registerProviders(){const P=preview(),node=canvas();if(!P?.camera||!P.radius||!node)return false;R.registerSceneProvider({id:'planet-webgl',scales:['orbit','approach','global_surface'],setActive(active,snap){node.dataset.scenePrimary=active?'true':'false';if(active&&snap?.semanticScale==='global_surface'&&P.surfaceMode==='LOCAL')P.leaveSurface?.()},setDistanceRadii(r){cameraTarget(P,{distanceRadii:r})},cameraIntent(intent){if(intent.kind==='rotate-drag'){const b=Array.isArray(intent.baseDirection)?intent.baseDirection:P.camera.targetDirection;cameraTarget(P,{direction:[b[0]+Number(intent.dx)*1.4,b[1]-Number(intent.dy)*1.4,b[2]]})}else if(intent.kind==='rotate-step'){const d=P.camera.targetDirection;cameraTarget(P,{direction:[d[0]+Number(intent.dx||0),d[1]+Number(intent.dy||0),d[2]]})}else if(intent.kind==='reset-direction')cameraTarget(P,{direction:[.18,.12,1]})}});state.providerReady=true;R.registerSceneProvider({id:'surface-webgl',scales:['regional_surface','local_surface','human'],setActive(active,snap){if(active){const band=String(snap.semanticScale).toUpperCase();const entered=P.surfaceMode==='LOCAL'?P.snapshot().surface:P.enterSurface(band);if(entered?.ready===false){O.productUI?.announce?.('Local solid-surface traversal is not available for this world.');root.queueMicrotask?.(()=>R.requestStage('approach',{source:'surface-unavailable'}));return}P.setSurfaceBand?.(band)}else if(P.surfaceMode==='LOCAL'){P.leaveSurface?.()}},cameraIntent(intent){if(P.surfaceMode!=='LOCAL')return;const map={move_forward:'MOVE_FORWARD',move_right:'MOVE_RIGHT',look_yaw:'LOOK_YAW',look_pitch:'LOOK_PITCH'};if(map[intent.kind])P.surfaceIntent?.({type:map[intent.kind],amount:Number(intent.amount)||1})}});state.surfaceProviderReady=true;refreshPlanetAnchors('provider-ready');R.requestStage(R.snapshot().semanticScale,{source:'provider-ready',transition:false});return true}
function routeStage(stage,source='stage-selection'){try{stage=R.normalizeBand(stage)}catch{return false}state.stageCommands++;state.lastStage=stage;state.lastIntent=source;const result=R.requestStage(stage,{source});for(const b of document.querySelectorAll('[data-wave-iv-scale]'))b.setAttribute('aria-pressed',b.dataset.waveIvScale===stage?'true':'false');return !!result}
function handleClick(e){const n=e.target.closest?.('[data-wave-iv-scale],[data-render-stage],[data-explore-stage]');if(!n)return;const stage=n.dataset.waveIvScale||n.dataset.renderStage||n.dataset.exploreStage;if(!stage)return;e.preventDefault();e.stopPropagation();routeStage(stage,'semantic-scale-control')}
function currentDistance(){const P=preview();return P?.camera&&P.radius?P.camera.targetDistanceM/P.radius:R.snapshot().distanceIntentRadii}
function surfaceWheel(sign){const P=preview(),before=P?.snapshot?.().surface?.camera;if(!before)return false;const factor=sign>0?1.55:.58,Palt=Math.max(2,before.presentationAltitudeM*factor),delta=(Palt-before.presentationAltitudeM)/20;P.surfaceIntent?.({type:'CHANGE_ALTITUDE',amount:delta});const after=P.snapshot().surface?.camera,band=String(after?.currentBand||'REGIONAL_SURFACE').toLowerCase();if(LOCAL_SURFACE.has(band)&&band!==R.snapshot().semanticScale)R.requestStage(band,{source:'wheel-surface-band',transition:true,driveCamera:false});return true}
function handleWheel(e){const P=preview();if(!P?.camera||!P.radius)return;const sign=Math.sign(Number(e.deltaY));if(!sign)return;e.preventDefault();e.stopImmediatePropagation();state.wheelCommands++;state.lastWheelDirection=sign>0?'out':'in';state.lastIntent='wheel';const scale=R.snapshot().semanticScale;if(scale==='global_surface'){R.stepTravel(sign,{source:'wheel-global-handoff'});return}if(LOCAL_SURFACE.has(scale)||P.surfaceMode==='LOCAL'){surfaceWheel(sign);return}if(['galaxy','stellar_neighborhood','system'].includes(scale)){R.stepTravel(sign,{source:'wheel-macro'});return}const min=.9999,next=clamp(currentDistance()*Math.exp(sign*.22),min,R.DEFAULT_ANCHORS.galaxy*1.01);R.setContinuousDistance(next,{source:'wheel-planet'})}
let drag=null;
function endPointer(e){const n=canvas();drag=null;state.pointerActive=false;const P=preview();if(P)P.pointerActive=false;if(e&&n?.hasPointerCapture?.(e.pointerId))try{n.releasePointerCapture(e.pointerId)}catch{}}
function down(e){const P=preview(),n=canvas();if(!P?.camera||!n)return;if(['galaxy','stellar_neighborhood','system'].includes(R.snapshot().semanticScale))return;e.stopImmediatePropagation();if(e.pointerType==='mouse'&&e.button!==0)return;n.focus({preventScroll:true});drag={id:e.pointerId,x:e.clientX,y:e.clientY,base:[...P.camera.targetDirection],kind:e.pointerType==='mouse'?'rotate':'pending'};state.pointerActive=true;P.pointerActive=true;if(e.pointerType==='mouse')try{n.setPointerCapture(e.pointerId)}catch{}}
function move(e){if(!drag||drag.id!==e.pointerId)return;e.stopImmediatePropagation();const n=canvas(),dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.kind==='pending'){if(Math.hypot(dx,dy)<7)return;if(Math.abs(dy)>Math.abs(dx)*1.1){drag.kind='scroll';return}drag.kind='rotate';try{n.setPointerCapture(e.pointerId)}catch{}}if(drag.kind!=='rotate')return;if(e.cancelable&&e.pointerType!=='mouse')e.preventDefault();state.pointerIntents++;if(LOCAL_SURFACE.has(R.snapshot().semanticScale)){preview().surfaceIntent?.({type:'LOOK_YAW',amount:dx/Math.max(80,n.clientWidth)*8});preview().surfaceIntent?.({type:'LOOK_PITCH',amount:-dy/Math.max(80,n.clientHeight)*8});drag.x=e.clientX;drag.y=e.clientY}else R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-drag',pointerType:e.pointerType,baseDirection:drag.base,dx:dx/Math.max(200,n.clientWidth),dy:dy/Math.max(200,n.clientHeight)},{source:'pointer-drag'})}
function key(e){const P=preview();if(!P?.camera)return;const scale=R.snapshot().semanticScale;if(['galaxy','stellar_neighborhood','system'].includes(scale))return;let handled=true;if(LOCAL_SURFACE.has(scale)){if(e.key==='ArrowLeft')P.surfaceIntent?.({type:'LOOK_YAW',amount:-1});else if(e.key==='ArrowRight')P.surfaceIntent?.({type:'LOOK_YAW',amount:1});else if(e.key==='ArrowUp')P.surfaceIntent?.({type:'LOOK_PITCH',amount:1});else if(e.key==='ArrowDown')P.surfaceIntent?.({type:'LOOK_PITCH',amount:-1});else if(e.key==='w'||e.key==='W')P.surfaceIntent?.({type:'MOVE_FORWARD',amount:1});else if(e.key==='s'||e.key==='S')P.surfaceIntent?.({type:'MOVE_FORWARD',amount:-1});else if(e.key==='a'||e.key==='A')P.surfaceIntent?.({type:'MOVE_RIGHT',amount:-1});else if(e.key==='d'||e.key==='D')P.surfaceIntent?.({type:'MOVE_RIGHT',amount:1});else if(e.key==='+'||e.key==='=')surfaceWheel(-1);else if(e.key==='-'||e.key==='_')surfaceWheel(1);else if(e.key==='Home'){P.leaveSurface?.();R.requestStage('global_surface',{source:'keyboard-reverse'})}else handled=false}else if(e.key==='ArrowLeft')R.dispatchCameraIntent({kind:'rotate-step',dx:-.12,dy:0},{source:'keyboard'});else if(e.key==='ArrowRight')R.dispatchCameraIntent({kind:'rotate-step',dx:.12,dy:0},{source:'keyboard'});else if(e.key==='ArrowUp')R.dispatchCameraIntent({kind:'rotate-step',dx:0,dy:.12},{source:'keyboard'});else if(e.key==='ArrowDown')R.dispatchCameraIntent({kind:'rotate-step',dx:0,dy:-.12},{source:'keyboard'});else if(e.key==='+'||e.key==='=')R.stepTravel(-1,{source:'keyboard-zoom-in'});else if(e.key==='-'||e.key==='_')R.stepTravel(1,{source:'keyboard-zoom-out'});else if(e.key==='Home'){R.dispatchCameraIntent({kind:'reset-direction'},{source:'keyboard-home'});routeStage('orbit','keyboard-home')}else handled=false;if(handled){state.keyboardIntents++;e.preventDefault();e.stopImmediatePropagation()}}
function viewport(){const n=canvas(),r=n?.getBoundingClientRect?.();if(!r)return;state.viewportUpdates++;R.viewportChanged({width:r.width,height:r.height,devicePixelRatio:Number(root.devicePixelRatio)||1},{source:'resize'});refreshPlanetAnchors('resize')}
function init(){if(state.initialized)return;const n=canvas();if(!n)return;state.initialized=true;if(!registerProviders()){const retry=()=>{if(state.providerReady&&state.surfaceProviderReady)return;if(registerProviders())return;root.requestAnimationFrame?.(retry)};root.requestAnimationFrame?.(retry)}document.addEventListener('click',handleClick,true);n.addEventListener('wheel',handleWheel,{passive:false,capture:true});n.addEventListener('pointerdown',down,true);n.addEventListener('pointermove',move,{passive:false,capture:true});n.addEventListener('pointerup',endPointer,true);n.addEventListener('pointercancel',endPointer,true);n.addEventListener('keydown',key,true);R.on('scaleChanged',e=>{for(const b of document.querySelectorAll('[data-wave-iv-scale]'))b.setAttribute('aria-pressed',b.dataset.waveIvScale===e.snapshot.semanticScale?'true':'false')});if(typeof ResizeObserver==='function'){const ro=new ResizeObserver(viewport);ro.observe(n);state.resizeObserver=ro}else root.addEventListener?.('resize',viewport,{passive:true})}
const snapshot=()=>Object.freeze({...state,scale:R.snapshot()});O.waveIVInputRouter=Object.freeze({VERSION,contract:INTENT_CONTRACT,state,snapshot,routeStage,refreshPlanetAnchors,init});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(typeof globalThis!=='undefined'?globalThis:this);
