(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
if(typeof document==='undefined')return;
const R=O.waveIVScaleRuntime,C=O.planetRenderCore;
if(!R||!C)throw new Error('Wave IV input router requires authoritative scale runtime and planet camera core');
const VERSION='ofu-wave-iv-input-router-1',INTENT_CONTRACT='ofu-wave-iv-input-intent-1';
const state={version:VERSION,contract:INTENT_CONTRACT,initialized:false,providerReady:false,stageCommands:0,wheelCommands:0,pointerIntents:0,keyboardIntents:0,selectionIntents:0,lastIntent:null,lastStage:null,lastWheelDirection:null,pointerActive:false};
const canvas=()=>document.getElementById('planet-view');
const preview=()=>root.__OFU_PLANET_PREVIEW__;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function settle(P){if(!P?.camera||!P.reducedMotion)return;P.camera.distanceM=Math.max(P.camera.minDistanceM,P.camera.targetDistanceM);P.camera.direction=P.camera.targetDirection}
function setCameraTarget(P,{distanceRadii=null,direction=null}={}){if(!P?.camera||!P?.radius)return false;const distanceM=distanceRadii===null?P.camera.targetDistanceM:P.radius*Number(distanceRadii);C.setCameraTarget(P.camera,{distanceM,direction:direction||P.camera.targetDirection});settle(P);return true}
function currentDistanceRadii(){const P=preview();return P?.camera&&P?.radius?P.camera.targetDistanceM/P.radius:R.snapshot().distanceIntentRadii}
function registerPlanetProvider(){const P=preview(),node=canvas();if(!P?.camera||!P?.radius||!node)return false;R.registerSceneProvider({id:'planet-webgl',scales:['orbit','approach','close'],setActive(active){node.dataset.scenePrimary=active?'true':'false';node.setAttribute('aria-hidden','false')},setDistanceRadii(distanceRadii){setCameraTarget(P,{distanceRadii})},cameraIntent(intent){if(intent.kind==='rotate-drag'){const base=Array.isArray(intent.baseDirection)?intent.baseDirection:P.camera.targetDirection;setCameraTarget(P,{direction:[base[0]+Number(intent.dx)*1.4,base[1]-Number(intent.dy)*1.4,base[2]]})}else if(intent.kind==='rotate-step'){const d=P.camera.targetDirection;setCameraTarget(P,{direction:[d[0]+Number(intent.dx||0),d[1]+Number(intent.dy||0),d[2]]})}else if(intent.kind==='reset-direction')setCameraTarget(P,{direction:[0.18,0.12,1]})}});if(!P.__waveIVNavigateDelegated){P.__waveIVNavigateDelegated=true;P.navigateToRadii=radii=>R.setContinuousDistance(Number(radii),{source:'compat-navigateToRadii'});}state.providerReady=true;return true}
function routeStage(stage,source){const nav=O.v08ExploreNavigation,P=preview();stage=String(stage||'').toLowerCase();if(!R.CURRENT_BANDS.includes(stage))return false;const framing=nav?.framingFor?.(stage);if(framing&&P?.radius){R.configureAnchor(stage,framing.distanceM/P.radius,{source:'projection-framing'});if(nav?.state){nav.state.framing=framing;nav.state.lastFramingKey=null}}if(nav?.state)nav.state.stage=stage;state.stageCommands++;state.lastStage=stage;state.lastIntent=source;const result=R.requestStage(stage,{source});for(const button of document.querySelectorAll('[data-explore-stage],[data-render-stage]')){const name=button.dataset.exploreStage||button.dataset.renderStage;button.setAttribute('aria-pressed',name===stage?'true':'false')}const note=document.getElementById('explore-stage-note'),meta=nav?.STAGES?.[stage];if(note&&meta?.note)note.textContent=meta.note;O.productUI?.announce?.((meta?.label||stage)+' view');return !!result}
function handleClick(event){const stageNode=event.target.closest?.('[data-render-stage],[data-explore-stage]');if(stageNode){const stage=stageNode.dataset.renderStage||stageNode.dataset.exploreStage;if(stage){event.preventDefault();event.stopPropagation();routeStage(stage,stageNode.hasAttribute('data-render-stage')?'stage-button':'explore-stage');return}}if(event.target.closest?.('[data-explore-action="approach"]')){event.preventDefault();event.stopPropagation();routeStage('approach','explore-approach')}}
function handleWheel(event){const P=preview();if(!P?.camera||!P.radius)return;event.preventDefault();event.stopImmediatePropagation();const sign=Math.sign(Number(event.deltaY));if(!sign)return;const current=currentDistanceRadii(),factor=Math.exp(sign*0.28),min=P.camera.minDistanceM/P.radius,next=clamp(current*factor,min,400);state.wheelCommands++;state.lastWheelDirection=sign>0?'out':'in';state.lastIntent='wheel';R.setContinuousDistance(next,{source:'wheel'})}
let drag=null;
function endPointer(event){if(event?.stopImmediatePropagation)event.stopImmediatePropagation();const node=canvas();drag=null;state.pointerActive=false;const P=preview();if(P)P.pointerActive=false;if(event&&node?.hasPointerCapture?.(event.pointerId))try{node.releasePointerCapture(event.pointerId)}catch{}}
function handlePointerDown(event){const P=preview(),node=canvas();if(!P?.camera||!node)return;event.stopImmediatePropagation();if(event.pointerType==='mouse'&&event.button!==0)return;node.focus({preventScroll:true});drag={id:event.pointerId,x:event.clientX,y:event.clientY,baseDirection:[...P.camera.targetDirection],kind:event.pointerType==='mouse'?'rotate':'pending'};state.pointerActive=true;P.pointerActive=true;if(event.pointerType==='mouse')try{node.setPointerCapture(event.pointerId)}catch{}}
function handlePointerMove(event){if(!drag||drag.id!==event.pointerId)return;event.stopImmediatePropagation();const node=canvas();if(!node)return;const dxPx=event.clientX-drag.x,dyPx=event.clientY-drag.y;if(drag.kind==='pending'){if(Math.hypot(dxPx,dyPx)<7)return;if(Math.abs(dyPx)>Math.abs(dxPx)*1.1){drag.kind='scroll';state.lastIntent='native-vertical-scroll';return}drag.kind='rotate';try{node.setPointerCapture(event.pointerId)}catch{}}if(drag.kind!=='rotate')return;if(event.cancelable&&event.pointerType!=='mouse')event.preventDefault();const dx=dxPx/Math.max(200,node.clientWidth),dy=dyPx/Math.max(200,node.clientHeight);state.pointerIntents++;state.lastIntent='pointer-drag';R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-drag',pointerType:event.pointerType,baseDirection:drag.baseDirection,dx,dy},{source:'pointer-drag'})}
function handleKeydown(event){const P=preview();if(!P?.camera)return;event.stopImmediatePropagation();let handled=true;if(event.key==='ArrowLeft')R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-step',dx:-.12,dy:0},{source:'keyboard'});else if(event.key==='ArrowRight')R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-step',dx:.12,dy:0},{source:'keyboard'});else if(event.key==='ArrowUp')R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-step',dx:0,dy:.12},{source:'keyboard'});else if(event.key==='ArrowDown')R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-step',dx:0,dy:-.12},{source:'keyboard'});else if(event.key==='+'||event.key==='=')R.setContinuousDistance(Math.max(P.camera.minDistanceM/P.radius,currentDistanceRadii()*.75),{source:'keyboard-zoom-in'});else if(event.key==='-'||event.key==='_')R.setContinuousDistance(Math.min(400,currentDistanceRadii()*1.35),{source:'keyboard-zoom-out'});else if(event.key==='Home'){R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'reset-direction'},{source:'keyboard-home'});routeStage('orbit','keyboard-home')}else handled=false;if(handled){state.keyboardIntents++;state.lastIntent='keyboard';event.preventDefault();event.stopPropagation()}}
function init(){if(state.initialized)return;const node=canvas();if(!node)return;state.initialized=true;if(!registerPlanetProvider()){const retry=()=>{if(state.providerReady)return;if(registerPlanetProvider())return;root.requestAnimationFrame?.(retry)};root.requestAnimationFrame?.(retry)}document.addEventListener('click',handleClick,true);node.addEventListener('wheel',handleWheel,{passive:false,capture:true});node.addEventListener('pointerdown',handlePointerDown,true);node.addEventListener('pointermove',handlePointerMove,{passive:false,capture:true});node.addEventListener('pointerup',endPointer,true);node.addEventListener('pointercancel',endPointer,true);node.addEventListener('lostpointercapture',()=>endPointer());node.addEventListener('keydown',handleKeydown,true);R.on('scaleChanged',event=>{const band=event.snapshot.semanticScale,nav=O.v08ExploreNavigation;if(nav?.state)nav.state.stage=band;for(const button of document.querySelectorAll('[data-explore-stage],[data-render-stage]')){const name=button.dataset.exploreStage||button.dataset.renderStage;button.setAttribute('aria-pressed',name===band?'true':'false')}})}
function snapshot(){return Object.freeze({...state,scale:R.snapshot()})}
const API=Object.freeze({VERSION,contract:INTENT_CONTRACT,state,snapshot,routeStage,init});O.waveIVInputRouter=API;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(typeof globalThis!=='undefined'?globalThis:this);
