(function(root){
'use strict';
const O=root.OFU=root.OFU||{};if(typeof document==='undefined')return;const R=O.waveIVScaleRuntime,C=O.planetRenderCore;if(!R||!C)throw new Error('Wave IV input router requires scale runtime and camera core');
const VERSION='ofu-wave-iv-input-router-6',INTENT_CONTRACT='ofu-wave-iv-input-intent-3',LOCAL_SURFACE=new Set(['regional_surface','local_surface','human']),MACRO=new Set(['galaxy','galactic_region','stellar_neighborhood','system']);
const state={version:VERSION,contract:INTENT_CONTRACT,initialized:false,providerReady:false,surfaceProviderReady:false,stageCommands:0,wheelCommands:0,pointerIntents:0,pinchIntents:0,keyboardIntents:0,viewportUpdates:0,lastIntent:null,lastStage:null,lastWheelDirection:null,pointerActive:false,activePointers:0,pointerCancels:0,lostPointerCaptures:0,pointerResets:0,lastGesture:'none',globalSurfaceRenderer:'planet-webgl',touchOwnedByApplication:true};
const canvas=()=>document.getElementById('planet-view'),preview=()=>root.__OFU_PLANET_PREVIEW__,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function settle(P){if(P?.camera&&P.reducedMotion){P.camera.distanceM=Math.max(P.camera.minDistanceM,P.camera.targetDistanceM);P.camera.direction=P.camera.targetDirection}}
function cameraTarget(P,{distanceRadii=null,direction=null}={}){if(!P?.camera||!P.radius)return false;C.setCameraTarget(P.camera,{distanceM:distanceRadii===null?P.camera.targetDistanceM:P.radius*Number(distanceRadii),direction:direction||P.camera.targetDirection});settle(P);return true}
function refreshPlanetAnchors(source='projection-framing'){const nav=O.v08ExploreNavigation,P=preview();if(!P?.radius)return false;for(const b of ['system','orbit','approach']){const f=nav?.framingFor?.(b);if(f&&Number(f.distanceM)>0)try{R.configureAnchor(b,f.distanceM/P.radius,{source})}catch{}}return true}
function registerProviders(){const P=preview(),node=canvas();if(!P?.camera||!P.radius||!node)return false;R.registerSceneProvider({id:'planet-webgl',scales:['orbit','approach','global_surface'],setActive(active,snap){node.dataset.scenePrimary=active?'true':'false';if(active&&snap?.semanticScale==='global_surface'&&P.surfaceMode==='LOCAL')P.leaveSurface?.()},setDistanceRadii(r){cameraTarget(P,{distanceRadii:r})},cameraIntent(intent){if(intent.kind==='rotate-drag'){const b=Array.isArray(intent.baseDirection)?intent.baseDirection:P.camera.targetDirection;cameraTarget(P,{direction:[b[0]+Number(intent.dx)*1.4,b[1]-Number(intent.dy)*1.4,b[2]]})}else if(intent.kind==='rotate-step'){const d=P.camera.targetDirection;cameraTarget(P,{direction:[d[0]+Number(intent.dx||0),d[1]+Number(intent.dy||0),d[2]]})}else if(intent.kind==='reset-direction')cameraTarget(P,{direction:[.18,.12,1]})}});state.providerReady=true;R.registerSceneProvider({id:'surface-webgl',scales:['regional_surface','local_surface','human'],setActive(active,snap){if(active){const band=String(snap.semanticScale).toUpperCase();const entered=P.surfaceMode==='LOCAL'?P.snapshot().surface:P.enterSurface(band);if(entered?.ready===false){O.productUI?.announce?.('Local solid-surface traversal is not available for this world.');root.queueMicrotask?.(()=>R.requestStage('approach',{source:'surface-unavailable'}));return}P.setSurfaceBand?.(band)}else if(P.surfaceMode==='LOCAL'){P.leaveSurface?.()}},cameraIntent(intent){if(P.surfaceMode!=='LOCAL')return;const map={move_forward:'MOVE_FORWARD',move_right:'MOVE_RIGHT',look_yaw:'LOOK_YAW',look_pitch:'LOOK_PITCH'};if(map[intent.kind])P.surfaceIntent?.({type:map[intent.kind],amount:Number(intent.amount)||1})}});state.surfaceProviderReady=true;refreshPlanetAnchors('provider-ready');R.requestStage(R.snapshot().semanticScale,{source:'provider-ready',transition:false});return true}
function routeStage(stage,source='stage-selection'){try{stage=R.normalizeBand(stage)}catch{return false}state.stageCommands++;state.lastStage=stage;state.lastIntent=source;const result=R.requestStage(stage,{source});for(const b of document.querySelectorAll('[data-wave-iv-scale]'))b.setAttribute('aria-pressed',b.dataset.waveIvScale===stage?'true':'false');return !!result}
function handleClick(e){const n=e.target.closest?.('[data-wave-iv-scale],[data-render-stage],[data-explore-stage]');if(!n)return;const stage=n.dataset.waveIvScale||n.dataset.renderStage||n.dataset.exploreStage;if(!stage)return;e.preventDefault();e.stopPropagation();routeStage(stage,'semantic-scale-control')}
function currentDistance(){const P=preview(),s=R.snapshot();if(MACRO.has(s.semanticScale)||s.semanticScale==='global_surface')return s.distanceIntentRadii;return P?.camera&&P.radius?P.camera.targetDistanceM/P.radius:s.distanceIntentRadii}
function surfaceAltitudeFactor(factor){const P=preview(),before=P?.snapshot?.().surface?.camera;if(!before)return false;const desired=Math.max(2,Math.min(250000,before.presentationAltitudeM*factor)),delta=(desired-before.presentationAltitudeM)/20;P.surfaceIntent?.({type:'CHANGE_ALTITUDE',amount:delta});const after=P.snapshot().surface?.camera,band=String(after?.currentBand||'REGIONAL_SURFACE').toLowerCase();if(LOCAL_SURFACE.has(band)&&band!==R.snapshot().semanticScale)R.requestStage(band,{source:'continuous-surface-band',transition:true,driveCamera:false});return true}
function surfaceWheel(sign){return surfaceAltitudeFactor(sign>0?1.45:.64)}
function handleWheel(e){const P=preview();if(!P?.camera||!P.radius)return;const delta=clamp(Number(e.deltaY),-180,180);if(!delta)return;e.preventDefault();e.stopImmediatePropagation();state.wheelCommands++;state.lastWheelDirection=delta>0?'out':'in';state.lastIntent='wheel';const scale=R.snapshot().semanticScale;if(LOCAL_SURFACE.has(scale)||P.surfaceMode==='LOCAL'){surfaceAltitudeFactor(Math.exp(delta*.0036));return}const next=clamp(currentDistance()*Math.exp(delta*.0042),R.DEFAULT_ANCHORS.human*.96,R.DEFAULT_ANCHORS.galaxy*1.08);R.setContinuousDistance(next,{source:scale==='global_surface'?'wheel-global-handoff':'wheel-planet'})}
const pointers=new Map();let gesture=null;
function pointerDistance(){const a=[...pointers.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}
function setPointerState(){state.activePointers=pointers.size;state.pointerActive=pointers.size>0;const P=preview();if(P)P.pointerActive=pointers.size>0}
function startSingle(id,p,P){gesture={kind:'single',id,x:p.x,y:p.y,base:[...P.camera.targetDirection]}}
function beginPinch(){gesture={kind:'pinch',lastDistance:Math.max(1,pointerDistance())}}
function applyPinch(ratio){if(!Number.isFinite(ratio)||ratio<=0)return;const P=preview(),scale=R.snapshot().semanticScale;if(LOCAL_SURFACE.has(scale)||P?.surfaceMode==='LOCAL')surfaceAltitudeFactor(Math.pow(ratio,-1.65));else{const next=clamp(currentDistance()*Math.pow(ratio,-2.25),R.DEFAULT_ANCHORS.human*.96,R.DEFAULT_ANCHORS.galaxy*1.08);R.setContinuousDistance(next,{source:'pinch-planet'})}state.pinchIntents++;state.lastIntent='pinch'}
function down(e){const P=preview(),n=canvas();if(!P?.camera||!n||MACRO.has(R.snapshot().semanticScale))return;if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();n.focus({preventScroll:true});pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,type:e.pointerType});state.lastGesture='canvas-'+e.pointerType;setPointerState();try{n.setPointerCapture(e.pointerId)}catch{}if(pointers.size===1)startSingle(e.pointerId,pointers.get(e.pointerId),P);else if(pointers.size===2)beginPinch()}
function move(e){if(!pointers.has(e.pointerId))return;const n=canvas(),P=preview(),old=pointers.get(e.pointerId);pointers.set(e.pointerId,{...old,x:e.clientX,y:e.clientY});if(e.cancelable)e.preventDefault();e.stopImmediatePropagation();if(pointers.size>=2){const d=Math.max(1,pointerDistance());if(gesture?.kind!=='pinch')beginPinch();else{const ratio=d/Math.max(1,gesture.lastDistance);if(Math.abs(ratio-1)>.003){applyPinch(ratio);if(gesture?.kind==='pinch')gesture.lastDistance=d}}return}if(gesture?.kind!=='single'||gesture.id!==e.pointerId)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)<1)return;state.pointerIntents++;if(LOCAL_SURFACE.has(R.snapshot().semanticScale)||P.surfaceMode==='LOCAL'){P.surfaceIntent?.({type:'LOOK_YAW',amount:dx/Math.max(80,n.clientWidth)*8});P.surfaceIntent?.({type:'LOOK_PITCH',amount:-dy/Math.max(80,n.clientHeight)*8});gesture.x=e.clientX;gesture.y=e.clientY}else R.dispatchCameraIntent({contract:INTENT_CONTRACT,kind:'rotate-drag',pointerType:e.pointerType,baseDirection:gesture.base,dx:(e.clientX-gesture.x)/Math.max(200,n.clientWidth),dy:(e.clientY-gesture.y)/Math.max(200,n.clientHeight)},{source:'pointer-drag'})}
function endPointer(e){const n=canvas();if(e.type==='lostpointercapture')e.stopImmediatePropagation();if(pointers.has(e.pointerId)){e.stopImmediatePropagation();pointers.delete(e.pointerId);if(e.type==='pointercancel'){state.pointerCancels++;state.lastGesture='canvas-pointercancel'}else if(e.type==='lostpointercapture'){state.lostPointerCaptures++;state.lastGesture='canvas-lostpointercapture'}}if(n?.hasPointerCapture?.(e.pointerId))try{n.releasePointerCapture(e.pointerId)}catch{}setPointerState();if(pointers.size===1){const [id,p]=pointers.entries().next().value;startSingle(id,p,preview())}else if(pointers.size===0)gesture=null;else beginPinch()}
function clearPointers(reason){if(!pointers.size)return;const n=canvas(),ids=[...pointers.keys()];pointers.clear();gesture=null;state.pointerResets++;state.lastGesture='canvas-'+reason;setPointerState();for(const id of ids)if(n?.hasPointerCapture?.(id))try{n.releasePointerCapture(id)}catch{}}
function key(e){const P=preview();if(!P?.camera)return;const scale=R.snapshot().semanticScale;if(MACRO.has(scale))return;let handled=true;if(LOCAL_SURFACE.has(scale)){if(e.key==='ArrowLeft')P.surfaceIntent?.({type:'LOOK_YAW',amount:-1});else if(e.key==='ArrowRight')P.surfaceIntent?.({type:'LOOK_YAW',amount:1});else if(e.key==='ArrowUp')P.surfaceIntent?.({type:'LOOK_PITCH',amount:1});else if(e.key==='ArrowDown')P.surfaceIntent?.({type:'LOOK_PITCH',amount:-1});else if(e.key==='w'||e.key==='W')P.surfaceIntent?.({type:'MOVE_FORWARD',amount:1});else if(e.key==='s'||e.key==='S')P.surfaceIntent?.({type:'MOVE_FORWARD',amount:-1});else if(e.key==='a'||e.key==='A')P.surfaceIntent?.({type:'MOVE_RIGHT',amount:-1});else if(e.key==='d'||e.key==='D')P.surfaceIntent?.({type:'MOVE_RIGHT',amount:1});else if(e.key==='+'||e.key==='=')surfaceWheel(-1);else if(e.key==='-'||e.key==='_')surfaceWheel(1);else if(e.key==='Home'){P.leaveSurface?.();R.requestStage('global_surface',{source:'keyboard-reverse'})}else handled=false}else if(e.key==='ArrowLeft')R.dispatchCameraIntent({kind:'rotate-step',dx:-.12,dy:0},{source:'keyboard'});else if(e.key==='ArrowRight')R.dispatchCameraIntent({kind:'rotate-step',dx:.12,dy:0},{source:'keyboard'});else if(e.key==='ArrowUp')R.dispatchCameraIntent({kind:'rotate-step',dx:0,dy:.12},{source:'keyboard'});else if(e.key==='ArrowDown')R.dispatchCameraIntent({kind:'rotate-step',dx:0,dy:-.12},{source:'keyboard'});else if(e.key==='+'||e.key==='=')R.stepTravel(-1,{source:'keyboard-zoom-in'});else if(e.key==='-'||e.key==='_')R.stepTravel(1,{source:'keyboard-zoom-out'});else if(e.key==='Home'){R.dispatchCameraIntent({kind:'reset-direction'},{source:'keyboard-home'});routeStage('orbit','keyboard-home')}else handled=false;if(handled){state.keyboardIntents++;e.preventDefault();e.stopImmediatePropagation()}}
function viewport(){const n=canvas(),r=n?.getBoundingClientRect?.();if(!r)return;state.viewportUpdates++;R.viewportChanged({width:r.width,height:r.height,devicePixelRatio:Number(root.devicePixelRatio)||1},{source:'resize'});refreshPlanetAnchors('resize')}
function init(){if(state.initialized)return;const n=canvas();if(!n)return;state.initialized=true;n.dataset.ofuTouchOwner='wave-iv-input-router';n.style.touchAction='none';n.style.overscrollBehavior='contain';if(!registerProviders()){const retry=()=>{if(state.providerReady&&state.surfaceProviderReady)return;if(registerProviders())return;root.requestAnimationFrame?.(retry)};root.requestAnimationFrame?.(retry)}document.addEventListener('click',handleClick,true);n.addEventListener('wheel',handleWheel,{passive:false,capture:true});n.addEventListener('pointerdown',down,{passive:false,capture:true});n.addEventListener('pointermove',move,{passive:false,capture:true});n.addEventListener('pointerup',endPointer,{passive:false,capture:true});n.addEventListener('pointercancel',endPointer,{passive:false,capture:true});n.addEventListener('lostpointercapture',endPointer,{capture:true});root.addEventListener?.('blur',()=>clearPointers('blur'));document.addEventListener('visibilitychange',()=>{if(document.hidden)clearPointers('hidden')});R.on('selectionChanged',()=>clearPointers('selection-change'));R.on('sceneChanged',()=>clearPointers('scene-change'));n.addEventListener('keydown',key,true);R.on('scaleChanged',e=>{for(const b of document.querySelectorAll('[data-wave-iv-scale]'))b.setAttribute('aria-pressed',b.dataset.waveIvScale===e.snapshot.semanticScale?'true':'false')});if(typeof ResizeObserver==='function'){const ro=new ResizeObserver(viewport);ro.observe(n);state.resizeObserver=ro}else root.addEventListener?.('resize',viewport,{passive:true})}
const snapshot=()=>Object.freeze({...state,scale:R.snapshot()});O.waveIVInputRouter=Object.freeze({VERSION,contract:INTENT_CONTRACT,state,snapshot,routeStage,refreshPlanetAnchors,init});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(typeof globalThis!=='undefined'?globalThis:this);
