(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
if(typeof document==='undefined')return;
const q=id=>document.getElementById(id);
const hex=v=>v&&O.p2?.hex?O.p2.hex(v):null;
const text=(id,value)=>{const n=q(id);if(n)n.textContent=value==null?'pending':String(value)};
const clear=id=>{const n=q(id);if(n)n.textContent=''};
const fact=(label,value)=>{const wrap=document.createElement('div');wrap.className='fact';const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=String(value);wrap.append(dt,dd);return wrap};
const setFacts=(id,items)=>{const n=q(id);if(!n)return;n.textContent='';for(const [label,value] of items)if(value!==null&&value!==undefined&&value!=='')n.append(fact(label,value))};
const safeNumber=v=>typeof v==='bigint'&&v>=BigInt(Number.MIN_SAFE_INTEGER)&&v<=BigInt(Number.MAX_SAFE_INTEGER)?Number(v):null;
const fixed=(v,scale,digits=2)=>{const n=safeNumber(v);return n===null?null:(n/scale).toFixed(digits)};
const titleType=t=>({PLANET:'Planet',SYSTEM:'Star system',STAR:'Star',MOON:'Moon',SECTOR:'Sector',GALAXY:'Galaxy',REGION:'Region'})[t]||t||'Canonical object';
const p6Copy=Object.freeze({
 INSUFFICIENT_ENVIRONMENT:{primary:'We cannot currently make a canonical biosphere assessment because the required environmental basis has not been established.',limit:'The environment model leaves required upstream conditions unknown or unsupported. This does not mean dead, sterile, lifeless, or uninhabitable.'},
 UNSUPPORTED_ENVIRONMENT:{primary:'This environment is outside the semantics currently supported by the canonical biology model.',limit:'No biological conclusion follows from an unsupported environment. Unsupported is distinct from absent or lifeless.'},
 NO_BIOSPHERE:{primary:'The canonical inputs are sufficient and supported, but no canonical biosphere is established by the current model.',limit:'This state is a model conclusion, not a claim that every possible form of life is physically impossible.'},
 BIOSPHERE_SUPPORTED:{primary:'The canonical model establishes that biosphere preconditions are satisfied.',limit:'This state must come from a versioned canonical path; presentation cannot manufacture it.'}
});
const unsupportedReason=reason=>{
 const r=String(reason||'UNSUPPORTED').replace(/^P5_/,'');
 if(r==='MASS_DOMAIN')return 'This target cannot currently be evaluated by the canonical physical/environment model because its mass lies outside the promoted domain.';
 if(r==='BULK_PRIOR')return 'This target cannot currently be evaluated by the canonical physical/environment model because its bulk class is outside the promoted terrestrial model.';
 if(r==='P3_ABSENT')return 'No canonical target exists at this address.';
 return 'This target cannot currently be evaluated by the canonical environment model.';
};
function currentView(){
 const I=O.inspectorTest?.state?.current||null,P=root.__OFU_PLANET_PREVIEW__||null,raw=q('entity-output')?.textContent||'';
 const invalid=/^(?:ERROR:|FAIL:|ABSENT|Input error:)/.test(raw.trim());
 if(!I||invalid)return{entity:null,preview:P,matched:false,invalid};
 const entity=I.r||null,planetMatch=I.type==='Planet'&&P?.chosen?.key&&I.key&&['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot'].every(k=>BigInt(P.chosen.key[k])===BigInt(I.key[k]));
 return{entity:{...I,r:entity},preview:P,matched:!!planetMatch,invalid:false};
}
function renderEmpty(){
 text('inspector-object-title','No resolved object');text('inspector-object-status','not resolved');text('inspector-object-type','pending');text('inspector-overview-copy','Resolve a canonical object to inspect its scientific context.');text('inspector-location-copy','No resolved location context.');text('inspector-physical-state','not evaluated');text('inspector-physical-copy','No canonical physical assessment is active.');text('inspector-environment-state','not evaluated');text('inspector-environment-copy','No canonical environment assessment is active.');text('inspector-biology-copy','No canonical biology assessment is active.');text('inspector-biology-limit','Resolve a supported planet before interpreting a biological state.');text('inspector-biology-state','not evaluated');text('inspector-biology-established','not established');text('inspector-evidence-copy','No current canonical target is available for evidence summary.');setFacts('inspector-orbit-facts',[]);setFacts('inspector-physical-facts',[]);setFacts('inspector-environment-summary',[]);setFacts('inspector-environment-statuses',[]);setFacts('inspector-evidence-facts',[]);
}
function renderGeneric(I){
 const r=I.r,type=titleType(r?.entityType||I.type?.toUpperCase());text('inspector-object-title',type);text('inspector-object-status','canonical');text('inspector-object-type',type);text('inspector-overview-copy',`This is a resolved canonical ${type.toLowerCase()} from the P3 astronomy model.`);text('inspector-location-copy',O.productUI?.keyLabel?O.productUI.keyLabel(I.type,I.key):'Canonical sparse address resolved.');
 const items=[];for(const [k,v] of Object.entries(r?.facts||{}).slice(0,6))items.push([humanKey(k),formatValue(k,v)]);setFacts('inspector-orbit-facts',items);text('inspector-physical-state','not applicable here');text('inspector-physical-copy','The promoted P5 physical/environment model is evaluated in Inspector only for supported canonical planets.');setFacts('inspector-physical-facts',[]);text('inspector-environment-state','not evaluated');text('inspector-environment-copy','Environment is not evaluated for this object type.');setFacts('inspector-environment-summary',[]);setFacts('inspector-environment-statuses',[]);text('inspector-biology-copy','Biology is not evaluated for this object type.');text('inspector-biology-limit','No biological conclusion is implied.');text('inspector-biology-state','NOT_EVALUATED');text('inspector-biology-established','not evaluated');text('inspector-evidence-copy','Canonical identity and facts are available. P5/P6 scientific interpretation applies only where their promoted contracts support the target.');setFacts('inspector-evidence-facts',[]);technical(I,null,false);
}
function humanKey(k){return ({baselineSemiMajorAxisMicroAu:'Semi-major axis',baselineEccentricityPpm:'Orbital eccentricity',baselineInclinationMilliDeg:'Orbital inclination',baselineMassMilliEarth:'Baseline mass',baselineInsolationPpm:'Stellar forcing',moonCount:'Moons',orbitCenter:'Orbit center',baselineAgeMyr:'Baseline age',baselineMetallicityMilliDex:'Metallicity',stellarComponentCount:'Stars',planetCount:'Planets',baselineEvolutionaryClass:'Evolutionary class',baselineTemperatureK:'Effective temperature',baselineLuminosityMilliSolar:'Luminosity'})[k]||k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());}
function formatValue(k,v){if(typeof v!=='bigint')return Array.isArray(v)?v.join(', '):String(v);if(k==='baselineSemiMajorAxisMicroAu')return `${fixed(v,1e6,3)} AU`;if(k==='baselineMassMilliEarth')return `${fixed(v,1000,3)} M⊕`;if(k==='baselineInsolationPpm')return `${fixed(v,1e6,3)} × Earth`;if(k==='baselineEccentricityPpm')return fixed(v,1e6,4);if(k==='baselineInclinationMilliDeg')return `${fixed(v,1000,3)}°`;if(k==='baselineAgeMyr')return `${fixed(v,1000,3)} Gyr`;if(k==='baselineTemperatureK')return `${v} K`;if(k==='baselineLuminosityMilliSolar')return `${fixed(v,1000,3)} L☉`;return String(v);}
function renderUnsupported(I,P){
 const reason=P?.targetReason||'UNSUPPORTED',copy=unsupportedReason(reason);text('inspector-object-title','Planet');text('inspector-object-status','canonical · model-limited');text('inspector-object-type','Planet');text('inspector-overview-copy','This planet is canonically resolved, but the promoted P5 realization cannot evaluate it within its supported domain.');text('inspector-location-copy',O.productUI?.keyLabel?O.productUI.keyLabel('Planet',I.key):'Canonical planet orbit resolved.');setFacts('inspector-orbit-facts',planetOrbitFacts(I.r));text('inspector-physical-state','outside current model');text('inspector-physical-copy',copy);setFacts('inspector-physical-facts',[['Canonical P3 baseline mass',formatValue('baselineMassMilliEarth',I.r.facts.baselineMassMilliEarth)],['Bulk class',I.r.facts.bulkPriorClass]]);text('inspector-environment-state','unsupported');text('inspector-environment-copy','This target cannot currently be evaluated by the canonical environment model.');setFacts('inspector-environment-summary',[['Why evaluation stops',copy]]);setFacts('inspector-environment-statuses',[['Technical target state','UNSUPPORTED'],['Technical reason',String(reason)]]);text('inspector-biology-copy','No canonical biosphere assessment is made because the required supported environment projection is unavailable for this target.');text('inspector-biology-limit','Unsupported target evaluation is distinct from dead, sterile, lifeless, uninhabitable, or absent.');text('inspector-biology-state','NOT_EVALUATED');text('inspector-biology-established','not evaluated');text('inspector-evidence-copy','P3 identity/orbit facts remain canonical. The conclusion stops at the P5 support boundary rather than inventing downstream environment or biology.');setFacts('inspector-evidence-facts',[['P3 astronomy','canonical'],['P5 target evaluation','unsupported'],['P6 biology','not evaluated']]);technical(I,P,true);
}
function planetOrbitFacts(r){const f=r?.facts||{};return[['Orbit',formatValue('baselineSemiMajorAxisMicroAu',f.baselineSemiMajorAxisMicroAu)],['Eccentricity',formatValue('baselineEccentricityPpm',f.baselineEccentricityPpm)],['Inclination',formatValue('baselineInclinationMilliDeg',f.baselineInclinationMilliDeg)],['Orbit center',f.orbitCenter],['Moons',f.moonCount]];}
function renderPlanet(I,P){
 const physical=P.physical,env=P.environment,p6=P.eligibility,biology=P.biology,f=I.r.facts;text('inspector-object-title','Planet');text('inspector-object-status','canonical · supported');text('inspector-object-type','Planet');text('inspector-overview-copy','A canonically resolved planet with a supported P5 terrestrial physical realization. Scientific claims below preserve the authority and limits of the promoted models.');text('inspector-location-copy',`This planet occupies orbit slot ${String(I.key.orbitSlot)} in its canonical star system.`);setFacts('inspector-orbit-facts',planetOrbitFacts(I.r));text('inspector-physical-state','supported');text('inspector-physical-copy','P5 derives a bounded terrestrial physical state from the immutable P3 baseline.');setFacts('inspector-physical-facts',[['Baseline mass',formatValue('baselineMassMilliEarth',f.baselineMassMilliEarth)],['Mean radius',`${physical.physical.meanRadiusM} m`],['Surface gravity',`${fixed(physical.physical.surfaceGravityMicroMs2,1e6,4)} m/s²`],['Mean density',`${physical.physical.meanDensityKgM3} kg/m³`],['Bulk class',physical.upstreamBaseline.formation.bulkPriorClass]]);
 const atmosphere=env.atmosphere,pressure=env.pressure,rad=env.radiativeTier0;text('inspector-environment-state',env.authority==='P5_CANONICAL'?'canonical · limited':'limited');text('inspector-environment-copy','The canonical environment model establishes authority and some upstream forcing, while deliberately leaving atmosphere genesis, pressure and climate conclusions unresolved where science is not promoted.');setFacts('inspector-environment-summary',[['Stellar forcing',`${fixed(rad.insolation.valuePpm,1e6,3)} × Earth`],['Atmosphere inventory',statusLabel(atmosphere.epistemicStatus)],['Global surface pressure',statusLabel(pressure.epistemicStatus)],['Bond albedo',statusLabel(rad.bondAlbedo.epistemicStatus)],['Mean surface temperature',statusLabel(rad.surfaceTemperature.epistemicStatus)],['Water phase',statusLabel(env.waterPhase.epistemicStatus)]]);setFacts('inspector-environment-statuses',[['Atmosphere',atmosphere.epistemicStatus],['Atmosphere provenance',atmosphere.provenance],['Pressure',pressure.epistemicStatus],['Pressure provenance',pressure.provenance],['Bond albedo',rad.bondAlbedo.epistemicStatus],['Surface temperature',rad.surfaceTemperature.epistemicStatus],['Greenhouse response',rad.greenhouseResponse.epistemicStatus],['Water phase',env.waterPhase.epistemicStatus],['XUV evolution',env.xuvEvolution.epistemicStatus],['Geological activity',env.geologicalActivity.epistemicStatus],['Geochemical energy',env.geochemicalEnergyAvailability.epistemicStatus]]);text('inspector-environment-authority',`${env.authority} · ${env.contractId}`);
 const pc=p6Copy[p6.state]||{primary:`Canonical biology state: ${p6.state}.`,limit:'No stronger biological conclusion is added by presentation.'};text('inspector-biology-copy',pc.primary);text('inspector-biology-limit',pc.limit);text('inspector-biology-state',p6.state);text('inspector-biology-established',biology?.biologyEstablished===true?'yes':'no');text('inspector-evidence-copy','The object identity and orbit are P3 canonical; physical state is P5 canonical/derived within its domain; environment fields carry explicit epistemic states; P6 preserves those upstream limits through its eligibility witness.');setFacts('inspector-evidence-facts',[['P3 planet occurrence',O.p3Astronomy?.EVIDENCE?.planetOccurrence?.evidenceClass||'canonical source'],['P3 bulk prior',O.p3Astronomy?.EVIDENCE?.planetBulkPrior?.evidenceClass||'canonical source'],['P5 mass/radius',physical.evidence?.massRadius?`${physical.evidence.massRadius.evidenceClass} · ${physical.evidence.massRadius.modelFidelity}`:null],['P5 gravity/density',physical.evidence?.gravityDensity?`${physical.evidence.gravityDensity.evidenceClass} · ${physical.evidence.gravityDensity.modelFidelity}`:null],['Environment atmosphere genesis',env.evidence?.volatileGenesis?`${env.evidence.volatileGenesis.evidenceClass} · ${env.evidence.volatileGenesis.modelFidelity}`:null],['Environment radiative Tier 0',env.evidence?.radiativeTier0?`${env.evidence.radiativeTier0.evidenceClass} · ${env.evidence.radiativeTier0.modelFidelity}`:null]]);technical(I,P,true);
}
function statusLabel(s){return ({KNOWN:'Known',DERIVED:'Derived',HYPOTHETICAL_MODEL_VALUE:'Model hypothesis',UNKNOWN:'Not established',UNSUPPORTED:'Outside current model'})[s]||String(s||'not evaluated');}
function technical(I,P,isPlanet){text('inspector-tech-target-state',isPlanet?(P?.targetStatus||'NOT_EVALUATED'):'NOT_EVALUATED');text('inspector-tech-target-reason',isPlanet?(P?.targetReason||'none'):'not applicable');text('inspector-tech-environment-authority',isPlanet&&P?.environment?.authority?P.environment.authority:'not evaluated');text('inspector-tech-environment-contract',isPlanet&&P?.environment?.contractId?P.environment.contractId:'not evaluated');text('inspector-tech-p6-state',isPlanet&&P?.eligibility?.state?P.eligibility.state:'NOT_EVALUATED');text('inspector-tech-p6-witness',isPlanet&&P?.eligibility?.witnessDigest?hex(P.eligibility.witnessDigest):'not evaluated');}
function render(){const v=currentView();if(!v.entity){renderEmpty();return}const I=v.entity,P=v.preview;if(I.type!=='Planet'){renderGeneric(I);return}if(!v.matched){text('inspector-overview-copy','The canonical planet selection is changing. Scientific presentation is withheld until the renderer/environment adapter matches this exact target.');text('inspector-object-title','Planet');text('inspector-object-status','synchronizing');text('inspector-object-type','Planet');text('inspector-location-copy',O.productUI?.keyLabel?O.productUI.keyLabel('Planet',I.key):'Canonical planet');setFacts('inspector-orbit-facts',planetOrbitFacts(I.r));text('inspector-physical-state','pending exact target match');text('inspector-physical-copy','Withholding P5/P6 presentation to avoid stale-target scientific state.');setFacts('inspector-physical-facts',[]);text('inspector-environment-state','pending');text('inspector-environment-copy','Waiting for the exact canonical target to match.');setFacts('inspector-environment-summary',[]);setFacts('inspector-environment-statuses',[]);text('inspector-biology-copy','Waiting for the exact canonical target to match before presenting a biology state.');text('inspector-biology-limit','No stale target state is shown.');text('inspector-biology-state','PENDING_TARGET_MATCH');text('inspector-biology-established','not evaluated');text('inspector-evidence-copy','Exact-target synchronization is required before downstream scientific presentation.');setFacts('inspector-evidence-facts',[]);technical(I,null,true);return}if(P.targetStatus==='UNSUPPORTED'){renderUnsupported(I,P);return}if(P.targetStatus==='SUPPORTED'&&P.physical&&P.environment&&P.eligibility){renderPlanet(I,P);return}renderEmpty();}
function init(){let stamp='';const tick=()=>{const I=O.inspectorTest?.state?.current,P=root.__OFU_PLANET_PREVIEW__,raw=q('entity-output')?.textContent||'';const s=JSON.stringify({id:I?.r?.id?hex(I.r.id):null,type:I?.type||null,key:I?.key?Object.fromEntries(Object.entries(I.key).map(([k,v])=>[k,String(v)])):null,target:P?.targetStatus||null,reason:P?.targetReason||null,planet:P?.provider?.planetId||P?.chosen?.planetId||null,p6:P?.eligibility?.state||null,raw:raw.slice(0,24)});if(s!==stamp){stamp=s;render()}};setInterval(tick,200);tick();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
O.v08InspectorProduct=Object.freeze({seamVersion:2,statusLabel,p6Copy,unsupportedReason,render});
})(typeof globalThis!=='undefined'?globalThis:this);
