(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-wave-iv-scale-runtime-3';
const SCENE_PROVIDER_CONTRACT='ofu-wave-iv-scene-provider-1',RENDERER_LIFECYCLE_CONTRACT='ofu-wave-iv-renderer-lifecycle-2',TRANSITION_CONTRACT='ofu-wave-iv-transition-2',SELECTION_CONTRACT='ofu-wave-iv-selection-1';
const LADDER=Object.freeze(['galaxy','stellar_neighborhood','system','orbit','approach','global_surface','regional_surface','local_surface','human']);
const CURRENT_BANDS=LADDER;
const FUTURE_LADDER=LADDER;
const CLOSE_ALIAS='human';
const DEFAULT_ANCHORS=Object.freeze({galaxy:1e12,stellar_neighborhood:1e7,system:180,orbit:4,approach:1.35,global_surface:2.16,regional_surface:1.006,local_surface:1.0007,human:1.00008,close:1.00008});
const PLANET_FIELDS=Object.freeze(['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot']),SYSTEM_FIELDS=Object.freeze(PLANET_FIELDS.slice(0,-1));
const listeners=new Map(),providers=new Map();let sequence=0,transitionSequence=0;
const state={version:VERSION,semanticScale:'system',distanceIntentRadii:DEFAULT_ANCHORS.system,intentKind:'anchor',selectedCanonicalTarget:null,activeSceneProvider:'wave-iv-macro',transition:null,cameraIntent:null,userNavigationSource:'bootstrap',lastStableState:null,anchors:{...DEFAULT_ANCHORS},commandCount:0,cameraCommandCount:0,scaleChanges:0,sceneChanges:0,selectionChanges:0,viewportChanges:0,rendererReady:0,lastEvent:null,hysteresisFraction:.07};
function finitePositive(v,label='value'){const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new TypeError(label+' must be positive finite');return n}
function normalizeBand(v){let b=String(v||'').toLowerCase();if(b==='neighborhood')b='stellar_neighborhood';if(b==='surface')b='global_surface';if(b==='close')b=CLOSE_ALIAS;if(!LADDER.includes(b))throw new Error('unsupported semantic scale: '+b);return b}
function copyKey(key,fields=PLANET_FIELDS){if(!key)return null;return Object.freeze(Object.fromEntries(fields.map(k=>[k,BigInt(key[k])])))}
function publicSelection(s){return s?Object.freeze({canonicalKey:s.canonicalKey,canonicalSystemKey:s.canonicalSystemKey,orbitIndex:s.orbitIndex,planetId:s.planetId||null,presentationStatus:s.presentationStatus||null}):null}
function defaultProviderForScale(b){if(['galaxy','stellar_neighborhood','system'].includes(b))return'wave-iv-macro';if(['orbit','approach','global_surface'].includes(b))return'planet-webgl';return'surface-webgl'}
function providerSupports(p,b){return !!p&&Array.isArray(p.scales)&&p.scales.includes(b)}
function sceneForBand(b){for(const p of providers.values())if(providerSupports(p,b))return p.id;return defaultProviderForScale(b)}
function snapshot(){return Object.freeze({version:VERSION,contract:VERSION,selectionContract:SELECTION_CONTRACT,sceneProviderContract:SCENE_PROVIDER_CONTRACT,rendererLifecycleContract:RENDERER_LIFECYCLE_CONTRACT,transitionContract:TRANSITION_CONTRACT,currentBands:CURRENT_BANDS,futureLadder:FUTURE_LADDER,compatibilityCloseBand:true,semanticScale:state.semanticScale,distanceIntentRadii:state.distanceIntentRadii,intentKind:state.intentKind,selectedCanonicalTarget:publicSelection(state.selectedCanonicalTarget),activeSceneProvider:state.activeSceneProvider,transition:state.transition,cameraIntent:state.cameraIntent,userNavigationSource:state.userNavigationSource,lastStableState:state.lastStableState,anchors:Object.freeze({...state.anchors}),commandCount:state.commandCount,cameraCommandCount:state.cameraCommandCount,scaleChanges:state.scaleChanges,sceneChanges:state.sceneChanges,selectionChanges:state.selectionChanges,viewportChanges:state.viewportChanges,rendererReady:state.rendererReady,lastEvent:state.lastEvent,hysteresisFraction:state.hysteresisFraction})}
function on(type,fn){if(typeof fn!=='function')throw new TypeError('handler required');const k=String(type);if(!listeners.has(k))listeners.set(k,new Set());listeners.get(k).add(fn);return()=>listeners.get(k)?.delete(fn)}
function emit(type,detail={}){const e=Object.freeze({type:String(type),sequence:++sequence,detail:Object.freeze({...detail}),snapshot:snapshot()});state.lastEvent=Object.freeze({type:e.type,sequence:e.sequence});for(const fn of listeners.get(e.type)||[])fn(e);for(const fn of listeners.get('*')||[])fn(e);return e}
function thresholds(anchors=state.anchors){const out=[];for(let i=0;i<LADDER.length-1;i++){const a=finitePositive(anchors[LADDER[i]],LADDER[i]),b=finitePositive(anchors[LADDER[i+1]],LADDER[i+1]);if(!(a>b))throw new Error('scale anchors must be strictly descending');out.push(Math.sqrt(a*b))}return out}
function deriveSemanticScale(distanceRadii,anchors=state.anchors,{previous=state.semanticScale,hysteresis=state.hysteresisFraction}={}){const d=finitePositive(distanceRadii,'distance radii'),ts=thresholds(anchors);let idx=LADDER.length-1;for(let i=0;i<ts.length;i++)if(d>=ts[i]){idx=i;break}const prev=LADDER.indexOf(normalizeBand(previous));if(prev>=0&&Math.abs(idx-prev)===1){const boundary=ts[Math.min(idx,prev)],lo=boundary*(1-hysteresis),hi=boundary*(1+hysteresis);if(d>lo&&d<hi)return LADDER[prev]}return LADDER[idx]}
function applyProviderOwnership(next,prev){if(prev&&prev!==next)try{providers.get(prev)?.setActive?.(false,snapshot())}catch{};if(next)try{providers.get(next)?.setActive?.(true,snapshot())}catch{}}
function setActiveSceneForScale(b,source){const next=sceneForBand(b),prev=state.activeSceneProvider;if(next===prev)return;state.activeSceneProvider=next;state.sceneChanges++;applyProviderOwnership(next,prev);emit('sceneChanged',{previous:prev,next,semanticScale:b,source})}
function setSelection(key,{planetId=null,presentationStatus=null,source='selection'}={}){const canonicalKey=copyKey(key),canonicalSystemKey=copyKey(key,SYSTEM_FIELDS),orbitIndex=Number(canonicalKey.orbitSlot),previous=state.selectedCanonicalTarget;state.selectedCanonicalTarget=Object.freeze({canonicalKey,canonicalSystemKey,orbitIndex,planetId,presentationStatus});state.selectionChanges++;state.userNavigationSource=source;emit('selectionChanged',{previous:publicSelection(previous),next:publicSelection(state.selectedCanonicalTarget),source});return snapshot()}
function configureAnchor(band,distanceRadii,{source='framing'}={}){band=String(band).toLowerCase()==='close'?'human':normalizeBand(band);const next={...state.anchors,[band]:finitePositive(distanceRadii,band+' anchor')};next.close=next.human;thresholds(next);state.anchors=next;emit('scaleAnchorsChanged',{band,distanceRadii:next[band],source});return snapshot()}
function driveDistance(distance,source,band){const p=providers.get(state.activeSceneProvider);if(p?.setDistanceRadii&&['orbit','approach','global_surface'].includes(band)){p.setDistanceRadii(distance,{source});state.cameraCommandCount++;return true}return false}
function commitScale({distanceRadii,semanticScale,intentKind,source,transition=true,driveCamera=true}){const distance=finitePositive(distanceRadii,'distance radii'),band=normalizeBand(semanticScale),prevBand=state.semanticScale,prevDist=state.distanceIntentRadii,prevScene=state.activeSceneProvider;state.commandCount++;state.distanceIntentRadii=distance;state.semanticScale=band;state.intentKind=intentKind;state.userNavigationSource=source;if(prevBand!==band&&transition){state.transition=Object.freeze({contract:TRANSITION_CONTRACT,id:++transitionSequence,from:prevBand,to:band,source,phase:'HANDOFF',startedSequence:sequence+1});emit('transitionChanged',{transition:state.transition})}else if(prevBand===band)state.transition=null;setActiveSceneForScale(band,source);if(driveCamera)driveDistance(distance,source,band);state.lastStableState=Object.freeze({semanticScale:band,distanceIntentRadii:distance,activeSceneProvider:state.activeSceneProvider,source});if(prevBand!==band||Math.abs(prevDist-distance)>Number.EPSILON){state.scaleChanges++;emit('scaleChanged',{previousSemanticScale:prevBand,semanticScale:band,previousDistanceRadii:prevDist,distanceRadii:distance,intentKind,source,sceneChanged:prevScene!==state.activeSceneProvider})}return snapshot()}
function requestStage(band,{source='stage-selection',transition=true,driveCamera=true}={}){band=normalizeBand(band);return commitScale({distanceRadii:state.anchors[band],semanticScale:band,intentKind:'anchor',source,transition,driveCamera})}
function setContinuousDistance(distanceRadii,{source='continuous-scale',driveCamera=true}={}){const d=finitePositive(distanceRadii,'distance radii'),band=deriveSemanticScale(d);return commitScale({distanceRadii:d,semanticScale:band,intentKind:'continuous',source,transition:true,driveCamera})}
function stepTravel(direction,{source='continuous-step'}={}){const dir=Math.sign(Number(direction));if(!dir)return snapshot();const i=LADDER.indexOf(state.semanticScale),span=dir>0?1.42:.7042253521,next=Math.max(DEFAULT_ANCHORS.human*.96,Math.min(DEFAULT_ANCHORS.galaxy*1.1,state.distanceIntentRadii*span));return setContinuousDistance(next,{source})}
function dispatchCameraIntent(intent,{source='input'}={}){if(!intent||typeof intent!=='object')throw new TypeError('camera intent required');const normalized=Object.freeze({...intent,source,semanticScale:state.semanticScale});state.commandCount++;state.cameraIntent=normalized;state.userNavigationSource=source;emit('cameraIntent',{intent:normalized,activeSceneProvider:state.activeSceneProvider});const p=providers.get(state.activeSceneProvider);if(p?.cameraIntent){p.cameraIntent(normalized,snapshot());state.cameraCommandCount++;return true}return false}
function registerSceneProvider(provider){if(!provider||typeof provider.id!=='string'||!provider.id)throw new TypeError('scene provider id required');const scales=Object.freeze([...(provider.scales||[])].map(normalizeBand)),registered=Object.freeze({...provider,scales});providers.set(provider.id,registered);state.rendererReady++;try{registered.setActive?.(provider.id===state.activeSceneProvider,snapshot())}catch{}emit('rendererReady',{id:provider.id,scales});setActiveSceneForScale(state.semanticScale,'provider-registration');return()=>{if(providers.get(provider.id)===registered)providers.delete(provider.id)}}
function viewportChanged(viewport,{source='viewport'}={}){state.viewportChanges++;emit('viewportChanged',{viewport:Object.freeze({...viewport}),source,semanticScale:state.semanticScale});return snapshot()}
function completeTransition(){if(!state.transition)return snapshot();const completed=state.transition;state.transition=null;emit('transitionChanged',{transition:null,completed});return snapshot()}
function adjacent(from,to){return Math.abs(LADDER.indexOf(normalizeBand(from))-LADDER.indexOf(normalizeBand(to)))===1}
const API=Object.freeze({VERSION,contract:VERSION,SELECTION_CONTRACT,SCENE_PROVIDER_CONTRACT,RENDERER_LIFECYCLE_CONTRACT,TRANSITION_CONTRACT,CURRENT_BANDS,FUTURE_LADDER,LADDER,DEFAULT_ANCHORS,state,snapshot,on,emit,copyKey,deriveSemanticScale,configureAnchor,setSelection,requestStage,setContinuousDistance,stepTravel,dispatchCameraIntent,registerSceneProvider,viewportChanged,completeTransition,adjacent,normalizeBand});
O.waveIVScaleRuntime=API;
})(typeof globalThis!=='undefined'?globalThis:this);
