(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-material-model-1';
const SOURCE_KINDS=Object.freeze(['ROCK','MINERAL','ICE','WATER','ATMOSPHERE','SOIL','BIOLOGICAL_TISSUE','MANUFACTURED_MATERIAL','ARTIFACT']);
const PHASES=Object.freeze(['SOLID','LIQUID','GAS','MIXED','UNKNOWN']);
const CHEMISTRY=Object.freeze({SOURCE_BACKED:'SOURCE_BACKED_KNOWN_CHEMISTRY',MODEL_DERIVED:'MODEL_DERIVED_PLAUSIBLE_CHEMISTRY',SCHEMATIC:'SCHEMATIC_PRESENTATION',UNRESOLVED:'UNRESOLVED_CHEMISTRY'});
const STRUCTURES=Object.freeze(['CRYSTALLINE_PROXY','POLYCRYSTALLINE_PROXY','AMORPHOUS_PROXY','POROUS_AGGREGATE','FLUID','GAS_MIXTURE','BIOLOGICAL_SUPPORTED','COMPOSITE','UNRESOLVED']);
const MAX_COMPONENTS=16;
const KNOWN=Object.freeze({
 H2O:Object.freeze({formula:'H2O',elements:Object.freeze({H:2,O:1}),kind:'MOLECULE'}),
 CO2:Object.freeze({formula:'CO2',elements:Object.freeze({C:1,O:2}),kind:'MOLECULE'}),
 N2:Object.freeze({formula:'N2',elements:Object.freeze({N:2}),kind:'MOLECULE'}),
 O2:Object.freeze({formula:'O2',elements:Object.freeze({O:2}),kind:'MOLECULE'}),
 CH4:Object.freeze({formula:'CH4',elements:Object.freeze({C:1,H:4}),kind:'MOLECULE'}),
 NH3:Object.freeze({formula:'NH3',elements:Object.freeze({N:1,H:3}),kind:'MOLECULE'}),
 NaCl:Object.freeze({formula:'NaCl',elements:Object.freeze({Na:1,Cl:1}),kind:'FORMULA_UNIT'}),
 SiO2:Object.freeze({formula:'SiO2',elements:Object.freeze({Si:1,O:2}),kind:'FORMULA_UNIT'}),
 Fe:Object.freeze({formula:'Fe',elements:Object.freeze({Fe:1}),kind:'FORMULA_UNIT'}),
 Al2O3:Object.freeze({formula:'Al2O3',elements:Object.freeze({Al:2,O:3}),kind:'FORMULA_UNIT'})
});
function cleanElements(elements){if(elements==null)return null;V.assert(elements&&typeof elements==='object'&&!Array.isArray(elements),'elements object');const out={};for(const key of Object.keys(elements).sort()){V.text(key,'element symbol',8);const n=elements[key];V.int(n,'element count',1,256);out[key]=n;}return Object.freeze(out);}
function component(raw,index){V.assert(raw&&typeof raw==='object','component '+index);const id=V.text(String(raw.id||raw.label||('component-'+index)),'component id',96),ppm=V.ppm(Number(raw.ppm??0),'component ppm'),formula=raw.formula==null?null:V.text(String(raw.formula),'formula',32),known=formula&&KNOWN[formula]?KNOWN[formula]:null,elements=cleanElements(raw.elements)||known?.elements||null,kind=raw.kind?V.text(String(raw.kind),'component kind',48):(known?.kind||'COMPONENT');return Object.freeze({id,ppm,formula,elements,kind,authority:raw.authority?String(raw.authority):null});}
function normalizeComponents(list,chemistryAuthority){V.assert(Array.isArray(list)&&list.length<=MAX_COMPONENTS,'component bound');const out=list.map(component).sort((a,b)=>a.id.localeCompare(b.id)),sum=out.reduce((n,x)=>n+x.ppm,0);V.assert(sum<=1000000,'component ppm sum');if(sum<1000000)out.push(Object.freeze({id:'UNRESOLVED_REMAINDER',ppm:1000000-sum,formula:null,elements:null,kind:'UNRESOLVED',authority:CHEMISTRY.UNRESOLVED}));return Object.freeze(out.map(x=>Object.freeze({...x,authority:x.authority||chemistryAuthority})));}
function defaultForKind(kind){if(kind==='WATER')return{phase:'LIQUID',structure:'FLUID',chemistryAuthority:CHEMISTRY.SOURCE_BACKED,components:[{id:'WATER',ppm:1000000,formula:'H2O'}],porosityPpm:0};if(kind==='ICE')return{phase:'SOLID',structure:'CRYSTALLINE_PROXY',chemistryAuthority:CHEMISTRY.SOURCE_BACKED,components:[{id:'WATER_ICE',ppm:1000000,formula:'H2O'}],porosityPpm:25000};if(kind==='ATMOSPHERE')return{phase:'GAS',structure:'GAS_MIXTURE',chemistryAuthority:CHEMISTRY.UNRESOLVED,components:[],porosityPpm:1000000};if(kind==='ROCK'||kind==='MINERAL')return{phase:'SOLID',structure:kind==='MINERAL'?'CRYSTALLINE_PROXY':'POLYCRYSTALLINE_PROXY',chemistryAuthority:CHEMISTRY.UNRESOLVED,components:[],porosityPpm:60000};if(kind==='SOIL')return{phase:'MIXED',structure:'POROUS_AGGREGATE',chemistryAuthority:CHEMISTRY.UNRESOLVED,components:[],porosityPpm:350000};if(kind==='BIOLOGICAL_TISSUE')return{phase:'MIXED',structure:'UNRESOLVED',chemistryAuthority:CHEMISTRY.UNRESOLVED,components:[],porosityPpm:100000};return{phase:'SOLID',structure:'UNRESOLVED',chemistryAuthority:CHEMISTRY.UNRESOLVED,components:[],porosityPpm:50000};}
function source(spec){V.assert(spec&&typeof spec==='object','source spec');const sourceEntityId=V.text(String(spec.sourceEntityId),'sourceEntityId',128),kind=String(spec.kind||'').toUpperCase();V.assert(SOURCE_KINDS.includes(kind),'source kind');const parentEntityId=spec.parentEntityId==null?null:V.text(String(spec.parentEntityId),'parentEntityId',128),provider=V.text(String(spec.provider||'v1.micro.source-adapter'),'provider',128),authority=V.text(String(spec.authority||'MODEL_DERIVED_SIMULATION'),'source authority',64),d=defaultForKind(kind),phase=String(spec.phase||d.phase).toUpperCase(),structure=String(spec.structure||d.structure).toUpperCase();V.assert(PHASES.includes(phase),'phase');V.assert(STRUCTURES.includes(structure),'structure');const hasExplicitChemistry=(Array.isArray(spec.components)&&spec.components.length>0)||(Array.isArray(spec.species)&&spec.species.length>0)||(Array.isArray(spec.atomicStructure)&&spec.atomicStructure.length>0),chemistryAuthority=String(spec.chemistryAuthority||(hasExplicitChemistry?CHEMISTRY.SOURCE_BACKED:d.chemistryAuthority));V.assert(Object.values(CHEMISTRY).includes(chemistryAuthority),'chemistry authority');const porosityPpm=V.ppm(Number(spec.porosityPpm??d.porosityPpm),'porosityPpm'),temperatureMilliK=spec.temperatureMilliK==null?null:V.int(Number(spec.temperatureMilliK),'temperatureMilliK',0,50000000),pressurePa=spec.pressurePa==null?null:V.int(Number(spec.pressurePa),'pressurePa',0,Number.MAX_SAFE_INTEGER),grainScaleNm=spec.grainScaleNm==null?null:V.int(Number(spec.grainScaleNm),'grainScaleNm',1,1000000000000),organization=spec.biologicalOrganization==null?null:String(spec.biologicalOrganization),technologySupported=spec.technologySupported===true,components=normalizeComponents(spec.components||spec.species||d.components,chemistryAuthority),latticeMotif=spec.latticeMotif==null?null:String(spec.latticeMotif);let atomicStructure=null;if(spec.atomicStructure!=null){V.assert(Array.isArray(spec.atomicStructure)&&spec.atomicStructure.length<=512,'source atomic structure bound');atomicStructure=Object.freeze(spec.atomicStructure.map((a,i)=>{V.assert(a&&typeof a.element==='string'&&Array.isArray(a.position)&&a.position.length===3,'source atom '+i);return Object.freeze({element:V.text(a.element,'element',8),position:Object.freeze(a.position.map((n,j)=>{V.assert(Number.isFinite(Number(n)),'source atom position '+j);return Number(n)}))});}));}
 return V.freezeDeep({contract:'ofu-v1-micro-source-1',sourceEntityId,parentEntityId,kind,provider,authority,phase,structure,chemistryAuthority,components,porosityPpm,temperatureMilliK,pressurePa,grainScaleNm,biologicalOrganization:organization,technologySupported,latticeMotif,atomicStructure,provenance:{geological:kind==='ROCK'||kind==='MINERAL'||kind==='SOIL',biological:kind==='BIOLOGICAL_TISSUE',artificial:kind==='MANUFACTURED_MATERIAL'||kind==='ARTIFACT'},metadata:spec.metadata&&typeof spec.metadata==='object'?{...spec.metadata}:{}});
}
function materialize(input){const s=input?.contract==='ofu-v1-micro-source-1'?input:source(input);if((s.kind==='MANUFACTURED_MATERIAL'||s.kind==='ARTIFACT')&&!s.technologySupported&&s.structure!=='UNRESOLVED')V.assert(false,'manufactured structure requires technological support');const materialId=V.deriveId('v1-material',s.sourceEntityId,s.kind,s.phase,s.structure),knownPpm=s.components.filter(c=>c.formula||c.elements).reduce((n,c)=>n+c.ppm,0),compositionCompletenessPpm=V.clamp(knownPpm,0,1000000);return V.freezeDeep({contract:'ofu-v1-material-1',materialId,sourceEntityId:s.sourceEntityId,sourceKind:s.kind,parentEntityId:s.parentEntityId,phase:s.phase,structure:s.structure,chemistryAuthority:s.chemistryAuthority,compositionCompletenessPpm,components:s.components,porosityPpm:s.porosityPpm,grainScaleNm:s.grainScaleNm,temperatureMilliK:s.temperatureMilliK,pressurePa:s.pressurePa,biologicalOrganization:s.biologicalOrganization,technologySupported:s.technologySupported,latticeMotif:s.latticeMotif,sourceAtomicStructure:s.atomicStructure,provenance:s.provenance,representationAuthority:s.authority,exactBulkCompositionClaim:compositionCompletenessPpm===1000000&&s.components.every(c=>c.authority===CHEMISTRY.SOURCE_BACKED),limitations:Object.freeze([compositionCompletenessPpm<1000000?'Bulk chemistry is incompletely resolved.':null,s.kind==='BIOLOGICAL_TISSUE'&&!s.biologicalOrganization?'No cell-like organization is assumed without biological provider support.':null].filter(Boolean))});}
function fromPlanetSurface(profile,{surfaceCell=null,kind='ROCK'}={}){V.assert(profile&&profile.planetIdentity,'planet profile');const k=String(kind).toUpperCase(),id=surfaceCell?.cellId||V.deriveId('surface-material-sample',profile.planetIdentity,k);if(k==='WATER'||k==='ICE')return source({sourceEntityId:id,parentEntityId:profile.planetIdentity,kind:k,provider:'v1.planetology',authority:'MODEL_DERIVED_SIMULATION',temperatureMilliK:profile.climate?.surfaceTemperatureMilliK,metadata:{surfaceCellId:surfaceCell?.cellId||null,canonicalOceanClaim:profile.hydrosphere?.canonicalOceanClaim===true}});const comp=profile.composition||{},parts=[];for(const [idKey,value] of [['METAL_FRACTION',comp.metalPpm],['SILICATE_FRACTION',comp.silicatePpm],['VOLATILE_FRACTION',comp.volatilePpm]])if(Number.isSafeInteger(value)&&value>=0)parts.push({id:idKey,ppm:value});return source({sourceEntityId:id,parentEntityId:profile.planetIdentity,kind:k,provider:'v1.planetology',authority:'MODEL_DERIVED_SIMULATION',chemistryAuthority:CHEMISTRY.MODEL_DERIVED,components:parts,temperatureMilliK:profile.climate?.surfaceTemperatureMilliK,porosityPpm:k==='SOIL'?350000:60000,metadata:{surfaceCellId:surfaceCell?.cellId||null,physicalElevationCanonical:surfaceCell?.physicalElevationCanonical===true}});}
function fromAtmosphere(profile,{species=null,sampleId='bulk'}={}){V.assert(profile&&profile.planetIdentity,'planet profile');return source({sourceEntityId:V.deriveId('atmosphere-sample',profile.planetIdentity,sampleId),parentEntityId:profile.planetIdentity,kind:'ATMOSPHERE',provider:'v1.planetology',authority:'MODEL_DERIVED_SIMULATION',species:Array.isArray(species)?species:[],chemistryAuthority:Array.isArray(species)&&species.length?CHEMISTRY.SOURCE_BACKED:CHEMISTRY.UNRESOLVED,temperatureMilliK:profile.climate?.surfaceTemperatureMilliK,metadata:{inventoryUnits:profile.atmosphere?.inventoryUnits??null,canonicalPressure:profile.atmosphere?.canonicalPressure===true}});}
O.v1Materials=Object.freeze({VERSION,SOURCE_KINDS,PHASES,CHEMISTRY,STRUCTURES,KNOWN,MAX_COMPONENTS,source,materialize,fromPlanetSurface,fromAtmosphere});
})(globalThis);
