import {assert,camera,close} from './support.mjs';
const {camera:c,adapter,model}=camera({band:'orbit'}),initial=c.snapshot(),selection=initial.selectionToken;
assert.equal(initial.distanceAuthorityKey,'logDistanceM');
const onlyMutableDistanceAuthority=c.distanceAuthorityKey;assert.equal(onlyMutableDistanceAuthority,'logDistanceM');
let before=c.snapshot().logDistanceM;adapter.wheel(120);assert.ok(c.snapshot().logDistanceM>before,'wheel out must increase semantic distance');
before=c.snapshot().logDistanceM;adapter.wheel(-120);assert.ok(c.snapshot().logDistanceM<before,'wheel in must decrease semantic distance');
before=c.snapshot().logDistanceM;adapter.pinch(1.15);assert.ok(c.snapshot().logDistanceM<before,'pinch apart must zoom inward');
before=c.snapshot().logDistanceM;adapter.pinch(.85);assert.ok(c.snapshot().logDistanceM>before,'pinch together must zoom outward');
before=c.snapshot().logDistanceM;adapter.keyboard(-1);assert.ok(c.snapshot().logDistanceM<before,'keyboard zoom-in monotonic');
before=c.snapshot().logDistanceM;adapter.keyboard(1);assert.ok(c.snapshot().logDistanceM>before,'keyboard zoom-out monotonic');
assert.equal(c.snapshot().selectionToken,selection,'scale input cannot mutate selection');
assert.throws(()=>c.travelToLogDistance(model.anchorLogM.galaxy),/explicit fastTravel/);
const start=c.snapshot();
for(let i=0;i<40;i++)c.applyDistanceDelta(-.12,{source:'inward-proof'});
const inner=c.snapshot();assert.equal(inner.semanticScale,'human');assert.equal(inner.belowWaveIVHuman,true);assert.equal(inner.selectionToken,selection);assert.ok(inner.referenceReturnDepth>0);
for(let i=0;i<40;i++)c.applyDistanceDelta(.12,{source:'outward-proof'});
const returned=c.snapshot();close(returned.logDistanceM,start.logDistanceM,1e-9);assert.equal(returned.semanticScale,start.semanticScale);assert.equal(returned.pose.frameId,start.pose.frameId);assert.deepEqual(returned.pose.position,start.pose.position,'return stack restores floating-frame pose exactly when no spatial mutation occurs');assert.deepEqual(returned.pose.orientation,start.pose.orientation);assert.equal(returned.selectionToken,selection);
const derived=model.describe(model.anchorLogM.human);assert.ok(derived.distanceM<1000&&derived.distanceM>100,'human anchor is surface clearance, not a duplicate planet-center distance');
console.log(JSON.stringify({status:'PASS',oracle:'v1x01-semantic-travel-oracle-1',distanceAuthority:'logDistanceM',selectionInvariant:true,reverseTraversal:true,authority:'PRESENTATION_ONLY'}));
