(function(root){
'use strict';
if(typeof document==='undefined')return;
const O=root.OFU=root.OFU||{},VERSION='ofu-v2-cinematic-experience-1',AUTHORITY='PRESENTATION_ONLY';
const REGIME=Object.freeze({UNIVERSE:'MACRO',GALAXY:'MACRO',REGION:'MACRO',NEIGHBORHOOD:'MACRO',SYSTEM:'SYSTEM',ORBIT:'PLANETARY',APPROACH:'PLANETARY',GLOBAL_SURFACE:'PLANETARY',REGIONAL_SURFACE:'SURFACE',LOCAL_SURFACE:'SURFACE',HUMAN:'LOCAL',MATERIAL:'MICRO',MATTER:'MICRO',MICROSTRUCTURE:'MICRO',MICROSCOPIC:'MICRO',MOLECULAR:'MICRO',ATOMIC:'MICRO'});
const PROMPT=Object.freeze({UNIVERSE:'Select a luminous structure. Drag to look. Wheel to travel deeper.',GALAXY:'Choose a region and continue inward.',REGION:'Enter a stellar neighborhood.',NEIGHBORHOOD:'Select a system or star.',SYSTEM:'Select a world to make it the destination.',ORBIT:'Manipulate the world, then approach when ready.',APPROACH:'You have arrived. Drag the world or descend.',GLOBAL_SURFACE:'Select a location to continue toward the surface.',REGIONAL_SURFACE:'Choose terrain or continue toward local scale.',LOCAL_SURFACE:'Select an object or material to inspect.',HUMAN:'Select what matters here; evidence remains available in Inspect.',MATERIAL:'This is a model regime change, not literal infinite zoom.',MATTER:'This is a model regime change, not literal infinite zoom.',MICROSTRUCTURE:'Inspect bounded material structure.',MICROSCOPIC:'Inspect bounded microscopic structure.',MOLECULAR:'Inspect bounded molecular structure.',ATOMIC:'Structural representation only; no electron trajectories are asserted.'});
let stage=null,guide=null,observer=null,settleTimer=0,dismissed=false,lastStage='';
const reduced=()=>typeof root.matchMedia==='function'&&root.matchMedia('(prefers-reduced-motion: reduce)').matches;
function classify(){if(!stage)return;const current=stage.dataset.stage||'UNKNOWN',regime=REGIME[current]||'UNKNOWN';stage.dataset.cinematicRegime=regime;stage.dataset.cinematicAuthority=AUTHORITY;stage.dataset.cinematicQuality=(root.innerWidth<=760||root.innerHeight<=520)?'BALANCED':'HIGH';if(current!==lastStage){lastStage=current;markArrival();}if(guide&&!dismissed){guide.textContent=PROMPT[current]||'Select the world directly or use the adjacent navigation controls.';guide.dataset.stage=current;}}
function markArrival(){if(!stage)return;root.clearTimeout(settleTimer);stage.dataset.cinematicPhase=reduced()?'SETTLED':'ARRIVAL';if(!reduced())settleTimer=root.setTimeout(()=>{if(stage)stage.dataset.cinematicPhase='SETTLED';},320);}
function dismiss(){if(dismissed)return;dismissed=true;if(guide){guide.hidden=true;guide.setAttribute('aria-hidden','true');}if(stage)stage.dataset.cinematicGuidance='DISMISSED';}
function meaningfulKey(event){return ['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','Escape','PageUp','PageDown','Home','End','+','-','=','w','a','s','d','W','A','S','D'].includes(event.key);}
function bindInput(){const options={passive:true,capture:true};stage.addEventListener('pointerdown',dismiss,options);stage.addEventListener('wheel',dismiss,options);stage.addEventListener('touchstart',dismiss,options);stage.addEventListener('keydown',event=>{if(meaningfulKey(event))dismiss();},{capture:true});}
function boot(){stage=document.getElementById('living-stage');if(!stage)return false;stage.classList.add('v2-cinematic-stage');stage.dataset.cinematicGuidance='VISIBLE';guide=document.createElement('p');guide.id='v2-cinematic-guide';guide.className='v2-cinematic-guide';guide.setAttribute('aria-hidden','true');guide.setAttribute('role','presentation');stage.append(guide);observer=new MutationObserver(records=>{if(records.some(r=>r.attributeName==='data-stage'))classify();});observer.observe(stage,{attributes:true,attributeFilter:['data-stage','data-world-identity','data-location-identity']});bindInput();root.addEventListener('resize',classify,{passive:true});classify();return true;}
function snapshot(){return Object.freeze({version:VERSION,authority:AUTHORITY,active:Boolean(stage),stage:stage?.dataset.stage||null,regime:stage?.dataset.cinematicRegime||null,phase:stage?.dataset.cinematicPhase||null,guidance:dismissed?'DISMISSED':'VISIBLE',semanticMutation:false,cameraAuthority:false,navigationAuthority:false,networkResources:0});}
if(!boot())document.addEventListener('DOMContentLoaded',boot,{once:true});
O.v2CinematicExperience=Object.freeze({VERSION,AUTHORITY,snapshot,dismissGuidance:dismiss});
})(globalThis);
