import fs from 'node:fs';import path from 'node:path';import process from 'node:process';import http from 'node:http';import {pathToFileURL} from 'node:url';import {chromium,firefox,webkit} from 'playwright';
const name=process.env.BROWSER||'chromium',engines={chromium,firefox,webkit};if(!engines[name])throw new Error('unknown browser '+name);const browser=await engines[name].launch({headless:true}),file=path.resolve('dist/One_File_Universe.html'),html=fs.readFileSync(file,'utf8'),evidenceDir='dist/evidence';fs.mkdirSync(evidenceDir,{recursive:true});const write=(suffix,value)=>fs.writeFileSync(`${evidenceDir}/browser-${name}${suffix}.json`,JSON.stringify(value,null,2)+'\n');
const installNetworkBlock=async page=>page.addInitScript(()=>{globalThis.__OFU_NET_CALLS__=[];const push=(kind,url)=>globalThis.__OFU_NET_CALLS__.push({kind,url:String(url)});if(globalThis.fetch)globalThis.fetch=(...a)=>{push('fetch',a[0]);throw new Error('network blocked by P1 harness');};if(globalThis.XMLHttpRequest){const X=globalThis.XMLHttpRequest;globalThis.XMLHttpRequest=function(){const x=new X(),open=x.open;x.open=function(m,u,...r){push('xhr',u);return open.call(this,m,u,...r)};return x;};}if(globalThis.WebSocket)globalThis.WebSocket=function(url){push('websocket',url);throw new Error('network blocked by P1 harness');};});
async function pageFor(url,{workers=true}={}){const context=await browser.newContext();const page=await context.newPage();const external=[];await installNetworkBlock(page);if(!workers)await page.addInitScript(()=>{Object.defineProperty(globalThis,'Worker',{value:undefined,configurable:true});});page.on('request',r=>{if(/^https?:|^wss?:/.test(r.url()))external.push(r.url());});await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.__OFU_REPORT__&&document.getElementById('status').textContent!=='BOOTING',{timeout:30000});const report=await page.evaluate(()=>({...globalThis.__OFU_REPORT__,networkCalls:globalThis.__OFU_NET_CALLS__||[],uiStatus:document.getElementById('status').textContent,heap:performance.memory?{usedJSHeapSize:performance.memory.usedJSHeapSize,totalJSHeapSize:performance.memory.totalJSHeapSize,jsHeapSizeLimit:performance.memory.jsHeapSizeLimit}:null}));await context.close();return {report,external};}
try{const url=pathToFileURL(file).href,{report:strict,external}=await pageFor(url);write('-strict',{browser:name,artifactBytes:fs.statSync(file).size,strict,externalRequests:external});if(strict.protocol!=='file:'||external.length||strict.networkCalls.length)throw new Error('Strict Direct-Open/network invariant failed');const failures=(strict.results||[]).filter(x=>x.status==='FAIL');if(failures.length)throw new Error('Strict self-test failures: '+JSON.stringify(failures));if((strict.results||[]).find(x=>x.name==='workers-1-2-n')?.status!=='PASS')throw new Error('Strict worker 1/2/N path did not PASS');
const {report:repeat}=await pageFor(url);if(repeat.digest!==strict.digest)throw new Error('fresh-context repeat digest mismatch');
const {report:noWorkers}=await pageFor(url,{workers:false}),workerFallback=(noWorkers.results||[]).find(x=>x.name==='workers-1-2-n');if(noWorkers.digest!==strict.digest||workerFallback?.status!=='ENVIRONMENT_LIMITED')throw new Error('worker-unavailable fallback violated canonical state');
const corruptPath=path.resolve('dist/One_File_Universe.corrupt.html'),corrupt=html.replace('u16 range','u16 rangx');if(corrupt===html)throw new Error('corruption injection target missing');fs.writeFileSync(corruptPath,corrupt);const corruptContext=await browser.newContext(),corruptPage=await corruptContext.newPage();let integrityRejected=false;corruptPage.on('pageerror',e=>{if(String(e.message).includes('component integrity mismatch'))integrityRejected=true;});await corruptPage.goto(pathToFileURL(corruptPath).href,{waitUntil:'load'});await corruptPage.waitForTimeout(100);await corruptContext.close();if(!integrityRejected)throw new Error('corrupted embedded component was not rejected');fs.unlinkSync(corruptPath);
const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,{report:enhanced}=await pageFor(`http://127.0.0.1:${port}/`);await new Promise(r=>server.close(r));if(strict.digest!==enhanced.digest)throw new Error('Strict/Enhanced digest mismatch');
const report={browser:name,platform:process.platform,arch:process.arch,artifactBytes:fs.statSync(file).size,strict,repeatDigest:repeat.digest,workerUnavailableDigest:noWorkers.digest,componentCorruptionRejected:true,enhancedDigest:enhanced.digest,strictEnhancedEqual:true,externalRequests:external,decodeAmplification:{componentEmbeddedBytes:strict.componentManifest.reduce((s,c)=>s+c.embeddedBytes,0),artifactBytes:fs.statSync(file).size}};write('',report);console.log(JSON.stringify(report,null,2));}finally{await browser.close();}
