import {W1_AUTHORITY,W1_FINGERPRINT_STATUS} from '../../contracts/w1-observation-contracts.js';

export const SEARCH_ENGINE_VERSION='ofu-prod-w2-search-engine-1';
export const SEARCH_RESULT_CONTRACT='ofu-prod-w2-search-result-1';
export const SEARCH_PROVIDER_CONTRACT='ofu-prod-w2-search-provider-1';
export const SEARCH_METRIC_VERSION='ofu-prod-w2-search-metric-1';
export const INTERESTINGNESS_MODEL_VERSION='ofu-prod-w2-interestingness-1';
export const SEARCH_STATE=Object.freeze({VALUE:'VALUE',UNKNOWN:'UNKNOWN',UNSUPPORTED:'UNSUPPORTED'});
export const SEARCH_SORT=Object.freeze({SIMILARITY:'SIMILARITY',INTERESTINGNESS:'INTERESTINGNESS',IDENTITY:'IDENTITY'});
export const SEARCH_DEFAULT_BUDGET=Object.freeze({maxCandidates:128,maxResults:24,maxBytes:262144,maxProviderCalls:16});

const enc=new TextEncoder();
const AUTHORITY_ORDER=Object.freeze({[W1_AUTHORITY.UNKNOWN]:0,[W1_AUTHORITY.PRESENTATION_ONLY]:1,[W1_AUTHORITY.ANALYSIS_ONLY]:2,[W1_AUTHORITY.MODEL_DERIVED]:3,[W1_AUTHORITY.CANONICAL]:4});
const ALLOWED_SORT=new Set(Object.values(SEARCH_SORT));
const ALLOWED_STATE=new Set(Object.values(SEARCH_STATE));
const ALLOWED_OP=new Set(['EQ','NE','GTE','LTE','IN','EXISTS']);

function fail(message){throw new Error('OFU Search: '+message)}
function plain(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;const p=Object.getPrototypeOf(value);return p===Object.prototype||p===null}
function exactKeys(value,expected,label){if(!plain(value))fail(label+' must be a plain object');const keys=Object.keys(value).sort(),want=[...expected].sort();if(keys.length!==want.length||keys.some((key,index)=>key!==want[index]))fail(label+' has missing or unsupported fields')}
function boundedInt(value,label,min,max){if(!Number.isSafeInteger(value)||value<min||value>max)fail(label+' out of bounds');return value}
function text(value,label,{nullable=false,maxBytes=512}={}){if(value===null&&nullable)return null;if(typeof value!=='string')fail(label+' must be text');const normalized=value.normalize('NFC');if(!normalized.length)fail(label+' must be non-empty');if(enc.encode(normalized).length>maxBytes)fail(label+' exceeds byte limit');return normalized}
function stable(value){if(value===null||typeof value==='string'||typeof value==='boolean')return JSON.stringify(value);if(typeof value==='number'){if(!Number.isSafeInteger(value))fail('numbers must be safe integers');return String(value)}if(Array.isArray(value))return '['+value.map(stable).join(',')+']';if(!plain(value))fail('value must be JSON-like');return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stable(value[k])).join(',')+'}'}
function cloneFreeze(value){if(Array.isArray(value))return Object.freeze(value.map(cloneFreeze));if(plain(value))return Object.freeze(Object.fromEntries(Object.keys(value).sort().map(k=>[k,cloneFreeze(value[k])])));return value}
function stateValue(value,label){exactKeys(value,['state','value'],'property '+label);if(!ALLOWED_STATE.has(value.state))fail('property '+label+' has invalid state');if(value.state!==SEARCH_STATE.VALUE&&value.value!==null)fail('non-VALUE property '+label+' must use null value');if(value.state===SEARCH_STATE.VALUE&&value.value===undefined)fail('VALUE property '+label+' requires value');return Object.freeze({state:value.state,value:cloneFreeze(value.value)})}
function normalizeProperties(value){if(!plain(value))fail('candidate properties must be a plain object');const keys=Object.keys(value).sort();if(keys.length>128)fail('candidate property count exceeds limit');return Object.freeze(Object.fromEntries(keys.map(k=>[text(k,'property key',{maxBytes:128}),stateValue(value[k],k)])))}
function canonicalIdentity(identity){exactKeys(identity,['universeId','entityKind','canonicalId','canonicalKey'],'candidate identity');const id=text(identity.canonicalId,'canonicalId',{maxBytes:128}).toLowerCase();if(!/^[0-9a-f]{64}$/.test(id))fail('canonicalId must be a 32-byte digest');if(!plain(identity.canonicalKey)||!Object.keys(identity.canonicalKey).length)fail('canonicalKey required');const key=Object.freeze(Object.fromEntries(Object.keys(identity.canonicalKey).sort().map(k=>[text(k,'canonicalKey field',{maxBytes:128}),String(identity.canonicalKey[k])])));return Object.freeze({universeId:text(identity.universeId,'universeId'),entityKind:text(identity.entityKind,'entityKind',{maxBytes:64}).toUpperCase(),canonicalId:id,canonicalKey:key})}
function normalizeFingerprint(value){
  if(value===null)return null;
  const source=value?.fingerprint??value;
  if(!plain(source))fail('fingerprint must be a plain object');
  for(const key of ['status','scientificStateContract','scientificModelVersion','scientificHashes','authorityByDomain'])if(!Object.hasOwn(source,key))fail('fingerprint missing '+key);
  if(!Object.values(W1_FINGERPRINT_STATUS).includes(source.status))fail('fingerprint status unsupported');
  const hashes=source.scientificHashes;if(!plain(hashes))fail('fingerprint scientificHashes invalid');
  const authorities=source.authorityByDomain;if(!plain(authorities))fail('fingerprint authorityByDomain invalid');
  const model=source.scientificModelVersion===null?null:text(source.scientificModelVersion,'scientificModelVersion');
  if(source.status===W1_FINGERPRINT_STATUS.PRESENT&&model===null)fail('PRESENT fingerprint requires scientificModelVersion');
  const normalizedHashes=Object.freeze(Object.fromEntries(['planet','context','surface','sample'].map(k=>{const v=hashes[k]??null;if(v!==null&&!/^[0-9a-f]{64}$/.test(String(v)))fail('fingerprint hash invalid');return [k,v===null?null:String(v)]})));
  if(source.status===W1_FINGERPRINT_STATUS.UNKNOWN&&Object.values(normalizedHashes).some(v=>v!==null))fail('UNKNOWN fingerprint must not assert scientific hashes');
  return Object.freeze({status:source.status,scientificStateContract:text(source.scientificStateContract,'scientificStateContract'),scientificModelVersion:model,scientificHashes:normalizedHashes,authorityByDomain:Object.freeze(Object.fromEntries(Object.keys(authorities).sort().map(k=>{const a=String(authorities[k]);if(!(a in AUTHORITY_ORDER))fail('fingerprint authority invalid');return [k,a]})))})
}
function normalizeCandidate(value,provider){exactKeys(value,['identity','properties','fingerprint','provenance','atlasEntryId'],'candidate');const identity=canonicalIdentity(value.identity);const atlasEntryId=value.atlasEntryId===null?null:text(value.atlasEntryId,'atlasEntryId',{maxBytes:64});const provenance=cloneFreeze(value.provenance);return Object.freeze({identity,properties:normalizeProperties(value.properties),fingerprint:normalizeFingerprint(value.fingerprint),provenance,atlasEntryId,provider:Object.freeze({id:provider.id,version:provider.version,authority:provider.authority})})}
function normalizeBudget(value={}){if(!plain(value))fail('budget must be a plain object');for(const k of Object.keys(value))if(!Object.hasOwn(SEARCH_DEFAULT_BUDGET,k))fail('unsupported budget field: '+k);return Object.freeze({maxCandidates:boundedInt(value.maxCandidates??SEARCH_DEFAULT_BUDGET.maxCandidates,'maxCandidates',1,4096),maxResults:boundedInt(value.maxResults??SEARCH_DEFAULT_BUDGET.maxResults,'maxResults',1,256),maxBytes:boundedInt(value.maxBytes??SEARCH_DEFAULT_BUDGET.maxBytes,'maxBytes',1024,16*1024*1024),maxProviderCalls:boundedInt(value.maxProviderCalls??SEARCH_DEFAULT_BUDGET.maxProviderCalls,'maxProviderCalls',1,256)})}
function normalizeFilters(value=[]){if(!Array.isArray(value)||value.length>64)fail('filters must be a bounded array');return Object.freeze(value.map((f,index)=>{exactKeys(f,['property','op','value','unknownPolicy'],'filter['+index+']');const op=text(f.op,'filter op',{maxBytes:16}).toUpperCase();if(!ALLOWED_OP.has(op))fail('unsupported filter operator');const unknownPolicy=text(f.unknownPolicy,'unknownPolicy',{maxBytes:16}).toUpperCase();if(!['REJECT','ALLOW'].includes(unknownPolicy))fail('unknownPolicy unsupported');return Object.freeze({property:text(f.property,'filter property',{maxBytes:128}),op,value:cloneFreeze(f.value),unknownPolicy})}))}
function compareScalar(a,b){if(typeof a==='number'&&typeof b==='number')return a===b?0:(a<b?-1:1);return stable(a).localeCompare(stable(b))}
function filterMatch(candidate,filter){const p=candidate.properties[filter.property];if(!p)fail('unsupported property filter: '+filter.property);if(p.state!==SEARCH_STATE.VALUE)return filter.unknownPolicy==='ALLOW';switch(filter.op){case 'EXISTS':return true;case 'EQ':return stable(p.value)===stable(filter.value);case 'NE':return stable(p.value)!==stable(filter.value);case 'GTE':return compareScalar(p.value,filter.value)>=0;case 'LTE':return compareScalar(p.value,filter.value)<=0;case 'IN':if(!Array.isArray(filter.value))fail('IN filter requires array');return filter.value.some(x=>stable(x)===stable(p.value));default:return false}}
function authorityScore(fp){if(!fp||fp.status!==W1_FINGERPRINT_STATUS.PRESENT)return null;const values=Object.values(fp.authorityByDomain);if(!values.length)return 0;return Math.floor(values.reduce((n,a)=>n+AUTHORITY_ORDER[a],0)*1000000/(values.length*4))}
function hashSimilarity(a,b){let compared=0,matches=0;for(const key of ['planet','context','surface','sample']){const x=a?.scientificHashes?.[key]??null,y=b?.scientificHashes?.[key]??null;if(x===null||y===null)continue;compared++;if(x===y)matches++}return compared?Math.floor(matches*1000000/compared):null}
function authoritySimilarity(a,b){if(!a||!b)return null;const keys=[...new Set([...Object.keys(a.authorityByDomain),...Object.keys(b.authorityByDomain)])].sort();if(!keys.length)return null;let distance=0,count=0;for(const key of keys){const x=a.authorityByDomain[key]??W1_AUTHORITY.UNKNOWN,y=b.authorityByDomain[key]??W1_AUTHORITY.UNKNOWN;distance+=Math.abs(AUTHORITY_ORDER[x]-AUTHORITY_ORDER[y]);count++}return 1000000-Math.floor(distance*1000000/(count*4))}
export function scientificSimilarity(reference,candidate){if(!reference||reference.status!==W1_FINGERPRINT_STATUS.PRESENT||!candidate||candidate.status!==W1_FINGERPRINT_STATUS.PRESENT)return Object.freeze({state:SEARCH_STATE.UNKNOWN,scorePpm:null,metricVersion:SEARCH_METRIC_VERSION,rationale:Object.freeze(['Scientific fingerprint unavailable or UNKNOWN.'])});if(reference.scientificStateContract!==candidate.scientificStateContract||reference.scientificModelVersion!==candidate.scientificModelVersion)return Object.freeze({state:SEARCH_STATE.UNSUPPORTED,scorePpm:null,metricVersion:SEARCH_METRIC_VERSION,rationale:Object.freeze(['Fingerprint contract/model versions differ; similarity is not comparable.'])});const h=hashSimilarity(reference,candidate),a=authoritySimilarity(reference,candidate);if(h===null&&a===null)return Object.freeze({state:SEARCH_STATE.UNKNOWN,scorePpm:null,metricVersion:SEARCH_METRIC_VERSION,rationale:Object.freeze(['No comparable fingerprint dimensions.'])});const score=Math.floor(((h??a)+(a??h))/2);return Object.freeze({state:SEARCH_STATE.VALUE,scorePpm:score,metricVersion:SEARCH_METRIC_VERSION,rationale:Object.freeze([`Hash agreement=${h===null?'UNKNOWN':h+'ppm'}.`,`Authority agreement=${a===null?'UNKNOWN':a+'ppm'}.`])})}
function interestingness(candidate){const novelty=candidate.properties.noveltyPpm?.state===SEARCH_STATE.VALUE?boundedInt(candidate.properties.noveltyPpm.value,'noveltyPpm',0,1000000):null;const rarity=candidate.properties.rarityPpm?.state===SEARCH_STATE.VALUE?boundedInt(candidate.properties.rarityPpm.value,'rarityPpm',0,1000000):null;const authority=authorityScore(candidate.fingerprint);const known=[novelty,rarity].filter(x=>x!==null);if(!known.length)return Object.freeze({state:SEARCH_STATE.UNKNOWN,scorePpm:null,modelVersion:INTERESTINGNESS_MODEL_VERSION,rationale:Object.freeze(['No governed novelty/rarity property is available; interestingness remains UNKNOWN.'])});const discovery=Math.floor(known.reduce((a,b)=>a+b,0)/known.length),score=authority===null?discovery:Math.floor((discovery*3+authority)/4);return Object.freeze({state:SEARCH_STATE.VALUE,scorePpm:score,modelVersion:INTERESTINGNESS_MODEL_VERSION,rationale:Object.freeze([`Governed discovery signal=${discovery}ppm from ${known.length} declared dimension(s).`,authority===null?'Scientific authority support is UNKNOWN and is omitted rather than coerced to zero.':`Scientific authority support=${authority}ppm.`,`Weights are fixed by ${INTERESTINGNESS_MODEL_VERSION}; user history is not an input.`])})}
function resultBytes(result){return enc.encode(stable(result)).length}
function rankTuple(item,sort){const sim=item.similarity.state===SEARCH_STATE.VALUE?item.similarity.scorePpm:-1,interesting=item.interestingness.state===SEARCH_STATE.VALUE?item.interestingness.scorePpm:-1;return sort===SEARCH_SORT.SIMILARITY?[-sim,-interesting,item.identity.canonicalId]:sort===SEARCH_SORT.INTERESTINGNESS?[-interesting,-sim,item.identity.canonicalId]:[0,0,item.identity.canonicalId]}
function cmpTuple(a,b){for(let i=0;i<a.length;i++){if(typeof a[i]==='number'&&a[i]!==b[i])return a[i]-b[i];const c=String(a[i]).localeCompare(String(b[i]));if(c)return c}return 0}
function normalizeProvider(provider,index){if(!provider||typeof provider!=='object')fail('provider['+index+'] invalid');for(const key of ['id','version','authority','discover'])if(!(key in provider))fail('provider missing '+key);if(typeof provider.discover!=='function')fail('provider discover must be a function');const authority=String(provider.authority);if(!(authority in AUTHORITY_ORDER))fail('provider authority unsupported');return Object.freeze({id:text(provider.id,'provider id',{maxBytes:128}),version:text(provider.version,'provider version',{maxBytes:128}),authority,discover:provider.discover})}
function cancellationReason(signal,generationToken,currentGeneration){if(signal?.aborted)return 'ABORT_SIGNAL';if(typeof currentGeneration==='function'&&generationToken!==undefined&&currentGeneration()!==generationToken)return 'STALE_GENERATION';return null}

export async function boundedSearch({providers,filters=[],sort=SEARCH_SORT.IDENTITY,referenceFingerprint=null,budget={},query={},signal=null,generationToken=undefined,currentGeneration=null}={}){
  if(!Array.isArray(providers)||!providers.length||providers.length>64)fail('providers must be a bounded non-empty array');
  const ps=providers.map(normalizeProvider).sort((a,b)=>a.id.localeCompare(b.id)||a.version.localeCompare(b.version)),b=normalizeBudget(budget),fs=normalizeFilters(filters);for(let i=1;i<ps.length;i++)if(ps[i-1].id===ps[i].id&&ps[i-1].version===ps[i].version)fail('duplicate provider id/version');sort=text(sort,'sort',{maxBytes:32}).toUpperCase();if(!ALLOWED_SORT.has(sort))fail('unsupported sort');if(!plain(query))fail('query must be a plain object');
  const normalizedQuery=cloneFreeze(query);if(enc.encode(stable(normalizedQuery)).length>65536)fail('query exceeds byte limit');
  const ref=normalizeFingerprint(referenceFingerprint),seen=new Set(),accepted=[];let providerCalls=0,candidatesSeen=0,bytesUsed=0,truncated=false,cancelled=false,cancelReason=null;
  for(const provider of ps){
    cancelReason=cancellationReason(signal,generationToken,currentGeneration);if(cancelReason){cancelled=true;break}
    if(providerCalls>=b.maxProviderCalls){truncated=true;break}providerCalls++;
    const remaining=b.maxCandidates-candidatesSeen;if(remaining<=0){truncated=true;break}
    const batch=await provider.discover(Object.freeze({contract:SEARCH_PROVIDER_CONTRACT,query:normalizedQuery,limit:remaining,budget:b,signal,generationToken}));
    if(!Array.isArray(batch))fail('provider '+provider.id+' must return an array');
    if(batch.length>remaining)fail('provider '+provider.id+' exceeded requested candidate limit');
    const normalizedBatch=batch.map(raw=>normalizeCandidate(raw,provider)).sort((a,b)=>a.identity.universeId.localeCompare(b.identity.universeId)||a.identity.entityKind.localeCompare(b.identity.entityKind)||a.identity.canonicalId.localeCompare(b.identity.canonicalId));
    for(const candidate of normalizedBatch){
      cancelReason=cancellationReason(signal,generationToken,currentGeneration);if(cancelReason){cancelled=true;break}
      if(candidatesSeen>=b.maxCandidates){truncated=true;break}candidatesSeen++;
      const dedupe=candidate.identity.universeId+'|'+candidate.identity.entityKind+'|'+candidate.identity.canonicalId;if(seen.has(dedupe))continue;seen.add(dedupe);
      let match=true;for(const f of fs)if(!filterMatch(candidate,f)){match=false;break}if(!match)continue;
      const similarity=scientificSimilarity(ref,candidate.fingerprint),interest=interestingness(candidate);
      const descriptor=Object.freeze({contract:SEARCH_RESULT_CONTRACT,engineVersion:SEARCH_ENGINE_VERSION,identity:candidate.identity,properties:candidate.properties,provider:candidate.provider,provenance:candidate.provenance,atlasEntryId:candidate.atlasEntryId,similarity,interestingness:interest,exactReference:true,mutatesWorld:false,mutatesCanonicalState:false,rankingPolicy:Object.freeze({unknownScores:'AFTER_KNOWN',tieBreak:'CANONICAL_ID_ASC',providerOrder:'PROVIDER_ID_VERSION_ASC'})});
      const bytes=resultBytes(descriptor);if(bytesUsed+bytes>b.maxBytes){truncated=true;break}bytesUsed+=bytes;accepted.push(descriptor);
    }
    if(cancelled||truncated)break;
  }
  if(candidatesSeen>=b.maxCandidates)truncated=true;
  accepted.sort((a,bx)=>cmpTuple(rankTuple(a,sort),rankTuple(bx,sort)));if(accepted.length>b.maxResults){accepted.length=b.maxResults;truncated=true}
  const returned=cancelled?[]:accepted;
  return Object.freeze({contract:'ofu-prod-w2-search-response-1',engineVersion:SEARCH_ENGINE_VERSION,sort,results:Object.freeze(returned),usage:Object.freeze({providerCalls,candidatesSeen,uniqueCandidates:seen.size,resultCount:returned.length,generatedResultCount:accepted.length,bytesUsed,returnedBytes:cancelled?0:bytesUsed,maxCandidates:b.maxCandidates,maxResults:b.maxResults,maxBytes:b.maxBytes,maxProviderCalls:b.maxProviderCalls}),truncated,cancelled,cancelReason,enumeratesUniverse:false,globalIndexUsed:false,userHistoryUsed:false,networkRequired:false,mutatesWorld:false,mutatesCanonicalState:false,rankingPolicy:Object.freeze({unknownScores:'AFTER_KNOWN',tieBreak:'CANONICAL_ID_ASC',providerOrder:'PROVIDER_ID_VERSION_ASC'})});
}
