(function(root){
'use strict';
const O=root.OFU=root.OFU||{},F=O.v1x06SurfaceFrame;if(!F)throw new Error('V1X-06 surface frame required');
const VERSION='ofu-v1x-06-surface-journey-1',AUTHORITY='PRESENTATION_ONLY';
const SCALE=Object.freeze({GLOBAL:'GLOBAL_SURFACE',REGIONAL:'REGIONAL_SURFACE',LOCAL:'LOCAL_SURFACE',HUMAN:'HUMAN'});
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function copy(v){return v==null?v:JSON.parse(JSON.stringify(v))}
function scaleForAltitude(m){const a=Math.max(0,Number(m)||0);if(a>250000)return SCALE.GLOBAL;if(a>20000)return SCALE.REGIONAL;if(a>700)return SCALE.LOCAL;return SCALE.HUMAN}
function createJourney({handoff,planetRadiusMeters,initialAltitudeMeters=600000,rebaseDistanceMeters=2048,maxStepMeters=5000}={}){if(!handoff||typeof handoff!=='object')throw new TypeError('V1X-05 surface target handoff required');const radius=Number(planetRadiusMeters||handoff.planetRadiusMeters);if(!(radius>0&&Number.isFinite(radius)))throw new RangeError('planetRadiusMeters required');const target=handoff.surfaceTarget||handoff.target||handoff,planetId=String(handoff.planetId||handoff.planetIdentity||target.planetId||target.planetIdentity||'unknown-planet'),selection=copy(handoff.selection||{selectedId:planetId}),referenceFrameRef=copy(handoff.referenceFrame||handoff.referenceFrameRef||null),historyRef=copy(handoff.historyRef||handoff.history||null),provenance=copy(handoff.provenance||null),sourceAuthority=String(handoff.authority?.class||handoff.authority||target.authority?.class||target.authority||'UNSPECIFIED_SOURCE_AUTHORITY');let face=String(target.face||'PZ').toUpperCase(),u=Number(target.u??target.uv?.[0]??0),v=Number(target.v??target.uv?.[1]??0),altitude=Math.max(0,Number(target.altitudeMeters??initialAltitudeMeters)||initialAltitudeMeters),originRevision=0,localOffset=[0,0,0],distanceTravelled=0,sequence=0;const trace=[];
function event(kind,extra={}){trace.push(freeze({sequence:sequence++,kind,scale:scaleForAltitude(altitude),altitudeMeters:altitude,face,u,v,originRevision,selectionId:selection?.selectedId||selection?.canonicalId||planetId,...copy(extra)}));if(trace.length>512)trace.shift()}
function state(){return freeze({version:VERSION,authority:AUTHORITY,sourceAuthority,planetId,selection:copy(selection),referenceFrameRef:copy(referenceFrameRef),historyRef:copy(historyRef),provenance:copy(provenance),scale:scaleForAltitude(altitude),surfaceTarget:{face,u,v},altitudeMeters:altitude,originRevision,localOffsetMeters:localOffset.slice(),distanceTravelledMeters:distanceTravelled,renderPoseAuthority:AUTHORITY,claims:{ownsCanonicalCamera:false,ownsCanonicalSelection:false,ownsReferenceFrame:false,localMovementChangesCanonicalPlanet:false}})}
function zoom(delta){const d=Math.max(-8,Math.min(8,Number(delta)||0)),before=scaleForAltitude(altitude);altitude=Math.max(1,Math.min(radius*4,altitude*Math.pow(2,-d*.5)));const after=scaleForAltitude(altitude);event('SEMANTIC_SCALE_TRAVEL',{delta,beforeScale:before,afterScale:after});return state()}
function setAltitude(meters,reason='DIRECT_TRAVEL_INTENT'){altitude=Math.max(1,Math.min(radius*4,Number(meters)||1));event(reason);return state()}
function currentFrame(){return F.localFrame({planetRadiusMeters:radius,face,u,v,elevationMeters:0,originRevision,sourceAuthority})}
function move({forwardMeters=0,rightMeters=0,upMeters=0}={}){const scale=scaleForAltitude(altitude);if(scale===SCALE.GLOBAL)throw new Error('local movement requires regional/local/human materialization');let forward=Number(forwardMeters)||0,right=Number(rightMeters)||0,up=Number(upMeters)||0,mag=Math.hypot(forward,right,up);if(mag>maxStepMeters){const s=maxStepMeters/mag;forward*=s;right*=s;up*=s;mag=maxStepMeters}const frame=currentFrame(),start=frame.toPlanet(localOffset),delta=[right,up,forward],next=frame.toPlanet([localOffset[0]+delta[0],localOffset[1]+delta[1],localOffset[2]+delta[2]]),nextUnit=F.math.unit(next),nextUv=F.unitToFaceUv(nextUnit);localOffset=[localOffset[0]+delta[0],localOffset[1]+delta[1],localOffset[2]+delta[2]];distanceTravelled+=mag;let rebased=false;if(Math.hypot(localOffset[0],localOffset[2])>=rebaseDistanceMeters){face=nextUv.face;u=nextUv.u;v=nextUv.v;originRevision++;localOffset=[0,Math.max(-1000,Math.min(1000,localOffset[1])),0];rebased=true}event('LOCAL_MOVE',{requested:{forwardMeters:Number(forwardMeters)||0,rightMeters:Number(rightMeters)||0,upMeters:Number(upMeters)||0},applied:{forwardMeters:forward,rightMeters:right,upMeters:up},clamped:mag+1e-9<Math.hypot(Number(forwardMeters)||0,Number(rightMeters)||0,Number(upMeters)||0),rebased,startPlanetMeters:start,endPlanetMeters:next});return state()}
function returnTowardGlobe(){if(altitude<250001)altitude=250001;else altitude=Math.min(radius*4,altitude*2);event('REVERSE_TO_GLOBE');return state()}
function acceptSurfaceTarget(nextTarget){if(!nextTarget||typeof nextTarget!=='object')throw new TypeError('surface target required');face=String(nextTarget.face||face).toUpperCase();u=Number(nextTarget.u??nextTarget.uv?.[0]??u);v=Number(nextTarget.v??nextTarget.uv?.[1]??v);if(Number.isFinite(Number(nextTarget.altitudeMeters)))altitude=Math.max(1,Number(nextTarget.altitudeMeters));localOffset=[0,0,0];originRevision++;event('UPSTREAM_SURFACE_TARGET_ACCEPTED',{targetAuthority:String(nextTarget.authority?.class||nextTarget.authority||sourceAuthority)});return state()}
function witness(){return freeze({version:'ofu-v1x-06-camera-journey-witness-1',authority:'MEASURED_RUNTIME_EVIDENCE',sourceAuthority,planetId,selectionPreserved:true,referenceFramePreserved:referenceFrameRef!==null,historyPreserved:historyRef!==null,events:trace.slice(),final:state(),claims:{cameraTraceIsCanonicalCameraHistory:false,journeyEventsAdmittedToP4History:false}})}
event('SURFACE_HANDOFF_ACCEPTED',{handoffContract:String(handoff.contract||handoff.version||'UNSPECIFIED')});return Object.freeze({VERSION,zoom,setAltitude,move,returnTowardGlobe,acceptSurfaceTarget,state,witness,currentFrame})}
O.v1x06SurfaceJourney=Object.freeze({VERSION,AUTHORITY,SCALE,scaleForAltitude,createJourney});
})(globalThis);
