(function(root){
'use strict';
const O=root.OFU=root.OFU||{},F=O.v1x06SurfaceFrame;if(!F)throw new Error('V1X-06 surface frame required');
const VERSION='ofu-v1x-06-terrain-lod-1',AUTHORITY='PRESENTATION_ONLY';
const {clamp,dot}=F.math;
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function hash(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;return h>>>0}
function noise01(key,salt=0){let x=(hash(key)+Math.imul(salt+1,0x9e3779b1))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/4294967296}
function authorityOf(v){const a=v?.authority;return typeof a==='string'?a:String(a?.class||a?.domain||'UNSPECIFIED_SOURCE_AUTHORITY')}
function desiredLevel({planetRadiusMeters,altitudeMeters,viewportHeightPx=900,maxLevel=14,minLevel=1}={}){const r=Math.max(1,Number(planetRadiusMeters)||1),a=Math.max(.25,Number(altitudeMeters)||r),px=Math.max(240,Number(viewportHeightPx)||900);const ratio=r/a,raw=Math.log2(Math.max(1,ratio))+Math.log2(px/480)+1;return Math.max(minLevel,Math.min(maxLevel,Math.floor(raw)))}
function locate(face,u,v,level){const l=Math.max(0,Math.floor(level)),n=2**l,x=Math.max(0,Math.min(n-1,Math.floor((clamp(u,-1,1)+1)*.5*n))),y=Math.max(0,Math.min(n-1,Math.floor((clamp(v,-1,1)+1)*.5*n)));return freeze({face:String(face).toUpperCase(),level:l,x,y,key:F.tileKey(face,l,x,y)})}
function surfaceClass({cell,waterAreaPpm=0,iceAreaPpm=0,key}){if(cell?.hydrology?.surfaceState)return String(cell.hydrology.surfaceState).toUpperCase();if(cell?.hydrology?.surfaceLiquid===true)return'LIQUID';const r=noise01(key,3);if(r<clamp(Number(iceAreaPpm)||0,0,1e6)/1e6)return'ICE';if(r<clamp(Number(waterAreaPpm)||0,0,1e6)/1e6)return'LIQUID';return'SOLID'}
function materialFamily({cell,surface,key}){if(cell?.material?.materialFamily)return String(cell.material.materialFamily);if(surface==='LIQUID')return'WATER_PRESENTATION';if(surface==='ICE')return'ICE_PRESENTATION';const r=noise01(key,5);return r<.28?'ROCK_DARK_PRESENTATION':r<.62?'REGOLITH_PRESENTATION':'ROCK_LIGHT_PRESENTATION'}
function tileDescriptor({face,level,x,y,planetRadiusMeters,cellsByKey=null,waterAreaPpm=0,iceAreaPpm=0,reliefCuePpm=300000}={}){const key=F.tileKey(face,level,x,y),b=F.tileBounds(level,x,y),cell=cellsByKey?.get?.(key)||null,sourceAuthority=cell?authorityOf(cell):'NONE',physicalElevationCanonical=Boolean(cell?.physicalElevationCanonical===true&&Number.isFinite(Number(cell?.topography?.elevationMeters))),sourceElevationMeters=Number.isFinite(Number(cell?.topography?.elevationMeters))?Number(cell.topography.elevationMeters):null,presentationRelief=(-1+2*noise01(key,7))*clamp(reliefCuePpm,0,1e6)/1e6,surface=surfaceClass({cell,waterAreaPpm,iceAreaPpm,key}),material=materialFamily({cell,surface,key}),center=F.tileCenterUnit(face,level,x,y),angularSpan=b.span/Math.sqrt(1+b.uc*b.uc+b.vc*b.vc),approxSurfaceSpanMeters=Math.max(1,Number(planetRadiusMeters)||1)*angularSpan;const seams=['N','S','E','W'].map(edge=>{const neighbor=F.neighborTile(face,level,x,y,edge);return freeze({edge,neighborKey:neighbor.key,crossFace:neighbor.crossFace,mode:neighbor.crossFace?'CUBE_FACE_STITCH':'SAME_FACE_STITCH',skirtMeters:Math.max(.05,Math.min(150,approxSurfaceSpanMeters*.006)),authority:AUTHORITY,claims:{skirtIsPhysicalTerrain:false}})});return freeze({version:VERSION,key,face:String(face).toUpperCase(),level,x,y,bounds:b,centerUnit:center,approxSurfaceSpanMeters,authority:AUTHORITY,sourceAuthority,sourceCellId:cell?.cellIdentity||cell?.cellId||null,physicalElevationCanonical,sourceElevationMeters,presentationReliefCue:presentationRelief,surfaceClass:surface,materialFamily:material,seams,claims:{tileBoundaryPhysical:false,proceduralReliefPhysical:false,sourceElevationUsedAsPhysicalMeasurement:physicalElevationCanonical}})}
function visibleFromHorizon(tile,cameraUnit,altitudeMeters,planetRadiusMeters){const r=Math.max(1,Number(planetRadiusMeters)||1),a=Math.max(0,Number(altitudeMeters)||0),threshold=r/(r+a+1e-9);return dot(tile.centerUnit,cameraUnit)>=threshold-.3}
function selectTerrain({planetRadiusMeters,anchor={face:'PZ',u:0,v:0},altitudeMeters=10000,viewportHeightPx=900,maxTiles=81,maxLevel=14,minLevel=1,cells=[],waterAreaPpm=0,iceAreaPpm=0,reliefCuePpm=300000}={}){const level=desiredLevel({planetRadiusMeters,altitudeMeters,viewportHeightPx,maxLevel,minLevel}),center=locate(anchor.face,anchor.u,anchor.v,level),n=2**level,radius=Math.max(1,Math.min(8,Math.floor(Math.sqrt(Math.max(1,maxTiles)))/2)),cellsByKey=new Map();for(const cell of cells||[]){if(!cell)continue;const key=cell.tileKey||cell.key||(cell.face!==undefined&&cell.level!==undefined&&cell.x!==undefined&&cell.y!==undefined?F.tileKey(cell.face,cell.level,cell.x,cell.y):null);if(key)cellsByKey.set(String(key),cell)}const cameraUnit=F.faceUvToUnit(anchor.face,anchor.u,anchor.v),tiles=[];for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){if(tiles.length>=maxTiles)break;const x=center.x+dx,y=center.y+dy;if(x<0||y<0||x>=n||y>=n)continue;const tile=tileDescriptor({face:center.face,level,x,y,planetRadiusMeters,cellsByKey,waterAreaPpm,iceAreaPpm,reliefCuePpm});if(visibleFromHorizon(tile,cameraUnit,altitudeMeters,planetRadiusMeters))tiles.push(tile)}tiles.sort((a,b)=>a.key.localeCompare(b.key));const crossFaceSeams=tiles.reduce((sum,t)=>sum+t.seams.filter(s=>s.crossFace).length,0),estimatedBytes=tiles.length*896;return freeze({version:VERSION,authority:AUTHORITY,level,anchor:center,tiles,culling:{candidateGrid:(radius*2+1)**2,visibleTiles:tiles.length,horizonCull:true},seams:{strategy:'DUPLICATED_EDGE_VERTICES_PLUS_SKIRTS',crossFaceSeams,crackFreeClaim:'PRESENTATION_TOPOLOGY_ONLY'},resources:{estimatedDescriptorBytes:estimatedBytes,tileCount:tiles.length},claims:{lodIsScientificResolution:false,cullingChangesCanonicalState:false}})}
function createTileCache({maxTiles=192,maxBytes=4*1024*1024}={}){const cap=Math.max(1,Math.floor(maxTiles)),byteCap=Math.max(1024,Math.floor(maxBytes));const entries=new Map();let bytes=0,tick=0,evictions=0;function evict(){while(entries.size>cap||bytes>byteCap){let oldest=null;for(const [key,e] of entries)if(!oldest||e.lastUse<oldest[1].lastUse)oldest=[key,e];if(!oldest)break;entries.delete(oldest[0]);bytes-=oldest[1].bytes;evictions++}}function touch(tile,payloadBytes=896){const key=tile?.key;if(!key)throw new TypeError('tile key required');const size=Math.max(64,Math.floor(Number(payloadBytes)||896)),prev=entries.get(key);tick++;if(prev){bytes-=prev.bytes;prev.bytes=size;prev.lastUse=tick;prev.level=tile.level;bytes+=size}else{entries.set(key,{bytes:size,lastUse:tick,level:tile.level});bytes+=size}evict();return entries.has(key)}function retain(keys){const keep=new Set(keys||[]);for(const [key,e] of [...entries])if(!keep.has(key)){entries.delete(key);bytes-=e.bytes;evictions++}}function snapshot(){const byLevel={};for(const e of entries.values())byLevel[e.level]=(byLevel[e.level]||0)+1;return freeze({version:'ofu-v1x-06-tile-cache-witness-1',authority:'MEASURED_RUNTIME_EVIDENCE',entries:entries.size,bytes,maxTiles:cap,maxBytes:byteCap,evictions,byLevel})}return Object.freeze({touch,retain,snapshot})}
function seamWitness(selection){let sameFace=0,crossFace=0,missing=0;const keys=new Set(selection.tiles.map(t=>t.key));for(const tile of selection.tiles)for(const seam of tile.seams){if(seam.crossFace)crossFace++;else sameFace++;if(!seam.neighborKey)missing++}return freeze({version:'ofu-v1x-06-seam-witness-1',authority:'MEASURED_RUNTIME_EVIDENCE',tiles:selection.tiles.length,sameFaceEdges:sameFace,crossFaceEdges:crossFace,missingNeighborKeys:missing,strategy:selection.seams.strategy,allEdgesAccounted:missing===0,claims:{crackFreeGpuRasterizationVerified:false}})}
O.v1x06TerrainLod=Object.freeze({VERSION,AUTHORITY,desiredLevel,locate,tileDescriptor,selectTerrain,createTileCache,seamWitness});
})(globalThis);
