(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-v2x-06-surface-address-1';
const AUTHORITY='DERIVED';
const MICRO_DEG=1000000;
const FACE_NAMES=Object.freeze(['PX','NX','PY','NY','PZ','NZ']);
const MAX_LEVEL=20;
const EPS=1e-12;
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0))}
function unit(v){const n=Math.hypot(v[0],v[1],v[2]);if(!(n>EPS))throw new RangeError('non-zero vector required');return [v[0]/n,v[1]/n,v[2]/n]}
function assertPlanet(id){if(typeof id!=='string'||id.length<1||id.length>256)throw new TypeError('planetIdentity required');return id}
function assertFace(face){const f=String(face||'').toUpperCase();if(!FACE_NAMES.includes(f))throw new RangeError('unsupported cube face '+face);return f}
function assertLevel(level){const l=Math.floor(Number(level));if(!Number.isFinite(l)||l<0||l>MAX_LEVEL)throw new RangeError('level out of range');return l}
function wrapLonMicro(v){let x=Math.round(Number(v)||0);const span=360*MICRO_DEG,half=180*MICRO_DEG;x=((x+half)%span+span)%span-half;return x}
function normalizeLatLon(latMicroDeg,lonMicroDeg){let lat=Math.round(clamp(latMicroDeg,-90*MICRO_DEG,90*MICRO_DEG));let lon=wrapLonMicro(lonMicroDeg);if(Math.abs(lat)===90*MICRO_DEG)lon=0;return freeze({latMicroDeg:lat,lonMicroDeg:lon})}
function latLonToUnit(latMicroDeg,lonMicroDeg){const p=normalizeLatLon(latMicroDeg,lonMicroDeg),lat=p.latMicroDeg/MICRO_DEG*Math.PI/180,lon=p.lonMicroDeg/MICRO_DEG*Math.PI/180,c=Math.cos(lat);return freeze([c*Math.cos(lon),Math.sin(lat),c*Math.sin(lon)])}
function unitToLatLon(vector){const p=unit(vector),lat=Math.asin(clamp(p[1],-1,1))*180/Math.PI,lon=Math.atan2(p[2],p[0])*180/Math.PI;return normalizeLatLon(Math.round(lat*MICRO_DEG),Math.round(lon*MICRO_DEG))}
function faceUvRaw(face,u,v){const f=assertFace(face),a=Number(u)||0,b=Number(v)||0;let p;if(f==='PX')p=[1,b,-a];else if(f==='NX')p=[-1,b,a];else if(f==='PY')p=[a,1,-b];else if(f==='NY')p=[a,-1,b];else if(f==='PZ')p=[a,b,1];else p=[-a,b,-1];return unit(p)}
function faceUvToUnit(face,u,v){return freeze(faceUvRaw(face,clamp(u,-1,1),clamp(v,-1,1)))}
function unitToFaceUv(vector){const p=unit(vector),ax=Math.abs(p[0]),ay=Math.abs(p[1]),az=Math.abs(p[2]);let face,u,v;if(ax>=ay&&ax>=az){if(p[0]>=0){face='PX';u=-p[2]/ax;v=p[1]/ax}else{face='NX';u=p[2]/ax;v=p[1]/ax}}else if(ay>=ax&&ay>=az){if(p[1]>=0){face='PY';u=p[0]/ay;v=-p[2]/ay}else{face='NY';u=p[0]/ay;v=p[2]/ay}}else if(p[2]>=0){face='PZ';u=p[0]/az;v=p[1]/az}else{face='NZ';u=-p[0]/az;v=p[1]/az}return freeze({face,u:clamp(u,-1,1),v:clamp(v,-1,1)})}
function tileBounds(level,x,y){const l=assertLevel(level),n=2**l,ix=Math.max(0,Math.min(n-1,Math.floor(Number(x)||0))),iy=Math.max(0,Math.min(n-1,Math.floor(Number(y)||0))),span=2/n,u0=-1+ix*span,v0=-1+iy*span;return freeze({level:l,n,x:ix,y:iy,u0,v0,u1:u0+span,v1:v0+span,uc:u0+span/2,vc:v0+span/2,span})}
function patchIdentity(planetIdentity,face,level,x,y){const b=tileBounds(level,x,y);return `surface-patch:${encodeURIComponent(assertPlanet(planetIdentity))}:${assertFace(face)}:${b.level}:${b.x}:${b.y}`}
function locationIdentity(planetIdentity,latMicroDeg,lonMicroDeg){const p=normalizeLatLon(latMicroDeg,lonMicroDeg);return `surface-location:${encodeURIComponent(assertPlanet(planetIdentity))}:${p.latMicroDeg}:${p.lonMicroDeg}`}
function patchAt(planetIdentity,face,level,x,y){const b=tileBounds(level,x,y),f=assertFace(face),id=patchIdentity(planetIdentity,f,b.level,b.x,b.y),parent=b.level?patchIdentity(planetIdentity,f,b.level-1,Math.floor(b.x/2),Math.floor(b.y/2)):null;return freeze({version:VERSION,authority:AUTHORITY,planetIdentity:assertPlanet(planetIdentity),patchIdentity:id,parentPatchIdentity:parent,face:f,level:b.level,x:b.x,y:b.y,bounds:b,claims:{patchIdentityCanonical:false,spatialAddressDerived:true}})}
function locate(planetIdentity,latMicroDeg,lonMicroDeg,level=0){const planet=assertPlanet(planetIdentity),p=normalizeLatLon(latMicroDeg,lonMicroDeg),u3=latLonToUnit(p.latMicroDeg,p.lonMicroDeg),q=unitToFaceUv(u3),l=assertLevel(level),n=2**l,x=Math.max(0,Math.min(n-1,Math.floor((q.u+1)*.5*n))),y=Math.max(0,Math.min(n-1,Math.floor((q.v+1)*.5*n))),patch=patchAt(planet,q.face,l,x,y),b=patch.bounds,du=b.span?clamp((q.u-b.u0)/b.span,0,1):0,dv=b.span?clamp((q.v-b.v0)/b.span,0,1):0;return freeze({version:VERSION,authority:AUTHORITY,planetIdentity:planet,locationIdentity:locationIdentity(planet,p.latMicroDeg,p.lonMicroDeg),latMicroDeg:p.latMicroDeg,lonMicroDeg:p.lonMicroDeg,unit:u3,face:q.face,u:q.u,v:q.v,level:l,patchIdentity:patch.patchIdentity,parentPatchIdentity:patch.parentPatchIdentity,x:patch.x,y:patch.y,localUv:[du,dv],claims:{locationIdentityIndependentOfLod:true,selectionAuthorityOwned:false,geodeticMeasurementClaim:false}})}
function atLevel(address,level){if(!address||typeof address.planetIdentity!=='string')throw new TypeError('surface address required');return locate(address.planetIdentity,address.latMicroDeg,address.lonMicroDeg,level)}
function parentPatch(patch){if(!patch||patch.level===undefined)throw new TypeError('patch required');if(patch.level===0)return null;return patchAt(patch.planetIdentity,patch.face,patch.level-1,Math.floor(patch.x/2),Math.floor(patch.y/2))}
function childPatches(patch){if(!patch||patch.level===undefined)throw new TypeError('patch required');if(patch.level>=MAX_LEVEL)return freeze([]);const l=patch.level+1,x=patch.x*2,y=patch.y*2;return freeze([patchAt(patch.planetIdentity,patch.face,l,x,y),patchAt(patch.planetIdentity,patch.face,l,x+1,y),patchAt(patch.planetIdentity,patch.face,l,x,y+1),patchAt(patch.planetIdentity,patch.face,l,x+1,y+1)])}
function neighborPatch(patch,edge){const e=String(edge||'').toUpperCase();if(!['N','S','E','W'].includes(e))throw new RangeError('edge must be N/S/E/W');const b=patch.bounds||tileBounds(patch.level,patch.x,patch.y),step=b.span*.500001;let u=b.uc,v=b.vc;if(e==='N')v=b.v1+step;else if(e==='S')v=b.v0-step;else if(e==='E')u=b.u1+step;else u=b.u0-step;const q=unitToFaceUv(faceUvRaw(patch.face,u,v)),n=2**patch.level,x=Math.max(0,Math.min(n-1,Math.floor((q.u+1)*.5*n))),y=Math.max(0,Math.min(n-1,Math.floor((q.v+1)*.5*n)));return patchAt(patch.planetIdentity,q.face,patch.level,x,y)}
function patchPointUnit(patch,s,t){const b=patch.bounds||tileBounds(patch.level,patch.x,patch.y),u=b.u0+b.span*clamp(s,0,1),v=b.v0+b.span*clamp(t,0,1);return faceUvToUnit(patch.face,u,v)}
function edgeUnits(patch,edge,resolution=17){const r=Math.max(2,Math.min(129,Math.floor(Number(resolution)||17))),e=String(edge||'').toUpperCase(),out=[];for(let i=0;i<r;i++){const t=i/(r-1);if(e==='N')out.push(patchPointUnit(patch,t,1));else if(e==='S')out.push(patchPointUnit(patch,t,0));else if(e==='E')out.push(patchPointUnit(patch,1,t));else if(e==='W')out.push(patchPointUnit(patch,0,t));else throw new RangeError('edge must be N/S/E/W')}return freeze(out)}
function edgePointKeys(patch,edge,resolution=17){return freeze(edgeUnits(patch,edge,resolution).map(v=>v.map(x=>Math.round(x*1e12)).join(',')).sort())}
function oppositeEdgeWitness(patch,edge,resolution=17){const neighbor=neighborPatch(patch,edge),a=edgePointKeys(patch,edge,resolution),edges=['N','S','E','W'];let best=null;for(const candidate of edges){const b=edgePointKeys(neighbor,candidate,resolution),matches=a.length===b.length&&a.every((v,i)=>v===b[i]);if(matches){best=candidate;break}}return freeze({version:'ofu-v2x-06-edge-address-witness-1',authority:'MEASURED_RUNTIME_EVIDENCE',patchIdentity:patch.patchIdentity,edge,neighborPatchIdentity:neighbor.patchIdentity,neighborEdge:best,crossFace:neighbor.face!==patch.face,pointCount:a.length,coincident:best!==null})}
function reconcileLocation(a,b){if(!a||!b)throw new TypeError('two surface addresses required');return freeze({version:'ofu-v2x-06-location-reconcile-1',authority:'MEASURED_RUNTIME_EVIDENCE',samePlanet:a.planetIdentity===b.planetIdentity,sameLocationIdentity:a.locationIdentity===b.locationIdentity,sameLatLon:a.latMicroDeg===b.latMicroDeg&&a.lonMicroDeg===b.lonMicroDeg,lodChanged:a.level!==b.level,pass:a.planetIdentity===b.planetIdentity&&a.locationIdentity===b.locationIdentity&&a.latMicroDeg===b.latMicroDeg&&a.lonMicroDeg===b.lonMicroDeg})}
O.v2x06SurfaceAddress=Object.freeze({VERSION,AUTHORITY,MICRO_DEG,FACE_NAMES,MAX_LEVEL,normalizeLatLon,latLonToUnit,unitToLatLon,faceUvToUnit,unitToFaceUv,tileBounds,patchIdentity,locationIdentity,patchAt,locate,atLevel,parentPatch,childPatches,neighborPatch,patchPointUnit,edgeUnits,edgePointKeys,oppositeEdgeWitness,reconcileLocation});
})(globalThis);
