(function(root){
'use strict';
const O=root.OFU=root.OFU||{},A=O.v2x06SurfaceAddress,G=O.v2x06Geography;
if(!A||!G)throw new Error('V2X-06 surface address/geography required');
const VERSION='ofu-v2x-06-hydrology-1';
const AUTHORITY='MODEL_DERIVED_SIMULATION';
const PPM=1000000,MAX_TRACE_STEPS=48,MAX_NETWORK_RIVERS=16;
const DIRS=Object.freeze([
 Object.freeze({id:'N',dLat:1,dLon:0,bearingDeg:0}),Object.freeze({id:'NE',dLat:1,dLon:1,bearingDeg:45}),
 Object.freeze({id:'E',dLat:0,dLon:1,bearingDeg:90}),Object.freeze({id:'SE',dLat:-1,dLon:1,bearingDeg:135}),
 Object.freeze({id:'S',dLat:-1,dLon:0,bearingDeg:180}),Object.freeze({id:'SW',dLat:-1,dLon:-1,bearingDeg:225}),
 Object.freeze({id:'W',dLat:0,dLon:-1,bearingDeg:270}),Object.freeze({id:'NW',dLat:1,dLon:-1,bearingDeg:315})
]);
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0))}
function ppm(v){return Math.round(clamp(v,0,PPM))}
function hash32(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function createHydrology(model,options={}){
 if(!model||typeof model.sample!=='function')throw new TypeError('geography model required');
 const stepMicroDeg=Math.max(5000,Math.min(1000000,Math.round(Number(options.stepMicroDeg)||250000))),maxTraceSteps=Math.max(4,Math.min(MAX_TRACE_STEPS,Math.floor(Number(options.maxTraceSteps)||32)));
 function neighbors(address){const out=[];for(const d of DIRS){const a=A.locate(model.planetIdentity,address.latMicroDeg+d.dLat*stepMicroDeg,address.lonMicroDeg+d.dLon*stepMicroDeg,address.level),g=model.sample(a);out.push(freeze({direction:d.id,bearingDeg:d.bearingDeg,address:a,reliefCuePpm:g.reliefCuePpm,surfaceClass:g.surfaceClass,coastDeltaPpm:g.coastDeltaPpm,basinIdentity:g.basinIdentity}))}return freeze(out)}
 function sample(address){const g=model.sample(address);if(model.noSolidSurface)return freeze({version:VERSION,authority:model.AUTHORITY,presentationAssumptions:model.presentationAssumptions,planetIdentity:model.planetIdentity,locationIdentity:address.locationIdentity,contextClass:'NO_SOLID_SURFACE_REFERENCE',surfaceClass:'NO_SOLID_SURFACE',basinIdentity:null,flowDirection:null,flowBearingDeg:null,downhillDropCuePpm:0,waterActivityPpm:0,accumulationCuePpm:0,riverOrder:0,lakeCue:false,wetlandCue:false,coastlineCue:false,sedimentTransportCuePpm:0,cryosphereCuePpm:0,aridityCuePpm:model.aridityPpm,claims:{physicalDrainageNetwork:false,watershedBoundaryCanonical:false,measuredHydrology:false}});
  const ns=neighbors(address),low=ns.slice().sort((a,b)=>a.reliefCuePpm-b.reliefCuePpm||a.direction.localeCompare(b.direction))[0],drop=Math.max(0,g.reliefCuePpm-low.reliefCuePpm),localMin=drop===0,wetBase=ppm(model.presentationInputs.waterAreaPpm*(1-model.presentationInputs.aridityPpm/PPM*.75)),concavity=ppm(Math.max(0,-g.coastDeltaPpm)*.55+Math.max(0,-g.reliefCuePpm)*.15),coastal=ppm(Math.max(0,180000-Math.abs(g.coastDeltaPpm))*4.2),waterActivityPpm=ppm(wetBase*.45+concavity*.28+coastal*.27),accumulationCuePpm=ppm(waterActivityPpm*.74+drop*.18+Math.max(0,-g.coastDeltaPpm)*.22);
  let riverOrder=0;if(g.surfaceClass==='SOLID'&&drop>450&&waterActivityPpm>120000){if(accumulationCuePpm>700000)riverOrder=5;else if(accumulationCuePpm>520000)riverOrder=4;else if(accumulationCuePpm>360000)riverOrder=3;else if(accumulationCuePpm>180000)riverOrder=2;else riverOrder=1}
  const coastlineCue=Math.abs(g.coastDeltaPpm)<85000,slope=model.slopeCue(address).slopePpm,flat=slope<90000,lakeCue=g.surfaceClass==='SOLID'&&waterActivityPpm>360000&&(localMin||(String(g.provinceClass).includes('BASIN')&&slope<55000)),wetlandCue=g.surfaceClass==='SOLID'&&flat&&waterActivityPpm>330000&&(coastlineCue||lakeCue||riverOrder>=2),sedimentTransportCuePpm=ppm(model.erosionActivityPpm*(drop/PPM*.45+accumulationCuePpm/PPM*.55));
  let contextClass='MODELED_DRY_SURFACE_CONTEXT';if(g.surfaceClass==='LIQUID')contextClass='MODELED_SURFACE_LIQUID_CONTEXT';else if(lakeCue)contextClass='MODELED_LAKE_DEPRESSION_CONTEXT';else if(wetlandCue)contextClass='MODELED_WETLAND_CONTEXT';else if(riverOrder>0)contextClass='MODELED_DRAINAGE_CONTEXT';else if(g.cryosphereCuePpm>600000)contextClass='MODELED_CRYOSPHERE_CONTEXT';
  return freeze({version:VERSION,authority:model.AUTHORITY,presentationAssumptions:model.presentationAssumptions,planetIdentity:model.planetIdentity,locationIdentity:address.locationIdentity,contextClass,surfaceClass:g.surfaceClass,basinIdentity:g.basinIdentity,flowDirection:drop>0?low.direction:null,flowBearingDeg:drop>0?low.bearingDeg:null,downhillLocationIdentity:drop>0?low.address.locationIdentity:null,downhillDropCuePpm:ppm(drop),waterActivityPpm,accumulationCuePpm,riverOrder,lakeCue,wetlandCue,coastlineCue,sedimentTransportCuePpm,cryosphereCuePpm:g.cryosphereCuePpm,aridityCuePpm:g.aridityCuePpm,claims:{physicalDrainageNetwork:false,watershedBoundaryCanonical:false,measuredHydrology:false,riverOrderIsModelCue:true,lakeBoundaryCanonical:false}})
 }
 function traceRiver(startAddress,options2={}){const limit=Math.max(1,Math.min(maxTraceSteps,Math.floor(Number(options2.maxSteps)||maxTraceSteps))),points=[],seen=new Set();let current=A.atLevel(startAddress,Math.max(0,startAddress.level||0)),stopReason='STEP_BOUND';const startSample=sample(current),riverIdentity=`river:${encodeURIComponent(model.planetIdentity)}:${startSample.basinIdentity||'none'}:${Math.round(current.latMicroDeg/stepMicroDeg)}:${Math.round(current.lonMicroDeg/stepMicroDeg)}`;for(let i=0;i<limit;i++){const h=sample(current),g=model.sample(current);points.push(freeze({locationIdentity:current.locationIdentity,latMicroDeg:current.latMicroDeg,lonMicroDeg:current.lonMicroDeg,reliefCuePpm:g.reliefCuePpm,surfaceClass:g.surfaceClass,riverOrder:h.riverOrder,basinIdentity:h.basinIdentity}));if(g.surfaceClass==='LIQUID'){stopReason='REACHED_SURFACE_LIQUID';break}if(!h.downhillLocationIdentity){stopReason=h.lakeCue?'LOCAL_DEPRESSION_LAKE':'LOCAL_MINIMUM';break}if(seen.has(current.locationIdentity)){stopReason='LOOP_GUARD';break}seen.add(current.locationIdentity);const d=DIRS.find(x=>x.id===h.flowDirection);current=A.locate(model.planetIdentity,current.latMicroDeg+d.dLat*stepMicroDeg,current.lonMicroDeg+d.dLon*stepMicroDeg,current.level)}return freeze({version:'ofu-v2x-06-river-trace-1',authority:model.AUTHORITY,presentationAssumptions:model.presentationAssumptions,riverIdentity,basinIdentity:startSample.basinIdentity,points,stopReason,bounds:{maxTraceSteps:limit,stepMicroDeg,materializedPoints:points.length},claims:{physicalRiverPath:false,measuredFlowRate:false,canonicalWatershed:false}})}
 function networkForPatch(patch,options2={}){if(model.noSolidSurface)return freeze({version:'ofu-v2x-06-drainage-network-1',authority:model.AUTHORITY,presentationAssumptions:model.presentationAssumptions,patchIdentity:patch.patchIdentity,rivers:[],lakes:[],wetlands:[],coastlineSeeds:[],bounds:{maxRivers:0,seedGrid:0},claims:{physicalDrainageNetwork:false}});const maxRivers=Math.max(1,Math.min(MAX_NETWORK_RIVERS,Math.floor(Number(options2.maxRivers)||8))),seedGrid=Math.max(3,Math.min(7,Math.floor(Number(options2.seedGrid)||5))),candidates=[],lakes=[],wetlands=[],coastlineSeeds=[];for(let y=0;y<seedGrid;y++)for(let x=0;x<seedGrid;x++){const u=A.patchPointUnit(patch,(x+.5)/seedGrid,(y+.5)/seedGrid),ll=A.unitToLatLon(u),a=A.locate(model.planetIdentity,ll.latMicroDeg,ll.lonMicroDeg,patch.level),h=sample(a);if(h.lakeCue)lakes.push(a.locationIdentity);if(h.wetlandCue)wetlands.push(a.locationIdentity);if(h.coastlineCue)coastlineSeeds.push(a.locationIdentity);if(h.riverOrder>=2)candidates.push({score:h.accumulationCuePpm,hash:hash32(a.locationIdentity),address:a})}candidates.sort((a,b)=>b.score-a.score||a.hash-b.hash);const rivers=[],seen=new Set();for(const c of candidates){if(rivers.length>=maxRivers)break;const r=traceRiver(c.address);if(seen.has(r.riverIdentity))continue;seen.add(r.riverIdentity);rivers.push(r)}return freeze({version:'ofu-v2x-06-drainage-network-1',authority:model.AUTHORITY,presentationAssumptions:model.presentationAssumptions,patchIdentity:patch.patchIdentity,rivers,lakes:[...new Set(lakes)].slice(0,32),wetlands:[...new Set(wetlands)].slice(0,32),coastlineSeeds:[...new Set(coastlineSeeds)].slice(0,64),bounds:{maxRivers,seedGrid,maxTraceSteps,materializedRivers:rivers.length},claims:{physicalDrainageNetwork:false,watershedBoundaryCanonical:false,riverHierarchyModelDerived:true}})}
 function reconcileLocation(a,b){const ha=sample(a),hb=sample(b),same=a.locationIdentity===b.locationIdentity;return freeze({version:'ofu-v2x-06-hydrology-reconcile-1',authority:'MEASURED_RUNTIME_EVIDENCE',sameLocationIdentity:same,sameBasin:ha.basinIdentity===hb.basinIdentity,sameFlowDirection:ha.flowDirection===hb.flowDirection,sameRiverOrder:ha.riverOrder===hb.riverOrder,pass:same&&ha.basinIdentity===hb.basinIdentity&&ha.flowDirection===hb.flowDirection&&ha.riverOrder===hb.riverOrder})}
 return Object.freeze({VERSION,AUTHORITY,model,stepMicroDeg,maxTraceSteps,neighbors,sample,traceRiver,networkForPatch,reconcileLocation,descriptor:()=>freeze({version:VERSION,authority:model.AUTHORITY,presentationAssumptions:model.presentationAssumptions,planetIdentity:model.planetIdentity,bounds:{stepMicroDeg,maxTraceSteps,maxNetworkRivers:MAX_NETWORK_RIVERS,globalEnumeration:false},claims:{physicalDrainageNetwork:false,measuredHydrology:false,canonicalWatershed:false}})});
}
O.v2x06Hydrology=Object.freeze({VERSION,AUTHORITY,PPM,MAX_TRACE_STEPS,MAX_NETWORK_RIVERS,createHydrology});
})(globalThis);
