(function(root){
'use strict';
const O=root.OFU=root.OFU||{},VERSION='ofu-render-webgpu-pipeline-1',AUTHORITY='PRESENTATION_ONLY';
function fail(c,m){const e=new Error(m);e.code=c;throw e}function safe(v,l,min=0,max=0x7fffffff){v=Number(v);if(!Number.isSafeInteger(v)||v<min||v>max)fail('BOUNDS','invalid '+l);return v}
const WGSL=`struct Uniforms{color:vec4f};@group(0) @binding(0) var<uniform> u:Uniforms;struct Out{@builtin(position) pos:vec4f};@vertex fn vs(@location(0) p:vec2f)->Out{var o:Out;o.pos=vec4f(p,0.,1.);return o;}@fragment fn fs()->@location(0) vec4f{return u.color;}`;
function create({navigatorRef=root.navigator,strictFallback,maxBufferBytes=67108864,maxBuffers=128}={}){
 if(typeof strictFallback!=='function')fail('FALLBACK','strict WebGL2 fallback required');safe(maxBufferBytes,'maxBufferBytes',1,1073741824);safe(maxBuffers,'maxBuffers',1,4096);
 let adapter=null,device=null,status='UNINITIALIZED',losses=0,renders=0,fallbacks=0,lastError=null,generation=0,resources=new Map(),trackedBytes=0,pipelineCache=new Map();
 function semantic(a,b){for(const k of ['sceneId','selectionId','semanticSignature'])if(a?.[k]!==b?.[k])fail('PARITY','semantic input changed');return true}
 function disposeResources(){resources.clear();trackedBytes=0;pipelineCache.clear()}
 async function initialize(){if(status==='READY'&&device)return snapshot();try{if(!navigatorRef?.gpu?.requestAdapter){status='UNAVAILABLE';return snapshot()}adapter=await navigatorRef.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter){status='UNAVAILABLE';return snapshot()}device=await adapter.requestDevice({requiredFeatures:[],requiredLimits:{}});generation++;status='READY';device.lost?.then?.(info=>{losses++;lastError=String(info?.message||'device lost');status='DEVICE_LOST';device=null;disposeResources()});return snapshot()}catch(e){lastError=String(e?.message||e);status='FAILED';device=null;disposeResources();return snapshot()}}
 function buffer(id,{size,usage,mappedAtCreation=false}={}){if(status!=='READY'||!device)fail('DEVICE','not ready');id=String(id);if(resources.has(id)||resources.size>=maxBuffers)fail('BUDGET','buffer count');size=safe(size,'buffer size',4,maxBufferBytes);if(trackedBytes+size>maxBufferBytes)fail('BUDGET','buffer bytes');const handle=device.createBuffer({size,usage,mappedAtCreation});resources.set(id,{kind:'buffer',handle,size});trackedBytes+=size;return handle}
 function release(id){const r=resources.get(String(id));if(!r)return false;try{r.handle.destroy?.()}finally{resources.delete(String(id));trackedBytes-=r.size||0}return true}
 function trianglePipeline({format='bgra8unorm'}={}){if(status!=='READY'||!device)fail('DEVICE','not ready');const key=String(format);if(pipelineCache.has(key))return pipelineCache.get(key);const module=device.createShaderModule({code:WGSL,label:'ofu-v2x13-presentation'});const p=device.createRenderPipeline({label:'ofu-v2x13-triangle',layout:'auto',vertex:{module,entryPoint:'vs',buffers:[{arrayStride:8,attributes:[{shaderLocation:0,offset:0,format:'float32x2'}]}]},fragment:{module,entryPoint:'fs',targets:[{format:key}]},primitive:{topology:'triangle-list',cullMode:'back'}});pipelineCache.set(key,p);return p}
 async function render(input,{enhancedRender=null}={}){renders++;if(status==='UNINITIALIZED'||status==='DEVICE_LOST'||status==='FAILED')await initialize();if(status==='READY'&&device&&typeof enhancedRender==='function')try{const out=await enhancedRender({device,adapter,input,pipeline:trianglePipeline,buffer,release});semantic(input,out);return Object.freeze({...out,backend:'webgpu-enhanced',authority:AUTHORITY,scientificTruthChanged:false})}catch(e){lastError=String(e?.message||e)}fallbacks++;const reason=lastError||(status!=='READY'?status:'NO_ENHANCED_RENDERER');const out=await strictFallback(input);semantic(input,out);return Object.freeze({...out,backend:out.backend||'webgl2',enhancedFallbackReason:reason})}
 function dispose(){for(const id of [...resources.keys()])release(id);device=null;adapter=null;status='DISPOSED';pipelineCache.clear();return snapshot()}
 function snapshot(){return Object.freeze({version:VERSION,authority:AUTHORITY,status,apiExposed:!!navigatorRef?.gpu,deviceReady:!!device,generation,losses,renders,fallbacks,trackedBufferBytes:trackedBytes,liveResources:resources.size,lastError,baselineRequired:'WEBGL2_STRICT',scientificStateAccess:'NONE',physicalDriverVramBytes:'NOT_MEASURABLE_PORTABLY'})}
 return Object.freeze({initialize,buffer,release,trianglePipeline,render,dispose,snapshot,semantic});
}
O.renderWebGPUPipeline=Object.freeze({VERSION,AUTHORITY,WGSL,create});
})(typeof globalThis!=='undefined'?globalThis:this);
