(function(root){
'use strict';
const O=root.OFU=root.OFU||{},VERSION='ofu-render-webgpu-primitive-pass-2',AUTHORITY='PRESENTATION_ONLY';
function fail(c,m){const e=new Error(m);e.code=c;throw e}function bound(v,name,min,max){v=Number(v);if(!Number.isSafeInteger(v)||v<min||v>max)fail('BUDGET','invalid '+name);return v}
const DEFAULT_WGSL=`@vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f{var p=array<vec2f,3>(vec2f(-1.,-1.),vec2f(3.,-1.),vec2f(-1.,3.));return vec4f(p[i],0.,1.);}\n@fragment fn fs()->@location(0) vec4f{return vec4f(0.,0.,0.,1.);}`;
function createFullscreenPass(device,{format='bgra8unorm',label='ofu.presentation.fullscreen',wgsl=DEFAULT_WGSL,loadOp='load',storeOp='store'}={}){if(!device||typeof device.createShaderModule!=='function'||typeof device.createRenderPipeline!=='function')fail('WEBGPU','device required');const module=device.createShaderModule({label:label+'.shader',code:String(wgsl)}),pipeline=device.createRenderPipeline({label,layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format}]},primitive:{topology:'triangle-list',cullMode:'none'}});let draws=0,disposed=false;
 function render({encoder,targetView,clearValue={r:0,g:0,b:0,a:1}}={}){if(disposed)fail('STATE','disposed');if(!encoder||typeof encoder.beginRenderPass!=='function'||!targetView)fail('WEBGPU','encoder/target required');const pass=encoder.beginRenderPass({label:label+'.pass',colorAttachments:[{view:targetView,loadOp,storeOp,clearValue}]});pass.setPipeline(pipeline);pass.draw(3,1,0,0);pass.end();draws++;return Object.freeze({version:VERSION,authority:AUTHORITY,backend:'webgpu-enhanced',drawCalls:1,vertices:3,scientificTruthChanged:false,semanticStateAccess:'NONE'})}
 function dispose(){disposed=true;return snapshot()}function snapshot(){return Object.freeze({version:VERSION,authority:AUTHORITY,format,label,draws,disposed,scientificStateAccess:'NONE',baselineRequired:'WEBGL2_STRICT'})}return Object.freeze({render,dispose,snapshot})}
function createBufferOwner(device,{maxBuffers=128,maxTrackedBytes=67108864}={}){if(!device||typeof device.createBuffer!=='function')fail('WEBGPU','device required');maxBuffers=bound(maxBuffers,'maxBuffers',1,4096);maxTrackedBytes=bound(maxTrackedBytes,'maxTrackedBytes',1,1073741824);const live=new Map;let bytes=0,created=0,destroyed=0,invalidated=0,generation=1,valid=true,disposed=false;function create(id,{size,usage,mappedAtCreation=false}={}){id=String(id);size=Number(size);if(disposed)fail('STATE','owner disposed');if(!valid)fail('DEVICE_LOST','owner invalid');if(!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,159}$/.test(id)||!Number.isSafeInteger(size)||size<1||size>maxTrackedBytes||live.has(id)||live.size>=maxBuffers||bytes+size>maxTrackedBytes)fail('BUDGET','buffer request');const b=device.createBuffer({label:id,size,usage,mappedAtCreation});if(!b||typeof b.destroy!=='function')fail('ALLOCATE','buffer');live.set(id,{buffer:b,size});bytes+=size;created++;return b}function release(id){const r=live.get(String(id));if(!r)return false;r.buffer.destroy();live.delete(String(id));bytes-=r.size;destroyed++;return true}function deviceLost(){for(const r of live.values())try{r.buffer.destroy()}catch{}invalidated+=live.size;live.clear();bytes=0;valid=false;return snapshot()}function restore(next){if(disposed||valid||!next||typeof next.createBuffer!=='function')fail('STATE','invalid restore');device=next;generation++;valid=true;return snapshot()}function dispose(){if(disposed)return snapshot();if(valid)for(const k of [...live.keys()])release(k);valid=false;disposed=true;return snapshot()}function snapshot(){return Object.freeze({version:'ofu-render-webgpu-buffer-owner-2',authority:AUTHORITY,generation,valid,disposed,liveBuffers:live.size,trackedBytes:bytes,maxBuffers,maxTrackedBytes,created,destroyed,invalidated,accountingExact:created===destroyed+invalidated+live.size,physicalDriverVramBytes:'NOT_MEASURABLE_PORTABLY'})}return Object.freeze({create,release,deviceLost,restore,dispose,snapshot})}
O.renderWebGPUPrimitive=Object.freeze({VERSION,AUTHORITY,DEFAULT_WGSL,createFullscreenPass,createBufferOwner});
})(typeof globalThis!=='undefined'?globalThis:this);
