(function(root){
'use strict';const O=root.OFU=root.OFU||{};const SEED='000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';
function jobs(){return Array.from({length:24},(_,i)=>({id:i,x:String(BigInt(i)-12n),y:String(BigInt(i*i)-50n),z:String(BigInt(i%5)-2n)}));}
function canonicalRows(seed,list){return list.map(j=>({id:j.id,fact:O.micro.sample(seed,BigInt(j.x),BigInt(j.y),BigInt(j.z))})).sort((a,b)=>a.id-b.id);}
function corpusDigest(rows){return O.canonical.digestObject(rows);}function hex(b){return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
async function run(kernelSources){const results=[];const add=(name,status,detail={})=>results.push({name,status,...detail});
try{const v=O.GOLDEN_VECTORS,a=v.address.map(s=>({kind:s.kind,value:s.kind==='text'?s.value:BigInt(s.value)})),ab=O.canonical.address(a),dh=O.sha256.hex(O.canonical.derive32({masterSeed256:v.seed,manifestHash:v.manifestHash,domainTag:v.domainTag,addressBytes:ab,propertyTag:v.propertyTag})),sd=O.canonical.digestObject(O.micro.sample(v.seed,...v.sampleAddress.map(BigInt)));add('golden-vectors',hex(ab)===v.addressHex&&dh===v.derive32Hex&&sd===v.sampleDigest?'PASS':'FAIL',{addressHex:hex(ab),derive32Hex:dh,sampleDigest:sd});}catch(e){add('golden-vectors','FAIL',{error:e.message});}
let rows,digest;try{rows=canonicalRows(SEED,jobs());digest=corpusDigest(rows);add('canonical-corpus',digest===O.GOLDEN_VECTORS.corpusDigest?'PASS':'FAIL',{digest,expectedDigest:O.GOLDEN_VECTORS.corpusDigest});}catch(e){add('canonical-corpus','FAIL',{error:e.message});return {results};}
const reversed=canonicalRows(SEED,[...jobs()].reverse());add('query-order',corpusDigest(reversed)===digest?'PASS':'FAIL');
try{const one=await O.workerHarness.run(SEED,jobs(),1,kernelSources,O.runtimeManifestHash),two=await O.workerHarness.run(SEED,jobs(),2,kernelSources,O.runtimeManifestHash),many=await O.workerHarness.run(SEED,jobs(),4,kernelSources,O.runtimeManifestHash),ok=[one,two,many].every(x=>corpusDigest(x.rows)===digest);add('workers-1-2-n',ok?'PASS':'FAIL',{workerCounts:[1,2,4],transferBytes:[one.transferBytes,two.transferBytes,many.transferBytes]});}catch(e){add('workers-1-2-n','ENVIRONMENT_LIMITED',{error:e.message});}
try{const w=await O.wasmExperiment.init(),bench=await O.wasmExperiment.benchmark(50000);add('embedded-wasm',w.add(20,22)===42&&w.deterministicProbe===2147483647&&bench.same?'PASS':'FAIL',{wasmBytes:w.bytes,wasmInitMs:w.initMs,jsAddMs:bench.jsMs,wasmAddMs:bench.wasmMs});}catch(e){add('embedded-wasm','FAIL',{error:e.message});}
const facts=O.micro.sample(SEED,1n,2n,3n),before=O.canonical.digestObject(facts);try{const r1=O.renderer.render(document.getElementById('scene'),facts,'baseline'),mid=O.canonical.digestObject(facts),r2=O.renderer.render(document.getElementById('scene'),facts,'low'),after=O.canonical.digestObject(facts);add('renderer-authority-boundary',before===mid&&mid===after?'PASS':'FAIL',{backends:[r1.backend,r2.backend]});}catch(e){add('renderer-authority-boundary','PARTIAL',{error:e.message});}
try{let p=O.save.payload({masterSeed256:SEED,manifestHash:O.runtimeManifestHash,events:[{type:'bookmark',data:{address:'demo'}}]}),d0=O.save.stateDigest(p),txt=O.save.exportPortable({masterSeed256:p.universeIdentity.masterSeed256,manifestHash:p.universeIdentity.generatorManifestHash,events:p.events});p=null;const p2=O.save.importPortable(txt,{manifestHash:O.runtimeManifestHash,masterSeed256:SEED}),d1=O.save.stateDigest(p2);add('save-roundtrip',d0===d1?'PASS':'FAIL',{saveBytes:new TextEncoder().encode(txt).length});let rejected=false;try{O.save.importPortable(txt.replace('bookmark','bookmarx'));}catch{rejected=true;}add('corrupted-save-fail-closed',rejected?'PASS':'FAIL');}catch(e){add('save-roundtrip','FAIL',{error:e.message});}
try{const base={masterSeed256:SEED,manifestHash:O.runtimeManifestHash,events:[{type:'é',data:{z:[1,true,null],a:'é'}}]},a=O.save.exportPortable(base),b=O.save.exportPortable({masterSeed256:SEED,manifestHash:O.runtimeManifestHash,events:[{type:'é',data:{a:'é',z:[1,true,null]}}]});let bigintRejected=false,cycleRejected=false,futureRejected=false;try{O.save.exportPortable({...base,events:[{type:'x',data:1n}]});}catch{bigintRejected=true;}const cyc={};cyc.self=cyc;try{O.save.exportPortable({...base,events:[{type:'x',data:cyc}]});}catch{cycleRejected=true;}const parsed=JSON.parse(a);parsed.payload.canonicalProtocolVersion='ofu-canonical-v2';try{O.save.importPortable(O.save.stableJson(parsed));}catch{futureRejected=true;}add('portable-save-contract',a===b&&bigintRejected&&cycleRejected&&futureRejected?'PASS':'FAIL',{deterministic:a===b,bigintRejected,cycleRejected,futureProtocolRejected:futureRejected});}catch(e){add('portable-save-contract','FAIL',{error:e.message});}
return {results,digest,capabilities:O.renderer.probe(),numeric:O.numericExperiment.run()};}
O.selftest={SEED,jobs,canonicalRows,corpusDigest,run};
})(typeof globalThis!=='undefined'?globalThis:this);
