(function(root){
'use strict';
const O=root.OFU=root.OFU||{},AUTHORITY='PRESENTATION_ONLY',VERSION='ofu-render-effects-1';
function fail(c,m){const e=new Error(m);e.code=c;throw e}function finite(v,l){v=Number(v);if(!Number.isFinite(v))fail('NUMBER','invalid '+l);return v}function clamp(v,a,b){return Math.max(a,Math.min(b,finite(v,'value')))}
const FXAA_VERTEX=`#version 300 es\nprecision highp float;layout(location=0) in vec2 aPosition;out vec2 vUv;void main(){vUv=aPosition*.5+.5;gl_Position=vec4(aPosition,0.,1.);}`;
const FXAA_FRAGMENT=`#version 300 es\nprecision highp float;uniform sampler2D uColor;uniform vec2 uInvResolution;in vec2 vUv;out vec4 outColor;float luma(vec3 c){return dot(c,vec3(.299,.587,.114));}void main(){vec3 c=texture(uColor,vUv).rgb;vec3 n=texture(uColor,vUv+vec2(0.,-uInvResolution.y)).rgb;vec3 s=texture(uColor,vUv+vec2(0.,uInvResolution.y)).rgb;vec3 e=texture(uColor,vUv+vec2(uInvResolution.x,0.)).rgb;vec3 w=texture(uColor,vUv+vec2(-uInvResolution.x,0.)).rgb;float lc=luma(c),lo=min(lc,min(min(luma(n),luma(s)),min(luma(e),luma(w)))),hi=max(lc,max(max(luma(n),luma(s)),max(luma(e),luma(w))));float edge=hi-lo;if(edge<max(.0312,hi*.125)){outColor=vec4(c,1.);return;}vec3 blend=(n+s+e+w+c*2.)/6.;outColor=vec4(mix(c,blend,.65),1.);}`;
function fxaa({width,height,enabled=true,quality='balanced'}={}){width=Math.max(1,Math.round(finite(width,'width')));height=Math.max(1,Math.round(finite(height,'height')));let active=enabled&&quality!=='low'&&width*height<=33554432;return Object.freeze({version:'ofu-fxaa-pass-1',authority:AUTHORITY,active,width,height,invResolution:Object.freeze([1/width,1/height]),vertexSource:FXAA_VERTEX,fragmentSource:FXAA_FRAGMENT,scientificTruthChanged:false,degradation:active?'NONE':quality==='low'?'QUALITY_TIER_DISABLED':'BOUNDED_DISABLED'})}
function shadow({mapSize=1024,cascades=1,maxDistance=10000,bias=.0015,normalBias=.02}={}){mapSize=Math.round(clamp(mapSize,128,4096));cascades=Math.round(clamp(cascades,1,4));return Object.freeze({version:'ofu-shadow-policy-1',authority:AUTHORITY,mapSize,cascades,maxDistance:clamp(maxDistance,1,1000000000),bias:clamp(bias,0,.05),normalBias:clamp(normalBias,0,.2),cameraAuthority:'EXTERNAL_READ_ONLY',scientificIlluminationClaim:false})}
function volumetric({steps=24,density=.02,phaseG=.2,heightScale=8000,jitter=true}={}){return Object.freeze({version:'ofu-volumetric-pass-1',authority:AUTHORITY,steps:Math.round(clamp(steps,4,64)),density:clamp(density,0,4),phaseG:clamp(phaseG,-.95,.95),heightScale:clamp(heightScale,1,2000000),jitter:!!jitter,scientificAtmosphereClaim:false,weatherClaim:false})}
function particleBatch(items,{maxParticles=65536,maxEmitters=1024}={}){if(!Array.isArray(items)||items.length>maxParticles)fail('BUDGET','particle count');const emitters=new Map();for(const p of items){const e=String(p.emitter||'default');if(!/^[A-Za-z0-9._:/@-]{1,128}$/.test(e))fail('ID','emitter');if(!emitters.has(e)){if(emitters.size>=maxEmitters)fail('BUDGET','emitter count');emitters.set(e,[])}const pos=p.position;if(!Array.isArray(pos)||pos.length!==3)fail('PARTICLE','position');emitters.get(e).push(Object.freeze({position:Object.freeze(pos.map(x=>finite(x,'position'))),size:clamp(p.size??1,.001,1000000),life:clamp(p.life??1,0,1),seed:String(p.seed??'0')}))}const batches=[...emitters].sort((a,b)=>a[0].localeCompare(b[0])).map(([emitter,particles])=>Object.freeze({emitter,particles:Object.freeze(particles)}));return Object.freeze({version:'ofu-particle-batch-1',authority:AUTHORITY,particles:items.length,batches:Object.freeze(batches),drawUpperBound:batches.length,simulationAuthority:'EXTERNAL_READ_ONLY'})}
O.renderEffects=Object.freeze({VERSION,AUTHORITY,fxaa,shadow,volumetric,particleBatch,FXAA_VERTEX,FXAA_FRAGMENT});
})(typeof globalThis!=='undefined'?globalThis:this);
