(function(root){
'use strict';
const O=root.OFU=root.OFU||{},VERSION='ofu-render-volumetrics-4',AUTHORITY='PRESENTATION_ONLY';
function fail(c,m){const e=new Error(m);e.code=c;throw e}function c(x,a,b){x=Number(x);if(!Number.isFinite(x))fail('NUMBER','non-finite');return Math.max(a,Math.min(b,x))}function bound(v,name,min,max){v=Number(v);if(!Number.isSafeInteger(v)||v<min||v>max)fail('BUDGET','invalid '+name);return v}function norm(v){if(!Array.isArray(v)||v.length!==3)fail('VECTOR','vec3');const n=v.map(Number);if(n.some(x=>!Number.isFinite(x)))fail('VECTOR','non-finite vec3');const m=Math.hypot(...n);if(!(m>1e-12))fail('VECTOR','zero');return n.map(x=>x/m)}function vec3(v,label='vec3'){if(!Array.isArray(v)||v.length!==3)fail('VECTOR',label);const n=v.map(Number);if(n.some(x=>!Number.isFinite(x)))fail('VECTOR',label);return Object.freeze(n)}function token(v,fallback,label){if(v==null&&fallback==null)fail('ID',label);const s=String(v==null?fallback:v);if(!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,159}$/.test(s))fail('ID',label);return s}
function profile(r={}){return Object.freeze({version:VERSION,authority:AUTHORITY,density:c(r.density==null?0.025:r.density,0,4),extinction:c(r.extinction==null?1:r.extinction,.01,8),anisotropy:c(r.anisotropy==null?.2:r.anisotropy,-.95,.95),steps:Math.round(c(r.steps==null?24:r.steps,4,64)),maxDistance:c(r.maxDistance==null?10000:r.maxDistance,.01,2e6),scientificAtmosphereClaim:false,weatherClaim:false})}
function integrateRay({origin=[0,0,0],direction=[0,0,1],lightDirection=[0,0,1],profile:raw={},sampleDensity=()=>1}={}){const p=profile(raw),d=norm(direction),l=norm(lightDirection);origin=vec3(origin,'origin');if(typeof sampleDensity!=='function')fail('INPUT','density sampler');const step=p.maxDistance/p.steps,g=p.anisotropy,cos=Math.max(-1,Math.min(1,d[0]*l[0]+d[1]*l[1]+d[2]*l[2])),phase=(1-g*g)/(4*Math.PI*Math.pow(Math.max(1e-5,1+g*g-2*g*cos),1.5));let trans=1,scatter=0;for(let i=0;i<p.steps;i++){const t=(i+.5)*step,pos=[origin[0]+d[0]*t,origin[1]+d[1]*t,origin[2]+d[2]*t],local=c(sampleDensity(pos,i),0,4)*p.density,atten=Math.exp(-local*p.extinction*step/Math.max(1,p.maxDistance));scatter+=trans*(1-atten)*phase;trans*=atten;if(trans<1e-4)break}return Object.freeze({version:VERSION,authority:AUTHORITY,transmittance:c(trans,0,1),inscatter:Math.max(0,scatter),steps:p.steps,scientificAtmosphereClaim:false})}
function planParticles(particles,{maxParticles=65536,maxBatches=1024}={}){maxParticles=bound(maxParticles,'maxParticles',0,1048576);maxBatches=bound(maxBatches,'maxBatches',1,16384);if(!Array.isArray(particles)||particles.length>maxParticles)fail('BUDGET','particles');const map=new Map,seen=new Set;for(const raw of particles){if(!raw||typeof raw!=='object')fail('INPUT','particle');const id=token(raw.id,null,'particle id');if(seen.has(id))fail('COLLISION','particle id');seen.add(id);const materialRef=token(raw.materialRef,'default','material ref'),blend=token(raw.blend,'alpha','blend'),key=materialRef+'|'+blend;if(!map.has(key)){if(map.size>=maxBatches)fail('BUDGET','particle batches');map.set(key,[])}map.get(key).push(Object.freeze({id,position:vec3(raw.position==null?[0,0,0]:raw.position,'particle position'),size:c(raw.size==null?1:raw.size,.001,1e5),opacity:c(raw.opacity==null?1:raw.opacity,0,1)}))}const batches=[...map].sort((a,b)=>a[0].localeCompare(b[0])).map(([key,items])=>Object.freeze({key,items:Object.freeze(items.sort((a,b)=>a.id.localeCompare(b.id))),instances:items.length}));return Object.freeze({version:'ofu-render-particle-plan-4',authority:AUTHORITY,particleCount:particles.length,batches:Object.freeze(batches),drawUpperBound:batches.length,simulationAuthority:'EXTERNAL_READ_ONLY'})}
O.renderVolumetrics=Object.freeze({VERSION,AUTHORITY,profile,integrateRay,planParticles});
})(typeof globalThis!=='undefined'?globalThis:this);
