(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.pxContracts,L=O.v1x11Lifecycle,S=O.v1x11Scheduler;
if(!C||!L||!S)throw new Error('V1X-11 resource manager requires PX contracts, lifecycle and scheduler');
const VERSION='ofu-v1x11-resource-manager-1';
const HARD=Object.freeze({cpuBytes:268435456,gpuBytes:536870912,entities:C.LIMITS.entities,draws:65536,entries:4096,workers:16,queue:C.LIMITS.queue,jobs:C.LIMITS.queue});
const DEFAULTS=Object.freeze({cpuBytes:33554432,gpuBytes:67108864,entities:16384,draws:8192,entries:512,workers:4,queue:128,jobs:132});
function error(code,detail){const e=new Error('OFU V1X-11 '+code+': '+detail);e.code=code;return e;}
function int(v,label,max,allowZero=false){C.assert(Number.isSafeInteger(v)&&(allowZero?v>=0:v>0)&&v<=max,'BUDGET',label);return v;}
function budgets(input={}){C.assert(input&&typeof input==='object'&&!Array.isArray(input),'SCHEMA','resource budgets');const out={};for(const k of Object.keys(DEFAULTS)){const v=input[k]??DEFAULTS[k];out[k]=int(v,k,HARD[k]);}C.assert(out.jobs>=out.workers&&out.jobs<=out.queue+out.workers,'BUDGET','jobs fit workers plus queue');return Object.freeze(out);}
function estimate(input,state){C.assert(input&&typeof input==='object'&&!Array.isArray(input),'SCHEMA','resource estimate');C.keys(input,['cpuBytes','gpuBytes','entities','draws']);const e={cpuBytes:int(input.cpuBytes,'estimated cpu bytes',HARD.cpuBytes,true),gpuBytes:int(input.gpuBytes,'estimated gpu bytes',HARD.gpuBytes,true),entities:int(input.entities,'estimated entities',HARD.entities,true),draws:int(input.draws,'estimated draws',HARD.draws,true)};if(state==='COLD')C.assert(Object.values(e).every(v=>v===0),'BUDGET','cold estimate must be zero');if(state==='WARM')C.assert(e.gpuBytes===0&&e.draws===0,'BUDGET','warm estimate cannot reserve GPU/draws');return Object.freeze(e);}
function create(options={}){
 const limit=budgets(options.budgets||{}),providerRegistry=options.providerRegistry||O.pxProduct?.registry;
 C.assert(providerRegistry&&typeof providerRegistry.descriptor==='function','DEPENDENCY','admitted provider registry required');
 const scheduler=S.create({maxWorkers:limit.workers,maxQueue:limit.queue,maxJobs:limit.jobs});
 const materializers=new Map(),entries=new Map();let clock=0,jobSequence=0,quality='FULL',contextLost=false;
 const usage={cpuBytes:0,gpuBytes:0,entities:0,draws:0},reserved={cpuBytes:0,gpuBytes:0,entities:0,draws:0};
 const peak={cpuBytes:0,gpuBytes:0,entities:0,draws:0,reservedCpuBytes:0,reservedGpuBytes:0,entries:0};
 const metrics={requests:0,hits:0,materializations:0,evictions:0,demotions:0,cancellations:0,backpressure:0,qualityChanges:0,contextLosses:0,contextRecoveries:0,contextRecoveryFailures:0,releaseFailures:0,semanticRejections:0};
 function touchPeak(){for(const k of ['cpuBytes','gpuBytes','entities','draws'])peak[k]=Math.max(peak[k],usage[k]+reserved[k]);peak.reservedCpuBytes=Math.max(peak.reservedCpuBytes,reserved.cpuBytes);peak.reservedGpuBytes=Math.max(peak.reservedGpuBytes,reserved.gpuBytes);peak.entries=Math.max(peak.entries,entries.size);}
 function add(target,value,sign){for(const k of ['cpuBytes','gpuBytes','entities','draws'])target[k]+=sign*value[k];touchPeak();}
 function fits(extra){return usage.cpuBytes+reserved.cpuBytes+extra.cpuBytes<=limit.cpuBytes&&usage.gpuBytes+reserved.gpuBytes+extra.gpuBytes<=limit.gpuBytes&&usage.entities+reserved.entities+extra.entities<=limit.entities&&usage.draws+reserved.draws+extra.draws<=limit.draws;}
 function adapterFor(providerId){const a=materializers.get(providerId);C.assert(a,'IMPLEMENTATION','materializer '+providerId);return a;}
 function releaseGpu(entry,reason){if(!entry.gpuBytes&&!entry.draws&&!entry.gpuHandle)return;const a=adapterFor(entry.identity.providerId);try{a.releaseGpu?.(entry.gpuHandle,entry.identity,reason);}catch(e){metrics.releaseFailures++;throw error('RELEASE_FAILURE',e.message||reason);}usage.gpuBytes-=entry.gpuBytes;usage.draws-=entry.draws;entry.gpuBytes=0;entry.draws=0;entry.gpuHandle=null;}
 function releaseCpu(entry,reason){if(!entry.cpuBytes&&!entry.entities&&!entry.cpuHandle)return;const a=adapterFor(entry.identity.providerId);try{a.releaseCpu?.(entry.cpuHandle,entry.identity,reason);}catch(e){metrics.releaseFailures++;throw error('RELEASE_FAILURE',e.message||reason);}usage.cpuBytes-=entry.cpuBytes;usage.entities-=entry.entities;entry.cpuBytes=0;entry.entities=0;entry.cpuHandle=null;}
 function demote(entry,target,reason){L.state(target);C.assert(L.compare(target,entry.state)<=0,'LIFECYCLE','demotion direction');if(L.compare(entry.state,'HOT')>=0&&L.compare(target,'HOT')<0)releaseGpu(entry,reason);if(L.compare(entry.state,'WARM')>=0&&L.compare(target,'WARM')<0)releaseCpu(entry,reason);entry.state=target;entry.pinned=target==='IMMEDIATE';entry.lastUse=++clock;metrics.demotions++;}
 function evictEntry(entry,reason){if(entry.pinned||entry.jobId)return false;releaseGpu(entry,reason);releaseCpu(entry,reason);entries.delete(entry.key);metrics.evictions++;touchPeak();return true;}
 function candidates(resourcePressure){return [...entries.values()].filter(e=>!e.pinned&&!e.jobId&&(resourcePressure?e.cpuBytes||e.gpuBytes||e.entities||e.draws:true)).sort((a,b)=>L.compare(a.state,b.state)||a.lastUse-b.lastUse||a.key.localeCompare(b.key));}
 function makeRoom(extra,needsEntry,protectedKey){
   let guard=0;
   while((!fits(extra)||(needsEntry&&entries.size>=limit.entries))&&guard++<=limit.entries+1){const pressure=!fits(extra);const c=candidates(pressure).find(e=>e.key!==protectedKey);if(!c||!evictEntry(c,'budget-pressure'))break;}
   if(!fits(extra)||(needsEntry&&entries.size>=limit.entries)){metrics.backpressure++;throw error('RESOURCE_BUDGET','bounded working set has no evictable capacity');}
 }
 function registerMaterializer(input){
   C.assert(input&&typeof input==='object'&&!Array.isArray(input),'SCHEMA','materializer');const providerId=C.token(input.providerId,'provider id'),domain=L.domain(input.domain);providerRegistry.descriptor(providerId);C.assert(!materializers.has(providerId),'DUPLICATE','materializer '+providerId);C.assert(typeof input.load==='function','SCHEMA','materializer load');for(const k of ['releaseCpu','releaseGpu','contextLost','contextRestored'])if(input[k]!==undefined)C.assert(typeof input[k]==='function','SCHEMA',k);
   const value=Object.freeze({providerId,domain,load:input.load,releaseCpu:input.releaseCpu||null,releaseGpu:input.releaseGpu||null,contextLost:input.contextLost||null,contextRestored:input.contextRestored||null});materializers.set(providerId,value);return value;
 }
 function normalize(input,overrideState){
   C.assert(input&&typeof input==='object'&&!Array.isArray(input),'SCHEMA','materialization request');C.keys(input,['identity','domain','state','semantic','presentation','estimate']);const identity=L.identity(input.identity),domain=L.domain(input.domain),state=L.state(overrideState||input.state),a=adapterFor(identity.providerId);C.assert(a.domain===domain,'OWNER','provider/domain mismatch');const semantic=C.data(input.semantic,{bytes:65536,nodes:4096}),presentation=C.data(input.presentation,{bytes:32768,nodes:2048}),semanticDigest=C.digest(semantic),est=estimate(input.estimate,state);return Object.freeze({identity,domain,state,semantic,presentation,semanticDigest,estimate:est});
 }
 function validateResult(result,req){
   C.assert(result&&typeof result==='object'&&!Array.isArray(result),'SCHEMA','materialization result');for(const k of ['identity','semanticDigest','state','cpuBytes','gpuBytes','entities','draws','cpuHandle','gpuHandle'])C.assert(Object.hasOwn(result,k),'SCHEMA','materialization result '+k);const identity=L.identity(result.identity);if(C.stable(identity)!==C.stable(req.identity)||result.semanticDigest!==req.semanticDigest){metrics.semanticRejections++;throw error('SEMANTIC_INVARIANCE','materializer changed identity or semantic digest');}C.assert(result.state===req.state,'LIFECYCLE','materializer state mismatch');const actual={cpuBytes:int(result.cpuBytes,'actual cpu bytes',HARD.cpuBytes,true),gpuBytes:int(result.gpuBytes,'actual gpu bytes',HARD.gpuBytes,true),entities:int(result.entities,'actual entities',HARD.entities,true),draws:int(result.draws,'actual draws',HARD.draws,true)};for(const k of Object.keys(actual))C.assert(actual[k]<=req.estimate[k],'BUDGET','materializer exceeded reservation '+k);if(req.state==='COLD')C.assert(Object.values(actual).every(v=>v===0),'BUDGET','cold materialization');if(req.state==='WARM')C.assert(actual.gpuBytes===0&&actual.draws===0,'BUDGET','warm materialization');return {identity,actual};
 }
 function releaseLoose(a,result,reason){try{if(result?.gpuHandle||result?.gpuBytes||result?.draws)a.releaseGpu?.(result.gpuHandle,result.identity,reason);if(result?.cpuHandle||result?.cpuBytes||result?.entities)a.releaseCpu?.(result.cpuHandle,result.identity,reason);}catch(e){metrics.releaseFailures++;throw error('RELEASE_FAILURE',e.message||reason);}}
 function cold(req){const key=L.key(req.identity),existing=entries.get(key);if(existing){if(existing.jobId){scheduler.cancel(existing.jobId,'cold-demotion');metrics.cancellations++;}if(existing.state!=='COLD')demote(existing,'COLD','explicit-cold');existing.semanticDigest=req.semanticDigest;existing.lastRequest=req;return witness(existing);}makeRoom(req.estimate,true,key);const entry={key,identity:req.identity,domain:req.domain,semanticDigest:req.semanticDigest,state:'COLD',desiredState:'COLD',cpuBytes:0,gpuBytes:0,entities:0,draws:0,cpuHandle:null,gpuHandle:null,pinned:false,lastUse:++clock,generation:0,jobId:null,lastRequest:req,restoreState:null};entries.set(key,entry);touchPeak();return witness(entry);}
 function request(input){
   metrics.requests++;const req=normalize(input),key=L.key(req.identity);if(req.state==='COLD')return Promise.resolve(cold(req));let entry=entries.get(key);
   if(entry&&entry.semanticDigest===req.semanticDigest&&entry.state===req.state&&!entry.jobId){entry.lastUse=++clock;entry.lastRequest=req;metrics.hits++;return Promise.resolve(witness(entry));}
   if(entry?.jobId){scheduler.cancel(entry.jobId,'superseded');metrics.cancellations++;entry.jobId=null;}
   if(entry){if(entry.state!=='COLD')demote(entry,'COLD','rematerialize');if(entry.semanticDigest!==req.semanticDigest)entry.semanticDigest=req.semanticDigest;}else{makeRoom(req.estimate,true,key);entry={key,identity:req.identity,domain:req.domain,semanticDigest:req.semanticDigest,state:'COLD',desiredState:req.state,cpuBytes:0,gpuBytes:0,entities:0,draws:0,cpuHandle:null,gpuHandle:null,pinned:false,lastUse:++clock,generation:0,jobId:null,lastRequest:req,restoreState:null};entries.set(key,entry);}
   makeRoom(req.estimate,false,key);add(reserved,req.estimate,1);let reservationHeld=true;const releaseReservation=()=>{if(reservationHeld){reservationHeld=false;add(reserved,req.estimate,-1);}};const generation=++entry.generation,jobId='v1x11.job.'+(++jobSequence);entry.jobId=jobId;entry.desiredState=req.state;entry.lastRequest=req;const a=adapterFor(req.identity.providerId);
   let handle;try{handle=scheduler.schedule({id:jobId,state:req.state,run:async signal=>{const result=await a.load(Object.freeze({identity:req.identity,domain:req.domain,targetState:req.state,semantic:req.semantic,semanticDigest:req.semanticDigest,presentation:req.presentation,signal,contextLost}));if(signal.aborted||entry.generation!==generation){releaseLoose(a,result,'stale-materialization');throw error('CANCELLED','stale materialization');}let checked;try{checked=validateResult(result,req);}catch(e){releaseLoose(a,result,'invalid-materialization');throw e;}entry.state=req.state;entry.desiredState=req.state;entry.semanticDigest=req.semanticDigest;entry.cpuBytes=checked.actual.cpuBytes;entry.gpuBytes=checked.actual.gpuBytes;entry.entities=checked.actual.entities;entry.draws=checked.actual.draws;entry.cpuHandle=result.cpuHandle;entry.gpuHandle=result.gpuHandle;entry.pinned=req.state==='IMMEDIATE';entry.lastUse=++clock;releaseReservation();add(usage,checked.actual,1);metrics.materializations++;return witness(entry);}});}catch(e){releaseReservation();entries.delete(key);throw e;}
   const promise=handle.promise.finally(()=>{releaseReservation();if(entries.get(key)===entry&&entry.jobId===jobId)entry.jobId=null;});return promise;
 }
 function witness(entry){return C.data({identity:entry.identity,domain:entry.domain,semanticDigest:entry.semanticDigest,state:entry.state,usage:{cpuBytes:entry.cpuBytes,gpuBytes:entry.gpuBytes,entities:entry.entities,draws:entry.draws},pinned:entry.pinned});}
 function evict(identity,reason='explicit-eviction'){const key=typeof identity==='string'?identity:L.key(identity),entry=entries.get(key);if(!entry)return false;if(entry.jobId){scheduler.cancel(entry.jobId,reason);metrics.cancellations++;return false;}return evictEntry(entry,reason);}
 function pressure(){return Math.max(usage.cpuBytes/limit.cpuBytes,usage.gpuBytes/limit.gpuBytes,usage.entities/limit.entities,usage.draws/limit.draws,entries.size/limit.entries);}
 function adaptiveQuality(){const p=pressure(),next=p>=0.85?'CONSERVATIVE':p>=0.65?'BALANCED':'FULL';if(next!==quality){quality=next;metrics.qualityChanges++;}return quality;}
 async function reconcileWorkingSet(intents){
   C.assert(Array.isArray(intents)&&intents.length<=limit.entries,'BUDGET','working-set intents');const desired=new Map();for(const raw of intents){const id=L.identity(raw.identity),key=L.key(id);C.assert(!desired.has(key),'DUPLICATE','working-set identity');desired.set(key,raw);}
   for(const entry of [...entries.values()])if(!desired.has(entry.key)&&!entry.jobId){if(entry.state==='IMMEDIATE'||entry.state==='HOT')demote(entry,'WARM','working-set-cooling');else if(entry.state==='WARM')demote(entry,'COLD','working-set-cooling');else evictEntry(entry,'working-set-expired');}
   const q=adaptiveQuality(),ordered=[...desired.values()].sort((a,b)=>L.compare(b.state,a.state));const promises=[];for(const raw of ordered){const presentation={...raw.presentation,adaptiveQuality:q};promises.push(request({...raw,presentation}));}return Promise.allSettled(promises);
 }
 function contextLoss(backendId='webgl2'){
   C.token(backendId,'backend id');contextLost=true;metrics.contextLosses++;for(const a of materializers.values())a.contextLost?.(backendId);for(const entry of entries.values()){if(entry.jobId){scheduler.cancel(entry.jobId,'context-lost');metrics.cancellations++;}if(entry.state==='HOT'||entry.state==='IMMEDIATE'){entry.restoreState=entry.state;demote(entry,'WARM','context-lost');}}return snapshot();
 }
 async function contextRestore(backendId='webgl2'){
   C.token(backendId,'backend id');for(const a of materializers.values())a.contextRestored?.(backendId);contextLost=false;const work=[];for(const entry of entries.values())if(entry.restoreState&&entry.lastRequest){const state=entry.restoreState;entry.restoreState=null;const {identity,domain,semantic,presentation,estimate}=entry.lastRequest;work.push(request({identity,domain,semantic,presentation,estimate,state}));}const results=await Promise.allSettled(work);if(results.some(r=>r.status==='rejected'))metrics.contextRecoveryFailures++;else metrics.contextRecoveries++;return results;
 }
 function bindContextTarget(target,backendId='webgl2'){C.assert(target&&typeof target.addEventListener==='function'&&typeof target.removeEventListener==='function','SCHEMA','context event target');const lost=e=>{e?.preventDefault?.();contextLoss(backendId);},restored=()=>{void contextRestore(backendId);};target.addEventListener('webglcontextlost',lost,false);target.addEventListener('webglcontextrestored',restored,false);return()=>{target.removeEventListener('webglcontextlost',lost,false);target.removeEventListener('webglcontextrestored',restored,false);};}
 function snapshot(){const states={COLD:0,WARM:0,HOT:0,IMMEDIATE:0};for(const e of entries.values())states[e.state]++;return C.data({version:VERSION,authority:'MEASURED_RUNTIME_EVIDENCE',budgets:limit,usage,reserved,peak,workingSet:{entries:entries.size,states,materializers:materializers.size,contextLost,adaptiveQuality:quality},scheduler:scheduler.snapshot(),metrics});}
 function trace(){return C.data([...entries.values()].sort((a,b)=>a.key.localeCompare(b.key)).map(witness),{bytes:262144,nodes:16384});}
 return Object.freeze({VERSION,registerMaterializer,request,reconcileWorkingSet,evict,contextLoss,contextRestore,bindContextTarget,adaptiveQuality,snapshot,trace,drain:scheduler.drain});
}
O.v1x11Resources=Object.freeze({VERSION,HARD,DEFAULTS,create});
})(globalThis);
