(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-civilization-economy-culture-1';
const AUTH=V.authority('v1.civilization.economy-culture','1.0.0',[],'Bounded production, storage, exchange, technology and cultural-transmission scenario model.',[
 'No universal monetary system is assumed; exchange operates on goods and transport costs.',
 'Culture state is synthetic convention transmission, not predicted Earth culture, grammar or belief.'
]);
const CAPABILITIES=Object.freeze(['production','transport','materials','energy','communication','medicine','construction','conflict']);
function economy(state,settlements,epochStep){const resources=state.resources.map(r=>({...r})),byRegion=new Map();for(const r of resources){if(!byRegion.has(r.regionId))byRegion.set(r.regionId,[]);byRegion.get(r.regionId).push(r);}const next=[];for(const s of settlements){if(s.status!=='ACTIVE'){next.push(s);continue;}const stocks={...s.stocks};for(const r of byRegion.get(s.regionId)||[]){const extractionCap=Math.max(0,Math.floor(s.population*(40000+r.availabilityPpm+state.technology.production*45000+state.technology.energy*22000)/1000000)),extracted=Math.min(r.amountUnits,Math.floor(extractionCap*epochStep/4)),efficiencyPpm=Math.min(950000,500000+state.technology.materials*45000+state.technology.production*35000),goods=Math.floor(extracted*efficiencyPpm/1000000);stocks[r.transformsTo]=(stocks[r.transformsTo]||0)+goods;if(r.depletable)r.amountUnits=Math.max(0,r.amountUnits-extracted);}stocks.SUBSISTENCE_GOODS=Math.max(0,(stocks.SUBSISTENCE_GOODS||0)-Math.floor(s.population*epochStep*.75));stocks.ENERGY_SERVICE=Math.max(0,(stocks.ENERGY_SERVICE||0)-Math.floor(s.population*epochStep*.14));stocks.MATERIAL_GOODS=Math.max(0,(stocks.MATERIAL_GOODS||0)-Math.floor(s.population*epochStep*.06));const total=Object.values(stocks).reduce((n,x)=>n+x,0),capacity=Math.max(s.storageCapacityUnits,s.population*(6+state.technology.construction));if(total>capacity)for(const k of Object.keys(stocks))stocks[k]=Math.floor(stocks[k]*capacity/total);const scarcityPpm=V.clamp(1000000-Math.floor((stocks.SUBSISTENCE_GOODS||0)*1000000/Math.max(1,s.population*2)),0,1000000),infrastructurePpm=V.clamp(s.infrastructurePpm+(stocks.MATERIAL_GOODS>s.population*.4?state.technology.construction*1200:0)-Math.floor(scarcityPpm/140),0,1000000);next.push(Object.freeze({...s,stocks:Object.freeze(stocks),scarcityPpm,infrastructurePpm}));}for(const r of resources){const regen=Math.floor(r.initialAmountUnits*r.regenerationPpm*epochStep/1000000);r.amountUnits=Math.min(r.initialAmountUnits,r.amountUnits+regen);}return {settlements:Object.freeze(next),resources:Object.freeze(resources.map(Object.freeze))};}
function exchange(settlements,edges){const byId=new Map(settlements.map(s=>[s.settlementId,{...s,stocks:{...s.stocks}}]));for(const e of edges){const a=byId.get(e.from),b=byId.get(e.to);for(const good of ['SUBSISTENCE_GOODS','MATERIAL_GOODS','ENERGY_SERVICE']){const needA=Math.max(1,a.population*(good==='SUBSISTENCE_GOODS'?1:.15)),needB=Math.max(1,b.population*(good==='SUBSISTENCE_GOODS'?1:.15)),ratioA=(a.stocks[good]||0)/needA,ratioB=(b.stocks[good]||0)/needB;if(Math.abs(ratioA-ratioB)<.15)continue;const from=ratioA>ratioB?a:b,to=ratioA>ratioB?b:a,amount=Math.min(Math.floor(e.flowUnits/3),Math.floor((from.stocks[good]||0)*.18));if(amount>0){from.stocks[good]-=amount;to.stocks[good]=(to.stocks[good]||0)+amount;}}}return Object.freeze(settlements.map(s=>Object.freeze({...byId.get(s.settlementId),stocks:Object.freeze(byId.get(s.settlementId).stocks)})));}
function initialCulture(population){return Object.freeze(population.groups.filter(g=>g.status==='ACTIVE').map((g,i)=>Object.freeze({cultureId:V.deriveId('culture',g.lineageId,g.groupId),groupId:g.groupId,languageFamilyId:V.deriveId('language-family',g.lineageId,i%Math.max(1,Math.ceil(population.groups.length/3))),dialectDivergencePpm:V.unitPpm(VERSION,g.groupId,'dialect'),materialTraditionPpm:V.unitPpm(VERSION,g.groupId,'material'),symbolicComplexityPpm:150000+(V.unitPpm(VERSION,g.groupId,'symbolic')%700001),worldviewVector:Object.freeze([0,1,2].map(x=>V.unitPpm(VERSION,g.groupId,'worldview',x))),knowledgePpm:220000+(V.unitPpm(VERSION,g.groupId,'knowledge')%600001),syncretismPpm:0,preservationPpm:500000,lossRiskPpm:0,status:'ACTIVE',claim:'synthetic evolving cultural state; not Earth-culture mapping'})));}
function technologyStep(state,settlements,edges,epoch){const t={...state.technology},population=settlements.reduce((n,s)=>n+s.population,0),avg=k=>state.regions.reduce((n,r)=>n+r[k],0)/state.regions.length,exchangePpm=V.clamp(Math.floor(edges.reduce((n,e)=>n+(1000000-e.costPpm),0)/Math.max(1,edges.length)),0,1000000),continuity=V.clamp(t.knowledgeContinuityPpm+Math.floor(exchangePpm/180)-Math.floor(settlements.reduce((n,s)=>n+(s.scarcityPpm||0),0)/Math.max(1,settlements.length)/120),0,1000000),conditions={production:population>1200,transport:exchangePpm>180000,materials:avg('materialResourcePpm')>180000,energy:avg('energyAccessPpm')>160000,communication:population>2500&&exchangePpm>220000,medicine:population>3000&&continuity>350000,construction:avg('materialResourcePpm')>220000,conflict:population>1800},changed=[];for(const cap of CAPABILITIES)if(t[cap]<8&&conditions[cap]){const threshold=820000-Math.min(280000,continuity/3)-Math.min(160000,exchangePpm/5),selector=V.unitPpm(VERSION,state.lineageId,epoch,cap,'innovation');if(selector>threshold){t[cap]++;changed.push(cap);}}t.knowledgeContinuityPpm=continuity;t.exchangePpm=exchangePpm;t.environmentImpactPpm=V.clamp(Math.floor((t.production+t.materials+t.energy)*42000+population/12),0,1000000);return {technology:Object.freeze(t),changed:Object.freeze(changed)};}
function cultureStep(state,settlements,edges,technology,epoch){const degree=new Map(),byGroup=new Map(settlements.map(s=>[s.foundingGroupId,s]));for(const e of edges){degree.set(e.from,(degree.get(e.from)||0)+1);degree.set(e.to,(degree.get(e.to)||0)+1);}return Object.freeze(state.cultures.map(c=>{const s=byGroup.get(c.groupId),connections=s?(degree.get(s.settlementId)||0):0,isolationPpm=V.clamp(700000-connections*90000,0,900000),knowledgePpm=V.clamp(c.knowledgePpm+connections*800+technology.communication*550-Math.floor((s?.scarcityPpm||0)/170),0,1000000),dialectDivergencePpm=V.clamp(c.dialectDivergencePpm+Math.floor(isolationPpm/100)-connections*450,0,1000000),materialTraditionPpm=V.clamp(c.materialTraditionPpm+Math.floor(V.signedPpm(VERSION,c.cultureId,epoch,'material')/800),0,1000000),syncretismPpm=V.clamp(c.syncretismPpm+connections*1800,0,1000000),preservationPpm=V.clamp(c.preservationPpm+Math.floor(isolationPpm/550)-connections*500+Math.floor(knowledgePpm/900),0,1000000),lossRiskPpm=V.clamp(Math.floor((s?.scarcityPpm||0)*.55)+(1000000-knowledgePpm)/4-preservationPpm/6,0,1000000);return Object.freeze({...c,dialectDivergencePpm,knowledgePpm,materialTraditionPpm,syncretismPpm,preservationPpm,lossRiskPpm});}));}
O.v1CivilizationEconomyCulture=Object.freeze({VERSION,AUTHORITY:AUTH,CAPABILITIES,economy,exchange,initialCulture,technologyStep,cultureStep});
})(globalThis);
