(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-civilization-foundation-1';
const AUTH=V.authority('v1.civilization.foundation','1.0.0',[],'Deterministic settlement/resource/network foundation for modeled intelligent populations.',[
 'Fallback resources are generic model-derived potentials, not source-backed chemistry.'
]);
const TYPES=Object.freeze(['CAMP','SMALL_SETTLEMENT','VILLAGE','TOWN','CITY','REGIONAL_CENTER']);
const typeFor=n=>n<80?'CAMP':n<250?'SMALL_SETTLEMENT':n<1000?'VILLAGE':n<5000?'TOWN':n<20000?'CITY':'REGIONAL_CENTER';
function resource(x,regionId,i){const resourceClass=x.resourceClass||'GENERIC_MATERIAL',amountUnits=x.amountUnits??100000,availabilityPpm=x.availabilityPpm??500000,regenerationPpm=x.regenerationPpm??0;V.int(amountUnits,'amountUnits',0,1000000000);V.ppm(availabilityPpm);V.ppm(regenerationPpm);return Object.freeze({resourceId:x.resourceId||V.deriveId('resource',regionId,i),regionId,resourceClass,amountUnits,initialAmountUnits:amountUnits,availabilityPpm,regenerationPpm,depletable:x.depletable!==false,transformsTo:x.transformsTo||(resourceClass.includes('BIOMASS')?'SUBSISTENCE_GOODS':resourceClass.includes('ENERGY')?'ENERGY_SERVICE':'MATERIAL_GOODS'),authority:x.authority||'MODEL_DERIVED_SIMULATION'});}
function region(r,i){const regionId=r.regionId||('region-'+i),o={regionId,waterPpm:r.waterPpm??500000,terrainPpm:r.terrainPpm??500000,climatePpm:r.climatePpm??500000,biologicalResourcePpm:r.biologicalResourcePpm??350000,materialResourcePpm:r.materialResourcePpm??350000,energyAccessPpm:r.energyAccessPpm??250000,transportPpm:r.transportPpm??400000,defensePpm:r.defensePpm??400000,historicalInheritancePpm:r.historicalInheritancePpm??0,barrierPpm:r.barrierPpm??300000,carryingCapacity:r.carryingCapacity??5000};V.text(regionId,'regionId',128);for(const k in o)if(k.endsWith('Ppm'))V.ppm(o[k],k);V.int(o.carryingCapacity,'carryingCapacity',1,1000000000);let rr=Array.isArray(r.resources)?r.resources.slice(0,24):[];if(!rr.length){if(o.biologicalResourcePpm>50000)rr.push({resourceClass:'BIOMASS_OR_ANALOGUE',amountUnits:50000+Math.floor(o.biologicalResourcePpm*.8),availabilityPpm:o.biologicalResourcePpm,regenerationPpm:12000,transformsTo:'SUBSISTENCE_GOODS'});if(o.materialResourcePpm>50000)rr.push({resourceClass:'MINERAL_OR_CONSTRUCTION_MATERIAL',amountUnits:50000+Math.floor(o.materialResourcePpm*1.2),availabilityPpm:o.materialResourcePpm,transformsTo:'MATERIAL_GOODS'});if(o.energyAccessPpm>50000)rr.push({resourceClass:'ACCESSIBLE_ENERGY_GRADIENT',amountUnits:100000+o.energyAccessPpm,availabilityPpm:o.energyAccessPpm,regenerationPpm:Math.floor(o.energyAccessPpm/30),depletable:false,transformsTo:'ENERGY_SERVICE'});}return Object.freeze({...o,resources:Object.freeze(rr.map((x,j)=>resource(x,regionId,j)))});}
function suitability(r){return V.clamp(Math.floor(r.waterPpm*.20+r.terrainPpm*.12+r.climatePpm*.18+r.biologicalResourcePpm*.16+r.materialResourcePpm*.10+r.transportPpm*.12+r.defensePpm*.07+r.historicalInheritancePpm*.05),0,1000000);}
function settlements(population,regions,worldIdentity,lineageId){const by=new Map(regions.map(r=>[r.regionId,r])),out=[];for(const g of population.groups){if(g.status!=='ACTIVE')continue;const parts=g.population>=30000?3:g.population>=7000?2:1,alloc=V.partition(g.population,Array.from({length:parts},(_,i)=>1000-i*170));for(let i=0;i<alloc.length&&out.length<V.MAX.settlements;i++){const n=alloc[i],id=V.deriveId('settlement',worldIdentity,lineageId,g.regionId,i),su=suitability(by.get(g.regionId));out.push(Object.freeze({settlementId:id,foundingGroupId:g.groupId,regionId:g.regionId,population:n,type:typeFor(n),status:'ACTIVE',suitabilityPpm:su,infrastructurePpm:60000+Math.floor(su*.28),storageCapacityUnits:Math.max(1000,n*6),stocks:Object.freeze({SUBSISTENCE_GOODS:n*2,MATERIAL_GOODS:Math.floor(n*.6),ENERGY_SERVICE:Math.floor(n*.4)}),polityId:null,lastActiveEpoch:0}));}}return Object.freeze(out);}
function technology(worldIdentity,lineageId,regions,population){const avg=k=>Math.floor(regions.reduce((a,r)=>a+r[k],0)/regions.length);return Object.freeze({production:1,transport:0,materials:avg('materialResourcePpm')>400000?1:0,energy:avg('energyAccessPpm')>400000?1:0,communication:0,medicine:0,construction:population>2500?1:0,conflict:0,knowledgeContinuityPpm:300000+(V.unitPpm(VERSION,worldIdentity,lineageId,'knowledge')%550001),exchangePpm:avg('transportPpm'),environmentImpactPpm:0});}
function routeCost(a,b,regions,technology){const by=new Map(regions.map(r=>[r.regionId,r])),x=by.get(a.regionId),y=by.get(b.regionId),access=Math.floor((x.transportPpm+y.transportPpm)/2),barrier=Math.floor((x.barrierPpm+y.barrierPpm)/2);if(access<=100000&&barrier>=900000)return 1000000;const distance=120000+(V.unitPpm(VERSION,a.regionId,b.regionId,'distance')%700001);return V.clamp(Math.floor(distance*.45+barrier*.35+(1000000-access)*.2)-technology.transport*45000,20000,1000000);}
function trade(settlements,regions,technology){const active=settlements.filter(s=>s.status==='ACTIVE'),edges=[];for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length&&edges.length<96;j++){const a=active[i],b=active[j],costPpm=routeCost(a,b,regions,technology);if(costPpm>=1000000)continue;const sa=Math.max(0,(a.stocks.SUBSISTENCE_GOODS||0)-a.population),sb=Math.max(0,(b.stocks.SUBSISTENCE_GOODS||0)-b.population),md=Math.abs((a.stocks.MATERIAL_GOODS||0)-(b.stocks.MATERIAL_GOODS||0)),potential=Math.min(1000000,Math.floor((sa+sb+md)*1000000/Math.max(1,a.population+b.population)));if(potential+V.unitPpm(VERSION,a.settlementId,b.settlementId,'trade')/4>costPpm)edges.push(Object.freeze({edgeId:V.deriveId('trade-edge',a.settlementId,b.settlementId),from:a.settlementId,to:b.settlementId,costPpm,flowUnits:Math.max(1,Math.floor((1000000-costPpm)*(1+sa+sb+md)/1000000)),mode:costPpm<250000?'HIGH_ACCESS_CORRIDOR':costPpm<600000?'REGIONAL_ROUTE':'DIFFICULT_ROUTE',status:'ACTIVE',modelDerivedRouteCost:true}));}return Object.freeze(edges);}
function metrics(settlements,edges){return Object.freeze(settlements.map(s=>{const incident=edges.filter(e=>e.from===s.settlementId||e.to===s.settlementId),flowUnits=incident.reduce((n,e)=>n+e.flowUnits,0),centralityPpm=V.clamp(incident.length*110000+Math.min(450000,flowUnits*120),0,1000000);return Object.freeze({settlementId:s.settlementId,degree:incident.length,flowUnits,centralityPpm,isolationPpm:1000000-centralityPpm});}));}
O.v1CivilizationFoundation=Object.freeze({VERSION,AUTHORITY:AUTH,TYPES,typeFor,resource,region,suitability,settlements,technology,routeCost,trade,metrics});
})(globalThis);
