(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-render-webgl2-pipeline-1';
const AUTHORITY='PRESENTATION_ONLY';
function fail(code,message){const e=new Error(message);e.code=code;throw e}
function safeInt(v,label,min=0,max=0x7fffffff){v=Number(v);if(!Number.isSafeInteger(v)||v<min||v>max)fail('BOUNDS','invalid '+label);return v}
function finite(v,label){v=Number(v);if(!Number.isFinite(v))fail('NUMBER','invalid '+label);return v}
function key(v){v=String(v||'');if(!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,159}$/.test(v))fail('ID','invalid resource id');return v}
function create(gl,{maxPrograms=64,maxTextures=128,maxFramebuffers=64,maxQueries=32,maxTrackedBytes=134217728}={}){
 if(!gl)fail('WEBGL2','context required');
 safeInt(maxPrograms,'maxPrograms',1,1024);safeInt(maxTextures,'maxTextures',1,4096);safeInt(maxFramebuffers,'maxFramebuffers',1,1024);safeInt(maxQueries,'maxQueries',0,1024);safeInt(maxTrackedBytes,'maxTrackedBytes',1,1073741824);
 let live=new Map(),trackedBytes=0,created=0,deleted=0,invalidated=0,generation=1,valid=true,disposed=false,activeQuery=null,timerExt=null;
 const caps={program:maxPrograms,texture:maxTextures,framebuffer:maxFramebuffers,query:maxQueries};
 function count(kind){let n=0;for(const r of live.values())if(r.kind===kind)n++;return n}
 function ensure(){if(disposed)fail('DISPOSED','pipeline disposed');if(!valid)fail('CONTEXT_LOST','context unavailable')}
 function preflight(id,kind,bytes){ensure();id=key(id);bytes=safeInt(bytes,'resource bytes',0,maxTrackedBytes);if(live.has(id))fail('COLLISION','resource exists: '+id);if(count(kind)>=caps[kind])fail('BUDGET',kind+' count');if(trackedBytes+bytes>maxTrackedBytes)fail('BUDGET','tracked bytes');return {id,bytes}}
 function put(pre,kind,handle,destroy){live.set(pre.id,{id:pre.id,kind,handle,bytes:pre.bytes,destroy});trackedBytes+=pre.bytes;created++;return handle}
 function shader(type,source){ensure();if(typeof source!=='string'||source.length<1||source.length>1048576)fail('SHADER','invalid source');const s=gl.createShader(type);if(!s)fail('SHADER','create failed');gl.shaderSource(s,source);gl.compileShader(s);if(gl.getShaderParameter&&!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const log=String(gl.getShaderInfoLog?.(s)||'compile failed').slice(0,4096);gl.deleteShader?.(s);fail('SHADER_COMPILE',log)}return s}
 function program(id,vertexSource,fragmentSource){const pre=preflight(id,'program',0),vs=shader(gl.VERTEX_SHADER,vertexSource),fs=shader(gl.FRAGMENT_SHADER,fragmentSource),p=gl.createProgram();if(!p){gl.deleteShader?.(vs);gl.deleteShader?.(fs);fail('PROGRAM','create failed')}let committed=false;try{gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);if(gl.getProgramParameter&&!gl.getProgramParameter(p,gl.LINK_STATUS))fail('PROGRAM_LINK',String(gl.getProgramInfoLog?.(p)||'link failed').slice(0,4096));const out=put(pre,'program',p,x=>gl.deleteProgram?.(x));committed=true;return out}finally{gl.deleteShader?.(vs);gl.deleteShader?.(fs);if(!committed)gl.deleteProgram?.(p)}}
 function texture2D(id,{width,height,internalFormat,format,type,data=null,minFilter,magFilter,wrapS,wrapT,mipmaps=false,bytesPerPixel=4}={}){ensure();width=safeInt(width,'width',1,16384);height=safeInt(height,'height',1,16384);bytesPerPixel=safeInt(bytesPerPixel,'bytesPerPixel',1,32);const bytes=safeInt(width*height*bytesPerPixel,'texture bytes',1,maxTrackedBytes),pre=preflight(id,'texture',bytes),t=gl.createTexture();if(!t)fail('TEXTURE','create failed');let committed=false;try{gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri?.(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,minFilter??gl.LINEAR);gl.texParameteri?.(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,magFilter??gl.LINEAR);gl.texParameteri?.(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,wrapS??gl.CLAMP_TO_EDGE);gl.texParameteri?.(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,wrapT??gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,internalFormat??gl.RGBA8,width,height,0,format??gl.RGBA,type??gl.UNSIGNED_BYTE,data);if(mipmaps)gl.generateMipmap?.(gl.TEXTURE_2D);const out=put(pre,'texture',t,x=>gl.deleteTexture?.(x));committed=true;return out}finally{if(!committed)gl.deleteTexture?.(t)}}
 function framebuffer(id,{colorTexture=null,depthTexture=null}={}){const pre=preflight(id,'framebuffer',0),f=gl.createFramebuffer();if(!f)fail('FRAMEBUFFER','create failed');let committed=false;try{gl.bindFramebuffer(gl.FRAMEBUFFER,f);if(colorTexture)gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,colorTexture,0);if(depthTexture)gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,depthTexture,0);if(gl.checkFramebufferStatus&&gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)fail('FRAMEBUFFER_INCOMPLETE','framebuffer incomplete');const out=put(pre,'framebuffer',f,x=>gl.deleteFramebuffer?.(x));committed=true;return out}finally{if(!committed)gl.deleteFramebuffer?.(f)}}
 function timerSupport(){ensure();if(timerExt!==null)return timerExt;timerExt=gl.getExtension?.('EXT_disjoint_timer_query_webgl2')||false;return timerExt}
 function beginTimer(id){ensure();if(activeQuery)fail('QUERY_STATE','query already active');const ext=timerSupport();if(!ext)return Object.freeze({supported:false,id:key(id)});const pre=preflight(id,'query',0),q=gl.createQuery();if(!q)fail('QUERY','create failed');const rid=pre.id;put(pre,'query',q,x=>gl.deleteQuery?.(x));try{gl.beginQuery(ext.TIME_ELAPSED_EXT,q);activeQuery={id:rid,q,ext};return Object.freeze({supported:true,id:rid})}catch(e){release(rid);throw e}}
 function endTimer(){ensure();if(!activeQuery)return Object.freeze({supported:false,reason:'NO_ACTIVE_QUERY'});gl.endQuery(activeQuery.ext.TIME_ELAPSED_EXT);const id=activeQuery.id;activeQuery=null;return Object.freeze({supported:true,id})}
 function pollTimer(id){ensure();id=key(id);const r=live.get(id);if(!r||r.kind!=='query')return Object.freeze({available:false,gpuMs:null,reason:'UNKNOWN_QUERY'});const ext=timerSupport();const available=!!gl.getQueryParameter?.(r.handle,gl.QUERY_RESULT_AVAILABLE),disjoint=!!gl.getParameter?.(ext.GPU_DISJOINT_EXT);if(!available||disjoint)return Object.freeze({available:false,gpuMs:null,disjoint});const ns=finite(gl.getQueryParameter(r.handle,gl.QUERY_RESULT),'query result');release(id);return Object.freeze({available:true,gpuMs:ns/1000000,disjoint:false})}
 function release(id){id=key(id);const r=live.get(id);if(!r)return false;if(activeQuery&&activeQuery.id===id)fail('QUERY_STATE','active query');try{r.destroy(r.handle)}catch(e){fail('DELETE_FAILED',String(e?.message||e))}live.delete(id);trackedBytes-=r.bytes;deleted++;return true}
 function lose(){if(disposed)return snapshot();if(activeQuery)activeQuery=null;invalidated+=live.size;live.clear();trackedBytes=0;valid=false;return snapshot()}
 function restore(nextGl){if(disposed||valid||!nextGl)fail('STATE','invalid restore');gl=nextGl;valid=true;generation++;timerExt=null;return snapshot()}
 function dispose(){if(disposed)return snapshot();if(valid){if(activeQuery)activeQuery=null;for(const id of [...live.keys()])release(id)}disposed=true;valid=false;return snapshot()}
 function snapshot(){return Object.freeze({version:VERSION,authority:AUTHORITY,generation,valid,disposed,liveResources:live.size,programs:count('program'),textures:count('texture'),framebuffers:count('framebuffer'),queries:count('query'),trackedBytes,created,deleted,invalidated,accountingExact:created===deleted+invalidated+live.size,physicalDriverVramBytes:'NOT_MEASURABLE_PORTABLY',timerQuerySupport:timerExt===null?'UNPROBED':!!timerExt})}
 return Object.freeze({program,texture2D,framebuffer,timerSupport,beginTimer,endTimer,pollTimer,release,lose,restore,dispose,snapshot});
}
O.renderWebGL2Pipeline=Object.freeze({VERSION,AUTHORITY,create});
})(typeof globalThis!=='undefined'?globalThis:this);
