(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-render-webgl2-resources-6';
const AUTHORITY='PRESENTATION_ONLY';
const FRAME_VERSION='ofu-render-webgl2-frame-consumer-2';
const FRAME_BACKEND='V2X13_WEBGL2_PIXEL_CONSUMER';
const DOMAINS=Object.freeze(['MACRO','SYSTEM','PLANET','TERRAIN','WATER','VEGETATION','ORGANISM','STRUCTURE','MATTER']);
const DOMAIN_SET=new Set(DOMAINS);
function fail(code,message){const e=new Error(message);e.code=code;throw e}
function key(v){const s=String(v||'');if(!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,159}$/.test(s))fail('ID','invalid resource id');return s}
function safeBytes(v,label='bytes'){v=Number(v);if(!Number.isSafeInteger(v)||v<0)fail('BUDGET','invalid '+label);return v}
function bound(v,label,min,max){v=Number(v);if(!Number.isSafeInteger(v)||v<min||v>max)fail('BUDGET','invalid '+label);return v}
function finite(v,label='number'){v=Number(v);if(!Number.isFinite(v))fail('NUMBER','invalid '+label);return v}
function clamp(v,a,b,label='number'){return Math.max(a,Math.min(b,finite(v,label)))}
function finiteArray(value,length,label){if(!Array.isArray(value)&&!ArrayBuffer.isView(value))fail('INPUT',label+' required');if(value.length!==length)fail('INPUT',label+' length');const out=new Float32Array(length);for(let i=0;i<length;i++)out[i]=finite(value[i],label+'['+i+']');return out}
function createManager(gl,{maxResources=512,maxTrackedBytes=134217728,maxTextureDimension=8192}={}){
 if(!gl)fail('WEBGL2','context required');
 if(!Number.isSafeInteger(maxResources)||maxResources<1||maxResources>4096)fail('BUDGET','resource limit');
 maxTrackedBytes=safeBytes(maxTrackedBytes,'maxTrackedBytes');if(maxTrackedBytes<1||maxTrackedBytes>1073741824)fail('BUDGET','tracked byte limit');
 if(!Number.isSafeInteger(maxTextureDimension)||maxTextureDimension<1||maxTextureDimension>32768)fail('BUDGET','texture dimension limit');
 let context=gl,generation=1,valid=true,disposed=false,trackedBytes=0,created=0,deleted=0,invalidated=0,failedCreates=0;
 const resources=new Map();
 function checkedAdd(a,b,label='bytes'){const n=a+b;if(!Number.isSafeInteger(n)||n<0)fail('BUDGET','overflow '+label);return n}
 function preflight(id,bytes){if(disposed||!valid)fail('CONTEXT_LOST','resource manager unavailable');if(resources.has(id))fail('COLLISION','duplicate resource '+id);if(resources.size>=maxResources)fail('BUDGET','resource count');if(checkedAdd(trackedBytes,bytes)>maxTrackedBytes)fail('BUDGET','tracked byte limit')}
 function own(id,kind,bytes,handles,destroy){resources.set(id,{id,kind,bytes,handles,destroy,generation});trackedBytes=checkedAdd(trackedBytes,bytes);created++;return handles.primary||handles}
 function guardedCreate(id,kind,bytes,build,destroy){id=key(id);bytes=safeBytes(bytes);preflight(id,bytes);let handles=null;try{handles=build();if(!handles)fail('ALLOCATE','empty '+kind);return own(id,kind,bytes,handles,()=>destroy(handles))}catch(e){failedCreates++;if(handles){try{destroy(handles)}catch{}}throw e}}
 function createBuffer(id,target,data,usage){if(!data||!Number.isSafeInteger(data.byteLength))fail('BUFFER','typed data required');return guardedCreate(id,'buffer',data.byteLength,()=>{let h=null;try{h=context.createBuffer();if(!h)fail('ALLOCATE','buffer');context.bindBuffer(target,h);context.bufferData(target,data,usage);return{primary:h}}catch(e){if(h)try{context.deleteBuffer(h)}catch{}throw e}},h=>context.deleteBuffer(h.primary))}
 function enumIs(value,name){const e=Number(context[name]);return Number.isFinite(e)&&value===e}
 function inferredTransferBytesPerPixel(format,type){const packed=[['UNSIGNED_SHORT_5_6_5',2],['UNSIGNED_SHORT_4_4_4_4',2],['UNSIGNED_SHORT_5_5_5_1',2],['UNSIGNED_INT_2_10_10_10_REV',4],['UNSIGNED_INT_10F_11F_11F_REV',4],['UNSIGNED_INT_5_9_9_9_REV',4],['UNSIGNED_INT_24_8',4],['FLOAT_32_UNSIGNED_INT_24_8_REV',8]];for(const [name,bytes] of packed)if(enumIs(type,name))return bytes;let channels=0;if(enumIs(format,'RED')||enumIs(format,'RED_INTEGER')||enumIs(format,'DEPTH_COMPONENT'))channels=1;else if(enumIs(format,'RG')||enumIs(format,'RG_INTEGER'))channels=2;else if(enumIs(format,'RGB')||enumIs(format,'RGB_INTEGER'))channels=3;else if(enumIs(format,'RGBA')||enumIs(format,'RGBA_INTEGER'))channels=4;else if(enumIs(format,'DEPTH_STENCIL'))channels=1;let scalar=0;if(enumIs(type,'BYTE')||enumIs(type,'UNSIGNED_BYTE'))scalar=1;else if(enumIs(type,'SHORT')||enumIs(type,'UNSIGNED_SHORT')||enumIs(type,'HALF_FLOAT'))scalar=2;else if(enumIs(type,'INT')||enumIs(type,'UNSIGNED_INT')||enumIs(type,'FLOAT'))scalar=4;return channels&&scalar?channels*scalar:null}
 function inferredStorageBytesPerPixel(internalFormat){const groups=[
  [1,['R8','R8_SNORM','R8UI','R8I']],
  [2,['R16F','R16UI','R16I','RG8','RG8_SNORM','RG8UI','RG8I','RGB565','RGBA4','RGB5_A1','DEPTH_COMPONENT16']],
  [3,['RGB8','SRGB8','RGB8_SNORM','RGB8UI','RGB8I']],
  [4,['R32F','R32UI','R32I','RG16F','RG16UI','RG16I','R11F_G11F_B10F','RGB9_E5','RGBA8','SRGB8_ALPHA8','RGBA8_SNORM','RGB10_A2','RGBA8UI','RGB10_A2UI','RGBA8I','DEPTH_COMPONENT24','DEPTH_COMPONENT32F','DEPTH24_STENCIL8']],
  [6,['RGB16F','RGB16UI','RGB16I']],
  [8,['RG32F','RG32UI','RG32I','RGBA16F','RGBA16UI','RGBA16I','DEPTH32F_STENCIL8']],
  [12,['RGB32F','RGB32UI','RGB32I']],
  [16,['RGBA32F','RGBA32UI','RGBA32I']]
 ];for(const [bytes,names] of groups)for(const name of names)if(enumIs(internalFormat,name))return bytes;return null}
 function resolveBytesPerPixel(internalFormat,format,type,declared){const transfer=inferredTransferBytesPerPixel(format,type),storage=inferredStorageBytesPerPixel(internalFormat),required=transfer==null?storage:storage==null?transfer:Math.max(transfer,storage);if(declared==null){if(required==null)fail('BUDGET','bytesPerPixel required for unrecognized texture format');return required}declared=safeBytes(declared,'bytesPerPixel');if(declared<1||declared>32)fail('BUDGET','bytesPerPixel range');if(required!=null&&declared<required)fail('BUDGET','bytesPerPixel understates texture storage');return declared}
 function textureBytes({width,height,bytesPerPixel,mipLevels=1}){width=safeBytes(width,'width');height=safeBytes(height,'height');bytesPerPixel=safeBytes(bytesPerPixel,'bytesPerPixel');mipLevels=safeBytes(mipLevels,'mipLevels');if(width<1||height<1||width>maxTextureDimension||height>maxTextureDimension||mipLevels<1||mipLevels>16||bytesPerPixel<1||bytesPerPixel>32)fail('BUDGET','texture shape');const maxMip=1+Math.floor(Math.log2(Math.max(width,height)));if(mipLevels>maxMip)fail('BUDGET','mip levels exceed texture chain');let total=0,w=width,h=height;for(let i=0;i<mipLevels;i++){const level=w*h*bytesPerPixel;if(!Number.isSafeInteger(level))fail('BUDGET','texture byte overflow');total=checkedAdd(total,level,'texture bytes');w=Math.max(1,w>>1);h=Math.max(1,h>>1)}return total}
 function createTexture2D(id,opt={}){const {width,height,internalFormat,format,type,data=null,bytesPerPixel=null,mipLevels=1,minFilter=context.LINEAR,magFilter=context.LINEAR,wrapS=context.CLAMP_TO_EDGE,wrapT=context.CLAMP_TO_EDGE}=opt,bpp=resolveBytesPerPixel(internalFormat,format,type,bytesPerPixel),bytes=textureBytes({width,height,bytesPerPixel:bpp,mipLevels});return guardedCreate(id,'texture',bytes,()=>{let h=null;try{h=context.createTexture();if(!h)fail('ALLOCATE','texture');context.bindTexture(context.TEXTURE_2D,h);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MIN_FILTER,minFilter);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MAG_FILTER,magFilter);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_S,wrapS);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_T,wrapT);if(mipLevels>1){if(!Number.isFinite(Number(context.TEXTURE_MAX_LEVEL)))fail('WEBGL2','TEXTURE_MAX_LEVEL required for bounded mip allocation');context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MAX_LEVEL,mipLevels-1)}context.texImage2D(context.TEXTURE_2D,0,internalFormat,width,height,0,format,type,data);if(mipLevels>1)context.generateMipmap(context.TEXTURE_2D);return{primary:h}}catch(e){if(h)try{context.deleteTexture(h)}catch{}throw e}},h=>context.deleteTexture(h.primary))}
 function compileShader(type,source){const s=context.createShader(type);if(!s)fail('ALLOCATE','shader');context.shaderSource(s,String(source));context.compileShader(s);if(!context.getShaderParameter(s,context.COMPILE_STATUS)){const log=String(context.getShaderInfoLog(s)||'shader compile failed').slice(0,2048);context.deleteShader(s);fail('SHADER_COMPILE',log)}return s}
 function createProgram(id,{vertexSource,fragmentSource}={}){id=key(id);preflight(id,0);let vs=null,fs=null,p=null;try{vs=compileShader(context.VERTEX_SHADER,vertexSource);fs=compileShader(context.FRAGMENT_SHADER,fragmentSource);p=context.createProgram();if(!p)fail('ALLOCATE','program');context.attachShader(p,vs);context.attachShader(p,fs);context.linkProgram(p);if(!context.getProgramParameter(p,context.LINK_STATUS))fail('PROGRAM_LINK',String(context.getProgramInfoLog(p)||'program link failed').slice(0,2048));context.deleteShader(vs);context.deleteShader(fs);vs=fs=null;return own(id,'program',0,{primary:p},()=>context.deleteProgram(p))}catch(e){failedCreates++;if(vs)try{context.deleteShader(vs)}catch{}if(fs)try{context.deleteShader(fs)}catch{}if(p)try{context.deleteProgram(p)}catch{}throw e}}
 function createVertexArray(id){return guardedCreate(id,'vao',0,()=>{const h=context.createVertexArray();if(!h)fail('ALLOCATE','vertex array');return{primary:h}},h=>context.deleteVertexArray(h.primary))}
 function createRenderTarget(id,{width,height,colorInternalFormat,colorFormat,colorType,bytesPerPixel=null,depth=true}={}){id=key(id);const bpp=resolveBytesPerPixel(colorInternalFormat,colorFormat,colorType,bytesPerPixel),colorBytes=textureBytes({width,height,bytesPerPixel:bpp,mipLevels:1}),depthBytes=depth?textureBytes({width,height,bytesPerPixel:4,mipLevels:1}):0,total=checkedAdd(colorBytes,depthBytes,'render target bytes');return guardedCreate(id,'render-target',total,()=>{let texture=null,framebuffer=null,renderbuffer=null;try{texture=context.createTexture();if(!texture)fail('ALLOCATE','render target texture');context.bindTexture(context.TEXTURE_2D,texture);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MIN_FILTER,context.LINEAR);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MAG_FILTER,context.LINEAR);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_S,context.CLAMP_TO_EDGE);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_T,context.CLAMP_TO_EDGE);context.texImage2D(context.TEXTURE_2D,0,colorInternalFormat,width,height,0,colorFormat,colorType,null);framebuffer=context.createFramebuffer();if(!framebuffer)fail('ALLOCATE','framebuffer');context.bindFramebuffer(context.FRAMEBUFFER,framebuffer);context.framebufferTexture2D(context.FRAMEBUFFER,context.COLOR_ATTACHMENT0,context.TEXTURE_2D,texture,0);if(depth){renderbuffer=context.createRenderbuffer();if(!renderbuffer)fail('ALLOCATE','renderbuffer');context.bindRenderbuffer(context.RENDERBUFFER,renderbuffer);context.renderbufferStorage(context.RENDERBUFFER,context.DEPTH_COMPONENT24,width,height);context.framebufferRenderbuffer(context.FRAMEBUFFER,context.DEPTH_ATTACHMENT,context.RENDERBUFFER,renderbuffer)}const status=context.checkFramebufferStatus(context.FRAMEBUFFER);if(status!==context.FRAMEBUFFER_COMPLETE)fail('FRAMEBUFFER','incomplete '+status);return{primary:framebuffer,framebuffer,texture,renderbuffer}}catch(e){if(renderbuffer)try{context.deleteRenderbuffer(renderbuffer)}catch{}if(framebuffer)try{context.deleteFramebuffer(framebuffer)}catch{}if(texture)try{context.deleteTexture(texture)}catch{}throw e}},h=>{if(h.renderbuffer)context.deleteRenderbuffer(h.renderbuffer);context.deleteFramebuffer(h.framebuffer);context.deleteTexture(h.texture)})}
 function handles(id){id=key(id);if(disposed||!valid)fail('CONTEXT_LOST','resource manager unavailable');const r=resources.get(id);if(!r)return null;return Object.freeze({...r.handles})}
 function release(id){id=key(id);const r=resources.get(id);if(!r)return false;try{r.destroy()}catch(e){e.code=e.code||'DELETE_FAILED';throw e}resources.delete(id);trackedBytes-=r.bytes;deleted++;return true}
 function contextLost(){if(disposed)return snapshot();invalidated+=resources.size;resources.clear();trackedBytes=0;valid=false;return snapshot()}
 function contextRestored(next){if(disposed||valid||!next)fail('STATE','invalid restore');context=next;generation++;valid=true;return snapshot()}
 function dispose(){if(disposed)return snapshot();if(valid){for(const id of [...resources.keys()])release(id)}else resources.clear();disposed=true;valid=false;return snapshot()}
 function snapshot(){const byKind={};for(const r of resources.values())byKind[r.kind]=(byKind[r.kind]||0)+1;return Object.freeze({version:VERSION,authority:AUTHORITY,generation,valid,disposed,liveResources:resources.size,liveByKind:Object.freeze(byKind),trackedBytes,maxTrackedBytes,created,deleted,invalidated,failedCreates,accountingExact:created===deleted+invalidated+resources.size,physicalDriverVramBytes:'NOT_MEASURABLE_PORTABLY'})}
 return Object.freeze({createBuffer,createTexture2D,createProgram,createVertexArray,createRenderTarget,handles,release,contextLost,contextRestored,dispose,snapshot});
}

const FLAT_VERTEX=`#version 300 es
precision highp float;
layout(location=0) in vec3 aPosition;uniform mat4 uViewProjection;uniform float uPointSize;void main(){gl_Position=uViewProjection*vec4(aPosition,1.0);gl_PointSize=uPointSize;}`;
const FLAT_FRAGMENT=`#version 300 es
precision highp float;
out vec4 outColor;uniform vec3 uColor;uniform float uOpacity;void main(){outColor=vec4(uColor,uOpacity);}`;
const IDENTITY=Object.freeze([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function fnvStep(h,b){h^=b;return Math.imul(h,16777619)>>>0}
function hashPairByte(h,b){h[0]=fnvStep(h[0],b);h[1]=fnvStep(h[1],b);return h}
function hashPairString(h,s){s=String(s);for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);hashPairByte(h,c&255);hashPairByte(h,c>>>8)}hashPairByte(h,255);return h}
function hashPairTyped(h,v){const bytes=new Uint8Array(v.buffer,v.byteOffset,v.byteLength);for(let i=0;i<bytes.length;i++)hashPairByte(h,bytes[i]);hashPairByte(h,254);return h}
function packetFingerprint(packet){const h=[2166136261>>>0,3339675911>>>0];for(const s of [packet.frameId,packet.sceneId,packet.selectionId||'',packet.semanticSignature,packet.aaMode,String(packet.fog),String(packet.viewport.width),String(packet.viewport.height)])hashPairString(h,s);hashPairTyped(h,packet.clearColor);hashPairTyped(h,packet.camera.viewProjection);hashPairTyped(h,packet.camera.position);hashPairTyped(h,packet.lighting.direction);hashPairTyped(h,packet.lighting.color);for(const s of [packet.lighting.intensity,packet.lighting.ambient])hashPairString(h,String(s));for(const draw of packet.draws){for(const s of [draw.id,draw.domain,draw.primitive,String(draw.lit),String(draw.lod.level),String(draw.lod.transition)])hashPairString(h,s);hashPairTyped(h,draw.positions);if(draw.normals)hashPairTyped(h,draw.normals);if(draw.indices)hashPairTyped(h,draw.indices);hashPairTyped(h,draw.material.baseColor);hashPairTyped(h,draw.material.emissive);for(const s of [draw.material.roughness,draw.material.metallic,draw.material.opacity,draw.material.pointSize])hashPairString(h,String(s))}return h.map(x=>(x>>>0).toString(16).padStart(8,'0')).join('')}
function cloneNormalizedPacket(packet){return Object.freeze({...packet,camera:Object.freeze({viewProjection:new Float32Array(packet.camera.viewProjection),position:new Float32Array(packet.camera.position)}),clearColor:new Float32Array(packet.clearColor),lighting:Object.freeze({...packet.lighting,direction:new Float32Array(packet.lighting.direction),color:new Float32Array(packet.lighting.color)}),draws:Object.freeze(packet.draws.map(draw=>Object.freeze({...draw,positions:new Float32Array(draw.positions),normals:draw.normals?new Float32Array(draw.normals):null,indices:draw.indices?new Uint32Array(draw.indices):null,material:Object.freeze({...draw.material,baseColor:new Float32Array(draw.material.baseColor),emissive:new Float32Array(draw.material.emissive)}),lod:Object.freeze({...draw.lod})})))})}
function createFrameConsumer(initialGl,{canvas=null,maxDraws=2048,maxVertices=1048576,maxIndices=3145728,maxFrameBytes=33554432,maxRetainedBytes=33554432,maxTrackedBytes=268435456,maxTextureDimension=8192}={}){
 if(!initialGl)fail('WEBGL2','context required');
 maxDraws=bound(maxDraws,'maxDraws',1,8192);maxVertices=bound(maxVertices,'maxVertices',1,4194304);maxIndices=bound(maxIndices,'maxIndices',0,12582912);maxFrameBytes=safeBytes(maxFrameBytes,'maxFrameBytes');maxRetainedBytes=safeBytes(maxRetainedBytes,'maxRetainedBytes');maxTrackedBytes=safeBytes(maxTrackedBytes,'maxTrackedBytes');maxTextureDimension=bound(maxTextureDimension,'maxTextureDimension',1,32768);
 if(maxFrameBytes<1||maxFrameBytes>268435456||maxRetainedBytes<1||maxRetainedBytes>268435456||maxRetainedBytes<maxFrameBytes)fail('BUDGET','frame retention bounds');
 let gl=initialGl,manager=createManager(gl,{maxResources:64,maxTrackedBytes,maxTextureDimension}),valid=true,disposed=false,frameCount=0,replayCount=0,totalDrawCalls=0,totalVertices=0,totalIndices=0,lastWitness=null,lastPacket=null,programs=new Map(),targetKey=null,targetId='v2x13.frame.color',lostEvents=0,restoredEvents=0;
 const listeners=[];
 function checkedAdd(a,b,label){const n=a+b;if(!Number.isSafeInteger(n)||n<0)fail('BUDGET',label);return n}
 function color3(value,label,fallback,max=1){if(value==null)value=fallback;const v=finiteArray(value,3,label);for(let i=0;i<3;i++)v[i]=clamp(v[i],0,max,label+'['+i+']');return v}
 function normalizePacket(raw){
  if(!raw||typeof raw!=='object')fail('INPUT','frame packet required');
  const frameId=key(raw.frameId),sceneId=key(raw.sceneId),selectionId=raw.selectionId==null?null:key(raw.selectionId),semanticSignature=key(raw.semanticSignature);
  const viewport=raw.viewport||{},width=bound(viewport.width,'viewport.width',1,maxTextureDimension),height=bound(viewport.height,'viewport.height',1,maxTextureDimension);
  const cameraRaw=raw.camera;if(!cameraRaw||typeof cameraRaw!=='object')fail('INPUT','external camera required');const camera=Object.freeze({viewProjection:finiteArray(cameraRaw.viewProjection,16,'camera.viewProjection'),position:finiteArray(cameraRaw.position,3,'camera.position'),authority:'EXTERNAL_READ_ONLY'});
  const clearRaw=raw.clearColor==null?[0,0,0,1]:raw.clearColor;if((!Array.isArray(clearRaw)&&!ArrayBuffer.isView(clearRaw))||clearRaw.length!==4)fail('COLOR','clearColor');const clearColor=new Float32Array(4);for(let i=0;i<4;i++)clearColor[i]=clamp(clearRaw[i],0,1,'clearColor['+i+']');
  const aaMode=String(raw.aaMode==null?'FXAA':raw.aaMode);if(!['FXAA','DEFAULT_MSAA','NONE'].includes(aaMode))fail('AA','unsupported AA mode');
  const fog=raw.fog===true;
  const l=raw.lighting||{},direction=finiteArray(l.direction==null?[0,-1,0]:l.direction,3,'lighting.direction');if(Math.hypot(direction[0],direction[1],direction[2])<=1e-8)fail('VECTOR','lighting.direction zero');const lighting=Object.freeze({direction,color:color3(l.color,'lighting.color',[1,1,1]),intensity:clamp(l.intensity==null?1:l.intensity,0,1000000,'lighting.intensity'),ambient:clamp(l.ambient==null?.08:l.ambient,0,1,'lighting.ambient'),authority:'PRESENTATION_ONLY'});
  if(!Array.isArray(raw.draws)||raw.draws.length>maxDraws)fail('BUDGET','draw count');const seen=new Set,draws=[];let frameBytes=0,vertices=0,indices=0;
  for(const source of raw.draws){if(!source||typeof source!=='object')fail('INPUT','draw');const id=key(source.id);if(seen.has(id))fail('COLLISION','draw id');seen.add(id);const domain=String(source.domain||'').toUpperCase();if(!DOMAIN_SET.has(domain))fail('DOMAIN','unsupported render domain');const primitive=String(source.primitive||'TRIANGLES').toUpperCase();if(!['POINTS','LINES','TRIANGLES'].includes(primitive))fail('PRIMITIVE','unsupported primitive');
   if(!Array.isArray(source.positions)&&!ArrayBuffer.isView(source.positions))fail('GEOMETRY','positions required');if(source.positions.length<3||source.positions.length%3)fail('GEOMETRY','position components');const vertexCount=source.positions.length/3;if(vertexCount>maxVertices-vertices)fail('BUDGET','vertex count');const positionBytes=source.positions.length*4;if(!Number.isSafeInteger(positionBytes)||frameBytes+positionBytes>maxFrameBytes)fail('BUDGET','frame byte limit');const positions=new Float32Array(source.positions.length);for(let i=0;i<positions.length;i++)positions[i]=finite(source.positions[i],'positions['+i+']');if(primitive==='LINES'&&vertexCount%2)fail('GEOMETRY','line vertex parity');if(primitive==='TRIANGLES'&&source.indices==null&&vertexCount%3)fail('GEOMETRY','triangle vertex parity');vertices=checkedAdd(vertices,vertexCount,'vertex count');frameBytes=checkedAdd(frameBytes,positions.byteLength,'frame bytes');
   const lit=source.lit!==false&&primitive==='TRIANGLES';let normals=null;if(lit){if(!Array.isArray(source.normals)&&!ArrayBuffer.isView(source.normals))fail('GEOMETRY','lit normals required');if(source.normals.length!==source.positions.length)fail('GEOMETRY','normal components');const normalBytes=source.normals.length*4;if(!Number.isSafeInteger(normalBytes)||frameBytes+normalBytes>maxFrameBytes)fail('BUDGET','frame byte limit');normals=new Float32Array(source.normals.length);for(let i=0;i<normals.length;i++)normals[i]=finite(source.normals[i],'normals['+i+']');frameBytes=checkedAdd(frameBytes,normals.byteLength,'frame bytes')}
   let indexData=null;if(source.indices!=null){if(!Array.isArray(source.indices)&&!ArrayBuffer.isView(source.indices))fail('GEOMETRY','indices');if(source.indices.length>maxIndices-indices)fail('BUDGET','index count');const indexBytes=source.indices.length*4;if(!Number.isSafeInteger(indexBytes)||frameBytes+indexBytes>maxFrameBytes)fail('BUDGET','frame byte limit');indexData=new Uint32Array(source.indices.length);for(let i=0;i<source.indices.length;i++){const q=Number(source.indices[i]);if(!Number.isSafeInteger(q)||q<0||q>=vertexCount)fail('GEOMETRY','index range');indexData[i]=q}if(primitive==='LINES'&&indexData.length%2)fail('GEOMETRY','line index parity');if(primitive==='TRIANGLES'&&indexData.length%3)fail('GEOMETRY','triangle index parity');indices=checkedAdd(indices,indexData.length,'index count');if(indices>maxIndices)fail('BUDGET','index count');frameBytes=checkedAdd(frameBytes,indexData.byteLength,'frame bytes')}
   const m=source.material||{},baseColor=color3(m.baseColor,'material.baseColor',[.5,.5,.5]),emissive=color3(m.emissive,'material.emissive',[0,0,0],64),material=Object.freeze({baseColor,emissive,roughness:clamp(m.roughness==null?.65:m.roughness,.04,1,'material.roughness'),metallic:clamp(m.metallic==null?0:m.metallic,0,1,'material.metallic'),opacity:clamp(m.opacity==null?1:m.opacity,0,1,'material.opacity'),pointSize:clamp(m.pointSize==null?2:m.pointSize,1,128,'material.pointSize'),physicalMaterialIdentityClaim:false});
   const lodRaw=source.lod||{},lod=Object.freeze({level:bound(lodRaw.level==null?0:lodRaw.level,'lod.level',0,32),transition:clamp(lodRaw.transition==null?0:lodRaw.transition,0,1,'lod.transition'),authority:'EXTERNAL_READ_ONLY'});
   draws.push(Object.freeze({id,domain,primitive,positions,normals,indices:indexData,vertexCount,lit,material,lod}));
  }
  if(frameBytes>maxFrameBytes||frameBytes>maxRetainedBytes)fail('BUDGET','frame byte limit');
  return Object.freeze({version:FRAME_VERSION,authority:AUTHORITY,frameId,sceneId,selectionId,semanticSignature,viewport:Object.freeze({width,height}),camera,clearColor,aaMode,fog,lighting,draws:Object.freeze(draws),frameBytes,vertices,indices});
 }
 function essentialUniform(program,name){const loc=gl.getUniformLocation(program,name);if(loc==null)fail('SHADER_INTERFACE','missing uniform '+name);return loc}
 function setMatrix(program,name,value){const loc=essentialUniform(program,name);gl.uniformMatrix4fv(loc,false,value)}
 function program(id,vertexSource,fragmentSource){let p=programs.get(id);if(p)return p;p=manager.createProgram(id,{vertexSource,fragmentSource});programs.set(id,p);return p}
 function flatProgram(){return program('v2x13.program.flat',FLAT_VERTEX,FLAT_FRAGMENT)}
 function litProgram(fog){const P=O.renderPresentationShaders;if(!P||typeof P.variant!=='function')fail('DEPENDENCY','renderPresentationShaders required for lit frames');const v=P.variant({shadow:false,fog,alpha:'blend'});return program('v2x13.program.'+v.key,v.vertex,v.fragment)}
 function fxaaProgram(){const F=O.renderFXAA;if(!F||!F.VERTEX_GLSL||!F.FRAGMENT_GLSL)fail('DEPENDENCY','renderFXAA required for FXAA frames');return program('v2x13.program.fxaa',F.VERTEX_GLSL,F.FRAGMENT_GLSL)}
 function ensureTarget(width,height){const k=width+'x'+height;if(targetKey===k&&manager.handles(targetId))return manager.handles(targetId);if(manager.handles(targetId))manager.release(targetId);manager.createRenderTarget(targetId,{width,height,colorInternalFormat:gl.RGBA8,colorFormat:gl.RGBA,colorType:gl.UNSIGNED_BYTE,depth:true});targetKey=k;return manager.handles(targetId)}
 function primitiveEnum(name){const value=gl[name];if(!Number.isFinite(Number(value)))fail('WEBGL2','missing primitive '+name);return value}
 function releaseTransient(ids){for(let i=ids.length-1;i>=0;i--)try{manager.release(ids[i])}catch{}}
 function renderDraw(frame,draw,index){const prefix='v2x13.frame.'+frame.frameId+'.'+index,ids=[],mode=primitiveEnum(draw.primitive);let vao=null;try{
   vao=manager.createVertexArray(prefix+'.vao');ids.push(prefix+'.vao');gl.bindVertexArray(vao);
   const pos=manager.createBuffer(prefix+'.pos',gl.ARRAY_BUFFER,draw.positions,gl.STREAM_DRAW||gl.STATIC_DRAW);ids.push(prefix+'.pos');gl.bindBuffer(gl.ARRAY_BUFFER,pos);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);
   let p;if(draw.lit){const nor=manager.createBuffer(prefix+'.nor',gl.ARRAY_BUFFER,draw.normals,gl.STREAM_DRAW||gl.STATIC_DRAW);ids.push(prefix+'.nor');gl.bindBuffer(gl.ARRAY_BUFFER,nor);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);p=litProgram(frame.fog)}else p=flatProgram();
   gl.useProgram(p);setMatrix(p,'uViewProjection',frame.camera.viewProjection);
   if(draw.lit){setMatrix(p,'uModel',new Float32Array(IDENTITY));const m=draw.material;const uniforms=[['uBaseColor','3fv',m.baseColor],['uEmissive','3fv',m.emissive],['uRoughness','1f',m.roughness],['uMetallic','1f',m.metallic],['uOpacity','1f',m.opacity],['uLightDirection','3fv',frame.lighting.direction],['uLightColor','3fv',frame.lighting.color],['uLightIntensity','1f',frame.lighting.intensity],['uViewPosition','3fv',frame.camera.position],['uAmbient','1f',frame.lighting.ambient]];for(const [name,kind,value] of uniforms){const loc=essentialUniform(p,name);if(kind==='3fv')gl.uniform3fv(loc,value);else gl.uniform1f(loc,value)}}else{let loc=essentialUniform(p,'uColor');gl.uniform3fv(loc,draw.material.baseColor);loc=essentialUniform(p,'uOpacity');gl.uniform1f(loc,draw.material.opacity);loc=essentialUniform(p,'uPointSize');gl.uniform1f(loc,draw.material.pointSize)}
   if(draw.material.opacity<1&&gl.BLEND!=null){gl.enable(gl.BLEND);if(gl.blendFunc)gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA)}else if(gl.BLEND!=null)gl.disable(gl.BLEND);
   if(draw.indices){const ib=manager.createBuffer(prefix+'.idx',gl.ELEMENT_ARRAY_BUFFER,draw.indices,gl.STREAM_DRAW||gl.STATIC_DRAW);ids.push(prefix+'.idx');gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.drawElements(mode,draw.indices.length,gl.UNSIGNED_INT,0);return {drawCalls:1,vertices:draw.vertexCount,indices:draw.indices.length}}
   gl.drawArrays(mode,0,draw.vertexCount);return {drawCalls:1,vertices:draw.vertexCount,indices:0};
  }finally{if(gl.bindVertexArray)gl.bindVertexArray(null);releaseTransient(ids)}}
 function applyFXAA(frame,target){const F=O.renderFXAA;if(!F||typeof F.config!=='function')fail('DEPENDENCY','renderFXAA required for FXAA frames');const cfg=F.config(),p=fxaaProgram();gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,frame.viewport.width,frame.viewport.height);if(gl.DEPTH_TEST!=null)gl.disable(gl.DEPTH_TEST);gl.useProgram(p);if(gl.activeTexture)gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,target.texture);let loc=essentialUniform(p,'uColor');gl.uniform1i(loc,0);loc=essentialUniform(p,'uInvResolution');gl.uniform2f(loc,1/frame.viewport.width,1/frame.viewport.height);loc=essentialUniform(p,'uEdgeThreshold');gl.uniform1f(loc,cfg.edgeThreshold);loc=essentialUniform(p,'uSubpixel');gl.uniform1f(loc,cfg.subpixel);gl.drawArrays(gl.TRIANGLES,0,3);return 1}
 function render(raw,{replay=false}={}){
  if(disposed)fail('STATE','consumer disposed');if(!valid)fail('CONTEXT_LOST','frame consumer unavailable');const frame=normalizePacket(raw),fingerprint=packetFingerprint(frame);let target=null;if(frame.aaMode==='FXAA')target=ensureTarget(frame.viewport.width,frame.viewport.height);else if(frame.aaMode==='DEFAULT_MSAA'){const samples=gl.getParameter&&gl.SAMPLES!=null?Number(gl.getParameter(gl.SAMPLES)):0;if(!Number.isFinite(samples)||samples<2)fail('AA','default framebuffer multisampling unavailable');}
  gl.bindFramebuffer(gl.FRAMEBUFFER,target?target.framebuffer:null);gl.viewport(0,0,frame.viewport.width,frame.viewport.height);if(gl.DEPTH_TEST!=null){gl.enable(gl.DEPTH_TEST);if(gl.depthFunc&&gl.LEQUAL!=null)gl.depthFunc(gl.LEQUAL)}if(gl.clearDepth)gl.clearDepth(1);gl.clearColor(frame.clearColor[0],frame.clearColor[1],frame.clearColor[2],frame.clearColor[3]);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
  let drawCalls=0,vertices=0,indices=0;const domainCounts={};for(let i=0;i<frame.draws.length;i++){const d=frame.draws[i],r=renderDraw(frame,d,i);drawCalls+=r.drawCalls;vertices+=r.vertices;indices+=r.indices;domainCounts[d.domain]=(domainCounts[d.domain]||0)+1}if(frame.aaMode==='FXAA')drawCalls+=applyFXAA(frame,target);
  frameCount++;if(replay)replayCount++;totalDrawCalls+=drawCalls;totalVertices+=vertices;totalIndices+=indices;lastPacket=cloneNormalizedPacket(frame);lastWitness=Object.freeze({version:FRAME_VERSION,authority:AUTHORITY,backend:FRAME_BACKEND,pixelConsumer:'V2X-13',primaryRendererAuthority:false,canvas2dFallbackUsed:false,fallbackPath:'FORBIDDEN',cameraAuthority:'EXTERNAL_READ_ONLY',sceneCompositionAuthority:'EXTERNAL_READ_ONLY',semanticScaleAuthority:'EXTERNAL_READ_ONLY',frameId:frame.frameId,sceneId:frame.sceneId,selectionId:frame.selectionId,semanticSignature:frame.semanticSignature,packetFingerprint:fingerprint,aaMode:frame.aaMode,depthTest:true,lighting:frame.draws.some(d=>d.lit),atmospherePresentation:frame.fog&&frame.draws.some(d=>d.lit),drawCalls,geometryDrawCalls:frame.draws.length,vertices,indices,frameBytes:frame.frameBytes,domainCounts:Object.freeze({...domainCounts}),lodAuthority:'EXTERNAL_READ_ONLY',replay});return lastWitness
 }
 function replayLastFrame(){if(!lastPacket)fail('STATE','no retained frame');return render(lastPacket,{replay:true})}
 function contextLost(){if(disposed)return snapshot();manager.contextLost();programs=new Map();targetKey=null;valid=false;lostEvents++;return snapshot()}
 function contextRestored(nextGl=gl){if(disposed||valid||!nextGl)fail('STATE','invalid consumer restore');gl=nextGl;manager.contextRestored(nextGl);programs=new Map();targetKey=null;valid=true;restoredEvents++;return snapshot()}
 function snapshot(){return Object.freeze({version:FRAME_VERSION,authority:AUTHORITY,backend:FRAME_BACKEND,valid,disposed,frameCount,replayCount,totalDrawCalls,totalVertices,totalIndices,lastWitness,retainedFrameBytes:lastPacket?.frameBytes||0,maxRetainedBytes,maxFrameBytes,maxDraws,maxVertices,maxIndices,lostEvents,restoredEvents,canvas2dFallbackUsed:false,fallbackPath:'FORBIDDEN',primaryRendererAuthority:false,resourceManager:manager.snapshot()})}
 function dispose(){if(disposed)return snapshot();for(const [target,kind,listener] of listeners)try{target.removeEventListener(kind,listener)}catch{}listeners.length=0;manager.dispose();programs.clear();targetKey=null;lastPacket=null;valid=false;disposed=true;return snapshot()}
 if(canvas&&typeof canvas.addEventListener==='function'){const lost=e=>{e?.preventDefault?.();contextLost()},restored=()=>{if(!disposed&&!valid)contextRestored(gl)};canvas.addEventListener('webglcontextlost',lost);canvas.addEventListener('webglcontextrestored',restored);listeners.push([canvas,'webglcontextlost',lost],[canvas,'webglcontextrestored',restored])}
 return Object.freeze({VERSION:FRAME_VERSION,AUTHORITY,DOMAINS,render,replayLastFrame,contextLost,contextRestored,snapshot,dispose});
}
O.renderWebGL2Resources=Object.freeze({VERSION,AUTHORITY,FRAME_VERSION,FRAME_BACKEND,DOMAINS,createManager,createFrameConsumer});
})(typeof globalThis!=='undefined'?globalThis:this);
