(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-render-webgl2-resources-4';
const AUTHORITY='PRESENTATION_ONLY';
function fail(code,message){const e=new Error(message);e.code=code;throw e}
function key(v){const s=String(v||'');if(!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,159}$/.test(s))fail('ID','invalid resource id');return s}
function safeBytes(v,label='bytes'){v=Number(v);if(!Number.isSafeInteger(v)||v<0)fail('BUDGET','invalid '+label);return v}
function createManager(gl,{maxResources=512,maxTrackedBytes=134217728,maxTextureDimension=8192}={}){
 if(!gl)fail('WEBGL2','context required');
 if(!Number.isSafeInteger(maxResources)||maxResources<1||maxResources>4096)fail('BUDGET','resource limit');
 maxTrackedBytes=safeBytes(maxTrackedBytes,'maxTrackedBytes');if(maxTrackedBytes<1||maxTrackedBytes>1073741824)fail('BUDGET','tracked byte limit');
 if(!Number.isSafeInteger(maxTextureDimension)||maxTextureDimension<1||maxTextureDimension>32768)fail('BUDGET','texture dimension limit');
 let context=gl,generation=1,valid=true,disposed=false,trackedBytes=0,created=0,deleted=0,invalidated=0,failedCreates=0;
 const resources=new Map();
 function checkedAdd(a,b,label='bytes'){const n=a+b;if(!Number.isSafeInteger(n)||n<0)fail('BUDGET','overflow '+label);return n}
 function preflight(id,bytes){if(disposed||!valid)fail('CONTEXT_LOST','resource manager unavailable');if(resources.has(id))fail('COLLISION','duplicate resource '+id);if(resources.size>=maxResources)fail('BUDGET','resource count');if(checkedAdd(trackedBytes,bytes)>maxTrackedBytes)fail('BUDGET','tracked byte limit')}
 function own(id,kind,bytes,handles,destroy){resources.set(id,{id,kind,bytes,handles,destroy,generation});trackedBytes=checkedAdd(trackedBytes,bytes);created++;return handles.primary||handles}
 function guardedCreate(id,kind,bytes,build,destroy){id=key(id);bytes=safeBytes(bytes);preflight(id,bytes);let handles=null;try{handles=build();if(!handles)fail('ALLOCATE','empty '+kind);return own(id,kind,bytes,handles,()=>destroy(handles))}catch(e){failedCreates++;if(handles){try{destroy(handles)}catch{}}throw e}}
 function createBuffer(id,target,data,usage){if(!data||!Number.isSafeInteger(data.byteLength))fail('BUFFER','typed data required');return guardedCreate(id,'buffer',data.byteLength,()=>{let h=null;try{h=context.createBuffer();if(!h)fail('ALLOCATE','buffer');context.bindBuffer(target,h);context.bufferData(target,data,usage);return{primary:h}}catch(e){if(h)try{context.deleteBuffer(h)}catch{}throw e}},h=>context.deleteBuffer(h.primary))}
 function enumIs(value,name){const e=Number(context[name]);return Number.isFinite(e)&&value===e}
 function inferredTransferBytesPerPixel(format,type){const packed=[['UNSIGNED_SHORT_5_6_5',2],['UNSIGNED_SHORT_4_4_4_4',2],['UNSIGNED_SHORT_5_5_5_1',2],['UNSIGNED_INT_2_10_10_10_REV',4],['UNSIGNED_INT_10F_11F_11F_REV',4],['UNSIGNED_INT_5_9_9_9_REV',4],['UNSIGNED_INT_24_8',4],['FLOAT_32_UNSIGNED_INT_24_8_REV',8]];for(const [name,bytes] of packed)if(enumIs(type,name))return bytes;let channels=0;if(enumIs(format,'RED')||enumIs(format,'RED_INTEGER')||enumIs(format,'DEPTH_COMPONENT'))channels=1;else if(enumIs(format,'RG')||enumIs(format,'RG_INTEGER'))channels=2;else if(enumIs(format,'RGB')||enumIs(format,'RGB_INTEGER'))channels=3;else if(enumIs(format,'RGBA')||enumIs(format,'RGBA_INTEGER'))channels=4;else if(enumIs(format,'DEPTH_STENCIL'))channels=1;let scalar=0;if(enumIs(type,'BYTE')||enumIs(type,'UNSIGNED_BYTE'))scalar=1;else if(enumIs(type,'SHORT')||enumIs(type,'UNSIGNED_SHORT')||enumIs(type,'HALF_FLOAT'))scalar=2;else if(enumIs(type,'INT')||enumIs(type,'UNSIGNED_INT')||enumIs(type,'FLOAT'))scalar=4;return channels&&scalar?channels*scalar:null}
 function inferredStorageBytesPerPixel(internalFormat){const groups=[
  [1,['R8','R8_SNORM','R8UI','R8I']],
  [2,['R16F','R16UI','R16I','RG8','RG8_SNORM','RG8UI','RG8I','RGB565','RGBA4','RGB5_A1','DEPTH_COMPONENT16']],
  [3,['RGB8','SRGB8','RGB8_SNORM','RGB8UI','RGB8I']],
  [4,['R32F','R32UI','R32I','RG16F','RG16UI','RG16I','R11F_G11F_B10F','RGB9_E5','RGBA8','SRGB8_ALPHA8','RGBA8_SNORM','RGB10_A2','RGBA8UI','RGB10_A2UI','RGBA8I','DEPTH_COMPONENT24','DEPTH_COMPONENT32F','DEPTH24_STENCIL8']],
  [6,['RGB16F','RGB16UI','RGB16I']],
  [8,['RG32F','RG32UI','RG32I','RGBA16F','RGBA16UI','RGBA16I','DEPTH32F_STENCIL8']],
  [12,['RGB32F','RGB32UI','RGB32I']],
  [16,['RGBA32F','RGBA32UI','RGBA32I']]
 ];for(const [bytes,names] of groups)for(const name of names)if(enumIs(internalFormat,name))return bytes;return null}
 function resolveBytesPerPixel(internalFormat,format,type,declared){const transfer=inferredTransferBytesPerPixel(format,type),storage=inferredStorageBytesPerPixel(internalFormat),required=transfer==null?storage:storage==null?transfer:Math.max(transfer,storage);if(declared==null){if(required==null)fail('BUDGET','bytesPerPixel required for unrecognized texture format');return required}declared=safeBytes(declared,'bytesPerPixel');if(declared<1||declared>32)fail('BUDGET','bytesPerPixel range');if(required!=null&&declared<required)fail('BUDGET','bytesPerPixel understates texture storage');return declared}
 function textureBytes({width,height,bytesPerPixel,mipLevels=1}){width=safeBytes(width,'width');height=safeBytes(height,'height');bytesPerPixel=safeBytes(bytesPerPixel,'bytesPerPixel');mipLevels=safeBytes(mipLevels,'mipLevels');if(width<1||height<1||width>maxTextureDimension||height>maxTextureDimension||mipLevels<1||mipLevels>16||bytesPerPixel<1||bytesPerPixel>32)fail('BUDGET','texture shape');const maxMip=1+Math.floor(Math.log2(Math.max(width,height)));if(mipLevels>maxMip)fail('BUDGET','mip levels exceed texture chain');let total=0,w=width,h=height;for(let i=0;i<mipLevels;i++){const level=w*h*bytesPerPixel;if(!Number.isSafeInteger(level))fail('BUDGET','texture byte overflow');total=checkedAdd(total,level,'texture bytes');w=Math.max(1,w>>1);h=Math.max(1,h>>1)}return total}
 function createTexture2D(id,opt={}){const {width,height,internalFormat,format,type,data=null,bytesPerPixel=null,mipLevels=1,minFilter=context.LINEAR,magFilter=context.LINEAR,wrapS=context.CLAMP_TO_EDGE,wrapT=context.CLAMP_TO_EDGE}=opt,bpp=resolveBytesPerPixel(internalFormat,format,type,bytesPerPixel),bytes=textureBytes({width,height,bytesPerPixel:bpp,mipLevels});return guardedCreate(id,'texture',bytes,()=>{let h=null;try{h=context.createTexture();if(!h)fail('ALLOCATE','texture');context.bindTexture(context.TEXTURE_2D,h);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MIN_FILTER,minFilter);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MAG_FILTER,magFilter);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_S,wrapS);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_T,wrapT);if(mipLevels>1){if(!Number.isFinite(Number(context.TEXTURE_MAX_LEVEL)))fail('WEBGL2','TEXTURE_MAX_LEVEL required for bounded mip allocation');context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MAX_LEVEL,mipLevels-1)}context.texImage2D(context.TEXTURE_2D,0,internalFormat,width,height,0,format,type,data);if(mipLevels>1)context.generateMipmap(context.TEXTURE_2D);return{primary:h}}catch(e){if(h)try{context.deleteTexture(h)}catch{}throw e}},h=>context.deleteTexture(h.primary))}
 function compileShader(type,source){const s=context.createShader(type);if(!s)fail('ALLOCATE','shader');context.shaderSource(s,String(source));context.compileShader(s);if(!context.getShaderParameter(s,context.COMPILE_STATUS)){const log=String(context.getShaderInfoLog(s)||'shader compile failed').slice(0,2048);context.deleteShader(s);fail('SHADER_COMPILE',log)}return s}
 function createProgram(id,{vertexSource,fragmentSource}={}){id=key(id);preflight(id,0);let vs=null,fs=null,p=null;try{vs=compileShader(context.VERTEX_SHADER,vertexSource);fs=compileShader(context.FRAGMENT_SHADER,fragmentSource);p=context.createProgram();if(!p)fail('ALLOCATE','program');context.attachShader(p,vs);context.attachShader(p,fs);context.linkProgram(p);if(!context.getProgramParameter(p,context.LINK_STATUS))fail('PROGRAM_LINK',String(context.getProgramInfoLog(p)||'program link failed').slice(0,2048));context.deleteShader(vs);context.deleteShader(fs);vs=fs=null;return own(id,'program',0,{primary:p},()=>context.deleteProgram(p))}catch(e){failedCreates++;if(vs)try{context.deleteShader(vs)}catch{}if(fs)try{context.deleteShader(fs)}catch{}if(p)try{context.deleteProgram(p)}catch{}throw e}}
 function createVertexArray(id){return guardedCreate(id,'vao',0,()=>{const h=context.createVertexArray();if(!h)fail('ALLOCATE','vertex array');return{primary:h}},h=>context.deleteVertexArray(h.primary))}
 function createRenderTarget(id,{width,height,colorInternalFormat,colorFormat,colorType,bytesPerPixel=null,depth=true}={}){id=key(id);const bpp=resolveBytesPerPixel(colorInternalFormat,colorFormat,colorType,bytesPerPixel),colorBytes=textureBytes({width,height,bytesPerPixel:bpp,mipLevels:1}),depthBytes=depth?textureBytes({width,height,bytesPerPixel:4,mipLevels:1}):0,total=checkedAdd(colorBytes,depthBytes,'render target bytes');return guardedCreate(id,'render-target',total,()=>{let texture=null,framebuffer=null,renderbuffer=null;try{texture=context.createTexture();if(!texture)fail('ALLOCATE','render target texture');context.bindTexture(context.TEXTURE_2D,texture);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MIN_FILTER,context.LINEAR);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_MAG_FILTER,context.LINEAR);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_S,context.CLAMP_TO_EDGE);context.texParameteri(context.TEXTURE_2D,context.TEXTURE_WRAP_T,context.CLAMP_TO_EDGE);context.texImage2D(context.TEXTURE_2D,0,colorInternalFormat,width,height,0,colorFormat,colorType,null);framebuffer=context.createFramebuffer();if(!framebuffer)fail('ALLOCATE','framebuffer');context.bindFramebuffer(context.FRAMEBUFFER,framebuffer);context.framebufferTexture2D(context.FRAMEBUFFER,context.COLOR_ATTACHMENT0,context.TEXTURE_2D,texture,0);if(depth){renderbuffer=context.createRenderbuffer();if(!renderbuffer)fail('ALLOCATE','renderbuffer');context.bindRenderbuffer(context.RENDERBUFFER,renderbuffer);context.renderbufferStorage(context.RENDERBUFFER,context.DEPTH_COMPONENT24,width,height);context.framebufferRenderbuffer(context.FRAMEBUFFER,context.DEPTH_ATTACHMENT,context.RENDERBUFFER,renderbuffer)}const status=context.checkFramebufferStatus(context.FRAMEBUFFER);if(status!==context.FRAMEBUFFER_COMPLETE)fail('FRAMEBUFFER','incomplete '+status);return{primary:framebuffer,framebuffer,texture,renderbuffer}}catch(e){if(renderbuffer)try{context.deleteRenderbuffer(renderbuffer)}catch{}if(framebuffer)try{context.deleteFramebuffer(framebuffer)}catch{}if(texture)try{context.deleteTexture(texture)}catch{}throw e}},h=>{if(h.renderbuffer)context.deleteRenderbuffer(h.renderbuffer);context.deleteFramebuffer(h.framebuffer);context.deleteTexture(h.texture)})}
 function release(id){id=key(id);const r=resources.get(id);if(!r)return false;try{r.destroy()}catch(e){e.code=e.code||'DELETE_FAILED';throw e}resources.delete(id);trackedBytes-=r.bytes;deleted++;return true}
 function contextLost(){if(disposed)return snapshot();invalidated+=resources.size;resources.clear();trackedBytes=0;valid=false;return snapshot()}
 function contextRestored(next){if(disposed||valid||!next)fail('STATE','invalid restore');context=next;generation++;valid=true;return snapshot()}
 function dispose(){if(disposed)return snapshot();if(valid){for(const id of [...resources.keys()])release(id)}else resources.clear();disposed=true;valid=false;return snapshot()}
 function snapshot(){const byKind={};for(const r of resources.values())byKind[r.kind]=(byKind[r.kind]||0)+1;return Object.freeze({version:VERSION,authority:AUTHORITY,generation,valid,disposed,liveResources:resources.size,liveByKind:Object.freeze(byKind),trackedBytes,maxTrackedBytes,created,deleted,invalidated,failedCreates,accountingExact:created===deleted+invalidated+resources.size,physicalDriverVramBytes:'NOT_MEASURABLE_PORTABLY'})}
 return Object.freeze({createBuffer,createTexture2D,createProgram,createVertexArray,createRenderTarget,release,contextLost,contextRestored,dispose,snapshot});
}
O.renderWebGL2Resources=Object.freeze({VERSION,AUTHORITY,createManager});
})(typeof globalThis!=='undefined'?globalThis:this);
