(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-astronomy-model-1';
const SOURCE_BRANCH='parallel/wave-v-astronomy-depth-2026-09-05@a4feefde0fcc4df1b257b7126f95c4bbcaf779d3';
const AUTH=V.authority('v1.astronomy.population', '1.0.0',[SOURCE_BRANCH],'Approximate sparse population synthesis for product exploration; P3 canonical facts remain authoritative.',[
 'Galaxy and stellar population distributions are deliberately low-dimensional approximations.',
 'Model outputs are not catalog measurements and do not modify P3 canonical entities.'
]);
// Fixed quantile table derived once from the WV-A research distribution family. Storing the table avoids per-lookup 2048-bin recomputation.
const MASS_LOG10_CENTIDEX=Object.freeze([700,735,764,790,814,837,859,880,901,922,943,965,988,1012,1037,1063,1090,1118,1147,1177,1207,1236,1264,1290,1314,1336,1356,1374,1390,1404,1416,1426,1435]);
function quantile(table,qPpm){V.ppm(qPpm,'quantile');const x=qPpm*(table.length-1),i=Math.floor(x/1000000),r=x-i*1000000;if(i>=table.length-1)return table[table.length-1];return Math.round((table[i]*(1000000-r)+table[i+1]*r)/1000000)}
function hierarchy({universeId,galaxyCell,regionCell,systemAddress,stellarOrdinal=0}){
 V.text(universeId,'universeId',128);for(const [k,v] of Object.entries({galaxyCell,regionCell,systemAddress}))V.text(v,k,160);V.int(stellarOrdinal,'stellarOrdinal',0,31);
 const galaxyIdentity=V.deriveId('galaxy',universeId,galaxyCell),galacticRegionIdentity=V.deriveId('galactic-region',galaxyIdentity,regionCell),localPopulationContext=V.deriveId('local-population',galacticRegionIdentity,'stellar-population'),stellarSystemIdentity=V.deriveId('stellar-system',galacticRegionIdentity,systemAddress),stellarObjectIdentity=V.deriveId('stellar-object',stellarSystemIdentity,stellarOrdinal);
 return Object.freeze({universeId,galaxyIdentity,galacticRegionIdentity,localPopulationContext,stellarSystemIdentity,stellarObjectIdentity});
}
function galaxyProfile({galaxyIdentity,environmentPpm=500000}){
 V.text(galaxyIdentity,'galaxyIdentity',128);V.ppm(environmentPpm,'environmentPpm');const q=V.unitPpm(VERSION,galaxyIdentity,'mass'),mass=quantile(MASS_LOG10_CENTIDEX,q),env=environmentPpm;
 const sph=V.clamp(60000+Math.max(0,mass-950)*900+Math.floor((env-500000)/6),30000,820000),irr=V.clamp(260000-Math.max(0,mass-850)*700,20000,330000),roll=V.unitPpm(VERSION,galaxyIdentity,'morphology'),morphology=roll<sph?'SPHEROID':roll<sph+irr?'IRREGULAR':'DISK';
 const radiusMilliKpc=V.clamp(1800+(mass-900)*12+Math.floor(V.signedPpm(VERSION,galaxyIdentity,'size')/850),350,60000),ageMyr=V.clamp(1900+(mass-900)*18+Math.floor(env/180)+Math.floor(V.signedPpm(VERSION,galaxyIdentity,'age')/500),100,13700),metallicityMilliDex=V.clamp(-1550+(mass-850)*3-Math.floor((ageMyr-5000)/35)+Math.floor(V.signedPpm(VERSION,galaxyIdentity,'metallicity')/6000),-2800,650);
 return Object.freeze({galaxyIdentity,log10StellarMassCentidex:mass,morphology,radiusMilliKpc,meanAgeMyr:ageMyr,meanMetallicityMilliDex:metallicityMilliDex,environmentPpm,authority:AUTH,provenance:V.provenance('v1.astronomy.population','1.0.0',[SOURCE_BRANCH])});
}
function regionProfile({galaxy,galacticRegionIdentity,radialPpm=500000,heightPpm=0}){
 V.text(galacticRegionIdentity,'galacticRegionIdentity',128);V.ppm(radialPpm,'radialPpm');V.ppm(heightPpm,'heightPpm');const sph=galaxy.morphology==='SPHEROID',disk=V.clamp((sph?230000:850000)-Math.floor(radialPpm*.34)-Math.floor(heightPpm*.28),80000,900000),bulge=V.clamp((sph?660000:220000)-Math.floor(radialPpm*.18),20000,820000),halo=Math.max(10000,1000000-disk-bulge),sum=disk+bulge+halo;
 return Object.freeze({galacticRegionIdentity,parentGalaxyIdentity:galaxy.galaxyIdentity,componentWeightsPpm:Object.freeze({disk:Math.floor(disk*1000000/sum),bulge:Math.floor(bulge*1000000/sum),halo:1000000-Math.floor(disk*1000000/sum)-Math.floor(bulge*1000000/sum)}),ageMyr:V.clamp(galaxy.meanAgeMyr+Math.floor(heightPpm/250)+Math.floor(bulge/700)-Math.floor(disk/1400),50,13700),metallicityMilliDex:V.clamp(galaxy.meanMetallicityMilliDex-Math.floor(radialPpm/2500)-Math.floor(heightPpm/4200),-3000,700),authority:AUTH});
}
function stellarPrimary({stellarSystemIdentity,region}){
 V.text(stellarSystemIdentity,'stellarSystemIdentity',128);const u=V.unitPpm(VERSION,stellarSystemIdentity,'primary-mass');let massMilliSolar;if(u<730000)massMilliSolar=80+Math.floor(u*420/730000);else massMilliSolar=500+Math.floor((u-730000)*115000/270000);massMilliSolar=V.clamp(massMilliSolar,80,120000);
 const ageMyr=V.clamp(region.ageMyr+Math.floor(V.signedPpm(VERSION,stellarSystemIdentity,'age')/800),10,13700),metallicityMilliDex=V.clamp(region.metallicityMilliDex+Math.floor(V.signedPpm(VERSION,stellarSystemIdentity,'z')/7000),-3000,700);
 const temperatureK=V.clamp(2600+Math.floor(Math.sqrt(massMilliSolar/1000)*3300),2200,45000),radiusMilliSolar=V.clamp(Math.round(1000*Math.pow(massMilliSolar/1000,0.78)),80,30000),luminosityMilliSolar=V.clamp(Math.round(1000*Math.pow(massMilliSolar/1000,3.2)),1,1000000000);
 return Object.freeze({stellarSystemIdentity,massMilliSolar,ageMyr,metallicityMilliDex,temperatureK,radiusMilliSolar,luminosityMilliSolar,authority:AUTH});
}
function multiplicity({stellarSystemIdentity,primary}){const mass=primary.massMilliSolar,p=mass<500?240000:mass<1500?430000:mass<5000?610000:mass<16000?770000:890000,u=V.unitPpm(VERSION,stellarSystemIdentity,'multiplicity'),componentCount=u>=p?1:(u<p/5&&mass>1200?3:2),companions=[];for(let i=1;i<componentCount;i++)companions.push(Object.freeze({stellarObjectIdentity:V.deriveId('stellar-object',stellarSystemIdentity,i),massRatioPpm:100000+(V.unitPpm(VERSION,stellarSystemIdentity,'q',i)%900001),periodLogDaysMilli:500+(V.unitPpm(VERSION,stellarSystemIdentity,'period',i)%6001),eccentricityPpm:V.unitPpm(VERSION,stellarSystemIdentity,'ecc',i)%800001}));return Object.freeze({componentCount,companions:Object.freeze(companions),authority:AUTH});}
function systemBirthContext(input){const ids=hierarchy(input),galaxy=galaxyProfile({galaxyIdentity:ids.galaxyIdentity,environmentPpm:input.environmentPpm??500000}),region=regionProfile({galaxy,galacticRegionIdentity:ids.galacticRegionIdentity,radialPpm:input.radialPpm??500000,heightPpm:input.heightPpm??0}),primary=stellarPrimary({stellarSystemIdentity:ids.stellarSystemIdentity,region}),multiple=multiplicity({stellarSystemIdentity:ids.stellarSystemIdentity,primary}),dustMassMilliEarth=V.clamp(4000+Math.floor(primary.massMilliSolar*22)+Math.floor(V.signedPpm(VERSION,ids.stellarSystemIdentity,'disk-dust')/45),100,500000000);return Object.freeze({ids,galaxy,region,primary,multiplicity:multiple,diskPrior:Object.freeze({dustMassMilliEarth,environmentPerturbationPpm:V.clamp(Math.floor((input.environmentPpm??500000)*.72)+(V.unitPpm(VERSION,ids.stellarSystemIdentity,'disk-env')%180000),0,1000000),authority:'MODEL_DERIVED_SIMULATION',claim:'formation boundary prior, not a reconstructed observed protoplanetary disk'}),authority:AUTH});}
function discoverGalaxies({universeId,cellPrefix='0,0,0',cursor=0,limit=24}){V.text(universeId,'universeId',128);V.text(cellPrefix,'cellPrefix',128);V.int(cursor,'cursor',0,1000000000);V.int(limit,'limit',1,64);const rows=[];for(let i=0;i<limit;i++){const ordinal=cursor+i,galaxyCell=cellPrefix+':'+ordinal,galaxyIdentity=V.deriveId('galaxy',universeId,galaxyCell),environmentPpm=V.unitPpm(VERSION,universeId,galaxyCell,'environment');rows.push(Object.freeze({ordinal,galaxyCell,...galaxyProfile({galaxyIdentity,environmentPpm})}));}return Object.freeze({scope:'SPARSE_ADDRESSABLE_GALAXY_FIELD',cursor,nextCursor:cursor+limit,materialized:rows.length,maxMaterialized:64,galaxies:Object.freeze(rows),authority:AUTH});}
O.v1Astronomy=Object.freeze({VERSION,AUTHORITY:AUTH,MASS_LOG10_CENTIDEX,hierarchy,galaxyProfile,regionProfile,stellarPrimary,multiplicity,systemBirthContext,discoverGalaxies});
})(globalThis);
