(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.pxContracts,P=O.pxProduct,V=O.v1Common,W=O.v1World,A=O.v1Astronomy;
if(!C||!P||!V||!W||!A)throw new Error('v1 provider prerequisites missing');
const VERSION='ofu-v1-provider-bindings-1',registry=P.registry,cache=new Map(),metrics={worldBuilds:0,worldCacheHits:0,invocations:0,discoveredGalaxies:0};
const safe=value=>C.data(JSON.parse(JSON.stringify(value,(_k,v)=>typeof v==='bigint'?String(v):v instanceof Uint8Array?O.p2.hex(v):v)),{bytes:1048576,nodes:32768});
function keyFromSelection(selection){const out={};for(const part of selection.target.address){const pos=part.indexOf('=');C.assert(pos>0,'IDENTITY','v1 canonical address');const k=part.slice(0,pos),v=part.slice(pos+1);C.assert(/^-?\d{1,20}$/.test(v),'IDENTITY','v1 canonical integer');out[k]=BigInt(v);}for(const k of ['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot'])C.assert(Object.hasOwn(out,k),'IDENTITY','v1 missing '+k);return out;}
function verifySelection(selection){const actual=P.captured(keyFromSelection(selection));C.assert(C.stable(actual.selection)===C.stable(selection),'IDENTITY','v1 request changed canonical selection/time');return actual;}
function worldFor(selection){const actual=verifySelection(selection),cacheKey=actual.selection.target.entityId+':'+actual.selection.time.historyDigest;if(cache.has(cacheKey)){metrics.worldCacheHits++;return cache.get(cacheKey);}const key=keyFromSelection(selection),raw=O.p3Astronomy.planetaryInputSnapshot(root.__OFU_PLANET_PREVIEW__.ctx,key),canonicalInput=safe(raw),world=W.build({universeId:selection.target.universeId,planetIdentity:selection.target.entityId,galaxyAddress:[key.galaxyX,key.galaxyY,key.galaxyZ].join(','),systemAddress:[key.sectorX,key.sectorY,key.sectorZ,key.siteX,key.siteY,key.siteZ].join(','),canonicalInput});metrics.worldBuilds++;if(cache.size===16)cache.delete(cache.keys().next().value);cache.set(cacheKey,world);return world;}
function bind(id,fn){const d=registry.descriptor(id);registry.bind(id,'v1','1.0.0',{handle(q,m){metrics.invocations++;verifySelection(q.selection);let operations=0,entities=0;const meter={consume(n=1,count=0){m.consume(n,count);operations+=n;entities+=count;}};const value=safe(fn(q,meter));meter.consume(1,Array.isArray(value?.galaxies)?value.galaxies.length:1);const bytes=Math.max(1,new TextEncoder().encode(C.stable(value)).length);return{contract:C.VERSION,provider:id,version:d.version,authority:d.authority,selection:q.selection,fidelity:d.fidelity,usage:{entities,bytes,operations,queue:0},value};}});}
bind('v1.domain.modeled-world',q=>{const w=worldFor(q.selection);return{version:w.version,planetIdentity:w.planetIdentity,canonicalInputDigest:w.canonicalInputDigest,biologyState:w.biology.occupancy.state,civilizationState:w.civilization.state,microscopicAvailable:!!w.microscopic,authority:'MODEL_DERIVED_SIMULATION',canonicalPromotion:false};});
bind('v1.model.astronomy',q=>worldFor(q.selection).astronomy);
bind('v1.query.galaxies',(q,meter)=>{const query=C.discovery(q.payload),cursor=query.cursor===null?0:Number(query.cursor);C.assert(Number.isSafeInteger(cursor)&&cursor>=0,'QUERY','v1 galaxy cursor');C.assert(query.limit<=q.budget.entities,'BUDGET','v1 galaxy limit');meter.consume(1);const cellPrefix=query.address.length?query.address.join('/'):'origin',value=A.discoverGalaxies({universeId:q.selection.target.universeId,cellPrefix,cursor,limit:Math.min(query.limit,64)});metrics.discoveredGalaxies+=value.galaxies.length;return value;});
bind('v1.model.planetology',q=>worldFor(q.selection).planetology);
bind('v1.model.biology',q=>worldFor(q.selection).biology);
bind('v1.model.civilization',q=>worldFor(q.selection).civilization);
bind('v1.model.microscopic',q=>{const w=worldFor(q.selection);return w.microscopic?{supported:true,...w.microscopic}:{supported:false,reason:'NO_MODELED_BIOSPHERE_CONTEXT',authority:'MODEL_DERIVED_SIMULATION'};});
bind('v1.inspector.world',q=>{const w=worldFor(q.selection),p=w.planetology,b=w.biology,c=w.civilization;return{title:'Modeled world',summary:b.occupancy.biosphereEstablished?'This scenario supports a modeled biosphere.':'This scenario is sterile under the current modeled prerequisites/occupancy.',fields:[{name:'Planet class',value:p.bulkPriorClass,unit:''},{name:'Modeled surface temperature',value:p.climate.surfaceTemperatureMilliK,unit:'mK'},{name:'Modeled water area',value:p.hydrosphere.waterAreaPpm,unit:'ppm'},{name:'Biology',value:b.occupancy.state,unit:''},{name:'Civilization',value:c.state,unit:''},{name:'Microscopic descent',value:w.microscopic?'AVAILABLE':'UNAVAILABLE',unit:''}],authority:'MODEL_DERIVED_SIMULATION',canonicalBiologyUnchanged:true,canonicalPromotion:false};});
function snapshot(){return C.data({version:VERSION,cacheEntries:cache.size,cacheLimit:16,metrics,providers:['v1.domain.modeled-world','v1.model.astronomy','v1.query.galaxies','v1.model.planetology','v1.model.biology','v1.model.civilization','v1.model.microscopic','v1.inspector.world']});}
O.v1Providers=Object.freeze({VERSION,worldFor,snapshot});
})(globalThis);
