(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-biology-evolution-model-1';
const SOURCE_BRANCH='research/wave-v-biology-evolution-2026-09-05@ccc1f91d5c6cd26e7b89b74433e4712755073e5a';
const AUTH=V.authority('v1.biology.ecosystem','1.0.0',[SOURCE_BRANCH],'Bounded post-genesis ecosystem/evolution scenario model that is explicitly separate from canonical P6 biology.',[
 'No universal alien biochemistry or abiogenesis probability is asserted.',
 'Redox is treated as one possible free-energy pathway rather than a universal eligibility gate.'
]);
const ROLES=Object.freeze(['PRIMARY_PRODUCER','CHEMOTROPH','CONSUMER','DECOMPOSER','MUTUALIST','PARASITE']);
function environmentEligibility({mediumAvailable,freeEnergyAvailabilityPpm,nutrientAvailabilityPpm,temperatureCompatibilityPpm,energyPathways=[]}){V.assert(typeof mediumAvailable==='boolean','mediumAvailable');V.ppm(freeEnergyAvailabilityPpm,'freeEnergyAvailabilityPpm');V.ppm(nutrientAvailabilityPpm,'nutrientAvailabilityPpm');V.ppm(temperatureCompatibilityPpm,'temperatureCompatibilityPpm');V.boundedArray(energyPathways,16,'energyPathways');const freeEnergy=freeEnergyAvailabilityPpm>=180000,nutrients=nutrientAvailabilityPpm>=120000,temp=temperatureCompatibilityPpm>=180000,eligible=mediumAvailable&&freeEnergy&&nutrients&&temp;return Object.freeze({eligible,missing:Object.freeze([!mediumAvailable&&'VIABLE_MEDIUM',!freeEnergy&&'THERMODYNAMIC_FREE_ENERGY_AVAILABILITY',!nutrients&&'NUTRIENT_AVAILABILITY',!temp&&'TEMPERATURE_COMPATIBILITY'].filter(Boolean)),energyPathways:Object.freeze([...energyPathways]),redoxRequired:false,redoxMayBeOnePathway:energyPathways.includes('REDOX_GRADIENT'),canonicalP6Authority:false,authority:AUTH});}
function scenarioOccupancy({worldIdentity,eligibility,occupancyParameterPpm=420000}){V.text(worldIdentity,'worldIdentity',128);V.ppm(occupancyParameterPpm,'occupancyParameterPpm');if(!eligibility.eligible)return Object.freeze({state:'STERILE_MODEL_OUTCOME',biosphereEstablished:false,reason:'ENVIRONMENT_NOT_ELIGIBLE',authority:AUTH});const selector=V.unitPpm(VERSION,worldIdentity,'biosphere-scenario-occupancy'),established=selector<occupancyParameterPpm;return Object.freeze({state:established?'MODELED_BIOSPHERE':'STERILE_MODEL_OUTCOME',biosphereEstablished:established,selectorPpm:selector,occupancyParameterPpm,claim:'scenario occupancy parameter, not an abiogenesis probability',authority:AUTH});}
function initialEcosystem({worldIdentity,eligibility,occupancy,energyBudgetUnits=1000000,populationCount=18}){V.text(worldIdentity,'worldIdentity',128);V.int(energyBudgetUnits,'energyBudgetUnits',1,1000000000);V.int(populationCount,'populationCount',1,64);if(!eligibility.eligible||!occupancy.biosphereEstablished)return Object.freeze({worldIdentity,state:'STERILE',populations:Object.freeze([]),interactions:Object.freeze([]),generation:0,authority:AUTH});const weights=Array.from({length:populationCount},(_,i)=>100+V.unitPpm(VERSION,worldIdentity,'population-weight',i)%900),alloc=V.partition(energyBudgetUnits,weights),populations=[];for(let i=0;i<populationCount;i++){const role=ROLES[V.u32(VERSION,worldIdentity,'role',i)%ROLES.length],lineageId=V.deriveId('lineage',worldIdentity,i),populationId=V.deriveId('population',lineageId,'founder');populations.push(Object.freeze({populationId,lineageId,role,individuals:100+(V.u32(VERSION,populationId,'individuals')%9000),energyUnits:alloc[i],traitPpm:V.unitPpm(VERSION,populationId,'trait'),nichePpm:V.unitPpm(VERSION,populationId,'niche'),generationBorn:0,status:'ACTIVE'}));}const interactions=[];for(let i=0;i<populations.length;i++){const degree=1+(V.u32(VERSION,worldIdentity,'degree',i)%3);for(let j=0;j<degree&&interactions.length<192;j++){const to=(i+1+(V.u32(VERSION,worldIdentity,'edge',i,j)%(populations.length-1)))%populations.length,kind=['TROPHIC','COMPETITION','MUTUALISM','FACILITATION','PARASITISM'][V.u32(VERSION,worldIdentity,'edge-kind',i,j)%5];interactions.push(Object.freeze({interactionId:V.deriveId('ecological-edge',populations[i].populationId,populations[to].populationId,kind),fromPopulationId:populations[i].populationId,toPopulationId:populations[to].populationId,type:kind,strengthPpm:80000+(V.unitPpm(VERSION,worldIdentity,'edge-strength',i,j)%520000)}));}}
 return Object.freeze({worldIdentity,state:'MODELED_BIOSPHERE',generation:0,populations:Object.freeze(populations),interactions:Object.freeze(interactions),energyBudgetUnits,successionStage:'PIONEER',authority:AUTH,provenance:V.provenance('v1.biology.ecosystem','1.0.0',[SOURCE_BRANCH])});}
function evolve(state,{generationStep=1,environmentShiftPpm=0,migrationPpm=30000,mutationPpm=12000,selectionPpm=120000,driftPpm=35000}={}){for(const [k,v] of Object.entries({generationStep,migrationPpm,mutationPpm,selectionPpm,driftPpm}))V.int(v,k,k==='generationStep'?1:0,k==='generationStep'?1000:1000000);V.int(environmentShiftPpm,'environmentShiftPpm',-1000000,1000000);if(state.state!=='MODELED_BIOSPHERE')return state;const generation=state.generation+generationStep,next=[];for(const p of state.populations){if(p.status!=='ACTIVE')continue;const fit=1000000-Math.min(1000000,Math.abs(p.nichePpm-(500000+Math.floor(environmentShiftPpm/2)))),selectionDelta=Math.floor((fit-500000)*selectionPpm/500000000),drift=Math.floor(V.signedPpm(VERSION,p.populationId,generation,'drift')*driftPpm/1000000),migration=Math.floor(V.signedPpm(VERSION,p.populationId,generation,'migration')*migrationPpm/1000000),growth=V.clamp(1000000+selectionDelta+Math.floor(drift/20)+Math.floor(migration/30),600000,1400000),individuals=Math.floor(p.individuals*growth/1000000);if(individuals<8)continue;const trait=V.clamp(p.traitPpm+Math.floor(V.signedPpm(VERSION,p.populationId,generation,'mutation')*mutationPpm/1000000)+Math.floor(selectionDelta/2),0,1000000);next.push(Object.freeze({...p,individuals,traitPpm:trait,energyUnits:Math.max(1,Math.floor(p.energyUnits*growth/1000000))}));if(next.length<96&&individuals>2200&&Math.abs(trait-p.traitPpm)>Math.max(3500,mutationPpm/3)&&V.unitPpm(VERSION,p.populationId,generation,'split')<90000){const childLineage=V.deriveId('lineage',p.lineageId,generation,trait),childPop=V.deriveId('population',childLineage,generation);const childCount=Math.max(50,Math.floor(individuals*.12));next.push(Object.freeze({...p,populationId:childPop,lineageId:childLineage,individuals:childCount,traitPpm:V.clamp(trait+Math.floor(V.signedPpm(VERSION,childLineage,'trait')/40),0,1000000),generationBorn:generation,status:'ACTIVE',parentLineageId:p.lineageId}));}}
 const succession=generation<20?'PIONEER':generation<120?'ESTABLISHING':generation<500?'MATURE':'DYNAMIC_MOSAIC';return Object.freeze({...state,generation,populations:Object.freeze(next.slice(0,96)),successionStage:succession,extinctions:Math.max(0,state.populations.filter(p=>p.status==='ACTIVE').length-next.length),authority:AUTH});}
function biogeographicRefine(state,{regionIdentity,capacity=24}){V.text(regionIdentity,'regionIdentity',128);V.int(capacity,'capacity',1,64);if(state.state!=='MODELED_BIOSPHERE')return Object.freeze({regionIdentity,populations:Object.freeze([]),authority:AUTH});const ranked=state.populations.map(p=>({p,score:V.u32(VERSION,regionIdentity,p.populationId,'presence')})).sort((a,b)=>a.score-b.score||a.p.populationId.localeCompare(b.p.populationId)).slice(0,capacity).map(x=>Object.freeze({...x.p,regionalAbundancePpm:50000+(V.unitPpm(VERSION,regionIdentity,x.p.populationId,'abundance')%900001)}));return Object.freeze({regionIdentity,parentWorldIdentity:state.worldIdentity,populations:Object.freeze(ranked),inheritedGeneration:state.generation,authority:AUTH});}
O.v1Biology=Object.freeze({VERSION,AUTHORITY:AUTH,ROLES,environmentEligibility,scenarioOccupancy,initialEcosystem,evolve,biogeographicRefine});
})(globalThis);
