(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-civilization-history-model-1';
const SOURCE_BRANCH='research/wave-v-civilization-history-2026-09-05@082d8c558ad56c36a894a4ca381d01b10c5697d4';
const AUTH=V.authority('v1.civilization.history','1.0.0',[SOURCE_BRANCH],'Bounded causal generative civilization/history scenario model for explicitly eligible modeled intelligent populations.',[
 'Social mechanisms are scenario abstractions, not universal sociological laws.',
 'Culture and language state represents synthetic convention transmission, not predicted grammar or belief.'
]);
const EVENT_TYPES=Object.freeze(['FOUNDING','MIGRATION','TECH_TRANSITION','RESOURCE_CRISIS','INFRASTRUCTURE_BUILT','CONFLICT','SETTLEMENT_DESTROYED','ABANDONMENT','EXPANSION','INSTITUTION_TRANSITION','ECOLOGICAL_PRESSURE','COLLAPSE','RECOVERY','TRADE_EXPANSION']);
function eligibility({lineageId,intelligenceModelEligible,population,energySurplusPpm=0,environmentStabilityPpm=0}){V.text(lineageId,'lineageId',128);V.assert(typeof intelligenceModelEligible==='boolean','intelligenceModelEligible');V.int(population,'population',0,1000000000);V.ppm(energySurplusPpm,'energySurplusPpm');V.ppm(environmentStabilityPpm,'environmentStabilityPpm');const eligible=intelligenceModelEligible&&population>=800&&energySurplusPpm>=120000;return Object.freeze({eligible,lineageId,missing:Object.freeze([!intelligenceModelEligible&&'INTELLIGENCE_MODEL_ELIGIBILITY',population<800&&'POPULATION_FLOOR',energySurplusPpm<120000&&'ENERGY_SURPLUS'].filter(Boolean)),environmentStabilityPpm,authority:AUTH});}
function initialState({worldIdentity,lineageId,population,eligibility:gate,resourceUnits=1000000}){V.text(worldIdentity,'worldIdentity',128);V.text(lineageId,'lineageId',128);V.int(population,'population',1,1000000000);V.int(resourceUnits,'resourceUnits',1,1000000000);if(!gate.eligible)return Object.freeze({worldIdentity,lineageId,state:'NO_CIVILIZATION_MODEL',population:0,settlements:Object.freeze([]),events:Object.freeze([]),authority:AUTH});const count=V.clamp(2+(V.u32(VERSION,worldIdentity,lineageId,'settlements')%7),2,8),pops=V.partition(population,Array.from({length:count},(_,i)=>500+V.unitPpm(VERSION,worldIdentity,'settlement-weight',i)%1500)),stocks=V.partition(resourceUnits,Array.from({length:count},(_,i)=>300+V.unitPpm(VERSION,worldIdentity,'stock-weight',i)%1700)),settlements=pops.map((p,i)=>Object.freeze({settlementId:V.deriveId('settlement',worldIdentity,lineageId,i),population:p,stockUnits:stocks[i],infrastructurePpm:90000+(V.unitPpm(VERSION,worldIdentity,'infra',i)%280000),suitabilityPpm:250000+(V.unitPpm(VERSION,worldIdentity,'suitability',i)%650001),status:'ACTIVE'}));const institutions=Object.freeze({coordinationPpm:250000+(V.unitPpm(VERSION,lineageId,'coordination')%500001),legitimacyPpm:250000+(V.unitPpm(VERSION,lineageId,'legitimacy')%500001),centralizationPpm:V.unitPpm(VERSION,lineageId,'centralization'),factionCount:2+(V.u32(VERSION,lineageId,'factions')%5)}),technology=Object.freeze({subsistence:1,transport:0,materials:0,energy:0,information:0,medicine:0});return Object.freeze({worldIdentity,lineageId,state:'MODELED_CIVILIZATION',epoch:0,population,resourceUnits,settlements:Object.freeze(settlements),institutions,technology,tradeEdges:Object.freeze([]),events:Object.freeze([]),culture:Object.freeze({conventionGroups:2+(V.u32(VERSION,lineageId,'conventions')%5),divergencePpm:V.unitPpm(VERSION,lineageId,'culture-divergence'),claim:'synthetic convention identity; not language prediction'}),authority:AUTH,provenance:V.provenance('v1.civilization.history','1.0.0',[SOURCE_BRANCH])});}
function eventProposal(state,type,targetId,epoch,payload={},causes=[]){V.assert(EVENT_TYPES.includes(type),'event type');V.text(targetId,'targetId',128);V.int(epoch,'epoch',0,Number.MAX_SAFE_INTEGER);V.boundedArray(causes,16,'causes');const body={contract:'ofu-v1-domain-event-proposal-1',model:VERSION,authority:'MODEL_DERIVED_SIMULATION',worldIdentity:state.worldIdentity,lineageId:state.lineageId,epoch,type,targetId,payload,causes:[...causes].sort(),requiresP4Admission:true};return Object.freeze({...body,eventProposalId:V.digest('OFU-V1-CIV-EVENT',body)});}
function step(state,{epochStep=1,climatePressurePpm=0,externalTradePpm=250000}={}){if(state.state!=='MODELED_CIVILIZATION')return state;V.int(epochStep,'epochStep',1,10000);V.ppm(climatePressurePpm,'climatePressurePpm');V.ppm(externalTradePpm,'externalTradePpm');const epoch=state.epoch+epochStep,settlements=[],events=[...state.events],technology={...state.technology};let total=0;for(const s of state.settlements){if(s.status!=='ACTIVE'){settlements.push(s);continue;}const resourcePressure=V.clamp(1000000-Math.floor(s.stockUnits*1000000/Math.max(1,state.resourceUnits)),0,1000000),growthPpm=V.clamp(1000000+90000-Math.floor(climatePressurePpm*.11)-Math.floor(resourcePressure*.09)+Math.floor(V.signedPpm(VERSION,s.settlementId,epoch,'growth')/30),780000,1180000),population=Math.floor(s.population*growthPpm/1000000),production=Math.floor((s.infrastructurePpm+s.suitabilityPpm)*Math.max(1,population)/1800000),consumption=Math.max(1,population),stockUnits=Math.max(0,s.stockUnits+production-consumption),infrastructurePpm=V.clamp(s.infrastructurePpm+(stockUnits>consumption*2?12000:-5000),0,1000000),nextStatus=population<25?'ABANDONED':'ACTIVE',next=Object.freeze({...s,population,stockUnits,infrastructurePpm,status:nextStatus});settlements.push(next);total+=population;if(nextStatus!==s.status&&events.length<V.MAX.events)events.push(eventProposal(state,'ABANDONMENT',s.settlementId,epoch,{population},events.slice(-1).map(e=>e.eventProposalId)));if(infrastructurePpm>s.infrastructurePpm+8000&&events.length<V.MAX.events)events.push(eventProposal(state,'INFRASTRUCTURE_BUILT',s.settlementId,epoch,{infrastructurePpm},[]));}
 const innovation=V.unitPpm(VERSION,state.lineageId,epoch,'innovation');for(const key of ['transport','materials','energy','information','medicine'])if(innovation>850000&&technology[key]<8){technology[key]++;if(events.length<V.MAX.events)events.push(eventProposal(state,'TECH_TRANSITION',state.lineageId,epoch,{capability:key,level:technology[key]},[]));break;}
 const active=settlements.filter(s=>s.status==='ACTIVE'),tradeEdges=[];for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length&&tradeEdges.length<64;j++){const affinity=V.unitPpm(VERSION,active[i].settlementId,active[j].settlementId,epoch,'trade');if(affinity<externalTradePpm)tradeEdges.push(Object.freeze({edgeId:V.deriveId('trade',active[i].settlementId,active[j].settlementId),from:active[i].settlementId,to:active[j].settlementId,flowUnits:1+Math.floor(Math.min(active[i].stockUnits,active[j].stockUnits)*affinity/10000000)}));}
 const institutions=Object.freeze({...state.institutions,legitimacyPpm:V.clamp(state.institutions.legitimacyPpm-Math.floor(climatePressurePpm*.025)+Math.floor(V.signedPpm(VERSION,state.lineageId,epoch,'legitimacy')/80),0,1000000),coordinationPpm:V.clamp(state.institutions.coordinationPpm+technology.information*1500-Math.floor(climatePressurePpm*.012),0,1000000)});if(institutions.legitimacyPpm<110000&&events.length<V.MAX.events)events.push(eventProposal(state,'INSTITUTION_TRANSITION',state.lineageId,epoch,{legitimacyPpm:institutions.legitimacyPpm},[]));return Object.freeze({...state,epoch,population:total,settlements:Object.freeze(settlements),institutions,technology:Object.freeze(technology),tradeEdges:Object.freeze(tradeEdges),events:Object.freeze(events.slice(-V.MAX.events)),authority:AUTH});}
function archaeology(state,settlementId){V.text(settlementId,'settlementId',128);const causal=state.events.filter(e=>e.targetId===settlementId&&['ABANDONMENT','SETTLEMENT_DESTROYED','INFRASTRUCTURE_BUILT','CONFLICT','RESOURCE_CRISIS','COLLAPSE'].includes(e.type)),features=causal.map(e=>Object.freeze({featureId:V.deriveId('archaeology',settlementId,e.eventProposalId),sourceEventId:e.eventProposalId,kind:e.type==='ABANDONMENT'?'RUIN':e.type==='SETTLEMENT_DESTROYED'?'DESTRUCTION_LAYER':e.type==='INFRASTRUCTURE_BUILT'?'STRUCTURAL_REMAINS':e.type==='RESOURCE_CRISIS'?'PRODUCTION_DEBRIS':'HISTORICAL_REMAINS'}));return Object.freeze({settlementId,status:features.length?'CAUSALLY_DERIVED':'NO_CAUSAL_ARCHAEOLOGY',features:Object.freeze(features),authority:AUTH});}
O.v1Civilization=Object.freeze({VERSION,AUTHORITY:AUTH,EVENT_TYPES,eligibility,initialState,eventProposal,step,archaeology});
})(globalThis);
