(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-microscopic-regimes-1';
const SOURCE_BRANCH='research/wave-v-microscopic-matter-2026-09-05@6aeecf2ccc564d7f0f316711d07710e74e667e27';
const AUTH=V.authority('v1.micro.regimes','1.0.0',[SOURCE_BRANCH],'Bounded regime transitions from biological context to representational material/molecular/atomic detail.',[
 'No molecular dynamics or quantum simulation is performed.',
 'Synthetic atomic coordinates never inherit source-backed visual authority.'
]);
const REGIMES=Object.freeze({
 tissue:Object.freeze({id:'tissue',scale:'MODEL_REGIME',purpose:'bounded tissue agent/field representation',maxNodes:256,authority:'MODEL_DERIVED_SIMULATION'}),
 cell:Object.freeze({id:'cell',scale:'MODEL_REGIME',purpose:'single-cell compartment and transport representation',maxNodes:192,authority:'MODEL_DERIVED_SIMULATION'}),
 molecular:Object.freeze({id:'molecular',scale:'MODEL_REGIME',purpose:'coarse molecular composition/structure representation',maxNodes:256,authority:'MODEL_DERIVED_SIMULATION'}),
 atomic:Object.freeze({id:'atomic',scale:'MODEL_REGIME',purpose:'source-backed or explicit synthetic atomic representation',maxNodes:512,authority:'PRESENTATION_ONLY'})
});
function representationId(entityId,regime,localAddress='root',epoch='0'){V.text(entityId,'entityId',128);V.text(regime,'regime',48);V.text(localAddress,'localAddress',128);V.text(String(epoch),'epoch',64);return V.deriveId('micro-representation',entityId,regime,localAddress,String(epoch));}
function tissue({organismIdentity,cellCount=64,fieldUnits=100000}){V.text(organismIdentity,'organismIdentity',128);V.int(cellCount,'cellCount',1,REGIMES.tissue.maxNodes);V.int(fieldUnits,'fieldUnits',1,1000000000);const weights=Array.from({length:cellCount},(_,i)=>100+V.unitPpm(VERSION,organismIdentity,'cell-weight',i)%900),parts=V.partition(fieldUnits,weights),cells=parts.map((units,i)=>Object.freeze({cellIdentity:V.deriveId('cell',organismIdentity,i),ordinal:i,storeUnits:units,phenotypePpm:V.unitPpm(VERSION,organismIdentity,'phenotype',i)}));return Object.freeze({regime:'tissue',representationId:representationId(organismIdentity,'tissue'),organismIdentity,fieldUnits,cells:Object.freeze(cells),massCommitmentUnits:fieldUnits,authority:AUTH});}
function cell(tissueState,ordinal=0){V.int(ordinal,'ordinal',0,tissueState.cells.length-1);const c=tissueState.cells[ordinal],fractions=[300000,180000,120000,400000],parts=V.partition(c.storeUnits,fractions),compartments=['CYTOSOL','MEMBRANE','GENETIC_COMPARTMENT','ORGANELLE_POOL'].map((name,i)=>Object.freeze({name,materialUnits:parts[i]}));return Object.freeze({regime:'cell',representationId:representationId(c.cellIdentity,'cell'),cellIdentity:c.cellIdentity,parentRepresentationId:tissueState.representationId,parentTissueMaterialUnits:tissueState.massCommitmentUnits,materialUnits:c.storeUnits,compartments:Object.freeze(compartments),transport:Object.freeze({kind:'BOUNDED_DIFFUSION_FIELD_APPROXIMATION',dynamicalAuthority:'MODEL_DERIVED_SIMULATION'}),authority:AUTH});}
function molecular(cellState,{complexCount=12}={}){V.int(complexCount,'complexCount',1,64);const weights=Array.from({length:complexCount},(_,i)=>50+V.unitPpm(VERSION,cellState.cellIdentity,'complex',i)%950),parts=V.partition(cellState.materialUnits,weights),complexes=parts.map((units,i)=>Object.freeze({complexIdentity:V.deriveId('molecular-complex',cellState.cellIdentity,i),ordinal:i,compositionUnits:units,shapeClass:['GLOBULAR','FILAMENT','MEMBRANE_ASSOCIATED','POLYMER_COARSE'][V.u32(VERSION,cellState.cellIdentity,'shape',i)%4],coordinatesAuthoritative:false}));return Object.freeze({regime:'molecular',representationId:representationId(cellState.cellIdentity,'molecular'),parentRepresentationId:cellState.representationId,materialUnits:cellState.materialUnits,complexes:Object.freeze(complexes),dynamics:'NOT_SIMULATED',authority:AUTH});}
function atomic(molecularState,{complexOrdinal=0,sourceRecord=null,maxAtoms=128}={}){V.int(complexOrdinal,'complexOrdinal',0,molecularState.complexes.length-1);V.int(maxAtoms,'maxAtoms',1,REGIMES.atomic.maxNodes);const complex=molecularState.complexes[complexOrdinal],sourceBacked=!!(sourceRecord&&typeof sourceRecord==='object'&&typeof sourceRecord.sourceId==='string'&&Array.isArray(sourceRecord.atoms)),atoms=[];if(sourceBacked){for(const a of sourceRecord.atoms.slice(0,maxAtoms)){V.assert(a&&typeof a.element==='string'&&Array.isArray(a.position)&&a.position.length===3,'source atom');atoms.push(Object.freeze({element:a.element,position:Object.freeze(a.position.map(Number)),coordinateAuthority:'SOURCE_BACKED_ATOMIC'}));}}else{const count=Math.min(maxAtoms,6+V.u32(VERSION,complex.complexIdentity,'atom-count')%Math.min(96,maxAtoms));for(let i=0;i<count;i++)atoms.push(Object.freeze({element:['C','H','O','N','P','S'][V.u32(VERSION,complex.complexIdentity,'element',i)%6],position:Object.freeze([V.signedPpm(VERSION,complex.complexIdentity,'x',i)/100000,V.signedPpm(VERSION,complex.complexIdentity,'y',i)/100000,V.signedPpm(VERSION,complex.complexIdentity,'z',i)/100000]),coordinateAuthority:'SYNTHETIC_ATOMIC_REPRESENTATION'}));}
 return Object.freeze({regime:'atomic',representationId:representationId(complex.complexIdentity,'atomic'),parentRepresentationId:molecularState.representationId,complexIdentity:complex.complexIdentity,visualAuthority:sourceBacked?'SOURCE_BACKED_ATOMIC':'SYNTHETIC_ATOMIC_REPRESENTATION',sourceId:sourceBacked?sourceRecord.sourceId:null,atoms:Object.freeze(atoms),dynamics:'NOT_SIMULATED',quantumSimulation:false,authority:sourceBacked?Object.freeze({...AUTH,class:'DERIVED'}):Object.freeze({...AUTH,class:'PRESENTATION_ONLY'})});}
function reconcile(parent,child){let expected;if(parent.regime==='tissue'&&child.regime==='cell'){const selected=parent.cells.find(c=>c.cellIdentity===child.cellIdentity);V.assert(selected,'selected cell must descend from tissue');expected=selected.storeUnits;V.assert(child.parentTissueMaterialUnits===parent.massCommitmentUnits,'tissue aggregate commitment changed');}else expected=parent.materialUnits??parent.massCommitmentUnits;const childUnits=child.materialUnits??child.compositionUnits??expected,pass=expected===childUnits;return Object.freeze({status:pass?'PASS':'FAIL',parentRepresentationId:parent.representationId,childRepresentationId:child.representationId,materialCommitmentPreserved:pass,selectedMaterialUnits:expected,authority:'DERIVED'});}
O.v1Microscopic=Object.freeze({VERSION,AUTHORITY:AUTH,REGIMES,representationId,tissue,cell,molecular,atomic,reconcile});
})(globalThis);
