(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required');
const VERSION='ofu-v1-planetology-model-1';
const SOURCE_BRANCH='research/wave-v-planetology-frontier-2026-09-05@3e102e26c2adfcc8cb461193f821e10d9c374e24';
const AUTH=V.authority('v1.planetology.causal','1.0.0',[SOURCE_BRANCH],'Causal, bounded planetary scenario model layered below preserved P3/P5 canonical facts.',[
 'Climate and geodynamics are approximate scenario models, not measurements.',
 'Relief fields are constrained model-derived geography cues and do not promote presentation terrain to canonical elevation.'
]);
function composition(planetIdentity,bulkClass){const metalBase=bulkClass==='TERRESTRIAL'?310000:bulkClass==='ICE_GIANT'?90000:bulkClass==='GAS_GIANT'?35000:160000,volatileBase=bulkClass==='VOLATILE_RICH'?330000:bulkClass==='ICE_GIANT'?610000:bulkClass==='GAS_GIANT'?850000:140000,dm=Math.floor(V.signedPpm(VERSION,planetIdentity,'metal')/18),dv=Math.floor(V.signedPpm(VERSION,planetIdentity,'volatile')/18),metal=V.clamp(metalBase+dm,10000,700000),vol=V.clamp(volatileBase+dv,10000,900000-metal),silicate=1000000-metal-vol;return Object.freeze({metalPpm:metal,silicatePpm:silicate,volatilePpm:vol,sumPpm:1000000});}
function escapeModelEstimate({xuvMilliWm2,radiusKm,massMilliEarth,durationMyr,efficiencyPpm=150000}){for(const [k,v] of Object.entries({xuvMilliWm2,radiusKm,massMilliEarth,durationMyr,efficiencyPpm}))V.int(v,k,0,Number.MAX_SAFE_INTEGER);V.assert(radiusKm>0&&massMilliEarth>0&&efficiencyPpm<=1000000,'escape domain');const scaled=BigInt(xuvMilliWm2)*BigInt(radiusKm)*BigInt(radiusKm)*BigInt(radiusKm)*BigInt(durationMyr)*BigInt(efficiencyPpm)/(BigInt(massMilliEarth)*1000000000000n);return Object.freeze({massLossProxyUnits:scaled.toString(),kind:'ENERGY_LIMITED_ESCAPE_MODEL_ESTIMATE',isMathematicalUpperBound:false,authority:AUTH});}
function planetProfile({planetIdentity,bulkPriorClass='UNKNOWN',stellarLuminosityMilliSolar=1000,orbitMilliAu=1000,massMilliEarth=1000,radiusKm=6371,ageMyr=4500}){
 V.text(planetIdentity,'planetIdentity',128);for(const [k,v] of Object.entries({stellarLuminosityMilliSolar,orbitMilliAu,massMilliEarth,radiusKm,ageMyr}))V.int(v,k,1,Number.MAX_SAFE_INTEGER);const comp=composition(planetIdentity,bulkPriorClass),formationTemperatureIndex=V.clamp(Math.floor(850000/(1+orbitMilliAu/800))+V.signedPpm(VERSION,planetIdentity,'formation-temp')/10,0,1000000),coreFractionPpm=V.clamp(comp.metalPpm+Math.floor(V.signedPpm(VERSION,planetIdentity,'core')/22),10000,800000),heatIndexPpm=V.clamp(Math.floor(760000*Math.min(1,Math.sqrt(massMilliEarth/1000))*Math.max(.08,1-ageMyr/16000))+Math.floor(V.signedPpm(VERSION,planetIdentity,'heat')/16),0,1000000),geodynamicRegime=heatIndexPpm>610000?'MOBILE_OR_ACTIVE_LITHOSPHERE_SCENARIO':heatIndexPpm>260000?'STAGNANT_OR_EPISODIC_LID_SCENARIO':'LOW_ACTIVITY_SCENARIO';
 const initialVolatileUnits=Math.max(1,Math.floor(comp.volatilePpm*massMilliEarth/1000)),retention=V.clamp(150000+Math.floor(massMilliEarth*380)-Math.floor(formationTemperatureIndex*.35)+Math.floor(V.signedPpm(VERSION,planetIdentity,'retention')/5),30000,980000),retained=Math.floor(initialVolatileUnits*retention/1000000),interior=Math.floor(retained*(250000+heatIndexPpm/3)/1000000),surface=Math.floor((retained-interior)*(380000+V.unitPpm(VERSION,planetIdentity,'surface-vol')%420000)/1000000),atmosphere=retained-interior-surface,lost=initialVolatileUnits-retained;
 const fluxPpm=V.clamp(Math.floor(stellarLuminosityMilliSolar*1000000/Math.max(1,orbitMilliAu*orbitMilliAu/1000)),1000,20000000),albedoPpm=V.clamp(170000+(V.unitPpm(VERSION,planetIdentity,'albedo')%430000),50000,850000),effectiveTempMilliK=V.clamp(Math.round(278500*Math.pow((fluxPpm/1000000)*(1-albedoPpm/1000000),.25)),30000,2500000),greenhouseDeltaMilliK=V.clamp(Math.floor(Math.log10(1+atmosphere)*42000)+(comp.volatilePpm>300000?15000:0),0,600000),surfaceTempMilliK=effectiveTempMilliK+greenhouseDeltaMilliK;
 const liquidWindow=surfaceTempMilliK>=245000&&surfaceTempMilliK<=390000&&atmosphere>0,waterFractionPpm=liquidWindow?V.clamp(Math.floor(surface*900000/Math.max(1,initialVolatileUnits)),0,900000):0,iceFractionPpm=surfaceTempMilliK<285000?V.clamp(Math.floor(surface*1000000/Math.max(1,initialVolatileUnits)),0,1000000):0;
 const climate=Object.freeze({model:'BOUNDED_ENERGY_BALANCE_SCENARIO',stellarFluxPpm:fluxPpm,bondAlbedoPpm:albedoPpm,effectiveTemperatureMilliK:effectiveTempMilliK,greenhouseDeltaMilliK,surfaceTemperatureMilliK:surfaceTempMilliK,temperatureAuthority:'MODEL_DERIVED_SIMULATION',measured:false});
 return Object.freeze({planetIdentity,bulkPriorClass,formation:Object.freeze({temperatureIndexPpm:Math.round(formationTemperatureIndex),ageMyr}),composition:comp,interior:Object.freeze({coreFractionPpm,heatIndexPpm,geodynamicRegime}),volatiles:Object.freeze({initialInventoryUnits:initialVolatileUnits,interiorUnits:interior,surfaceCondensedUnits:surface,atmosphereUnits:atmosphere,lostUnits:lost,conserved:interior+surface+atmosphere+lost===initialVolatileUnits}),atmosphere:Object.freeze({inventoryUnits:atmosphere,modelPressureProxy:Math.floor(atmosphere*Math.max(1,massMilliEarth)/Math.max(1,radiusKm*radiusKm)),canonicalPressure:false}),climate,hydrosphere:Object.freeze({liquidSurfaceEligible:liquidWindow,waterAreaPpm:waterFractionPpm,iceFractionPpm,canonicalOceanClaim:false}),surfaceProcesses:Object.freeze({tectonicActivityPpm:heatIndexPpm,erosionPotentialPpm:V.clamp(Math.floor(waterFractionPpm*.6+atmosphere*17),0,1000000),impactRetentionPpm:V.clamp(1000000-Math.floor(heatIndexPpm*.55),100000,1000000)}),escape:escapeModelEstimate({xuvMilliWm2:Math.max(1,Math.floor(stellarLuminosityMilliSolar/3)),radiusKm,massMilliEarth,durationMyr:ageMyr}),authority:AUTH,provenance:V.provenance('v1.planetology.causal','1.0.0',[SOURCE_BRANCH])});
}
function surfaceRoot(profile){const water=profile.hydrosphere.waterAreaPpm,relief=V.clamp(Math.floor(profile.interior.heatIndexPpm*.55+profile.surfaceProcesses.impactRetentionPpm*.35),10000,1000000);return Object.freeze({planetIdentity:profile.planetIdentity,cellId:V.deriveId('surface-root',profile.planetIdentity,'cube-sphere'),face:-1,level:0,x:0,y:0,waterBudgetUnits:water,reliefBudgetUnits:relief,parentId:profile.planetIdentity,authority:AUTH});}
function refineCell(parent,{face=0,quadrant=0}={}){V.int(face,'face',0,5);V.int(quadrant,'quadrant',0,3);const childLevel=parent.level+1,Vx=quadrant%2,Vy=Math.floor(quadrant/2),x=parent.x*2+Vx,y=parent.y*2+Vy,weights=[1,1,1,1],waterParts=V.partition(parent.waterBudgetUnits,weights),reliefParts=V.partition(parent.reliefBudgetUnits,[3,4,4,3]),cellId=V.deriveId('surface-cell',parent.cellId,face,childLevel,x,y);return Object.freeze({planetIdentity:parent.planetIdentity,cellId,face,parentId:parent.cellId,level:childLevel,x,y,waterBudgetUnits:waterParts[quadrant],reliefBudgetUnits:reliefParts[quadrant],reliefBiasPpm:V.signedPpm(VERSION,cellId,'relief'),basinBiasPpm:V.signedPpm(VERSION,cellId,'basin'),authority:AUTH,physicalElevationCanonical:false});}
function refineFour(parent,{face=0}={}){return Object.freeze([0,1,2,3].map(q=>refineCell(parent,{face,quadrant:q})));}
function reconcileChildren(parent,children){V.assert(Array.isArray(children)&&children.length===4,'four children');const water=children.reduce((n,c)=>n+c.waterBudgetUnits,0),relief=children.reduce((n,c)=>n+c.reliefBudgetUnits,0);return Object.freeze({status:water===parent.waterBudgetUnits&&relief===parent.reliefBudgetUnits?'PASS':'FAIL',parentId:parent.cellId,waterConserved:water===parent.waterBudgetUnits,reliefBudgetConserved:relief===parent.reliefBudgetUnits,authority:'DERIVED'});}
O.v1Planetology=Object.freeze({VERSION,AUTHORITY:AUTH,composition,escapeModelEstimate,planetProfile,surfaceRoot,refineCell,refineFour,reconcileChildren});
})(globalThis);
