(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.pxContracts,R=O.waveIVScaleRuntime,P=O.v1Providers,M=O.v1Microscopic;
if(!C||!R||!P||!M)throw new Error('v1 model regime prerequisites missing');
const VERSION='ofu-v1-model-regime-runtime-1',ORDER=Object.freeze(['tissue','cell','molecular','atomic']),listeners=new Set();
const state={mode:'SPATIAL',regime:null,planetId:null,organismIdentity:null,context:null,transitions:0,lastWitness:null,lastError:null};
function emit(){const snap=snapshot();for(const fn of listeners)try{fn(snap)}catch{}return snap}
function onChange(fn){if(typeof fn!=='function')throw new TypeError('listener required');listeners.add(fn);return()=>listeners.delete(fn)}
function selectedWorld(){const sel=R.snapshot().selectedCanonicalTarget;if(!sel?.canonicalKey)throw new Error('canonical selection required');return{sel,world:P.worldFor(O.pxProduct.captured(sel.canonicalKey).selection)};}
function materialize(){const {sel,world}=selectedWorld();if(!world.microscopic)throw new Error('microscopic regime unavailable for current modeled world');const x=world.microscopic;return Object.freeze({planetId:sel.planetId,organismIdentity:x.organismIdentity,tissue:x.tissue,cell:x.cell,molecular:x.molecular,atomic:x.atomicPreview,witnesses:x.witnesses});}
function request(regime){regime=String(regime||'').toLowerCase();if(!ORDER.includes(regime))throw new Error('unsupported model regime '+regime);if(state.mode==='SPATIAL'){if(R.snapshot().semanticScale!=='human')throw new Error('microscopic descent requires Human spatial context');state.context=materialize();state.planetId=state.context.planetId;state.organismIdentity=state.context.organismIdentity;}const current=state.regime,from=current===null?'human':current,fromIndex=current===null?-1:ORDER.indexOf(current),toIndex=ORDER.indexOf(regime);if(current===null&&toIndex!==0)throw new Error('model regime descent must enter at tissue');if(current!==null&&Math.abs(toIndex-fromIndex)!==1&&toIndex!==fromIndex)throw new Error('model regimes require adjacent transitions');state.mode='MODEL_REGIME';state.regime=regime;state.transitions++;state.lastWitness=Object.freeze({contract:'ofu-v1-model-regime-transition-1',from,to:regime,planetId:state.planetId,organismIdentity:state.organismIdentity,identityPreserved:true,materialCommitmentPreserved:(state.context.witnesses||[]).every(w=>w.status==='PASS'),authority:regime==='atomic'&&state.context.atomic.visualAuthority==='SYNTHETIC_ATOMIC_REPRESENTATION'?'PRESENTATION_ONLY':'MODEL_DERIVED_SIMULATION',geometricZoomClaim:false});state.lastError=null;return emit()}
function step(direction){const d=Math.sign(Number(direction));if(!d)return snapshot();if(state.mode==='SPATIAL')return d<0?request('tissue'):snapshot();const i=ORDER.indexOf(state.regime),n=i+(d<0?1:-1);if(n<0)return exit();if(n>=ORDER.length)return snapshot();return request(ORDER[n])}
function exit(){if(state.mode==='SPATIAL')return snapshot();const before=state.regime;state.mode='SPATIAL';state.regime=null;state.context=null;state.transitions++;state.lastWitness=Object.freeze({contract:'ofu-v1-model-regime-transition-1',from:before,to:'human',planetId:state.planetId,organismIdentity:state.organismIdentity,identityPreserved:true,materialCommitmentPreserved:true,authority:'DERIVED',geometricZoomClaim:false});return emit()}
function currentValue(){return state.mode==='MODEL_REGIME'&&state.context?state.context[state.regime]:null}
function snapshot(){return Object.freeze({version:VERSION,mode:state.mode,regime:state.regime,order:ORDER,planetId:state.planetId,organismIdentity:state.organismIdentity,transitions:state.transitions,lastWitness:state.lastWitness,lastError:state.lastError,current:currentValue(),spatialScale:R.snapshot().semanticScale});}
O.v1ModelRegimeRuntime=Object.freeze({VERSION,ORDER,state,snapshot,onChange,request,step,exit,currentValue});
})(globalThis);
