(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.p2,T=O.p4,C=O.pxContracts,X=O.pxProduct,R=O.waveIVScaleRuntime,MR=O.v1ModelRegimeRuntime;
if(!P||!T||!C||!X||!R||!MR)throw new Error('v1 session prerequisites missing');
const VERSION='ofu-v1-session-runtime-1',FORMAT='OFU-V1-SESSION',SCHEMA=1n,MAX_BYTES=1024*1024,BROWSER_KEY='ofu.v1.session';
const ACTIONS=Object.freeze(['MEASURE','SAMPLE','EXPERIMENT','ECOLOGY_INTERVENTION','BIOLOGICAL_SEEDING']);
const LIVING_SPATIAL=Object.freeze({GALAXY:'galaxy',REGION:'galactic_region',NEIGHBORHOOD:'stellar_neighborhood',SYSTEM:'system',ORBIT:'orbit',APPROACH:'approach',GLOBAL_SURFACE:'global_surface',REGIONAL_SURFACE:'regional_surface',LOCAL_SURFACE:'local_surface',HUMAN:'human'});
const SPATIAL_LIVING=Object.freeze(Object.fromEntries(Object.entries(LIVING_SPATIAL).map(([stage,scale])=>[scale,stage]))),MICRO_STAGES=Object.freeze(['MATERIAL','MICROSTRUCTURE','MOLECULAR','ATOMIC']);
const encoder=new TextEncoder(),state={world:null,lineage:null,universe:null,nextSeconds:1n,exports:0,imports:0,actions:0,lastAction:null,lastImport:null};
function fail(message){throw new Error('OFU v1 session: '+message)}
function bytesEqual(a,b){return a instanceof Uint8Array&&b instanceof Uint8Array&&a.length===b.length&&a.every((v,i)=>v===b[i])}
function hashTagged(tag,value){const body=P.encode(value),prefix=encoder.encode(tag+'\0'),all=new Uint8Array(prefix.length+body.length);all.set(prefix);all.set(body,prefix.length);return O.sha256.digest(all)}
function exact(value,keys,label){if(!value||typeof value!=='object'||Array.isArray(value))fail(label+' record');const actual=Reflect.ownKeys(value);if(actual.some(k=>typeof k!=='string'))fail(label+' symbol key');const a=actual.slice().sort(),b=[...keys].sort();if(a.length!==b.length||a.some((k,i)=>k!==b[i]))fail(label+' schema');}
function preview(){const v=root.__OFU_PLANET_PREVIEW__;if(!v?.ctx?.masterSeed||!v?.ctx?.semanticManifestHash)fail('canonical preview context unavailable');return v}
function universeIdentity(){const v=preview();return P.universeIdentity(v.ctx.masterSeed,v.ctx.semanticManifestHash).digest}
function baseline(){return{contract:'ofu-v1-player-overlay-1',authority:'MODEL_DERIVED_SIMULATION',canonicalMutation:false,canonicalP6Mutation:false};}
function emptyEntity(){return{fields:Object.create(null),counters:Object.create(null),sets:Object.create(null),relations:Object.create(null),tombstoned:false}}
function agencyReducer(s,event){const d=event.descriptor;if(d.targets.length!==1)fail('agency event requires one target');const p=d.payload;exact(p,['contract','kind','parameters','authority','canonicalMutation','canonicalP6Mutation'],'agency payload');if(p.contract!=='ofu-v1-intervention-1'||!ACTIONS.includes(p.kind)||p.authority!=='MODEL_DERIVED_SIMULATION'||p.canonicalMutation!==false||p.canonicalP6Mutation!==false)fail('agency payload invalid');const k=P.hex(d.targets[0]);if(!s.entities[k])s.entities[k]=emptyEntity();s.entities[k].fields['v1.intervention.last']=P.decode(P.encode(p));s.entities[k].counters['v1.intervention.count']=(s.entities[k].counters['v1.intervention.count']||0n)+1n;}
const TRANSITION=T.createTransitionContract({contractId:'ofu.v1.player-agency',semanticVersion:'1.0.0',eventFamilies:['v1.intervention.record@1'],reducers:new Map([['v1.intervention.record@1',agencyReducer]])});
function initWorld(){if(state.world)return state.world;state.universe=universeIdentity();state.lineage=T.lineageId(state.universe,null,'v1-player-agency');state.world=T.createLiveWorld({universeIdentity:state.universe,lineage:state.lineage,baseline:baseline(),transition:TRANSITION,compactionPolicy:{threshold:64,retainTail:16}});state.nextSeconds=1n;return state.world}
function selectedCapture(){const live=R.snapshot().selectedCanonicalTarget;if(!live?.canonicalKey)fail('canonical selection required');const captured=X.captured(live.canonicalKey);if(captured.selection.target.entityId!==live.planetId)fail('selection identity mismatch');return{live,captured};}
function primarySpatialScale(){return R.snapshot().semanticScale;}
function restoreLivingSpatial(key,scale){const runtime=O.v1LivingProduct?.runtime,stage=SPATIAL_LIVING[scale];if(!runtime?.enterKey||!runtime?.scale||!runtime?.snapshot||!stage)return false;runtime.enterKey(key);if(stage!=='ORBIT')runtime.scale(stage);const s=runtime.snapshot(),expected=X.captured(key).selection.target.entityId;if(s.stage!==stage)fail('living spatial restore drift');if(s.body?.canonicalId&&s.body.canonicalId!==expected)fail('living spatial restore identity drift');return true;}
function restoreLivingPrior(prior){const runtime=O.v1LivingProduct?.runtime;if(!prior||!runtime?.snapshot)return false;try{if(prior.stage==='UNIVERSE'&&runtime.scale){runtime.scale('UNIVERSE');return true}const key=prior.body?.canonicalKey;if(!key||!runtime.enterKey)return false;runtime.enterKey(key);if(prior.point&&runtime.at&&['GLOBAL_SURFACE','REGIONAL_SURFACE','LOCAL_SURFACE','HUMAN'].includes(prior.stage)){runtime.at(prior.point.latMicroDeg,prior.point.lonMicroDeg,{stage:prior.stage});}else if(SPATIAL_LIVING[LIVING_SPATIAL[prior.stage]]&&runtime.scale&&prior.stage!=='ORBIT'){runtime.scale(prior.stage);}else if(MICRO_STAGES.includes(prior.stage)&&prior.point&&runtime.at&&runtime.selectObject&&runtime.enterMicro&&runtime.deeper){runtime.at(prior.point.latMicroDeg,prior.point.lonMicroDeg,{stage:'HUMAN'});if(prior.selectedObjectId)runtime.selectObject(prior.selectedObjectId);runtime.enterMicro(prior.selectedObjectId);let remaining=MICRO_STAGES.length;while(runtime.snapshot().stage!==prior.stage&&remaining-->0)runtime.deeper();if(runtime.snapshot().stage!==prior.stage)return false;}return true}catch{return false}}
function keyStrings(key){const out={};for(const name of ['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot']){if(!(name in key))fail('selection key missing '+name);out[name]=String(key[name]);}return out}
function keyBigInts(key){exact(key,['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot'],'selection key');const out={};for(const [k,v] of Object.entries(key)){if(typeof v!=='string'||!/^-?\d{1,20}$/.test(v))fail('selection key integer');out[k]=BigInt(v);}return out}
function modelManifest(){const h=X.snapshot().registry.manifestDigest;if(typeof h!=='string'||!/^[0-9a-f]{64}$/.test(h))fail('provider manifest unavailable');return P.unhex(h)}
function frontierSeconds(world){let s=0n;const cp=world.checkpoint?.descriptor?.lastOrderKey?.time?.seconds;if(typeof cp==='bigint'&&cp>s)s=cp;for(const e of world.events||[])if(e.descriptor.time.seconds>s)s=e.descriptor.time.seconds;return s}
function validateAction(kind,parameters={}){kind=String(kind||'').toUpperCase();if(!ACTIONS.includes(kind))fail('unsupported action');const clean=C.data(parameters,{bytes:32768,nodes:2048}),id='v1.interaction.player-agency',d=X.registry.descriptor(id),captured=selectedCapture().captured,request=C.request({contract:C.VERSION,provider:id,operation:'TRANSITION',selection:captured.selection,fidelity:d.fidelity,budget:d.budget,payload:{kind,parameters:clean}},d),impl=X.registry.implementation(id);if(!impl?.handle)fail('agency provider implementation missing');let operations=0,entities=0;const meter={consume(n=1,count=0){operations+=n;entities+=count;C.assert(operations<=request.budget.operations&&entities<=request.budget.entities,'BUDGET','agency admission');}},out=C.envelope(impl.handle(request,meter),d,request),gate=out.value;if(!gate.admissible)fail(gate.reason||'action not admissible');return{kind,parameters:clean,gate};}
function submit(kind,parameters={}){const a=validateAction(kind,parameters),{captured}=selectedCapture(),world=initWorld(),current=T.replayLiveWorld(world,TRANSITION),command={universeIdentity:state.universe,lineageId:state.lineage,time:{seconds:state.nextSeconds,micros:0n},type:'v1.intervention.record',version:1n,operationKey:'v1.'+a.kind.toLowerCase()+'.'+state.nextSeconds.toString(),targets:[P.unhex(captured.selection.target.entityId)],payload:{contract:'ofu-v1-intervention-1',kind:a.kind,parameters:a.parameters,authority:'MODEL_DERIVED_SIMULATION',canonicalMutation:false,canonicalP6Mutation:false},causes:[],preconditionStateDigest:current.digest},result=T.commit({world,command,transition:TRANSITION});state.world=result.world;state.nextSeconds=frontierSeconds(state.world)+1n;state.actions++;state.lastAction=Object.freeze({kind:a.kind,eventId:P.hex(result.event.id),stateDigest:P.hex(result.digest),compacted:result.compacted,canonicalMutation:false,canonicalP6Mutation:false});return state.lastAction;}
function body(){const {live,captured}=selectedCapture(),world=initWorld(),archive=T.exportArchive({universeIdentity:state.universe,lineage:state.lineage,baseline:world.baseline,checkpoint:world.checkpoint,events:world.events,transition:TRANSITION,compactionPolicy:world.compactionPolicy}),replayed=T.replayLiveWorld(world,TRANSITION),micro=MR.snapshot();return{format:FORMAT,schemaVersion:SCHEMA,universeIdentity:new Uint8Array(state.universe),providerManifestDigest:modelManifest(),v1ModelVersion:'1.0.0',selection:{entityId:P.unhex(captured.selection.target.entityId),key:keyStrings(live.canonicalKey)},spatialScale:primarySpatialScale(),modelRegime:micro.mode==='MODEL_REGIME'?micro.regime:null,p4TransitionDigest:T.transitionContractDigest(TRANSITION.descriptor),p4StateDigest:new Uint8Array(replayed.digest),p4Archive:archive,canonicalP6Unchanged:true,modelAuthority:'MODEL_DERIVED_SIMULATION',physicalDevices:'NOT_VERIFIED'};}
function exportBytes(){const b=body(),integrity=hashTagged('OFU-V1-SESSION-v1',b),bytes=P.encode({body:b,integrity});if(bytes.length>MAX_BYTES)fail('session exceeds byte limit');state.exports++;return bytes;}
function validateBytes(bytes){if(!(bytes instanceof Uint8Array)||bytes.length===0||bytes.length>MAX_BYTES)fail('invalid session bytes');let c;try{c=P.decode(bytes)}catch(e){fail('malformed session: '+e.message)}exact(c,['body','integrity'],'container');if(!(c.integrity instanceof Uint8Array)||c.integrity.length!==32||!bytesEqual(c.integrity,hashTagged('OFU-V1-SESSION-v1',c.body)))fail('integrity mismatch');const b=c.body;exact(b,['format','schemaVersion','universeIdentity','providerManifestDigest','v1ModelVersion','selection','spatialScale','modelRegime','p4TransitionDigest','p4StateDigest','p4Archive','canonicalP6Unchanged','modelAuthority','physicalDevices'],'body');if(b.format!==FORMAT||b.schemaVersion!==SCHEMA||b.v1ModelVersion!=='1.0.0')fail('unsupported session version');if(!bytesEqual(b.universeIdentity,universeIdentity()))fail('universe identity mismatch');if(!bytesEqual(b.providerManifestDigest,modelManifest()))fail('provider manifest mismatch');if(!bytesEqual(b.p4TransitionDigest,T.transitionContractDigest(TRANSITION.descriptor)))fail('P4 transition contract mismatch');if(b.canonicalP6Unchanged!==true||b.modelAuthority!=='MODEL_DERIVED_SIMULATION'||b.physicalDevices!=='NOT_VERIFIED')fail('authority metadata mismatch');if(!R.LADDER.includes(b.spatialScale))fail('unsupported spatial scale');if(b.modelRegime!==null&&!MR.ORDER.includes(b.modelRegime))fail('unsupported model regime');exact(b.selection,['entityId','key'],'selection');const key=keyBigInts(b.selection.key),captured=X.captured(key);if(!bytesEqual(b.selection.entityId,P.unhex(captured.selection.target.entityId)))fail('saved selection identity mismatch');const world=T.importArchive(b.p4Archive,{transition:TRANSITION}),replayed=T.replayLiveWorld(world,TRANSITION);if(!bytesEqual(replayed.digest,b.p4StateDigest))fail('P4 replay digest mismatch');if(b.modelRegime!==null){const w=O.v1Providers.worldFor(captured.selection);if(!w.microscopic)fail('saved model regime unavailable for selected world');}return{body:b,key,captured,world,replayed};}
function enterRegime(regime){MR.exit();if(regime===null)return;MR.request('tissue');while(MR.snapshot().regime!==regime){const i=MR.ORDER.indexOf(MR.snapshot().regime),j=MR.ORDER.indexOf(regime);MR.step(j>i?-1:1)}}
function importBytes(bytes){
 const v=validateBytes(bytes),prior=R.snapshot(),priorRegime=MR.snapshot().mode==='MODEL_REGIME'?MR.snapshot().regime:null,priorLiving=(()=>{try{return O.v1LivingProduct?.runtime?.snapshot?.()||null}catch{return null}})(),priorState={world:state.world,lineage:state.lineage,universe:state.universe,nextSeconds:state.nextSeconds,lastImport:state.lastImport,imports:state.imports};
 try{
  MR.exit();
  if(O.v08SelectionBridge?.selectPlanet)O.v08SelectionBridge.selectPlanet(v.key,{announce:false});else R.setSelection(v.key,{planetId:v.captured.selection.target.entityId,presentationStatus:'SUPPORTED'});
   const livingSpatialRestored=restoreLivingSpatial(v.key,v.body.spatialScale);if(R.snapshot().semanticScale!==v.body.spatialScale)R.requestStage(v.body.spatialScale,{source:livingSpatialRestored?'living-derived-representation':'v1-session-import'});enterRegime(v.body.modelRegime);
  state.world=v.world;state.universe=new Uint8Array(v.body.universeIdentity);state.lineage=new Uint8Array(v.world.lineageId);state.nextSeconds=frontierSeconds(v.world)+1n;state.imports++;
  state.lastImport=Object.freeze({status:'IMPORTED_INTEGRITY_VERIFIED',trustClass:'PORTABLE_ARCHIVE_INTEGRITY_ONLY',historicalAdmissionAttested:false,planetId:v.captured.selection.target.entityId,spatialScale:v.body.spatialScale,modelRegime:v.body.modelRegime,livingSpatialRestored,stateDigest:P.hex(v.replayed.digest),canonicalP6Unchanged:true});return state.lastImport;
 }catch(importError){
  const rollbackErrors=[];const attempt=(label,fn)=>{try{fn()}catch(error){rollbackErrors.push(new Error(label+': '+String(error?.message||error),{cause:error}))}};
  attempt('model regime rollback',()=>{MR.exit();enterRegime(priorRegime)});
  attempt('selection rollback',()=>{if(prior.selectedCanonicalTarget?.canonicalKey){if(O.v08SelectionBridge?.selectPlanet)O.v08SelectionBridge.selectPlanet(prior.selectedCanonicalTarget.canonicalKey,{announce:false});else R.setSelection(prior.selectedCanonicalTarget.canonicalKey,{planetId:prior.selectedCanonicalTarget.planetId,presentationStatus:prior.selectedCanonicalTarget.presentationStatus||'SUPPORTED'});}});
  attempt('scale rollback',()=>R.setContinuousDistance(prior.distanceIntentRadii,{source:'v1-session-import-rollback',driveCamera:false}));
  attempt('living presentation rollback',()=>{if(priorLiving&&!restoreLivingPrior(priorLiving))throw new Error('living presentation restore failed')});
  state.world=priorState.world;state.lineage=priorState.lineage;state.universe=priorState.universe;state.nextSeconds=priorState.nextSeconds;state.lastImport=priorState.lastImport;state.imports=priorState.imports;
  if(rollbackErrors.length)throw new AggregateError([importError,...rollbackErrors],'session import failed and rollback was incomplete',{cause:importError});throw importError;
 }
}
function hex(bytes){return P.hex(bytes)}function unhex(text){if(typeof text!=='string'||text.length===0||text.length%2)fail('hex session required');if(text.length>2*MAX_BYTES)fail('hex session exceeds byte limit');if(!/^[0-9a-f]+$/i.test(text))fail('hex session required');return P.unhex(text.toLowerCase())}
function browserStorage(){let storage;try{storage=root.localStorage}catch(error){fail('browser storage unavailable: '+String(error?.message||error))}if(!storage||typeof storage.getItem!=='function'||typeof storage.setItem!=='function'||typeof storage.removeItem!=='function')fail('browser storage unavailable');return storage}
function storageRead(storage){let value;try{value=storage.getItem(BROWSER_KEY)}catch(error){fail('browser storage read failed: '+String(error?.message||error))}if(value!==null&&typeof value!=='string')fail('browser storage returned invalid value');return value}
function restoreStoreState(prior){state.world=prior.world;state.lineage=prior.lineage;state.universe=prior.universe;state.nextSeconds=prior.nextSeconds;state.exports=prior.exports;}
function storeBrowser(){const storage=browserStorage(),previous=storageRead(storage),priorState={world:state.world,lineage:state.lineage,universe:state.universe,nextSeconds:state.nextSeconds,exports:state.exports};let text;try{text=hex(exportBytes());if(text.length>2*MAX_BYTES)fail('browser convenience payload too large')}catch(exportError){restoreStoreState(priorState);throw exportError}try{storage.setItem(BROWSER_KEY,text);if(storageRead(storage)!==text)throw new Error('browser storage write verification failed')}catch(writeError){restoreStoreState(priorState);const rollbackErrors=[];try{if(previous===null)storage.removeItem(BROWSER_KEY);else storage.setItem(BROWSER_KEY,previous);if(storageRead(storage)!==previous)throw new Error('browser storage rollback verification failed')}catch(error){rollbackErrors.push(error)}if(rollbackErrors.length)throw new AggregateError([writeError,...rollbackErrors],'OFU v1 session: browser save failed and rollback was incomplete',{cause:writeError});fail('browser save failed: '+String(writeError?.message||writeError))}return{textBytes:text.length,portableAuthoritative:true,verified:true}}
function loadBrowser(){const storage=browserStorage(),text=storageRead(storage);if(!text)fail('no browser convenience save');return importBytes(unhex(text))}
function snapshot(){const world=state.world,live=world?T.replayLiveWorld(world,TRANSITION):null;return Object.freeze({version:VERSION,format:FORMAT,schemaVersion:Number(SCHEMA),actions:state.actions,exports:state.exports,imports:state.imports,lastAction:state.lastAction,lastImport:state.lastImport,p4Protocol:T.VERSION,p4Transition:T.transitionContractDigest(TRANSITION.descriptor),p4StateDigest:live?P.hex(live.digest):null,portableAuthoritative:true,importTrustPolicy:'PORTABLE_ARCHIVE_INTEGRITY_ONLY',historicalAdmissionAttested:false,browserStorageConvenience:true,canonicalMutation:false,canonicalP6Mutation:false});}
O.v1Session=Object.freeze({VERSION,FORMAT,SCHEMA,MAX_BYTES,ACTIONS,TRANSITION,LIVING_SPATIAL,SPATIAL_LIVING,initWorld,validateAction,submit,exportBytes,validateBytes,importBytes,storeBrowser,loadBrowser,hex,unhex,snapshot});
})(globalThis);
