import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const sandbox={console,Math,TextEncoder,TextDecoder,Uint8Array,Uint32Array,ArrayBuffer,BigInt};sandbox.globalThis=sandbox;vm.createContext(sandbox);
for(const file of ['src/kernel/sha256.js','src/rendering/deep3d/spatial-address.js','src/rendering/deep3d/render-packets.js','src/rendering/deep3d/local-adapter.js'])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});
const A=sandbox.OFU.deep3dLocalAdapter,frame={version:'local-frame-1',authority:'PRESENTATION_ONLY',terrain:{supported:true,camera:{planetId:'planet-a',anchorToken:'location-a'},vertices:[[-1,4,0],[1,4,0],[-1,6,.2],[1,6,.2]],vertexSamples:[{surfaceClass:'SOLID',materialFamily:'REGOLITH',sourceAuthority:'MODEL_DERIVED_SIMULATION'},{surfaceClass:'SOLID',materialFamily:'REGOLITH',sourceAuthority:'MODEL_DERIVED_SIMULATION'},{surfaceClass:'WATER_MODELLED',materialFamily:'WATER',sourceAuthority:'MODEL_DERIVED_SIMULATION'},{surfaceClass:'WATER_MODELLED',materialFamily:'WATER',sourceAuthority:'MODEL_DERIVED_SIMULATION'}],triangles:[[0,1,2],[1,3,2]]},embodiment:{planetId:'planet-a',anchorToken:'location-a',objects:[{id:'settlement-a',pickKey:'entity:settlement-a',persistentEntity:true,kind:'SETTLEMENT',positionM:[2,8,0],radiusM:2,heightM:5,sourceAuthority:'MODEL_DERIVED_SIMULATION',claims:{canonicalPositionClaim:false}},{id:'organism-cue',pickKey:'presentation:organism-cue',persistentEntity:false,kind:'ORGANISM',positionM:[-2,6,0],radiusM:.4,heightM:1.2,sourceAuthority:'PRESENTATION_ONLY',claims:{canonicalPositionClaim:false}}]}};
const options={stage:'HUMAN',cameraPosition:[1,2,3],viewportClass:'desktop',semanticSelection:{entityId:'settlement-a'}},source=JSON.stringify({frame,options}),scene=A.createRenderScene(frame,options),again=A.createRenderScene(frame,options);
assert.equal(scene.fingerprint,again.fingerprint);assert.equal(JSON.stringify({frame,options}),source,'local adaptation must not mutate source materialization');assert.equal(scene.frameId,'local:location-a');assert.equal(scene.semanticSelection.entityId,'settlement-a');assert.ok(scene.packets.some(p=>p.packetId==='local:terrain:sediment'));assert.ok(scene.packets.some(p=>p.packetId==='local:objects:structure'));assert.ok(scene.packets.some(p=>p.packetId==='local:objects:organism'));const structure=scene.packets.find(p=>p.packetId==='local:objects:structure');assert.equal(structure.geometry.domain,'STRUCTURE');assert.equal(structure.geometry.coordinateSpace,'CAMERA_RELATIVE_FLOAT32');assert.ok(structure.semanticState.entityIds.includes('settlement-a'));assert.equal(structure.semanticState.sourceAuthorities[0],'MODEL_DERIVED_SIMULATION');assert.equal(structure.claims.canonicalPosition,false);assert.ok(scene.resourceTotals.gpuBytes<=A.LIMITS.maxGpuBytes);assert.deepEqual(Array.from(A.localPoint([2,8,0],[1,2,3])),[1,-2,-11]);assert.equal(A.claims.cameraAuthority,false);assert.equal(A.claims.selectionAuthority,false);assert.throws(()=>A.createRenderScene({...frame,authority:'CANONICAL_PROVEN'},options),/materialization required/);assert.throws(()=>A.createRenderScene(frame,{...options,cameraPosition:[0,Infinity,0]}),/finite/);assert.throws(()=>A.createRenderScene({...frame,embodiment:{...frame.embodiment,objects:Array.from({length:A.LIMITS.maxObjects+1},()=>frame.embodiment.objects[0])}},options),/bound/);
console.log(JSON.stringify({status:'PASS',suite:'v2-deep3d-local-adapter',packets:scene.packets.length,vertices:scene.resourceTotals.vertices,identity:'settlement-a',fingerprint:scene.fingerprint}));
