import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const sandbox={console,Math,TextEncoder,TextDecoder,Uint8Array,Uint32Array,ArrayBuffer,BigInt};sandbox.globalThis=sandbox;vm.createContext(sandbox);
for(const file of ['src/kernel/sha256.js','src/rendering/deep3d/spatial-address.js','src/rendering/deep3d/render-packets.js','src/rendering/deep3d/matter-adapter.js'])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});
const A=sandbox.OFU.deep3dMatterAdapter,presentation={contract:'ofu-v2x12-microscopic-presentation-12',providerId:'v2x12.presentation.matter-continuity',authority:'PRESENTATION_ONLY',sourceEntityId:'material-source-a',materialId:'material-a',regime:'MOLECULAR',nodes:[{id:'molecule-a',kind:'REPRESENTATIVE_MOLECULE',componentId:'a',position:[-1,0,.25],positionAuthority:'PRESENTATION_ONLY'},{id:'molecule-b',kind:'REPRESENTATIVE_MOLECULE',componentId:'b',position:{x:1,y:0,z:-.25},positionAuthority:'PRESENTATION_ONLY'},{id:'unknown',kind:'UNRESOLVED_MATERIAL_REMAINDER',position:[0,1,0],componentAuthority:'UNRESOLVED_CHEMISTRY'}],nodeAvailableCount:3,relations:[{id:'r1',kind:'SEMANTIC_RELATION',from:'molecule-a',to:'molecule-b'},{id:'r2',kind:'UNRESOLVED_RELATION'}],relationAvailableCount:2};
const options={stage:'MOLECULAR',cameraPosition:[1,2,3],viewportClass:'desktop',scaleUnits:10,semanticSelection:{entityId:'material-source-a'}},source=JSON.stringify({presentation,options}),scene=A.createRenderScene(presentation,options),again=A.createRenderScene(presentation,options);
assert.equal(scene.fingerprint,again.fingerprint);assert.equal(JSON.stringify({presentation,options}),source,'matter adaptation must not mutate V2X-12 presentation');assert.equal(scene.frameId,'matter:material-source-a:molecular');assert.equal(scene.semanticSelection.entityId,'material-source-a');assert.ok(scene.packets.some(p=>p.packetId==='matter:nodes:molecular'));assert.ok(scene.packets.some(p=>p.packetId==='matter:nodes:unresolved'));const molecular=scene.packets.find(p=>p.packetId==='matter:nodes:molecular'),unresolved=scene.packets.find(p=>p.packetId==='matter:nodes:unresolved'),relations=scene.packets.find(p=>p.packetId==='matter:relations');assert.deepEqual(Array.from(molecular.geometry.positions.slice(0,3)),[-11,-2,-.5]);assert.equal(unresolved.semanticState.unresolved,true);assert.equal(unresolved.claims.exactSpatialArrangement,false);assert.equal(relations.semanticState.representedRelations,1);assert.equal(relations.claims.physicalBondGeometry,false);assert.ok(scene.resourceTotals.points<=A.LIMITS.maxPoints);assert.equal(A.claims.quantumDynamics,false);assert.equal(A.claims.unresolvedChemistryPreserved,true);assert.throws(()=>A.createRenderScene({...presentation,authority:'CANONICAL_PROVEN'},options),/presentation required/);assert.throws(()=>A.createRenderScene(presentation,{...options,stage:'ATOMIC'}),/mismatch/);assert.throws(()=>A.createRenderScene({...presentation,nodes:[...presentation.nodes,{id:'molecule-a',kind:'X',position:[0,0,0]}]},options),/unique/);assert.throws(()=>A.createRenderScene(presentation,{...options,cameraPosition:[NaN,0,0]}),/finite/);
const sparse=A.createRenderScene({...presentation,regime:'MATERIAL',nodes:[{id:'material-only',kind:'MATERIAL_COMPONENT',position:[0,0,0],positionAuthority:'PRESENTATION_ONLY'}],relations:[]},{...options,stage:'MATERIAL'}),focus=sparse.packets.find(p=>p.packetId==='matter:semantic-focus');assert(focus);assert.equal(focus.claims.presentationFocusCue,true);assert.equal(focus.claims.additionalMatterEntity,false);assert.equal(focus.geometry.positions.length,48*2*3);
console.log(JSON.stringify({status:'PASS',suite:'v2-deep3d-matter-adapter',packets:scene.packets.length,points:scene.resourceTotals.points,representedRelations:relations.semanticState.representedRelations,sourceEntityId:presentation.sourceEntityId,fingerprint:scene.fingerprint}));
