import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const sandbox={console,Math,TextEncoder,TextDecoder,Uint8Array,Uint32Array,ArrayBuffer,BigInt};
sandbox.globalThis=sandbox;
vm.createContext(sandbox);
for(const file of ['src/kernel/sha256.js','src/rendering/deep3d/spatial-address.js','src/rendering/deep3d/render-packets.js','src/rendering/deep3d/surface-adapter.js'])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});
const A=sandbox.OFU.deep3dSurfaceAdapter;
const frame={status:'READY',authority:'PRESENTATION_ONLY',planetIdentity:'planet-a',anchorLocationIdentity:'location-a',frameDigest:'surface-frame-a',patches:[{patchIdentity:'patch-a',polygons:[{kind:'TERRAIN_CELL',baseFill:'#52684f',surfaceClass:'SOLID',reliefCue:.2,points:[[0,0],[.5,0],[.5,.5],[0,.5]]},{kind:'TERRAIN_CELL',baseFill:'#315a74',surfaceClass:'LIQUID',reliefCue:-.1,points:[[.5,0],[1,0],[1,.5],[.5,.5]]}],coasts:[{points:[[.45,0],[.5,.5],[.48,1]]}],rivers:[{points:[[.15,.2],[.3,.45],[.5,.7]]}]}]};
const options={stage:'REGIONAL_SURFACE',cameraPosition:[1,2,3],viewportClass:'desktop',scaleUnits:24,reliefScale:4,semanticSelection:{entityId:'location-a'}};
const sourceBefore=JSON.stringify({frame,options}),scene=A.createRenderScene(frame,options),again=A.createRenderScene(frame,options);
assert.equal(scene.fingerprint,again.fingerprint,'surface adaptation must be deterministic');
assert.equal(JSON.stringify({frame,options}),sourceBefore,'surface adaptation must not mutate source state');
assert.equal(scene.frameId,'surface:regional_surface');
assert.equal(scene.cameraPolicyId,'v2x02.authoritative');
assert.equal(scene.semanticSelection.entityId,'location-a');
assert.equal(scene.packets.filter(p=>p.family==='MESH').length,2);
assert.equal(scene.packets.filter(p=>p.family==='CURVE').length,2);
const land=scene.packets.find(p=>p.packetId==='surface:terrain:52684f:0');
assert.deepEqual(Array.from(land.geometry.positions.slice(0,3)),[-13,-1.2,9]);
assert.equal(land.geometry.coordinateSpace,'CAMERA_RELATIVE_FLOAT32');
assert.equal(land.provenance,'PRESENTATION_ONLY');
assert.equal(land.semanticState.sourceAuthority,'MODEL_DERIVED_SIMULATION');
assert.equal(land.claims.physicalElevation,false);
assert.equal(land.claims.canonicalGeodesy,false);
assert.equal(land.claims.presentationColorVariation,true);
assert.ok(scene.resourceTotals.vertices<=A.LIMITS.maxVertices);
assert.ok(scene.resourceTotals.gpuBytes<=8388608);
assert.equal(A.claims.cameraAuthority,false);
assert.equal(A.claims.selectionAuthority,false);
assert.throws(()=>A.createRenderScene({...frame,authority:'CANONICAL_PROVEN'},options),/authority mismatch/);
assert.throws(()=>A.createRenderScene(frame,{...options,cameraPosition:[0,Number.NaN,0]}),/must be finite/);
assert.throws(()=>A.createRenderScene(frame,{...options,cameraPosition:[0,0]}),/vec3/);
assert.throws(()=>A.createRenderScene({...frame,patches:[{polygons:[{baseFill:'#000000',reliefCue:0,points:[[0,0],[1,0],[1,1],[Number.POSITIVE_INFINITY,1]]}]}]},options),/must be finite/);
console.log(JSON.stringify({status:'PASS',suite:'v2-deep3d-surface-adapter',packets:scene.packets.length,vertices:scene.resourceTotals.vertices,fingerprint:scene.fingerprint,authority:A.AUTHORITY}));
