import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const x={console,TextEncoder,TextDecoder,Uint8Array,Float32Array,Float64Array,ArrayBuffer,Math,Map};x.globalThis=x;vm.createContext(x);
for(const f of ['src/kernel/sha256.js','src/v1x-04-stellar-system-rendering/system-math.js','src/v1x-04-stellar-system-rendering/orbit-presentation.js','src/v1x-04-stellar-system-rendering/system-scene.js','src/rendering/deep3d/spatial-address.js','src/rendering/deep3d/render-packets.js','src/rendering/deep3d/system-adapter.js'])vm.runInContext(fs.readFileSync(f,'utf8'),x,{filename:f});
const A=x.OFU.deep3dSystemAdapter;
const source={coordinateModel:'TRUE_3D_CARTESIAN_PRESENTATION_SPACE',systemCanonicalEntityId:'sys:alpha',nodes:[{kind:'STAR',canonicalEntityId:'star:a',parentCanonicalEntityId:'sys:alpha',transitionPosition3d:[10,2,-4],position3d:[10,2,-4],selectionAuthority:'UPSTREAM_SELECTION_CONTRACT',geometryAuthority:'PRESENTATION_ONLY',sourceFactsAuthority:'CANONICAL_PROVEN'},{kind:'PLANET',canonicalEntityId:'planet:b',parentCanonicalEntityId:'star:a',systemCanonicalEntityId:'sys:alpha',transitionPosition3d:[20,3,-5],position3d:[20,3,-5],selectionAuthority:'UPSTREAM_SELECTION_CONTRACT',geometryAuthority:'PRESENTATION_ONLY',sourceFactsAuthority:'CANONICAL_PROVEN',currentOrbitalPhaseAuthority:'PRESENTATION_ONLY'}],orbits:[{canonicalEntityId:'planet:b',geometryAuthority:'PRESENTATION_ONLY',currentOrbitalPhaseAuthority:'PRESENTATION_ONLY',vertices:Array.from({length:24},(_,i)=>{const a=i*Math.PI*2/23;return [20+5*Math.cos(a),3,-5+5*Math.sin(a)]})}]};
const mesh=A.makeIcosphere(2);assert.equal(mesh.vertices.length,162);assert.equal(mesh.indices.length,960);for(const n of mesh.vertices)assert.ok(Math.abs(Math.hypot(...n)-1)<1e-12);
const scene=A.createRenderScene(source,{cameraPosition:[10,2,-4],semanticSelection:{entityId:'planet:b'}});assert.equal(scene.frameId,'system');assert.equal(scene.packets.length,3);assert.equal(scene.semanticSelection.entityId,'planet:b');const star=scene.packets.find(p=>p.entityId==='star:a'&&p.family==='MESH'),planet=scene.packets.find(p=>p.entityId==='planet:b'&&p.family==='MESH'),orbit=scene.packets.find(p=>p.family==='CURVE');assert.ok(star);assert.ok(planet);assert.ok(orbit);assert.equal(star.provenance,'PRESENTATION_ONLY');assert.equal(star.representationId,'deep3d-icosphere-body-1');assert.equal(star.geometry.coordinateSpace,'CAMERA_RELATIVE_FLOAT32');assert.equal(star.geometry.positions.length,486);assert.equal(star.geometry.normals.length,486);assert.equal(star.geometry.indices.length,960);assert.equal(star.resources.vertices,162);assert.equal(star.resources.indices,960);assert.ok(Math.abs(Math.hypot(...Array.from(star.geometry.positions.slice(0,3)))-2.6)<1e-12);assert.equal(star.geometry.lit,false);assert.equal(planet.geometry.lit,true);assert.equal(planet.semanticState.selected,true);assert.equal(planet.material.selectionGlow,.72);assert.equal(star.claims.physicalRadius,false);assert.equal(star.claims.physicalLighting,false);assert.equal(orbit.claims.metricOrbitDistance,false);assert.equal(orbit.claims.currentOrbitalPhase,false);assert.equal(orbit.geometry.curveTopology,'LINE_STRIP');assert.equal(star.picking.entityId,'star:a');assert.deepEqual(Array.from(star.spatialAddress.hierarchy),['galaxy','system']);assert.equal(A.claims.cameraAuthority,false);assert.equal(A.claims.bodyGeometry,'DETERMINISTIC_ICOSPHERE');
const scene2=A.createRenderScene(source,{cameraPosition:[10,2,-4],semanticSelection:{entityId:'planet:b'}});assert.equal(scene.fingerprint,scene2.fingerprint);const mobile=A.createRenderScene(source,{cameraPosition:[10,2,-4],viewportClass:'mobile-portrait',semanticSelection:{entityId:'planet:b'}}),mobileBody=mobile.packets.find(p=>p.entityId==='planet:b'&&p.family==='MESH');assert.equal(mobileBody.resources.vertices,42);assert.equal(mobileBody.resources.indices,240);assert.notEqual(scene.fingerprint,mobile.fingerprint);assert.throws(()=>A.createRenderScene({...source,coordinateModel:'FAKE_2D'}),/true-3D/);
console.log(JSON.stringify({status:'PASS',suite:'v2-deep3d-system-adapter',packets:scene.packets.length,desktopBodyVertices:star.resources.vertices,mobileBodyVertices:mobileBody.resources.vertices,fingerprint:scene.fingerprint,canonicalIdentityPreserved:true,scientificPromotion:false,cameraAuthority:false}));
