import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const sandbox={console,TextEncoder,TextDecoder,Uint8Array,Float32Array,Float64Array,Uint32Array,ArrayBuffer,Math};sandbox.globalThis=sandbox;vm.createContext(sandbox);
for(const file of ['src/kernel/sha256.js','src/rendering/deep3d/spatial-address.js','src/rendering/deep3d/render-packets.js'])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});
const calls=[],fake={render(frame){calls.push(['render',frame]);return Object.freeze({backend:'V2X13_WEBGL2_PIXEL_CONSUMER',primaryRendererAuthority:false,cameraAuthority:'EXTERNAL_READ_ONLY',semanticSignature:frame.semanticSignature})},replayLastFrame(){calls.push(['replay']);return {replay:true}},snapshot(){return {valid:true,resourceManager:{trackedBytes:0}}},contextLost(){calls.push(['lost']);return {valid:false}},contextRestored(){calls.push(['restored']);return {valid:true}},dispose(){calls.push(['dispose']);return {disposed:true}}};
sandbox.OFU.renderWebGL2Resources={createFrameConsumer(){throw new Error('injected consumer expected')}};vm.runInContext(fs.readFileSync('src/rendering/deep3d/webgl2-backend.js','utf8'),sandbox,{filename:'webgl2-backend.js'});
const P=sandbox.OFU.deep3dRenderPackets,B=sandbox.OFU.deep3dWebGL2Backend,address={frameId:'system',hierarchy:['galaxy','system'],nativeKey:{system:'alpha'},local:[0,0,0],unit:'FRAME_NATIVE',parentFrameId:'galaxy',transformRevision:'1'};
const packets=[
 {packetId:'mesh:b',family:'MESH',entityId:'body:b',representationId:'sphere-mesh',lodKey:'2',spatialAddress:address,provenance:'MODEL_DERIVED',semanticState:{body:'b'},geometry:{domain:'SYSTEM',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:[-1,-1,0,1,-1,0,0,1,0],normals:[0,0,1,0,0,1,0,0,1],lit:true,lodLevel:2,lodTransition:0},material:{baseColor:[.7,.5,.3]},picking:{entityId:'body:b'},resources:{vertices:3,cpuBytes:72,gpuBytes:72}},
 {packetId:'points:a',family:'POINT_BATCH',entityId:'field:a',representationId:'points',lodKey:'0',spatialAddress:address,provenance:'PRESENTATION_ONLY',semanticState:{field:'a'},geometry:{domain:'MACRO',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:[0,0,-2,2,0,-2],lit:false},material:{baseColor:[1,1,1],pointSize:3},picking:{entityId:'field:a'},resources:{points:2,vertices:2,cpuBytes:24,gpuBytes:24}},
 {packetId:'curve:c',family:'CURVE',entityId:'orbit:c',representationId:'polyline',lodKey:'0',spatialAddress:address,provenance:'PRESENTATION_ONLY',semanticState:{orbit:'c'},geometry:{domain:'SYSTEM',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:[0,0,0,1,0,0,1,1,0],curveTopology:'LINE_STRIP',lit:false},material:{baseColor:[.5,.5,.5]},picking:{entityId:'orbit:c'},resources:{vertices:3,cpuBytes:36,gpuBytes:36}}
];
const scene={frameId:'system',cameraPolicyId:'v2x02.authoritative',viewportClass:'desktop',packets,semanticSelection:{selectionToken:'body:b'}};
const I=[1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1],frame={viewport:{width:1280,height:720},camera:{frameId:'system',viewProjection:I,position:[0,0,0]},aaMode:'NONE'};
const compiled=B.compileScene(scene,frame),canonical=P.createScene(scene);assert.equal(compiled.semanticSignature,canonical.fingerprint);assert.equal(compiled.deep3d.sceneFingerprint,canonical.fingerprint);assert.equal(compiled.selectionId,'body:b');const byId=Object.fromEntries(compiled.draws.map(d=>[d.id,d]));assert.equal(byId['mesh:b'].primitive,'TRIANGLES');assert.equal(byId['points:a'].primitive,'POINTS');assert.equal(byId['curve:c'].primitive,'LINES');assert.equal(byId['curve:c'].sourceVertexCount,3);assert.equal(byId['curve:c'].drawVertexCount,4);assert.deepEqual(Array.from(byId['curve:c'].positions),[0,0,0,1,0,0,1,0,0,1,1,0]);assert.equal(compiled.deep3d.curveCompilation,'LINE_STRIP_TO_SEGMENT_PAIRS');assert.deepEqual(Array.from(compiled.deep3d.presentationBounds.span),[3,2,2]);assert.equal(compiled.deep3d.presentationBounds.nonDegenerateAxes,3);assert.equal(compiled.deep3d.presentationBounds.volumetric,true);
const backend=B.createBackend(null,{frameConsumer:fake}),witness=backend.render(scene,frame);assert.equal(witness.sceneFingerprint,canonical.fingerprint);assert.equal(witness.primaryRendererAuthority,false);assert.equal(witness.cameraAuthority,'EXTERNAL_READ_ONLY');assert.equal(witness.presentationBounds.volumetric,true);assert.equal(witness.v2x13.semanticSignature,canonical.fingerprint);assert.equal(backend.snapshot().resourceLifecycle,'V2X13_DELEGATED');backend.contextLost();backend.contextRestored();backend.replayLastFrame();backend.dispose();assert.ok(calls.some(c=>c[0]==='lost')&&calls.some(c=>c[0]==='restored')&&calls.some(c=>c[0]==='dispose'));
const unsupported={...packets[1],packetId:'instances:x',family:'INSTANCE_BATCH',representationId:'instances'};assert.throws(()=>B.compileScene({...scene,packets:[unsupported]},frame),/not implemented/);assert.throws(()=>B.compileScene(scene,{...frame,camera:{...frame.camera,frameId:'planet'}}),/frame mismatch/);assert.throws(()=>B.compileScene({...scene,packets:[{...packets[1],packetId:'bad-space',geometry:{...packets[1].geometry,coordinateSpace:'GLOBAL_FLOAT32'}}]},frame),/CAMERA_RELATIVE_FLOAT32/);assert.throws(()=>B.compileScene({...scene,packets:[{...packets[2],packetId:'bad-curve',geometry:{...packets[2].geometry,curveTopology:'BEZIER'}}]},frame),/curve topology/);
console.log(JSON.stringify({status:'PASS',suite:'v2-deep3d-webgl2-backend',sceneFingerprint:canonical.fingerprint,delegatedLifecycle:true,curveContinuityCompiled:true,supportedFamilies:Object.keys(B.FAMILY_PRIMITIVE),unsupportedFamiliesFailClosed:true}));
