(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const TAU=Math.PI*2;
const AUTHORITY='PRESENTATION_ONLY';
const PHASE='UNKNOWN_NOT_CANONICAL';
const LIMITS=Object.freeze({minSegments:24,maxSegments:256,maxBodies:128,maxVertices:32896,maxPresentationEccentricity:.95});
function finite(value,label){if(value===null||value===undefined||typeof value==='boolean'||(typeof value==='string'&&value.trim()===''))throw new TypeError(label+' must be finite');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite');return n}
function optionalFinite(value,label){if(value===null||value===undefined||(typeof value==='string'&&value.trim()===''))return null;if(typeof value==='boolean')throw new TypeError(label+' must be finite when supplied');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite when supplied');return n}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function idToken(id){if(typeof id==='string'&&id)return id;if(id instanceof Uint8Array)return Array.from(id,b=>b.toString(16).padStart(2,'0')).join('');if(ArrayBuffer.isView(id))return Array.from(new Uint8Array(id.buffer,id.byteOffset,id.byteLength),b=>b.toString(16).padStart(2,'0')).join('');throw new TypeError('entity id must be non-empty string or bytes')}
function compareId(a,b){a=String(a);b=String(b);return a<b?-1:a>b?1:0}
function stableHash(text){let h=2166136261>>>0,s=String(text);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function unitHash(text,salt){let x=(stableHash(text)^Math.imul(salt+1,0x9e3779b1))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/4294967296}
function rotate(x,y,inc,node,peri){const cw=Math.cos(peri),sw=Math.sin(peri),ci=Math.cos(inc),si=Math.sin(inc),cn=Math.cos(node),sn=Math.sin(node),xp=x*cw-y*sw,yp=x*sw+y*cw,yi=yp*ci,zi=yp*si;return Object.freeze([xp*cn-yi*sn,xp*sn+yi*cn,zi])}
function orientationFromFacts(facts,entityId='presentation-orbit'){
 facts=facts||{};const token=idToken(entityId),incValue=optionalFinite(facts.baselineInclinationMilliDeg,'baselineInclinationMilliDeg'),nodeValue=optionalFinite(facts.longitudeAscendingNodeMilliDeg,'longitudeAscendingNodeMilliDeg'),periValue=optionalFinite(facts.argumentPeriapsisMilliDeg,'argumentPeriapsisMilliDeg'),unknownFields=[];
 if(incValue===null)unknownFields.push('inclination');if(nodeValue===null)unknownFields.push('longitudeAscendingNode');if(periValue===null)unknownFields.push('argumentPeriapsis');
 const inc=(incValue===null?0:incValue)*Math.PI/180000,node=nodeValue===null?unitHash(token,0)*TAU:nodeValue*Math.PI/180000,peri=periValue===null?unitHash(token,1)*TAU:periValue*Math.PI/180000;
 return Object.freeze({inclinationRad:inc,longitudeAscendingNodeRad:node,argumentPeriapsisRad:peri,orientationAuthority:unknownFields.length?'PARTIAL_PRESENTATION_FALLBACK':'CANONICAL_PROVEN',unknownFields:Object.freeze(unknownFields),fallbackDeterministic:unknownFields.length>0});
}
function displayRadius(facts){if(!facts||typeof facts!=='object')throw new TypeError('orbit facts required');const microAu=finite(facts.baselineSemiMajorAxisMicroAu,'baselineSemiMajorAxisMicroAu');if(!(microAu>0))throw new RangeError('positive baselineSemiMajorAxisMicroAu required');return 12+24*Math.log1p(microAu/1e6)}
function shapeFromFacts(facts){const a=displayRadius(facts),rawPpm=optionalFinite(facts.baselineEccentricityPpm,'baselineEccentricityPpm');if(rawPpm!==null&&(rawPpm<0||rawPpm>=1e6))throw new RangeError('baselineEccentricityPpm must be in [0,1000000) when supplied');const rawE=(rawPpm===null?0:rawPpm)/1e6,e=clamp(rawE,0,LIMITS.maxPresentationEccentricity),b=a*Math.sqrt(1-e*e);return Object.freeze({semiMajorDisplayUnits:a,semiMinorDisplayUnits:b,inputEccentricityPpm:rawPpm,effectivePresentationEccentricity:e,eccentricityAuthority:rawPpm===null?'PRESENTATION_FALLBACK_ZERO':'CANONICAL_PROVEN_INPUT',eccentricityClampedForPresentation:rawPpm!==null&&rawE>LIMITS.maxPresentationEccentricity})}
function orbitPoint(shape,orientation,center3d,eccentricAnomaly){const E=finite(eccentricAnomaly,'eccentricAnomaly'),x=shape.semiMajorDisplayUnits*(Math.cos(E)-shape.effectivePresentationEccentricity),y=shape.semiMinorDisplayUnits*Math.sin(E),p=rotate(x,y,orientation.inclinationRad,orientation.longitudeAscendingNodeRad,orientation.argumentPeriapsisRad);return Object.freeze([p[0]+center3d[0],p[1]+center3d[1],p[2]+center3d[2]])}
function orbitPointFromAnomaly(body,orientation,center3d,eccentricAnomaly){if(!body||!body.facts)throw new TypeError('body facts required');if(!Array.isArray(center3d)||center3d.length!==3)throw new TypeError('center3d must be vec3');const center=center3d.map((v,i)=>finite(v,'center3d['+i+']'));return orbitPoint(shapeFromFacts(body.facts),orientation,center,eccentricAnomaly)}
function presentationAnchorAnomaly(body){if(!body)throw new TypeError('body required');return unitHash(idToken(body.id),2)*TAU}
function buildOrbit(body,{segments=96,center3d=[0,0,0]}={}){
 if(!body||body.id===undefined||body.id===null||!body.facts)throw new TypeError('body envelope with id and facts required');segments=finite(segments,'segments');if(!Number.isInteger(segments)||segments<LIMITS.minSegments||segments>LIMITS.maxSegments)throw new RangeError('segments outside bounded orbit budget');if(!Array.isArray(center3d)||center3d.length!==3)throw new TypeError('center3d must be vec3');const center=center3d.map((v,i)=>finite(v,'center3d['+i+']')),canonicalEntityId=idToken(body.id),parentCanonicalEntityId=body.parentId===undefined||body.parentId===null?null:idToken(body.parentId),orientation=orientationFromFacts(body.facts,body.id),shape=shapeFromFacts(body.facts),vertices=[];
 for(let i=0;i<segments;i++)vertices.push(orbitPoint(shape,orientation,center,TAU*i/segments));vertices.push(vertices[0]);const anchorAnomaly=presentationAnchorAnomaly(body),presentationAnchor3d=orbitPoint(shape,orientation,center,anchorAnomaly);
 return Object.freeze({canonicalEntityId,parentCanonicalEntityId,vertices:Object.freeze(vertices),center3d:Object.freeze(center),presentationAnchor3d,presentationAnchorAnomalyRad:anchorAnomaly,presentationAnchorAuthority:AUTHORITY,geometryAuthority:AUTHORITY,inputFactsAuthority:'CANONICAL_PROVEN_WHERE_PRESENT',orientation,shape,currentOrbitalPhaseAuthority:PHASE,scaleSemantics:'SCHEMATIC_LOG_AU',limitations:Object.freeze(['No current orbital phase is invented.','Missing orientation facts use deterministic presentation fallbacks and remain explicitly non-canonical.','The identity-derived presentation anchor is not a current ephemeris position.','Display radius is logarithmically compressed presentation geometry.','Very high but bound eccentricity may be visually clamped and is disclosed by eccentricityClampedForPresentation.','The closing orbit vertex reuses the first vertex exactly to avoid presentation seam drift.'])});
}
function resolveHierarchy(bodies,{segments=96,rootCenter3d=[0,0,0]}={}){
 if(!Array.isArray(bodies))throw new TypeError('bodies array required');if(bodies.length>LIMITS.maxBodies)throw new RangeError('body budget exceeded');if(!Array.isArray(rootCenter3d)||rootCenter3d.length!==3)throw new TypeError('rootCenter3d must be vec3');const rootCenter=Object.freeze(rootCenter3d.map((v,i)=>finite(v,'rootCenter3d['+i+']'))),byId=new Map(),ordered=[];
 for(const body of bodies){if(!body||body.id===undefined||body.id===null)throw new TypeError('body id required');const id=idToken(body.id);if(byId.has(id))throw new Error('duplicate body id '+id);byId.set(id,body)}
 const state=new Map(),centers=new Map();function visit(body){const id=idToken(body.id),s=state.get(id);if(s===2)return;if(s===1)throw new Error('orbital hierarchy cycle at '+id);state.set(id,1);let center=rootCenter;let parentId=null;if(body.parentId!==undefined&&body.parentId!==null){parentId=idToken(body.parentId);const parent=byId.get(parentId);if(!parent)throw new Error('missing orbital parent '+parentId);visit(parent);center=centers.get(parentId)||rootCenter}const orbit=buildOrbit(body,{segments,center3d:center}),anchor=orbit.presentationAnchor3d;centers.set(id,anchor);ordered.push(Object.freeze({id,parentId,orbit,anchor3d:anchor,anchorAuthority:AUTHORITY,kind:body.kind||'BODY'}));state.set(id,2)}
 for(const body of [...bodies].sort((a,b)=>compareId(idToken(a.id),idToken(b.id))))visit(body);const vertexCount=ordered.reduce((n,x)=>n+x.orbit.vertices.length,0);if(vertexCount>LIMITS.maxVertices)throw new RangeError('orbit vertex budget exceeded');return Object.freeze({authority:AUTHORITY,currentOrbitalPhaseAuthority:PHASE,nodes:Object.freeze(ordered),resourceUsage:Object.freeze({bodies:ordered.length,vertices:vertexCount}),limits:LIMITS});
}
O.v2x04Orbit3D=Object.freeze({VERSION:'ofu-v2x-04-orbit-3d-5',AUTHORITY,PHASE,LIMITS,idToken,compareId,stableHash,unitHash,orientationFromFacts,displayRadius,shapeFromFacts,orbitPointFromAnomaly,presentationAnchorAnomaly,buildOrbit,resolveHierarchy});

const SYSTEM_LIMITS=Object.freeze({maxStars:8,maxPlanets:128,maxHitTargets:136,maxProjectedVertices:32896,maxViewportDimension:16384,maxViewportPixels:67108864});
const SYSTEM_PROVIDER_ID='v2x04.system.presentation';
function requireV2(name){const api=O[name];if(!api)throw new Error('V2X-04 dependency '+name+' required; legacy fallback forbidden');return api}
function sysId(value,label='canonical entity id'){const raw=value&&typeof value==='object'?(value.canonicalEntityId??value.entityId??value.id):value;if(raw===undefined||raw===null)throw new TypeError(label+' required');return idToken(raw)}
function factsOf(raw,label){const facts=raw?.facts;if(facts===undefined||facts===null)return{};if(typeof facts!=='object'||Array.isArray(facts)||ArrayBuffer.isView(facts))throw new TypeError(label+' facts must be an object when supplied');return facts}
function sysVec3(value,label){if(!Array.isArray(value)||value.length!==3)throw new TypeError(label+' must be vec3');return Object.freeze(value.map((x,i)=>finite(x,label+'['+i+']')))}
function optionalSysVec3(value,label){if(value===undefined||value===null)return null;return sysVec3(value,label)}
function sysNorm(value,label){const v=sysVec3(value,label),n=Math.hypot(...v);if(!(n>1e-12))throw new RangeError(label+' must be non-zero');return Object.freeze(v.map(x=>x/n))}
function sysSub(a,b){return Object.freeze([a[0]-b[0],a[1]-b[1],a[2]-b[2]])}
function sysAdd(a,b){return Object.freeze([a[0]+b[0],a[1]+b[1],a[2]+b[2]])}
function sysDot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
function sysCross(a,b){return Object.freeze([a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]])}
function cameraProjector(camera,viewport){
 if(!camera||typeof camera!=='object')throw new TypeError('external camera frame required');const width=finite(viewport?.width??1280,'viewport.width'),height=finite(viewport?.height??720,'viewport.height');if(!(width>0&&height>0&&width<=SYSTEM_LIMITS.maxViewportDimension&&height<=SYSTEM_LIMITS.maxViewportDimension&&width*height<=SYSTEM_LIMITS.maxViewportPixels))throw new RangeError('viewport outside bounded projection budget');
 const position=sysVec3(camera.position,'camera.position'),target=sysVec3(camera.target,'camera.target'),upInput=sysNorm(camera.up,'camera.up'),forward=sysNorm(sysSub(target,position),'camera.forward'),right=sysNorm(sysCross(forward,upInput),'camera.right'),up=sysNorm(sysCross(right,forward),'camera.correctedUp'),fovY=finite(camera.fovYRadians,'camera.fovYRadians'),aspect=finite(camera.aspect??width/height,'camera.aspect'),near=finite(camera.near,'camera.near'),far=finite(camera.far,'camera.far');if(!(fovY>0&&fovY<Math.PI&&aspect>0&&near>0&&far>near))throw new RangeError('invalid external camera projection');const tangent=Math.tan(fovY/2);
 function project(point){const p=sysVec3(point,'presentation point'),rel=sysSub(p,position),depth=sysDot(rel,forward);if(!(depth>=near&&depth<=far))return null;const denom=depth*tangent,ndcX=sysDot(rel,right)/(denom*aspect),ndcY=sysDot(rel,up)/denom;if(!Number.isFinite(ndcX)||!Number.isFinite(ndcY))return null;return Object.freeze({x:(ndcX*.5+.5)*width,y:(.5-ndcY*.5)*height,depth,visible:Math.abs(ndcX)<=1&&Math.abs(ndcY)<=1})}
 return Object.freeze({width,height,project,cameraAuthority:'EXTERNAL_CONVERGENCE_CAMERA'});
}
function normalizedStars(systemId,stars){if(!Array.isArray(stars))throw new TypeError('stars array required');if(stars.length>SYSTEM_LIMITS.maxStars)throw new RangeError('stellar-system star budget exceeded');const seen=new Set(),rows=stars.map((raw,index)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('star['+index+'] required');const id=sysId(raw,'star['+index+'] id');if(seen.has(id))throw new Error('duplicate stellar identity '+id);seen.add(id);return {id,raw,facts:factsOf(raw,'star['+index+']')}}).sort((a,b)=>compareId(a.id,b.id)),baseAngle=unitHash(systemId,31)*TAU,radius=8+2*Math.log1p(Math.max(1,rows.length));return Object.freeze(rows.map((row,index)=>{const explicit=optionalSysVec3(row.raw.position3d,'star '+row.id+' position3d'),angle=baseAngle+TAU*index/Math.max(1,rows.length),fallback=rows.length<=1?[0,0,0]:[Math.cos(angle)*radius,(unitHash(row.id,32)-.5)*2,Math.sin(angle)*radius],position3d=explicit||Object.freeze(fallback);return Object.freeze({...row,position3d,positionAuthority:explicit?'UPSTREAM_PRESENTATION_POSITION':'DETERMINISTIC_PRESENTATION_FALLBACK'})}))}
function planetSemiMajor(raw){const value=optionalFinite(raw?.facts?.baselineSemiMajorAxisMicroAu,'baselineSemiMajorAxisMicroAu');if(value!==null&&!(value>0))throw new RangeError('baselineSemiMajorAxisMicroAu must be positive when supplied');return value}
function normalizedPlanets(systemId,planets,starRows,{segments=96}={}){if(!Array.isArray(planets))throw new TypeError('planets array required');if(planets.length>SYSTEM_LIMITS.maxPlanets)throw new RangeError('stellar-system planet budget exceeded');const seen=new Set(starRows.map(x=>x.id)),rows=planets.map((raw,index)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('planet['+index+'] required');const id=sysId(raw,'planet['+index+'] id');if(seen.has(id))throw new Error('duplicate system entity identity '+id);seen.add(id);const facts=factsOf(raw,'planet['+index+']'),semiMajor=planetSemiMajor({facts}),parentRaw=raw.parentCanonicalEntityId??raw.parentId??facts.parentCanonicalEntityId??facts.parentId??null,parentId=parentRaw===null?null:sysId(parentRaw,'planet parent id');return {id,raw,facts,semiMajor,parentId}}).sort((a,b)=>a.semiMajor===null&&b.semiMajor!==null?1:a.semiMajor!==null&&b.semiMajor===null?-1:a.semiMajor!==null&&b.semiMajor!==null&&a.semiMajor!==b.semiMajor?a.semiMajor-b.semiMajor:compareId(a.id,b.id));rows.forEach((row,index)=>row.orderIndex=index);const starById=new Map(starRows.map(row=>[row.id,row])),planetById=new Map(rows.map(row=>[row.id,row])),resolved=new Map(),state=new Map(),baseAngle=unitHash(systemId,33)*TAU;
 function resolve(row){if(resolved.has(row.id))return resolved.get(row.id);if(state.get(row.id)===1)throw new Error('planet presentation parent cycle at '+row.id);state.set(row.id,1);let center3d=Object.freeze([0,0,0]),parentResolutionAuthority='SYSTEM_PRESENTATION_ORIGIN';if(row.parentId&&row.parentId!==systemId){if(starById.has(row.parentId)){center3d=starById.get(row.parentId).position3d;parentResolutionAuthority='PARENT_STAR_PRESENTATION_POSITION'}else if(planetById.has(row.parentId)){center3d=resolve(planetById.get(row.parentId)).position3d;parentResolutionAuthority='PARENT_BODY_PRESENTATION_POSITION'}else parentResolutionAuthority='UNRESOLVED_PARENT_SYSTEM_ORIGIN_FALLBACK'}let orbit=null,position3d,positionAuthority;if(row.semiMajor!==null){orbit=buildOrbit({id:row.id,parentId:row.parentId,facts:row.facts},{segments,center3d});position3d=orbit.presentationAnchor3d;positionAuthority=orbit.presentationAnchorAuthority}else{const radius=20+7*(row.orderIndex+1),angle=baseAngle+TAU*row.orderIndex/Math.max(1,rows.length),offset=[Math.cos(angle)*radius,(unitHash(row.id,34)-.5)*3,Math.sin(angle)*radius];position3d=sysAdd(center3d,offset);positionAuthority='DETERMINISTIC_PRESENTATION_FALLBACK_NO_ORBIT_FACTS'}const out=Object.freeze({...row,center3d,parentResolutionAuthority,orbit,position3d,positionAuthority,orderAuthority:row.semiMajor===null?'CANONICAL_ID_FALLBACK':'BASELINE_SEMI_MAJOR_AXIS'});resolved.set(row.id,out);state.set(row.id,2);return out}
 return Object.freeze(rows.map(resolve));
}
function buildSystemScene(input,{orbitSegments=96}={}){if(!input||typeof input!=='object'||Array.isArray(input))throw new TypeError('system render input required');orbitSegments=finite(orbitSegments,'orbitSegments');if(!Number.isInteger(orbitSegments)||orbitSegments<LIMITS.minSegments||orbitSegments>LIMITS.maxSegments)throw new RangeError('orbitSegments outside bounded orbit budget');const systemId=sysId(input.system,'system id'),S=requireV2('v2x04StellarAppearance'),I=requireV2('v2x04MultiStarIllumination'),B=requireV2('v2x04BodyCues'),stars=normalizedStars(systemId,input.stars??[]),planets=normalizedPlanets(systemId,input.planets??[],stars,{segments:orbitSegments}),starPresentations=Object.freeze(stars.map(row=>S.describeStar({id:row.id,facts:row.facts}))),lightStars=stars.map(row=>({canonicalEntityId:row.id,position3d:row.position3d,facts:row.facts,luminosity:row.raw.luminosity??null})),bodyPresentations=Object.freeze(planets.map(row=>{const illumination=I.buildIllumination(lightStars,{bodyPosition3d:row.position3d}),body={...row.raw,id:row.id,facts:row.facts},environment=row.raw.environment??row.facts.environment??null,visual=row.raw.visual??(row.raw.rings?{rings:row.raw.rings}:null),cues=B.bodyCues(body,{environment,visual,illumination}),occluders=row.raw.presentationOccluders??[];if(!Array.isArray(occluders))throw new TypeError('presentationOccluders must be an array when supplied');const eclipseCue=occluders.length?B.compositeEclipse(illumination,{occluders,starAngularRadiusRad:row.raw.presentationStarAngularRadiusRad??.00465}):null;return Object.freeze({canonicalEntityId:row.id,parentCanonicalEntityId:row.parentId,position3d:row.position3d,positionAuthority:row.positionAuthority,parentResolutionAuthority:row.parentResolutionAuthority,orbit:row.orbit,illumination,bodyCues:cues,eclipseCue,orderIndex:row.orderIndex,orderAuthority:row.orderAuthority})}));return Object.freeze({authority:AUTHORITY,scientificEvidence:false,systemCanonicalEntityId:systemId,stars,planets,starPresentations,bodyPresentations,planetOrder:Object.freeze(planets.map(row=>Object.freeze({canonicalEntityId:row.id,orderIndex:row.orderIndex,semiMajorAxisMicroAu:row.semiMajor,orderAuthority:row.orderAuthority}))),limitations:Object.freeze(['All positions are presentation-space coordinates.','Missing star positions and missing planet orbit facts use deterministic presentation fallbacks and are never promoted to physical positions.','Current orbital phase is never inferred.','Camera, selection, semantic scale and persistence remain external convergence authorities.'])})}
function renderSystem(input,{camera,viewport={width:1280,height:720},orbitSegments=96,approach=null}={}){const scene=buildSystemScene(input,{orbitSegments}),projection=cameraProjector(camera,viewport),projectedOrbits=[],hitTargets=[];let projectedVertices=0;for(const body of scene.bodyPresentations){if(body.orbit){const points=[];for(const vertex of body.orbit.vertices){const pixel=projection.project(vertex);if(pixel)points.push(pixel)}projectedVertices+=points.length;if(projectedVertices>SYSTEM_LIMITS.maxProjectedVertices)throw new RangeError('projected orbit vertex budget exceeded');projectedOrbits.push(Object.freeze({canonicalEntityId:body.canonicalEntityId,parentCanonicalEntityId:body.parentCanonicalEntityId,geometryAuthority:AUTHORITY,currentOrbitalPhaseAuthority:PHASE,points:Object.freeze(points)}))}}
 for(const star of scene.stars){const pixel=projection.project(star.position3d);if(!pixel)continue;const appearance=scene.starPresentations.find(x=>x.canonicalEntityId===star.id),radiusPx=Math.max(2,Math.min(48,appearance?.renderCue?.discRadiusPx??6));hitTargets.push(Object.freeze({canonicalEntityId:star.id,kind:'STAR',parentCanonicalEntityId:scene.systemCanonicalEntityId,x:pixel.x,y:pixel.y,depth:pixel.depth,visible:pixel.visible,radiusPx,selectionAuthority:'UPSTREAM_SELECTION_CONTRACT',positionAuthority:star.positionAuthority}))}
 for(const body of scene.bodyPresentations){const pixel=projection.project(body.position3d);if(!pixel)continue;hitTargets.push(Object.freeze({canonicalEntityId:body.canonicalEntityId,kind:'PLANET',parentCanonicalEntityId:body.parentCanonicalEntityId??scene.systemCanonicalEntityId,x:pixel.x,y:pixel.y,depth:pixel.depth,visible:pixel.visible,radiusPx:7,selectionAuthority:'UPSTREAM_SELECTION_CONTRACT',positionAuthority:body.positionAuthority}))}
 if(hitTargets.length>SYSTEM_LIMITS.maxHitTargets)throw new RangeError('system hit-target budget exceeded');const resourceUsage=Object.freeze({stars:scene.stars.length,planets:scene.planets.length,orbits:projectedOrbits.length,projectedVertices,hitTargets:hitTargets.length,drawPackets:projectedOrbits.length+hitTargets.length,maxStars:SYSTEM_LIMITS.maxStars,maxPlanets:SYSTEM_LIMITS.maxPlanets,maxProjectedVertices:SYSTEM_LIMITS.maxProjectedVertices,maxHitTargets:SYSTEM_LIMITS.maxHitTargets});const result={version:'ofu-v2x-04-system-provider-2',providerId:SYSTEM_PROVIDER_ID,authority:AUTHORITY,scientificEvidence:false,scene,projectedOrbits:Object.freeze(projectedOrbits),hitTargets:Object.freeze(hitTargets),planetOrder:scene.planetOrder,starPresentations:scene.starPresentations,bodyPresentations:scene.bodyPresentations,resourceUsage,cameraAuthority:projection.cameraAuthority,selectionAuthority:'UPSTREAM_SELECTION_CONTRACT',semanticScaleAuthority:'EXTERNAL_CONVERGENCE_SCALE',legacyFallbackUsed:false};if(approach)result.approach=buildSystemApproach(input,{...approach,orbitSegments});return Object.freeze(result)}
function validatePickSurface(rendered){try{if(!rendered||rendered.providerId!==SYSTEM_PROVIDER_ID||rendered.authority!==AUTHORITY||rendered.scientificEvidence!==false||rendered.legacyFallbackUsed!==false||!Array.isArray(rendered.hitTargets)||rendered.hitTargets.length>SYSTEM_LIMITS.maxHitTargets)return false;if(!rendered.resourceUsage||rendered.resourceUsage.hitTargets!==rendered.hitTargets.length||rendered.resourceUsage.maxHitTargets!==SYSTEM_LIMITS.maxHitTargets)return false;const ids=new Set();for(const target of rendered.hitTargets){if(!target||typeof target.canonicalEntityId!=='string'||!target.canonicalEntityId||ids.has(target.canonicalEntityId)||(target.kind!=='STAR'&&target.kind!=='PLANET')||target.selectionAuthority!=='UPSTREAM_SELECTION_CONTRACT'||typeof target.visible!=='boolean')return false;ids.add(target.canonicalEntityId);for(const [value,label] of [[target.x,'x'],[target.y,'y'],[target.depth,'depth'],[target.radiusPx,'radiusPx']]){const n=finite(value,'hit target '+label);if(label==='radiusPx'&&n<0)return false}}return true}catch{return false}}
function pickSystem(rendered,x,y,{maxDistancePx=18}={}){if(!validatePickSurface(rendered))throw new TypeError('valid V2X-04 rendered system required');const px=finite(x,'pick x'),py=finite(y,'pick y'),limit=finite(maxDistancePx,'maxDistancePx');if(limit<0)throw new RangeError('maxDistancePx must be non-negative');let best=null,bestDistance=Infinity;for(const target of rendered.hitTargets){if(!target.visible)continue;const d=Math.max(0,Math.hypot(target.x-px,target.y-py)-target.radiusPx);if(d<=limit&&(d<bestDistance||(d===bestDistance&&target.depth<(best?.depth??Infinity)))){best=target;bestDistance=d}}return best?Object.freeze({canonicalEntityId:best.canonicalEntityId,kind:best.kind,parentCanonicalEntityId:best.parentCanonicalEntityId,selectionIntent:'SELECT_CANONICAL_ENTITY',selectionAuthority:'UPSTREAM_SELECTION_CONTRACT',distancePx:bestDistance,providerId:SYSTEM_PROVIDER_ID}):null}
function buildSystemApproach(input,options={}){const A=requireV2('v2x04ApproachContinuity'),L=requireV2('v2x04ApproachLod'),scene=buildSystemScene(input,{orbitSegments:options.orbitSegments??96}),bodyId=sysId(options.bodyId??options.planetCanonicalEntityId,'approach body id'),body=scene.bodyPresentations.find(row=>row.canonicalEntityId===bodyId);if(!body)throw new RangeError('approach body must be a canonical planet in the rendered system');const base=A.makePacket({systemId:scene.systemCanonicalEntityId,bodyId,parentBodyId:body.parentCanonicalEntityId,startDistanceRatio:options.startDistanceRatio??5000,endDistanceRatio:options.endDistanceRatio??1.02,samples:options.samples??65,approachVector3d:options.approachVector3d??[0,0,1],surfaceTarget:options.surfaceTarget??null,referenceFrameId:options.referenceFrameId??null,scaleStateToken:options.scaleStateToken??null}),referenceRadiusPx=options.referenceRadiusPx??160,refine=L.decorate(base,{bodyCues:body.bodyCues,referenceRadiusPx,eclipseCue:body.eclipseCue}),project=L.decorate(A.reverse(base),{bodyCues:body.bodyCues,referenceRadiusPx,eclipseCue:body.eclipseCue}),roundTrip=A.roundTripWitness(base);if(!roundTrip.reversible||!L.validate(refine)||!L.validate(project))throw new Error('V2X-04 approach continuity validation failed');return Object.freeze({authority:AUTHORITY,scientificEvidence:false,systemCanonicalEntityId:scene.systemCanonicalEntityId,bodyCanonicalEntityId:bodyId,refine,project,roundTrip,selectionMutation:false,cameraStateMutation:false,legacyFallbackUsed:false})}
const SYSTEM_PROVIDER_DESCRIPTOR=Object.freeze({id:SYSTEM_PROVIDER_ID,version:'2.0.1',owner:'V2X-04',kind:'RENDER_PACKET_PROVIDER',authority:AUTHORITY,claims:Object.freeze(['system.multi-star.presentation','system.orbit.3d.presentation','system.canonical-entity-picking','planet.approach.reversible-presentation']),centralAuthoritiesOwned:Object.freeze([]),legacyFallbackPolicy:'FORBIDDEN',budget:SYSTEM_LIMITS});
O.v2x04SystemProvider=Object.freeze({VERSION:'ofu-v2x-04-system-provider-2',AUTHORITY,DESCRIPTOR:SYSTEM_PROVIDER_DESCRIPTOR,LIMITS:SYSTEM_LIMITS,buildSystemScene,render:renderSystem,validatePickSurface,pick:pickSystem,buildApproach:buildSystemApproach});
})(typeof globalThis!=='undefined'?globalThis:this);
