(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const TAU=Math.PI*2;
const AUTHORITY='PRESENTATION_ONLY';
const PHASE='UNKNOWN_NOT_CANONICAL';
const LIMITS=Object.freeze({minSegments:24,maxSegments:256,maxBodies:128,maxVertices:32896});
function finite(n,label){n=Number(n);if(!Number.isFinite(n))throw new TypeError(label+' must be finite');return n}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function idToken(id){if(typeof id==='string'&&id)return id;if(id instanceof Uint8Array)return Array.from(id,b=>b.toString(16).padStart(2,'0')).join('');if(ArrayBuffer.isView(id))return Array.from(new Uint8Array(id.buffer,id.byteOffset,id.byteLength),b=>b.toString(16).padStart(2,'0')).join('');throw new TypeError('entity id must be string or bytes')}
function rotate(x,y,inc,node,peri){const cw=Math.cos(peri),sw=Math.sin(peri),ci=Math.cos(inc),si=Math.sin(inc),cn=Math.cos(node),sn=Math.sin(node),xp=x*cw-y*sw,yp=x*sw+y*cw,yi=yp*ci,zi=yp*si;return Object.freeze([xp*cn-yi*sn,xp*sn+yi*cn,zi])}
function orientationFromFacts(facts){facts=facts||{};const inc=finite(facts.baselineInclinationMilliDeg||0,'inclination')*Math.PI/180000;const hasNode=Number.isFinite(Number(facts.longitudeAscendingNodeMilliDeg));const hasPeri=Number.isFinite(Number(facts.argumentPeriapsisMilliDeg));return Object.freeze({inclinationRad:inc,longitudeAscendingNodeRad:hasNode?Number(facts.longitudeAscendingNodeMilliDeg)*Math.PI/180000:0,argumentPeriapsisRad:hasPeri?Number(facts.argumentPeriapsisMilliDeg)*Math.PI/180000:0,orientationAuthority:hasNode&&hasPeri?'CANONICAL_PROVEN':'PARTIAL_PRESENTATION_FALLBACK',unknownFields:Object.freeze([...(hasNode?[]:['longitudeAscendingNode']),...(hasPeri?[]:['argumentPeriapsis'])])})}
function displayRadius(facts){const microAu=finite(facts.baselineSemiMajorAxisMicroAu,'baselineSemiMajorAxisMicroAu');if(!(microAu>0))throw new RangeError('positive baselineSemiMajorAxisMicroAu required');return 12+24*Math.log1p(microAu/1e6)}
function buildOrbit(body,{segments=96,center3d=[0,0,0]}={}){if(!body||!body.id||!body.facts)throw new TypeError('body envelope with id and facts required');segments=Math.trunc(Number(segments));if(!(segments>=LIMITS.minSegments&&segments<=LIMITS.maxSegments))throw new RangeError('segments outside bounded orbit budget');const center=center3d.map((v,i)=>finite(v,'center3d['+i+']'));if(center.length!==3)throw new RangeError('center3d must contain 3 coordinates');const a=displayRadius(body.facts),e=clamp(finite(body.facts.baselineEccentricityPpm||0,'eccentricity')/1e6,0,.95),b=a*Math.sqrt(1-e*e),o=orientationFromFacts(body.facts),vertices=[];for(let i=0;i<=segments;i++){const E=TAU*i/segments,x=a*(Math.cos(E)-e),y=b*Math.sin(E),p=rotate(x,y,o.inclinationRad,o.longitudeAscendingNodeRad,o.argumentPeriapsisRad);vertices.push(Object.freeze([p[0]+center[0],p[1]+center[1],p[2]+center[2]]))}return Object.freeze({canonicalEntityId:idToken(body.id),parentCanonicalEntityId:body.parentId? idToken(body.parentId):null,vertices:Object.freeze(vertices),center3d:Object.freeze(center),geometryAuthority:AUTHORITY,inputFactsAuthority:'CANONICAL_PROVEN_WHERE_PRESENT',orientation:o,currentOrbitalPhaseAuthority:PHASE,scaleSemantics:'SCHEMATIC_LOG_AU',limitations:Object.freeze(['No current orbital phase is invented.','Missing node/periapsis remain explicitly non-canonical fallback orientation.','Display radius is logarithmically compressed presentation geometry.'])})}
function resolveHierarchy(bodies,{segments=96,rootCenter3d=[0,0,0]}={}){if(!Array.isArray(bodies))throw new TypeError('bodies array required');if(bodies.length>LIMITS.maxBodies)throw new RangeError('body budget exceeded');const byId=new Map(),ordered=[];for(const body of bodies){const id=idToken(body.id);if(byId.has(id))throw new Error('duplicate body id '+id);byId.set(id,body)}
const state=new Map(),centers=new Map();function visit(body){const id=idToken(body.id),s=state.get(id);if(s===2)return;if(s===1)throw new Error('orbital hierarchy cycle at '+id);state.set(id,1);let center=rootCenter3d;if(body.parentId){const pid=idToken(body.parentId),parent=byId.get(pid);if(!parent)throw new Error('missing orbital parent '+pid);visit(parent);center=centers.get(pid)||rootCenter3d}const orbit=buildOrbit(body,{segments,center3d:center});const anchor=orbit.vertices[0];centers.set(id,anchor);ordered.push(Object.freeze({id,parentId:body.parentId?idToken(body.parentId):null,orbit,anchor3d:anchor,kind:body.kind||'BODY'}));state.set(id,2)}for(const body of bodies)visit(body);const vertexCount=ordered.reduce((n,x)=>n+x.orbit.vertices.length,0);if(vertexCount>LIMITS.maxVertices)throw new RangeError('orbit vertex budget exceeded');return Object.freeze({authority:AUTHORITY,currentOrbitalPhaseAuthority:PHASE,nodes:Object.freeze(ordered),resourceUsage:Object.freeze({bodies:ordered.length,vertices:vertexCount}),limits:LIMITS})}
O.v2x04Orbit3D=Object.freeze({VERSION:'ofu-v2x-04-orbit-3d-1',AUTHORITY,PHASE,LIMITS,idToken,orientationFromFacts,displayRadius,buildOrbit,resolveHierarchy});
})(typeof globalThis!=='undefined'?globalThis:this);
