(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const TAU=Math.PI*2;
const AUTHORITY='PRESENTATION_ONLY';
const PHASE='UNKNOWN_NOT_CANONICAL';
const LIMITS=Object.freeze({minSegments:24,maxSegments:256,maxBodies:128,maxVertices:32896,maxPresentationEccentricity:.95});
function finite(value,label){if(value===null||value===undefined||typeof value==='boolean'||(typeof value==='string'&&value.trim()===''))throw new TypeError(label+' must be finite');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite');return n}
function optionalFinite(value,label){if(value===null||value===undefined||(typeof value==='string'&&value.trim()===''))return null;if(typeof value==='boolean')throw new TypeError(label+' must be finite when supplied');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite when supplied');return n}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function idToken(id){if(typeof id==='string'&&id)return id;if(id instanceof Uint8Array)return Array.from(id,b=>b.toString(16).padStart(2,'0')).join('');if(ArrayBuffer.isView(id))return Array.from(new Uint8Array(id.buffer,id.byteOffset,id.byteLength),b=>b.toString(16).padStart(2,'0')).join('');throw new TypeError('entity id must be non-empty string or bytes')}
function stableHash(text){let h=2166136261>>>0;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function unitHash(text,salt){let x=(stableHash(text)^Math.imul(salt+1,0x9e3779b1))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/4294967296}
function rotate(x,y,inc,node,peri){const cw=Math.cos(peri),sw=Math.sin(peri),ci=Math.cos(inc),si=Math.sin(inc),cn=Math.cos(node),sn=Math.sin(node),xp=x*cw-y*sw,yp=x*sw+y*cw,yi=yp*ci,zi=yp*si;return Object.freeze([xp*cn-yi*sn,xp*sn+yi*cn,zi])}
function orientationFromFacts(facts,entityId='presentation-orbit'){
 facts=facts||{};const token=idToken(entityId),incValue=optionalFinite(facts.baselineInclinationMilliDeg,'baselineInclinationMilliDeg'),nodeValue=optionalFinite(facts.longitudeAscendingNodeMilliDeg,'longitudeAscendingNodeMilliDeg'),periValue=optionalFinite(facts.argumentPeriapsisMilliDeg,'argumentPeriapsisMilliDeg'),unknownFields=[];
 if(incValue===null)unknownFields.push('inclination');if(nodeValue===null)unknownFields.push('longitudeAscendingNode');if(periValue===null)unknownFields.push('argumentPeriapsis');
 const inc=(incValue===null?0:incValue)*Math.PI/180000,node=nodeValue===null?unitHash(token,0)*TAU:nodeValue*Math.PI/180000,peri=periValue===null?unitHash(token,1)*TAU:periValue*Math.PI/180000;
 return Object.freeze({inclinationRad:inc,longitudeAscendingNodeRad:node,argumentPeriapsisRad:peri,orientationAuthority:unknownFields.length?'PARTIAL_PRESENTATION_FALLBACK':'CANONICAL_PROVEN',unknownFields:Object.freeze(unknownFields),fallbackDeterministic:unknownFields.length>0});
}
function displayRadius(facts){if(!facts||typeof facts!=='object')throw new TypeError('orbit facts required');const microAu=finite(facts.baselineSemiMajorAxisMicroAu,'baselineSemiMajorAxisMicroAu');if(!(microAu>0))throw new RangeError('positive baselineSemiMajorAxisMicroAu required');return 12+24*Math.log1p(microAu/1e6)}
function shapeFromFacts(facts){const a=displayRadius(facts),rawPpm=optionalFinite(facts.baselineEccentricityPpm,'baselineEccentricityPpm');if(rawPpm!==null&&(rawPpm<0||rawPpm>=1e6))throw new RangeError('baselineEccentricityPpm must be in [0,1000000) when supplied');const rawE=(rawPpm===null?0:rawPpm)/1e6,e=clamp(rawE,0,LIMITS.maxPresentationEccentricity),b=a*Math.sqrt(1-e*e);return Object.freeze({semiMajorDisplayUnits:a,semiMinorDisplayUnits:b,inputEccentricityPpm:rawPpm,effectivePresentationEccentricity:e,eccentricityAuthority:rawPpm===null?'PRESENTATION_FALLBACK_ZERO':'CANONICAL_PROVEN_INPUT',eccentricityClampedForPresentation:rawPpm!==null&&rawE>LIMITS.maxPresentationEccentricity})}
function orbitPoint(shape,orientation,center3d,eccentricAnomaly){const E=finite(eccentricAnomaly,'eccentricAnomaly'),x=shape.semiMajorDisplayUnits*(Math.cos(E)-shape.effectivePresentationEccentricity),y=shape.semiMinorDisplayUnits*Math.sin(E),p=rotate(x,y,orientation.inclinationRad,orientation.longitudeAscendingNodeRad,orientation.argumentPeriapsisRad);return Object.freeze([p[0]+center3d[0],p[1]+center3d[1],p[2]+center3d[2]])}
function orbitPointFromAnomaly(body,orientation,center3d,eccentricAnomaly){if(!body||!body.facts)throw new TypeError('body facts required');if(!Array.isArray(center3d)||center3d.length!==3)throw new TypeError('center3d must be vec3');const center=center3d.map((v,i)=>finite(v,'center3d['+i+']'));return orbitPoint(shapeFromFacts(body.facts),orientation,center,eccentricAnomaly)}
function presentationAnchorAnomaly(body){if(!body)throw new TypeError('body required');return unitHash(idToken(body.id),2)*TAU}
function buildOrbit(body,{segments=96,center3d=[0,0,0]}={}){
 if(!body||body.id===undefined||body.id===null||!body.facts)throw new TypeError('body envelope with id and facts required');segments=finite(segments,'segments');if(!Number.isInteger(segments)||segments<LIMITS.minSegments||segments>LIMITS.maxSegments)throw new RangeError('segments outside bounded orbit budget');if(!Array.isArray(center3d)||center3d.length!==3)throw new TypeError('center3d must be vec3');const center=center3d.map((v,i)=>finite(v,'center3d['+i+']')),canonicalEntityId=idToken(body.id),parentCanonicalEntityId=body.parentId===undefined||body.parentId===null?null:idToken(body.parentId),orientation=orientationFromFacts(body.facts,body.id),shape=shapeFromFacts(body.facts),vertices=[];
 for(let i=0;i<segments;i++)vertices.push(orbitPoint(shape,orientation,center,TAU*i/segments));vertices.push(vertices[0]);const anchorAnomaly=presentationAnchorAnomaly(body),presentationAnchor3d=orbitPoint(shape,orientation,center,anchorAnomaly);
 return Object.freeze({canonicalEntityId,parentCanonicalEntityId,vertices:Object.freeze(vertices),center3d:Object.freeze(center),presentationAnchor3d,presentationAnchorAnomalyRad:anchorAnomaly,presentationAnchorAuthority:AUTHORITY,geometryAuthority:AUTHORITY,inputFactsAuthority:'CANONICAL_PROVEN_WHERE_PRESENT',orientation,shape,currentOrbitalPhaseAuthority:PHASE,scaleSemantics:'SCHEMATIC_LOG_AU',limitations:Object.freeze(['No current orbital phase is invented.','Missing orientation facts use deterministic presentation fallbacks and remain explicitly non-canonical.','The identity-derived presentation anchor is not a current ephemeris position.','Display radius is logarithmically compressed presentation geometry.','Very high but bound eccentricity may be visually clamped and is disclosed by eccentricityClampedForPresentation.','The closing orbit vertex reuses the first vertex exactly to avoid presentation seam drift.'])});
}
function resolveHierarchy(bodies,{segments=96,rootCenter3d=[0,0,0]}={}){
 if(!Array.isArray(bodies))throw new TypeError('bodies array required');if(bodies.length>LIMITS.maxBodies)throw new RangeError('body budget exceeded');if(!Array.isArray(rootCenter3d)||rootCenter3d.length!==3)throw new TypeError('rootCenter3d must be vec3');const rootCenter=Object.freeze(rootCenter3d.map((v,i)=>finite(v,'rootCenter3d['+i+']'))),byId=new Map(),ordered=[];
 for(const body of bodies){if(!body||body.id===undefined||body.id===null)throw new TypeError('body id required');const id=idToken(body.id);if(byId.has(id))throw new Error('duplicate body id '+id);byId.set(id,body)}
 const state=new Map(),centers=new Map();function visit(body){const id=idToken(body.id),s=state.get(id);if(s===2)return;if(s===1)throw new Error('orbital hierarchy cycle at '+id);state.set(id,1);let center=rootCenter;let parentId=null;if(body.parentId!==undefined&&body.parentId!==null){parentId=idToken(body.parentId);const parent=byId.get(parentId);if(!parent)throw new Error('missing orbital parent '+parentId);visit(parent);center=centers.get(parentId)||rootCenter}const orbit=buildOrbit(body,{segments,center3d:center}),anchor=orbit.presentationAnchor3d;centers.set(id,anchor);ordered.push(Object.freeze({id,parentId,orbit,anchor3d:anchor,anchorAuthority:AUTHORITY,kind:body.kind||'BODY'}));state.set(id,2)}
 for(const body of bodies)visit(body);const vertexCount=ordered.reduce((n,x)=>n+x.orbit.vertices.length,0);if(vertexCount>LIMITS.maxVertices)throw new RangeError('orbit vertex budget exceeded');return Object.freeze({authority:AUTHORITY,currentOrbitalPhaseAuthority:PHASE,nodes:Object.freeze(ordered),resourceUsage:Object.freeze({bodies:ordered.length,vertices:vertexCount}),limits:LIMITS});
}
O.v2x04Orbit3D=Object.freeze({VERSION:'ofu-v2x-04-orbit-3d-3',AUTHORITY,PHASE,LIMITS,idToken,stableHash,unitHash,orientationFromFacts,displayRadius,shapeFromFacts,orbitPointFromAnomaly,presentationAnchorAnomaly,buildOrbit,resolveHierarchy});
})(typeof globalThis!=='undefined'?globalThis:this);
