import { assertRecord, boundedArray, boundedAscii, identifier, int, mulDivFloor, nonNegativeInt, ppm, stableFingerprint64, sumSafe } from '../reference/bounded-math.mjs';
export const INDIVIDUAL_AUTHORITY='RESEARCH_ONLY_MODEL_DERIVED_SIMULATION';
export const INDIVIDUAL_LIMITS=Object.freeze({ageBins:256,maxPopulation:10_000_000_000,materializedPersons:512,kinshipLinks:1024,migrationEntries:256});
export function validateCohorts(state){assertRecord(state,'state');boundedArray(state.cohorts,'cohorts',INDIVIDUAL_LIMITS.ageBins);if(!state.cohorts.length)throw new Error('at least one cohort is required');state.cohorts.forEach((v,a)=>nonNegativeInt(v,`cohorts[${a}]`,INDIVIDUAL_LIMITS.maxPopulation));return true;}
export function stepCohorts(state,rates){validateCohorts(state);assertRecord(rates,'rates');boundedArray(rates.mortalityPpm,'mortalityPpm',INDIVIDUAL_LIMITS.ageBins);boundedArray(rates.fertilityPpm,'fertilityPpm',INDIVIDUAL_LIMITS.ageBins);if(rates.mortalityPpm.length!==state.cohorts.length||rates.fertilityPpm.length!==state.cohorts.length)throw new Error('rate vectors must match cohort vector length');const migration=rates.netMigration??Array(state.cohorts.length).fill(0);boundedArray(migration,'netMigration',INDIVIDUAL_LIMITS.migrationEntries);if(migration.length!==state.cohorts.length)throw new Error('migration vector must match cohort vector length');let births=0;const deathsByAge=[],survivors=[];for(let a=0;a<state.cohorts.length;a++){const p=state.cohorts[a],d=mulDivFloor(p,ppm(rates.mortalityPpm[a]),1_000_000),f=mulDivFloor(p,ppm(rates.fertilityPpm[a]),1_000_000);deathsByAge.push(d);survivors.push(p-d);births+=f;if(!Number.isSafeInteger(births)||births>INDIVIDUAL_LIMITS.maxPopulation)throw new RangeError('births overflow');}const next=Array(state.cohorts.length).fill(0);next[0]=births;for(let a=1;a<next.length-1;a++)next[a]=survivors[a-1];if(next.length>1)next[next.length-1]=survivors[next.length-2]+survivors[next.length-1];let netMigration=0;for(let a=0;a<next.length;a++){const d=int(migration[a]??0,`migration[${a}]`,-INDIVIDUAL_LIMITS.maxPopulation,INDIVIDUAL_LIMITS.maxPopulation);if(next[a]+d<0||next[a]+d>INDIVIDUAL_LIMITS.maxPopulation)throw new RangeError(`migration leaves cohort ${a} outside bounds`);next[a]+=d;netMigration+=d;}const opening=sumSafe(state.cohorts),deaths=sumSafe(deathsByAge),closing=sumSafe(next);if(opening+births-deaths+netMigration!==closing)throw new Error('demographic balancing equation failed');return Object.freeze({authority:INDIVIDUAL_AUTHORITY,cohorts:Object.freeze(next),evidence:Object.freeze({opening,births,deaths,netMigration,closing}),nonClaim:'Scenario accounting, not a forecast of a real population.'});}
function cohortStateFingerprint(state){const vector=state.cohorts.join(',');return stableFingerprint64([vector],'cohortState',4096);}
export function materializePersons(state,request){validateCohorts(state);assertRecord(request,'request');const age=int(request.age,'age',0,state.cohorts.length-1),count=nonNegativeInt(request.count,'count',INDIVIDUAL_LIMITS.materializedPersons);if(count>state.cohorts[age])throw new Error('cannot materialize more persons than cohort stock');const context=boundedAscii(request.contextKey??'default','contextKey',128),requestClass=boundedAscii(request.requestClass??'sample','requestClass',64),epoch=nonNegativeInt(request.epoch??0,'epoch',1_000_000_000),stateFingerprint=cohortStateFingerprint(state),requestFingerprint=stableFingerprint64([context,String(epoch),String(age),requestClass,stateFingerprint],'materializationRequest',256),persons=[];for(let i=0;i<count;i++){const id=`rp:${requestFingerprint}:${i}`;persons.push(Object.freeze({id,age,slot:i,stateFingerprint,requestFingerprint,identityAuthority:'RESEARCH_EPHEMERAL_ID_NOT_CANONICAL_PERSON_ID',psychologicalProfile:null,predictedBiography:null}));}return Object.freeze({authority:INDIVIDUAL_AUTHORITY,stateFingerprint,requestFingerprint,persons:Object.freeze(persons),adaptiveResolution:true,collisionClaim:'NONCRYPTOGRAPHIC_64_BIT_RESEARCH_FINGERPRINT_VERIFY_BATCH_METADATA_ON_MATCH'});}
export function reconcileMaterialization(cohorts,persons){validateCohorts({cohorts});boundedArray(persons,'persons',INDIVIDUAL_LIMITS.materializedPersons);const expectedFingerprint=cohortStateFingerprint({cohorts}),counts=Array(cohorts.length).fill(0),ids=new Set();for(const p of persons){assertRecord(p,'person');const id=identifier(p.id,'person.id');if(ids.has(id))throw new Error('duplicate person');ids.add(id);if(p.stateFingerprint!==expectedFingerprint)throw new Error('person state fingerprint mismatch');const a=int(p.age,'age',0,cohorts.length-1);counts[a]++;if(counts[a]>cohorts[a])throw new Error('materialized persons exceed cohort stock');}return Object.freeze({authority:INDIVIDUAL_AUTHORITY,stateFingerprint:expectedFingerprint,representedByAge:Object.freeze(counts),omittedPopulation:sumSafe(cohorts.map((c,a)=>c-counts[a]))});}
export function createKinshipWindow({maxPersons=256,maxLinks=512}={}){return{authority:INDIVIDUAL_AUTHORITY,maxPersons:nonNegativeInt(maxPersons,'maxPersons',512),maxLinks:nonNegativeInt(maxLinks,'maxLinks',1024),persons:[],links:[],compacted:{persons:0,links:0}};}
function compact(w){while(w.persons.length>w.maxPersons){const v=w.persons.shift();w.compacted.persons++;w.links=w.links.filter(l=>{if(l.parentId===v.id||l.childId===v.id){w.compacted.links++;return false;}return true;});}while(w.links.length>w.maxLinks){w.links.shift();w.compacted.links++;}}
export function retainPerson(w,p){assertRecord(p,'person');const id=identifier(p.id,'person.id');const age=p.age==null?null:nonNegativeInt(p.age,'person.age',1_000_000);if(!w.persons.some(x=>x.id===id))w.persons.push({id,age});compact(w);return w;}
function cycle(w,parent,child){const q=[child],seen=new Set();while(q.length){const x=q.pop();if(x===parent)return true;if(seen.has(x))continue;seen.add(x);for(const l of w.links)if(l.parentId===x)q.push(l.childId);}return false;}
export function addParentChild(w,parentId,childId){identifier(parentId,'parentId');identifier(childId,'childId');if(parentId===childId)throw new Error('self-parent invalid');if(!w.persons.some(p=>p.id===parentId)||!w.persons.some(p=>p.id===childId))throw new Error('both persons must be retained');if(cycle(w,parentId,childId))throw new Error('kinship cycle');if(!w.links.some(l=>l.parentId===parentId&&l.childId===childId))w.links.push({parentId,childId});compact(w);return w;}
export function kinshipSnapshot(w){return Object.freeze({authority:INDIVIDUAL_AUTHORITY,retainedPersons:w.persons.length,retainedLinks:w.links.length,compacted:Object.freeze({...w.compacted}),exactBeyondWindow:false});}
