import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';

globalThis.OFU={};
for(const f of[
  'src/kernel/sha256.js','src/extensions/contracts.js','src/runtime/v2x-01-contracts.js',
  'src/simulation/materialization/cache-key.js','src/runtime/scheduling/adaptive-scheduler.js',
  'src/runtime/resources/resource-ledger.js','src/runtime/workers/worker-executor.js',
  'src/simulation/materialization/materialization-runtime.js'
])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});

const O=globalThis.OFU,h=x=>crypto.createHash('sha256').update(x).digest('hex');
const rt=O.v2x01MaterializationRuntime.create({budgets:{active:3,queue:24,cacheEntries:12,materializations:12,cpuEstimateBytes:2048,gpuEstimateBytes:2048,heapBytes:1048576,entities:64,operations:8192,transferBytes:4096,taskBytes:65536}}),scaleLadder=['universe','galaxy','region','stellar-neighborhood','system','orbit','planet','global','regional','local','human','microscopic'];
for(const d of scaleLadder)rt.registerMaterializer({providerId:'provider.'+d,domain:d,modelVersion:'1.0.0',representationVersion:'1.0.0',async load(q){return{identity:q.durable.identity,semanticDigest:q.semanticDigest,state:q.targetState,cpuEstimateBytes:48,gpuEstimateBytes:q.targetState==='WARM'?0:48,entities:1,operations:8,transferBytes:2,value:{d}}}});
const ladderPath=[...scaleLadder,...scaleLadder.slice(0,-1).reverse()];
const adaptiveReq=(d,id,step)=>{const signals={visible:true,selected:d==='human'&&step%17===0,scaleRelevancePpm:step%5===0?100000:650000,causalRelevancePpm:d==='human'?800000:50000},decision=O.v2x01Contracts.adaptiveState(signals),gpu=decision.state==='WARM'||decision.state==='COLD'?0:64;return{durable:{identity:{providerId:'provider.'+d,entityId:h(id),representationId:'primary'},commitmentDigest:h('c:'+id),historyDigest:h('history')},taskClass:decision.state==='IMMEDIATE'?'INTERACTION':'REFINE',signals,semantic:{d,id,step},presentation:{},estimate:{cpuEstimateBytes:64,gpuEstimateBytes:gpu,entities:1,operations:16,transferBytes:4}}};
let ladderSteps=0;
for(let journey=0;journey<120;journey++)for(let step=0;step<ladderPath.length;step++){const out=await rt.requestAdaptive(adaptiveReq(ladderPath[step],journey+':'+step,step+journey));assert(['WARM','HOT','IMMEDIATE'].includes(out.targetState));ladderSteps++;if(ladderSteps%100===0){const p=rt.runtimePacket();assert.equal(p.authority,'MEASURED_RUNTIME_EVIDENCE');assert(p.workingSet.entries<=12);assert(p.scheduler.current.queued<=24);assert(p.resources.used.cpuEstimateBytes+p.resources.reserved.cpuEstimateBytes<=2048);assert(p.resources.used.gpuEstimateBytes+p.resources.reserved.gpuEstimateBytes<=2048)}}
const serial=await rt.drain();assert.equal(ladderSteps,120*ladderPath.length);assert(serial.workingSet.entries<=12);assert(serial.resources.peak.cpuEstimateBytes<=2048);assert(serial.resources.peak.gpuEstimateBytes<=2048);assert(serial.scheduler.metrics.peakQueued<=24);assert.equal(serial.scheduler.current.admissions,0);assert(serial.scheduler.metrics.peakAdmissions<=1);assert(serial.metrics.evictions>0);assert.equal(serial.metrics.adaptiveDecisions,ladderSteps);assert(serial.metrics.adaptiveByState.WARM>0);assert(serial.metrics.adaptiveByState.HOT>0);assert(serial.metrics.adaptiveByState.IMMEDIATE>0);for(const d of scaleLadder)assert(serial.scheduler.metrics.startedByWorkload[d]>0,'missing workload '+d);

// Sustained same-class terrain saturation cannot starve life/civilization/matter domains.
const domainScheduler=O.v2x01AdaptiveScheduler.create({budgets:{active:1,queue:64}});let releaseDomainGate;const domainGate=domainScheduler.schedule({id:'soak.domain.gate',taskClass:'REFINE',state:'HOT',workloadDomain:'terrain',run:()=>new Promise(r=>{releaseDomainGate=r})});await new Promise(r=>setTimeout(r,0));const domainOrder=[],domainPromises=[];
for(let i=0;i<48;i++)domainPromises.push(domainScheduler.schedule({id:'soak.terrain.'+i,taskClass:'REFINE',state:'HOT',workloadDomain:'terrain',run:async()=>{domainOrder.push('terrain')}}).promise);
for(const domain of ['life','civilization','matter'])for(let i=0;i<4;i++)domainPromises.push(domainScheduler.schedule({id:'soak.'+domain+'.'+i,taskClass:'REFINE',state:'WARM',workloadDomain:domain,run:async()=>{domainOrder.push(domain)}}).promise);
releaseDomainGate();await domainGate.promise;await Promise.all(domainPromises);const domainSoak=await domainScheduler.drain();for(const domain of ['life','civilization','matter'])assert(domainOrder.indexOf(domain)>=0&&domainOrder.indexOf(domain)<=2,'sustained '+domain+' starvation');assert.equal(domainSoak.metrics.startedByWorkload.terrain,49);for(const domain of ['life','civilization','matter'])assert.equal(domainSoak.metrics.startedByWorkload[domain],4);

// Deterministic concurrent churn: supersession, cancellation, context loss and pressure must plateau under the same finite accounting rules.
let seed=0x5eed1234,releases=0,fulfilled=0,rejected=0;const rnd=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);
const cb={active:4,queue:32,cacheEntries:8,materializations:8,cpuEstimateBytes:2048,gpuEstimateBytes:2048,heapBytes:1048576,entities:64,operations:8192,syncFallbackOperations:64,transferBytes:4096,taskBytes:65536},churn=O.v2x01MaterializationRuntime.create({workerExecutor:false,budgets:cb});
churn.registerMaterializer({providerId:'provider.churn',domain:'churn',modelVersion:'1.0.0',representationVersion:'1.0.0',async load(q,signal){const delay=Math.floor(rnd()*3);if(delay)await new Promise((resolve,reject)=>{const timer=setTimeout(resolve,delay);signal?.addEventListener?.('abort',()=>{clearTimeout(timer);reject(signal.reason)},{once:true})});const warm=q.targetState==='WARM';return{identity:q.durable.identity,semanticDigest:q.semanticDigest,state:q.targetState,cpuEstimateBytes:16,gpuEstimateBytes:warm?0:16,entities:1,operations:4,transferBytes:1,value:{n:q.semantic.n}}},release(){releases++}});
const churnReq=(round,slot)=>{const idx=Math.floor(rnd()*16),state=rnd()<.28?'WARM':'HOT',taskClass=state==='WARM'&&rnd()<.4?'PREFETCH':(rnd()<.12?'RENDER_PREP':'REFINE');return{durable:{identity:{providerId:'provider.churn',entityId:h('churn:'+idx),representationId:'primary'},commitmentDigest:h('churn-c:'+round+':'+slot),historyDigest:h('history')},targetState:state,taskClass,semantic:{n:round*10+slot},presentation:{},estimate:{cpuEstimateBytes:24,gpuEstimateBytes:state==='WARM'?0:24,entities:1,operations:8,transferBytes:2}}};
for(let round=0;round<200;round++){
  const results=await Promise.allSettled(Array.from({length:6},(_,slot)=>churn.request(churnReq(round,slot))));for(const result of results)result.status==='fulfilled'?fulfilled++:rejected++;
  if(round%17===0)churn.handleContextLoss();if(round%19===0)churn.handleMemoryPressure('MODERATE');if(round%53===0)churn.handleMemoryPressure('CRITICAL');
  if(round%20===0){const s=churn.snapshot(),total=k=>s.resources.used[k]+s.resources.reserved[k];assert(s.workingSet.entries<=cb.cacheEntries);assert(s.scheduler.current.active<=cb.active);assert(s.scheduler.current.queued<=cb.queue);for(const k of ['cpuEstimateBytes','gpuEstimateBytes','entities','operations','transferBytes'])assert(total(k)<=cb[k]);assert.equal(s.workingSet.quarantined,0);assert.equal(s.workingSet.detached,0)}
}
await churn.drain();churn.handleMemoryPressure('CRITICAL');const concurrent=await churn.drain();for(const k of ['cpuEstimateBytes','gpuEstimateBytes','entities','operations','transferBytes']){assert.equal(concurrent.resources.reserved[k],0);assert.equal(concurrent.resources.used[k],0)}assert.equal(concurrent.workingSet.entries,0);assert.equal(concurrent.workingSet.active,0);assert.equal(concurrent.workingSet.quarantined,0);assert.equal(concurrent.workingSet.detached,0);assert.equal(concurrent.scheduler.current.admissions,0);assert(concurrent.scheduler.metrics.peakAdmissions<=cb.queue);assert(concurrent.scheduler.metrics.peakActive<=cb.active);assert(concurrent.resources.peak.cpuEstimateBytes<=cb.cpuEstimateBytes);assert(concurrent.resources.peak.gpuEstimateBytes<=cb.gpuEstimateBytes);assert.equal(fulfilled+rejected,1200);assert.equal(releases,concurrent.metrics.materializations);

// Saturated scheduler + tight resource pressure: backpressure must be discovered before unrelated cache/resource eviction and all admission tokens must roll back or commit exactly once.
let pressureSeed=0x0badcafe,pressureReleases=0,pressureFulfilled=0,pressureRejected=0,pressureBackpressure=0;const pressureRnd=()=>((pressureSeed=(Math.imul(pressureSeed,1103515245)+12345)>>>0)/2**32),pb={active:2,queue:3,cacheEntries:2,materializations:2,cpuEstimateBytes:100,gpuEstimateBytes:100,heapBytes:1048576,entities:6,operations:100,syncFallbackOperations:20,transferBytes:100,taskBytes:65536},pressureRt=O.v2x01MaterializationRuntime.create({workerExecutor:false,budgets:pb});
pressureRt.registerMaterializer({providerId:'provider.pressure',domain:'pressure',modelVersion:'1.0.0',representationVersion:'1.0.0',async load(q,signal){await new Promise((resolve,reject)=>{const timer=setTimeout(resolve,1+Math.floor(pressureRnd()*3));signal.addEventListener('abort',()=>{clearTimeout(timer);reject(signal.reason)},{once:true})});return{identity:q.durable.identity,semanticDigest:q.semanticDigest,state:q.targetState,cpuEstimateBytes:20,gpuEstimateBytes:q.targetState==='WARM'?0:20,entities:1,operations:4,transferBytes:1,value:{n:q.semantic.n}}},release(){pressureReleases++}});
const pressureReq=(round,slot)=>{const idx=Math.floor(pressureRnd()*7),state=pressureRnd()<.3?'WARM':(pressureRnd()<.04?'IMMEDIATE':'HOT'),taskClass=state==='IMMEDIATE'?'INTERACTION':(state==='WARM'&&pressureRnd()<.5?'PREFETCH':'REFINE');return{durable:{identity:{providerId:'provider.pressure',entityId:h('pressure:'+idx),representationId:'primary'},commitmentDigest:h('pressure-c:'+round+':'+slot),historyDigest:h('history')},targetState:state,taskClass,semantic:{n:round*10+slot},presentation:{},estimate:{cpuEstimateBytes:30,gpuEstimateBytes:state==='WARM'?0:30,entities:1,operations:8,transferBytes:2}}};
for(let round=0;round<150;round++){
  const results=await Promise.allSettled(Array.from({length:8},(_,slot)=>pressureRt.request(pressureReq(round,slot))));for(const result of results){if(result.status==='fulfilled')pressureFulfilled++;else{pressureRejected++;if(result.reason?.code==='BACKPRESSURE')pressureBackpressure++}}
  if(round%31===0)pressureRt.handleContextLoss();if(round%37===0)pressureRt.handleMemoryPressure('MODERATE');const s=pressureRt.snapshot(),total=k=>s.resources.used[k]+s.resources.reserved[k];assert(s.scheduler.current.active<=pb.active);assert(s.scheduler.current.queued+s.scheduler.current.admissions<=pb.queue);assert(s.scheduler.current.jobs+s.scheduler.current.admissions<=pb.active+pb.queue);assert.equal(s.scheduler.current.admissions,0);for(const k of ['cpuEstimateBytes','gpuEstimateBytes','entities','operations','transferBytes'])assert(total(k)<=pb[k]);assert.equal(s.workingSet.quarantined,0);assert.equal(s.workingSet.detached,0)
}
pressureRt.handleMemoryPressure('CRITICAL');const admissionPressure=await pressureRt.drain();for(const k of ['cpuEstimateBytes','gpuEstimateBytes','entities','operations','transferBytes']){assert.equal(admissionPressure.resources.reserved[k],0);assert.equal(admissionPressure.resources.used[k],0)}assert.equal(admissionPressure.scheduler.current.admissions,0);assert.equal(admissionPressure.workingSet.entries,0);assert.equal(admissionPressure.workingSet.active,0);assert.equal(admissionPressure.workingSet.quarantined,0);assert.equal(admissionPressure.workingSet.detached,0);assert.equal(pressureFulfilled+pressureRejected,1200);assert(pressureBackpressure>0);assert.equal(pressureReleases,admissionPressure.metrics.materializations);assert.equal(admissionPressure.scheduler.metrics.admissionsReserved,admissionPressure.scheduler.metrics.admissionsConsumed+admissionPressure.scheduler.metrics.admissionsReleased);assert(admissionPressure.resources.peak.cpuEstimateBytes<=pb.cpuEstimateBytes);assert(admissionPressure.resources.peak.gpuEstimateBytes<=pb.gpuEstimateBytes);

// Repeated streaming must stay within per-run transfer ceilings and preserve strict one-at-a-time consumer backpressure.
const streamSoakExecutor=O.v2x01WorkerExecutor.create({maxChunkBytes:128,maxStreamBytes:4096,maxStreamChunks:64,timeoutMs:1000});streamSoakExecutor.register({id:'worker.stream-soak',version:'1.0.0',direct:async()=>({ok:true}),directStream:async function*(q){for(let i=0;i<32;i++)yield{run:q.run,index:i};return{run:q.run,done:true}}});let streamCallbacks=0,peakStreamCallbacks=0,streamSoakBytes=0;for(let run=0;run<200;run++){const result=await streamSoakExecutor.executeStream({handlerId:'worker.stream-soak',payload:{run},preferWorker:false,onChunk:async()=>{streamCallbacks++;peakStreamCallbacks=Math.max(peakStreamCallbacks,streamCallbacks);await Promise.resolve();streamCallbacks--}});assert.equal(result.mode,'STREAM_FALLBACK');assert.equal(result.chunks,32);assert(result.bytes<=4096);streamSoakBytes+=result.bytes}const streamingSoak=streamSoakExecutor.snapshot();assert.equal(peakStreamCallbacks,1);assert.equal(streamingSoak.metrics.streamFallbackRuns,200);assert.equal(streamingSoak.metrics.streamChunks,6400);assert.equal(streamingSoak.metrics.streamAcks,6400);assert.equal(streamingSoak.metrics.streamFailures,0);assert.equal(streamingSoak.metrics.streamBytes,streamSoakBytes);assert(streamingSoak.metrics.peakStreamBytes<=4096);

console.log(JSON.stringify({status:'PASS',oracle:'V2X01_LONG_RESOURCE_PLATEAU',generation:'V2_RUNTIME_2',scaleLadder,journeys:120,ladderSteps,domainFairness:{firstStarts:domainOrder.slice(0,12),metrics:domainSoak.metrics},concurrentRequests:1200,concurrentFulfilled:fulfilled,concurrentRejected:rejected,pressureRequests:1200,pressureFulfilled,pressureRejected,pressureBackpressure,streamingSoak:{runs:200,chunks:6400,peakCallbacks:peakStreamCallbacks,snapshot:streamingSoak},serial,concurrent,admissionPressure}));
