(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,Base=O.v1ExplorationAddressSpace,A=O.v1Astronomy;
if(!V||!Base||!A)throw new Error('v1 exploration interaction requires address space and astronomy');
function sectorCompatibility(){
 const bi=v=>BigInt(v),fields=['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ'];
 const key=(galaxy,x,y,z)=>Object.freeze({galaxyX:bi(galaxy.canonicalKey.galaxyX),galaxyY:bi(galaxy.canonicalKey.galaxyY),galaxyZ:bi(galaxy.canonicalKey.galaxyZ),sectorX:bi(x),sectorY:bi(y),sectorZ:bi(z)});
 const p3=k=>Object.freeze({galaxyX:k.galaxyX,galaxyY:k.galaxyY,galaxyZ:k.galaxyZ,x:k.sectorX,y:k.sectorY,z:k.sectorZ});
 const serial=k=>fields.map(f=>f+'='+String(k[f])).join(';');
 function node(galaxy,k,sector){const rid=V.deriveId('galactic-region',galaxy.entityId,[k.sectorX,k.sectorY,k.sectorZ].join(';')),gp=galaxy.metadata.modelProfile||A.galaxyProfile({galaxyIdentity:galaxy.canonicalId||galaxy.entityId}),profile=A.regionProfile({galaxy:gp,galacticRegionIdentity:rid,radialPpm:V.unitPpm(Base.VERSION,rid,'radial'),heightPpm:V.unitPpm(Base.VERSION,rid,'height')});return Object.freeze({version:Base.VERSION,kind:'galactic_region',scale:'galactic_region',entityId:V.deriveId('exploration-galactic_region',galaxy.universeId,serial(k)),universeId:galaxy.universeId,parentId:galaxy.entityId,lineage:Object.freeze([...(galaxy.lineage||[]),galaxy.entityId]),canonicalId:null,canonicalKey:k,authority:'DERIVED',sourceAuthority:'MODEL_DERIVED_SIMULATION',selectable:true,navigable:true,metadata:Object.freeze({p3SectorStatus:'PRESENT',sectorFacts:sector?.facts||null,regionProfile:profile,computationalSectorSource:true,physicalRegionClaim:false,p3SectorKeyShape:'x/y/z'})})}
 function regionFromCanonical({ctx,galaxy,canonicalKey}){const k=key(galaxy,canonicalKey.sectorX,canonicalKey.sectorY,canonicalKey.sectorZ),s=O.p3Astronomy.resolveSector(ctx,p3(k));V.assert(s?.status==='PRESENT','exploration address: canonical sector absent');return node(galaxy,k,s)}
 function discoverRegions({ctx,galaxy,window={x:0n,y:0n,z:0n},cursor=0,limit=16,maxProbes=512}={}){V.assert(ctx&&galaxy?.kind==='galaxy','exploration region discovery context');const side=Base.SECTOR_WINDOW_SIDE||8,cap=side**3,w=Object.freeze({x:bi(window.x??0),y:bi(window.y??0),z:bi(window.z??0)});cursor=Number(cursor);limit=Math.max(1,Math.min(Base.MAX_RESULTS||64,Number(limit)));maxProbes=Math.max(1,Math.min(Base.MAX_PROBES||65536,Number(maxProbes)));const regions=[];let probes=0,index=cursor;for(;index<cap&&probes<maxProbes&&regions.length<limit;index++){const z=Math.floor(index/(side*side)),r=index-z*side*side,y=Math.floor(r/side),x=r-y*side,k=key(galaxy,w.x*BigInt(side)+BigInt(x-Math.floor(side/2)),w.y*BigInt(side)+BigInt(y-Math.floor(side/2)),w.z*BigInt(side)+BigInt(z-Math.floor(side/2))),s=O.p3Astronomy.resolveSector(ctx,p3(k));probes++;if(s?.status==='PRESENT')regions.push(node(galaxy,k,s))}return Object.freeze({version:Base.VERSION,kind:'GALACTIC_REGION_DISCOVERY',galaxyId:galaxy.entityId,window:w,cursor,nextCursor:index<cap?index:null,probes,maxProbes,regions:Object.freeze(regions),bounded:true,regionAuthority:'MODEL_DERIVED_SIMULATION',sectorSourceAuthority:'CANONICAL_PROVEN'})}
 function discoverSystems({ctx,neighborhood:hood,cursor=0,limit=24,maxProbes=4096}={}){V.assert(ctx&&hood?.kind==='stellar_neighborhood','exploration system discovery context');const side=Base.SITE_WINDOW_SIDE||16,cap=side**3,w=hood.metadata.siteWindow,base=hood.canonicalKey;cursor=Number(cursor);limit=Math.max(1,Math.min(Base.MAX_RESULTS||64,Number(limit)));maxProbes=Math.max(1,Math.min(Base.MAX_PROBES||65536,Number(maxProbes)));const systems=[];let probes=0,index=cursor;for(;index<cap&&probes<maxProbes&&systems.length<limit;index++){const z=Math.floor(index/(side*side)),r=index-z*side*side,y=Math.floor(r/side),x=r-y*side,k=Object.freeze({galaxyX:bi(base.galaxyX),galaxyY:bi(base.galaxyY),galaxyZ:bi(base.galaxyZ),sectorX:bi(base.sectorX),sectorY:bi(base.sectorY),sectorZ:bi(base.sectorZ),siteX:bi(w.x)*BigInt(side)+BigInt(x),siteY:bi(w.y)*BigInt(side)+BigInt(y),siteZ:bi(w.z)*BigInt(side)+BigInt(z)}),entity=O.p3Astronomy.resolveSystem(ctx,k);probes++;if(entity?.status==='PRESENT')systems.push(Base.systemFromCanonical({ctx,neighborhood:hood,canonicalKey:k}))}return Object.freeze({version:Base.VERSION,kind:'STELLAR_SYSTEM_DISCOVERY',neighborhoodId:hood.entityId,cursor,nextCursor:index<cap?index:null,probes,maxProbes,systems:Object.freeze(systems),bounded:true,canonicalSource:true})}
 const patched=Object.freeze({...Base,discoverRegions,regionFromCanonical,discoverSystems,sectorContract:'P3_XYZ_TO_PRODUCT_SECTOR_XYZ_V1',systemDiscoveryContract:'BOUNDED_SITE_WINDOW_V1'});O.v1ExplorationAddressSpace=patched;return patched;
}
const AS=sectorCompatibility(),VERSION='ofu-v1-direct-exploration-interaction-3',MAX_OBJECTS=256,DOUBLE_ACTIVATION_MS=420;
function assert(ok,message){V.assert(ok,'exploration interaction: '+message)}
function create({maxObjects=MAX_OBJECTS,onSelect=null,onTravel=null,onInspect=null,onCancel=null}={}){
 maxObjects=Number(maxObjects);assert(Number.isSafeInteger(maxObjects)&&maxObjects>=1&&maxObjects<=MAX_OBJECTS,'object cap');const items=new Map();let focused=null,lastActivation=null;const metrics={registrations:0,hits:0,selections:0,travels:0,inspects:0,cancellations:0,keyboardMoves:0,doubleActivations:0};
 function register({objectId,node,bounds,selectable=true,navigable=true,inspectable=true,decorative=false}){assert(typeof objectId==='string'&&objectId.length>0&&objectId.length<=256,'objectId');assert(node?.version===AS.VERSION,'stable exploration node');assert(!decorative,'decorative objects cannot enter pick registry');assert(!items.has(objectId),'duplicate objectId');assert(items.size<maxObjects,'pick registry cap');assert(bounds&&[bounds.left,bounds.top,bounds.right,bounds.bottom].every(Number.isFinite),'finite bounds');const item=Object.freeze({objectId,node,bounds:Object.freeze({...bounds}),selectable:!!selectable,navigable:!!navigable,inspectable:!!inspectable});items.set(objectId,item);metrics.registrations++;if(focused===null)focused=objectId;return item}
 function ingestMacroLayout(layout,resolveNode){assert(layout&&Array.isArray(layout.hits),'macro layout');assert(typeof resolveNode==='function','macro node resolver');items.clear();focused=null;for(const h of layout.hits.slice(0,maxObjects)){if(h.selectable!==true&&h.navigable!==true)continue;const n=resolveNode(h);if(n)register({objectId:String(h.objectId),node:n,bounds:{left:Number(h.left),top:Number(h.top),right:Number(h.right),bottom:Number(h.bottom)},selectable:h.selectable===true,navigable:h.navigable===true})}return snapshot()}
 function hitTest(x,y){x=Number(x);y=Number(y);let best=null,d=Infinity;for(const item of items.values()){const b=item.bounds;if(x<b.left||x>b.right||y<b.top||y>b.bottom)continue;const dx=x-(b.left+b.right)/2,dy=y-(b.top+b.bottom)/2,q=dx*dx+dy*dy;if(q<d){best=item;d=q}}if(best)metrics.hits++;return best}
 function act(item,type,source){if(!item)return Object.freeze({handled:false,reason:'MISS'});if(type==='SELECT'&&!item.selectable)return Object.freeze({handled:false,reason:'NOT_SELECTABLE'});if(type==='TRAVEL'&&!item.navigable)return Object.freeze({handled:false,reason:'NOT_NAVIGABLE'});if(type==='INSPECT'&&!item.inspectable)return Object.freeze({handled:false,reason:'NOT_INSPECTABLE'});focused=item.objectId;if(type==='SELECT'){metrics.selections++;onSelect?.(item.node,{source})}else if(type==='TRAVEL'){metrics.travels++;onTravel?.(item.node,{source})}else{metrics.inspects++;onInspect?.(item.node,{source})}return Object.freeze({handled:true,action:type,node:item.node,source})}
 function pointerActivate(x,y,{timestamp=Date.now(),pointerType='pointer',activation='auto'}={}){const item=hitTest(x,y);if(!item)return Object.freeze({handled:false,reason:'MISS'});const now=Number(timestamp),dbl=!!lastActivation&&lastActivation.objectId===item.objectId&&now-lastActivation.time>=0&&now-lastActivation.time<=DOUBLE_ACTIVATION_MS;lastActivation={objectId:item.objectId,time:now};if(activation==='inspect')return act(item,'INSPECT',pointerType);if(activation==='travel'||dbl){if(dbl)metrics.doubleActivations++;return act(item,'TRAVEL',dbl?pointerType+'-double':pointerType)}return act(item,'SELECT',pointerType)}
 const ordered=()=>[...items.values()].sort((a,b)=>(a.bounds.top+a.bounds.bottom)-(b.bounds.top+b.bounds.bottom)||(a.bounds.left+a.bounds.right)-(b.bounds.left+b.bounds.right)||a.objectId.localeCompare(b.objectId));
 function keyboardMove(k){const a=ordered();if(!a.length)return null;let i=Math.max(0,a.findIndex(x=>x.objectId===focused));if(k==='Home')i=0;else if(k==='End')i=a.length-1;else if(k==='ArrowRight'||k==='ArrowDown')i=(i+1)%a.length;else if(k==='ArrowLeft'||k==='ArrowUp')i=(i-1+a.length)%a.length;focused=a[i].objectId;metrics.keyboardMoves++;return a[i]}
 function keyboardActivate(k,{shiftKey=false}={}){if(k==='Escape'){metrics.cancellations++;onCancel?.({source:'keyboard'});return Object.freeze({handled:true,action:'CANCEL'})}if(!['Enter',' ','Spacebar'].includes(k))return Object.freeze({handled:false,reason:'NOT_ACTIVATION_KEY'});return act(items.get(focused),shiftKey?'INSPECT':'TRAVEL','keyboard')}
 function focus(id){assert(items.has(String(id)),'unknown focus object');focused=String(id);return items.get(focused)}
 function snapshot(){return Object.freeze({version:VERSION,sectorContract:AS.sectorContract,systemDiscoveryContract:AS.systemDiscoveryContract,objectCap:maxObjects,objects:items.size,focusedObjectId:focused,decorativeSelectable:false,doubleActivationMs:DOUBLE_ACTIVATION_MS,metrics:Object.freeze({...metrics}),entries:Object.freeze([...items.values()])})}
 return Object.freeze({VERSION,register,ingestMacroLayout,hitTest,pointerActivate,keyboardMove,keyboardActivate,focus,snapshot});
}
function macroHandlers({resolveIntent,delegate=null,onResolved=null}={}){assert(typeof resolveIntent==='function','macro intent resolver');return Object.freeze({onNavigate(intent){const node=resolveIntent(intent);if(node)onResolved?.(node,intent);return typeof delegate==='function'?delegate(intent):!!node}})}
O.v1ExplorationInteraction=Object.freeze({VERSION,MAX_OBJECTS,DOUBLE_ACTIVATION_MS,create,macroHandlers,sectorContract:AS.sectorContract,systemDiscoveryContract:AS.systemDiscoveryContract});
})(typeof globalThis!=='undefined'?globalThis:this);
