(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,AS=O.v1ExplorationAddressSpace;
if(!V||!AS)throw new Error('v1 exploration interaction requires address space');
const VERSION='ofu-v1-direct-exploration-interaction-1',MAX_OBJECTS=256,DOUBLE_ACTIVATION_MS=420;
function assert(ok,message){V.assert(ok,'exploration interaction: '+message)}
function create({maxObjects=MAX_OBJECTS,onSelect=null,onTravel=null,onInspect=null,onCancel=null}={}){
 maxObjects=Number(maxObjects);assert(Number.isSafeInteger(maxObjects)&&maxObjects>=1&&maxObjects<=MAX_OBJECTS,'object cap');const items=new Map();let focused=null,lastActivation=null;const metrics={registrations:0,hits:0,selections:0,travels:0,inspects:0,cancellations:0,keyboardMoves:0,doubleActivations:0};
 function register({objectId,node,bounds,selectable=true,navigable=true,inspectable=true,decorative=false}){assert(typeof objectId==='string'&&objectId.length>0&&objectId.length<=256,'objectId');assert(node?.version===AS.VERSION,'stable exploration node');assert(!decorative,'decorative objects cannot enter pick registry');assert(!items.has(objectId),'duplicate objectId');assert(items.size<maxObjects,'pick registry cap');assert(bounds&&[bounds.left,bounds.top,bounds.right,bounds.bottom].every(Number.isFinite),'finite bounds');assert(bounds.left<=bounds.right&&bounds.top<=bounds.bottom,'ordered bounds');const item=Object.freeze({objectId,node,bounds:Object.freeze({...bounds}),selectable:!!selectable,navigable:!!navigable,inspectable:!!inspectable});items.set(objectId,item);metrics.registrations++;if(focused===null)focused=objectId;return item}
 function ingestMacroLayout(layout,resolveNode){assert(layout&&Array.isArray(layout.hits),'macro layout');assert(typeof resolveNode==='function','macro node resolver');items.clear();focused=null;for(const h of layout.hits.slice(0,maxObjects)){if(h.selectable!==true&&h.navigable!==true)continue;const node=resolveNode(h);if(!node)continue;register({objectId:String(h.objectId),node,bounds:{left:Number(h.left),top:Number(h.top),right:Number(h.right),bottom:Number(h.bottom)},selectable:h.selectable===true,navigable:h.navigable===true,inspectable:true,decorative:false})}return snapshot()}
 function hitTest(x,y){x=Number(x);y=Number(y);if(!Number.isFinite(x)||!Number.isFinite(y))return null;let best=null,d=Infinity;for(const item of items.values()){const b=item.bounds;if(x<b.left||x>b.right||y<b.top||y>b.bottom)continue;const cx=(b.left+b.right)/2,cy=(b.top+b.bottom)/2,dist=(x-cx)**2+(y-cy)**2;if(dist<d){best=item;d=dist}}if(best)metrics.hits++;return best}
 function select(item,source='pointer'){if(!item?.selectable)return Object.freeze({handled:false,reason:'NOT_SELECTABLE'});focused=item.objectId;metrics.selections++;onSelect?.(item.node,{source});return Object.freeze({handled:true,action:'SELECT',node:item.node,source})}
 function travel(item,source='pointer'){if(!item?.navigable)return Object.freeze({handled:false,reason:'NOT_NAVIGABLE'});focused=item.objectId;metrics.travels++;onTravel?.(item.node,{source});return Object.freeze({handled:true,action:'TRAVEL',node:item.node,source})}
 function inspect(item,source='pointer'){if(!item?.inspectable)return Object.freeze({handled:false,reason:'NOT_INSPECTABLE'});focused=item.objectId;metrics.inspects++;onInspect?.(item.node,{source});return Object.freeze({handled:true,action:'INSPECT',node:item.node,source})}
 function pointerActivate(x,y,{timestamp=Date.now(),pointerType='pointer',activation='auto'}={}){const item=hitTest(x,y);if(!item)return Object.freeze({handled:false,reason:'MISS'});const now=Number(timestamp),double=lastActivation&&lastActivation.objectId===item.objectId&&now-lastActivation.time>=0&&now-lastActivation.time<=DOUBLE_ACTIVATION_MS;lastActivation={objectId:item.objectId,time:now};if(activation==='inspect')return inspect(item,pointerType);if(activation==='travel'||double){if(double)metrics.doubleActivations++;return travel(item,double?pointerType+'-double':pointerType)}return select(item,pointerType)}
 function ordered(){return [...items.values()].sort((a,b)=>{const ay=(a.bounds.top+a.bounds.bottom)/2,by=(b.bounds.top+b.bounds.bottom)/2,ax=(a.bounds.left+a.bounds.right)/2,bx=(b.bounds.left+b.bounds.right)/2;return ay-by||ax-bx||a.objectId.localeCompare(b.objectId)})}
 function keyboardMove(key){const list=ordered();if(!list.length)return null;let i=list.findIndex(x=>x.objectId===focused);if(i<0)i=0;if(key==='Home')i=0;else if(key==='End')i=list.length-1;else if(key==='ArrowRight'||key==='ArrowDown')i=(i+1)%list.length;else if(key==='ArrowLeft'||key==='ArrowUp')i=(i-1+list.length)%list.length;else return list[i];focused=list[i].objectId;metrics.keyboardMoves++;return list[i]}
 function keyboardActivate(key,{shiftKey=false}={}){if(key==='Escape'){metrics.cancellations++;onCancel?.({source:'keyboard'});return Object.freeze({handled:true,action:'CANCEL'})}const item=items.get(focused);if(!item)return Object.freeze({handled:false,reason:'NO_FOCUS'});if(key==='Enter'||key===' '||key==='Spacebar')return shiftKey?inspect(item,'keyboard'):travel(item,'keyboard');return Object.freeze({handled:false,reason:'NOT_ACTIVATION_KEY'})}
 function focus(objectId){assert(items.has(String(objectId)),'unknown focus object');focused=String(objectId);return items.get(focused)}
 function snapshot(){return Object.freeze({version:VERSION,objectCap:maxObjects,objects:items.size,focusedObjectId:focused,decorativeSelectable:false,doubleActivationMs:DOUBLE_ACTIVATION_MS,metrics:Object.freeze({...metrics}),entries:Object.freeze([...items.values()])})}
 return Object.freeze({VERSION,register,ingestMacroLayout,hitTest,pointerActivate,keyboardMove,keyboardActivate,focus,snapshot});
}
function macroHandlers({resolveIntent,delegate=null,onResolved=null}={}){assert(typeof resolveIntent==='function','macro intent resolver');return Object.freeze({onNavigate(intent){const node=resolveIntent(intent);if(node)onResolved?.(node,intent);return typeof delegate==='function'?delegate(intent):!!node}})}
O.v1ExplorationInteraction=Object.freeze({VERSION,MAX_OBJECTS,DOUBLE_ACTIVATION_MS,create,macroHandlers});
})(typeof globalThis!=='undefined'?globalThis:this);
