(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,Base=O.v1ExplorationAddressSpace,A=O.v1Astronomy;
if(!V||!Base||!A)throw new Error('v1 exploration interaction requires address space and astronomy');
const AS=Base,VERSION='ofu-v1-direct-exploration-interaction-3',MAX_OBJECTS=256,DOUBLE_ACTIVATION_MS=420;
function assert(ok,message){V.assert(ok,'exploration interaction: '+message)}
function create({maxObjects=MAX_OBJECTS,onSelect=null,onTravel=null,onInspect=null,onCancel=null}={}){
 maxObjects=Number(maxObjects);assert(Number.isSafeInteger(maxObjects)&&maxObjects>=1&&maxObjects<=MAX_OBJECTS,'object cap');const items=new Map();let focused=null,lastActivation=null;const metrics={registrations:0,hits:0,selections:0,travels:0,inspects:0,cancellations:0,keyboardMoves:0,doubleActivations:0};
 function register({objectId,node,bounds,selectable=true,navigable=true,inspectable=true,decorative=false}){assert(typeof objectId==='string'&&objectId.length>0&&objectId.length<=256,'objectId');assert(node?.version===AS.VERSION,'stable exploration node');assert(!decorative,'decorative objects cannot enter pick registry');assert(!items.has(objectId),'duplicate objectId');assert(items.size<maxObjects,'pick registry cap');assert(bounds&&[bounds.left,bounds.top,bounds.right,bounds.bottom].every(Number.isFinite),'finite bounds');const item=Object.freeze({objectId,node,bounds:Object.freeze({...bounds}),selectable:!!selectable,navigable:!!navigable,inspectable:!!inspectable});items.set(objectId,item);metrics.registrations++;if(focused===null)focused=objectId;return item}
 function ingestMacroLayout(layout,resolveNode){assert(layout&&Array.isArray(layout.hits),'macro layout');assert(typeof resolveNode==='function','macro node resolver');items.clear();focused=null;for(const h of layout.hits.slice(0,maxObjects)){if(h.selectable!==true&&h.navigable!==true)continue;const n=resolveNode(h);if(n)register({objectId:String(h.objectId),node:n,bounds:{left:Number(h.left),top:Number(h.top),right:Number(h.right),bottom:Number(h.bottom)},selectable:h.selectable===true,navigable:h.navigable===true})}return snapshot()}
 function hitTest(x,y){x=Number(x);y=Number(y);let best=null,d=Infinity;for(const item of items.values()){const b=item.bounds;if(x<b.left||x>b.right||y<b.top||y>b.bottom)continue;const dx=x-(b.left+b.right)/2,dy=y-(b.top+b.bottom)/2,q=dx*dx+dy*dy;if(q<d){best=item;d=q}}if(best)metrics.hits++;return best}
 function act(item,type,source){if(!item)return Object.freeze({handled:false,reason:'MISS'});if(type==='SELECT'&&!item.selectable)return Object.freeze({handled:false,reason:'NOT_SELECTABLE'});if(type==='TRAVEL'&&!item.navigable)return Object.freeze({handled:false,reason:'NOT_NAVIGABLE'});if(type==='INSPECT'&&!item.inspectable)return Object.freeze({handled:false,reason:'NOT_INSPECTABLE'});focused=item.objectId;if(type==='SELECT'){metrics.selections++;onSelect?.(item.node,{source})}else if(type==='TRAVEL'){metrics.travels++;onTravel?.(item.node,{source})}else{metrics.inspects++;onInspect?.(item.node,{source})}return Object.freeze({handled:true,action:type,node:item.node,source})}
 function pointerActivate(x,y,{timestamp=Date.now(),pointerType='pointer',activation='auto'}={}){const item=hitTest(x,y);if(!item)return Object.freeze({handled:false,reason:'MISS'});const now=Number(timestamp),dbl=!!lastActivation&&lastActivation.objectId===item.objectId&&now-lastActivation.time>=0&&now-lastActivation.time<=DOUBLE_ACTIVATION_MS;lastActivation={objectId:item.objectId,time:now};if(activation==='inspect')return act(item,'INSPECT',pointerType);if(activation==='travel'||dbl){if(dbl)metrics.doubleActivations++;return act(item,'TRAVEL',dbl?pointerType+'-double':pointerType)}return act(item,'SELECT',pointerType)}
 const ordered=()=>[...items.values()].sort((a,b)=>(a.bounds.top+a.bounds.bottom)-(b.bounds.top+b.bounds.bottom)||(a.bounds.left+a.bounds.right)-(b.bounds.left+b.bounds.right)||a.objectId.localeCompare(b.objectId));
 function keyboardMove(k){const a=ordered();if(!a.length)return null;let i=Math.max(0,a.findIndex(x=>x.objectId===focused));if(k==='Home')i=0;else if(k==='End')i=a.length-1;else if(k==='ArrowRight'||k==='ArrowDown')i=(i+1)%a.length;else if(k==='ArrowLeft'||k==='ArrowUp')i=(i-1+a.length)%a.length;focused=a[i].objectId;metrics.keyboardMoves++;return a[i]}
 function keyboardActivate(k,{shiftKey=false}={}){if(k==='Escape'){metrics.cancellations++;onCancel?.({source:'keyboard'});return Object.freeze({handled:true,action:'CANCEL'})}if(!['Enter',' ','Spacebar'].includes(k))return Object.freeze({handled:false,reason:'NOT_ACTIVATION_KEY'});return act(items.get(focused),shiftKey?'INSPECT':'TRAVEL','keyboard')}
 function focus(id){assert(items.has(String(id)),'unknown focus object');focused=String(id);return items.get(focused)}
 function snapshot(){return Object.freeze({version:VERSION,sectorContract:AS.sectorContract,systemDiscoveryContract:AS.systemDiscoveryContract,objectCap:maxObjects,objects:items.size,focusedObjectId:focused,decorativeSelectable:false,doubleActivationMs:DOUBLE_ACTIVATION_MS,metrics:Object.freeze({...metrics}),entries:Object.freeze([...items.values()])})}
 return Object.freeze({VERSION,register,ingestMacroLayout,hitTest,pointerActivate,keyboardMove,keyboardActivate,focus,snapshot});
}
function macroHandlers({resolveIntent,delegate=null,onResolved=null}={}){assert(typeof resolveIntent==='function','macro intent resolver');return Object.freeze({onNavigate(intent){const node=resolveIntent(intent);if(node)onResolved?.(node,intent);return typeof delegate==='function'?delegate(intent):!!node}})}
O.v1ExplorationInteraction=Object.freeze({VERSION,MAX_OBJECTS,DOUBLE_ACTIVATION_MS,create,macroHandlers,sectorContract:AS.sectorContract,systemDiscoveryContract:AS.systemDiscoveryContract});
})(typeof globalThis!=='undefined'?globalThis:this);
