(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const AUTHORITY='PRESENTATION_ONLY';
const LEVELS=Object.freeze(['MARKER','BODY_DISC','GLOBE','GLOBE_DETAIL','DESCENT_SURFACE']);
const THRESHOLDS=Object.freeze([1000,50,8,1.5]);
const GEOMETRY=Object.freeze([{maxVertices:4,maxDrawPackets:1},{maxVertices:96,maxDrawPackets:2},{maxVertices:768,maxDrawPackets:3},{maxVertices:3072,maxDrawPackets:4},{maxVertices:8192,maxDrawPackets:5}]);
const LIMITS=Object.freeze({maxFrames:257,minApparentRadiusPx:1,maxApparentRadiusPx:4096,maxVertices:8192,maxDrawPackets:5,transitionFactor:1.8});
function finite(v,label){v=Number(v);if(!Number.isFinite(v))throw new TypeError(label+' must be finite');return v}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function smoothstep(t){t=clamp(t,0,1);return t*t*(3-2*t)}
function levelForRatio(r){r=finite(r,'distanceRatio');if(r>1000)return 0;if(r>50)return 1;if(r>8)return 2;if(r>1.5)return 3;return 4}
function refineBlend(r,levelIndex){if(levelIndex>=LEVELS.length-1)return 0;const threshold=THRESHOLDS[levelIndex],far=threshold*LIMITS.transitionFactor;if(r>=far)return 0;if(r<=threshold)return 1;return smoothstep((Math.log(far)-Math.log(r))/(Math.log(far)-Math.log(threshold)))}
function projectBlend(r,levelIndex){if(levelIndex<=0)return 0;const threshold=THRESHOLDS[levelIndex-1],near=threshold/LIMITS.transitionFactor;if(r<=near)return 0;if(r>=threshold)return 1;return smoothstep((Math.log(r)-Math.log(near))/(Math.log(threshold)-Math.log(near)))}
function transitionBlend(r,levelIndex,direction='REFINE_TO_BODY'){return direction==='PROJECT_TO_SYSTEM'?projectBlend(r,levelIndex):refineBlend(r,levelIndex)}
function geometryBudgetBetween(fromIndex,toIndex,blend){const a=GEOMETRY[fromIndex],b=GEOMETRY[toIndex],t=clamp(blend,0,1);return Object.freeze({maxVertices:Math.min(LIMITS.maxVertices,Math.ceil(a.maxVertices+(b.maxVertices-a.maxVertices)*t)),maxDrawPackets:Math.min(LIMITS.maxDrawPackets,Math.ceil(a.maxDrawPackets+(b.maxDrawPackets-a.maxDrawPackets)*t))})}
function geometryBudget(levelIndex,blendToNext){return geometryBudgetBetween(levelIndex,Math.min(levelIndex+1,GEOMETRY.length-1),blendToNext)}
function decorate(packet,{bodyCues=null,referenceRadiusPx=160,eclipseCue=null}={}){if(!packet||!Array.isArray(packet.frames))throw new TypeError('approach packet required');if(packet.frames.length>LIMITS.maxFrames)throw new RangeError('approach LOD frame budget exceeded');referenceRadiusPx=finite(referenceRadiusPx,'referenceRadiusPx');if(!(referenceRadiusPx>0))throw new RangeError('referenceRadiusPx must be positive');const project=packet.direction==='PROJECT_TO_SYSTEM';let last=project?Infinity:-1,lastApparent=project?Infinity:0;const frames=packet.frames.map(frame=>{const levelIndex=levelForRatio(frame.distanceRatio);if(project?levelIndex>last:levelIndex<last)throw new Error('approach detail must be monotonic for direction');last=levelIndex;const apparentRadiusPx=clamp(referenceRadiusPx/frame.distanceRatio,LIMITS.minApparentRadiusPx,LIMITS.maxApparentRadiusPx);if(project?apparentRadiusPx-1e-12>lastApparent:apparentRadiusPx+1e-12<lastApparent)throw new Error('approach apparent radius must be monotonic for direction');lastApparent=apparentRadiusPx;const blendToAdjacent=transitionBlend(frame.distanceRatio,levelIndex,packet.direction),adjacentIndex=project?Math.max(0,levelIndex-1):Math.min(LEVELS.length-1,levelIndex+1),budget=geometryBudgetBetween(levelIndex,adjacentIndex,blendToAdjacent);return Object.freeze({...frame,lod:Object.freeze({level:LEVELS[levelIndex],levelIndex,adjacentLevel:LEVELS[adjacentIndex],blendToAdjacent,blendToNext:project?0:blendToAdjacent,transitionDirection:project?'COARSEN':'REFINE',apparentRadiusPx,showAtmosphere:Boolean(bodyCues?.atmosphere?.enabled)&&levelIndex>=2,showRings:Boolean(bodyCues?.rings?.enabled)&&levelIndex>=1,showTerminator:Boolean(bodyCues?.terminator?.enabled)&&levelIndex>=1,showEclipseCue:Boolean(eclipseCue&&eclipseCue.classification!=='NO_PRESENTATION_ECLIPSE')&&levelIndex>=1,eclipseWeightedOcclusion:eclipseCue?Number(eclipseCue.weightedOcclusion)||0:0,showSurfaceDetail:levelIndex>=3,geometryBudget:budget,authority:AUTHORITY})})});return Object.freeze({...packet,frames:Object.freeze(frames),lod:Object.freeze({authority:AUTHORITY,levels:LEVELS,thresholds:THRESHOLDS,monotonicDetail:true,continuousTransitionBlend:true,directionAware:true,bodyCueAuthority:bodyCues?.authority||null,eclipseCueAuthority:eclipseCue?.authority||null}),limitations:Object.freeze([...(packet.limitations||[]),'Apparent radius, LOD thresholds and transition blending are bounded presentation policy, not physical angular diameter.','Geometry budgets are admission ceilings for presentation detail and do not change canonical state.'])})}
function validate(packet){if(!packet||!Array.isArray(packet.frames)||packet.frames.length<2)return false;const project=packet.direction==='PROJECT_TO_SYSTEM';if(packet.direction!=='REFINE_TO_BODY'&&!project)return false;let last=project?Infinity:-1,apparent=project?Infinity:0;for(const frame of packet.frames){const lod=frame.lod;if(!lod||LEVELS[lod.levelIndex]!==lod.level||(project?lod.levelIndex>last:lod.levelIndex<last)||(project?lod.apparentRadiusPx-1e-12>apparent:lod.apparentRadiusPx+1e-12<apparent)||lod.blendToAdjacent<0||lod.blendToAdjacent>1||lod.geometryBudget?.maxVertices>LIMITS.maxVertices||lod.geometryBudget?.maxDrawPackets>LIMITS.maxDrawPackets)return false;last=lod.levelIndex;apparent=lod.apparentRadiusPx}return true}
O.v2x04ApproachLod=Object.freeze({VERSION:'ofu-v2x-04-approach-lod-3',AUTHORITY,LEVELS,THRESHOLDS,GEOMETRY,LIMITS,levelForRatio,refineBlend,projectBlend,transitionBlend,geometryBudgetBetween,geometryBudget,decorate,validate});
})(typeof globalThis!=='undefined'?globalThis:this);
