(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const AUTHORITY='PRESENTATION_ONLY';
const LEVELS=Object.freeze(['MARKER','BODY_DISC','GLOBE','GLOBE_DETAIL','DESCENT_SURFACE']);
const THRESHOLDS=Object.freeze([1000,50,8,1.5]);
const GEOMETRY=Object.freeze([{maxVertices:4,maxDrawPackets:1},{maxVertices:96,maxDrawPackets:2},{maxVertices:768,maxDrawPackets:3},{maxVertices:3072,maxDrawPackets:4},{maxVertices:8192,maxDrawPackets:5}]);
const LIMITS=Object.freeze({maxFrames:257,minApparentRadiusPx:1,maxApparentRadiusPx:4096,maxVertices:8192,maxDrawPackets:5,transitionFactor:1.8,scalarTolerance:1e-10});
function finite(value,label){if(value===null||value===undefined||typeof value==='boolean'||(typeof value==='string'&&value.trim()===''))throw new TypeError(label+' must be finite');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite');return n}
function positive(value,label){const n=finite(value,label);if(!(n>0))throw new RangeError(label+' must be positive');return n}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function smoothstep(t){t=clamp(t,0,1);return t*t*(3-2*t)}
function scalarNear(a,b,tolerance=LIMITS.scalarTolerance){a=Number(a);b=Number(b);return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=tolerance*Math.max(1,Math.abs(b))}
function levelIndex(value,label){const n=finite(value,label);if(!Number.isInteger(n)||n<0||n>=LEVELS.length)throw new RangeError(label+' outside LOD range');return n}
function levelForRatio(r){r=positive(r,'distanceRatio');if(r>1000)return 0;if(r>50)return 1;if(r>8)return 2;if(r>1.5)return 3;return 4}
function refineBlend(r,index){r=positive(r,'distanceRatio');index=levelIndex(index,'levelIndex');if(index>=LEVELS.length-1)return 0;const threshold=THRESHOLDS[index],far=threshold*LIMITS.transitionFactor;if(r>=far)return 0;if(r<=threshold)return 1;return smoothstep((Math.log(far)-Math.log(r))/(Math.log(far)-Math.log(threshold)))}
function projectBlend(r,index){return refineBlend(r,index)}
function transitionBlend(r,index,direction='REFINE_TO_BODY'){if(direction!=='REFINE_TO_BODY'&&direction!=='PROJECT_TO_SYSTEM')throw new TypeError('valid approach direction required');return direction==='PROJECT_TO_SYSTEM'?projectBlend(r,index):refineBlend(r,index)}
function geometryBudgetBetween(fromIndex,toIndex,blend){fromIndex=levelIndex(fromIndex,'fromIndex');toIndex=levelIndex(toIndex,'toIndex');blend=finite(blend,'blend');if(blend<0||blend>1)throw new RangeError('blend must be in [0,1]');const a=GEOMETRY[fromIndex],b=GEOMETRY[toIndex];return Object.freeze({maxVertices:Math.min(LIMITS.maxVertices,Math.ceil(a.maxVertices+(b.maxVertices-a.maxVertices)*blend)),maxDrawPackets:Math.min(LIMITS.maxDrawPackets,Math.ceil(a.maxDrawPackets+(b.maxDrawPackets-a.maxDrawPackets)*blend))})}
function geometryBudget(index,blendToNext){index=levelIndex(index,'levelIndex');return geometryBudgetBetween(index,Math.min(index+1,GEOMETRY.length-1),blendToNext)}
function eclipseWeight(eclipseCue){if(!eclipseCue)return 0;if(eclipseCue.authority!==AUTHORITY||eclipseCue.scientificEvidence!==false)throw new TypeError('presentation-only eclipse cue required');const weight=finite(eclipseCue.weightedOcclusion,'eclipse weightedOcclusion');if(weight<0||weight>1)throw new RangeError('eclipse weightedOcclusion must be in [0,1]');if(eclipseCue.classification==='NO_PRESENTATION_ECLIPSE'&&weight>LIMITS.scalarTolerance)throw new RangeError('NO_PRESENTATION_ECLIPSE requires zero occlusion');if(eclipseCue.classification==='TOTAL_PRESENTATION_ECLIPSE_CUE'&&Math.abs(weight-1)>LIMITS.scalarTolerance)throw new RangeError('TOTAL_PRESENTATION_ECLIPSE_CUE requires full occlusion');if(eclipseCue.classification==='PARTIAL_PRESENTATION_ECLIPSE_CUE'&&!(weight>0&&weight<1))throw new RangeError('PARTIAL_PRESENTATION_ECLIPSE_CUE requires partial occlusion');return weight}
function decorate(packet,{bodyCues=null,referenceRadiusPx=160,eclipseCue=null}={}){
 if(!packet||!Array.isArray(packet.frames))throw new TypeError('approach packet required');if(packet.direction!=='REFINE_TO_BODY'&&packet.direction!=='PROJECT_TO_SYSTEM')throw new TypeError('valid approach direction required');if(bodyCues&&bodyCues.authority!==AUTHORITY)throw new TypeError('presentation-only body cues required');if(packet.frames.length<2||packet.frames.length>LIMITS.maxFrames)throw new RangeError('approach LOD frame budget exceeded');if(O.v2x04ApproachContinuity?.validate&&!O.v2x04ApproachContinuity.validate(packet))throw new TypeError('valid approach continuity packet required');referenceRadiusPx=positive(referenceRadiusPx,'referenceRadiusPx');const project=packet.direction==='PROJECT_TO_SYSTEM',eclipseWeightedOcclusion=eclipseWeight(eclipseCue),cueSupport=Object.freeze({atmosphere:Boolean(bodyCues?.atmosphere?.enabled),rings:Boolean(bodyCues?.rings?.enabled),terminator:Boolean(bodyCues?.terminator?.enabled),eclipse:Boolean(eclipseCue&&eclipseCue.classification!=='NO_PRESENTATION_ECLIPSE'&&eclipseWeightedOcclusion>0)});let last=project?Infinity:-1,lastApparent=project?Infinity:0;
 const frames=packet.frames.map(frame=>{const ratio=positive(frame.distanceRatio,'distanceRatio'),index=levelForRatio(ratio);if(project?index>last:index<last)throw new Error('approach detail must be monotonic for direction');last=index;const apparentRadiusPx=clamp(referenceRadiusPx/ratio,LIMITS.minApparentRadiusPx,LIMITS.maxApparentRadiusPx);if(project?apparentRadiusPx-1e-12>lastApparent:apparentRadiusPx+1e-12<lastApparent)throw new Error('approach apparent radius must be monotonic for direction');lastApparent=apparentRadiusPx;const blendToAdjacent=transitionBlend(ratio,index,packet.direction),adjacentIndex=Math.min(LEVELS.length-1,index+1),budget=geometryBudgetBetween(index,adjacentIndex,blendToAdjacent);return Object.freeze({...frame,lod:Object.freeze({level:LEVELS[index],levelIndex:index,adjacentLevel:LEVELS[adjacentIndex],blendToAdjacent,blendToNext:blendToAdjacent,transitionDirection:project?'COARSEN':'REFINE',apparentRadiusPx,showAtmosphere:cueSupport.atmosphere&&index>=2,showRings:cueSupport.rings&&index>=1,showTerminator:cueSupport.terminator&&index>=1,showEclipseCue:cueSupport.eclipse&&index>=1,eclipseWeightedOcclusion,showSurfaceDetail:index>=3,geometryBudget:budget,authority:AUTHORITY})})});
 return Object.freeze({...packet,frames:Object.freeze(frames),lod:Object.freeze({authority:AUTHORITY,levels:LEVELS,thresholds:THRESHOLDS,referenceRadiusPx,monotonicDetail:true,continuousTransitionBlend:true,directionAware:true,directionInvariantVisualState:true,cueSupport,eclipseWeightedOcclusion,bodyCueAuthority:bodyCues?.authority||null,eclipseCueAuthority:eclipseCue?.authority||null}),limitations:Object.freeze([...(packet.limitations||[]),'Apparent radius, LOD thresholds and transition blending are bounded presentation policy, not physical angular diameter.','Geometry budgets are admission ceilings for presentation detail and do not change canonical state.'])});
}
function validate(packet){try{
 if(!packet||!Array.isArray(packet.frames)||packet.frames.length<2||packet.frames.length>LIMITS.maxFrames||!packet.lod||packet.lod.authority!==AUTHORITY)return false;if(!Array.isArray(packet.lod.levels)||packet.lod.levels.length!==LEVELS.length||packet.lod.levels.some((x,i)=>x!==LEVELS[i])||!Array.isArray(packet.lod.thresholds)||packet.lod.thresholds.length!==THRESHOLDS.length||packet.lod.thresholds.some((x,i)=>x!==THRESHOLDS[i])||packet.lod.monotonicDetail!==true||packet.lod.continuousTransitionBlend!==true||packet.lod.directionAware!==true||packet.lod.directionInvariantVisualState!==true)return false;const project=packet.direction==='PROJECT_TO_SYSTEM';if(packet.direction!=='REFINE_TO_BODY'&&!project)return false;if(O.v2x04ApproachContinuity?.validate&&!O.v2x04ApproachContinuity.validate(packet))return false;const referenceRadiusPx=positive(packet.lod.referenceRadiusPx,'referenceRadiusPx'),cueSupport=packet.lod.cueSupport;if(!cueSupport||typeof cueSupport!=='object'||['atmosphere','rings','terminator','eclipse'].some(k=>typeof cueSupport[k]!=='boolean'))return false;const eclipseWeightedOcclusion=finite(packet.lod.eclipseWeightedOcclusion,'eclipseWeightedOcclusion');if(eclipseWeightedOcclusion<0||eclipseWeightedOcclusion>1)return false;if(packet.lod.bodyCueAuthority!==null&&packet.lod.bodyCueAuthority!==AUTHORITY)return false;if(packet.lod.eclipseCueAuthority!==null&&packet.lod.eclipseCueAuthority!==AUTHORITY)return false;let last=project?Infinity:-1,apparent=project?Infinity:0;
 for(const frame of packet.frames){const ratio=positive(frame.distanceRatio,'distanceRatio'),lod=frame.lod,index=levelForRatio(ratio);if(!lod||lod.authority!==AUTHORITY||lod.levelIndex!==index||lod.level!==LEVELS[index])return false;const adjacentIndex=Math.min(LEVELS.length-1,index+1),expectedBlend=transitionBlend(ratio,index,packet.direction),expectedApparent=clamp(referenceRadiusPx/ratio,LIMITS.minApparentRadiusPx,LIMITS.maxApparentRadiusPx),expectedBudget=geometryBudgetBetween(index,adjacentIndex,expectedBlend);if(lod.adjacentLevel!==LEVELS[adjacentIndex]||!scalarNear(lod.blendToAdjacent,expectedBlend)||!scalarNear(lod.blendToNext,expectedBlend)||lod.transitionDirection!==(project?'COARSEN':'REFINE')||!scalarNear(lod.apparentRadiusPx,expectedApparent)||lod.geometryBudget?.maxVertices!==expectedBudget.maxVertices||lod.geometryBudget?.maxDrawPackets!==expectedBudget.maxDrawPackets)return false;if(lod.showAtmosphere!==(Boolean(cueSupport.atmosphere)&&index>=2)||lod.showRings!==(Boolean(cueSupport.rings)&&index>=1)||lod.showTerminator!==(Boolean(cueSupport.terminator)&&index>=1)||lod.showEclipseCue!==(Boolean(cueSupport.eclipse)&&index>=1)||lod.showSurfaceDetail!==(index>=3)||!scalarNear(lod.eclipseWeightedOcclusion,eclipseWeightedOcclusion))return false;if(project?index>last:index<last)return false;if(project?expectedApparent-1e-12>apparent:expectedApparent+1e-12<apparent)return false;last=index;apparent=expectedApparent}
 return true;
 }catch{return false}}
O.v2x04ApproachLod=Object.freeze({VERSION:'ofu-v2x-04-approach-lod-5',AUTHORITY,LEVELS,THRESHOLDS,GEOMETRY,LIMITS,levelForRatio,refineBlend,projectBlend,transitionBlend,geometryBudgetBetween,geometryBudget,decorate,validate});
})(typeof globalThis!=='undefined'?globalThis:this);
