(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const AUTHORITY='PRESENTATION_ONLY';
const LIMITS=Object.freeze({maxOccluders:64,maxStars:8,minRingInnerRatio:1.01,maxRingInnerRatio:5,maxRingOuterRatio:8});
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function finite(value,label){if(value===null||value===undefined||typeof value==='boolean'||(typeof value==='string'&&value.trim()===''))throw new TypeError(label+' must be finite');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite');return n}
function optionalFinite(value,label){if(value===undefined||value===null||(typeof value==='string'&&value.trim()===''))return null;if(typeof value==='boolean')throw new TypeError(label+' must be finite when supplied');const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite when supplied');return n}
function nonNegative(value,label){const n=finite(value,label);if(n<0)throw new RangeError(label+' must be non-negative');return n}
function optionalPositive(value,label){const n=optionalFinite(value,label);if(n===null)return null;if(!(n>0))throw new RangeError(label+' must be positive when supplied');return n}
function idToken(id){if(typeof id==='string'&&id)return id;if(id instanceof Uint8Array)return Array.from(id,b=>b.toString(16).padStart(2,'0')).join('');if(ArrayBuffer.isView(id))return Array.from(new Uint8Array(id.buffer,id.byteOffset,id.byteLength),b=>b.toString(16).padStart(2,'0')).join('');throw new TypeError('body id must be non-empty string or bytes')}
function vec3(v,label){if(!Array.isArray(v)||v.length!==3)throw new TypeError(label+' must be vec3');return Object.freeze(v.map((x,i)=>finite(x,label+'['+i+']')))}
function stableHash(text){let h=2166136261>>>0,s=String(text);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function unitHash(text,salt=0){let x=(stableHash(text)^Math.imul(salt+1,0x9e3779b1))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/4294967296}
function atmosphereMass(input){if(!input)return null;for(const [field,unit] of [['retainedMassYg','Yg'],['atmosphericRetainedMassTg','Tg']]){const value=optionalFinite(input[field],field);if(value!==null){if(value<0)throw new RangeError(field+' must be non-negative');return Object.freeze({field,unit,value})}}return null}
function knownAtmosphere(input){if(!input)return false;const mass=atmosphereMass(input),knownState=input.status==='KNOWN'||input.epistemicStatus==='KNOWN';if(knownState&&mass)return mass.value>0;if(input.epistemicState==='KNOWN'&&input.present===true)return true;if(input.supported===true&&input.present===true)return true;return false}
function knownRings(input){if(!input)return false;return (input.status==='KNOWN'||input.epistemicStatus==='KNOWN'||input.epistemicState==='KNOWN'||input.supported===true)&&input.present===true}
function knownRadius(body){const f=body?.facts||{},physical=body?.physical||{};for(const [value,label,scale] of [[f.radiusKm,'radiusKm',1],[f.meanRadiusKm,'meanRadiusKm',1],[f.canonicalRadiusKm,'canonicalRadiusKm',1],[f.radiusM,'radiusM',1/1000],[f.meanRadiusM,'meanRadiusM',1/1000],[physical.radiusM,'physical.radiusM',1/1000],[physical.meanRadiusM,'physical.meanRadiusM',1/1000]]){const n=optionalPositive(value,label);if(n!==null)return n*scale}return null}
function atmospherePresentation(input){if(!knownAtmosphere(input))return Object.freeze({enabled:false,authority:AUTHORITY,sourceSupport:'NOT_SUPPORTED_OR_UNKNOWN',rimStrength:0,parameterAuthority:'DISABLED'});const sourceMass=atmosphereMass(input),explicit=optionalFinite(input?.presentationRimStrength,'presentationRimStrength');if(explicit!==null&&(explicit<0||explicit>1))throw new RangeError('presentationRimStrength must be in [0,1]');const rimStrength=explicit===null?.5:explicit;return Object.freeze({enabled:true,authority:AUTHORITY,sourceSupport:'KNOWN_OR_EXPLICIT_SUPPORTED',sourceMass,rimStrength,parameterAuthority:explicit===null?'GENERIC_PRESENTATION_FALLBACK':'UPSTREAM_PRESENTATION_PARAMETER'})}
function ringsPresentation(body,input){if(!knownRings(input))return Object.freeze({enabled:false,authority:AUTHORITY,sourceSupport:'NOT_SUPPORTED_OR_UNKNOWN'});const id=idToken(body.id),inner=optionalFinite(input?.innerRadiusRatio,'innerRadiusRatio'),outer=optionalFinite(input?.outerRadiusRatio,'outerRadiusRatio'),tiltValues=[['tiltDeg',input?.tiltDeg],['inclinationDeg',input?.inclinationDeg],['planeInclinationDeg',input?.planeInclinationDeg]],tiltPair=tiltValues.map(([label,value])=>[label,optionalFinite(value,label)]).find(([,value])=>value!==null),knownTilt=tiltPair?tiltPair[1]:null;if(inner!==null&&!(inner>1))throw new RangeError('innerRadiusRatio must be > 1');if(outer!==null&&!(outer>1))throw new RangeError('outerRadiusRatio must be > 1');if(inner!==null&&outer!==null&&!(outer>inner))throw new RangeError('outerRadiusRatio must exceed innerRadiusRatio');let innerRatio;if(inner!==null)innerRatio=clamp(inner,LIMITS.minRingInnerRatio,LIMITS.maxRingInnerRatio);else if(outer!==null)innerRatio=Math.min(1.35,Math.max(LIMITS.minRingInnerRatio,outer-.25));else innerRatio=1.35;let outerRatio;if(outer!==null){if(!(outer>innerRatio))throw new RangeError('outerRadiusRatio must exceed effective inner radius');outerRatio=clamp(outer,innerRatio+.01,LIMITS.maxRingOuterRatio)}else outerRatio=Math.max(innerRatio+.25,Math.min(2.15,LIMITS.maxRingOuterRatio));const tiltRad=knownTilt===null?(unitHash(id,4)-.5)*Math.PI*.45:knownTilt*Math.PI/180,fallbackDeterministic=inner===null||outer===null||knownTilt===null,parameterClamped=(inner!==null&&inner!==innerRatio)||(outer!==null&&outer!==outerRatio);return Object.freeze({enabled:true,authority:AUTHORITY,sourceSupport:'KNOWN_OR_EXPLICIT_SUPPORTED',innerRadiusRatio:innerRatio,outerRadiusRatio:outerRatio,tiltRad,geometryAuthority:AUTHORITY,parameterAuthority:fallbackDeterministic?'PARTIAL_PRESENTATION_FALLBACK':'SUPPORTED_INPUT_PRESENTATION_MAPPING',fallbackDeterministic,parameterClamped})}
function requireIlluminationValidator(){const validator=O.v2x04MultiStarIllumination?.validateIllumination;if(typeof validator!=='function')throw new Error('V2X-04 illumination validator required; unvalidated illumination forbidden');return validator}
function bodyCues(body,{environment=null,visual=null,illumination=null}={}){if(!body||body.id===undefined||body.id===null)throw new TypeError('body envelope with id required');if(body.facts!==undefined&&body.facts!==null&&(typeof body.facts!=='object'||Array.isArray(body.facts)||ArrayBuffer.isView(body.facts)))throw new TypeError('body facts must be an object when supplied');if(illumination&&!requireIlluminationValidator()(illumination))throw new TypeError('valid illumination packet required');const canonicalEntityId=idToken(body.id),radiusKm=knownRadius(body),atmosphereInput=environment?.atmosphere||environment,ringsInput=visual?.rings||body?.rings,atmosphere=atmospherePresentation(atmosphereInput),rings=ringsPresentation(body,ringsInput),lightCount=Array.isArray(illumination?.lights)?illumination.lights.length:0;if(lightCount>LIMITS.maxStars)throw new RangeError('illumination star budget exceeded');return Object.freeze({canonicalEntityId,authority:AUTHORITY,scientificEvidence:false,silhouette:Object.freeze({enabled:true,radiusKnown:radiusKm!==null,sourceRadiusKm:radiusKm,scaleAuthority:radiusKm!==null?'SUPPORTED_INPUT':'GENERIC_PRESENTATION_FALLBACK'}),atmosphere,rings,terminator:Object.freeze({enabled:lightCount>0,authority:AUTHORITY,lightCount}),shadow:Object.freeze({enabled:lightCount>0,authority:AUTHORITY,mode:'PRESENTATION_DIRECTIONAL_CUE'}),limitations:Object.freeze(['Atmosphere and rings remain disabled when support is unknown.','Supported rings may use bounded presentation fallback geometry when ring radii or plane orientation are unknown.','Atmosphere existence may follow supported retained-mass evidence, but rim strength is not inferred from physical mass.','Terminator and shadow are presentation cues derived from a validated illumination packet, not radiative-transfer evidence.','Unknown body radius uses generic silhouette scale and is never promoted to a physical measurement.'])})}
function discOverlapFraction(r1,r2,d){r1=nonNegative(r1,'occluderAngularRadiusRad');r2=nonNegative(r2,'targetAngularRadiusRad');d=nonNegative(d,'angularSeparationRad');if(!(r2>0))return d<r1?1:0;if(d>=r1+r2)return 0;if(r1>=d+r2)return 1;if(r2>=d+r1)return clamp((r1*r1)/(r2*r2),0,1);const a1=Math.acos(clamp((d*d+r1*r1-r2*r2)/(2*d*r1),-1,1)),a2=Math.acos(clamp((d*d+r2*r2-r1*r1)/(2*d*r2),-1,1)),area=r1*r1*a1+r2*r2*a2-.5*Math.sqrt(Math.max(0,(-d+r1+r2)*(d+r1-r2)*(d-r1+r2)*(d+r1+r2)));return clamp(area/(Math.PI*r2*r2),0,1)}
function presentationOcclusion({lightDirection3d,occluderDirection3d,occluderAngularRadiusRad,targetAngularRadiusRad=0}){const a=vec3(lightDirection3d,'lightDirection3d'),b=vec3(occluderDirection3d,'occluderDirection3d'),an=Math.hypot(...a),bn=Math.hypot(...b);if(!(an>0&&bn>0))throw new RangeError('directions must be non-zero');const dot=clamp((a[0]*b[0]+a[1]*b[1]+a[2]*b[2])/(an*bn),-1,1),separation=Math.acos(dot),occ=nonNegative(occluderAngularRadiusRad,'occluderAngularRadiusRad'),target=nonNegative(targetAngularRadiusRad,'targetAngularRadiusRad'),overlapFraction=discOverlapFraction(occ,target,separation),overlap=overlapFraction>0,classification=!overlap?'NO_PRESENTATION_OVERLAP':overlapFraction>=1-1e-9?'TOTAL_PRESENTATION_OCCLUSION_CUE':'PARTIAL_PRESENTATION_OCCLUSION_CUE';return Object.freeze({authority:AUTHORITY,scientificEvidence:false,overlap,overlapFraction,separationRad:separation,occluderAngularRadiusRad:occ,targetAngularRadiusRad:target,classification,limitations:Object.freeze(['Presentation-space angular overlap is not a canonical eclipse prediction.'])})}
function starRadiusFor(starAngularRadiusRad,starId){const raw=typeof starAngularRadiusRad==='object'&&starAngularRadiusRad!==null?starAngularRadiusRad[starId]:starAngularRadiusRad;if(raw===undefined||raw===null||(typeof raw==='string'&&raw.trim()===''))return .00465;return nonNegative(raw,'starAngularRadiusRad')}
function validateIlluminationWeights(illumination){if(!illumination||!Array.isArray(illumination.lights)||illumination.lights.length>LIMITS.maxStars)throw new TypeError('bounded illumination packet required');let sum=0;const ids=new Set();for(const light of illumination.lights){if(!light||typeof light.starCanonicalEntityId!=='string'||!light.starCanonicalEntityId||ids.has(light.starCanonicalEntityId))throw new TypeError('unique illumination star identity required');ids.add(light.starCanonicalEntityId);const direction=vec3(light.direction3d,'light.direction3d');if(!(Math.hypot(...direction)>0))throw new RangeError('illumination direction must be non-zero');const weight=finite(light.normalizedWeight,'light.normalizedWeight');if(weight<0)throw new RangeError('normalizedWeight must be non-negative');sum+=weight}if(illumination.lights.length&&Math.abs(sum-1)>1e-9)throw new RangeError('illumination weights must sum to 1');return true}
function compositeEclipse(illumination,{occluders=[],starAngularRadiusRad=.00465}={}){validateIlluminationWeights(illumination);if(!Array.isArray(occluders))throw new TypeError('occluders array required');if(occluders.length>LIMITS.maxOccluders)throw new RangeError('occluder budget exceeded');const rows=illumination.lights.map(light=>{let maxFraction=0,best=null;for(const occ of occluders){if(!occ)throw new TypeError('occluder required');const radius=starRadiusFor(starAngularRadiusRad,light.starCanonicalEntityId),cue=presentationOcclusion({lightDirection3d:light.direction3d,occluderDirection3d:occ.direction3d,occluderAngularRadiusRad:occ.angularRadiusRad,targetAngularRadiusRad:radius});if(cue.overlapFraction>maxFraction){maxFraction=cue.overlapFraction;best=occ.canonicalEntityId??occ.id??null}}return Object.freeze({starCanonicalEntityId:light.starCanonicalEntityId,normalizedWeight:light.normalizedWeight,occludedFraction:maxFraction,visibleFraction:1-maxFraction,dominantOccluderCanonicalEntityId:best,authority:AUTHORITY})}),weightedOcclusion=clamp(rows.reduce((n,row)=>n+row.normalizedWeight*row.occludedFraction,0),0,1),classification=weightedOcclusion<=1e-9?'NO_PRESENTATION_ECLIPSE':weightedOcclusion>=1-1e-9?'TOTAL_PRESENTATION_ECLIPSE_CUE':'PARTIAL_PRESENTATION_ECLIPSE_CUE';return Object.freeze({authority:AUTHORITY,scientificEvidence:false,classification,weightedOcclusion,weightedVisibility:1-weightedOcclusion,perStar:Object.freeze(rows),resourceUsage:Object.freeze({stars:rows.length,occluders:occluders.length,maxOccluders:LIMITS.maxOccluders}),limitations:Object.freeze(['Composite eclipse is a bounded presentation cue over supplied angular inputs, not canonical orbital event truth.','Multiple occluders are deliberately reduced to the strongest overlap per stellar source, avoiding unsupported union-area claims.'])})}
O.v2x04BodyCues=Object.freeze({VERSION:'ofu-v2x-04-body-cues-5',AUTHORITY,LIMITS,idToken,knownAtmosphere,knownRings,knownRadius,atmospherePresentation,ringsPresentation,bodyCues,discOverlapFraction,presentationOcclusion,compositeEclipse});
})(typeof globalThis!=='undefined'?globalThis:this);
