(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const AUTHORITY='PRESENTATION_ONLY';
function finiteOrNull(v){const n=Number(v);return Number.isFinite(n)?n:null}
function knownAtmosphere(input){if(!input)return false;if(input.status==='KNOWN'&&finiteOrNull(input.retainedMassYg)>0)return true;if(input.epistemicState==='KNOWN'&&input.present===true)return true;return input.supported===true&&input.present===true}
function knownRings(input){if(!input)return false;return (input.status==='KNOWN'||input.epistemicState==='KNOWN'||input.supported===true)&&input.present===true}
function knownRadius(body){const f=body?.facts||{},candidates=[f.radiusKm,f.meanRadiusKm,f.canonicalRadiusKm];for(const value of candidates){const n=finiteOrNull(value);if(n!==null&&n>0)return n}return null}
function bodyCues(body,{environment=null,visual=null,illumination=null}={}){if(!body||body.id===undefined||body.id===null)throw new TypeError('body envelope with id required');const radiusKm=knownRadius(body),atmosphere=knownAtmosphere(environment?.atmosphere||environment),rings=knownRings(visual?.rings||body?.rings),lightCount=Array.isArray(illumination?.lights)?illumination.lights.length:0;return Object.freeze({canonicalEntityId:String(body.id),authority:AUTHORITY,scientificEvidence:false,silhouette:Object.freeze({enabled:true,radiusKnown:radiusKm!==null,sourceRadiusKm:radiusKm,scaleAuthority:radiusKm!==null?'SUPPORTED_INPUT':'GENERIC_PRESENTATION_FALLBACK'}),atmosphere:Object.freeze({enabled:atmosphere,authority:AUTHORITY,sourceSupport:atmosphere?'KNOWN_OR_EXPLICIT_SUPPORTED':'NOT_SUPPORTED_OR_UNKNOWN'}),rings:Object.freeze({enabled:rings,authority:AUTHORITY,sourceSupport:rings?'KNOWN_OR_EXPLICIT_SUPPORTED':'NOT_SUPPORTED_OR_UNKNOWN'}),terminator:Object.freeze({enabled:lightCount>0,authority:AUTHORITY,lightCount}),shadow:Object.freeze({enabled:lightCount>0,authority:AUTHORITY,mode:'PRESENTATION_DIRECTIONAL_CUE'}),limitations:Object.freeze(['Atmosphere and rings remain disabled when support is unknown.','Terminator and shadow are presentation cues derived from an illumination packet, not radiative-transfer evidence.','Unknown body radius uses generic silhouette scale and is never promoted to a physical measurement.'])})}
function presentationOcclusion({lightDirection3d,occluderDirection3d,occluderAngularRadiusRad,targetAngularRadiusRad=0}){const a=Array.isArray(lightDirection3d)?lightDirection3d:null,b=Array.isArray(occluderDirection3d)?occluderDirection3d:null;if(!a||a.length!==3||!b||b.length!==3)throw new TypeError('light and occluder directions must be vec3');const an=Math.hypot(...a),bn=Math.hypot(...b);if(!(an>0&&bn>0))throw new RangeError('directions must be non-zero');const dot=Math.max(-1,Math.min(1,(a[0]*b[0]+a[1]*b[1]+a[2]*b[2])/(an*bn))),separation=Math.acos(dot),occ=Math.max(0,Number(occluderAngularRadiusRad)||0),target=Math.max(0,Number(targetAngularRadiusRad)||0),overlap=separation<occ+target;return Object.freeze({authority:AUTHORITY,scientificEvidence:false,overlap,separationRad:separation,occluderAngularRadiusRad:occ,targetAngularRadiusRad:target,classification:overlap?'PRESENTATION_OCCLUSION_CUE':'NO_PRESENTATION_OVERLAP',limitations:Object.freeze(['Presentation-space angular overlap is not a canonical eclipse prediction.'])})}
O.v2x04BodyCues=Object.freeze({VERSION:'ofu-v2x-04-body-cues-1',AUTHORITY,knownAtmosphere,knownRings,knownRadius,bodyCues,presentationOcclusion});
})(typeof globalThis!=='undefined'?globalThis:this);
