(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const AUTHORITY='PRESENTATION_ONLY';
function finiteOrNull(v){const n=Number(v);return Number.isFinite(n)?n:null}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function stableHash(text){let h=2166136261>>>0;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function unitHash(text,salt=0){let x=(stableHash(text)^Math.imul(salt+1,0x9e3779b1))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/4294967296}
function knownAtmosphere(input){if(!input)return false;if(input.status==='KNOWN'&&finiteOrNull(input.retainedMassYg)>0)return true;if(input.epistemicState==='KNOWN'&&input.present===true)return true;return input.supported===true&&input.present===true}
function knownRings(input){if(!input)return false;return (input.status==='KNOWN'||input.epistemicState==='KNOWN'||input.supported===true)&&input.present===true}
function knownRadius(body){const f=body?.facts||{},candidates=[f.radiusKm,f.meanRadiusKm,f.canonicalRadiusKm];for(const value of candidates){const n=finiteOrNull(value);if(n!==null&&n>0)return n}return null}
function atmospherePresentation(input){if(!knownAtmosphere(input))return Object.freeze({enabled:false,authority:AUTHORITY,sourceSupport:'NOT_SUPPORTED_OR_UNKNOWN',rimStrength:0});const mass=finiteOrNull(input?.retainedMassYg),rimStrength=mass!==null&&mass>0?clamp(.28+.08*Math.log1p(mass),.28,.85):.5;return Object.freeze({enabled:true,authority:AUTHORITY,sourceSupport:'KNOWN_OR_EXPLICIT_SUPPORTED',rimStrength,parameterAuthority:mass!==null&&mass>0?'SUPPORTED_INPUT_PRESENTATION_MAPPING':'GENERIC_PRESENTATION_FALLBACK'})}
function ringsPresentation(body,input){if(!knownRings(input))return Object.freeze({enabled:false,authority:AUTHORITY,sourceSupport:'NOT_SUPPORTED_OR_UNKNOWN'});const id=String(body.id),inner=finiteOrNull(input?.innerRadiusRatio),outer=finiteOrNull(input?.outerRadiusRatio),tiltCandidates=[input?.tiltDeg,input?.inclinationDeg,input?.planeInclinationDeg],knownTilt=tiltCandidates.map(finiteOrNull).find(v=>v!==null),innerRatio=inner!==null&&inner>1?clamp(inner,1.01,5):1.35,outerRatio=outer!==null&&outer>innerRatio?clamp(outer,innerRatio+.01,8):Math.max(innerRatio+.25,2.15),tiltRad=knownTilt!==undefined&&knownTilt!==null?knownTilt*Math.PI/180:(unitHash(id,4)-.5)*Math.PI*.45;return Object.freeze({enabled:true,authority:AUTHORITY,sourceSupport:'KNOWN_OR_EXPLICIT_SUPPORTED',innerRadiusRatio:innerRatio,outerRadiusRatio:outerRatio,tiltRad,geometryAuthority:AUTHORITY,parameterAuthority:inner!==null&&outer!==null&&knownTilt!==undefined&&knownTilt!==null?'SUPPORTED_INPUT_PRESENTATION_MAPPING':'PARTIAL_PRESENTATION_FALLBACK',fallbackDeterministic:knownTilt===undefined||knownTilt===null||inner===null||outer===null})}
function bodyCues(body,{environment=null,visual=null,illumination=null}={}){if(!body||body.id===undefined||body.id===null)throw new TypeError('body envelope with id required');const radiusKm=knownRadius(body),atmosphereInput=environment?.atmosphere||environment,ringsInput=visual?.rings||body?.rings,atmosphere=atmospherePresentation(atmosphereInput),rings=ringsPresentation(body,ringsInput),lightCount=Array.isArray(illumination?.lights)?illumination.lights.length:0;return Object.freeze({canonicalEntityId:String(body.id),authority:AUTHORITY,scientificEvidence:false,silhouette:Object.freeze({enabled:true,radiusKnown:radiusKm!==null,sourceRadiusKm:radiusKm,scaleAuthority:radiusKm!==null?'SUPPORTED_INPUT':'GENERIC_PRESENTATION_FALLBACK'}),atmosphere,rings,terminator:Object.freeze({enabled:lightCount>0,authority:AUTHORITY,lightCount}),shadow:Object.freeze({enabled:lightCount>0,authority:AUTHORITY,mode:'PRESENTATION_DIRECTIONAL_CUE'}),limitations:Object.freeze(['Atmosphere and rings remain disabled when support is unknown.','Supported rings may use bounded presentation fallback geometry when ring radii or plane orientation are unknown.','Atmosphere rim strength is a presentation mapping, not optical depth or measured density.','Terminator and shadow are presentation cues derived from an illumination packet, not radiative-transfer evidence.','Unknown body radius uses generic silhouette scale and is never promoted to a physical measurement.'])})}
function discOverlapFraction(r1,r2,d){r1=Math.max(0,Number(r1)||0);r2=Math.max(0,Number(r2)||0);d=Math.max(0,Number(d)||0);if(!(r2>0))return d<r1?1:0;if(d>=r1+r2)return 0;if(r1>=d+r2)return 1;if(r2>=d+r1)return clamp((r1*r1)/(r2*r2),0,1);const a1=Math.acos(clamp((d*d+r1*r1-r2*r2)/(2*d*r1),-1,1)),a2=Math.acos(clamp((d*d+r2*r2-r1*r1)/(2*d*r2),-1,1)),area=r1*r1*a1+r2*r2*a2-.5*Math.sqrt(Math.max(0,(-d+r1+r2)*(d+r1-r2)*(d-r1+r2)*(d+r1+r2)));return clamp(area/(Math.PI*r2*r2),0,1)}
function presentationOcclusion({lightDirection3d,occluderDirection3d,occluderAngularRadiusRad,targetAngularRadiusRad=0}){const a=Array.isArray(lightDirection3d)?lightDirection3d:null,b=Array.isArray(occluderDirection3d)?occluderDirection3d:null;if(!a||a.length!==3||!b||b.length!==3)throw new TypeError('light and occluder directions must be vec3');const an=Math.hypot(...a),bn=Math.hypot(...b);if(!(an>0&&bn>0))throw new RangeError('directions must be non-zero');const dot=clamp((a[0]*b[0]+a[1]*b[1]+a[2]*b[2])/(an*bn),-1,1),separation=Math.acos(dot),occ=Math.max(0,Number(occluderAngularRadiusRad)||0),target=Math.max(0,Number(targetAngularRadiusRad)||0),overlapFraction=discOverlapFraction(occ,target,separation),overlap=overlapFraction>0,classification=!overlap?'NO_PRESENTATION_OVERLAP':overlapFraction>=1-1e-9?'TOTAL_PRESENTATION_OCCLUSION_CUE':'PARTIAL_PRESENTATION_OCCLUSION_CUE';return Object.freeze({authority:AUTHORITY,scientificEvidence:false,overlap,overlapFraction,separationRad:separation,occluderAngularRadiusRad:occ,targetAngularRadiusRad:target,classification,limitations:Object.freeze(['Presentation-space angular overlap is not a canonical eclipse prediction.'])})}
function compositeEclipse(illumination,{occluders=[],starAngularRadiusRad=.00465}={}){if(!illumination||!Array.isArray(illumination.lights))throw new TypeError('illumination packet required');if(!Array.isArray(occluders))throw new TypeError('occluders array required');if(occluders.length>64)throw new RangeError('occluder budget exceeded');const rows=illumination.lights.map(light=>{let maxFraction=0,best=null;for(const occ of occluders){if(!occ||!Array.isArray(occ.direction3d))throw new TypeError('occluder direction3d required');const radius=typeof starAngularRadiusRad==='object'&&starAngularRadiusRad?Number(starAngularRadiusRad[light.starCanonicalEntityId]??.00465):Number(starAngularRadiusRad),cue=presentationOcclusion({lightDirection3d:light.direction3d,occluderDirection3d:occ.direction3d,occluderAngularRadiusRad:occ.angularRadiusRad,targetAngularRadiusRad:radius});if(cue.overlapFraction>maxFraction){maxFraction=cue.overlapFraction;best=occ.canonicalEntityId??occ.id??null}}return Object.freeze({starCanonicalEntityId:light.starCanonicalEntityId,normalizedWeight:Number(light.normalizedWeight)||0,occludedFraction:maxFraction,visibleFraction:1-maxFraction,dominantOccluderCanonicalEntityId:best,authority:AUTHORITY})}),weightedOcclusion=clamp(rows.reduce((n,row)=>n+row.normalizedWeight*row.occludedFraction,0),0,1),classification=weightedOcclusion<=1e-9?'NO_PRESENTATION_ECLIPSE':weightedOcclusion>=1-1e-9?'TOTAL_PRESENTATION_ECLIPSE_CUE':'PARTIAL_PRESENTATION_ECLIPSE_CUE';return Object.freeze({authority:AUTHORITY,scientificEvidence:false,classification,weightedOcclusion,weightedVisibility:1-weightedOcclusion,perStar:Object.freeze(rows),resourceUsage:Object.freeze({stars:rows.length,occluders:occluders.length,maxOccluders:64}),limitations:Object.freeze(['Composite eclipse is a bounded presentation cue over supplied angular inputs, not canonical orbital event truth.','Multiple occluders are conservatively reduced to the strongest overlap per stellar source rather than physical union-area integration.'])})}
O.v2x04BodyCues=Object.freeze({VERSION:'ofu-v2x-04-body-cues-3',AUTHORITY,knownAtmosphere,knownRings,knownRadius,atmospherePresentation,ringsPresentation,bodyCues,discOverlapFraction,presentationOcclusion,compositeEclipse});
})(typeof globalThis!=='undefined'?globalThis:this);
