(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,B=O.v1Biology;if(!V||!B)throw new Error('v1 biology provider prerequisites missing');
const VERSION='ofu-v1-life-provider-1',MAX_CACHE=12,cache=new Map(),metrics={builds:0,hits:0,regions:0,locals:0};
function key(worldIdentity,sourceDigest,ageMyr,epochs,generationsPerEpoch,occupancyParameterPpm,energyBudgetUnits,populationCount){return [VERSION,worldIdentity,sourceDigest,ageMyr,epochs,generationsPerEpoch,occupancyParameterPpm,energyBudgetUnits,populationCount].join(':');}
function buildFromEnvironment({worldIdentity,environment,ageMyr=1000,evolutionEpochs=0,generationsPerEpoch=96,occupancyParameterPpm=420000,energyBudgetUnits=1000000,populationCount=18}){V.text(worldIdentity,'worldIdentity',128);V.int(ageMyr,'ageMyr',0,20000);V.int(evolutionEpochs,'evolutionEpochs',0,64);const sourceDigest=V.digest('OFU-V1-LIFE-ENVIRONMENT',environment),k=key(worldIdentity,sourceDigest,ageMyr,evolutionEpochs,generationsPerEpoch,occupancyParameterPpm,energyBudgetUnits,populationCount);if(cache.has(k)){metrics.hits++;return cache.get(k);}const value=B.buildBiosphere({worldIdentity,environment,ageMyr,evolutionEpochs,generationsPerEpoch,occupancyParameterPpm,energyBudgetUnits,populationCount});metrics.builds++;if(cache.size>=MAX_CACHE)cache.delete(cache.keys().next().value);cache.set(k,value);return value;}
function buildFromPlanetology({worldIdentity,planetology,ageMyr=1000,evolutionEpochs=0,generationsPerEpoch=96,occupancyParameterPpm=420000,energyBudgetUnits=1000000,populationCount=18}){const environment=B.environmentFromPlanetology(planetology);return buildFromEnvironment({worldIdentity,environment,ageMyr,evolutionEpochs,generationsPerEpoch,occupancyParameterPpm,energyBudgetUnits,populationCount});}
function inspect(biosphere){const e=biosphere.eligibility,eco=biosphere.ecosystem,i=biosphere.intelligence;return Object.freeze({state:eco.state,opportunityClass:e.opportunityClass,opportunityScorePpm:e.opportunityScorePpm,limitingFactors:e.limitingFactors.filter(x=>x.limiting),possibleMetabolicRegimes:e.possibleMetabolicRegimes,spatialNiches:e.spatialNiches,biosphereEstablished:biosphere.occupancy.biosphereEstablished,generation:eco.generation,successionStage:eco.successionStage,biomassUnits:eco.ecology?.biomassUnits||0,diversityPpm:eco.ecology?.diversityPpm||0,intelligenceCandidate:!!i.eligible,uncertaintyPpm:e.uncertaintyPpm,authority:'MODEL_DERIVED_SIMULATION',canonicalP6Unchanged:true});}
function queryRegion(biosphere,{regionIdentity,environment=null,capacity=24}){metrics.regions++;return B.biogeographicRefine(biosphere.ecosystem,{regionIdentity,environment,capacity});}
function queryLocal(region,{locationIdentity,capacity=12}){metrics.locals++;return B.localLifeQuery(region,{locationIdentity,capacity});}
function rendererSnapshot(biosphere,{regionIdentity=null,locationIdentity=null,capacity=12}={}){let region=null,local=null;if(regionIdentity){region=queryRegion(biosphere,{regionIdentity,capacity:Math.min(48,capacity*2)});if(locationIdentity)local=queryLocal(region,{locationIdentity,capacity});}const populations=(local?.populations||region?.populations||biosphere.ecosystem.populations||[]).slice(0,capacity);return Object.freeze({biosphereState:biosphere.ecosystem.state,biome:local?.biome||region?.biome||null,productivityPpm:region?.productivityPpm||biosphere.ecosystem.ecology?.productivityPpm||0,biomassUnits:region?.biomassUnits||biosphere.ecosystem.ecology?.biomassUnits||0,densityPpm:local?.populations?.length?Math.floor(local.populations.reduce((n,x)=>n+x.localDensityPpm,0)/local.populations.length):0,dominantStrategies:region?.dominantStrategies||[],organisms:populations.map(B.morphologyHints),fossilOrTracePotential:biosphere.traceEvidence.evidence.slice(0,12),authority:'MODEL_DERIVED_SIMULATION',presentationAuthoritative:false,canonicalP6Unchanged:true});}
function snapshot(){return Object.freeze({version:VERSION,cacheEntries:cache.size,cacheLimit:MAX_CACHE,metrics:{...metrics},authority:'MODEL_DERIVED_SIMULATION'});}
O.v1LifeProvider=Object.freeze({VERSION,buildFromEnvironment,buildFromPlanetology,inspect,queryRegion,queryLocal,rendererSnapshot,snapshot});
})(globalThis);
