(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-v2x-03-neighborhood-depth-5',AUTHORITY='PRESENTATION_ONLY',MAX_OBJECTS=64;
const freeze=v=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
function finite(value,label){const n=Number(value);if(!Number.isFinite(n))throw new TypeError(label+' must be finite');return n}
function keySnapshot(value){const seen=new WeakSet(),state={nodes:0};function walk(v,depth){if(depth>16)throw new RangeError('canonicalKey exceeds depth bound');if(v===null)return null;const t=typeof v;if(t==='string'){if(v.length>512)throw new RangeError('canonicalKey string exceeds bound');return v}if(t==='number'){if(!Number.isFinite(v))throw new TypeError('canonicalKey numbers must be finite');return Object.is(v,-0)?0:v}if(t==='boolean')return v;if(t!=='object')throw new TypeError('canonicalKey contains unsupported value');if(seen.has(v))throw new TypeError('canonicalKey must be acyclic');seen.add(v);if(++state.nodes>256)throw new RangeError('canonicalKey exceeds node bound');let out;if(Array.isArray(v)){if(v.length>64)throw new RangeError('canonicalKey array exceeds bound');out=v.map(item=>walk(item,depth+1))}else{const proto=Object.getPrototypeOf(v);if(proto!==Object.prototype&&proto!==null)throw new TypeError('canonicalKey must contain plain data objects');const keys=Object.keys(v).sort();if(keys.length>64)throw new RangeError('canonicalKey object exceeds key bound');out={};for(const key of keys){if(key.length>128)throw new RangeError('canonicalKey property exceeds bound');out[key]=walk(v[key],depth+1)}}seen.delete(v);return out}const copy=walk(value,0),stable=JSON.stringify(copy);if(stable.length>8192)throw new RangeError('canonicalKey serialization exceeds bound');return{copy,stable}}
function identityRecord(e){for(const k of ['canonicalId','entityId','id'])if(typeof e?.[k]==='string'&&e[k])return{id:e[k],keyCopy:null};if(e?.canonicalKey&&typeof e.canonicalKey==='object'){const key=keySnapshot(e.canonicalKey);return{id:'canonicalKey:'+key.stable,keyCopy:key.copy}}throw new TypeError('stable upstream identity required')}
function qualityCap(quality){return({LOW:20,MOBILE:28,STANDARD:48,HIGH:64}[String(quality).toUpperCase()]||48)}
function ordered(objects){const seen=new Set(),stable=[];for(const source of objects){const identity=identityRecord(source);if(seen.has(identity.id))throw new Error('duplicate upstream identity '+identity.id);seen.add(identity.id);stable.push({id:identity.id,keyCopy:identity.keyCopy,source})}stable.sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);return stable}
function sourcePoint(source){return source.position||source.presentationPosition||source.sourcePosition||null}
function project({objects=[],cameraFrame,scaleUnits=36,quality='STANDARD'}={}){
 const S=O.v1x02SpatialUniverse;if(!S)throw new Error('V1X-02 spatial universe provider required');if(!cameraFrame)throw new TypeError('external camera frame required');if(!Array.isArray(objects))throw new TypeError('objects array required');const scale=finite(scaleUnits,'scaleUnits');if(!(scale>0))throw new RangeError('scaleUnits must be positive');const cap=Math.min(qualityCap(quality),MAX_OBJECTS),materialized=[];let eligible=0;
 for(const {source,id,keyCopy} of ordered(objects)){
  const point=sourcePoint(source);if(!point)continue;eligible++;if(materialized.length>=cap)continue;const view=S.projectPoint(point,cameraFrame),depth=view.depth,depthNorm=clamp(depth/Math.max(1,scale),0,4),apparentScale=view.visible?clamp(1/Math.max(.35,depthNorm),.28,2.2):0,fog=view.visible?clamp((depthNorm-.65)/2.2,0,.78):1,brightnessCue=view.visible?clamp(1-fog*.55,.35,1):0;
  materialized.push(freeze({objectId:'neighborhood:'+id,sourceId:id,canonicalId:source.canonicalId||null,entityId:source.entityId||null,canonicalKey:keyCopy?freeze(keyCopy):null,sourceAuthority:source.sourceAuthority||null,authority:AUTHORITY,view,visual:freeze({apparentScale,fog,brightnessCue,parallaxEligible:view.visible&&depth>0}),selectable:true,navigable:true,claims:freeze({fogPhysical:false,brightnessPhysical:false,positionPhysical:false,identityPreserved:true,inputCanonicalKeyMutated:false})}));
 }
 const drawOrder=materialized.filter(o=>o.view?.visible).slice().sort((a,b)=>b.view.depth-a.view.depth||String(a.sourceId).localeCompare(String(b.sourceId))).map(o=>o.sourceId);
 return freeze({version:VERSION,status:'READY',authority:AUTHORITY,objects:Object.freeze(materialized),drawOrder:Object.freeze(drawOrder),bounds:freeze({requested:objects.length,eligible,materialized:materialized.length,maxMaterialized:MAX_OBJECTS,qualityCap:cap,bounded:true}),stability:freeze({identityKeyed:true,queryOrderIndependent:true,revisitStable:true,invalidPlacementDoesNotConsumeCap:true,drawOrderStable:true,canonicalKeySnapshotBounded:true}),camera:freeze({consumedExternalFrame:true,ownsFrame:false}),claims:freeze({drawOrderIsPresentationOnly:true,physicalOcclusionClaim:false})});
}
function pick(projected,x,y,{radius=0.055}={}){const px=finite(x,'pick x'),py=finite(y,'pick y'),r=finite(radius,'pick radius');if(!(r>0))throw new RangeError('pick radius must be positive');let best=null,bestD=Infinity;for(const o of projected?.objects||[]){if(!o.view?.visible)continue;const d=Math.hypot(Number(o.view.x)-px,Number(o.view.y)-py),better=d<bestD-1e-15||(Math.abs(d-bestD)<=1e-15&&best&&String(o.sourceId)<String(best.sourceId));if(d<=r&&better){best=o;bestD=d}}return best?freeze({handled:true,objectId:best.objectId,sourceId:best.sourceId,canonicalId:best.canonicalId,entityId:best.entityId,canonicalKey:best.canonicalKey,distance:bestD,decorative:false}):freeze({handled:false,decorative:false})}
O.v2x03NeighborhoodDepth=Object.freeze({VERSION,AUTHORITY,MAX_OBJECTS,qualityCap,project,pick});
})(typeof globalThis!=='undefined'?globalThis:this);
