(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-v2x10-persistent-individuals-provider-2';
const AUTHORITY='MODEL_DERIVED_SIMULATION';
const LIMITS=Object.freeze({active:128,memories:16,socialTies:24,skills:16,conventions:16,knowledge:24,stringChars:4096,retainedBytes:262144,parameterBytes:32768,dataNodes:1024,dataDepth:12});
const enc=new TextEncoder();
function fail(message){throw new Error('OFU V2X-10 individuals: '+message)}
function text(value,name,max=LIMITS.stringChars){if(value===undefined||value===null)fail(name+' is required');const v=String(value).normalize('NFC');if(!v.length||v.length>max)fail(name+' exceeds bounded text contract');return v}
function part(value,name){const v=text(value,name,256);if(/[|\u0000-\u001f\u007f]/u.test(v))fail(name+' contains reserved delimiter/control characters');return v}
function ordinal(value,name){if(!Number.isSafeInteger(value)||value<0)fail(name+' must be a non-negative safe integer');return value}
function fnv1a64(value){let hash=0xcbf29ce484222325n;const prime=0x100000001b3n;for(let i=0;i<value.length;i++){hash^=BigInt(value.charCodeAt(i));hash=BigInt.asUintN(64,hash*prime)}return hash.toString(16).padStart(16,'0')}
function hash32(value){let h=2166136261>>>0;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619)>>>0;return h>>>0}
function individualId({worldId,settlementId,birthOrdinal}={}){birthOrdinal=ordinal(birthOrdinal,'birthOrdinal');return 'person:'+fnv1a64(part(worldId,'worldId')+'|'+part(settlementId,'settlementId')+'|'+birthOrdinal)}
function householdId({worldId,settlementId,householdOrdinal}={}){householdOrdinal=ordinal(householdOrdinal,'householdOrdinal');return 'household:'+fnv1a64(part(worldId,'worldId')+'|'+part(settlementId,'settlementId')+'|household|'+householdOrdinal)}
function identity(input={}){return Object.freeze({id:individualId(input),worldId:part(input.worldId,'worldId'),settlementId:part(input.settlementId,'settlementId'),birthOrdinal:input.birthOrdinal,birthYear:Number.isSafeInteger(input.birthYear)?input.birthYear:null,cohortKey:input.cohortKey==null?null:text(input.cohortKey,'cohortKey',512),provenance:AUTHORITY})}
function deep(value,name,maxBytes){const seen=new WeakSet();let nodes=0;function walk(v,depth){if(depth>LIMITS.dataDepth)fail(name+' exceeds depth bound');if(++nodes>LIMITS.dataNodes)fail(name+' exceeds node bound');if(v===null||typeof v==='boolean')return v;if(typeof v==='number'){if(!Number.isFinite(v))fail(name+' contains non-finite number');return Object.is(v,-0)?0:v}if(typeof v==='string')return text(v,name);if(typeof v!=='object')fail(name+' contains unsupported value');if(seen.has(v))fail(name+' must be acyclic');seen.add(v);let out;if(Array.isArray(v)){if(v.length>LIMITS.dataNodes)fail(name+' array exceeds bound');out=v.map(x=>walk(x,depth+1))}else{const proto=Object.getPrototypeOf(v);if(proto!==Object.prototype&&proto!==null)fail(name+' must contain plain records');out={};for(const k of Object.keys(v).sort()){if(k.length>256)fail(name+' key exceeds bound');out[k]=walk(v[k],depth+1)}}seen.delete(v);return out}const out=walk(value,0),serialized=JSON.stringify(out);if(enc.encode(serialized).length>maxBytes)fail(name+' exceeds byte budget');function freeze(v){if(v&&typeof v==='object'){for(const x of Object.values(v))freeze(x);Object.freeze(v)}return v}return freeze(out)}
function bounded(values,max,name='bounded collection'){if(!Array.isArray(values||[]))fail(name+' must be an array');return Object.freeze((values||[]).slice(-max).map(v=>deep(v,name,LIMITS.retainedBytes)))}
function boundedUnique(values,max){return Object.freeze([...new Set((values||[]).map(v=>text(v,'structured convention')))].sort().slice(0,max))}
function culture({settlementConventions=[],householdConventions=[],educationTopics=[],seedTag=''}={}){return Object.freeze({authority:AUTHORITY,semantics:'structured-conventions-not-real-language-or-belief-truth',seedTag:String(seedTag),conventions:boundedUnique([...settlementConventions,...householdConventions],LIMITS.conventions),knowledge:boundedUnique(educationTopics,LIMITS.knowledge)})}
function deterministicInt(value,modulo){let result=2166136261>>>0;for(let i=0;i<value.length;i++)result=Math.imul(result^value.charCodeAt(i),16777619)>>>0;return modulo?result%modulo:result}
function sanitizeRetained(retained,expectedId){if(!retained||retained.id!==expectedId)return null;const durable=Object.freeze({id:expectedId,householdOrdinal:Number.isSafeInteger(retained.householdOrdinal)&&retained.householdOrdinal>=0?retained.householdOrdinal:null,role:retained.role==null?null:text(retained.role,'retained role',256),skills:bounded(retained.skills,LIMITS.skills,'retained skills'),education:bounded(retained.education,LIMITS.skills,'retained education'),knowledge:bounded(retained.knowledge,LIMITS.knowledge,'retained knowledge'),socialTies:bounded(retained.socialTies,LIMITS.socialTies,'retained social ties'),memories:bounded(retained.memories,LIMITS.memories,'retained memories'),culture:retained.culture==null?null:deep(retained.culture,'retained culture',LIMITS.retainedBytes),lineage:retained.lineage==null?null:deep(retained.lineage,'retained lineage',LIMITS.retainedBytes)});if(enc.encode(JSON.stringify(durable)).length>LIMITS.retainedBytes)fail('retained state exceeds provider byte budget');return durable}
function materialize({worldId,settlementId,birthOrdinal,birthYear=null,cohortKey=null,currentYear=0,aggregate={},retained=null}={}){
 const personIdentity=identity({worldId,settlementId,birthOrdinal,birthYear,cohortKey}),durable=sanitizeRetained(retained,personIdentity.id);
 const householdSize=Number.isSafeInteger(aggregate.householdSizeEstimate)&&aggregate.householdSizeEstimate>0?Math.min(32,aggregate.householdSizeEstimate):null,householdOrdinal=durable?.householdOrdinal??(householdSize===null?null:Math.floor(birthOrdinal/householdSize)),roles=Array.isArray(aggregate.roles)&&aggregate.roles.length?aggregate.roles.slice(0,128).map(v=>text(v,'aggregate role',256)):[],role=durable?.role??(roles.length?roles[deterministicInt(personIdentity.id,roles.length)]:null),profile=durable?.culture||culture({settlementConventions:aggregate.cultureConventions||[],educationTopics:aggregate.educationTopics||[],seedTag:personIdentity.id});
 if(!Number.isSafeInteger(currentYear)||currentYear<0)fail('currentYear must be a non-negative safe integer');if(Number.isSafeInteger(personIdentity.birthYear)&&currentYear<personIdentity.birthYear)fail('currentYear cannot precede birthYear');const age=Number.isSafeInteger(personIdentity.birthYear)?currentYear-personIdentity.birthYear:null;
 return Object.freeze({schema:'ofu-individual-2',...personIdentity,age,householdOrdinal,householdId:householdOrdinal===null?null:householdId({worldId,settlementId,householdOrdinal}),householdAuthority:householdOrdinal===null?'UNKNOWN_WITHHELD_NO_GROUPING_EVIDENCE':'MODEL_DERIVED_GROUPING_NOT_KINSHIP',roleAuthority:role===null?'UNKNOWN_WITHHELD_NO_ROLE_EVIDENCE':'MODEL_DERIVED_FROM_AGGREGATE_OR_RETAINED',role,skills:durable?.skills||Object.freeze([]),education:durable?.education||Object.freeze([]),knowledge:durable?.knowledge||Object.freeze([]),socialTies:durable?.socialTies||Object.freeze([]),memories:durable?.memories||Object.freeze([]),culture:profile,lineage:durable?.lineage||Object.freeze({parentIds:Object.freeze([]),relations:Object.freeze([]),status:'UNKNOWN_UNLESS_RETAINED'})})
}
function refine({worldId,settlementId,aggregate,startOrdinal=0,count=1,retainedById=null,currentYear=0}={}){
 if(!aggregate||!Number.isSafeInteger(aggregate.population)||aggregate.population<0)fail('aggregate.population must be a non-negative safe integer');ordinal(startOrdinal,'startOrdinal');ordinal(count,'count');const addressable=Number.isSafeInteger(aggregate.nextBirthOrdinal)?aggregate.nextBirthOrdinal:aggregate.population;if(addressable<aggregate.population)fail('aggregate.nextBirthOrdinal cannot be below living population');const n=Math.min(count,LIMITS.active,Math.max(0,addressable-startOrdinal),aggregate.population),people=[];
 for(let offset=0;offset<n;offset++){const birthOrdinal=startOrdinal+offset,birthYear=aggregate.birthYears?.[birthOrdinal]??null,id=individualId({worldId,settlementId,birthOrdinal});people.push(materialize({worldId,settlementId,birthOrdinal,birthYear,currentYear,aggregate,retained:retainedById?.get?.(id)||null}))}return Object.freeze(people)
}
function demographyPools(ledger){const out=[];if(ledger.initialPopulation>0)out.push({key:ledger.settlementId+':legacy',firstBirthOrdinal:0,births:ledger.initialPopulation,deaths:ledger.legacyDeaths,living:ledger.legacyLiving,birthYear:null,cohortKey:null});for(const c of ledger.cohorts||[])out.push({key:c.key,firstBirthOrdinal:c.firstBirthOrdinal,births:c.births,deaths:c.deaths,living:c.living,birthYear:c.startYear,cohortKey:c.key});return out.sort((a,b)=>a.firstBirthOrdinal-b.firstBirthOrdinal)}
function rotatedOrdinal(pool,local){const n=BigInt(pool.births),rotation=BigInt(hash32(pool.key))%n,rank=BigInt(pool.deaths+local),value=Number(BigInt(pool.firstBirthOrdinal)+(rank-rotation+n)%n);if(!Number.isSafeInteger(value))fail('birth ordinal exceeds safe integer range');return value}
function selectLiving(ledger,start,count){ordinal(start,'start');ordinal(count,'count');if(start>=ledger.population||count===0)return[];const wanted=Math.min(count,ledger.population-start),out=[];let cursor=0;for(const pool of demographyPools(ledger)){if(out.length>=wanted)break;const end=cursor+pool.living;if(!Number.isSafeInteger(end))fail('living cursor exceeds safe integer range');if(start<end){const localStart=Math.max(0,start-cursor);for(let local=localStart;local<pool.living&&out.length<wanted;local++)out.push({birthOrdinal:rotatedOrdinal(pool,local),birthYear:pool.birthYear,cohortKey:pool.cohortKey})}cursor=end}return out}
function refinePopulation({worldId,ledger,aggregate={},start=0,count=1,retainedById=null,currentYear=ledger?.currentYear??0}={}){if(!ledger)fail('ledger is required');return Object.freeze(selectLiving(ledger,start,Math.min(count,LIMITS.active)).map(member=>{const id=individualId({worldId,settlementId:ledger.settlementId,birthOrdinal:member.birthOrdinal});return materialize({worldId,settlementId:ledger.settlementId,birthOrdinal:member.birthOrdinal,birthYear:member.birthYear,cohortKey:member.cohortKey,currentYear,aggregate:{...aggregate,population:ledger.population,nextBirthOrdinal:ledger.nextBirthOrdinal},retained:retainedById?.get?.(id)||null})}))}
function retain(person){const out=Object.freeze({id:text(person.id,'person.id',256),householdOrdinal:Number.isSafeInteger(person.householdOrdinal)&&person.householdOrdinal>=0?person.householdOrdinal:null,role:person.role==null?null:text(person.role,'person.role',256),skills:bounded(person.skills,LIMITS.skills,'skills'),education:bounded(person.education,LIMITS.skills,'education'),knowledge:bounded(person.knowledge,LIMITS.knowledge,'knowledge'),socialTies:bounded(person.socialTies,LIMITS.socialTies,'social ties'),memories:bounded(person.memories,LIMITS.memories,'memories'),culture:deep(person.culture||{},'culture',LIMITS.retainedBytes),lineage:deep(person.lineage||{parentIds:[],relations:[],status:'UNKNOWN_UNLESS_RETAINED'},'lineage',LIMITS.retainedBytes)});if(enc.encode(JSON.stringify(out)).length>LIMITS.retainedBytes)fail('retained state exceeds provider byte budget');return out}
function appendHistoryRef(person,ref){if(!ref?.eventId||!ref?.provenance)fail('history ref requires eventId and provenance');return Object.freeze({...person,memories:bounded([...person.memories,{eventId:text(ref.eventId,'eventId'),provenance:text(ref.provenance,'provenance',256),kind:text(ref.kind||'OBSERVED','kind',128)}],LIMITS.memories,'memories')})}
function propose(person,proposal){if(!person?.id)fail('person.id is required');if(!proposal?.kind)fail('proposal.kind is required');return Object.freeze({schema:'ofu-individual-action-proposal-1',authority:'PROPOSAL_ONLY_REQUIRES_P4_ADMISSION',actorId:text(person.id,'person.id',256),kind:text(proposal.kind,'proposal.kind',128),targetId:proposal.targetId==null?null:text(proposal.targetId,'proposal.targetId',256),parameters:deep(proposal.parameters||{},'proposal.parameters',LIMITS.parameterBytes)})}
function project(people=[]){const roles={};for(const p of people){const r=String(p.role);roles[r]=(roles[r]||0)+1}return Object.freeze({materializedCount:people.length,roleCounts:Object.freeze(Object.fromEntries(Object.entries(roles).sort(([a],[b])=>a<b?-1:a>b?1:0)))})}
function reconcile({aggregate,people=[],startOrdinal=0}={}){if(!aggregate||!Number.isSafeInteger(aggregate.population)||aggregate.population<0)fail('aggregate.population is required');const addressable=Number.isSafeInteger(aggregate.nextBirthOrdinal)?aggregate.nextBirthOrdinal:aggregate.population;if(addressable<aggregate.population)fail('aggregate.nextBirthOrdinal cannot be below living population');const ids=new Set(),ordinals=new Set(),defects=[];for(const p of people){if(ids.has(p.id))defects.push('duplicate-id:'+p.id);ids.add(p.id);if(ordinals.has(p.birthOrdinal))defects.push('duplicate-ordinal:'+p.birthOrdinal);ordinals.add(p.birthOrdinal);if(p.birthOrdinal<startOrdinal||p.birthOrdinal>=addressable)defects.push('ordinal-outside-address-space:'+p.birthOrdinal);try{const expected=individualId(p);if(expected!==p.id)defects.push('identity-address-mismatch:'+p.id+':'+expected)}catch(e){defects.push('invalid-identity-address:'+String(p.id||'unknown'))}}if(people.length>aggregate.population)defects.push('materialized-count-exceeds-living-aggregate');return Object.freeze({status:defects.length?'FAIL':'PASS',defects:Object.freeze(defects),projection:project(people),aggregatePopulation:aggregate.population,addressableBirths:addressable})}
function descriptor(){return Object.freeze({id:'v2x10.model.persistent-individuals',version:'2.0.0',authority:AUTHORITY,identity:'WORLD_SETTLEMENT_BIRTH_ORDINAL_FNV1A64_RESERVED_DELIMITER_SAFE',maxActive:LIMITS.active,persistentPersons:'RETAINED_BOUNDED_STATE_ONLY',genealogy:'UNKNOWN_UNLESS_RETAINED',actionAuthority:'PROPOSAL_ONLY_REQUIRES_P4_ADMISSION',canonicalMutation:false,byteBudget:LIMITS.retainedBytes,mortalityAwareRefinement:true})}
O.v2x10Individuals=Object.freeze({VERSION,AUTHORITY,LIMITS,individualId,householdId,identity,culture,materialize,refine,refinePopulation,retain,appendHistoryRef,propose,project,reconcile,descriptor});
})(typeof globalThis!=='undefined'?globalThis:this);
