(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-v2x10-persistent-individuals-provider-1';
const AUTHORITY='MODEL_DERIVED_SIMULATION';
const LIMITS=Object.freeze({active:128,memories:16,socialTies:24,skills:16,conventions:16,knowledge:24});
function fail(message){throw new Error('OFU V2X-10 individuals: '+message)}
function part(value,name){if(value===undefined||value===null||value==='')fail(name+' is required');return String(value).normalize('NFC')}
function ordinal(value,name){if(!Number.isSafeInteger(value)||value<0)fail(name+' must be a non-negative safe integer');return value}
function fnv1a64(text){let hash=0xcbf29ce484222325n;const prime=0x100000001b3n;for(let i=0;i<text.length;i++){hash^=BigInt(text.charCodeAt(i));hash=BigInt.asUintN(64,hash*prime)}return hash.toString(16).padStart(16,'0')}
function individualId({worldId,settlementId,birthOrdinal}={}){birthOrdinal=ordinal(birthOrdinal,'birthOrdinal');return 'person:'+fnv1a64(part(worldId,'worldId')+'|'+part(settlementId,'settlementId')+'|'+birthOrdinal)}
function householdId({worldId,settlementId,householdOrdinal}={}){householdOrdinal=ordinal(householdOrdinal,'householdOrdinal');return 'household:'+fnv1a64(part(worldId,'worldId')+'|'+part(settlementId,'settlementId')+'|household|'+householdOrdinal)}
function identity(input={}){return Object.freeze({id:individualId(input),worldId:part(input.worldId,'worldId'),settlementId:part(input.settlementId,'settlementId'),birthOrdinal:input.birthOrdinal,birthYear:Number.isSafeInteger(input.birthYear)?input.birthYear:null,cohortKey:input.cohortKey==null?null:String(input.cohortKey),provenance:input.provenance||AUTHORITY})}
function boundedUnique(values,max){return Object.freeze([...new Set((values||[]).map(String))].sort().slice(0,max))}
function culture({settlementConventions=[],householdConventions=[],educationTopics=[],seedTag=''}={}){return Object.freeze({authority:AUTHORITY,semantics:'structured-conventions-not-real-language-or-belief-truth',seedTag:String(seedTag),conventions:boundedUnique([...settlementConventions,...householdConventions],LIMITS.conventions),knowledge:boundedUnique(educationTopics,LIMITS.knowledge)})}
function bounded(values,max){return Object.freeze((values||[]).slice(-max).map(value=>typeof value==='object'&&value!==null?Object.freeze({...value}):value))}
function deterministicInt(text,modulo){let value=2166136261>>>0;for(let i=0;i<text.length;i++)value=Math.imul(value^text.charCodeAt(i),16777619)>>>0;return modulo?value%modulo:value}
function materialize({worldId,settlementId,birthOrdinal,birthYear=null,cohortKey=null,currentYear=0,aggregate={},retained=null}={}){
 const personIdentity=identity({worldId,settlementId,birthOrdinal,birthYear,cohortKey}),durable=retained&&retained.id===personIdentity.id?retained:null;
 const householdSize=Number.isSafeInteger(aggregate.householdSizeEstimate)&&aggregate.householdSizeEstimate>0?Math.min(32,aggregate.householdSizeEstimate):4,householdOrdinal=durable?.householdOrdinal??Math.floor(birthOrdinal/householdSize),roles=aggregate.roles?.length?aggregate.roles:['resident'],role=durable?.role||String(roles[deterministicInt(personIdentity.id,roles.length)]),profile=durable?.culture||culture({settlementConventions:aggregate.cultureConventions||[],educationTopics:aggregate.educationTopics||[],seedTag:personIdentity.id}),age=Number.isSafeInteger(personIdentity.birthYear)?Math.max(0,currentYear-personIdentity.birthYear):null;
 return Object.freeze({schema:'ofu-individual-2',...personIdentity,age,householdOrdinal,householdId:householdId({worldId,settlementId,householdOrdinal}),householdAuthority:'MODEL_DERIVED_GROUPING_NOT_KINSHIP',role,skills:durable?.skills||Object.freeze([]),education:durable?.education||Object.freeze([]),knowledge:durable?.knowledge||Object.freeze([]),socialTies:durable?.socialTies||Object.freeze([]),memories:durable?.memories||Object.freeze([]),culture:profile,lineage:durable?.lineage||Object.freeze({parentIds:Object.freeze([]),relations:Object.freeze([]),status:'UNKNOWN_UNLESS_RETAINED'})})
}
function refine({worldId,settlementId,aggregate,startOrdinal=0,count=1,retainedById=null,currentYear=0}={}){
 if(!aggregate||!Number.isSafeInteger(aggregate.population)||aggregate.population<0)fail('aggregate.population must be a non-negative safe integer');ordinal(startOrdinal,'startOrdinal');ordinal(count,'count');const addressable=Number.isSafeInteger(aggregate.nextBirthOrdinal)?aggregate.nextBirthOrdinal:aggregate.population,n=Math.min(count,LIMITS.active,Math.max(0,addressable-startOrdinal),aggregate.population),people=[];
 for(let offset=0;offset<n;offset++){const birthOrdinal=startOrdinal+offset,birthYear=aggregate.birthYears?.[birthOrdinal]??null,id=individualId({worldId,settlementId,birthOrdinal});people.push(materialize({worldId,settlementId,birthOrdinal,birthYear,currentYear,aggregate,retained:retainedById?.get?.(id)||null}))}return Object.freeze(people)
}
function retain(person){return Object.freeze({id:person.id,householdOrdinal:person.householdOrdinal,role:person.role,skills:bounded(person.skills,LIMITS.skills),education:bounded(person.education,LIMITS.skills),knowledge:bounded(person.knowledge,LIMITS.skills),socialTies:bounded(person.socialTies,LIMITS.socialTies),memories:bounded(person.memories,LIMITS.memories),culture:person.culture,lineage:person.lineage})}
function appendHistoryRef(person,ref){if(!ref?.eventId||!ref?.provenance)fail('history ref requires eventId and provenance');return Object.freeze({...person,memories:bounded([...person.memories,{eventId:String(ref.eventId),provenance:String(ref.provenance),kind:String(ref.kind||'OBSERVED')}],LIMITS.memories)})}
function propose(person,proposal){if(!proposal?.kind)fail('proposal.kind is required');return Object.freeze({schema:'ofu-individual-action-proposal-1',authority:'PROPOSAL_ONLY_REQUIRES_P4_ADMISSION',actorId:person.id,kind:String(proposal.kind),targetId:proposal.targetId==null?null:String(proposal.targetId),parameters:Object.freeze({...proposal.parameters||{}})})}
function descriptor(){return Object.freeze({id:'v2x10.model.persistent-individuals',version:'1.0.0',authority:AUTHORITY,identity:'WORLD_SETTLEMENT_BIRTH_ORDINAL_FNV1A64',maxActive:LIMITS.active,persistentPersons:'RETAINED_BOUNDED_STATE_ONLY',genealogy:'UNKNOWN_UNLESS_RETAINED',actionAuthority:'PROPOSAL_ONLY_REQUIRES_P4_ADMISSION',canonicalMutation:false})}
O.v2x10Individuals=Object.freeze({VERSION,AUTHORITY,LIMITS,individualId,householdId,identity,culture,materialize,refine,retain,appendHistoryRef,propose,descriptor});
})(typeof globalThis!=='undefined'?globalThis:this);
