(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress;
if(!P||!S)throw new Error('Deep3D local adapter dependencies missing');
const VERSION='ofu-deep3d-local-adapter-1',AUTHORITY='PRESENTATION_ONLY',STAGES=Object.freeze(['HUMAN']);
const LIMITS=Object.freeze({maxTerrainVertices:2304,maxObjects:768,maxObjectVertices:27648,maxPackets:16,maxGpuBytes:8388608});
const COLORS=Object.freeze({WATER:[.12,.38,.56],ICE:[.73,.86,.9],SOIL:[.38,.48,.27],ROCK:[.38,.34,.3],SEDIMENT:[.52,.39,.25],TERRAIN:[.35,.32,.27],VEGETATION:[.23,.48,.29],ORGANISM:[.5,.66,.42],STRUCTURE:[.56,.48,.37],LOCAL:[.47,.4,.3]});
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const flat=rows=>rows.reduce((out,row)=>out.concat(row),[]);
function materialKey(sample={}){const value=(String(sample.surfaceClass||'')+' '+String(sample.materialFamily||'')).toUpperCase();if(value.includes('WATER'))return'WATER';if(value.includes('ICE'))return'ICE';if(value.includes('SOIL')||value.includes('TEMPERATE'))return'SOIL';if(value.includes('ROCK')||value.includes('BARREN'))return'ROCK';if(value.includes('SEDIMENT')||value.includes('REGOLITH')||value.includes('DRY'))return'SEDIMENT';return'TERRAIN'}
function objectKey(kind){const value=String(kind||'LOCAL').toUpperCase();if(/VEGETATION|TREE|PLANT/.test(value))return'VEGETATION';if(/ORGANISM|ANIMAL|PERSON|INDIVIDUAL/.test(value))return'ORGANISM';if(/BUILDING|STRUCTURE|SETTLEMENT|RUIN/.test(value))return'STRUCTURE';return'LOCAL'}
function localPoint(value,camera){if(!Array.isArray(value)||value.length!==3)throw new TypeError('local point vec3 required');const x=finite(value[0],'local x'),forward=finite(value[1],'local forward'),up=finite(value[2],'local up');return[x-camera[0],up-camera[1],-forward-camera[2]]}
function normal(a,b,c){const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]],n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],d=Math.hypot(...n)||1;return n.map(x=>x/d)}
function appendTriangle(positions,normals,a,b,c){const n=normal(a,b,c);positions.push(a,b,c);normals.push(n,n,n)}
function appendObject(positions,normals,obj,camera){const p=obj.positionM,r=Math.max(.05,finite(obj.radiusM,'object radius')),h=Math.max(.1,finite(obj.heightM,'object height')),x=finite(p?.[0],'object x'),y=finite(p?.[1],'object y'),z=finite(p?.[2],'object z'),v=[[-r,0,-r],[r,0,-r],[r,0,r],[-r,0,r],[-r,h,-r],[r,h,-r],[r,h,r],[-r,h,r]].map(q=>localPoint([x+q[0],y-q[2],z+q[1]],camera)),faces=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];for(const f of faces)appendTriangle(positions,normals,v[f[0]],v[f[1]],v[f[2]])}
function packet({id,domain,positions,normals,color,address,state,entityIds=[],claims={}}){return P.createPacket({packetId:'local:'+id,family:'MESH',entityId:null,representationId:'deep3d-v2x07-'+id+'-1',lodKey:String(state.stage)+':'+positions.length,spatialAddress:address,provenance:'PRESENTATION_ONLY',presentationSeed:String(state.anchorToken),semanticState:{...state,entityIds},geometry:{domain,coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flat(positions),normals:flat(normals),lit:true,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:true},material:{baseColor:color,emissive:[.012,.014,.01],roughness:.82,metallic:0,opacity:1},lighting:{model:'DIRECTIONAL_AMBIENT',authority:AUTHORITY},picking:{entityIds,selectionAuthority:'UPSTREAM_LOCAL_PICK_CONTRACT'},resources:{vertices:positions.length,cpuBytes:positions.length*24,gpuBytes:positions.length*24},claims:{canonical:false,canonicalPosition:false,physicalElevation:false,identityInvented:false,sourceAuthorityPreserved:true,...claims}})}
function createRenderScene(localFrame,{stage='HUMAN',cameraPosition=[0,0,0],viewportClass='desktop',semanticSelection=null}={}){
 const band=String(stage).toUpperCase();if(!STAGES.includes(band))throw new Error('unsupported Deep3D local stage '+band);if(!localFrame||localFrame.authority!==AUTHORITY||!localFrame.terrain||!localFrame.embodiment)throw new TypeError('V2X-07 local materialization required');const camera=Array.from(cameraPosition,(v,i)=>finite(v,'cameraPosition['+i+']'));if(camera.length!==3)throw new TypeError('cameraPosition vec3 required');const terrain=localFrame.terrain,objects=localFrame.embodiment.objects||[];if((terrain.vertices?.length||0)>LIMITS.maxTerrainVertices||objects.length>LIMITS.maxObjects)throw new RangeError('local adapter input bound exceeded');
 const planetId=String(localFrame.embodiment.planetId||localFrame.terrain.camera?.planetId||''),anchorToken=String(localFrame.embodiment.anchorToken||localFrame.terrain.camera?.anchorToken||'');if(!planetId||!anchorToken)throw new Error('local planet and anchor identity required');const addr=S.create({frameId:'local:'+anchorToken,hierarchy:['universe','planet',planetId,'surface',anchorToken,'human'],nativeKey:{planetId,anchorToken},local:[0,0,0],unit:'LOCAL_TANGENT_PRESENTATION',parentFrameId:'surface:'+anchorToken,transformRevision:String(localFrame.version||VERSION)}),terrainGroups=new Map,packets=[];
 if(terrain.supported)for(const tri of terrain.triangles||[]){if(!Array.isArray(tri)||tri.length!==3)throw new TypeError('local terrain triangle required');const material=materialKey(terrain.vertexSamples?.[tri[0]]),meanHeight=tri.reduce((sum,i)=>sum+finite(terrain.vertices[i]?.[2],'terrain height'),0)/3,reliefBand=Math.round(Math.max(-2,Math.min(2,meanHeight/4))),preferred=material+'|'+reliefBand,key=terrainGroups.has(preferred)||terrainGroups.size<10?preferred:material+'|0',group=terrainGroups.get(key)||{positions:[],normals:[],authorities:new Set,material,reliefBand:key.endsWith('|0')?0:reliefBand};const points=tri.map(i=>localPoint(terrain.vertices[i],camera));appendTriangle(group.positions,group.normals,...points);for(const i of tri)group.authorities.add(String(terrain.vertexSamples?.[i]?.sourceAuthority||'UNSPECIFIED_SOURCE_AUTHORITY'));terrainGroups.set(key,group)}
 for(const [key,group] of [...terrainGroups].sort((a,b)=>a[0].localeCompare(b[0]))){const shade=.9+group.reliefBand*.055,color=COLORS[group.material].map(x=>Math.max(0,Math.min(1,x*shade)));packets.push(packet({id:'terrain:'+key.toLowerCase().replace('|',':'),domain:'TERRAIN',positions:group.positions,normals:group.normals,color,address:addr,state:{stage:band,planetId,anchorToken,sourceAuthorities:[...group.authorities].sort(),sourceAuthorityClass:'MODEL_OR_PRESENTATION_INHERITED',reliefBand:group.reliefBand},claims:{presentationReliefShading:true}}))}
 const grid=terrain.grid;if(terrain.supported&&grid&&terrain.vertices.length===grid.cols*grid.rows){const lines=[];for(let j=0;j<grid.rows;j+=2)for(let i=0;i+1<grid.cols;i++)lines.push(localPoint(terrain.vertices[j*grid.cols+i],camera),localPoint(terrain.vertices[j*grid.cols+i+1],camera));for(let i=0;i<grid.cols;i+=2)for(let j=0;j+1<grid.rows;j++)lines.push(localPoint(terrain.vertices[j*grid.cols+i],camera),localPoint(terrain.vertices[(j+1)*grid.cols+i],camera));if(lines.length)packets.push(P.createPacket({packetId:'local:terrain-grid',family:'CURVE',entityId:null,representationId:'deep3d-v2x07-terrain-grid-1',lodKey:band+':'+lines.length,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:anchorToken,semanticState:{stage:band,planetId,anchorToken,sourceAuthority:'PRESENTATION_ONLY',gridStride:2},geometry:{domain:'TERRAIN',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flat(lines),curveTopology:'SEGMENTS',lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[.19,.26,.23],emissive:[.006,.01,.008],roughness:1,metallic:0,opacity:.62},picking:{entityIds:[],selectionAuthority:'UPSTREAM_LOCAL_PICK_CONTRACT'},resources:{vertices:lines.length,cpuBytes:lines.length*12,gpuBytes:lines.length*12},claims:{canonical:false,presentationTopologyCue:true,physicalGridClaim:false,canonicalGeodesy:false}}))}
 const objectGroups=new Map;for(const obj of objects){const key=objectKey(obj.kind),group=objectGroups.get(key)||{positions:[],normals:[],entityIds:[],authorities:new Set};appendObject(group.positions,group.normals,obj,camera);group.entityIds.push(String(obj.id||obj.pickKey));group.authorities.add(String(obj.sourceAuthority||'UNSPECIFIED_SOURCE_AUTHORITY'));objectGroups.set(key,group)}
 for(const [key,group] of [...objectGroups].sort((a,b)=>a[0].localeCompare(b[0]))){if(group.positions.length>LIMITS.maxObjectVertices)throw new RangeError('local object vertex bound exceeded');packets.push(packet({id:'objects:'+key.toLowerCase(),domain:key==='LOCAL'?'STRUCTURE':key,positions:group.positions,normals:group.normals,color:COLORS[key],address:addr,state:{stage:band,planetId,anchorToken,sourceAuthorities:[...group.authorities].sort(),persistentIdentityPreserved:true},entityIds:group.entityIds}))}
 const cuePositions=[],cueNormals=[];for(const marker of localFrame.cues?.markers||[]){const distance=finite(marker.distanceM,'scale cue distance'),p=marker.positionM;if(!Array.isArray(p)||p.length!==3)throw new TypeError('scale cue position vec3 required');appendObject(cuePositions,cueNormals,{positionM:p,radiusM:.26+Math.min(50,distance)*.003,heightM:1.7+Math.min(50,distance)*.018},camera)}if(cuePositions.length)packets.push(packet({id:'scale-cues',domain:'STRUCTURE',positions:cuePositions,normals:cueNormals,color:[.68,.76,.58],address:addr,state:{stage:band,planetId,anchorToken,sourceAuthorities:['PRESENTATION_ONLY'],persistentIdentityPreserved:false},claims:{presentationScaleCues:true,scientificMeasurement:false,worldObjectClaim:false}}));
 if(packets.length>LIMITS.maxPackets)throw new RangeError('local packet bound exceeded');const scene=P.createScene({frameId:addr.frameId,cameraPolicyId:'v2x02.authoritative',viewportClass,packets,semanticSelection});if(scene.resourceTotals.gpuBytes>LIMITS.maxGpuBytes)throw new RangeError('local GPU resource bound exceeded');return scene
}
O.deep3dLocalAdapter=Object.freeze({VERSION,AUTHORITY,STAGES,LIMITS,COLORS,materialKey,objectKey,localPoint,createRenderScene,claims:Object.freeze({source:'V2X07_LOCAL_EXPERIENCE_MATERIALIZATION',physicalElevation:false,canonicalGeodesy:false,cameraAuthority:false,selectionAuthority:false,persistentIdentityInvented:false,modelAuthorityPreserved:true})});
})(typeof globalThis!=='undefined'?globalThis:this);
