(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress;
if(!P||!S)throw new Error('Deep3D macro adapter dependencies missing');
const VERSION='ofu-deep3d-macro-adapter-2',AUTHORITY='PRESENTATION_ONLY',CONTEXTS=Object.freeze(['UNIVERSE','GALAXY','REGION','NEIGHBORHOOD']);
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const hash32=input=>{let h=2166136261>>>0;for(const c of String(input)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return h>>>0};
const unit=(seed,k)=>hash32(seed+'\0'+k)/4294967296;
const rel=(p,c)=>[finite(p.x,'position.x')-c[0],finite(p.y,'position.y')-c[1],finite(p.z,'position.z')-c[2]];
const flatten=a=>a.reduce((out,v)=>out.concat(v),[]);
function address(frameId,context,scopeId){return S.create({frameId,hierarchy:['universe',String(context).toLowerCase()],nativeKey:{context,scopeId},local:[0,0,0],unit:'FRAME_NATIVE',parentFrameId:context==='UNIVERSE'?null:'macro:parent',transformRevision:'v1x02-spatial-universe-1'})}
function densityPoints({seed,scaleUnits,morphology='UNKNOWN',count=384}){const m=String(morphology).toUpperCase(),disk=/SPIRAL|DISK|DISC|BARRED/.test(m),points=[];for(let i=0;i<count;i++){const r=Math.pow(unit(seed,i+':r'),.62),a=Math.PI*2*unit(seed,i+':a')+r*(disk?4.8:0),z=(unit(seed,i+':z')*2-1)*(disk?.14:.74),rad=scaleUnits*r;points.push([Math.cos(a)*rad,Math.sin(a)*rad*(disk?.92:.88),z*scaleUnits*r])}return Object.freeze(points.map(Object.freeze))}
function filamentSegments({seed,scaleUnits,morphology='UNKNOWN',mobile=false}){const disk=/SPIRAL|DISK|DISC|BARRED/.test(String(morphology).toUpperCase()),arms=mobile?(disk?2:3):(disk?4:5),steps=mobile?18:34,segments=[];for(let arm=0;arm<arms;arm++){let previous=null;for(let i=0;i<steps;i++){const t=i/(steps-1),phase=Math.PI*2*arm/arms,r=scaleUnits*(.07+.86*t),jitter=(unit(seed,arm+':'+i+':j')-.5)*.055*scaleUnits;let p;if(disk){const a=phase+t*Math.PI*3.6;p=[Math.cos(a)*(r+jitter),Math.sin(a)*(r+jitter)*.9,(unit(seed,arm+':'+i+':z')-.5)*scaleUnits*.11*(.35+t)]}else{const a=phase+t*Math.PI*2.25,b=(t-.5)*Math.PI*.78+(unit(seed,arm+':'+i+':b')-.5)*.12;p=[Math.cos(a)*Math.cos(b)*(r+jitter),Math.sin(b)*(r+jitter),Math.sin(a)*Math.cos(b)*(r+jitter)]}if(previous)segments.push(previous,p);previous=p}}return Object.freeze(segments.map(Object.freeze))}
function createRenderScene(spatial,{frameId='macro',context='UNIVERSE',scopeId='root',cameraPosition=[0,0,0],viewportClass='desktop',semanticSelection=null,morphology='UNKNOWN',scaleUnits=100,densitySeed='OFU-DEEP3D-MACRO-1'}={}){
 const c=String(context).toUpperCase();if(!CONTEXTS.includes(c))throw new Error('unsupported macro context '+c);if(!spatial||!Array.isArray(spatial.objects))throw new TypeError('bounded V1X-02 spatial representation required');if(spatial.objects.length>64)throw new RangeError('macro working set exceeds V1X-02 bound');const cam=cameraPosition.map((v,i)=>finite(v,'cameraPosition['+i+']'));if(cam.length!==3)throw new TypeError('cameraPosition vec3 required');const addr=address(String(frameId),c,String(scopeId)),ids=spatial.objects.map(o=>String(o.canonicalId||o.entityId||o.identity)),positions=spatial.objects.map(o=>rel(o.position,cam)),mobile=String(viewportClass).toLowerCase().includes('mobile'),scale=finite(scaleUnits,'scaleUnits'),densityCount=mobile?128:512,density=densityPoints({seed:densitySeed+'|'+c+'|'+scopeId,scaleUnits:scale,morphology,count:densityCount}).map(p=>[p[0]-cam[0],p[1]-cam[1],p[2]-cam[2]]),filaments=filamentSegments({seed:densitySeed+'|filaments|'+c+'|'+scopeId,scaleUnits:scale,morphology,mobile}).map(p=>[p[0]-cam[0],p[1]-cam[1],p[2]-cam[2]]),packets=[];
 if(positions.length)packets.push(P.createPacket({packetId:'macro:entities:'+c,family:'POINT_BATCH',entityId:null,representationId:'deep3d-macro-identity-points-1',lodKey:String(positions.length),spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:densitySeed,semanticState:{context:c,scopeId:String(scopeId),entityIds:ids,sourceAuthority:spatial.authority||AUTHORITY},geometry:{domain:'MACRO',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flatten(positions),lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:true},material:{baseColor:c==='UNIVERSE'?[.56,.72,.94]:c==='GALAXY'?[1,.79,.52]:[.7,.86,1],emissive:[.06,.08,.12],roughness:1,metallic:0,opacity:.96,pointSize:mobile?5:6},picking:{entityIds:ids,selectionAuthority:'UPSTREAM_SELECTION_CONTRACT'},resources:{points:positions.length,vertices:positions.length,cpuBytes:positions.length*12,gpuBytes:positions.length*12},claims:{physicalCoordinate:false,canonicalIdentityPreserved:true,presentationPositionsOnly:true}}));
 packets.push(P.createPacket({packetId:'macro:density:'+c,family:'POINT_BATCH',entityId:null,representationId:'deep3d-macro-density-field-1',lodKey:String(densityCount),spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:densitySeed,semanticState:{context:c,scopeId:String(scopeId),canonical:false,selectable:false},geometry:{domain:'MACRO',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flatten(density),lit:false,lodLevel:mobile?1:2,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:c==='GALAXY'?[.5,.65,.9]:[.42,.55,.75],emissive:[.025,.035,.06],roughness:1,metallic:0,opacity:mobile?.32:.42,pointSize:mobile?1.25:1.5},picking:{entityIds:[],selectionAuthority:'NONE_PRESENTATION_DENSITY'},resources:{points:densityCount,vertices:densityCount,cpuBytes:densityCount*12,gpuBytes:densityCount*12},claims:{canonical:false,physicalCoordinate:false,discoveryResult:false,selectable:false}}));
 packets.push(P.createPacket({packetId:'macro:filaments:'+c,family:'CURVE',entityId:null,representationId:'deep3d-macro-volumetric-filaments-1',lodKey:String(filaments.length),spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:densitySeed,semanticState:{context:c,scopeId:String(scopeId),canonical:false,selectable:false,morphologyCue:true},geometry:{domain:'MACRO',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flatten(filaments),curveTopology:'SEGMENTS',lit:false,lodLevel:mobile?1:2,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:c==='GALAXY'?[.62,.48,.88]:[.28,.55,.72],emissive:[.03,.025,.065],roughness:1,metallic:0,opacity:mobile?.16:.24},picking:{entityIds:[],selectionAuthority:'NONE_PRESENTATION_MORPHOLOGY'},resources:{vertices:filaments.length,cpuBytes:filaments.length*12,gpuBytes:filaments.length*12},claims:{canonical:false,physicalCoordinate:false,astrophysicalFilamentClaim:false,morphologyPresentationOnly:true,selectable:false}}));
 if(c==='GALAXY')packets.push(P.createPacket({packetId:'macro:luminous-core',family:'POINT_BATCH',entityId:null,representationId:'deep3d-macro-luminous-core-1',lodKey:'core',spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:densitySeed,semanticState:{context:c,scopeId:String(scopeId),canonical:false,selectable:false},geometry:{domain:'MACRO',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:[-cam[0],-cam[1],-cam[2]],lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[1,.73,.38],emissive:[.45,.2,.05],roughness:1,metallic:0,opacity:.92,pointSize:mobile?18:28},picking:{entityIds:[],selectionAuthority:'NONE_PRESENTATION_MORPHOLOGY'},resources:{points:1,vertices:1,cpuBytes:12,gpuBytes:12},claims:{canonical:false,physicalCoordinate:false,galacticCenterClaim:false,presentationFocusCue:true,additionalEntity:false}}));
 if(semanticSelection?.entityId){const selected=spatial.objects.find(o=>String(o.canonicalId||o.entityId||o.identity)===String(semanticSelection.entityId));if(selected){const p=rel(selected.position,cam);packets.push(P.createPacket({packetId:'macro:selected:'+String(semanticSelection.entityId),family:'POINT_BATCH',entityId:String(semanticSelection.entityId),representationId:'deep3d-macro-selection-halo-1',lodKey:'selected',spatialAddress:addr,provenance:'PRESENTATION_ONLY',semanticState:{context:c,selected:true},geometry:{domain:'MACRO',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:p,lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[1,.9,.52],emissive:[.16,.1,.02],roughness:1,metallic:0,opacity:1,pointSize:mobile?10:12},picking:{entityId:String(semanticSelection.entityId),selectionAuthority:'UPSTREAM_SELECTION_CONTRACT'},resources:{points:1,vertices:1,cpuBytes:12,gpuBytes:12},claims:{physicalCoordinate:false,canonicalIdentityPreserved:true}}))}}
 return P.createScene({frameId:String(frameId),cameraPolicyId:'v2x02.authoritative',viewportClass,packets,semanticSelection});
}
O.deep3dMacroAdapter=Object.freeze({VERSION,AUTHORITY,CONTEXTS,densityPoints,filamentSegments,createRenderScene,claims:Object.freeze({source:'V1X02_SPATIAL_3D',physicalCoordinate:false,densityCanonical:false,filamentCanonical:false,canonicalIdentityPreserved:true,cameraAuthority:false})});
})(typeof globalThis!=='undefined'?globalThis:this);
