(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress;
if(!P||!S)throw new Error('Deep3D matter adapter dependencies missing');
const VERSION='ofu-deep3d-matter-adapter-3',AUTHORITY='PRESENTATION_ONLY',STAGES=Object.freeze(['MATERIAL','MICROSTRUCTURE','MOLECULAR','ATOMIC']);
const LIMITS=Object.freeze({maxNodes:192,maxRelations:128,maxPackets:12,maxPoints:192,maxMeshVertices:36864,maxCurveVertices:448,maxGpuBytes:1048576});
const VISUAL=Object.freeze({UNRESOLVED:{color:[.47,.39,.46],size:18},ATOMIC:{color:[.78,.52,.39],size:18},MOLECULAR:{color:[.34,.63,.76],size:21},MATERIAL:{color:[.35,.62,.66],size:34},MICROSTRUCTURE:{color:[.5,.62,.48],size:24},GENERIC:{color:[.52,.6,.64],size:19}});
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const kindOf=node=>{const k=String(node?.kind||'').toUpperCase();if(k.includes('UNRESOLVED'))return'UNRESOLVED';if(k.includes('ATOM'))return'ATOMIC';if(/MOLEC|BOND|REACTION/.test(k))return'MOLECULAR';if(k.includes('MATERIAL'))return'MATERIAL';if(/FEATURE|PHASE|DEFECT|INTERFACE|GRAIN|CRYSTAL/.test(k))return'MICROSTRUCTURE';return'GENERIC'};
function rawPosition(node,index,count){const raw=node?.position,side=Math.max(1,Math.ceil(Math.cbrt(Math.max(1,count)))),fallback=count===1?[0,0,0]:[index%side/Math.max(1,side-1)*2-1,Math.floor(index/side)%side/Math.max(1,side-1)*2-1,Math.floor(index/(side*side))/Math.max(1,side-1)*2-1],p=Array.isArray(raw)?raw:raw&&typeof raw==='object'?[raw.x,raw.y,raw.z??0]:fallback;if(p.length!==3)throw new TypeError('matter node position vec3 required');return p.map((v,i)=>finite(v,'matter position['+i+']'))}
function coordinateFrame(nodes){if(!nodes.length)return Object.freeze({center:Object.freeze([0,0,0]),extent:1});const points=nodes.map((node,index)=>rawPosition(node,index,nodes.length)),min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const p of points)for(let i=0;i<3;i++){min[i]=Math.min(min[i],p[i]);max[i]=Math.max(max[i],p[i])}const center=min.map((v,i)=>(v+max[i])/2),extent=Math.max(1,...max.map((v,i)=>(v-min[i])/2));return Object.freeze({center:Object.freeze(center),extent})}
function positionOf(node,index,count,scale,camera,frame={center:[0,0,0],extent:1}){const p=rawPosition(node,index,count),center=frame?.center,extent=Math.max(1,finite(frame?.extent??1,'coordinateExtent'));if(!Array.isArray(center)||center.length!==3)throw new TypeError('coordinate center vec3 required');return p.map((v,i)=>(v-finite(center[i],'coordinate center['+i+']'))/extent*scale-camera[i])}
function endpoints(relation){for(const pair of [[relation?.from,relation?.to],[relation?.source,relation?.target],[relation?.a,relation?.b],[relation?.left,relation?.right],relation?.between])if(Array.isArray(pair)&&pair.length===2&&pair[0]!=null&&pair[1]!=null)return pair.map(String);return null}
function glyphRadii(kind,id,radius){let hash=2166136261;for(const ch of String(id)){hash^=ch.charCodeAt(0);hash=Math.imul(hash,16777619)>>>0}if(kind==='ATOMIC')return[radius,radius,radius];if(kind==='MATERIAL')return[radius*1.34,radius*.78,radius*1.08];if(kind==='MICROSTRUCTURE')return[radius*(.82+(hash&7)*.055),radius*(1.08+((hash>>>3)&7)*.045),radius*(.78+((hash>>>6)&7)*.05)];if(kind==='MOLECULAR')return[radius*1.16,radius*.78,radius*.92];return[radius*.92,radius*.92,radius*.92]}
function sphereGlyph(center,radii,positions,normals,segments=8,rings=4){const radius=Array.isArray(radii)?radii:[radii,radii,radii],vertex=(ring,segment)=>{const phi=Math.PI*ring/rings,theta=Math.PI*2*segment/segments,unit=[Math.sin(phi)*Math.cos(theta),Math.cos(phi),Math.sin(phi)*Math.sin(theta)],n=[unit[0]/radius[0],unit[1]/radius[1],unit[2]/radius[2]],length=Math.hypot(...n)||1;return{p:[center[0]+unit[0]*radius[0],center[1]+unit[1]*radius[1],center[2]+unit[2]*radius[2]],n:n.map(x=>x/length)}};for(let ring=0;ring<rings;ring++)for(let segment=0;segment<segments;segment++){const a=vertex(ring,segment),b=vertex(ring+1,segment),c=vertex(ring+1,segment+1),d=vertex(ring,segment+1);for(const v of [a,b,c,a,c,d]){positions.push(v.p);normals.push(v.n)}}}
function referenceFrame(center,radius,segments=32){const lines=[];for(let plane=0;plane<3;plane++)for(let i=0;i<segments;i++){const a=Math.PI*2*i/segments,b=Math.PI*2*(i+1)/segments,point=angle=>plane===0?[center[0]+Math.cos(angle)*radius,center[1]+Math.sin(angle)*radius,center[2]]:plane===1?[center[0]+Math.cos(angle)*radius,center[1],center[2]+Math.sin(angle)*radius]:[center[0],center[1]+Math.cos(angle)*radius,center[2]+Math.sin(angle)*radius];lines.push(point(a),point(b))}return lines}
function createRenderScene(presentation,{stage=null,cameraPosition=[0,0,0],viewportClass='desktop',scaleUnits=18,semanticSelection=null}={}){
 if(!presentation||presentation.authority!==AUTHORITY||!Array.isArray(presentation.nodes)||!Array.isArray(presentation.relations))throw new TypeError('V2X-12 microscopic presentation required');const band=String(stage||presentation.regime||'').toUpperCase();if(!STAGES.includes(band)||String(presentation.regime||band).toUpperCase()!==band)throw new Error('matter stage/regime mismatch');if(presentation.nodes.length>LIMITS.maxNodes||presentation.relations.length>LIMITS.maxRelations)throw new RangeError('matter presentation bound exceeded');const camera=Array.from(cameraPosition,(v,i)=>finite(v,'cameraPosition['+i+']'));if(camera.length!==3)throw new TypeError('cameraPosition vec3 required');const scale=finite(scaleUnits,'scaleUnits');if(!(scale>0))throw new RangeError('matter scale must be positive');const sourceId=String(presentation.sourceEntityId||presentation.materialId||'');if(!sourceId)throw new Error('matter source identity required');const addr=S.create({frameId:'matter:'+sourceId+':'+band.toLowerCase(),hierarchy:['universe','matter-source',sourceId,band.toLowerCase()],nativeKey:{sourceEntityId:sourceId,materialId:presentation.materialId||null,regime:band},local:[0,0,0],unit:'SEMANTIC_MICRO_PRESENTATION',parentFrameId:'local:'+sourceId,transformRevision:String(presentation.contract||VERSION)}),groups=new Map,byId=new Map,packets=[],coordinate=coordinateFrame(presentation.nodes);
 presentation.nodes.forEach((node,index)=>{const id=String(node?.id||'');if(!id||byId.has(id))throw new Error('unique matter node identity required');const position=positionOf(node,index,presentation.nodes.length,scale,camera,coordinate),kind=kindOf(node),group=groups.get(kind)||{positions:[],ids:[],authorityStates:new Set};group.positions.push(position);group.ids.push(id);group.authorityStates.add(String(node.coordinateAuthority||node.modelCoordinateAuthority||node.componentAuthority||node.positionAuthority||'PRESENTATION_ONLY'));groups.set(kind,group);byId.set(id,position)});
 for(const [kind,group] of [...groups].sort((a,b)=>a[0].localeCompare(b[0]))){const visual=VISUAL[kind],positions=[],normals=[],radius=scale*(presentation.nodes.length===1?.13:.032+visual.size/1400),geometryKind=kind==='ATOMIC'?'SPHERE':kind==='MATERIAL'?'FACETED_SAMPLE':kind==='MICROSTRUCTURE'?'ANISOTROPIC_GRAIN':kind==='MOLECULAR'?'LOBED_NODE':'UNRESOLVED_GLYPH';for(let i=0;i<group.positions.length;i++)sphereGlyph(group.positions[i],glyphRadii(kind,group.ids[i],radius),positions,normals);const vertices=positions.length;if(vertices>LIMITS.maxMeshVertices)throw new RangeError('matter glyph vertex bound exceeded');packets.push(P.createPacket({packetId:'matter:nodes:'+kind.toLowerCase(),family:'MESH',entityId:null,representationId:'deep3d-v2x12-'+kind.toLowerCase()+'-spatial-glyphs-3',lodKey:band+':'+group.ids.length,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:sourceId,semanticState:{stage:band,sourceEntityId:sourceId,nodeIds:group.ids,sourceAuthorityStates:[...group.authorityStates].sort(),unresolved:kind==='UNRESOLVED',presentationGeometry:'LOW_POLY_'+geometryKind+'_GLYPH'},geometry:{domain:'MATTER',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:positions.flat(),normals:normals.flat(),lit:true,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:true},material:{baseColor:visual.color,emissive:visual.color.map(x=>x*.045),roughness:.68,metallic:.05,opacity:kind==='UNRESOLVED'?.68:1},lighting:{model:'DIRECTIONAL_AMBIENT',authority:AUTHORITY},picking:{entityIds:group.ids,selectionAuthority:'UPSTREAM_MICRO_SOURCE_CONTRACT'},resources:{vertices,cpuBytes:vertices*24,gpuBytes:vertices*24},claims:{canonical:false,scientificGeometry:false,exactSpatialArrangement:false,trajectory:false,quantumDynamics:false,identityInvented:false,presentationGlyphOnly:true}}))}
 const lines=[];let represented=0;for(const relation of presentation.relations){const pair=endpoints(relation);if(!pair)continue;const a=byId.get(pair[0]),b=byId.get(pair[1]);if(!a||!b)continue;lines.push(a,b);represented++}if(lines.length>LIMITS.maxCurveVertices)throw new RangeError('matter relation vertex bound exceeded');if(lines.length)packets.push(P.createPacket({packetId:'matter:relations',family:'CURVE',entityId:null,representationId:'deep3d-v2x12-semantic-relations-1',lodKey:band+':'+represented,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:sourceId,semanticState:{stage:band,sourceEntityId:sourceId,representedRelations:represented,availableRelations:presentation.relationAvailableCount??presentation.relations.length,semanticTopologyOnly:true},geometry:{domain:'MATTER',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:lines.flat(),curveTopology:'SEGMENTS',lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[.38,.61,.72],emissive:[.02,.035,.045],roughness:1,metallic:0,opacity:.62},picking:{entityIds:[],selectionAuthority:'UPSTREAM_MICRO_SOURCE_CONTRACT'},resources:{vertices:lines.length,cpuBytes:lines.length*12,gpuBytes:lines.length*12},claims:{canonical:false,semanticRelationOnly:true,physicalBondGeometry:false,dynamics:false}}));
 if(presentation.nodes.length===1){const center=byId.get(String(presentation.nodes[0].id)),ring=[],segments=48,radius=scale*.19;for(let i=0;i<segments;i++){const a=Math.PI*2*i/segments,b=Math.PI*2*(i+1)/segments;ring.push([center[0]+Math.cos(a)*radius,center[1]+Math.sin(a)*radius,center[2]],[center[0]+Math.cos(b)*radius,center[1]+Math.sin(b)*radius,center[2]])}packets.push(P.createPacket({packetId:'matter:semantic-focus',family:'CURVE',entityId:null,representationId:'deep3d-v2x12-single-node-focus-1',lodKey:band+':single',spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:sourceId,semanticState:{stage:band,sourceEntityId:sourceId,sparseSource:true,sourceNodeCount:1},geometry:{domain:'MATTER',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:ring.flat(),curveTopology:'SEGMENTS',lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[.42,.72,.76],emissive:[.035,.065,.07],roughness:1,metallic:0,opacity:.72},picking:{entityIds:[],selectionAuthority:'UPSTREAM_MICRO_SOURCE_CONTRACT'},resources:{vertices:ring.length,cpuBytes:ring.length*12,gpuBytes:ring.length*12},claims:{canonical:false,presentationFocusCue:true,scientificGeometry:false,additionalMatterEntity:false}}))}else if(presentation.nodes.length>1){const lines=referenceFrame(camera.map(x=>-x),scale*1.14);packets.push(P.createPacket({packetId:'matter:reference-frame',family:'CURVE',entityId:null,representationId:'deep3d-v2x12-nested-reference-frame-1',lodKey:band+':'+presentation.nodes.length,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:sourceId,semanticState:{stage:band,sourceEntityId:sourceId,targetAnchored:true,coordinateAuthority:'PRESENTATION_ONLY'},geometry:{domain:'MATTER',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:lines.flat(),curveTopology:'SEGMENTS',lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[.18,.34,.43],emissive:[.008,.018,.024],roughness:1,metallic:0,opacity:.28},picking:{entityIds:[],selectionAuthority:'UPSTREAM_MICRO_SOURCE_CONTRACT'},resources:{vertices:lines.length,cpuBytes:lines.length*12,gpuBytes:lines.length*12},claims:{canonical:false,targetAnchoredReferenceFrame:true,scientificGeometry:false,physicalExtent:false,additionalMatterEntity:false}}))}
 if(packets.length>LIMITS.maxPackets)throw new RangeError('matter packet bound exceeded');const scene=P.createScene({frameId:addr.frameId,cameraPolicyId:'v2x02.authoritative',viewportClass,packets,semanticSelection});if(scene.resourceTotals.points>LIMITS.maxPoints||scene.resourceTotals.vertices>LIMITS.maxMeshVertices+LIMITS.maxCurveVertices||scene.resourceTotals.gpuBytes>LIMITS.maxGpuBytes)throw new RangeError('matter GPU resource bound exceeded');return scene
}
O.deep3dMatterAdapter=Object.freeze({VERSION,AUTHORITY,STAGES,LIMITS,VISUAL,kindOf,rawPosition,coordinateFrame,positionOf,endpoints,glyphRadii,referenceFrame,createRenderScene,claims:Object.freeze({source:'V2X12_MICROSCOPIC_PRESENTATION',scientificGeometry:false,exactSpatialArrangement:false,trajectory:false,quantumDynamics:false,cameraAuthority:false,selectionAuthority:false,sourceIdentityPreserved:true,unresolvedChemistryPreserved:true,presentationGlyphsOnly:true,targetAnchoredReferenceFrame:true})});
})(typeof globalThis!=='undefined'?globalThis:this);
