(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress;
if(!P||!S)throw new Error('Deep3D matter adapter dependencies missing');
const VERSION='ofu-deep3d-matter-adapter-1',AUTHORITY='PRESENTATION_ONLY',STAGES=Object.freeze(['MATERIAL','MICROSTRUCTURE','MOLECULAR','ATOMIC']);
const LIMITS=Object.freeze({maxNodes:192,maxRelations:128,maxPackets:12,maxPoints:192,maxCurveVertices:256,maxGpuBytes:1048576});
const VISUAL=Object.freeze({UNRESOLVED:{color:[.47,.39,.46],size:7},ATOMIC:{color:[.78,.52,.39],size:9},MOLECULAR:{color:[.34,.63,.76],size:10},MATERIAL:{color:[.35,.62,.66],size:13},MICROSTRUCTURE:{color:[.5,.62,.48],size:11},GENERIC:{color:[.52,.6,.64],size:9}});
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const kindOf=node=>{const k=String(node?.kind||'').toUpperCase();if(k.includes('UNRESOLVED'))return'UNRESOLVED';if(k.includes('ATOM'))return'ATOMIC';if(/MOLEC|BOND|REACTION/.test(k))return'MOLECULAR';if(k.includes('MATERIAL'))return'MATERIAL';if(/FEATURE|PHASE|DEFECT|INTERFACE|GRAIN|CRYSTAL/.test(k))return'MICROSTRUCTURE';return'GENERIC'};
function positionOf(node,index,count,scale,camera){const raw=node?.position,side=Math.max(1,Math.ceil(Math.cbrt(Math.max(1,count)))),fallback=[index%side/Math.max(1,side-1)*2-1,Math.floor(index/side)%side/Math.max(1,side-1)*2-1,Math.floor(index/(side*side))/Math.max(1,side-1)*2-1],p=Array.isArray(raw)?raw:raw&&typeof raw==='object'?[raw.x,raw.y,raw.z??0]:fallback;if(p.length!==3)throw new TypeError('matter node position vec3 required');return[p[0],p[1],p[2]].map((v,i)=>finite(v,'matter position['+i+']')*scale-camera[i])}
function endpoints(relation){for(const pair of [[relation?.from,relation?.to],[relation?.source,relation?.target],[relation?.a,relation?.b],[relation?.left,relation?.right],relation?.between])if(Array.isArray(pair)&&pair.length===2&&pair[0]!=null&&pair[1]!=null)return pair.map(String);return null}
function createRenderScene(presentation,{stage=null,cameraPosition=[0,0,0],viewportClass='desktop',scaleUnits=18,semanticSelection=null}={}){
 if(!presentation||presentation.authority!==AUTHORITY||!Array.isArray(presentation.nodes)||!Array.isArray(presentation.relations))throw new TypeError('V2X-12 microscopic presentation required');const band=String(stage||presentation.regime||'').toUpperCase();if(!STAGES.includes(band)||String(presentation.regime||band).toUpperCase()!==band)throw new Error('matter stage/regime mismatch');if(presentation.nodes.length>LIMITS.maxNodes||presentation.relations.length>LIMITS.maxRelations)throw new RangeError('matter presentation bound exceeded');const camera=Array.from(cameraPosition,(v,i)=>finite(v,'cameraPosition['+i+']'));if(camera.length!==3)throw new TypeError('cameraPosition vec3 required');const scale=finite(scaleUnits,'scaleUnits');if(!(scale>0))throw new RangeError('matter scale must be positive');const sourceId=String(presentation.sourceEntityId||presentation.materialId||'');if(!sourceId)throw new Error('matter source identity required');const addr=S.create({frameId:'matter:'+sourceId+':'+band.toLowerCase(),hierarchy:['universe','matter-source',sourceId,band.toLowerCase()],nativeKey:{sourceEntityId:sourceId,materialId:presentation.materialId||null,regime:band},local:[0,0,0],unit:'SEMANTIC_MICRO_PRESENTATION',parentFrameId:'local:'+sourceId,transformRevision:String(presentation.contract||VERSION)}),groups=new Map,byId=new Map,packets=[];
 presentation.nodes.forEach((node,index)=>{const id=String(node?.id||'');if(!id||byId.has(id))throw new Error('unique matter node identity required');const position=positionOf(node,index,presentation.nodes.length,scale,camera),kind=kindOf(node),group=groups.get(kind)||{positions:[],ids:[],authorityStates:new Set};group.positions.push(position);group.ids.push(id);group.authorityStates.add(String(node.coordinateAuthority||node.modelCoordinateAuthority||node.componentAuthority||node.positionAuthority||'PRESENTATION_ONLY'));groups.set(kind,group);byId.set(id,position)});
 for(const [kind,group] of [...groups].sort((a,b)=>a[0].localeCompare(b[0]))){const visual=VISUAL[kind];packets.push(P.createPacket({packetId:'matter:nodes:'+kind.toLowerCase(),family:'POINT_BATCH',entityId:null,representationId:'deep3d-v2x12-'+kind.toLowerCase()+'-nodes-1',lodKey:band+':'+group.ids.length,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:sourceId,semanticState:{stage:band,sourceEntityId:sourceId,nodeIds:group.ids,sourceAuthorityStates:[...group.authorityStates].sort(),unresolved:kind==='UNRESOLVED'},geometry:{domain:'MATTER',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:group.positions.flat(),lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:true},material:{baseColor:visual.color,emissive:visual.color.map(x=>x*.08),roughness:1,metallic:0,opacity:kind==='UNRESOLVED'?.68:1,pointSize:visual.size},picking:{entityIds:group.ids,selectionAuthority:'UPSTREAM_MICRO_SOURCE_CONTRACT'},resources:{points:group.ids.length,vertices:group.ids.length,cpuBytes:group.ids.length*12,gpuBytes:group.ids.length*12},claims:{canonical:false,scientificGeometry:false,exactSpatialArrangement:false,trajectory:false,quantumDynamics:false,identityInvented:false}}))}
 const lines=[];let represented=0;for(const relation of presentation.relations){const pair=endpoints(relation);if(!pair)continue;const a=byId.get(pair[0]),b=byId.get(pair[1]);if(!a||!b)continue;lines.push(a,b);represented++}if(lines.length>LIMITS.maxCurveVertices)throw new RangeError('matter relation vertex bound exceeded');if(lines.length)packets.push(P.createPacket({packetId:'matter:relations',family:'CURVE',entityId:null,representationId:'deep3d-v2x12-semantic-relations-1',lodKey:band+':'+represented,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:sourceId,semanticState:{stage:band,sourceEntityId:sourceId,representedRelations:represented,availableRelations:presentation.relationAvailableCount??presentation.relations.length,semanticTopologyOnly:true},geometry:{domain:'MATTER',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:lines.flat(),curveTopology:'SEGMENTS',lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:[.38,.61,.72],emissive:[.02,.035,.045],roughness:1,metallic:0,opacity:.62},picking:{entityIds:[],selectionAuthority:'UPSTREAM_MICRO_SOURCE_CONTRACT'},resources:{vertices:lines.length,cpuBytes:lines.length*12,gpuBytes:lines.length*12},claims:{canonical:false,semanticRelationOnly:true,physicalBondGeometry:false,dynamics:false}}));
 if(packets.length>LIMITS.maxPackets)throw new RangeError('matter packet bound exceeded');const scene=P.createScene({frameId:addr.frameId,cameraPolicyId:'v2x02.authoritative',viewportClass,packets,semanticSelection});if(scene.resourceTotals.points>LIMITS.maxPoints||scene.resourceTotals.gpuBytes>LIMITS.maxGpuBytes)throw new RangeError('matter GPU resource bound exceeded');return scene
}
O.deep3dMatterAdapter=Object.freeze({VERSION,AUTHORITY,STAGES,LIMITS,VISUAL,kindOf,positionOf,endpoints,createRenderScene,claims:Object.freeze({source:'V2X12_MICROSCOPIC_PRESENTATION',scientificGeometry:false,exactSpatialArrangement:false,trajectory:false,quantumDynamics:false,cameraAuthority:false,selectionAuthority:false,sourceIdentityPreserved:true,unresolvedChemistryPreserved:true})});
})(typeof globalThis!=='undefined'?globalThis:this);
