(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress;
if(!P||!S)throw new Error('Deep3D planet adapter dependencies missing');
const VERSION='ofu-deep3d-planet-adapter-1',AUTHORITY='PRESENTATION_ONLY',SCALES=Object.freeze(['PLANET','APPROACH']);
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const text=(v,l)=>{const s=String(v??'').trim();if(!s)throw new TypeError(l+' required');return s};
const boundedColor=(v,fallback)=>{const a=Array.isArray(v)?v:fallback;if(!Array.isArray(a)||a.length!==3)throw new TypeError('color vec3 required');return a.map((x,i)=>Math.max(0,Math.min(1,finite(x,'color['+i+']'))))};
function createRenderScene(worldScene,{frameId=null,viewportClass='desktop'}={}){
 if(!worldScene||typeof worldScene!=='object')throw new TypeError('world scene required');const scale=String(worldScene.scale||'').toUpperCase();if(!SCALES.includes(scale))throw new Error('unsupported planet scale '+scale);const sourceId=text(worldScene.sourceId,'sourceId'),globe=(worldScene.objects||[]).find(x=>x?.kind==='PLANET_GLOBE');if(!globe)throw new Error('PLANET_GLOBE object required');const map=worldScene.surfaceTexture||null,mapBytes=Math.max(0,Number(map?.data?.byteLength??map?.data?.length??0)||0),addr=S.create({frameId:frameId||'planet:'+sourceId,hierarchy:['system','planet'],nativeKey:{planetIdentity:sourceId},local:[0,0,0],unit:'PLANET_PRESENTATION_FRAME',parentFrameId:'system',transformRevision:'v1-world-webgl2-1'}),visual=globe.visual||{},packet=P.createPacket({packetId:'planet:globe:'+sourceId,family:'IMPOSTOR',entityId:sourceId,representationId:'deep3d-specialized-planet-globe-1',lodKey:[scale,map?.width||0,map?.height||0].join(':'),spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:String(visual.seed??''),semanticState:{scale,sourceId,worldSceneAuthority:worldScene.authority||AUTHORITY,globeScale:finite(worldScene.globeScale??.76,'globeScale'),camera:{yaw:finite(worldScene.camera?.yaw??0,'camera.yaw'),pitch:finite(worldScene.camera?.pitch??0,'camera.pitch')},surfaceMap:map?{key:String(map.key||''),width:Number(map.width)||0,height:Number(map.height)||0,cloudPatternOnly:Boolean(map.cloudPatternOnly)}:null},geometry:{domain:'PLANET',coordinateSpace:'PLANET_VIEW_IMPOSTOR',specializedPass:'V1_WORLD_WEBGL2_GLOBE',depthTest:true,depthWrite:true,lodLevel:scale==='APPROACH'?1:0,lodTransition:0},material:{baseColor:boundedColor(visual.primaryColor,[.35,.48,.62]),secondaryColor:boundedColor(visual.secondaryColor,[.5,.52,.54]),oceanColor:boundedColor(visual.oceanColor,[.08,.22,.38]),iceColor:boundedColor(visual.iceColor,[.86,.9,.94]),atmosphereStrength:Math.max(0,finite(visual.atmosphereStrength??0,'atmosphereStrength')),opacity:1},picking:{entityId:sourceId,selectionAuthority:'UPSTREAM_SELECTION_CONTRACT'},resources:{instances:1,cpuBytes:mapBytes,gpuBytes:4096+mapBytes},claims:{canonicalIdentityPreserved:true,physicalRadius:false,physicalAtmosphere:false,surfaceTextureScientificTruth:false,cameraAuthority:false}});
 return P.createScene({frameId:addr.frameId,cameraPolicyId:'v2x02.authoritative',viewportClass,packets:[packet],semanticSelection:{entityId:sourceId}});
}
O.deep3dPlanetAdapter=Object.freeze({VERSION,AUTHORITY,SCALES,createRenderScene,claims:Object.freeze({sourceRenderer:'V1_WORLD_WEBGL2',specializedPass:true,canonicalIdentityPreserved:true,scientificPromotion:false,cameraAuthority:false})});
})(typeof globalThis!=='undefined'?globalThis:this);
