(function(root){
'use strict';
const O=root.OFU=root.OFU||{},CONTRACT='ofu-deep3d-render-packets-1',VERSION='ofu-deep3d-render-packets-1';
const PROVENANCE=Object.freeze(['SOURCE_BACKED','MODEL_DERIVED','MODEL_DERIVED_SIMULATION','PRESENTATION_ONLY','CANONICAL_PROVEN','CANONICAL_GEOMETRY','CANONICAL_ORDER_PRESENTATION_GEOMETRY','DECORATIVE_ONLY']);
const FAMILIES=Object.freeze(['MESH','POINT_BATCH','INSTANCE_BATCH','CURVE','IMPOSTOR','DENSITY_VOLUME','ATMOSPHERE_SHELL']);
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const text=(v,l)=>{const s=String(v??'').trim();if(!s)throw new TypeError(l+' required');return s};
function stable(v){if(v===null||v===undefined)return v===undefined?null:v;if(typeof v==='bigint')return {$bigint:v.toString()};if(ArrayBuffer.isView(v))return Array.from(v,Number);if(Array.isArray(v))return v.map(stable);if(typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));if(typeof v==='number'&&!Number.isFinite(v))throw new TypeError('non-finite semantic value');return v}
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v)||ArrayBuffer.isView(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function hash(v){if(!O.sha256?.hex)throw new Error('OFU.sha256 required before render packets');return O.sha256.hex(JSON.stringify(stable(v)))}
function provenance(v){const p=text(v,'provenance');if(!PROVENANCE.includes(p))throw new Error('unsupported provenance '+p);return p}
function resources(i={}){const n=k=>Math.max(0,Math.floor(finite(i[k]??0,'resources.'+k)));return freeze({vertices:n('vertices'),indices:n('indices'),instances:n('instances'),points:n('points'),cpuBytes:n('cpuBytes'),gpuBytes:n('gpuBytes')})}
function createPacket(input){if(!input||typeof input!=='object')throw new TypeError('packet input required');if(!O.spatialAddress?.create)throw new Error('OFU.spatialAddress required before render packets');const family=text(input.family,'family');if(!FAMILIES.includes(family))throw new Error('unsupported render packet family '+family);const packet={contract:CONTRACT,version:VERSION,packetId:text(input.packetId,'packetId'),family,entityId:input.entityId==null?null:String(input.entityId),representationId:text(input.representationId,'representationId'),lodKey:text(input.lodKey,'lodKey'),spatialAddress:O.spatialAddress.create(input.spatialAddress),provenance:provenance(input.provenance),presentationSeed:String(input.presentationSeed??''),semanticState:stable(input.semanticState||{}),geometry:stable(input.geometry||{}),material:stable(input.material||{}),lighting:stable(input.lighting||{}),picking:stable(input.picking||{}),resources:resources(input.resources),claims:stable(input.claims||{})};if(packet.provenance==='PRESENTATION_ONLY'&&packet.claims.canonical===true)throw new Error('presentation-only packet cannot claim canonical authority');if(packet.picking.entityId!=null&&packet.entityId!=null&&String(packet.picking.entityId)!==packet.entityId)throw new Error('picking entity identity mismatch');packet.fingerprint=hash(packet);return freeze(packet)}
function createScene(input){if(!input||typeof input!=='object')throw new TypeError('scene input required');const packets=(input.packets||[]).map(createPacket).sort((a,b)=>a.packetId.localeCompare(b.packetId)||a.fingerprint.localeCompare(b.fingerprint));const totals=packets.reduce((a,p)=>({vertices:a.vertices+p.resources.vertices,indices:a.indices+p.resources.indices,instances:a.instances+p.resources.instances,points:a.points+p.resources.points,cpuBytes:a.cpuBytes+p.resources.cpuBytes,gpuBytes:a.gpuBytes+p.resources.gpuBytes}),{vertices:0,indices:0,instances:0,points:0,cpuBytes:0,gpuBytes:0});const scene={contract:'ofu-deep3d-render-scene-1',version:'ofu-deep3d-render-scene-1',frameId:text(input.frameId,'frameId'),cameraPolicyId:text(input.cameraPolicyId,'cameraPolicyId'),viewportClass:text(input.viewportClass,'viewportClass'),packets,semanticSelection:stable(input.semanticSelection||null),resourceTotals:totals};scene.fingerprint=hash({...scene,packets:packets.map(p=>p.fingerprint)});return freeze(scene)}
function semanticParity(a,b){const left=createScene(a),right=createScene(b);return freeze({contract:'ofu-deep3d-semantic-parity-1',pass:left.fingerprint===right.fingerprint,left:left.fingerprint,right:right.fingerprint})}
O.deep3dRenderPackets=Object.freeze({CONTRACT,VERSION,PROVENANCE,FAMILIES,stable,hash,createPacket,createScene,semanticParity});
})(typeof globalThis!=='undefined'?globalThis:this);
