(function(root){
'use strict';
const O=root.OFU=root.OFU||{},CONTRACT='ofu-spatial-address-1';
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const text=(v,l)=>{const s=String(v??'').trim();if(!s)throw new TypeError(l+' required');return s};
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v)||ArrayBuffer.isView(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function stable(v){if(v===null||v===undefined)return v===undefined?null:v;if(typeof v==='bigint')return {$bigint:v.toString()};if(ArrayBuffer.isView(v))return Array.from(v,Number);if(Array.isArray(v))return v.map(stable);if(typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));if(typeof v==='number'&&!Number.isFinite(v))throw new TypeError('non-finite spatial value');return v}
function create(input){if(!input||typeof input!=='object')throw new TypeError('spatial address input required');const local=(input.local||[]).map((v,i)=>finite(v,'local['+i+']'));if(local.length!==3)throw new TypeError('local must contain 3 coordinates');return freeze({contract:CONTRACT,frameId:text(input.frameId,'frameId'),hierarchy:(input.hierarchy||[]).map((v,i)=>text(v,'hierarchy['+i+']')),nativeKey:stable(input.nativeKey||{}),local,unit:text(input.unit||'FRAME_NATIVE','unit'),parentFrameId:input.parentFrameId==null?null:String(input.parentFrameId),transformRevision:String(input.transformRevision??'0')})}
function token(input){const a=create(input),s=JSON.stringify(stable(a));if(!O.sha256?.hex)throw new Error('OFU.sha256 required before SpatialAddress tokenization');return O.sha256.hex(s)}
function split(value){const v=finite(value,'value'),high=Math.fround(v),low=Math.fround(v-high);return freeze({high,low})}
function highLow3(vector){if(!Array.isArray(vector)||vector.length!==3)throw new TypeError('vector must contain 3 coordinates');const high=[],low=[];for(let i=0;i<3;i++){const s=split(vector[i]);high.push(s.high);low.push(s.low)}return freeze({high,low})}
function relativeCpu(world,camera){if(!Array.isArray(world)||!Array.isArray(camera)||world.length!==3||camera.length!==3)throw new TypeError('world/camera must be vec3');return freeze(world.map((v,i)=>finite(v,'world['+i+']')-finite(camera[i],'camera['+i+']')))}
function relativeFloat32(world,camera){return new Float32Array(relativeCpu(world,camera).map(Math.fround))}
function relativeHighLow(world,camera){const w=highLow3(world),c=highLow3(camera),high=[],low=[],relative=[];for(let i=0;i<3;i++){high.push(Math.fround(w.high[i]-c.high[i]));low.push(Math.fround(w.low[i]-c.low[i]));relative.push(Math.fround(high[i]+low[i]))}return freeze({world:w,camera:c,high,low,relative})}
function sameFrameDelta(aInput,bInput){const a=create(aInput),b=create(bInput);if(a.frameId!==b.frameId||a.unit!==b.unit||a.transformRevision!==b.transformRevision)throw new Error('same-frame delta requires identical frame/unit/revision');return relativeCpu(a.local,b.local)}
function rebase(addressInput,nextFrame,local,meta={}){const a=create(addressInput),next=create({frameId:text(nextFrame,'nextFrame'),hierarchy:meta.hierarchy||a.hierarchy,nativeKey:meta.nativeKey||a.nativeKey,local,unit:meta.unit||a.unit,parentFrameId:meta.parentFrameId??a.parentFrameId,transformRevision:meta.transformRevision??a.transformRevision});return freeze({contract:'ofu-spatial-rebase-witness-1',from:a,to:next,preservedEntityId:meta.entityId==null?null:String(meta.entityId),preservedTargetId:meta.targetId==null?null:String(meta.targetId),orientation:stable(meta.orientation||null),lineOfSight:stable(meta.lineOfSight||null)})}
O.spatialAddress=Object.freeze({CONTRACT,create,token,split,highLow3,relativeCpu,relativeFloat32,relativeHighLow,sameFrameDelta,rebase,stable});
})(typeof globalThis!=='undefined'?globalThis:this);
