(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress;
if(!P||!S)throw new Error('Deep3D surface adapter dependencies missing');
const VERSION='ofu-deep3d-surface-adapter-1',AUTHORITY='PRESENTATION_ONLY',STAGES=Object.freeze(['GLOBAL_SURFACE','REGIONAL_SURFACE','LOCAL_SURFACE']);
const LIMITS=Object.freeze({maxPolygons:16384,maxVertices:98304,maxMaterialPackets:32,maxPathVertices:32768});
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hex=value=>{const m=/^#([0-9a-f]{6})$/i.exec(String(value||''));if(!m)return[.39,.45,.38];const n=parseInt(m[1],16);return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255]};
const flat=rows=>rows.reduce((out,row)=>out.concat(row),[]);
function address(frame,stage){return S.create({frameId:'surface:'+stage.toLowerCase(),hierarchy:['universe','planet',String(frame.planetIdentity),'surface',String(frame.anchorLocationIdentity)],nativeKey:{planetIdentity:frame.planetIdentity,anchorLocationIdentity:frame.anchorLocationIdentity,frameDigest:frame.frameDigest},local:[0,0,0],unit:'LOCAL_TANGENT_PRESENTATION',parentFrameId:'planet:'+frame.planetIdentity,transformRevision:String(frame.frameDigest||'0')})}
function point(q,relief,scale,reliefScale,camera){if(!Array.isArray(q)||q.length!==2)throw new TypeError('surface point must contain two values');return[(finite(q[0],'surface x')-.5)*scale-camera[0],finite(relief,'relief')*reliefScale-camera[1],(.5-finite(q[1],'surface y'))*scale-camera[2]]}
function triangleNormal(a,b,c){const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]],n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],d=Math.hypot(...n)||1;return n.map(x=>x/d)}
function createRenderScene(frame,{stage='REGIONAL_SURFACE',cameraPosition=[0,0,0],viewportClass='desktop',scaleUnits=24,reliefScale=4,semanticSelection=null}={}){
 const band=String(stage).toUpperCase();if(!STAGES.includes(band))throw new Error('unsupported Deep3D surface stage '+band);if(!frame||frame.status!=='READY'||!Array.isArray(frame.patches))throw new TypeError('ready V2X-06 surface frame required');if(frame.authority!==AUTHORITY)throw new Error('surface frame authority mismatch');
 const camera=cameraPosition.map((v,i)=>finite(v,'cameraPosition['+i+']'));if(camera.length!==3)throw new TypeError('cameraPosition vec3 required');const scale=finite(scaleUnits,'scaleUnits'),height=finite(reliefScale,'reliefScale');if(!(scale>0&&height>=0))throw new RangeError('surface presentation scale invalid');
 const groups=new Map(),coasts=[],rivers=[];let polygons=0;
 for(const panel of frame.patches)for(const polygon of panel.polygons||[]){if(++polygons>LIMITS.maxPolygons)throw new RangeError('surface polygon bound exceeded');const material=String(polygon.baseFill||polygon.surfaceClass||'#626f5b'),reliefBand=Math.round(clamp(finite(polygon.reliefCue??0,'reliefCue'),-1,1)*2),key=material+'|'+reliefBand;if(!groups.has(key)){if(groups.size>=LIMITS.maxMaterialPackets)throw new RangeError('surface material packet bound exceeded');groups.set(key,[])}groups.get(key).push(polygon)}
 const addr=address(frame,band),packets=[];
 for(const [groupKey,items] of [...groups].sort((a,b)=>a[0].localeCompare(b[0]))){const split=groupKey.lastIndexOf('|'),material=groupKey.slice(0,split),reliefBand=Number(groupKey.slice(split+1)),positions=[],normals=[];for(const polygon of items){if(!Array.isArray(polygon.points)||polygon.points.length!==4)throw new Error('surface terrain cell must remain a quad');const z=finite(polygon.reliefCue??0,'reliefCue'),q=polygon.points.map(p=>point(p,z,scale,height,camera)),tri=[q[0],q[1],q[2],q[0],q[2],q[3]];for(let i=0;i<tri.length;i+=3){const n=triangleNormal(tri[i],tri[i+1],tri[i+2]);for(let j=0;j<3;j++){positions.push(tri[i+j]);normals.push(n)}}}const vertices=positions.length,shade=.92+reliefBand*.055,color=hex(material).map(x=>clamp(x*shade,0,1));if(vertices+packets.reduce((n,p)=>n+p.resources.vertices,0)>LIMITS.maxVertices)throw new RangeError('surface vertex bound exceeded');packets.push(P.createPacket({packetId:'surface:terrain:'+material.replace('#','')+':'+reliefBand,family:'MESH',entityId:null,representationId:'deep3d-v2x06-terrain-cells-2',lodKey:band+':'+reliefBand+':'+items.length,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:String(frame.frameDigest),semanticState:{stage:band,planetIdentity:frame.planetIdentity,anchorLocationIdentity:frame.anchorLocationIdentity,sourceAuthority:'MODEL_DERIVED_SIMULATION',materialGroup:material,reliefBand,cellCount:items.length},geometry:{domain:'TERRAIN',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flat(positions),normals:flat(normals),lit:true,lodLevel:band==='GLOBAL_SURFACE'?2:band==='REGIONAL_SURFACE'?5:7,lodTransition:0,depthTest:true,depthWrite:true},material:{baseColor:color,emissive:color.map(x=>x*.035),roughness:.86,metallic:0,opacity:1},lighting:{model:'DIRECTIONAL_AMBIENT',authority:AUTHORITY},picking:{entityIds:[],selectionAuthority:'UPSTREAM_SURFACE_PICK_CONTRACT'},resources:{vertices,cpuBytes:vertices*24,gpuBytes:vertices*24},claims:{canonical:false,physicalElevation:false,canonicalGeodesy:false,modelDerivedReliefCue:true,presentationColorVariation:true,identityInvented:false}}))}
 const paths=(kind,target)=>{for(const panel of frame.patches)for(const path of panel[kind]||[]){const pts=path.points||[];for(let i=0;i+1<pts.length;i++)target.push(point(pts[i],.012,scale,height,camera),point(pts[i+1],.012,scale,height,camera));}};
 paths('coasts',coasts);paths('rivers',rivers);if(coasts.length+rivers.length>LIMITS.maxPathVertices)throw new RangeError('surface path vertex bound exceeded');
 const pathPacket=(name,positions,color)=>positions.length&&P.createPacket({packetId:'surface:'+name,family:'CURVE',entityId:null,representationId:'deep3d-v2x06-'+name+'-1',lodKey:band+':'+positions.length,spatialAddress:addr,provenance:'PRESENTATION_ONLY',presentationSeed:String(frame.frameDigest),semanticState:{stage:band,planetIdentity:frame.planetIdentity,pathClass:name,sourceAuthority:'MODEL_DERIVED_SIMULATION'},geometry:{domain:name==='rivers'?'WATER':'TERRAIN',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flat(positions),curveTopology:'SEGMENTS',lit:false,lodLevel:0,lodTransition:0,depthTest:true,depthWrite:false},material:{baseColor:color,emissive:[.025,.04,.05],roughness:1,metallic:0,opacity:.92},picking:{entityIds:[],selectionAuthority:'UPSTREAM_SURFACE_PICK_CONTRACT'},resources:{vertices:positions.length,cpuBytes:positions.length*12,gpuBytes:positions.length*12},claims:{canonical:false,physicalPath:false,canonicalGeodesy:false}});
 const coastPacket=pathPacket('coasts',coasts,[.72,.86,.9]),riverPacket=pathPacket('rivers',rivers,[.28,.68,.86]);if(coastPacket)packets.push(coastPacket);if(riverPacket)packets.push(riverPacket);
 return P.createScene({frameId:addr.frameId,cameraPolicyId:'v2x02.authoritative',viewportClass,packets,semanticSelection});
}
O.deep3dSurfaceAdapter=Object.freeze({VERSION,AUTHORITY,STAGES,LIMITS,createRenderScene,claims:Object.freeze({source:'V2X06_LIVING_SURFACE_FRAME',physicalElevation:false,canonicalGeodesy:false,cameraAuthority:false,selectionAuthority:false,modelAuthorityPreserved:true})});
})(typeof globalThis!=='undefined'?globalThis:this);
