(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,S=O.spatialAddress,V=O.v1x04SystemScene;
if(!P||!S||!V)throw new Error('Deep3D system adapter dependencies missing');
const VERSION='ofu-deep3d-system-adapter-1',AUTHORITY='PRESENTATION_ONLY';
const f=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new TypeError(l+' must be finite');return n};
const v3=(v,l)=>{if(!Array.isArray(v)||v.length!==3)throw new TypeError(l+' vec3 required');return v.map((x,i)=>f(x,l+'['+i+']'))};
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const flatten=points=>points.flatMap(p=>v3(p,'point'));
const BODY={STAR:{radius:2.2,baseColor:[1,.72,.32],emissive:[.18,.08,.01]},PLANET:{radius:.85,baseColor:[.32,.55,.82],emissive:[0,0,0]}};
const OCTA=Object.freeze([[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]]),OCTA_I=Object.freeze([0,2,4,2,1,4,1,3,4,3,0,4,2,0,5,1,2,5,3,1,5,0,3,5]);
function address(frameId,systemId){return S.create({frameId,hierarchy:['galaxy',frameId],nativeKey:{systemCanonicalEntityId:systemId},local:[0,0,0],unit:'FRAME_NATIVE',parentFrameId:'galaxy',transformRevision:'v1x04-system-scene-1'})}
function bodyPacket(node,origin,addr){const cue=BODY[node.kind]||BODY.PLANET,center=sub(v3(node.transitionPosition3d,'node.transitionPosition3d'),origin),positions=[];for(const p of OCTA)positions.push([center[0]+p[0]*cue.radius,center[1]+p[1]*cue.radius,center[2]+p[2]*cue.radius]);const normals=flatten(OCTA);return P.createPacket({packetId:'system:body:'+node.canonicalEntityId,family:'MESH',entityId:node.canonicalEntityId,representationId:'v1x04-octa-body-1',lodKey:'0',spatialAddress:addr,provenance:'PRESENTATION_ONLY',semanticState:{kind:node.kind,parentCanonicalEntityId:node.parentCanonicalEntityId||null,systemCanonicalEntityId:node.systemCanonicalEntityId||null,sourceFactsAuthority:node.sourceFactsAuthority||null,currentOrbitalPhaseAuthority:node.currentOrbitalPhaseAuthority||null,geometryAuthority:node.geometryAuthority||AUTHORITY},geometry:{domain:'SYSTEM',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flatten(positions),normals,indices:Array.from(OCTA_I),lit:true,lodLevel:0,lodTransition:0},material:{baseColor:cue.baseColor,emissive:cue.emissive,roughness:node.kind==='STAR'?.35:.72,metallic:0,opacity:1},picking:{entityId:node.canonicalEntityId,selectionAuthority:node.selectionAuthority||'UPSTREAM_SELECTION_CONTRACT'},resources:{vertices:6,indices:24,cpuBytes:216,gpuBytes:216},claims:{physicalRadius:false,currentOrbitalPhase:false,canonicalIdentityPreserved:true}})}
function orbitPacket(orbit,origin,addr){const points=orbit.vertices.map(p=>sub(v3(p,'orbit vertex'),origin));return P.createPacket({packetId:'system:orbit:'+orbit.canonicalEntityId,family:'CURVE',entityId:orbit.canonicalEntityId,representationId:'v1x04-orbit-curve-1',lodKey:String(points.length),spatialAddress:addr,provenance:'PRESENTATION_ONLY',semanticState:{orbitCenter:orbit.orbitCenter||null,geometryAuthority:orbit.geometryAuthority||AUTHORITY,currentOrbitalPhaseAuthority:orbit.currentOrbitalPhaseAuthority||null},geometry:{domain:'SYSTEM',coordinateSpace:'CAMERA_RELATIVE_FLOAT32',positions:flatten(points),lit:false,lodLevel:0,lodTransition:0},material:{baseColor:[.42,.48,.58],emissive:[.03,.03,.04],roughness:1,metallic:0,opacity:.7},picking:{entityId:orbit.canonicalEntityId,selectionAuthority:'UPSTREAM_SELECTION_CONTRACT'},resources:{vertices:points.length,cpuBytes:points.length*12,gpuBytes:points.length*12},claims:{metricOrbitDistance:false,currentOrbitalPhase:false,canonicalIdentityPreserved:true}})}
function createRenderScene(systemScene,{frameId='system',cameraPosition=[0,0,0],cameraPolicyId='v2x02.authoritative',viewportClass='desktop',semanticSelection=null}={}){if(!V.validatePrimary3DRepresentation(systemScene))throw new Error('valid V1X-04 true-3D system scene required');const origin=v3(cameraPosition,'cameraPosition'),addr=address(String(frameId),systemScene.systemCanonicalEntityId),packets=[];for(const orbit of systemScene.orbits)packets.push(orbitPacket(orbit,origin,addr));for(const node of systemScene.nodes)packets.push(bodyPacket(node,origin,addr));return P.createScene({frameId:String(frameId),cameraPolicyId,viewportClass,packets,semanticSelection:semanticSelection||{entityId:systemScene.systemCanonicalEntityId}})}
O.deep3dSystemAdapter=Object.freeze({VERSION,AUTHORITY,createRenderScene,claims:Object.freeze({sourceScene:'V1X04_TRUE_3D',physicalBodyRadius:false,metricOrbitDistance:false,currentOrbitalPhase:false,canonicalIdentityPreserved:true,cameraAuthority:false})});
})(typeof globalThis!=='undefined'?globalThis:this);
