(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.deep3dRenderPackets,W=O.renderWebGPUPrimitive;
if(!P||!W||typeof W.createBufferOwner!=='function')throw new Error('Deep3D WebGPU dependencies missing');
const VERSION='ofu-deep3d-webgpu-backend-1',AUTHORITY='PRESENTATION_ONLY',BACKEND='DEEP3D_WEBGPU';
const TOPOLOGY=Object.freeze({MESH:'triangle-list',POINT_BATCH:'point-list',CURVE:'line-list'});
const U=root.GPUBufferUsage||Object.freeze({COPY_DST:8,INDEX:16,VERTEX:32,UNIFORM:64});
const WGSL=`struct U{viewProjection:mat4x4<f32>,color:vec4f};@group(0) @binding(0) var<uniform> u:U;struct VOut{@builtin(position) position:vec4f};@vertex fn vs(@location(0) p:vec3f)->VOut{var o:VOut;o.position=u.viewProjection*vec4f(p,1.0);return o;}@fragment fn fs()->@location(0) vec4f{return u.color;}`;
function fail(code,message){const e=new Error(message);e.code=code;throw e}
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))fail('DEEP3D_WEBGPU_INPUT',l+' must be finite');return n};
const vec=(v,n,l)=>{if((!Array.isArray(v)&&!ArrayBuffer.isView(v))||v.length!==n)fail('DEEP3D_WEBGPU_INPUT',l+' must contain '+n+' values');return Array.from(v,(x,i)=>finite(x,l+'['+i+']'))};
function lineStripPairs(src){if(src.length<6)return src.slice();const out=[];for(let i=0;i<=src.length-6;i+=3)out.push(src[i],src[i+1],src[i+2],src[i+3],src[i+4],src[i+5]);return out}
function compilePacket(packet){const topology=TOPOLOGY[packet.family];if(!topology)fail('DEEP3D_WEBGPU_FAMILY','Deep3D WebGPU family not implemented: '+packet.family);const g=packet.geometry||{};if(g.coordinateSpace!=='CAMERA_RELATIVE_FLOAT32')fail('DEEP3D_WEBGPU_SPACE','Deep3D WebGPU requires CAMERA_RELATIVE_FLOAT32 geometry');if(!Array.isArray(g.positions)||g.positions.length<3||g.positions.length%3)fail('DEEP3D_WEBGPU_GEOMETRY','positions required');let positions=g.positions.map((v,i)=>Math.fround(finite(v,'positions['+i+']')));if(packet.family==='CURVE'){const curveTopology=String(g.curveTopology||'LINE_STRIP');if(curveTopology==='LINE_STRIP')positions=lineStripPairs(positions);else if(curveTopology!=='SEGMENTS')fail('DEEP3D_WEBGPU_CURVE','unsupported curve topology '+curveTopology);if(g.indices!=null)fail('DEEP3D_WEBGPU_CURVE','indexed curves unsupported')}let indices=null;if(g.indices!=null){if(!Array.isArray(g.indices))fail('DEEP3D_WEBGPU_INDEX','indices must be array');indices=g.indices.map((v,i)=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<0||n>=positions.length/3)fail('DEEP3D_WEBGPU_INDEX','index['+i+'] out of range');return n})}const c=vec(packet.material?.baseColor||[.5,.5,.5],3,'baseColor'),opacity=finite(packet.material?.opacity??1,'opacity');return Object.freeze({id:packet.packetId,topology,positions:Object.freeze(positions),indices:indices&&Object.freeze(indices),color:Object.freeze([c[0],c[1],c[2],opacity]),domain:String(g.domain||'').toUpperCase(),sourceVertexCount:g.positions.length/3,drawVertexCount:positions.length/3})}
function compileScene(sceneInput,frameInput){const scene=P.createScene(sceneInput);if(!frameInput||typeof frameInput!=='object'||!frameInput.camera)fail('DEEP3D_WEBGPU_CAMERA','external camera required');const frameId=String(frameInput.camera.frameId||scene.frameId);if(frameId!==scene.frameId)fail('DEEP3D_WEBGPU_FRAME','scene/camera frame mismatch');for(const packet of scene.packets)if(packet.spatialAddress.frameId!==scene.frameId)fail('DEEP3D_WEBGPU_FRAME','packet/scene frame mismatch');return Object.freeze({scene,semanticSignature:scene.fingerprint,viewProjection:Object.freeze(vec(frameInput.camera.viewProjection,16,'viewProjection')),clearColor:Object.freeze(vec(frameInput.clearColor||[0,0,0,1],4,'clearColor')),draws:Object.freeze(scene.packets.map(compilePacket))})}
function createBackend(device,{context,format='bgra8unorm',maxBuffers=1024,maxTrackedBytes=67108864,maxInFlightFrames=3}={}){
 if(!device||typeof device.createShaderModule!=='function'||typeof device.createRenderPipeline!=='function'||typeof device.createCommandEncoder!=='function'||!device.queue||typeof device.queue.writeBuffer!=='function'||typeof device.queue.submit!=='function')fail('DEEP3D_WEBGPU_DEVICE','WebGPU device required');if(!context||typeof context.getCurrentTexture!=='function')fail('DEEP3D_WEBGPU_CONTEXT','GPUCanvasContext required');if(typeof context.configure==='function')context.configure({device,format,alphaMode:'premultiplied'});
 const owner=W.createBufferOwner(device,{maxBuffers,maxTrackedBytes}),module=device.createShaderModule({label:'ofu.deep3d.webgpu.shader',code:WGSL}),pipelines=new Map;let serial=0,inFlight=0,renderCount=0,lost=false,disposed=false,lastWitness=null;
 function pipeline(topology){if(pipelines.has(topology))return pipelines.get(topology);const p=device.createRenderPipeline({label:'ofu.deep3d.'+topology,layout:'auto',vertex:{module,entryPoint:'vs',buffers:[{arrayStride:12,attributes:[{shaderLocation:0,offset:0,format:'float32x3'}]}]},fragment:{module,entryPoint:'fs',targets:[{format}]},primitive:{topology,cullMode:'none'}});pipelines.set(topology,p);return p}
 function render(sceneInput,frameInput){if(disposed)fail('DEEP3D_WEBGPU_STATE','backend disposed');if(lost)fail('DEEP3D_WEBGPU_DEVICE_LOST','device lost');if(inFlight>=maxInFlightFrames)fail('DEEP3D_WEBGPU_BACKPRESSURE','too many in-flight frames');const compiled=compileScene(sceneInput,frameInput),frameNo=++serial,ids=[];inFlight++;try{const encoder=device.createCommandEncoder({label:'ofu.deep3d.frame.'+frameNo}),view=context.getCurrentTexture().createView(),c=compiled.clearColor,pass=encoder.beginRenderPass({label:'ofu.deep3d.pass.'+frameNo,colorAttachments:[{view,loadOp:'clear',storeOp:'store',clearValue:{r:c[0],g:c[1],b:c[2],a:c[3]}}]});let drawCalls=0;for(let i=0;i<compiled.draws.length;i++){const d=compiled.draws[i],p=pipeline(d.topology),vertexData=new Float32Array(d.positions),vid='deep3d:'+frameNo+':'+i+':v',vb=owner.create(vid,{size:Math.max(4,vertexData.byteLength),usage:U.VERTEX|U.COPY_DST});ids.push(vid);device.queue.writeBuffer(vb,0,vertexData.buffer,vertexData.byteOffset,vertexData.byteLength);const uniformData=new Float32Array(20);uniformData.set(compiled.viewProjection,0);uniformData.set(d.color,16);const uid='deep3d:'+frameNo+':'+i+':u',ub=owner.create(uid,{size:80,usage:U.UNIFORM|U.COPY_DST});ids.push(uid);device.queue.writeBuffer(ub,0,uniformData.buffer,uniformData.byteOffset,uniformData.byteLength);const bind=device.createBindGroup({layout:p.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:ub}}]});pass.setPipeline(p);pass.setBindGroup(0,bind);pass.setVertexBuffer(0,vb);if(d.indices){const indexData=new Uint32Array(d.indices),iid='deep3d:'+frameNo+':'+i+':i',ib=owner.create(iid,{size:Math.max(4,indexData.byteLength),usage:U.INDEX|U.COPY_DST});ids.push(iid);device.queue.writeBuffer(ib,0,indexData.buffer,indexData.byteOffset,indexData.byteLength);pass.setIndexBuffer(ib,'uint32');pass.drawIndexed(indexData.length,1,0,0,0)}else pass.draw(d.positions.length/3,1,0,0);drawCalls++}pass.end();device.queue.submit([encoder.finish()]);renderCount++;lastWitness=Object.freeze({version:VERSION,authority:AUTHORITY,backend:BACKEND,sceneFingerprint:compiled.semanticSignature,semanticSignature:compiled.semanticSignature,packetCount:compiled.draws.length,drawCalls,renderCount,pixelIdentityClaim:false,semanticDeterminism:true,primaryRendererAuthority:false,cameraAuthority:'EXTERNAL_READ_ONLY',sceneCompositionAuthority:'EXTERNAL_READ_ONLY',lightingMode:'UNLIT_PRESENTATION_STAGE_1',resourceLifecycle:'WEBGPU_BUFFER_OWNER'});const cleanup=()=>{for(const id of ids)owner.release(id);inFlight=Math.max(0,inFlight-1)};if(typeof device.queue.onSubmittedWorkDone==='function')Promise.resolve(device.queue.onSubmittedWorkDone()).then(cleanup,cleanup);else cleanup();return lastWitness}catch(error){for(const id of ids)owner.release(id);inFlight=Math.max(0,inFlight-1);throw error}}
 function deviceLost(){if(disposed)return snapshot();lost=true;owner.deviceLost();inFlight=0;return snapshot()}
 function dispose(){if(disposed)return snapshot();disposed=true;lost=true;owner.dispose();inFlight=0;return snapshot()}
 function snapshot(){return Object.freeze({version:VERSION,authority:AUTHORITY,backend:BACKEND,renderCount,inFlight,lost,disposed,primaryRendererAuthority:false,cameraAuthority:'EXTERNAL_READ_ONLY',sceneCompositionAuthority:'EXTERNAL_READ_ONLY',pixelIdentityClaim:false,resourceOwner:owner.snapshot(),lastWitness})}
 return Object.freeze({VERSION,AUTHORITY,BACKEND,render,deviceLost,dispose,snapshot});
}
O.deep3dWebGPUBackend=Object.freeze({VERSION,AUTHORITY,BACKEND,TOPOLOGY,WGSL,lineStripPairs,compilePacket,compileScene,createBackend});
})(typeof globalThis!=='undefined'?globalThis:this);
