import {W1_AUTHORITY} from '../../contracts/w1-observation-contracts.js';
import {SCIENTIFIC_WHY_UNCERTAINTY_KIND} from '../scientific-why.js';
import {AUTHORITY_RANK,INSTRUMENTS,SCIENTIFIC_INSTRUMENT_DEFAULT_LIMITS,SCIENTIFIC_INSTRUMENT_STATUS,SCIENTIFIC_INSTRUMENT_UNCERTAINTY_KIND} from './catalog.js';

const enc=new TextEncoder(),AUTH=new Set(Object.values(W1_AUTHORITY)),UNC=new Set(Object.values(SCIENTIFIC_INSTRUMENT_UNCERTAINTY_KIND));
export function fail(message){throw new Error('OFU Scientific Instruments: '+message)}
export function plain(v){if(!v||typeof v!=='object'||Array.isArray(v))return false;const p=Object.getPrototypeOf(v);return p===Object.prototype||p===null}
function exactKeys(v,want,label){if(!plain(v))fail(label+' must be a plain object');const a=Object.keys(v).sort(),b=[...want].sort();if(a.length!==b.length||a.some((k,i)=>k!==b[i]))fail(label+' has missing or unsupported fields')}
function bounded(v,label,min,max){if(!Number.isSafeInteger(v)||v<min||v>max)fail(label+' out of bounds');return v}
export function normalizeLimits(v={}){if(!plain(v))fail('limits must be a plain object');for(const k of Object.keys(v))if(!(k in SCIENTIFIC_INSTRUMENT_DEFAULT_LIMITS))fail('unsupported limit: '+k);return Object.freeze({
  maxRequests:bounded(v.maxRequests??32,'maxRequests',1,128),maxTextBytes:bounded(v.maxTextBytes??2048,'maxTextBytes',64,16384),
  maxCanonicalBytes:bounded(v.maxCanonicalBytes??262144,'maxCanonicalBytes',4096,1048576)});}
function text(v,label,l,max=l.maxTextBytes){if(typeof v!=='string')fail(label+' must be text');const x=v.normalize('NFC').trim();if(!x)fail(label+' must be non-empty');if(enc.encode(x).length>max)fail(label+' exceeds byte limit');return x}
function authority(v,label,l){const x=text(v,label,l,64).toUpperCase();if(!AUTH.has(x))fail(label+' is unsupported: '+x);return x}
export function lowerAuthority(a,b){return AUTHORITY_RANK[a]<=AUTHORITY_RANK[b]?a:b}
function integerText(v,label){let x;if(typeof v==='bigint')x=v.toString();else if(typeof v==='number'){if(!Number.isSafeInteger(v))fail(label+' must be a safe integer');x=String(v)}else if(typeof v==='string')x=v;else fail(label+' must be an integer-like scientific source value');if(!/^-?(0|[1-9][0-9]*)$/.test(x)||x==='-0')fail(label+' is not canonical integer text');return x}
function scaled(x,e){const neg=x[0]==='-',d0=neg?x.slice(1):x,d=d0.replace(/^0+(?=[0-9])/,'');if(d==='0')return'0';if(e>=0)return(neg?'-':'')+d+'0'.repeat(e);const n=-e;let y=d.length>n?d.slice(0,-n)+'.'+d.slice(-n):'0.'+'0'.repeat(n-d.length)+d;y=y.replace(/\.0+$/,'').replace(/(\.[0-9]*?)0+$/,'$1').replace(/\.$/,'');return(neg?'-':'')+y}
function decimal(v,label,l){let x=text(v,label,l,256);if(!/^-?(0|[1-9][0-9]*)(\.[0-9]+)?$/.test(x)||x==='-0')fail(label+' must be canonical decimal text');if(x.includes('.'))x=x.replace(/0+$/,'').replace(/\.$/,'');return x==='-0'?'0':x}
function cmp(a,b){const p=x=>{const neg=x[0]==='-',z=neg?x.slice(1):x,[w,f='']=z.split('.');return{neg,n:BigInt(w+f),s:f.length}},x=p(a),y=p(b),s=Math.max(x.s,y.s),xa=(x.neg?-1n:1n)*x.n*10n**BigInt(s-x.s),yb=(y.neg?-1n:1n)*y.n*10n**BigInt(s-y.s);return xa<yb?-1:xa>yb?1:0}
function get(root,path){let v=root;for(const k of path.split('.')){if(v==null||typeof v!=='object'||!(k in v))return undefined;v=v[k]}return v}
function none(){return Object.freeze({state:'NOT_DECLARED_UPSTREAM',kind:null,parameters:null,sourceAuthority:null,provenanceClass:null})}
function uncertainty(raw,{requestId,unit,sourceAuthority,def,fp,l}){if(raw===null)return{record:none(),why:null};if(fp.fingerprint.scientificModelVersion===null)fail('requests['+requestId+'].uncertainty requires an available scientific model');exactKeys(raw,['kind','sourceAuthority','provenanceClass','parameters'],'requests['+requestId+'].uncertainty');const kind=text(raw.kind,'uncertainty.kind',l,64).toUpperCase();if(!UNC.has(kind))fail('uncertainty.kind is unsupported: '+kind);const ua=authority(raw.sourceAuthority,'uncertainty.sourceAuthority',l);if(AUTHORITY_RANK[ua]>AUTHORITY_RANK[sourceAuthority])fail('uncertainty cannot exceed measurement source authority');const provenanceClass=text(raw.provenanceClass,'uncertainty.provenanceClass',l);let parameters;
  if(kind==='INTERVAL'){exactKeys(raw.parameters,['lower','upper','unit'],'uncertainty.parameters');const u=text(raw.parameters.unit,'uncertainty.parameters.unit',l,64);if(u!==unit)fail('uncertainty unit must match output unit');const lower=decimal(raw.parameters.lower,'uncertainty.lower',l),upper=decimal(raw.parameters.upper,'uncertainty.upper',l);if(cmp(lower,upper)>0)fail('uncertainty interval is reversed');parameters=Object.freeze({lower,upper,unit:u});}
  else if(kind==='QUALITATIVE'){exactKeys(raw.parameters,['label'],'uncertainty.parameters');parameters=Object.freeze({label:text(raw.parameters.label,'uncertainty.label',l)});}
  else{exactKeys(raw.parameters,['reason'],'uncertainty.parameters');parameters=Object.freeze({reason:text(raw.parameters.reason,'uncertainty.reason',l)});}
  const record=Object.freeze({state:'EXPLICIT_UPSTREAM_BOUND_INPUT',kind,parameters,sourceAuthority:ua,provenanceClass});return{record,why:Object.freeze({id:'instrument:'+requestId+':uncertainty',scope:Object.freeze({key:def.sourcePath,nodeType:def.whyNodeType,authority:sourceAuthority}),kind:kind==='INTERVAL'?SCIENTIFIC_WHY_UNCERTAINTY_KIND.INTERVAL:kind==='QUALITATIVE'?SCIENTIFIC_WHY_UNCERTAINTY_KIND.QUALITATIVE:SCIENTIFIC_WHY_UNCERTAINTY_KIND.UNKNOWN,parameters,sourceAuthority:ua,subjectCanonicalId:fp.fingerprint.subject.canonicalId,scientificModelVersion:fp.fingerprint.scientificModelVersion,provenanceClass})};}
export function normalizeRequest(raw,i,l){const label='requests['+i+']';exactKeys(raw,['requestId','instrumentId','outputUnit','uncertainty'],label);const requestId=text(raw.requestId,label+'.requestId',l,256),instrumentId=text(raw.instrumentId,label+'.instrumentId',l,128).toUpperCase(),outputUnit=raw.outputUnit===null?null:text(raw.outputUnit,label+'.outputUnit',l,64);if(raw.uncertainty!==null&&!plain(raw.uncertainty))fail(label+'.uncertainty must be null or a plain object');return Object.freeze({requestId,instrumentId,outputUnit,uncertainty:raw.uncertainty})}
export function evaluateRequest(request,fp,worldState,l){const def=INSTRUMENTS[request.instrumentId];if(!def){if(request.uncertainty!==null)fail('cannot attach uncertainty to an unsupported instrument');return Object.freeze({request,def:null,status:SCIENTIFIC_INSTRUMENT_STATUS.UNSUPPORTED,reason:'INSTRUMENT_NOT_REGISTERED',sourceAuthority:W1_AUTHORITY.UNKNOWN,unit:request.outputUnit,quantity:null,exactSource:null,uncertainty:none(),why:null,domainModel:null})}const unit=request.outputUnit??def.defaultUnit;if(!(unit in def.units)){if(request.uncertainty!==null)fail('cannot attach uncertainty to an unsupported output unit');return Object.freeze({request,def,status:SCIENTIFIC_INSTRUMENT_STATUS.UNSUPPORTED,reason:'OUTPUT_UNIT_UNSUPPORTED',sourceAuthority:fp.fingerprint.authorityByDomain[def.sourceDomain]??W1_AUTHORITY.UNKNOWN,unit,quantity:null,exactSource:null,uncertainty:none(),why:null,domainModel:null})}const sourceAuthority=fp.fingerprint.authorityByDomain[def.sourceDomain]??W1_AUTHORITY.UNKNOWN,state=worldState?.scientificState??null,raw=state?get(state,def.sourcePath):undefined,domainModel=def.basisPath&&state?get(state,def.basisPath):null;if(raw==null||sourceAuthority===W1_AUTHORITY.UNKNOWN){if(request.uncertainty!==null)fail('cannot attach numeric/model uncertainty to an UNKNOWN measurement');return Object.freeze({request,def,status:SCIENTIFIC_INSTRUMENT_STATUS.UNKNOWN,reason:'SOURCE_VALUE_UNAVAILABLE_OR_UNKNOWN_AUTHORITY',sourceAuthority,unit,quantity:null,exactSource:null,uncertainty:none(),why:null,domainModel:domainModel==null?null:String(domainModel)})}const integer=integerText(raw,'source '+def.sourcePath),u=uncertainty(request.uncertainty,{requestId:request.requestId,unit,sourceAuthority,def,fp,l});return Object.freeze({request,def,status:SCIENTIFIC_INSTRUMENT_STATUS.VALUE,reason:null,sourceAuthority,unit,quantity:Object.freeze({value:scaled(integer,def.units[unit]),unit}),exactSource:Object.freeze({integer,unit:def.sourceUnit,path:def.sourcePath}),uncertainty:u.record,why:u.why,domainModel:domainModel==null?null:String(domainModel)})}
