import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1280,height:800}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e.message||e)));await page.goto(pathToFileURL(path.resolve('dist/One_File_Universe.html')).href,{waitUntil:'load'});await page.waitForFunction(()=>OFU?.v1Experience?.snapshot?.().initialized&&OFU?.v1Session&&OFU?.v1LivingProduct?.snapshot?.().initialized&&OFU?.productUI,{timeout:30000});
const openExplore=async()=>{await page.evaluate(()=>OFU.productUI.workspace('explore',{focus:false,announceChange:false}));await page.waitForFunction(()=>!document.querySelector('[data-workspace-panel="explore"]').hidden)};
const stage=async expected=>page.waitForFunction(s=>OFU.v1LivingProduct.runtime.snapshot().stage===s,expected,{timeout:10000});
const clickScale=async id=>{await openExplore();const x=page.locator(`[data-living-scale="${id}"]:visible`).first();await x.waitFor({state:'visible',timeout:5000});await x.click()};
const clickFirstEntity=async()=>{await openExplore();const x=page.locator('#living-panel [data-living-entity]:visible').first();await x.waitFor({state:'visible',timeout:5000});await x.click()};
const clickAction=async id=>{await openExplore();const x=page.locator(`#living-panel [data-living-action="${id}"]:visible`).first();await x.waitFor({state:'visible',timeout:5000});await x.click()};
await clickScale('UNIVERSE');await stage('UNIVERSE');await clickFirstEntity();await stage('GALAXY');await clickFirstEntity();await stage('REGION');await clickAction('deeper');await stage('NEIGHBORHOOD');await clickFirstEntity();await stage('SYSTEM');
await openExplore();await page.locator('#living-panel #living-search-goal:visible').selectOption('BIOSPHERE');await clickAction('survey');await page.waitForFunction(()=>{const s=OFU.v1LivingProduct.snapshot().search;return !s.running&&s.results>0},null,{timeout:60000});await page.locator('#living-panel #living-search-results .living-choice:visible').first().click();await page.waitForFunction(()=>OFU.v1LivingProduct.runtime.snapshot().world?.biology?.occupancy?.state==='MODELED_BIOSPHERE',null,{timeout:30000});await clickScale('HUMAN');await stage('HUMAN');
const material=await page.evaluate(()=>OFU.v1LivingProduct.runtime.snapshot().rows.find(x=>!['SETTLEMENT','RUIN'].includes(x.kind))?.entityId||null);assert(material,'soak requires an inspectable Living material/object');await page.locator(`#living-panel [data-living-entity="${material}"]:visible`).first().click();const samples=[];
for(let cycle=0;cycle<20;cycle++){
 await openExplore();if((await page.evaluate(()=>OFU.v1LivingProduct.runtime.snapshot().stage))!=='HUMAN'){await clickScale('HUMAN');await stage('HUMAN')}
 await page.evaluate(id=>{const L=OFU.v1LivingProduct.runtime,s=L.snapshot();if(s.selectedObjectId!==id)L.selectObject(id);L.enterMicro(id);L.deeper();L.deeper();L.deeper();L.scale('HUMAN');OFU.v1Session.submit('MEASURE',{instrument:'soak-'+OFU.v1Session.snapshot().actions});OFU.v1Session.submit('SAMPLE',{medium:'regolith'});},material);
 if(cycle%5===0){const save=await page.evaluate(()=>OFU.v1Session.hex(OFU.v1Session.exportBytes()));await page.evaluate(()=>OFU.v1LivingProduct.runtime.scale('GALAXY'));await page.waitForFunction(()=>OFU.v1LivingProduct.runtime.snapshot().stage==='GALAXY');await page.evaluate(h=>OFU.v1Session.importBytes(OFU.v1Session.unhex(h)),save);await page.waitForFunction(()=>OFU.v1LivingProduct.runtime.snapshot().stage==='HUMAN')}
 samples.push(await page.evaluate(()=>{const p=__OFU_PLANET_PREVIEW__.snapshot(),v=OFU.v1Providers.snapshot(),s=OFU.v1Session.snapshot(),l=OFU.v1LivingProduct.runtime.snapshot(),r=OFU.v1LivingProduct.renderer.state();return{cycle:s.actions,providerCache:v.cacheEntries,providerCacheLimit:v.cacheLimit,session:s,livingStage:l.stage,livingHistory:l.historyDepth,livingHistoryLimit:l.maxHistory,livingCache:l.discoveryCacheEntries,livingCacheLimit:l.discoveryCacheLimit,render:r,working:p.workingSet||null,gpu:p.gpu||null,heap:performance.memory?.usedJSHeapSize||null}}));
}
for(const s of samples){assert(s.providerCache<=s.providerCacheLimit);assert.equal(s.livingStage,'HUMAN');assert(s.livingHistory<=s.livingHistoryLimit);assert(s.livingCache<=s.livingCacheLimit);assert.equal(s.session.canonicalMutation,false);assert.equal(s.session.canonicalP6Mutation,false);if(s.working){assert((s.working.activePatches??0)<=28);assert((s.working.cpuMeshes??0)<=64)}}const bytes=await page.evaluate(()=>OFU.v1Session.exportBytes().length);assert(bytes<1048576);assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({status:'PASS',suite:'v1-browser-soak',cycles:20,actions:samples.at(-1).cycle,sessionBytes:bytes,providerCache:samples.at(-1).providerCache,livingHistory:samples.at(-1).livingHistory,livingCache:samples.at(-1).livingCache,heapSamples:samples.map(x=>x.heap).filter(Boolean),pageErrors:errors.length,physicalDevices:'NOT_VERIFIED'}));await context.close();await browser.close();
