(function(root){
'use strict';
const O=root.OFU=root.OFU||{}; const MAX_SAVE_BYTES=1024*1024; const SCHEMA=1;
function payload({masterSeed256,manifestHash,events=[]}){if(!/^[0-9a-f]{64}$/i.test(masterSeed256))throw new Error('invalid seed');if(!/^[0-9a-f]{64}$/i.test(manifestHash))throw new Error('invalid manifest');if(!Array.isArray(events)||events.length>1024)throw new Error('invalid events');const normalized=events.map((e,i)=>{if(!e||typeof e!=='object'||typeof e.type!=='string'||e.type.length>64)throw new Error('invalid event '+i);return {seq:i,type:e.type,data:e.data??null};});return {schemaVersion:SCHEMA,canonicalProtocolVersion:'ofu-canonical-v1',universeIdentity:{masterSeed256:masterSeed256.toLowerCase(),generatorManifestHash:manifestHash.toLowerCase()},events:normalized};}
function exportPortable(input){const p=payload(input),digest=O.canonical.digestObject(p);return JSON.stringify({format:'OFU-SAVE',schemaVersion:SCHEMA,payload:p,integrity:{algorithm:'SHA-256',digest}});}
function importPortable(text){if(typeof text!=='string')throw new Error('save must be text');if(new TextEncoder().encode(text).length>MAX_SAVE_BYTES)throw new Error('save exceeds limit');let c;try{c=JSON.parse(text);}catch{throw new Error('malformed save');}if(!c||c.format!=='OFU-SAVE')throw new Error('unsupported save format');if(c.schemaVersion!==SCHEMA)throw new Error('unsupported save version');if(!c.integrity||c.integrity.algorithm!=='SHA-256'||!/^[0-9a-f]{64}$/.test(c.integrity.digest))throw new Error('invalid integrity metadata');const raw=c.payload||{};const p=payload({masterSeed256:raw.universeIdentity&&raw.universeIdentity.masterSeed256,manifestHash:raw.universeIdentity&&raw.universeIdentity.generatorManifestHash,events:raw.events});if(O.canonical.digestObject(p)!==c.integrity.digest)throw new Error('integrity mismatch');return p;}
function stateDigest(p){return O.canonical.digestObject(p);}
O.save={SCHEMA,MAX_SAVE_BYTES,payload,exportPortable,importPortable,stateDigest};
})(typeof globalThis!=='undefined'?globalThis:this);
