(function(root){
'use strict';
const O=root.OFU=root.OFU||{},R=O.v1ModelRegimeRuntime;if(!R)return;
const VERSION='ofu-v1-micro-canvas-1',state={canvas:null,ctx:null,frames:0,lastRegime:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function ensure(){if(state.canvas?.isConnected)return state.canvas;const planet=document.getElementById('planet-view'),frame=planet?.parentElement;if(!frame)return null;const c=document.createElement('canvas');c.id='v1-micro-view';c.dataset.authority='PRESENTATION_ONLY';c.setAttribute('aria-label','Microscopic modeled representation');c.style.cssText='position:absolute;inset:0;width:100%;height:100%;z-index:5;display:none;background:#02070b;touch-action:none';planet.insertAdjacentElement('afterend',c);state.canvas=c;state.ctx=c.getContext('2d');return c}
function resize(){const c=ensure();if(!c)return null;const dpr=Math.min(2,Math.max(1,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}return{w,h,dpr}}
function dot(g,x,y,r,alpha=.8){g.globalAlpha=alpha;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();g.globalAlpha=1}
function draw(){const snap=R.snapshot(),c=ensure();if(!c||!state.ctx)return;if(snap.mode!=='MODEL_REGIME'){c.style.display='none';return}c.style.display='block';const v=resize();if(!v)return;const g=state.ctx,{w,h}=v;g.clearRect(0,0,w,h);const bg=g.createRadialGradient(w*.5,h*.45,10,w*.5,h*.5,Math.max(w,h)*.7);bg.addColorStop(0,'#102a35');bg.addColorStop(1,'#02070b');g.fillStyle=bg;g.fillRect(0,0,w,h);g.fillStyle='#d9eef7';g.font=Math.max(13,Math.round(14*v.dpr))+'px system-ui';g.fillText(String(snap.regime).toUpperCase()+' - modeled microscopic regime',18*v.dpr,28*v.dpr);const value=snap.current;if(snap.regime==='tissue'){const cells=value?.cells||[];for(let i=0;i<cells.length;i++){const a=i/Math.max(1,cells.length)*Math.PI*2*3,r=.08*Math.min(w,h)+((i%7)/7)*.28*Math.min(w,h),x=w*.5+Math.cos(a)*r,y=h*.53+Math.sin(a)*r*.58;g.fillStyle=i%3===0?'#a4d5c2':'#6ba9b7';dot(g,x,y,clamp(4+(cells[i].phenotypePpm||0)/150000,4,11)*v.dpr,.74)}}else if(snap.regime==='cell'){const comps=value?.compartments||[];g.strokeStyle='#8fc7d9';g.lineWidth=2*v.dpr;g.beginPath();g.ellipse(w*.5,h*.53,w*.28,h*.30,0,0,Math.PI*2);g.stroke();for(let i=0;i<comps.length;i++){const a=i/comps.length*Math.PI*2,x=w*.5+Math.cos(a)*w*.14,y=h*.53+Math.sin(a)*h*.15;g.fillStyle='#87c9a8';dot(g,x,y,(13+i*3)*v.dpr,.62)}}else if(snap.regime==='molecular'){for(const [i,m] of (value?.complexes||[]).entries()){const a=i*2.399,x=w*.5+Math.cos(a)*(40+i*5)*v.dpr,y=h*.52+Math.sin(a)*(28+i*3)*v.dpr;g.fillStyle=['#9fd4e5','#b9a9dc','#86c8a0','#d6b579'][i%4];dot(g,x,y,7*v.dpr,.78)}}else if(snap.regime==='atomic'){for(const a of value?.atoms||[]){const p=a.position||[0,0,0],x=w*.5+p[0]*30*v.dpr,y=h*.53+p[1]*30*v.dpr,r=a.element==='H'?4:7;g.fillStyle=a.coordinateAuthority==='SOURCE_BACKED_ATOMIC'?'#e6d6a3':'#9bb7d1';dot(g,x,y,r*v.dpr,.86)}}g.fillStyle='#9bb5c1';g.font=Math.max(11,Math.round(11*v.dpr))+'px system-ui';g.fillText('Representation authority: '+(snap.lastWitness?.authority||'MODEL_DERIVED_SIMULATION'),18*v.dpr,h-18*v.dpr);state.frames++;state.lastRegime=snap.regime}
function sync(){const c=ensure();if(!c)return;const active=R.snapshot().mode==='MODEL_REGIME';c.style.display=active?'block':'none';document.getElementById('planet-view')?.style.setProperty('visibility',active?'hidden':'visible');const macro=document.getElementById('wave-iv-macro-view');if(macro&&active)macro.style.display='none';draw()}
if(typeof document!=='undefined'){R.onChange(sync);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{ensure();sync()},{once:true});else{ensure();sync()}}
O.v1MicroCanvas=Object.freeze({VERSION,ensure,draw,sync,snapshot:()=>Object.freeze({version:VERSION,attached:!!state.canvas,frames:state.frames,lastRegime:state.lastRegime,backend:'canvas2d-presentation',authority:'PRESENTATION_ONLY'})});
})(globalThis);
