import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
globalThis.OFU={};
for(const f of [
 'src/kernel/sha256.js','src/extensions/contracts.js','src/domains/v1/common.js','src/domains/v1/microscopic.js',
 'src/domains/v1/materials/material-model.js','src/domains/v1/materials/reference-properties.js','src/domains/v1/micro/source-adapters.js','src/domains/v1/micro/microstructure.js',
 'src/domains/v1/molecular/representative.js','src/domains/v1/molecular/reference-mass.js','src/domains/v1/molecular/stoichiometric-reference.js','src/domains/v1/molecular/electronic-reference.js',
 'src/domains/v1/atomic/representative.js','src/domains/v1/micro/pipeline.js','src/domains/v1/micro/matter-continuity-v2.js','src/rendering/microscopic/matter-continuity-provider.js'
])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const O=globalThis.OFU,C=O.v2x12MatterContinuity,M=O.v1Materials,A=O.v1MicroSourceAdapters,Legacy=O.v1Microscopic,Render=O.v2x12MicroscopicPresentation;
let cases=0;
const tissue=Legacy.tissue({organismIdentity:'v2x12-organism',cellCount:8,fieldUnits:100000});
const coarse=C.biologicalContinuity({tissueState:tissue,cellOrdinal:2});assert.equal(coarse.state,'COARSE_MODEL_ONLY');assert.equal(coarse.gradients.length,0);cases+=2;
const bio=C.biologicalContinuity({tissueState:tissue,cellOrdinal:2,descriptor:{organizationSupported:true,authority:'MODEL_DERIVED_SIMULATION',chemistryAuthority:M.CHEMISTRY.MODEL_DERIVED,componentBasis:'PROVIDER_DECLARED_MATERIAL_COMPONENT_PPM_NOT_MOLE_FRACTION',components:[{id:'WATER_PROXY',ppm:700000,formula:'H2O',authority:M.CHEMISTRY.MODEL_DERIVED},{id:'BIOMATERIAL_UNRESOLVED',ppm:200000,authority:M.CHEMISTRY.UNRESOLVED}],compartments:[{id:'CYTOSOL',fractionPpm:650000},{id:'MEMBRANE',fractionPpm:150000},{id:'ORGANELLE_POOL',fractionPpm:100000}],membranes:[{id:'CELL_MEMBRANE',separates:['CYTOSOL','MEMBRANE'],permeabilityClass:'SELECTIVE_MODEL_DESCRIPTOR'}],gradients:[{id:'ION_GRADIENT_PROXY',quantity:'ION_ACTIVITY_PROXY',from:'CYTOSOL',to:'MEMBRANE',relativeDeltaPpm:120000}],transport:[{id:'ION_TRANSPORT_PROXY',speciesId:'ION_PROXY',from:'CYTOSOL',to:'MEMBRANE',relativeCapacityPpm:80000}],materialFlows:[{id:'METABOLIC_FLOW_TOPOLOGY',inputs:['WATER_PROXY','BIOMATERIAL_UNRESOLVED'],outputs:['BIOMATERIAL_UNRESOLVED']}]}});
assert.equal(bio.state,'PROVIDER_SUPPORTED_DESCRIPTOR');assert.equal(bio.materialCommitmentPreserved,true);assert.equal(bio.compartments.reduce((n,x)=>n+x.materialUnits,0),bio.materialUnits);assert.equal(bio.compartments.at(-1).id,'UNRESOLVED_COMPARTMENT_REMAINDER');assert.equal(bio.transport[0].fluxRateClaim,false);assert.equal(bio.materialFlows[0].metabolicKineticsClaim,false);assert.equal(bio.componentBasis,'PROVIDER_DECLARED_MATERIAL_COMPONENT_PPM_NOT_MOLE_FRACTION');cases+=7;
const bioJourney=C.journey(bio.materialSource,{microFeatures:64,molecularUnits:24,atoms:64});assert.equal(C.reconcile(bioJourney).status,'PASS');assert.equal(bioJourney.molecular.exactMolecularInventoryClaim,false);assert.equal(bioJourney.atomic.dynamics,'NOT_SIMULATED');assert(bioJourney.resources.counts.microFeatures<=128&&bioJourney.resources.counts.molecularUnits<=64&&bioJourney.resources.counts.atoms<=256);cases+=4;
const unknownRock=M.source({sourceEntityId:'v2x12-unknown-rock',kind:'ROCK',provider:'fixture'}),rockJourney=C.journey(unknownRock);assert.equal(C.reconcile(rockJourney).status,'PASS');assert.equal(rockJourney.molecular.status,'INSUFFICIENT_CHEMISTRY_FOR_MOLECULAR_STRUCTURE');assert.equal(rockJourney.atomic.atomCount,0);assert.equal(rockJourney.atomic.status,'INSUFFICIENT_CHEMISTRY_FOR_ATOMIC_STRUCTURE');cases+=4;
const manufactured=A.manufactured({artifactIdentity:'v2x12-alloy',technologySupported:true,family:'ALLOY',structure:'POLYCRYSTALLINE_PROXY',components:[{id:'IRON',ppm:980000,formula:'Fe'},{id:'UNRESOLVED_ALLOYING',ppm:20000}]});const manufacturedNoProv=C.journey(manufactured,{atoms:32});assert.equal(manufacturedNoProv.continuity.status,'FAIL_CLOSED');cases++;
const provider=Render.providerDescriptor();assert.equal(provider.canonicalMutationAuthority,false);assert.equal(provider.sharedSelectionAuthority,false);assert.equal(provider.maxNodes,C.CAPS.renderNodes);cases+=3;
assert.throws(()=>C.atomicStructureRecord({sourceEntityId:'x',sourceRecord:{sourceId:'x',dataset:'x',version:'1',licenseId:'CC0-1.0',method:'fixture',accessedOn:'2026-09-07',citation:'fixture',authorityClass:'SOURCE_BACKED_EXPERIMENTAL_STRUCTURE'},coordinateFrame:'x',inputUnit:'fm',roundingPolicy:'NONE',sites:Array.from({length:C.CAPS.sourceAtomSites+1},(_,i)=>({siteId:'s'+i,element:'C',positionFm:[i,0,0]}))}),/bound/i);cases++;
console.log(JSON.stringify({status:'PASS',suite:'v2x12-continuity-biology',cases}));
