import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
globalThis.OFU={};
for(const f of [
 'src/kernel/sha256.js','src/extensions/contracts.js','src/domains/v1/common.js','src/domains/v1/microscopic.js',
 'src/domains/v1/materials/material-model.js','src/domains/v1/materials/reference-properties.js','src/domains/v1/micro/source-adapters.js','src/domains/v1/micro/microstructure.js',
 'src/domains/v1/molecular/representative.js','src/domains/v1/molecular/reference-mass.js','src/domains/v1/molecular/stoichiometric-reference.js','src/domains/v1/molecular/electronic-reference.js',
 'src/domains/v1/atomic/representative.js','src/domains/v1/micro/pipeline.js','src/domains/v1/micro/matter-continuity-v2.js','src/domains/v1/micro/matter-continuity-unit-contract.js','src/rendering/microscopic/matter-continuity-provider.js'
])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const O=globalThis.OFU,C=O.v2x12MatterContinuity,M=O.v1Materials,A=O.v1MicroSourceAdapters,Legacy=O.v1Microscopic,Render=O.v2x12MicroscopicPresentation;
let cases=0;
const tissue=Legacy.tissue({organismIdentity:'v2x12-organism',cellCount:8,fieldUnits:100000});
const tissueView=Render.presentTissue(tissue,{maxNodes:8});assert.equal(tissueView.authority,'PRESENTATION_ONLY');assert.equal(tissueView.nodeCount,8);assert.equal(tissueView.nodeAvailableCount,8);assert.equal(tissueView.nodesTruncated,false);assert.equal(tissueView.descriptorCues.materialUnitClosure,true);assert.equal(tissueView.descriptorCues.totalCellStoreUnits,tissue.fieldUnits);assert.equal(tissueView.resourceWitness.omittedStoreUnits,0);assert(tissueView.nodes.every(x=>x.kind==='TISSUE_CELL'&&x.positionAuthority==='PRESENTATION_ONLY'&&x.exactCellPositionClaim===false&&x.cellDynamicsSimulated===false));cases+=8;
const tissueBudgetView=Render.presentTissue(tissue,{maxNodes:2});assert.equal(tissueBudgetView.nodeCount,2);assert.equal(tissueBudgetView.nodeAvailableCount,8);assert.equal(tissueBudgetView.nodesTruncated,true);assert.deepEqual(tissueBudgetView.nodes[0].position,tissueView.nodes[0].position);assert.deepEqual(tissueBudgetView.nodes[1].position,tissueView.nodes[1].position);assert(tissueBudgetView.resourceWitness.omittedStoreUnits>0);assert.equal(tissueBudgetView.descriptorCues.materialUnitClosure,true);cases+=7;
assert.throws(()=>Render.presentTissue({...tissue,massCommitmentUnits:tissue.massCommitmentUnits+1},{maxNodes:8}),/material commitment closure/i);cases++;const duplicateCells=tissue.cells.map((x,i)=>i===1?{...x,cellIdentity:tissue.cells[0].cellIdentity}:x);assert.throws(()=>Render.presentTissue({...tissue,cells:duplicateCells},{maxNodes:8}),/duplicate tissue cell identity/i);cases++;const duplicateOrdinals=tissue.cells.map((x,i)=>i===1?{...x,ordinal:tissue.cells[0].ordinal}:x);assert.throws(()=>Render.presentTissue({...tissue,cells:duplicateOrdinals},{maxNodes:8}),/duplicate tissue cell ordinal/i);cases++;
const coarse=C.biologicalContinuity({tissueState:tissue,cellOrdinal:2});assert.equal(coarse.state,'COARSE_MODEL_ONLY');assert.equal(coarse.gradients.length,0);cases+=2;
const coarseView=Render.presentBiological(coarse,{maxNodes:16});assert.equal(coarseView.authority,'PRESENTATION_ONLY');assert.equal(coarseView.state,'COARSE_MODEL_ONLY');assert.equal(coarseView.nodeCount,4);assert.equal(coarseView.nodeAvailableCount,4);assert.equal(coarseView.nodesTruncated,false);assert.equal(coarseView.relationCount,0);assert.equal(coarseView.relationAvailableCount,0);assert.equal(coarseView.relationsTruncated,false);assert.equal(coarseView.descriptorCues.organizationSupported,false);assert.equal(coarseView.descriptorCues.materialCommitmentPreserved,false);assert.equal(coarseView.descriptorCues.baseMaterialPartitionPreserved,true);assert.equal(coarseView.descriptorCues.materialUnitClosure,true);assert.equal(coarseView.resourceWitness.measuredRuntimeEvidence,false);assert(coarseView.nodes.every(x=>x.positionAuthority==='PRESENTATION_ONLY'&&x.exactGeometryClaim===false&&x.absoluteConcentrationClaim===false));cases+=14;
assert.throws(()=>Render.presentBiological({...coarse,membranes:[{id:'INJECTED_MEMBRANE',separates:['x','y']}]},{maxNodes:16}),/coarse biology forbids rich relation cues/i);cases++;assert.throws(()=>Render.presentBiological({...coarse,materialCommitmentPreserved:true},{maxNodes:16}),/coarse biology cannot claim provider material commitment/i);cases++;
const bio=C.biologicalContinuity({tissueState:tissue,cellOrdinal:2,descriptor:{organizationSupported:true,authority:'MODEL_DERIVED_SIMULATION',chemistryAuthority:M.CHEMISTRY.MODEL_DERIVED,componentBasis:'PROVIDER_DECLARED_MATERIAL_COMPONENT_PPM_NOT_MOLE_FRACTION',components:[{id:'WATER_PROXY',ppm:700000,formula:'H2O',authority:M.CHEMISTRY.MODEL_DERIVED},{id:'BIOMATERIAL_UNRESOLVED',ppm:200000,authority:M.CHEMISTRY.UNRESOLVED}],compartments:[{id:'CYTOSOL',fractionPpm:650000},{id:'MEMBRANE',fractionPpm:150000},{id:'ORGANELLE_POOL',fractionPpm:100000}],membranes:[{id:'CELL_MEMBRANE',separates:['CYTOSOL','MEMBRANE'],permeabilityClass:'SELECTIVE_MODEL_DESCRIPTOR'}],gradients:[{id:'ION_GRADIENT_PROXY',quantity:'ION_ACTIVITY_PROXY',from:'CYTOSOL',to:'MEMBRANE',relativeDeltaPpm:120000}],transport:[{id:'ION_TRANSPORT_PROXY',speciesId:'ION_PROXY',from:'CYTOSOL',to:'MEMBRANE',relativeCapacityPpm:80000}],materialFlows:[{id:'METABOLIC_FLOW_TOPOLOGY',inputs:['WATER_PROXY','BIOMATERIAL_UNRESOLVED'],outputs:['BIOMATERIAL_UNRESOLVED']}]}});
assert.equal(bio.state,'PROVIDER_SUPPORTED_DESCRIPTOR');assert.equal(bio.materialCommitmentPreserved,true);assert.equal(bio.compartments.reduce((n,x)=>n+x.materialUnits,0),bio.materialUnits);assert.equal(bio.compartments.at(-1).id,'UNRESOLVED_COMPARTMENT_REMAINDER');assert.equal(bio.transport[0].fluxRateClaim,false);assert.equal(bio.materialFlows[0].metabolicKineticsClaim,false);assert.equal(bio.componentBasis,'PROVIDER_DECLARED_MATERIAL_COMPONENT_PPM_NOT_MOLE_FRACTION');cases+=7;
const bioView=Render.presentBiological(bio,{maxNodes:16});assert.equal(bioView.nodeCount,4);assert.equal(bioView.nodeAvailableCount,4);assert.equal(bioView.nodesTruncated,false);assert.equal(bioView.relationCount,4);assert.equal(bioView.relationAvailableCount,4);assert.equal(bioView.relationsTruncated,false);assert.equal(bioView.descriptorCues.organizationSupported,true);assert.equal(bioView.descriptorCues.materialCommitmentPreserved,true);assert.equal(bioView.descriptorCues.baseMaterialPartitionPreserved,true);assert.equal(bioView.descriptorCues.materialUnitClosure,true);assert.equal(bioView.descriptorCues.dynamicsSimulated,false);assert(bioView.nodes.some(x=>x.kind==='UNRESOLVED_COMPARTMENT'&&x.exactGeometryClaim===false));assert(bioView.relations.some(x=>x.kind==='MEMBRANE_TOPOLOGY_CUE'&&x.transportRateClaim===false));assert(bioView.relations.some(x=>x.kind==='RELATIVE_GRADIENT_CUE'&&x.absoluteConcentrationClaim===false&&x.dynamicsSimulated===false));assert(bioView.relations.some(x=>x.kind==='TRANSPORT_CAPACITY_CUE'&&x.fluxRateClaim===false&&x.dynamicsSimulated===false));assert(bioView.relations.some(x=>x.kind==='MATERIAL_FLOW_TOPOLOGY_CUE'&&x.rateClaim===false&&x.metabolicKineticsClaim===false));assert.equal(bioView.resourceWitness.measuredRuntimeEvidence,false);cases+=17;
assert.throws(()=>Render.presentBiological({...bio,materialUnits:bio.materialUnits+1},{maxNodes:16}),/material commitment closure/i);cases++;const duplicateCompartments=bio.compartments.map((x,i)=>i===1?{...x,id:bio.compartments[0].id}:x);assert.throws(()=>Render.presentBiological({...bio,compartments:duplicateCompartments},{maxNodes:16}),/duplicate biological compartment/i);cases++;assert.throws(()=>Render.presentBiological({...bio,materialCommitmentPreserved:false},{maxNodes:16}),/provider-supported biological material commitment/i);cases++;
assert.throws(()=>Render.presentBiological({...bio,membranes:[{...bio.membranes[0],separates:['CYTOSOL','MISSING_COMPARTMENT']}]},{maxNodes:16}),/membrane compartments/i);cases++;assert.throws(()=>Render.presentBiological({...bio,gradients:[{...bio.gradients[0],to:'MISSING_COMPARTMENT'}]},{maxNodes:16}),/gradient compartments/i);cases++;assert.throws(()=>Render.presentBiological({...bio,transport:[{...bio.transport[0],from:'MISSING_COMPARTMENT'}]},{maxNodes:16}),/transport compartments/i);cases++;assert.throws(()=>Render.presentBiological({...bio,membranes:Array.from({length:C.CAPS.membranes+1},(_,i)=>({...bio.membranes[0],id:'OVER_'+i}))},{maxNodes:16}),/biological membranes bound/i);cases++;assert.throws(()=>Render.presentBiological({...bio,materialFlows:[{...bio.materialFlows[0],inputs:Array.from({length:C.CAPS.reactionTerms+1},(_,i)=>'X'+i)}]},{maxNodes:16}),/material flow term bound/i);cases++;
const bioBudgetView=Render.presentBiological(bio,{maxNodes:2});assert.equal(bioBudgetView.nodeCount,2);assert.equal(bioBudgetView.nodeAvailableCount,4);assert.equal(bioBudgetView.nodesTruncated,true);assert.deepEqual(bioBudgetView.nodes[0].position,bioView.nodes[0].position);assert.deepEqual(bioBudgetView.nodes[1].position,bioView.nodes[1].position);assert.equal(bioBudgetView.relationAvailableCount,4);assert.equal(bioBudgetView.relationsTruncated,false);cases+=7;
const denseBioFixture={...bio,membranes:Array.from({length:32},(_,i)=>({...bio.membranes[0],id:'M'+i})),gradients:Array.from({length:32},(_,i)=>({...bio.gradients[0],id:'G'+i})),transport:Array.from({length:48},(_,i)=>({...bio.transport[0],id:'T'+i})),materialFlows:Array.from({length:32},(_,i)=>({...bio.materialFlows[0],id:'F'+i}))},denseBioView=Render.presentBiological(denseBioFixture,{maxNodes:16});assert.equal(denseBioView.relationAvailableCount,144);assert.equal(denseBioView.relationCount,128);assert.equal(denseBioView.relationsTruncated,true);assert.equal(new Set(denseBioView.relations.map(x=>x.id)).size,128);for(const kind of ['MEMBRANE_TOPOLOGY_CUE','RELATIVE_GRADIENT_CUE','TRANSPORT_CAPACITY_CUE','MATERIAL_FLOW_TOPOLOGY_CUE'])assert(denseBioView.relations.some(x=>x.kind===kind));const denseTransportWitness=denseBioView.relationCategoryWitness.find(x=>x.kind==='TRANSPORT_CAPACITY_CUE');assert.equal(denseTransportWitness.availableCount,48);assert.equal(denseTransportWitness.projectedCount,32);assert.equal(denseTransportWitness.omittedCount,16);assert.equal(denseTransportWitness.truncated,true);cases+=12;
const bioJourney=C.journey(bio.materialSource,{microFeatures:64,molecularUnits:24,atoms:64});assert.equal(C.reconcile(bioJourney).status,'PASS');assert.equal(bioJourney.molecular.exactMolecularInventoryClaim,false);assert.equal(bioJourney.atomic.dynamics,'NOT_SIMULATED');assert(bioJourney.resources.counts.microFeatures<=128&&bioJourney.resources.counts.molecularUnits<=64&&bioJourney.resources.counts.atoms<=256);cases+=4;
const unknownRock=M.source({sourceEntityId:'v2x12-unknown-rock',kind:'ROCK',provider:'fixture'}),rockJourney=C.journey(unknownRock);assert.equal(C.reconcile(rockJourney).status,'PASS');assert.equal(rockJourney.molecular.status,'INSUFFICIENT_CHEMISTRY_FOR_MOLECULAR_STRUCTURE');assert.equal(rockJourney.atomic.atomCount,0);assert.equal(rockJourney.atomic.status,'INSUFFICIENT_CHEMISTRY_FOR_ATOMIC_STRUCTURE');cases+=4;
const unknownMaterialView=Render.present(rockJourney,{regime:'MATERIAL',maxNodes:16}),unknownMolecularView=Render.present(rockJourney,{regime:'MOLECULAR',maxNodes:16}),unknownAtomicView=Render.present(rockJourney,{regime:'ATOMIC',maxNodes:16});assert.equal(unknownMaterialView.nodeCount,1);assert.equal(unknownMaterialView.nodeAvailableCount,1);assert.equal(unknownMaterialView.nodes[0].componentId,'UNRESOLVED_REMAINDER');assert.equal(unknownMaterialView.nodes[0].kind,'UNRESOLVED_MATERIAL_REMAINDER');assert.equal(unknownMaterialView.nodes[0].unresolved,true);assert.equal(unknownMaterialView.nodes[0].chemistryDescriptorPresent,false);assert.equal(unknownMaterialView.nodes[0].chemistryKnowledgeStatus,'UNKNOWN_UNRESOLVED');assert.equal(unknownMaterialView.nodes[0].knownChemistryClaim,false);assert.equal(unknownMaterialView.nodes[0].exactChemicalIdentityClaim,false);assert.equal(unknownMaterialView.nodes[0].ppm,1000000);assert.equal(unknownMaterialView.nodes[0].formula,null);assert.equal(unknownMaterialView.nodes[0].componentAuthority,M.CHEMISTRY.UNRESOLVED);assert.equal(unknownMaterialView.nodes[0].exactBulkCompositionClaim,false);assert.equal(unknownMaterialView.descriptorCues.chemistryAuthority,M.CHEMISTRY.UNRESOLVED);assert.equal(unknownMaterialView.descriptorCues.chemistryKnowledgeStatus,'UNKNOWN_UNRESOLVED');assert.equal(unknownMaterialView.descriptorCues.describedComponentCount,0);assert.equal(unknownMaterialView.descriptorCues.unresolvedComponentCount,1);assert.equal(unknownMaterialView.descriptorCues.descriptorCoverageComplete,false);assert.equal(unknownMaterialView.descriptorCues.knownChemistryClaim,false);assert.equal(unknownMaterialView.descriptorCues.exactChemicalIdentityClaim,false);assert.equal(unknownMaterialView.fidelity.level,'UNRESOLVED_MATERIAL_CHEMISTRY');assert.equal(unknownMolecularView.nodeCount,0);assert.equal(unknownMolecularView.relationCount,0);assert.equal(unknownMolecularView.relationAvailableCount,0);assert.equal(unknownMolecularView.fidelity.level,'UNRESOLVED_CHEMISTRY');assert.equal(unknownAtomicView.nodeCount,0);assert.equal(unknownAtomicView.nodeAvailableCount,0);assert.equal(unknownAtomicView.descriptorCues.sourceStructurePresent,false);assert.equal(unknownAtomicView.quantumBoundary.wavefunctionClaim,false);cases+=29;
const coarseChemistrySource=M.fromPlanetSurface({planetIdentity:'v2x12-planet',composition:{metalPpm:300000,silicatePpm:700000},climate:{}},{kind:'ROCK'}),coarseChemistryJourney=C.journey(coarseChemistrySource),coarseChemistryView=Render.present(coarseChemistryJourney,{regime:'MATERIAL',maxNodes:16});assert.equal(coarseChemistryJourney.material.chemistryAuthority,M.CHEMISTRY.MODEL_DERIVED);assert.equal(coarseChemistryView.descriptorCues.chemistryAuthority,M.CHEMISTRY.MODEL_DERIVED);assert.equal(coarseChemistryView.descriptorCues.chemistryKnowledgeStatus,'UNKNOWN_UNRESOLVED');assert.equal(coarseChemistryView.descriptorCues.describedComponentCount,0);assert.equal(coarseChemistryView.descriptorCues.unresolvedComponentCount,2);assert.equal(coarseChemistryView.descriptorCues.descriptorCoverageComplete,false);assert(coarseChemistryView.nodes.every(x=>x.chemistryDescriptorPresent===false&&x.chemistryKnowledgeStatus==='UNKNOWN_UNRESOLVED'&&x.knownChemistryClaim===false&&x.exactChemicalIdentityClaim===false));cases+=7;
const partialChemistrySource=M.source({sourceEntityId:'v2x12-partial-chemistry',kind:'ROCK',provider:'fixture',chemistryAuthority:M.CHEMISTRY.MODEL_DERIVED,components:[{id:'WATER_PROXY',ppm:500000,formula:'H2O'},{id:'SILICATE_FRACTION',ppm:500000}]}),partialChemistryJourney=C.journey(partialChemistrySource),partialChemistryView=Render.present(partialChemistryJourney,{regime:'MATERIAL',maxNodes:16}),describedNode=partialChemistryView.nodes.find(x=>x.componentId==='WATER_PROXY'),descriptorlessNode=partialChemistryView.nodes.find(x=>x.componentId==='SILICATE_FRACTION');assert.equal(partialChemistryView.descriptorCues.chemistryAuthority,M.CHEMISTRY.MODEL_DERIVED);assert.equal(partialChemistryView.descriptorCues.chemistryKnowledgeStatus,'PARTIAL_DESCRIPTOR_WITH_UNRESOLVED_CHEMISTRY');assert.equal(partialChemistryView.descriptorCues.describedComponentCount,1);assert.equal(partialChemistryView.descriptorCues.unresolvedComponentCount,1);assert.equal(partialChemistryView.descriptorCues.descriptorCoverageComplete,false);assert.equal(describedNode.chemistryDescriptorPresent,true);assert.equal(describedNode.chemistryKnowledgeStatus,'DESCRIPTOR_AVAILABLE_NOT_EXACT_IDENTITY');assert.equal(describedNode.knownChemistryClaim,false);assert.equal(describedNode.exactChemicalIdentityClaim,false);assert.equal(descriptorlessNode.unresolved,false);assert.equal(descriptorlessNode.chemistryDescriptorPresent,false);assert.equal(descriptorlessNode.chemistryKnowledgeStatus,'UNKNOWN_UNRESOLVED');assert.equal(descriptorlessNode.knownChemistryClaim,false);assert.equal(descriptorlessNode.exactChemicalIdentityClaim,false);cases+=14;
const completeChemistrySource=M.source({sourceEntityId:'v2x12-complete-descriptor',kind:'ROCK',provider:'fixture',chemistryAuthority:M.CHEMISTRY.MODEL_DERIVED,components:[{id:'SILICA_PROXY',ppm:1000000,formula:'SiO2'}]}),completeChemistryJourney=C.journey(completeChemistrySource),completeChemistryView=Render.present(completeChemistryJourney,{regime:'MATERIAL',maxNodes:16});assert.equal(completeChemistryView.descriptorCues.chemistryAuthority,M.CHEMISTRY.MODEL_DERIVED);assert.equal(completeChemistryView.descriptorCues.chemistryKnowledgeStatus,'DESCRIPTOR_BOUNDED_NOT_EXACT_IDENTITY');assert.equal(completeChemistryView.descriptorCues.describedComponentCount,1);assert.equal(completeChemistryView.descriptorCues.unresolvedComponentCount,0);assert.equal(completeChemistryView.descriptorCues.descriptorCoverageComplete,true);assert.equal(completeChemistryView.nodes[0].chemistryDescriptorPresent,true);assert.equal(completeChemistryView.nodes[0].chemistryKnowledgeStatus,'DESCRIPTOR_AVAILABLE_NOT_EXACT_IDENTITY');assert.equal(completeChemistryView.nodes[0].knownChemistryClaim,false);assert.equal(completeChemistryView.nodes[0].exactChemicalIdentityClaim,false);cases+=9;
const manufactured=A.manufactured({artifactIdentity:'v2x12-alloy',technologySupported:true,family:'ALLOY',structure:'POLYCRYSTALLINE_PROXY',components:[{id:'IRON',ppm:980000,formula:'Fe'},{id:'UNRESOLVED_ALLOYING',ppm:20000}]});const manufacturedNoProv=C.journey(manufactured,{atoms:32});assert.equal(manufacturedNoProv.continuity.status,'FAIL_CLOSED');cases++;
const manufacturedView=Render.present(manufacturedNoProv,{regime:'MATERIAL',maxNodes:16});assert.equal(manufacturedView.descriptorCues.claimEligible,false);assert.equal(manufacturedView.fidelity.level,'PROVENANCE_INCOMPLETE');assert(manufacturedView.nodes.every(x=>x.exactBulkCompositionClaim===false));cases+=3;
const provider=Render.providerDescriptor();assert.equal(provider.canonicalMutationAuthority,false);assert.equal(provider.sharedSelectionAuthority,false);assert.equal(provider.maxNodes,C.CAPS.renderNodes);assert.equal(provider.maxRelations,128);assert(provider.capabilities.includes('TISSUE_CELL_FIELD_CUES'));assert(provider.capabilities.includes('BIOLOGICAL_COMPARTMENT_CUES'));assert(provider.capabilities.includes('BIOLOGICAL_TRANSPORT_TOPOLOGY_CUES'));assert(provider.capabilities.includes('EXPLICIT_TRUNCATION_WITNESS'));assert(provider.capabilities.includes('CATEGORY_PRESERVING_RELATION_PROJECTION'));assert(provider.capabilities.includes('UNRESOLVED_REMAINDER_CUES'));assert(provider.capabilities.includes('EXACT_INTEGER_FM_NORMALIZATION'));assert(provider.capabilities.includes('FAIL_CLOSED_BIOLOGICAL_BOUNDARY'));assert(provider.capabilities.includes('EXPLICIT_UNKNOWN_CHEMISTRY_CLAIM_STATE'));assert(provider.capabilities.includes('CHEMISTRY_DESCRIPTOR_COVERAGE_WITNESS'));cases+=14;
assert.throws(()=>Render.presentTissue(tissue,{maxNodes:C.CAPS.renderNodes+1}),/maxNodes|bound/i);cases++;
assert.throws(()=>Render.presentBiological(bio,{maxNodes:C.CAPS.renderNodes+1}),/maxNodes|bound/i);cases++;
assert.throws(()=>C.atomicStructureRecord({sourceEntityId:'x',sourceRecord:{sourceId:'x',dataset:'x',version:'1',licenseId:'CC0-1.0',method:'fixture',accessedOn:'2026-09-07',citation:'fixture',authorityClass:'SOURCE_BACKED_EXPERIMENTAL_STRUCTURE'},coordinateFrame:'x',inputUnit:'fm',roundingPolicy:'NONE',sites:Array.from({length:C.CAPS.sourceAtomSites+1},(_,i)=>({siteId:'s'+i,element:'C',positionFm:[i,0,0]}))}),/bound/i);cases++;
console.log(JSON.stringify({status:'PASS',suite:'v2x12-continuity-biology',cases}));
