(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,Materials=O.v1Materials,Micro=O.v1Microstructure,Molecular=O.v1Molecular,Atomic=O.v1Atomic;if(!V||!Materials||!Micro||!Molecular||!Atomic)throw new Error('v1 micro pipeline prerequisites missing');
const VERSION='ofu-v1-micro-pipeline-1',ORDER=Object.freeze(['material','microstructure','molecular','atomic']),CAPS=Object.freeze({microFeatures:128,molecularUnits:64,atoms:256,cacheEntries:4});
function uncertaintyFor(value){if(value==='SOURCE_BACKED_KNOWN_CHEMISTRY')return Object.freeze({class:'BOUNDED_SOURCE_UNCERTAINTY',reason:'Source classification may not resolve impurities, isotopes, defects, or exact local state.'});if(value==='MODEL_DERIVED_PLAUSIBLE_CHEMISTRY')return Object.freeze({class:'MODEL_UNCERTAINTY',reason:'Chemistry is a bounded model-derived representation, not a measurement.'});if(value==='UNRESOLVED_CHEMISTRY')return Object.freeze({class:'INSUFFICIENT_INFORMATION',reason:'Chemistry is intentionally unresolved.'});return Object.freeze({class:'PRESENTATION_UNCERTAINTY',reason:'Representation is schematic.'});}
function witness(from,to,operation,source,child,authority,extra={}){return V.freezeDeep({contract:'ofu-v1-micro-regime-transition-1',transitionId:V.deriveId('micro-transition',source.sourceEntityId,from,to,operation,child?.representationId||child?.materialId||'source'),operation,from:from.toUpperCase(),to:to.toUpperCase(),sourceEntityId:source.sourceEntityId,identityPreserved:true,geometricZoomClaim:false,representationAuthority:authority,scaleRegime:to.toUpperCase(),resolution:extra.resolution||Object.freeze({kind:'SEMANTIC_REGIME',detail:to.toUpperCase()}),uncertainty:uncertaintyFor(extra.chemistryAuthority||source.chemistryAuthority),inherited:Object.freeze(extra.inherited||['sourceEntityId','provenance']),newlyModeled:Object.freeze(extra.newlyModeled||[]),parentRepresentationId:extra.parentRepresentationId||null,childRepresentationId:child?.representationId||child?.materialId||null});}
function createSession(sourceSpec,{sampleIndex=0,microFeatures=64,molecularUnits=24,atoms=128,rveSizeNm=1000000}={}){V.int(sampleIndex,'sampleIndex',0,1000000);V.int(microFeatures,'microFeatures',1,CAPS.microFeatures);V.int(molecularUnits,'molecularUnits',1,CAPS.molecularUnits);V.int(atoms,'atoms',1,CAPS.atoms);V.int(rveSizeNm,'rveSizeNm',10,1000000000000);const source=sourceSpec?.contract==='ofu-v1-micro-source-1'?sourceSpec:Materials.source(sourceSpec),sessionId=V.deriveId('micro-session',source.sourceEntityId,sampleIndex),cache=new Map(),transitions=[],state={regime:'local',materializations:0,evictions:0};
 function put(k,v){if(cache.has(k))cache.delete(k);cache.set(k,v);while(cache.size>CAPS.cacheEntries){const first=cache.keys().next().value;cache.delete(first);state.evictions++;}return v;}
 function materialize(regime){regime=String(regime).toLowerCase();V.assert(ORDER.includes(regime),'regime');if(cache.has(regime)){const v=cache.get(regime);cache.delete(regime);cache.set(regime,v);return v;}let value;if(regime==='material'){value=Materials.materialize(source);}else if(regime==='microstructure'){const material=materialize('material');value=Micro.sample(material,{sampleIndex,maxFeatures:microFeatures,sizeNm:rveSizeNm});}else if(regime==='molecular'){const material=materialize('material'),micro=materialize('microstructure');value=Molecular.represent(material,micro,{sampleIndex,maxUnits:molecularUnits});}else{const material=materialize('material'),molecular=materialize('molecular');value=Atomic.represent(material,molecular,{sampleIndex,maxAtoms:atoms});}state.materializations++;return put(regime,value);}
 function transitionTo(regime){regime=String(regime).toLowerCase();V.assert(ORDER.includes(regime),'regime');const current=state.regime,currentIndex=current==='local'?-1:ORDER.indexOf(current),target=ORDER.indexOf(regime);V.assert(target===currentIndex||target===currentIndex+1,'forward transitions must be adjacent');if(target===currentIndex)return snapshot();const child=materialize(regime),parent=current==='local'?null:materialize(current),operation=regime==='material'?'PROJECT':regime==='microstructure'?'REFINE':'PROJECT',authority=regime==='molecular'?child.chemistryAuthority:regime==='atomic'?child.visualAuthority:child.representationAuthority||source.authority;transitions.push(witness(current,regime,operation,source,child,authority,{parentRepresentationId:parent?.representationId||parent?.materialId||null,chemistryAuthority:regime==='molecular'?child.chemistryAuthority:source.chemistryAuthority,resolution:regime==='material'?{kind:'MATERIAL_DESCRIPTOR',sourceBound:true}:regime==='microstructure'?{kind:'REPRESENTATIVE_VOLUME',value:child.resolutionNm,unit:'nm'}:regime==='molecular'?{kind:'REPRESENTATIVE_CHEMICAL_UNIT',exactSpatialArrangement:false}:regime==='atomic'?{kind:'REPRESENTATIVE_ATOMIC_STRUCTURE',coordinateAuthority:child.coordinateAuthority}:null,inherited:regime==='material'?['sourceEntityId','sourceKind','provenance']:['sourceEntityId','materialId','provenance'],newlyModeled:regime==='microstructure'?['representativeVolume','features']:regime==='molecular'?['representativeChemistry']:regime==='atomic'?['boundedAtomicArrangement','quantumBoundary']:['materialDescriptor']}));state.regime=regime;return snapshot();}
 function step(direction=-1){const d=Math.sign(Number(direction));if(!d)return snapshot();if(d<0){const i=state.regime==='local'?-1:ORDER.indexOf(state.regime);return i<ORDER.length-1?transitionTo(ORDER[i+1]):snapshot();}if(state.regime==='local')return snapshot();const i=ORDER.indexOf(state.regime);if(i===0)return exit();state.regime=ORDER[i-1];const child=materialize(state.regime),from=ORDER[i];transitions.push(witness(from,state.regime,'RECONCILE',source,child,child.representationAuthority||child.chemistryAuthority||source.authority,{newlyModeled:['reverseProjectionWitness']}));return snapshot();}
 function exit(){const from=state.regime;if(from!=='local')transitions.push(witness(from,'local','RECONCILE',source,null,source.authority,{inherited:['sourceEntityId','provenance'],newlyModeled:['reverseContextWitness']}));state.regime='local';return snapshot();}
 function evict(regime=null){if(regime==null){const n=cache.size;cache.clear();state.evictions+=n;return n;}const key=String(regime).toLowerCase(),removed=cache.delete(key);if(removed)state.evictions++;return removed?1:0;}
 function current(){return state.regime==='local'?source:materialize(state.regime);}
 function reconcile(){let pass=true,reason=null;for(const t of transitions)if(t.sourceEntityId!==source.sourceEntityId||!t.identityPreserved){pass=false;reason='SOURCE_IDENTITY_DRIFT';break;}return V.freezeDeep({contract:'ofu-v1-micro-reconcile-1',sessionId,sourceEntityId:source.sourceEntityId,status:pass?'PASS':'FAIL',reason,transitionCount:transitions.length,exactSourceReturn:true,authority:'DERIVED'});}
 function portableState(){return V.freezeDeep({contract:'ofu-v1-micro-session-portable-1',version:1,sessionId,sourceEntityId:source.sourceEntityId,sourceKind:source.kind,sourceDigest:V.digest('OFU-V1-MICRO-SOURCE',source),regime:state.regime,sampleIndex,caps:{microFeatures,molecularUnits,atoms,rveSizeNm},explicitMicroNodesPersisted:false,regeneration:'DETERMINISTIC'});}
 function snapshot(){return V.freezeDeep({version:VERSION,sessionId,order:ORDER,regime:state.regime,sourceEntityId:source.sourceEntityId,sourceKind:source.kind,current:state.regime==='local'?source:(cache.get(state.regime)||null),transitionCount:transitions.length,lastWitness:transitions.length?transitions[transitions.length-1]:null,cacheEntries:cache.size,cacheLimit:CAPS.cacheEntries,materializations:state.materializations,evictions:state.evictions});}
 return Object.freeze({VERSION,sessionId,source,ORDER,CAPS,materialize,transitionTo,step,exit,evict,current,reconcile,portableState,snapshot,transitions:()=>Object.freeze([...transitions])});}
O.v1MicroPipeline=Object.freeze({VERSION,ORDER,CAPS,createSession});
})(globalThis);
