(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,A=O.v1Astronomy;
if(!V||!A)throw new Error('v1 exploration address space requires v1 common and astronomy');
const VERSION='ofu-v1-universal-address-space-1';
const NAV_AUTHORITY='DERIVED',MODEL_AUTHORITY='MODEL_DERIVED_SIMULATION',CANONICAL_SOURCE='CANONICAL_PROVEN';
const GALAXY_WINDOW_SIDE=24,SECTOR_WINDOW_SIDE=8,SITE_WINDOW_SIDE=16,MAX_RESULTS=64,MAX_PROBES=65536;
const SYSTEM_FIELDS=Object.freeze(['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ']);
const PLANET_FIELDS=Object.freeze([...SYSTEM_FIELDS,'orbitSlot']);
const KIND_SCALE=Object.freeze({universe:'galaxy',galaxy_population:'galaxy',galaxy:'galaxy',galactic_region:'galactic_region',stellar_neighborhood:'stellar_neighborhood',system:'system',star:'orbit',planet:'orbit',moon:'orbit',approach:'approach',global_surface:'global_surface',regional_surface:'regional_surface',local_surface:'local_surface',human:'human',microscopic_handoff:'human'});
function assert(ok,message){V.assert(ok,'exploration address: '+message)}
function int(value,label,min=0,max=Number.MAX_SAFE_INTEGER){const n=Number(value);V.int(n,label,min,max);return n}
function bi(value,label='coordinate'){try{return BigInt(value)}catch{throw new Error('exploration address: '+label)}}
function text(value,label,max=256){return V.text(String(value),label,max)}
function idText(value){if(typeof value==='string')return value;if(value instanceof Uint8Array){if(O.p2?.hex)return O.p2.hex(value);return [...value].map(v=>v.toString(16).padStart(2,'0')).join('')}if(value===null||value===undefined)return null;return String(value)}
function copyKey(key,fields=Object.keys(key||{})){assert(key&&typeof key==='object','key required');return Object.freeze(Object.fromEntries(fields.filter(k=>Object.hasOwn(key,k)).map(k=>[k,bi(key[k],k)])))}
function serializeKey(key,fields=Object.keys(key||{})){return fields.filter(k=>Object.hasOwn(key,k)).map(k=>k+'='+String(bi(key[k],k))).join(';')}
function floorDiv(a,b){a=bi(a);b=bi(b);let q=a/b,r=a%b;if(r<0n){q--;r+=b}return q}
function volume(side){return side*side*side}
function local3(index,side){const z=Math.floor(index/(side*side)),rest=index-z*side*side,y=Math.floor(rest/side),x=rest-y*side;return{x,y,z}}
function window3(value,label='window'){const v=value||{};return Object.freeze({x:bi(v.x??0,label+'.x'),y:bi(v.y??0,label+'.y'),z:bi(v.z??0,label+'.z')})}
function lineage(parent){return Object.freeze(parent?Object.freeze([...(parent.lineage||[]),parent.entityId]):Object.freeze([]))}
function makeNode({kind,universeId,parent=null,identityParts=[],canonicalId=null,canonicalKey=null,sourceAuthority=MODEL_AUTHORITY,metadata=null,selectable=true,navigable=true,scale=null}){
 kind=text(kind,'kind',64);universeId=text(universeId,'universeId',128);const entityId=V.deriveId('exploration-'+kind,universeId,...identityParts.map(String));
 return Object.freeze({version:VERSION,kind,scale:scale||KIND_SCALE[kind]||'system',entityId,universeId,parentId:parent?.entityId||null,lineage:lineage(parent),canonicalId:idText(canonicalId),canonicalKey:canonicalKey?copyKey(canonicalKey):null,authority:NAV_AUTHORITY,sourceAuthority,selectable:!!selectable,navigable:!!navigable,metadata:metadata?Object.freeze({...metadata}):Object.freeze({})});
}
function universe(universeId){return makeNode({kind:'universe',universeId,identityParts:['root'],sourceAuthority:CANONICAL_SOURCE,selectable:false});}
function galaxyPopulation(universeNode,window={}){assert(universeNode?.kind==='universe','universe parent required');const w=window3(window,'galaxyWindow');return makeNode({kind:'galaxy_population',universeId:universeNode.universeId,parent:universeNode,identityParts:[w.x,w.y,w.z,GALAXY_WINDOW_SIDE],sourceAuthority:MODEL_AUTHORITY,metadata:{window:w,windowSide:GALAXY_WINDOW_SIDE,bounded:true,wholeUniverseEnumeration:false}})}
function galaxyKeyForWindow(window,index){const l=local3(index,GALAXY_WINDOW_SIDE);return Object.freeze({x:window.x*BigInt(GALAXY_WINDOW_SIDE)+BigInt(l.x),y:window.y*BigInt(GALAXY_WINDOW_SIDE)+BigInt(l.y),z:window.z*BigInt(GALAXY_WINDOW_SIDE)+BigInt(l.z)})}
function galaxyNode(population,key,entity){const canonicalKey=Object.freeze({galaxyX:key.x,galaxyY:key.y,galaxyZ:key.z}),canonicalId=idText(entity?.id),modelIdentity=canonicalId||V.deriveId('p3-galaxy-key',population.universeId,serializeKey(canonicalKey)),profile=A.galaxyProfile({galaxyIdentity:modelIdentity,environmentPpm:V.unitPpm(VERSION,modelIdentity,'environment')});return makeNode({kind:'galaxy',universeId:population.universeId,parent:population,identityParts:[serializeKey(canonicalKey)],canonicalId,canonicalKey,sourceAuthority:CANONICAL_SOURCE,metadata:{p3Status:'PRESENT',facts:entity?.facts||null,modelProfile:profile,discoveryWindow:population.metadata.window}})}
function discoverGalaxies({ctx,universeNode,window={x:0n,y:0n,z:0n},cursor=0,limit=16,maxProbes=4096}={}){
 assert(ctx&&O.p3Astronomy,'P3 context required');assert(universeNode?.kind==='universe','universe node required');limit=int(limit,'galaxy limit',1,MAX_RESULTS);maxProbes=int(maxProbes,'galaxy maxProbes',1,MAX_PROBES);const w=window3(window,'galaxyWindow'),pop=galaxyPopulation(universeNode,w),cap=volume(GALAXY_WINDOW_SIDE);cursor=int(cursor,'galaxy cursor',0,cap);const galaxies=[];let probes=0,index=cursor;
 for(;index<cap&&probes<maxProbes&&galaxies.length<limit;index++){const key=galaxyKeyForWindow(w,index),entity=O.p3Astronomy.resolveGalaxy(ctx,key);probes++;if(entity?.status==='PRESENT')galaxies.push(galaxyNode(pop,key,entity));}
 return Object.freeze({version:VERSION,kind:'GALAXY_DISCOVERY',population:pop,window:w,cursor,nextCursor:index<cap?index:null,spatialContinuation:Object.freeze({negativeX:Object.freeze({x:w.x-1n,y:w.y,z:w.z}),positiveX:Object.freeze({x:w.x+1n,y:w.y,z:w.z}),negativeY:Object.freeze({x:w.x,y:w.y-1n,z:w.z}),positiveY:Object.freeze({x:w.x,y:w.y+1n,z:w.z}),negativeZ:Object.freeze({x:w.x,y:w.y,z:w.z-1n}),positiveZ:Object.freeze({x:w.x,y:w.y,z:w.z+1n})}),probes,maxProbes,materialized:galaxies.length,maxMaterialized:limit,galaxies:Object.freeze(galaxies),bounded:true,wholeUniverseEnumeration:false,authority:NAV_AUTHORITY,sourceAuthority:CANONICAL_SOURCE});
}
function galaxyFromCanonical({universeNode,ctx,canonicalKey}){assert(universeNode?.kind==='universe','universe node required');const k={x:bi(canonicalKey.galaxyX),y:bi(canonicalKey.galaxyY),z:bi(canonicalKey.galaxyZ)},entity=O.p3Astronomy.resolveGalaxy(ctx,k);assert(entity?.status==='PRESENT','canonical galaxy absent');const w={x:floorDiv(k.x,BigInt(GALAXY_WINDOW_SIDE)),y:floorDiv(k.y,BigInt(GALAXY_WINDOW_SIDE)),z:floorDiv(k.z,BigInt(GALAXY_WINDOW_SIDE))};return galaxyNode(galaxyPopulation(universeNode,w),k,entity)}
function sectorKey(galaxy,sector){return Object.freeze({galaxyX:bi(galaxy.canonicalKey.galaxyX),galaxyY:bi(galaxy.canonicalKey.galaxyY),galaxyZ:bi(galaxy.canonicalKey.galaxyZ),sectorX:bi(sector.x),sectorY:bi(sector.y),sectorZ:bi(sector.z)})}
function regionNode(galaxy,key,sector){const regionIdentity=V.deriveId('galactic-region',galaxy.entityId,serializeKey(key,['sectorX','sectorY','sectorZ'])),gp=galaxy.metadata.modelProfile||A.galaxyProfile({galaxyIdentity:galaxy.canonicalId||galaxy.entityId}),radial=V.unitPpm(VERSION,regionIdentity,'radial'),height=V.unitPpm(VERSION,regionIdentity,'height'),profile=A.regionProfile({galaxy:gp,galacticRegionIdentity:regionIdentity,radialPpm:radial,heightPpm:height});return makeNode({kind:'galactic_region',universeId:galaxy.universeId,parent:galaxy,identityParts:[serializeKey(key,['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ'])],canonicalKey:key,sourceAuthority:MODEL_AUTHORITY,metadata:{p3SectorStatus:'PRESENT',sectorFacts:sector?.facts||null,regionProfile:profile,computationalSectorSource:true,physicalRegionClaim:false}})}
function discoverRegions({ctx,galaxy,window={x:0n,y:0n,z:0n},cursor=0,limit=16,maxProbes=512}={}){
 assert(ctx&&O.p3Astronomy,'P3 context required');assert(galaxy?.kind==='galaxy','galaxy node required');const w=window3(window,'sectorWindow');limit=int(limit,'region limit',1,MAX_RESULTS);maxProbes=int(maxProbes,'region maxProbes',1,MAX_PROBES);const cap=volume(SECTOR_WINDOW_SIDE);cursor=int(cursor,'region cursor',0,cap);const regions=[];let probes=0,index=cursor;
 for(;index<cap&&probes<maxProbes&&regions.length<limit;index++){const l=local3(index,SECTOR_WINDOW_SIDE),sector={x:w.x*BigInt(SECTOR_WINDOW_SIDE)+BigInt(l.x-Math.floor(SECTOR_WINDOW_SIDE/2)),y:w.y*BigInt(SECTOR_WINDOW_SIDE)+BigInt(l.y-Math.floor(SECTOR_WINDOW_SIDE/2)),z:w.z*BigInt(SECTOR_WINDOW_SIDE)+BigInt(l.z-Math.floor(SECTOR_WINDOW_SIDE/2))},key=sectorKey(galaxy,sector),entity=O.p3Astronomy.resolveSector(ctx,key);probes++;if(entity?.status==='PRESENT')regions.push(regionNode(galaxy,key,entity));}
 return Object.freeze({version:VERSION,kind:'GALACTIC_REGION_DISCOVERY',galaxyId:galaxy.entityId,window:w,cursor,nextCursor:index<cap?index:null,probes,maxProbes,regions:Object.freeze(regions),bounded:true,regionAuthority:MODEL_AUTHORITY,sectorSourceAuthority:CANONICAL_SOURCE});
}
function regionFromCanonical({ctx,galaxy,canonicalKey}){assert(ctx&&O.p3Astronomy,'P3 context required');assert(galaxy?.kind==='galaxy','galaxy node required');const key=sectorKey(galaxy,{x:bi(canonicalKey.sectorX),y:bi(canonicalKey.sectorY),z:bi(canonicalKey.sectorZ)}),entity=O.p3Astronomy.resolveSector(ctx,key);assert(entity?.status==='PRESENT','canonical sector absent');return regionNode(galaxy,key,entity)}
function neighborhood(region,siteWindow={x:0,y:0,z:0}){assert(region?.kind==='galactic_region','region node required');const w=window3(siteWindow,'siteWindow');for(const v of [w.x,w.y,w.z])assert(v>=0n&&v<BigInt(512/SITE_WINDOW_SIDE),'site window outside sector');return makeNode({kind:'stellar_neighborhood',universeId:region.universeId,parent:region,identityParts:[region.entityId,w.x,w.y,w.z,SITE_WINDOW_SIDE],canonicalKey:region.canonicalKey,sourceAuthority:MODEL_AUTHORITY,metadata:{siteWindow:w,siteWindowSide:SITE_WINDOW_SIDE,lateMaterialized:true,canonicalIndividualStarClaim:false}})}
function systemNode(neighborhoodNode,key,entity){const canonicalId=idText(entity?.id);return makeNode({kind:'system',universeId:neighborhoodNode.universeId,parent:neighborhoodNode,identityParts:[serializeKey(key,SYSTEM_FIELDS)],canonicalId,canonicalKey:key,sourceAuthority:CANONICAL_SOURCE,metadata:{p3Status:'PRESENT',facts:entity?.facts||null}})}
function systemFromCanonical({ctx,neighborhood:hood,canonicalKey}){assert(ctx&&O.p3Astronomy,'P3 context required');assert(hood?.kind==='stellar_neighborhood','stellar neighborhood required');const key=copyKey(canonicalKey,SYSTEM_FIELDS),entity=O.p3Astronomy.resolveSystem(ctx,key);assert(entity?.status==='PRESENT','canonical system absent');return systemNode(hood,key,entity)}
function discoverSystems({ctx,neighborhood:hood,cursor=0,limit=24,maxProbes=4096}={}){
 assert(ctx&&O.p3Astronomy,'P3 context required');assert(hood?.kind==='stellar_neighborhood','stellar neighborhood required');limit=int(limit,'system limit',1,MAX_RESULTS);maxProbes=int(maxProbes,'system maxProbes',1,MAX_PROBES);const cap=volume(SITE_WINDOW_SIDE);cursor=int(cursor,'system cursor',0,cap),w=hood.metadata.siteWindow,base=hood.canonicalKey,systems=[];let probes=0,index=cursor;
 for(;index<cap&&probes<maxProbes&&systems.length<limit;index++){const l=local3(index,SITE_WINDOW_SIDE),key=Object.freeze({galaxyX:bi(base.galaxyX),galaxyY:bi(base.galaxyY),galaxyZ:bi(base.galaxyZ),sectorX:bi(base.sectorX),sectorY:bi(base.sectorY),sectorZ:bi(base.sectorZ),siteX:w.x*BigInt(SITE_WINDOW_SIDE)+BigInt(l.x),siteY:w.y*BigInt(SITE_WINDOW_SIDE)+BigInt(l.y),siteZ:w.z*BigInt(SITE_WINDOW_SIDE)+BigInt(l.z)}),entity=O.p3Astronomy.resolveSystem(ctx,key);probes++;if(entity?.status==='PRESENT')systems.push(systemNode(hood,key,entity));}
 return Object.freeze({version:VERSION,kind:'STELLAR_SYSTEM_DISCOVERY',neighborhoodId:hood.entityId,cursor,nextCursor:index<cap?index:null,probes,maxProbes,systems:Object.freeze(systems),bounded:true,canonicalSource:true});
}
function shiftSystemKey(base,dx,dy,dz){const axis=(sector,site,delta)=>{let a=bi(sector)*512n+bi(site)+bi(delta),q=a/512n,r=a%512n;if(r<0n){q--;r+=512n}return[q,r]},[sectorX,siteX]=axis(base.sectorX,base.siteX,dx),[sectorY,siteY]=axis(base.sectorY,base.siteY,dy),[sectorZ,siteZ]=axis(base.sectorZ,base.siteZ,dz);return Object.freeze({galaxyX:bi(base.galaxyX),galaxyY:bi(base.galaxyY),galaxyZ:bi(base.galaxyZ),sectorX,sectorY,sectorZ,siteX,siteY,siteZ});}
function nearbyOffsets(radius){radius=int(radius,'neighborhood radius',1,12);const out=[];for(let z=-radius;z<=radius;z++)for(let y=-radius;y<=radius;y++)for(let x=-radius;x<=radius;x++)out.push({x,y,z,d2:x*x+y*y+z*z});out.sort((a,b)=>a.d2-b.d2||a.z-b.z||a.y-b.y||a.x-b.x);return out}
function neighborhoodAroundSystem(system,{radiusSites=8}){assert(system?.kind==='system','system node required');const parent=system.parentId?null:null;return makeNode({kind:'stellar_neighborhood',universeId:system.universeId,parent:null,identityParts:['around',serializeKey(system.canonicalKey,SYSTEM_FIELDS),radiusSites],canonicalKey:system.canonicalKey,sourceAuthority:MODEL_AUTHORITY,metadata:{centerSystemId:system.entityId,radiusSites:int(radiusSites,'radiusSites',1,12),queryNeighborhood:true,detachedParentRegionId:system.parentId}})}
function discoverNearbySystems({ctx,system,cursor=0,limit=24,maxProbes=512,radiusSites=8}={}){assert(system?.kind==='system','system node required');limit=int(limit,'nearby limit',1,MAX_RESULTS);maxProbes=int(maxProbes,'nearby maxProbes',1,MAX_PROBES);const offsets=nearbyOffsets(radiusSites);cursor=int(cursor,'nearby cursor',0,offsets.length);const hood=neighborhoodAroundSystem(system,{radiusSites}),systems=[];let probes=0,index=cursor;for(;index<offsets.length&&probes<maxProbes&&systems.length<limit;index++){const o=offsets[index],key=shiftSystemKey(system.canonicalKey,o.x,o.y,o.z),entity=O.p3Astronomy.resolveSystem(ctx,key);probes++;if(entity?.status==='PRESENT')systems.push(systemNode(hood,key,entity));}return Object.freeze({version:VERSION,kind:'STELLAR_NEIGHBORHOOD_QUERY',neighborhood:hood,cursor,nextCursor:index<offsets.length?index:null,probes,maxProbes,systems:Object.freeze(systems),bounded:true,radiusSites});}
function starNode(system,key,entity,index){return makeNode({kind:'star',universeId:system.universeId,parent:system,identityParts:[system.entityId,'star',index],canonicalId:idText(entity?.id),canonicalKey:key,sourceAuthority:CANONICAL_SOURCE,metadata:{componentIndex:index,facts:entity?.facts||null}})}
function planetNode(system,key,entity,index){return makeNode({kind:'planet',universeId:system.universeId,parent:system,identityParts:[system.entityId,'planet',index],canonicalId:idText(entity?.id),canonicalKey:key,sourceAuthority:CANONICAL_SOURCE,metadata:{orbitSlot:index,facts:entity?.facts||null}})}
function moonNode(planet,key,entity,index){return makeNode({kind:'moon',universeId:planet.universeId,parent:planet,identityParts:[planet.entityId,'moon',index],canonicalId:idText(entity?.id),canonicalKey:key,sourceAuthority:CANONICAL_SOURCE,metadata:{satelliteSlot:index,facts:entity?.facts||null}})}
function systemChildren({ctx,system,includeMoons=true}={}){assert(ctx&&O.p3Astronomy,'P3 context required');assert(system?.kind==='system','system node required');const s=O.p3Astronomy.resolveSystem(ctx,system.canonicalKey);assert(s?.status==='PRESENT','system no longer present at canonical baseline');const stars=[],planets=[],moons=[];const starCount=Number(s.facts.stellarComponentCount||0n),planetCount=Number(s.facts.planetCount||0n);assert(starCount<=4&&planetCount<=10,'P3 child bounds');for(let i=0;i<starCount;i++){const key=Object.freeze({...copyKey(system.canonicalKey,SYSTEM_FIELDS),componentIndex:BigInt(i)}),entity=O.p3Astronomy.resolveStar(ctx,key);if(entity?.status==='PRESENT')stars.push(starNode(system,key,entity,i))}for(let i=0;i<planetCount;i++){const key=Object.freeze({...copyKey(system.canonicalKey,SYSTEM_FIELDS),orbitSlot:BigInt(i)}),entity=O.p3Astronomy.resolvePlanet(ctx,key);if(entity?.status!=='PRESENT')continue;const p=planetNode(system,key,entity,i);planets.push(p);if(includeMoons){const count=Number(entity.facts.moonCount||0n);assert(count<=8,'P3 moon bound');for(let j=0;j<count;j++){const mk=Object.freeze({...key,satelliteSlot:BigInt(j)}),m=O.p3Astronomy.resolveMoon(ctx,mk);if(m?.status==='PRESENT')moons.push(moonNode(p,mk,m,j))}}}return Object.freeze({version:VERSION,systemId:system.entityId,stars:Object.freeze(stars),planets:Object.freeze(planets),moons:Object.freeze(moons),selectableStars:true,selectableOrbitalBodies:true,decorativeIncluded:false,canonicalSource:true});}
function approach(body){assert(['planet','moon'].includes(body?.kind),'planet or moon required');return makeNode({kind:'approach',universeId:body.universeId,parent:body,identityParts:[body.entityId,'approach'],canonicalId:body.canonicalId,canonicalKey:body.canonicalKey,sourceAuthority:body.sourceAuthority,metadata:{targetBodyId:body.entityId,targetCanonicalId:body.canonicalId,representationChangeOnly:true,identityPreserved:true}})}
const SURFACE_LEVELS=Object.freeze([{kind:'global_surface',cell:30000000},{kind:'regional_surface',cell:5000000},{kind:'local_surface',cell:50000},{kind:'human',cell:10}]);
function normalizeLongitude(value){let v=bi(value,'longitudeMicroDeg'),full=360000000n;v=((v+180000000n)%full+full)%full-180000000n;return v}
function surfaceHierarchy(body,{latitudeMicroDeg=0n,longitudeMicroDeg=0n}={}){assert(['planet','moon'].includes(body?.kind),'surface body required');const lat=bi(latitudeMicroDeg,'latitudeMicroDeg'),lon=normalizeLongitude(longitudeMicroDeg);assert(lat>=-90000000n&&lat<=90000000n,'latitude out of range');let parent=approach(body);const out=[];for(const spec of SURFACE_LEVELS){const size=BigInt(spec.cell),latCell=floorDiv(lat+90000000n,size),lonCell=floorDiv(lon+180000000n,size),n=makeNode({kind:spec.kind,universeId:body.universeId,parent,identityParts:[body.entityId,spec.kind,latCell,lonCell,spec.cell],canonicalId:body.canonicalId,canonicalKey:body.canonicalKey,sourceAuthority:MODEL_AUTHORITY,metadata:{targetBodyId:body.entityId,latitudeMicroDeg:lat,longitudeMicroDeg:lon,cellLatitudeIndex:latCell,cellLongitudeIndex:lonCell,cellSizeMicroDeg:spec.cell,referenceFrame:'BODY_FIXED_NAVIGATION_ADDRESS',canonicalGeodesyClaim:false,stableSurfaceAddress:true}});out.push(n);parent=n}return Object.freeze({bodyId:body.entityId,latitudeMicroDeg:lat,longitudeMicroDeg:lon,approach:approach(body),globalSurface:out[0],regionalSurface:out[1],localSurface:out[2],human:out[3],nodes:Object.freeze(out)});}
function microscopicHandoff(source,{sourceObjectId='local-context',sourceKind='material',materialIdentity=null}={}){assert(source&&['human','local_surface','regional_surface'].includes(source.kind),'local/human source required');sourceObjectId=text(sourceObjectId,'sourceObjectId',192);sourceKind=text(sourceKind,'sourceKind',64);const stableSourceIdentity=V.deriveId('microscopic-source',source.entityId,sourceObjectId,sourceKind,materialIdentity===null?'unspecified':String(materialIdentity)),requestId=V.deriveId('microscopic-target-request',stableSourceIdentity,'v1');return makeNode({kind:'microscopic_handoff',universeId:source.universeId,parent:source,identityParts:[stableSourceIdentity,requestId],sourceAuthority:MODEL_AUTHORITY,metadata:{requestId,stableSourceIdentity,sourceObjectId,sourceKind,materialIdentity:materialIdentity===null?null:String(materialIdentity),requestedRegime:'MICROSCOPIC',scienceOwnedBy:'LANE_5',microscopicScienceIncluded:false}})}
function cacheKey(kind,input){return V.digest('OFU-V1-EXPLORATION-CACHE',VERSION,String(kind),typeof input==='string'?input:serializeKey(input||{}));}
O.v1ExplorationAddressSpace=Object.freeze({VERSION,NAV_AUTHORITY,MODEL_AUTHORITY,CANONICAL_SOURCE,GALAXY_WINDOW_SIDE,SECTOR_WINDOW_SIDE,SITE_WINDOW_SIDE,MAX_RESULTS,MAX_PROBES,SYSTEM_FIELDS,PLANET_FIELDS,KIND_SCALE,copyKey,serializeKey,universe,galaxyPopulation,discoverGalaxies,galaxyFromCanonical,discoverRegions,regionFromCanonical,neighborhood,systemFromCanonical,discoverSystems,shiftSystemKey,neighborhoodAroundSystem,discoverNearbySystems,systemChildren,approach,surfaceHierarchy,microscopicHandoff,cacheKey});
})(typeof globalThis!=='undefined'?globalThis:this);
