(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,AS=O.v1ExplorationAddressSpace,T=O.v1UniversalTraversal,WS=O.v1ExplorationWorkingSet,I=O.v1ExplorationInteraction;
if(!V||!AS||!T||!WS||!I)throw new Error('v1 exploration product adapter prerequisites missing');
const VERSION='ofu-v1-universal-exploration-product-adapter-1',MAX_ANCHOR_PROBES=16384;
const state={initialized:false,ctx:null,universe:null,traversal:null,workingSet:null,origin:null,currentGraph:null,macroIntegrated:false,macroIntents:0,discoveries:0,anchorProbes:0,lastError:null,lastJourney:null,keyboardBound:false};
function assert(ok,message){V.assert(ok,'exploration product adapter: '+message)}
const runtime=()=>O.waveIVScaleRuntime,preview=()=>root.__OFU_PLANET_PREVIEW__;
function selectedKey(){return runtime()?.snapshot?.().selectedCanonicalTarget?.canonicalKey||preview()?.chosen?.key||null}
function universeIdFor(key){try{return O.pxProduct?.captured?.(key)?.selection?.target?.universeId||null}catch{return null}}
function copyPlanetKey(key){return Object.freeze(Object.fromEntries(AS.PLANET_FIELDS.map(k=>[k,BigInt(key[k])])))}
function sectorWindowFor(value){const v=BigInt(value),side=BigInt(AS.SECTOR_WINDOW_SIDE),half=BigInt(Math.floor(AS.SECTOR_WINDOW_SIDE/2));let q=(v+half)/side,r=(v+half)%side;if(r<0n){q--;r+=side}return q}
function siteWindowFor(value){return BigInt(value)/BigInt(AS.SITE_WINDOW_SIDE)}
function selectPlanetKey(key,{announce=false}={}){const k=copyPlanetKey(key);if(O.v08SelectionBridge?.selectPlanet)return O.v08SelectionBridge.selectPlanet(k,{announce});return runtime()?.setSelection?.(k,{source:'v1-universal-exploration-anchor'})}
function firstPlanetKey(systemKey){const s=O.p3Astronomy.resolveSystem(state.ctx,systemKey);if(s?.status!=='PRESENT'||Number(s.facts.planetCount||0n)<1)return null;for(let i=0n;i<s.facts.planetCount;i++){const key=Object.freeze({...AS.copyKey(systemKey,AS.SYSTEM_FIELDS),orbitSlot:i}),p=O.p3Astronomy.resolvePlanet(state.ctx,key);if(p?.status==='PRESENT')return key}return null}
function graphForKey(key){assert(state.ctx&&state.universe,'adapter initialized');const full=copyPlanetKey(key),galaxy=AS.galaxyFromCanonical({universeNode:state.universe,ctx:state.ctx,canonicalKey:full}),region=AS.regionFromCanonical({ctx:state.ctx,galaxy,canonicalKey:full}),hood=AS.neighborhood(region,{x:siteWindowFor(full.siteX),y:siteWindowFor(full.siteY),z:siteWindowFor(full.siteZ)}),system=AS.systemFromCanonical({ctx:state.ctx,neighborhood:hood,canonicalKey:full}),children=AS.systemChildren({ctx:state.ctx,system}),planet=children.planets.find(p=>BigInt(p.canonicalKey.orbitSlot)===BigInt(full.orbitSlot))||children.planets[0]||null;return Object.freeze({galaxy,region,neighborhood:hood,system,children,planet})}
function registerGraph(graph){const tr=state.traversal;for(const n of [graph.galaxy,graph.region,graph.neighborhood,graph.system,...graph.children.stars,...graph.children.planets,...graph.children.moons])tr.remember(n,n===graph.planet?'IMMEDIATE':'WARM');try{tr.refine(graph.galaxy,[graph.region]);tr.refine(graph.region,[graph.neighborhood]);tr.refine(graph.neighborhood,[graph.system]);const systemChildren=[...graph.children.stars,...graph.children.planets].filter(n=>n.parentId===graph.system.entityId);if(systemChildren.length)tr.refine(graph.system,systemChildren)}catch(e){state.lastError=String(e?.message||e)}return graph}
function init({ctx=preview()?.ctx,key=selectedKey(),universeId=null}={}){if(state.initialized)return snapshot();assert(ctx&&key,'canonical product context required');universeId=universeId||universeIdFor(key)||V.deriveId('universe-navigation-root','OFU',String(preview()?.provider?.planetId||'default'));state.ctx=ctx;state.universe=AS.universe(String(universeId));state.workingSet=WS.create({caps:{COLD:96,WARM:48,HOT:24,IMMEDIATE:8},maxRequests:8});const graph=graphForKey(key),initial=graph.planet||graph.system;state.traversal=T.create({initialNode:initial,runtime:runtime(),workingSet:state.workingSet,maxHistory:96});state.currentGraph=registerGraph(graph);state.origin=Object.freeze({nodeId:initial.entityId,planetKey:copyPlanetKey(key),planetCanonicalId:graph.planet?.canonicalId||null,scale:runtime()?.snapshot?.().semanticScale||initial.scale,galaxyId:graph.galaxy.entityId,systemId:graph.system.entityId});state.initialized=true;bindKeyboard();attachMacroIntegration();return snapshot()}
function ensure(){if(!state.initialized)init();return state.traversal}
function rememberDiscovery(result){state.discoveries++;const nodes=result.galaxies||result.regions||result.systems||[];for(const n of nodes)state.traversal.remember(n,'WARM');return result}
function discoverGalaxies(options={}){ensure();const window=options.window||state.currentGraph?.galaxy?.metadata?.discoveryWindow||{x:0n,y:0n,z:0n},cacheKey='galaxies:'+String(window.x)+','+String(window.y)+','+String(window.z)+':'+String(options.cursor||0)+':'+String(options.limit||16),cached=state.workingSet.get(cacheKey,{promote:'HOT'});if(cached)return cached;const result=rememberDiscovery(AS.discoverGalaxies({ctx:state.ctx,universeNode:state.universe,window,cursor:options.cursor??0,limit:options.limit??16,maxProbes:options.maxProbes??4096}));state.workingSet.put(cacheKey,result,{lifecycle:'WARM',identity:result.population.entityId});return result}
function discoverRegions(galaxy,options={}){ensure();const result=rememberDiscovery(AS.discoverRegions({ctx:state.ctx,galaxy,window:options.window||{x:0n,y:0n,z:0n},cursor:options.cursor??0,limit:options.limit??16,maxProbes:options.maxProbes??512}));return result}
function discoverSystems(hood,options={}){ensure();return rememberDiscovery(AS.discoverSystems({ctx:state.ctx,neighborhood:hood,cursor:options.cursor??0,limit:options.limit??24,maxProbes:options.maxProbes??4096}))}
function nearbySystems(system,options={}){ensure();return rememberDiscovery(AS.discoverNearbySystems({ctx:state.ctx,system,cursor:options.cursor??0,limit:options.limit??24,maxProbes:options.maxProbes??512,radiusSites:options.radiusSites??8}))}
function sectorOffsets(){const out=[];for(let z=-2;z<=2;z++)for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++)out.push({x,y,z,d2:x*x+y*y+z*z});out.sort((a,b)=>a.d2-b.d2||a.z-b.z||a.y-b.y||a.x-b.x);return out}
function findPlanetAnchor(galaxy,{maxProbes=MAX_ANCHOR_PROBES}={}){ensure();maxProbes=Number(maxProbes);assert(Number.isSafeInteger(maxProbes)&&maxProbes>=64&&maxProbes<=MAX_ANCHOR_PROBES,'anchor probe bound');const g=galaxy.canonicalKey;let probes=0;for(const so of sectorOffsets()){for(let i=0;i<512&&probes<maxProbes;i++){const key=Object.freeze({galaxyX:BigInt(g.galaxyX),galaxyY:BigInt(g.galaxyY),galaxyZ:BigInt(g.galaxyZ),sectorX:BigInt(so.x),sectorY:BigInt(so.y),sectorZ:BigInt(so.z),siteX:BigInt(i),siteY:0n,siteZ:0n}),system=O.p3Astronomy.resolveSystem(state.ctx,key);probes++;if(system?.status!=='PRESENT'||Number(system.facts.planetCount||0n)<1)continue;const planet=firstPlanetKey(key);if(planet){state.anchorProbes+=probes;return Object.freeze({planetKey:planet,systemKey:key,probes})}}if(probes>=maxProbes)break}state.anchorProbes+=probes;return Object.freeze({planetKey:null,systemKey:null,probes})}
function chooseGalaxy(galaxy,{enter=false,source='v1-direct-galaxy'}={}){ensure();assert(galaxy?.kind==='galaxy','galaxy node required');const anchor=findPlanetAnchor(galaxy);assert(anchor.planetKey,'no bounded planet-bearing system anchor found in selected galaxy');selectPlanetKey(anchor.planetKey,{announce:false});state.traversal.retarget(galaxy,{source,driveCamera:false});runtime()?.requestStage?.(enter?'galactic_region':'galaxy',{source,transition:true,driveCamera:false});const graph=registerGraph(graphForKey(anchor.planetKey));state.currentGraph=graph;if(enter)state.traversal.travel(graph.region,{source:source+'-enter',driveCamera:false});return Object.freeze({galaxy,anchor,graph,snapshot:snapshot()})}
function enterGalaxy(galaxy,{source='v1-enter-galaxy'}={}){const r=chooseGalaxy(galaxy,{enter:true,source});return r.graph.region}
function enterNeighborhood(region,{siteWindow=null,source='v1-enter-neighborhood'}={}){ensure();assert(region?.kind==='galactic_region','region node required');if(!siteWindow){const key=selectedKey();siteWindow=key?{x:siteWindowFor(key.siteX),y:siteWindowFor(key.siteY),z:siteWindowFor(key.siteZ)}:{x:0n,y:0n,z:0n}}const hood=AS.neighborhood(region,siteWindow);state.traversal.remember(hood,'HOT');state.traversal.travel(hood,{source,driveCamera:false});runtime()?.requestStage?.('stellar_neighborhood',{source,transition:true,driveCamera:false});return hood}
function chooseSystem(system,{source='v1-direct-system'}={}){ensure();assert(system?.kind==='system','system node required');const key=firstPlanetKey(system.canonicalKey);if(key)selectPlanetKey(key,{announce:false});const current=state.traversal.snapshot().selectedNode,mode=T.related(current,system)?'TRAVEL':'RETARGET';state.traversal[mode==='RETARGET'?'retarget':'travel'](system,{source,driveCamera:false});runtime()?.requestStage?.('system',{source,transition:true,driveCamera:false});const graph=key?registerGraph(graphForKey(key)):null;if(graph)state.currentGraph=graph;return Object.freeze({system,planetAnchor:key,graph})}
function chooseBody(body,{source='v1-direct-body'}={}){ensure();assert(['planet','moon'].includes(body?.kind),'planet/moon node required');if(body.canonicalKey?.orbitSlot!==undefined)selectPlanetKey(body.canonicalKey,{announce:false});const current=state.traversal.snapshot().selectedNode,method=T.related(current,body)?'travel':'retarget';state.traversal[method](body,{source,driveCamera:false});runtime()?.requestStage?.('orbit',{source,transition:true,driveCamera:true});return body}
function approach(body,{source='v1-approach'}={}){chooseBody(body,{source:source+'-target'});const node=AS.approach(body);state.traversal.remember(node,'IMMEDIATE');state.traversal.refine(body,[node]);state.traversal.travel(node,{source,driveCamera:true});return node}
function surface(body,{latitudeMicroDeg=0n,longitudeMicroDeg=0n,target='human',source='v1-surface'}={}){ensure();assert(['planet','moon'].includes(body?.kind),'surface body required');const chain=AS.surfaceHierarchy(body,{latitudeMicroDeg,longitudeMicroDeg}),order=[chain.globalSurface,chain.regionalSurface,chain.localSurface,chain.human],targetIndex=order.findIndex(n=>n.kind===target);assert(targetIndex>=0,'surface target kind');let parent=AS.approach(body);state.traversal.remember(parent,'HOT');for(let i=0;i<=targetIndex;i++){const n=order[i];state.traversal.remember(n,i===targetIndex?'IMMEDIATE':'HOT');state.traversal.refine(parent,[n]);const current=state.traversal.snapshot().selectedNode;if(current?.entityId!==parent.entityId&&i===0){const method=T.related(current,parent)?'travel':'retarget';state.traversal[method](parent,{source:source+'-approach',driveCamera:true})}state.traversal.travel(n,{source:source+'-'+n.kind,driveCamera:true});parent=n}return Object.freeze({...chain,selected:order[targetIndex]})}
function humanAnchor(body,location={}){return surface(body,{...location,target:'human',source:location.source||'v1-human-anchor'}).human}
function microscopicHandoff(sourceNode,request={}){ensure();const node=AS.microscopicHandoff(sourceNode,request);state.traversal.remember(node,'IMMEDIATE');state.traversal.refine(sourceNode,[node]);state.traversal.travel(node,{source:'v1-microscopic-handoff',driveCamera:false});return node}
function back(options={}){ensure();return state.traversal.back(options)}
function returnToOrigin({source='v1-return-origin'}={}){ensure();let guard=0;while(state.traversal.snapshot().selectedNode?.entityId!==state.origin.nodeId&&state.traversal.snapshot().historyDepth&&guard++<96)state.traversal.back({source});selectPlanetKey(state.origin.planetKey,{announce:false});runtime()?.requestStage?.(state.origin.scale,{source,transition:true,driveCamera:true});try{state.currentGraph=registerGraph(graphForKey(state.origin.planetKey))}catch(e){state.lastError=String(e?.message||e)}const restored=state.traversal.snapshot().selectedNode?.entityId===state.origin.nodeId;return Object.freeze({restored,origin:state.origin,selectedNodeId:state.traversal.snapshot().selectedNode?.entityId||null,guard})}
function nodeForMacroIntent(intent){if(!intent||!intent.canonicalKey)return null;try{if(intent.type==='FOCUS_GALAXY')return AS.galaxyFromCanonical({universeNode:state.universe,ctx:state.ctx,canonicalKey:intent.canonicalKey});const key={...selectedKey(),...intent.canonicalKey};const graph=registerGraph(graphForKey(key));if(intent.type==='FOCUS_REGION')return graph.region;if(intent.type==='FOCUS_SYSTEM')return graph.system;if(intent.type==='VISIT_PLANET')return graph.children.planets.find(p=>BigInt(p.canonicalKey.orbitSlot)===BigInt(intent.canonicalKey.orbitSlot))||graph.planet;return null}catch(e){state.lastError=String(e?.message||e);return null}}
function navigateMacro(intent){ensure();state.macroIntents++;const node=nodeForMacroIntent(intent);if(!node)return O.waveIVVerticalSlice?.navigateMacro?.(intent)||false;try{if(node.kind==='galaxy'){chooseGalaxy(node,{enter:true,source:'v1-macro-galaxy'});return true}if(node.kind==='galactic_region'){const current=state.traversal.snapshot().selectedNode;state.traversal[T.related(current,node)?'travel':'retarget'](node,{source:'v1-macro-region',driveCamera:false});runtime()?.requestStage?.('stellar_neighborhood',{source:'v1-macro-region',transition:true,driveCamera:false});return true}if(node.kind==='system'){chooseSystem(node,{source:'v1-macro-system'});return true}if(node.kind==='planet'){chooseBody(node,{source:'v1-macro-planet'});return true}}catch(e){state.lastError=String(e?.message||e)}return O.waveIVVerticalSlice?.navigateMacro?.(intent)||false}
function attachMacroIntegration(){if(typeof document==='undefined'||state.macroIntegrated)return state.macroIntegrated;const canvas=document.getElementById('wave-iv-macro-view'),C=O.waveIVMacroCanvas,V4=O.waveIVVerticalSlice;if(!canvas||!C||!V4)return false;C.attach(canvas,{selectionAuthority:O.v08SelectionBridge,onNavigate:navigateMacro,onScaleGesture:V4.macroScaleGesture});state.macroIntegrated=true;return true}
function bindKeyboard(){if(typeof document==='undefined'||state.keyboardBound)return;state.keyboardBound=true;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.traversal?.snapshot().transition){state.traversal.cancelTransition('USER_ESCAPE');e.preventDefault();return}if(e.altKey&&e.key==='ArrowLeft'){state.traversal?.back({source:'keyboard-alt-left'});e.preventDefault()}},true)}
function syncFromRuntime(){ensure();const key=selectedKey();if(!key)return snapshot();try{const graph=registerGraph(graphForKey(key));state.currentGraph=graph;const scale=runtime()?.snapshot?.().semanticScale||'orbit',node=scale==='galaxy'?graph.galaxy:scale==='galactic_region'?graph.region:scale==='stellar_neighborhood'?graph.neighborhood:scale==='system'?graph.system:graph.planet||graph.system;const current=state.traversal.snapshot().selectedNode;if(node&&current?.entityId!==node.entityId)state.traversal[T.related(current,node)?'travel':'retarget'](node,{source:'runtime-sync',driveCamera:false});return snapshot()}catch(e){state.lastError=String(e?.message||e);return snapshot()}}
function findDifferentGalaxy({maxWindows=8,limit=16}={}){ensure();const originGalaxy=state.origin.galaxyId;try{const key=selectedKey(),scene=O.waveIVMacroProvider?.getScene?.({scale:'GALAXY',ctx:state.ctx,canonicalKey:key,selectedOrbitSlot:key?.orbitSlot??0n});for(const object of scene?.objects||[]){if(object.kind!=='GALAXY'||!object.canonicalKey)continue;const g=AS.galaxyFromCanonical({universeNode:state.universe,ctx:state.ctx,canonicalKey:object.canonicalKey});state.traversal.remember(g,'WARM');if(g.entityId!==originGalaxy)return Object.freeze({galaxy:g,page:Object.freeze({source:'WAVE_IV_MACRO_PROVIDER',objects:scene.objects.length,bounded:true,wholeUniverseEnumeration:false})})}}catch(e){state.lastError=String(e?.message||e)}for(let wx=0;wx<maxWindows;wx++){let cursor=0;do{const r=discoverGalaxies({window:{x:BigInt(wx),y:0n,z:0n},cursor,limit,maxProbes:4096});const g=r.galaxies.find(x=>x.entityId!==originGalaxy);if(g)return Object.freeze({galaxy:g,page:r});cursor=r.nextCursor??0}while(cursor&&cursor<AS.GALAXY_WINDOW_SIDE**3)}return null}
function journey({latitudeMicroDeg=12345678n,longitudeMicroDeg=23456789n}={}){ensure();const start=Object.freeze({nodeId:state.traversal.snapshot().selectedNode.entityId,planetKey:state.origin.planetKey,galaxyId:state.origin.galaxyId,systemId:state.origin.systemId});const found=findDifferentGalaxy({maxWindows:8,limit:16});assert(found?.galaxy,'different provider-backed galaxy not found in bounded windows');const chosen=chooseGalaxy(found.galaxy,{enter:true,source:'v1-journey-galaxy'}),region=chosen.graph.region,hood=enterNeighborhood(region,{siteWindow:{x:siteWindowFor(chosen.anchor.systemKey.siteX),y:siteWindowFor(chosen.anchor.systemKey.siteY),z:siteWindowFor(chosen.anchor.systemKey.siteZ)},source:'v1-journey-neighborhood'}),systems=discoverSystems(hood,{limit:24,maxProbes:4096});let system=systems.systems.find(s=>Number(s.metadata.facts?.planetCount||0n)>0)||chosen.graph.system;if(system.entityId!==chosen.graph.system.entityId)chooseSystem(system,{source:'v1-journey-system'});else chooseSystem(chosen.graph.system,{source:'v1-journey-system'});const children=AS.systemChildren({ctx:state.ctx,system:state.currentGraph.system}),planet=children.planets[0];assert(planet,'journey planet required');chooseBody(planet,{source:'v1-journey-planet'});approach(planet,{source:'v1-journey-approach'});const surf=surface(planet,{latitudeMicroDeg,longitudeMicroDeg,target:'human',source:'v1-journey-surface'}),micro=microscopicHandoff(surf.human,{sourceObjectId:'journey-local-material',sourceKind:'material'});const beforeReturn=state.traversal.snapshot(),returned=returnToOrigin({source:'v1-journey-return'}),result=Object.freeze({status:returned.restored?'PASS':'FAIL',start,differentGalaxyId:found.galaxy.entityId,selectedSystemId:state.currentGraph.system.entityId,selectedPlanetId:planet.entityId,humanAnchorId:surf.human.entityId,microRequestId:micro.metadata.requestId,beforeReturnNodeId:beforeReturn.selectedNode.entityId,returned,originIdentityRecovered:returned.restored&&returned.selectedNodeId===start.nodeId,providerBacked:true,hardCodedFixture:false});state.lastJourney=result;return result}
function snapshot(){return Object.freeze({version:VERSION,initialized:state.initialized,origin:state.origin,currentGraph:state.currentGraph?Object.freeze({galaxyId:state.currentGraph.galaxy.entityId,regionId:state.currentGraph.region.entityId,neighborhoodId:state.currentGraph.neighborhood.entityId,systemId:state.currentGraph.system.entityId,planetId:state.currentGraph.planet?.entityId||null}):null,macroIntegrated:state.macroIntegrated,macroIntents:state.macroIntents,discoveries:state.discoveries,anchorProbes:state.anchorProbes,lastError:state.lastError,lastJourney:state.lastJourney,traversal:state.traversal?.snapshot?.()||null});}
O.v1UniversalExploration=Object.freeze({VERSION,MAX_ANCHOR_PROBES,state,init,snapshot,syncFromRuntime,discoverGalaxies,discoverRegions,discoverSystems,nearbySystems,findPlanetAnchor,findDifferentGalaxy,chooseGalaxy,enterGalaxy,enterNeighborhood,chooseSystem,chooseBody,approach,surface,humanAnchor,microscopicHandoff,back,returnToOrigin,navigateMacro,attachMacroIntegration,journey});
if(typeof document!=='undefined'){const boot=()=>{try{if(!state.initialized&&preview()?.ctx&&selectedKey())init();if(state.initialized&&!state.macroIntegrated)attachMacroIntegration()}catch(e){state.lastError=String(e?.message||e);root.requestAnimationFrame?.(boot)}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()}
})(typeof globalThis!=='undefined'?globalThis:this);
