(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,M=O.v1Materials;if(!V||!M)throw new Error('v1 materials required');
const VERSION='ofu-v1-atomic-representative-1',MAX_ATOMS=256;
const GEOMETRY=Object.freeze({H2O:Object.freeze({elements:Object.freeze(['O','H','H']),positions:Object.freeze([[0,0,0],[0.9572,0,0],[-0.239,0.927,0]])}),CO2:Object.freeze({elements:Object.freeze(['O','C','O']),positions:Object.freeze([[-1.16,0,0],[0,0,0],[1.16,0,0]])}),N2:Object.freeze({elements:Object.freeze(['N','N']),positions:Object.freeze([[-0.55,0,0],[0.55,0,0]])}),O2:Object.freeze({elements:Object.freeze(['O','O']),positions:Object.freeze([[-0.60,0,0],[0.60,0,0]])}),CH4:Object.freeze({elements:Object.freeze(['C','H','H','H','H']),positions:Object.freeze([[0,0,0],[.63,.63,.63],[-.63,-.63,.63],[-.63,.63,-.63],[.63,-.63,-.63]])})});
function expandedElements(unit){const g=unit.formula&&GEOMETRY[unit.formula];if(g)return[...g.elements];const out=[];if(!unit.elementCounts)return out;for(const k of Object.keys(unit.elementCounts).sort())for(let i=0;i<unit.elementCounts[k];i++)out.push(k);return out;}
function representativePosition(repId,unit,atomIndex,unitIndex){const g=unit.formula&&GEOMETRY[unit.formula];if(g&&atomIndex<g.positions.length){const p=g.positions[atomIndex];return[p[0]+unitIndex*3,p[1],p[2]];}return[(V.signedPpm(VERSION,repId,'x',unitIndex,atomIndex)/100000)+(unitIndex%8)*2,(V.signedPpm(VERSION,repId,'y',unitIndex,atomIndex)/100000)+Math.floor(unitIndex/8)*2,V.signedPpm(VERSION,repId,'z',unitIndex,atomIndex)/100000];}
function represent(material,molecular,{maxAtoms=128,sampleIndex=0}={}){V.assert(material?.contract==='ofu-v1-material-1','material');V.assert(molecular?.contract==='ofu-v1-molecular-representation-1'&&molecular.materialId===material.materialId,'molecular ancestry');V.int(maxAtoms,'maxAtoms',1,MAX_ATOMS);V.int(sampleIndex,'sampleIndex',0,1000000);const representationId=V.deriveId('atomic-representation',molecular.representationId,sampleIndex),atoms=[];let coordinateAuthority='MODEL_DERIVED_REPRESENTATIVE_COORDINATE',visualAuthority='MODEL_DERIVED_SIMULATION';if(Array.isArray(material.sourceAtomicStructure)&&material.sourceAtomicStructure.length){coordinateAuthority='SOURCE_BACKED_ATOMIC_COORDINATE';visualAuthority='DERIVED';for(let i=0;i<Math.min(maxAtoms,material.sourceAtomicStructure.length);i++){const a=material.sourceAtomicStructure[i];atoms.push(Object.freeze({atomId:V.deriveId('source-atom',representationId,i),ordinal:i,element:a.element,position:Object.freeze([...a.position]),coordinateAuthority}));}}else{outer:for(let u=0;u<molecular.units.length;u++){const unit=molecular.units[u],elements=expandedElements(unit);for(let i=0;i<elements.length;i++){if(atoms.length>=maxAtoms)break outer;atoms.push(Object.freeze({atomId:V.deriveId('representative-atom',representationId,u,i),ordinal:atoms.length,element:elements[i],position:Object.freeze(representativePosition(representationId,unit,i,u)),coordinateAuthority}));}}if(!atoms.length)visualAuthority='PRESENTATION_ONLY';}
 const quantumBoundary=Object.freeze({contract:'ofu-v1-nonclassical-boundary-1',classicalTrajectoryClaim:false,electronOrbitClaim:false,exactWavefunctionClaim:false,quantumDynamicsSimulated:false,providerRegimeReserved:'FUTURE_NON_CLASSICAL_PROVIDER',message:'Atomic positions are bounded structural representations; below this boundary classical particle trajectories are not asserted.'});return V.freezeDeep({contract:'ofu-v1-atomic-representation-1',representationId,regime:'ATOMIC',sourceEntityId:material.sourceEntityId,materialId:material.materialId,parentRepresentationId:molecular.representationId,sampleIndex,status:atoms.length?'REPRESENTATIVE_ATOMIC_STRUCTURE':'INSUFFICIENT_CHEMISTRY_FOR_ATOMIC_STRUCTURE',atomCount:atoms.length,atoms,coordinateAuthority,visualAuthority,latticeMotif:material.latticeMotif?{name:material.latticeMotif,authority:material.chemistryAuthority}:null,thermalVariation:{mode:'BOUNDED_PRESENTATION_JITTER',enabled:false,trajectoryClaim:false,temperatureMilliK:material.temperatureMilliK},dynamics:'NOT_SIMULATED',quantumBoundary,entireObjectEnumerated:false,authority:visualAuthority});}
O.v1Atomic=Object.freeze({VERSION,MAX_ATOMS,GEOMETRY,represent});
})(globalThis);
