import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {chromium,firefox,webkit} from 'playwright';
const name=process.env.BROWSER||'chromium',engine={chromium,firefox,webkit}[name];assert(engine,'known browser required');
const file=path.resolve('dist/One_File_Universe.html'),build=JSON.parse(fs.readFileSync('dist/rendering-build-manifest.json','utf8')),source=process.env.OFU_SOURCE_SHA;
assert.equal(build.sourceCommit,source);assert.equal(build.px?.scope,'FULL_V1_WAVE_A_PRODUCT');assert.equal(createHash('sha256').update(fs.readFileSync(file)).digest('hex'),build.artifactSha256);
const headed=process.env.HEADED==='1',browser=await engine.launch({headless:!headed,...(name==='firefox'?{firefoxUserPrefs:{'webgl.disabled':false,'webgl.force-enabled':true,'webgl.forbid-software':false}}:{})}),context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:Number(process.env.DPR||1)}),page=await context.newPage(),errors=[],requests=[];
page.on('pageerror',e=>errors.push(String(e.message||e)));page.on('request',r=>requests.push({url:r.url(),type:r.resourceType(),nav:r.isNavigationRequest()}));const url=pathToFileURL(file).href;
try{
 await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>OFU.pxProduct?.snapshot().registry.bindingsSealed&&OFU.waveIVVerticalSlice?.state.initialized&&__OFU_BASELINE_REPORT__?.status==='READY',null,{timeout:30000});
 const capability=await page.evaluate(()=>{const c=document.createElement('canvas'),gl=c.getContext('webgl2');return{webgl2:!!gl,renderer:gl?String(gl.getParameter(gl.RENDERER)):null};});assert.equal(capability.webgl2,true,'PX release requires real WebGL2 capability');
 const baseline=await page.evaluate(()=>OFU.pxProduct.captured()),initial=await page.evaluate(()=>OFU.pxProduct.snapshot());
 const providerChecks=await page.evaluate(()=>{const P=OFU.pxProduct,checks=[];for(const id of ['px.domain.canonical','px.model.identity','px.inspector.selection','px.test.conformance']){const result=P.inspect(id);if(result.provider!==id)throw new Error('provider dispatch mismatch');checks.push(id);}const repr=P.inspect('px.representation.context',{},'REPRESENT');if(repr.value.authority!=='PRESENTATION_ONLY')throw new Error('representation authority');checks.push(repr.provider);const query=P.inspect('px.query.discovery',{address:[],cursor:null,limit:10,filters:{}},'DISCOVER');if(!query.value.planets.some(p=>p.id===P.captured().selection.target.entityId))throw new Error('bounded discovery lost selected planet');checks.push(query.provider);const payload={selection:P.captured().selection,scale:OFU.waveIVScaleRuntime.snapshot().semanticScale},encoded=P.inspect('px.persistence.context',payload,'ENCODE').value,decoded=P.inspect('px.persistence.context',encoded,'DECODE').value;if(OFU.pxContracts.stable(payload)!==OFU.pxContracts.stable(decoded))throw new Error('context persistence roundtrip');let rejected=false;try{P.decodeContext({...encoded,payload:{corrupt:true}});}catch(e){rejected=e.code==='INTEGRITY';}if(!rejected)throw new Error('corrupt context admitted');checks.push('px.persistence.context');return checks;});
 const journeys=[];
 for(const viewport of [{width:1280,height:800},{width:390,height:844},{width:844,height:390}]){
  await page.setViewportSize(viewport);
  for(const scale of ['galaxy','galactic_region','stellar_neighborhood','system','orbit','approach','global_surface','regional_surface','local_surface','human','local_surface','global_surface','orbit','system','galaxy']){
   await page.locator('[data-wave-iv-scale="'+scale+'"]').click();await page.waitForFunction(s=>OFU.waveIVScaleRuntime.snapshot().semanticScale===s,scale,{timeout:10000});
   if(!['galaxy','galactic_region','stellar_neighborhood','system'].includes(scale))await page.waitForFunction(s=>{const p=__OFU_PLANET_PREVIEW__;return ['regional_surface','local_surface','human'].includes(s)?p.backend==='webgl2-local-surface':p.backend==='webgl2';},scale,{timeout:10000});
   const record=await page.evaluate(()=>{const x=OFU.pxProduct.snapshot(),r=OFU.waveIVScaleRuntime.snapshot(),p=__OFU_PLANET_PREVIEW__.snapshot();return{scale:r.semanticScale,provider:r.activeSceneProvider,id:r.selectedCanonicalTarget.planetId,backend:p.backend,witness:x.lastWitness,resources:p.gpu?.gpu||null,registry:x.registry};});
   assert.equal(record.id,baseline.selection.target.entityId);assert.equal(record.witness.status,'PASS');assert.equal(record.witness.projection.selectionDigest,await page.evaluate(()=>OFU.pxContracts.digest(OFU.pxProduct.captured().selection)));assert.equal(record.registry.manifestDigest,initial.registry.manifestDigest);journeys.push({viewport,scale,provider:record.provider,backend:record.backend,witness:record.witness.projection.resultDigest});
  }
 }
 const final=await page.evaluate(()=>({capture:OFU.pxProduct.captured(),state:OFU.pxProduct.snapshot(),resources:OFU.pxResources.snapshot(),globe:OFU.planetWebGL2.stateStats(document.getElementById('planet-view')),surface:OFU.planetSurfaceWebGL2.stats(document.getElementById('planet-view'))}));
 assert.deepEqual(final.capture,baseline);assert(final.state.metrics.renderCalls>0);assert(final.state.metrics.reconciliations>=30);assert(final.state.cacheEntries<=final.state.cacheLimit);assert(final.state.witnessCount<=final.state.witnessLimit);assert.equal(final.state.registry.entries,initial.registry.entries);assert.equal(final.state.registry.bindingsSealed,true);
 const unexpected=requests.filter(r=>!(r.nav&&r.type==='document'&&r.url===url)&&!['blob:','data:','about:'].some(prefix=>r.url.startsWith(prefix)));assert.equal(unexpected.length,0,JSON.stringify(unexpected));assert.deepEqual(errors,[]);
 const evidence={schema:'ofu-px-browser-evidence-1',status:'PASS',sourceSha:source,artifactSha256:build.artifactSha256,componentCompositionSha256:build.componentCompositionSha256,platform:process.platform,arch:process.arch,browser:name,browserVersion:browser.version(),headed,capability,providerChecks,journeys,canonicalBefore:baseline.canonicalDigest,canonicalAfter:final.capture.canonicalDigest,p4Before:baseline.p4Digest,p4After:final.capture.p4Digest,registry:final.state.registry,metrics:final.state.metrics,workingSet:{cacheEntries:final.state.cacheEntries,witnessCount:final.state.witnessCount,resources:final.resources},directFile:true,offline:true,unexpectedNetworkRequests:0,pageErrors:0,physicalAndroid:'NOT_VERIFIED',physicalIOS:'NOT_VERIFIED'};
 const dir='dist/evidence/rendering-production';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,`px-browser-${process.platform}-${process.arch}-${name}.json`),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence));
}finally{await context.close();await browser.close();}
