import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {chromium,firefox,webkit} from 'playwright';
import {immutableBrowserArtifact} from '../helpers/immutable-browser-artifact.mjs';
const name=process.env.BROWSER||'chromium',engine={chromium,firefox,webkit}[name];assert(engine,'known browser required');
const source=process.env.OFU_SOURCE_SHA,immutableInput=immutableBrowserArtifact({consumer:`px-browser-${name}`}),file=immutableInput.artifactPath,build=immutableInput.manifest;
assert.equal(build.sourceCommit,source);assert.equal(build.px?.scope,'FULL_V2_LIVING_PRODUCT_OVER_V1_COMPATIBILITY_RUNTIME');assert.equal(createHash('sha256').update(fs.readFileSync(file)).digest('hex'),build.artifactSha256);
const headed=process.env.HEADED==='1',browser=await engine.launch({headless:!headed,...(name==='firefox'?{firefoxUserPrefs:{'webgl.disabled':false,'webgl.force-enabled':true,'webgl.forbid-software':false}}:{})}),context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:Number(process.env.DPR||1)}),page=await context.newPage(),errors=[],requests=[];
page.on('pageerror',e=>errors.push(String(e.message||e)));page.on('request',r=>requests.push({url:r.url(),type:r.resourceType(),nav:r.isNavigationRequest()}));const url=pathToFileURL(file).href;
try{
 await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>OFU.pxProduct?.snapshot().registry.bindingsSealed&&OFU.v1LivingProduct?.snapshot().initialized&&OFU.productUI&&__OFU_BASELINE_REPORT__?.status==='READY',null,{timeout:30000});
 const capability=await page.evaluate(()=>{const c=document.createElement('canvas'),gl=c.getContext('webgl2');return{webgl2:!!gl,renderer:gl?String(gl.getParameter(gl.RENDERER)):null};});assert.equal(capability.webgl2,true,'PX release requires real WebGL2 capability');
 const baseline=await page.evaluate(()=>OFU.pxProduct.captured()),initial=await page.evaluate(()=>OFU.pxProduct.snapshot());
 const providerChecks=await page.evaluate(()=>{const P=OFU.pxProduct,checks=[];for(const id of ['px.domain.canonical','px.model.identity','px.inspector.selection','px.test.conformance']){const result=P.inspect(id);if(result.provider!==id)throw new Error('provider dispatch mismatch');checks.push(id);}const repr=P.inspect('px.representation.context',{},'REPRESENT');if(repr.value.authority!=='PRESENTATION_ONLY')throw new Error('representation authority');checks.push(repr.provider);const query=P.inspect('px.query.discovery',{address:[],cursor:null,limit:10,filters:{}},'DISCOVER');if(!query.value.planets.some(p=>p.id===P.captured().selection.target.entityId))throw new Error('bounded discovery lost selected planet');checks.push(query.provider);const payload={selection:P.captured().selection,scale:OFU.waveIVScaleRuntime.snapshot().semanticScale},encoded=P.inspect('px.persistence.context',payload,'ENCODE').value,decoded=P.inspect('px.persistence.context',encoded,'DECODE').value;if(OFU.pxContracts.stable(payload)!==OFU.pxContracts.stable(decoded))throw new Error('context persistence roundtrip');let rejected=false;try{P.decodeContext({...encoded,payload:{corrupt:true}});}catch(e){rejected=e.code==='INTEGRITY';}if(!rejected)throw new Error('corrupt context admitted');checks.push('px.persistence.context');return checks;});
 const journeys=[];let mobileSheetExpansions=0,mobileSheetCollapses=0;
 async function stage(expected){await page.waitForFunction(s=>OFU.v1LivingProduct.runtime.snapshot().stage===s,expected,{timeout:10000});const rec=await page.evaluate(()=>{const s=OFU.v1LivingProduct.runtime.snapshot(),p=OFU.pxProduct.snapshot(),r=OFU.v1LivingProduct.renderer.state();return{stage:s.stage,body:s.body?.entityId||null,history:s.historyDepth,cache:s.discoveryCacheEntries,cacheLimit:s.discoveryCacheLimit,traversal:s.traversal,registry:p.registry,render:r};});assert.equal(rec.stage,expected);assert(rec.cache<=rec.cacheLimit);return rec;}
 async function settleMobileMode(){await page.waitForFunction(()=>{const expected=matchMedia('(max-width: 700px), (max-height: 520px) and (pointer: coarse)').matches,mobile=OFU.v08MobileInteraction?.snapshot?.();return !!mobile&&mobile.active===expected&&document.documentElement.dataset.ofuMobile===(expected?'true':'false');},null,{timeout:5000});}
 async function settleMobileSheet(){const mobile=await page.evaluate(()=>OFU.v08MobileInteraction?.snapshot?.()||null);if(!mobile?.active)return;const panel=page.locator('#mobile-sheet');await panel.evaluate(el=>new Promise((resolve,reject)=>{let last='',stable=0,frames=0;const tick=()=>{const r=el.getBoundingClientRect(),sig=[r.top,r.bottom,r.height].map(x=>Math.round(x*10)).join(':');stable=sig===last?stable+1:0;last=sig;if(stable>=3)return resolve(true);if(++frames>120)return reject(new Error('mobile sheet geometry did not settle'));requestAnimationFrame(tick)};requestAnimationFrame(tick)}));const nested=await panel.evaluate(el=>[...el.querySelectorAll('.mobile-sheet-body .living-choices')].filter(x=>/auto|scroll/.test(getComputedStyle(x).overflowY)).length);assert.equal(nested,0,'mobile Explore sheet must own vertical scrolling without nested living-choice scroll traps');}
 async function ensureExplore(){await page.evaluate(()=>OFU.productUI.workspace('explore',{focus:false,announceChange:false}));await page.waitForFunction(()=>!document.querySelector('[data-workspace-panel="explore"]').hidden);const mobile=await page.evaluate(()=>OFU.v08MobileInteraction?.snapshot?.()||null);if(mobile?.active&&!mobile.accessibility.sheetExpanded){const toggle=page.locator('.mobile-sheet-toggle:visible').first();await toggle.waitFor({state:'visible',timeout:5000});assert.equal(await toggle.getAttribute('aria-expanded'),'false');await toggle.click();await page.waitForFunction(()=>OFU.v08MobileInteraction.snapshot().accessibility.sheetExpanded===true);assert.equal(await toggle.getAttribute('aria-expanded'),'true');mobileSheetExpansions++;}await settleMobileSheet();}
 async function collapseExploreForViewport(){const mobile=await page.evaluate(()=>OFU.v08MobileInteraction?.snapshot?.()||null);if(!mobile?.active||!mobile.accessibility.sheetExpanded)return;const toggle=page.locator('.mobile-sheet-toggle:visible').first();await toggle.waitFor({state:'visible',timeout:5000});assert.equal(await toggle.getAttribute('aria-expanded'),'true');await toggle.click();await page.waitForFunction(()=>OFU.v08MobileInteraction.snapshot().accessibility.sheetExpanded===false);assert.equal(await toggle.getAttribute('aria-expanded'),'false');mobileSheetCollapses++;await settleMobileSheet();}
 async function clickPanel(target){await target.waitFor({state:'visible',timeout:5000});await target.scrollIntoViewIfNeeded();await target.click({timeout:15000});}
 async function clickScale(id){await ensureExplore();await collapseExploreForViewport();const target=page.locator(`[data-living-scale="${id}"]:visible`).first();await clickPanel(target);}
 async function clickFirstEntity(){await ensureExplore();const target=page.locator('#living-panel [data-living-entity]:visible').first();await target.waitFor({state:'visible',timeout:5000});const id=await target.getAttribute('data-living-entity');assert(id,'visible living entity identity required');await clickPanel(target);return id;}
 async function clickEntity(id){await ensureExplore();const target=page.locator(`#living-panel [data-living-entity="${id}"]:visible`).first();await clickPanel(target);}
 async function clickAction(id){await ensureExplore();const target=page.locator(`#living-panel [data-living-action="${id}"]:visible`).first();await clickPanel(target);}
 async function chooseSurfaceBody(){const candidate=await page.evaluate(()=>{const rows=OFU.v1LivingProduct.runtime.snapshot().rows||[],solid=rows.find(x=>x.kind==='planet'&&!['GAS_GIANT','ICE_GIANT'].includes(x.metadata?.facts?.bulkPriorClass))||rows.find(x=>x.kind==='moon')||rows.find(x=>x.kind==='planet');return solid?{selector:solid.canonicalId||solid.entityId,entityId:solid.entityId,kind:solid.kind,bulk:solid.metadata?.facts?.bulkPriorClass||null}:null;});assert(candidate,'current visible system must expose a traversable world');await clickEntity(candidate.selector);return candidate;}
 for(const viewport of [{width:1280,height:800},{width:390,height:844},{width:844,height:390}]){
  await page.setViewportSize(viewport);await settleMobileMode();await clickScale('UNIVERSE');await stage('UNIVERSE');
  await clickFirstEntity();await stage('GALAXY');await clickFirstEntity();await stage('REGION');
  await clickAction('deeper');await stage('NEIGHBORHOOD');await clickFirstEntity();await stage('SYSTEM');
  const chosen=await chooseSurfaceBody();let rec=await stage('ORBIT');assert.equal(rec.body,chosen.entityId);
  for(const expected of ['APPROACH','GLOBAL_SURFACE','REGIONAL_SURFACE','LOCAL_SURFACE','HUMAN']){await clickAction('deeper');rec=await stage(expected);assert.equal(rec.body,chosen.entityId);journeys.push({viewport,stage:expected,body:rec.body,cache:rec.cache,backend:rec.render.backend||rec.render.mode||null});}
  for(const expected of ['LOCAL_SURFACE','GLOBAL_SURFACE','ORBIT','SYSTEM','GALAXY']){await clickScale(expected);rec=await stage(expected);if(!['SYSTEM','GALAXY'].includes(expected))assert.equal(rec.body,chosen.entityId);journeys.push({viewport,stage:expected,body:rec.body,cache:rec.cache,backend:rec.render.backend||rec.render.mode||null});}
 }
 const final=await page.evaluate(()=>({capture:OFU.pxProduct.captured(),state:OFU.pxProduct.snapshot(),resources:OFU.pxResources.snapshot(),living:OFU.v1LivingProduct.runtime.snapshot(),render:OFU.v1LivingProduct.renderer.state(),mobile:OFU.v08MobileInteraction?.snapshot?.()||null}));
 assert.deepEqual(final.capture,baseline);assert(final.state.cacheEntries<=final.state.cacheLimit);assert(final.state.witnessCount<=final.state.witnessLimit);assert.equal(final.state.registry.entries,initial.registry.entries);assert.equal(final.state.registry.bindingsSealed,true);assert.equal(final.state.registry.manifestDigest,initial.registry.manifestDigest);assert(final.living.historyDepth<=final.living.maxHistory);assert(final.living.discoveryCacheEntries<=final.living.discoveryCacheLimit);assert(mobileSheetExpansions>=1,'mobile journeys must exercise the real Explore sheet expand affordance');assert(mobileSheetCollapses>=1,'mobile viewport travel must exercise the real Explore sheet collapse affordance');
 const unexpected=requests.filter(r=>!(r.nav&&r.type==='document'&&r.url===url)&&!['blob:','data:','about:'].some(prefix=>r.url.startsWith(prefix)));assert.equal(unexpected.length,0,JSON.stringify(unexpected));assert.deepEqual(errors,[]);
 const artifactVerification=immutableInput.verify();assert.equal(artifactVerification.hashBeforeEqualsAfter,true,'PX browser artifact changed during certification');
 const evidence={schema:'ofu-px-browser-evidence-2',status:'PASS',sourceSha:source,artifactSha256:build.artifactSha256,componentCompositionSha256:build.componentCompositionSha256,platform:process.platform,arch:process.arch,browser:name,browserVersion:browser.version(),headed,capability,providerChecks,journeys,mobileSheetExpansions,mobileSheetCollapses,canonicalBefore:baseline.canonicalDigest,canonicalAfter:final.capture.canonicalDigest,p4Before:baseline.p4Digest,p4After:final.capture.p4Digest,registry:final.state.registry,metrics:final.state.metrics,workingSet:{pxCacheEntries:final.state.cacheEntries,pxWitnessCount:final.state.witnessCount,livingHistoryDepth:final.living.historyDepth,livingDiscoveryCacheEntries:final.living.discoveryCacheEntries,resources:final.resources},directFile:true,offline:true,unexpectedNetworkRequests:0,pageErrors:0,physicalAndroid:'NOT_VERIFIED',physicalIOS:'NOT_VERIFIED',immutableArtifact:{sourceCommit:artifactVerification.sourceCommit,bytes:artifactVerification.bytes,sha256:artifactVerification.sha256,hashBeforeEqualsAfter:artifactVerification.hashBeforeEqualsAfter}};
 const dir='dist/evidence/rendering-production';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,`px-browser-${process.platform}-${process.arch}-${name}.json`),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence));
}finally{await context.close();await browser.close();}
