import assert from 'node:assert/strict';
import {load, descriptor, authority, budget, fidelity, selection, hash} from './helpers.mjs';
const O = load(), C = O.pxContracts;
let cases = 0;
function rejects(fn, code) { cases++; assert.throws(fn, e => e.code === code, code); }
assert.equal(C.stable({z: 1, a: 2}), C.stable({a: 2, z: 1})); cases++;
assert(Object.isFrozen(C.data({a: [{b: 1}]}).a[0])); cases++;
for (const v of [NaN, Infinity, -Infinity, -0, Number.MAX_SAFE_INTEGER + 1]) rejects(() => C.data(v), 'NUMBER');
for (const v of [undefined, 1n, new Date(), new Uint8Array(1), () => {}, Object.create({x: 1})]) rejects(() => C.data(v), 'DATA_TYPE');
rejects(() => C.data(JSON.parse('{"__proto__":{}}')), 'DATA_KEY');
rejects(() => C.data(Object.defineProperty({}, 'x', {get() { throw new Error('must never execute'); }, enumerable: true})), 'DATA_TYPE');
const cyclic = {}; cyclic.self = cyclic; rejects(() => C.data(cyclic), 'DATA_CYCLE');
rejects(() => C.data(new Array(3)), 'DATA_TYPE');
rejects(() => C.data('x'.repeat(65537)), 'DATA_BUDGET');
rejects(() => C.data({x: 'hello'}, {bytes: 5}), 'DATA_BUDGET');
rejects(() => C.data({x: {y: 1}}, {depth: 1}), 'DATA_BUDGET');
rejects(() => C.uint('18446744073709551616'), 'UINT');
rejects(() => C.uint('00'), 'UINT');
rejects(() => C.time({...selection().time, micros: '1000000'}), 'TIME');
rejects(() => C.time({...selection().time, protocol: 'private-clock'}), 'TIME');
assert.equal(C.provider(descriptor()).id, 'test.provider'); cases++;
for (const kind of C.AUTHORITIES) { C.authority(authority(kind)); cases++; }
rejects(() => C.provider(descriptor('test.research', {lifecycle: 'RESEARCH', authority: authority('CANONICAL_PROVEN')})), 'AUTHORITY');
rejects(() => C.provider(descriptor('test.render', {kind: 'renderer'})), 'AUTHORITY');
rejects(() => C.provider(descriptor('test.render', {authority: authority('PRESENTATION_ONLY'), operations: ['TRANSITION']})), 'AUTHORITY');
rejects(() => C.provider(descriptor('test.typo', {operations: ['FAKE']})), 'OPERATION');
rejects(() => C.authority({...authority('CANONICAL_PROVEN'), evidence: []}), 'AUTHORITY');
rejects(() => C.authority({...authority(), class: 'RESEARCH_BECAME_CANONICAL'}), 'AUTHORITY');
rejects(() => C.budget({...budget, entities: 257}, budget), 'BUDGET');
const p = C.provider(descriptor());
const q = C.request({contract: C.VERSION, provider: p.id, operation: 'INSPECT', selection: selection(), fidelity, budget, payload: {}}, p);
const out = {contract: C.VERSION, provider: p.id, version: p.version, authority: p.authority, selection: q.selection, fidelity, usage: {entities: 1, bytes: 16, operations: 1, queue: 0}, value: {a: 1}};
assert.equal(C.envelope(out, p, q).value.a, 1); cases++;
rejects(() => C.envelope({...out, authority: authority('CANONICAL_PROVEN')}, p, q), 'AUTHORITY');
rejects(() => C.envelope({...out, selection: {...q.selection, time: {...q.selection.time, seconds: '1'}}}, p, q), 'IDENTITY');
rejects(() => C.envelope({...out, usage: {...out.usage, bytes: 1}}, p, q), 'BUDGET');
rejects(() => C.request({...q, operation: 'TRANSITION'}, p), 'CAPABILITY');
rejects(() => C.discovery({address: ['galaxy'], cursor: null, limit: 257, filters: {}}), 'QUERY');
const portable = {contract: C.VERSION, codec: 'test.codec', version: '1.0.0', universeId: hash, modelManifestDigest: hash, historyDigest: hash, payload: {x: 1}, payloadDigest: C.digest({x: 1})};
C.persistence(portable); cases++;
rejects(() => C.persistence({...portable, payload: {x: 2}}), 'INTEGRITY');
console.log(JSON.stringify({status: 'PASS', suite: 'px-contracts', cases, authorityClasses: C.AUTHORITIES, sideEffectsFromMalformedInputs: false}));
