(function(root){
'use strict';
const O=root.OFU=root.OFU||{},M=O.waveIVMacroScene,I=O.waveIVMacroInteraction;
if(!M||!I)throw new Error('Wave IV macro canvas requires scene and interaction contracts');
const VERSION='ofu-wave-iv-macro-canvas-4',CONTRACT='ofu-macro-canvas-renderer-4',AUTHORITY='PRESENTATION_ONLY',TAP_SLOP=9;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
const state={canvas:null,ctx:null,scene:null,layout:null,handlers:null,focusedObjectId:null,reducedMotion:false,resizeObserver:null,galaxyPresentation:null,pointers:new Map(),gesture:null,panX:0,panY:0,gestureZooms:0,gesturePans:0,taps:0};
function attach(canvas,{selectionAuthority=null,onNavigate=null,onScaleGesture=null}={}){if(!canvas||typeof canvas.getContext!=='function')throw new TypeError('macro canvas required');detach();state.canvas=canvas;state.ctx=canvas.getContext('2d',{alpha:true});state.handlers={selectionAuthority,onNavigate,onScaleGesture};canvas.tabIndex=canvas.tabIndex<0?0:canvas.tabIndex;canvas.setAttribute('role','application');canvas.setAttribute('aria-label','Universe exploration viewport. Drag to pan, pinch or wheel to move through scale, tap a system or world to visit.');canvas.style.touchAction='none';canvas.addEventListener('pointerdown',onPointerDown,{passive:false});canvas.addEventListener('pointermove',onPointerMove,{passive:false});canvas.addEventListener('pointerup',onPointerUp,{passive:false});canvas.addEventListener('pointercancel',onPointerCancel,{passive:false});canvas.addEventListener('wheel',onWheel,{passive:false});canvas.addEventListener('keydown',onKey);state.reducedMotion=!!root.matchMedia?.('(prefers-reduced-motion: reduce)').matches;if(typeof ResizeObserver==='function'){state.resizeObserver=new ResizeObserver(()=>draw());state.resizeObserver.observe(canvas)}else root.addEventListener?.('resize',draw);return snapshot()}
function detach(){if(state.canvas){state.canvas.removeEventListener('pointerdown',onPointerDown);state.canvas.removeEventListener('pointermove',onPointerMove);state.canvas.removeEventListener('pointerup',onPointerUp);state.canvas.removeEventListener('pointercancel',onPointerCancel);state.canvas.removeEventListener('wheel',onWheel);state.canvas.removeEventListener('keydown',onKey)}state.resizeObserver?.disconnect?.();state.resizeObserver=null;state.canvas=null;state.ctx=null;state.layout=null;state.scene=null;state.focusedObjectId=null;state.galaxyPresentation=null;state.pointers.clear();state.gesture=null;state.panX=0;state.panY=0}
function resize(){const c=state.canvas;if(!c||!state.ctx)return null;const r=c.getBoundingClientRect(),dpr=Math.max(1,Math.min(2,Number(root.devicePixelRatio)||1)),w=Math.max(2,Math.round(r.width*dpr)),h=Math.max(2,Math.round(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}state.ctx.setTransform(dpr,0,0,dpr,0,0);return{width:Math.max(2,r.width),height:Math.max(2,r.height),mobile:r.width<640}}
function cssPoint(event){const r=state.canvas.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top}}
function hitPoint(event){const p=cssPoint(event);return{x:p.x-state.panX,y:p.y-state.panY}}
function pointerDistance(){const a=[...state.pointers.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}
function beginSingle(e,p){state.gesture={kind:'single',id:e.pointerId,startX:p.x,startY:p.y,lastX:p.x,lastY:p.y,moved:false}}
function onPointerDown(e){if(!state.canvas||!state.layout)return;if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();e.stopPropagation();state.canvas.focus({preventScroll:true});const p=cssPoint(e);state.pointers.set(e.pointerId,{x:p.x,y:p.y,type:e.pointerType});try{state.canvas.setPointerCapture(e.pointerId)}catch{}if(state.pointers.size===1)beginSingle(e,p);else if(state.pointers.size===2)state.gesture={kind:'pinch',lastDistance:Math.max(1,pointerDistance()),moved:true,scaleTransitioned:false}}
function onPointerMove(e){if(!state.pointers.has(e.pointerId)||!state.canvas)return;const p=cssPoint(e),prev=state.pointers.get(e.pointerId);state.pointers.set(e.pointerId,{...prev,x:p.x,y:p.y});if(e.cancelable)e.preventDefault();e.stopPropagation();if(state.pointers.size>=2){const d=Math.max(1,pointerDistance());if(state.gesture?.kind!=='pinch')state.gesture={kind:'pinch',lastDistance:d,moved:true,scaleTransitioned:false};else{const ratio=d/Math.max(1,state.gesture.lastDistance);if(!state.gesture.scaleTransitioned&&Number.isFinite(ratio)&&Math.abs(ratio-1)>.004){const before=state.scene?.scale;state.handlers?.onScaleGesture?.({kind:'pinch',zoomDelta:-Math.log(ratio)*5,pointerType:e.pointerType});state.gestureZooms++;if(state.scene?.scale!==before)state.gesture.scaleTransitioned=true}state.gesture.lastDistance=d}return}if(state.gesture?.kind!=='single'||state.gesture.id!==e.pointerId)return;const dx=p.x-state.gesture.lastX,dy=p.y-state.gesture.lastY,total=Math.hypot(p.x-state.gesture.startX,p.y-state.gesture.startY);if(total>TAP_SLOP)state.gesture.moved=true;if(state.gesture.moved){const r=state.canvas.getBoundingClientRect(),maxX=Math.max(24,r.width*.28),maxY=Math.max(24,r.height*.22);state.panX=clamp(state.panX+dx,-maxX,maxX);state.panY=clamp(state.panY+dy,-maxY,maxY);state.gesturePans++;draw()}state.gesture.lastX=p.x;state.gesture.lastY=p.y}
function activateAt(e){if(!state.layout)return;const p=hitPoint(e),hit=I.hitTest(state.layout,p.x,p.y);if(!hit)return;state.focusedObjectId=hit.objectId;I.activate(hit,state.handlers||{});state.taps++;draw()}
function finishPointer(e,cancelled=false){const wasSingle=state.gesture?.kind==='single'&&state.gesture.id===e.pointerId,shouldTap=wasSingle&&!state.gesture.moved&&!cancelled&&state.pointers.size===1;if(shouldTap)activateAt(e);state.pointers.delete(e.pointerId);if(state.canvas?.hasPointerCapture?.(e.pointerId))try{state.canvas.releasePointerCapture(e.pointerId)}catch{}if(state.pointers.size===1){const [id,p]=state.pointers.entries().next().value;beginSingle({pointerId:id},p)}else if(state.pointers.size===0)state.gesture=null;else state.gesture={kind:'pinch',lastDistance:Math.max(1,pointerDistance()),moved:true,scaleTransitioned:false}}
function onPointerUp(e){if(!state.pointers.has(e.pointerId))return;if(e.cancelable)e.preventDefault();e.stopPropagation();finishPointer(e,false)}
function onPointerCancel(e){if(!state.pointers.has(e.pointerId))return;finishPointer(e,true)}
function onWheel(e){if(!state.layout)return;e.preventDefault();e.stopPropagation();const delta=clamp(Number(e.deltaY)/100,-1.5,1.5);if(!delta)return;state.handlers?.onScaleGesture?.({kind:'wheel',zoomDelta:delta,pointerType:'wheel'});state.gestureZooms++}
function onKey(event){if(!state.layout)return;if(event.key==='+'||event.key==='='){event.preventDefault();state.handlers?.onScaleGesture?.({kind:'keyboard',zoomDelta:-1,pointerType:'keyboard'});state.gestureZooms++;return}if(event.key==='-'||event.key==='_'){event.preventDefault();state.handlers?.onScaleGesture?.({kind:'keyboard',zoomDelta:1,pointerType:'keyboard'});state.gestureZooms++;return}if(['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home','End'].includes(event.key)){const hit=I.keyboardTarget(state.layout,state.focusedObjectId,event.key);if(hit){state.focusedObjectId=hit.objectId;event.preventDefault();draw()}return}if(event.key==='Enter'||event.key===' '){event.preventDefault();I.keyActivation(state.layout,state.focusedObjectId,event.key,state.handlers||{});draw()}}
function background(g,w,h){const grd=g.createRadialGradient(w*.5,h*.45,0,w*.5,h*.5,Math.max(w,h)*.75);grd.addColorStop(0,'#111c2b');grd.addColorStop(.62,'#07101a');grd.addColorStop(1,'#020509');g.fillStyle=grd;g.fillRect(0,0,w,h)}
function drawDecorative(g,scene,w,h){g.save();for(const d of scene.decorative||[]){const p=d.presentationGeometry||{};g.globalAlpha=clamp(p.opacity??.25,0,.7);g.fillStyle='#c8d3dd';g.beginPath();g.arc((p.x||0)*w,(p.y||0)*h,clamp(p.sizePx??1,.4,2.2),0,Math.PI*2);g.fill()}g.restore()}
function hashText(s){let h=2166136261>>>0;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function rand(seed){let x=seed>>>0;return()=>{x+=0x6d2b79f5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function galaxyPresentationDescriptor(o,{width=1000,height=600,mobile=false}={}){const morphology=String(o?.canonicalGeometry?.morphology||'IRREGULAR').toUpperCase(),min=Math.max(100,Math.min(width,height)),radiusPx=clamp(min*(mobile?.30:.38),92,mobile?180:320),axisY=morphology==='DISK'?.42:morphology==='SPHEROID'?.82:.7,particleCap=mobile?240:480,angleRad=((Number(o?.canonicalGeometry?.orientation?.positionAngleMilliDeg)||0)/1000)*Math.PI/180;return Object.freeze({authority:AUTHORITY,morphology,radiusPx,axisY,angleRad,particleCount:particleCap,particleCap,selectedViewportWidthFraction:Math.min(1,2*radiusPx/Math.max(1,width)),selectedViewportHeightFraction:Math.min(1,2*radiusPx*axisY/Math.max(1,height)),canonicalIndividualStarClaim:false,canonicalSurfaceBrightnessImageClaim:false,decorativeParticlesSelectable:false,geometryMeaning:'BOUNDED_DETERMINISTIC_GALAXY_PRESENTATION_DENSITY'})}
function drawSelectedGalaxyField(g,o,w,h,mobile){const p=o.presentationGeometry||{},cx=(Number(p.x)||.5)*w,cy=(Number(p.y)||.5)*h,d=galaxyPresentationDescriptor(o,{width:w,height:h,mobile}),r=d.radiusPx,rng=rand(hashText(String(o.objectId)+'|'+d.morphology));g.save();g.translate(cx,cy);g.rotate(d.angleRad);g.globalCompositeOperation='lighter';g.scale(1,d.axisY);let glow=g.createRadialGradient(0,0,0,0,0,r);glow.addColorStop(0,'rgba(232,240,245,.58)');glow.addColorStop(.12,'rgba(183,207,223,.38)');glow.addColorStop(.38,'rgba(105,145,176,.20)');glow.addColorStop(.78,'rgba(64,99,128,.09)');glow.addColorStop(1,'rgba(38,65,91,0)');g.globalAlpha=1;g.fillStyle=glow;g.beginPath();g.arc(0,0,r,0,Math.PI*2);g.fill();const core=g.createRadialGradient(0,0,0,0,0,r*.22);core.addColorStop(0,'rgba(247,250,252,.82)');core.addColorStop(.3,'rgba(210,226,236,.44)');core.addColorStop(1,'rgba(150,183,204,0)');g.fillStyle=core;g.beginPath();g.arc(0,0,r*.22,0,Math.PI*2);g.fill();for(let i=0;i<d.particleCount;i++){let rr=Math.pow(rng(),d.morphology==='SPHEROID'?.74:1.45)*r,th=rng()*Math.PI*2,x=Math.cos(th)*rr,y=Math.sin(th)*rr;if(d.morphology==='IRREGULAR'){const l=i%3,a=[-.36,.3,.08][l]*r,b=[.14,-.22,.32][l]*r;x=x*.58+a;y=y*.62+b}const central=1-Math.min(1,rr/r),size=.65+rng()*1.55+central*.9,alpha=.15+rng()*.33+central*.16;g.globalAlpha=alpha;g.fillStyle=i%7===0?'rgba(235,243,248,.96)':'rgba(151,187,211,.9)';g.beginPath();g.arc(x,y,size,0,Math.PI*2);g.fill()}g.restore();state.galaxyPresentation=d;return d}
function drawGalaxy(g,o,w,h){const p=o.presentationGeometry,x=p.x*w,y=p.y*h,r=clamp(p.glyphRadiusPx||10,6,24),m=o.canonicalGeometry?.morphology;g.save();g.translate(x,y);g.rotate(((Number(o.canonicalGeometry?.orientation?.positionAngleMilliDeg)||0)/1000)*Math.PI/180);g.strokeStyle=o.selectedPath?'rgba(245,250,253,.98)':'rgba(176,199,216,.75)';g.fillStyle=o.selectedPath?'rgba(188,214,230,.34)':'rgba(99,128,151,.18)';g.lineWidth=o.selectedPath?2:1.2;if(m==='DISK'){g.scale(1,.42);g.beginPath();g.arc(0,0,r,0,Math.PI*2)}else if(m==='SPHEROID'){g.beginPath();g.arc(0,0,r*.72,0,Math.PI*2)}else{g.beginPath();for(let i=0;i<7;i++){const a=i/7*Math.PI*2,rr=r*(.58+((i*37)%30)/100),px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?g.lineTo(px,py):g.moveTo(px,py)}g.closePath()}g.fill();g.stroke();g.restore()}
function drawSystemGlyph(g,o,w,h){const p=o.presentationGeometry,x=p.x*w,y=p.y*h,r=clamp(p.glyphRadiusPx||7,5,13),stars=Math.max(1,Number(o.canonicalFacts?.stellarComponentCount||1));g.save();g.strokeStyle=o.selectedPath?'rgba(236,245,250,.94)':'rgba(164,188,207,.68)';g.fillStyle='rgba(196,217,231,.82)';for(let i=0;i<Math.min(4,stars);i++){const a=i/Math.max(1,stars)*Math.PI*2,rr=i===0?0:r*.5;g.beginPath();g.arc(x+Math.cos(a)*rr,y+Math.sin(a)*rr,Math.max(1.8,r*.22),0,Math.PI*2);g.fill()}if(o.selectedPath){g.lineWidth=1.5;g.beginPath();g.arc(x,y,r+6,0,Math.PI*2);g.stroke()}g.restore()}
function starRgb(d){const rgb=d?.displayRgb||[.78,.82,.86];return'rgb('+rgb.map(v=>Math.round(clamp(v,0,1)*255)).join(',')+')'}
function rgbCss(rgb,fallback){if(!Array.isArray(rgb))return fallback;return'rgb('+rgb.map(v=>Math.round(clamp(v,0,1)*255)).join(',')+')'}
function drawSystem(g,scene,w,h){for(const guide of scene.guides||[]){if(guide.kind!=='ORBIT_ORDER_GUIDE')continue;const p=guide.presentationGeometry,r=p.radiusNormalized*Math.min(w,h);g.strokeStyle='rgba(162,184,201,.18)';g.lineWidth=1;g.beginPath();g.ellipse(w*.5,h*.5,r,r*(p.ellipseYScale||.58),0,0,Math.PI*2);g.stroke()}for(const o of scene.objects||[]){const p=o.presentationGeometry;if(o.kind==='STAR'){g.fillStyle=starRgb(o.presentationDescriptor);g.globalAlpha=clamp(o.presentationDescriptor?.displayIntensity??.8,.28,1);g.shadowColor=g.fillStyle;g.shadowBlur=18;g.beginPath();g.arc(p.x*w,p.y*h,clamp(p.glyphRadiusPx||8,5,25),0,Math.PI*2);g.fill();g.shadowBlur=0;g.globalAlpha=1}else if(o.kind==='PLANET'){const x=p.x*w,y=p.y*h,pal=o.presentationDescriptor?.palette||{},r=o.selectedPath?12:9;const grad=g.createRadialGradient(x-r*.35,y-r*.4,1,x,y,r);grad.addColorStop(0,rgbCss(pal.accent,'#d4d8db'));grad.addColorStop(.52,rgbCss(pal.primary,pal.marker||'#9aa3aa'));grad.addColorStop(1,rgbCss(pal.secondary,'#4b5157'));g.fillStyle=grad;g.shadowColor='rgba(170,205,225,.28)';g.shadowBlur=o.selectedPath?12:4;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();g.shadowBlur=0;g.strokeStyle=o.selectedPath?'rgba(242,249,253,.98)':'rgba(189,211,226,.42)';g.lineWidth=o.selectedPath?2:1;g.beginPath();g.arc(x,y,r+4,0,Math.PI*2);g.stroke();if(o.selectedPath){g.strokeStyle='rgba(129,194,231,.50)';g.beginPath();g.arc(x,y,r+10,0,Math.PI*2);g.stroke()}}}}
function drawOrbit(g,scene,w,h){const exclusion=Math.min(w,h)*(scene.handoff?.centerExclusionNormalized||.31);g.save();g.strokeStyle='rgba(166,190,207,.24)';g.lineWidth=1.3;g.beginPath();g.arc(w*.5,h*.5,exclusion,Math.PI*.15,Math.PI*.82);g.stroke();for(const o of scene.objects||[]){if(o.kind!=='STAR')continue;const p=o.presentationGeometry;g.fillStyle=starRgb(o.presentationDescriptor);g.globalAlpha=.72;g.beginPath();g.arc(p.x*w,p.y*h,clamp(p.glyphRadiusPx||5,3,12),0,Math.PI*2);g.fill()}g.restore();g.globalAlpha=1}
function drawLabels(g,layout){g.save();g.font='600 11px system-ui,sans-serif';g.textBaseline='bottom';for(const l of layout.labels||[]){g.fillStyle=l.objectId===state.focusedObjectId?'rgba(245,250,253,.98)':'rgba(207,221,231,.80)';g.fillText(l.text,l.x+12,l.y-9)}g.restore()}
function drawFocus(g,layout){const hit=(layout.hits||[]).find(h=>h.objectId===state.focusedObjectId);if(!hit)return;g.save();g.strokeStyle='rgba(242,248,252,.96)';g.lineWidth=2;g.setLineDash([4,3]);g.strokeRect(hit.left,hit.top,hit.width,hit.height);g.restore()}
function draw(scene=state.scene){if(scene)state.scene=scene;if(!state.canvas||!state.ctx||!state.scene)return snapshot();M.validateScene(state.scene);const vp=resize();if(!vp)return snapshot();const g=state.ctx,w=vp.width,h=vp.height;g.clearRect(0,0,w,h);background(g,w,h);state.galaxyPresentation=null;state.layout=I.layout(state.scene,vp);g.save();g.translate(state.panX,state.panY);if(state.scene.scale===M.SCALE.GALAXY){const selected=(state.scene.objects||[]).find(o=>o.kind==='GALAXY'&&o.selectedPath)||(state.scene.objects||[]).find(o=>o.kind==='GALAXY');if(selected)drawSelectedGalaxyField(g,selected,w,h,vp.mobile)}drawDecorative(g,state.scene,w,h);if(state.scene.scale===M.SCALE.GALAXY){for(const o of state.scene.objects)if(o.kind==='GALAXY')drawGalaxy(g,o,w,h)}else if(state.scene.scale===M.SCALE.REGION){for(const o of state.scene.objects)if(o.kind==='GALACTIC_REGION')drawSystemGlyph(g,o,w,h)}else if(state.scene.scale===M.SCALE.NEIGHBORHOOD){for(const o of state.scene.objects)if(o.kind==='SYSTEM')drawSystemGlyph(g,o,w,h)}else if(state.scene.scale===M.SCALE.SYSTEM){drawSystem(g,state.scene,w,h)}else if(state.scene.scale===M.SCALE.ORBIT){drawOrbit(g,state.scene,w,h)}drawLabels(g,state.layout);drawFocus(g,state.layout);g.restore();return snapshot()}
function setScene(scene){M.validateScene(scene);const scaleChanged=state.scene?.scale!==scene.scale;state.scene=scene;if(scaleChanged){state.panX=0;state.panY=0}if(!state.focusedObjectId||!(scene.objects||[]).some(o=>o.objectId===state.focusedObjectId))state.focusedObjectId=I.orderedHits(I.layout(scene,{width:1000,height:600}))[0]?.objectId||null;return draw()}
function snapshot(){return Object.freeze({version:VERSION,contract:CONTRACT,attached:!!state.canvas,scale:state.scene?.scale||null,sceneStatus:state.scene?.status||null,focusedObjectId:state.focusedObjectId,hitCount:state.layout?.hits?.length||0,labelCount:state.layout?.labels?.length||0,reducedMotion:state.reducedMotion,orbitPrimaryWorldPrimitiveRendered:false,selectionAuthority:'EXTERNAL',galaxyPresentation:state.galaxyPresentation,touchAction:state.canvas?.style?.touchAction||null,pan:Object.freeze({x:state.panX,y:state.panY}),gestureZooms:state.gestureZooms,gesturePans:state.gesturePans,taps:state.taps})}
O.waveIVMacroCanvas=Object.freeze({VERSION,CONTRACT,AUTHORITY,galaxyPresentationDescriptor,attach,detach,setScene,draw,snapshot});
})(typeof globalThis!=='undefined'?globalThis:this);
