(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,AS=O.v1ExplorationAddressSpace,WS=O.v1ExplorationWorkingSet;
if(!V||!AS||!WS)throw new Error('v1 universal traversal requires address space and working set');
const VERSION='ofu-v1-universal-traversal-1',MAX_HISTORY=96,MAX_NODE_INDEX=256;
function assert(ok,message){V.assert(ok,'universal traversal: '+message)}
function frozenNode(node){assert(node&&node.version===AS.VERSION&&typeof node.entityId==='string','valid exploration node required');return node}
function related(a,b){if(!a||!b)return true;if(a.entityId===b.entityId)return true;if(b.parentId===a.entityId||a.parentId===b.entityId)return true;const aa=new Set(a.lineage||[]),bb=new Set(b.lineage||[]);return aa.has(b.entityId)||bb.has(a.entityId)}
function create({initialNode=null,runtime=O.waveIVScaleRuntime||null,workingSet=WS.create(),maxHistory=MAX_HISTORY}={}){
 maxHistory=Number(maxHistory);assert(Number.isSafeInteger(maxHistory)&&maxHistory>=8&&maxHistory<=MAX_HISTORY,'history bound');
 const listeners=new Set(),nodes=new Map(),history=[],forward=[];let sequence=0,transitionSequence=0;
 const state={selectedNode:null,focusedNodeId:null,cameraTargetId:null,transition:null,lastStable:null,lastCancellation:null,travelCount:0,retargetCount:0,backCount:0,forwardCount:0,refineCount:0,reconcileCount:0,lateRequests:0};
 function remember(node,lifecycle='HOT'){node=frozenNode(node);if(nodes.has(node.entityId))nodes.delete(node.entityId);nodes.set(node.entityId,node);while(nodes.size>MAX_NODE_INDEX)nodes.delete(nodes.keys().next().value);workingSet.put('node:'+node.entityId,node,{lifecycle,identity:node.entityId});return node}
 function publicState(){return Object.freeze({version:VERSION,selectedNode:state.selectedNode,focusedNodeId:state.focusedNodeId,cameraTargetId:state.cameraTargetId,transition:state.transition,lastStable:state.lastStable,lastCancellation:state.lastCancellation,historyDepth:history.length,forwardDepth:forward.length,indexedNodes:nodes.size,travelCount:state.travelCount,retargetCount:state.retargetCount,backCount:state.backCount,forwardCount:state.forwardCount,refineCount:state.refineCount,reconcileCount:state.reconcileCount,lateRequests:state.lateRequests,workingSet:workingSet.snapshot()})}
 function emit(type,detail={}){const event=Object.freeze({type:String(type),sequence:++sequence,detail:Object.freeze({...detail}),snapshot:publicState()});for(const fn of listeners)fn(event);return event}
 function onChange(fn){assert(typeof fn==='function','listener');listeners.add(fn);return()=>listeners.delete(fn)}
 function pushHistory(node){if(!node)return;history.push(node);if(history.length>maxHistory)history.shift();forward.length=0}
 function canonicalPlanetKey(node){const key=node?.canonicalKey;if(!key||!Object.hasOwn(key,'orbitSlot'))return null;const fields=AS.PLANET_FIELDS;return Object.freeze(Object.fromEntries(fields.filter(k=>Object.hasOwn(key,k)).map(k=>[k,BigInt(key[k])])))}
 function applyRuntime(node,{source='v1-universal-traversal',driveCamera=true}={}){if(!runtime)return null;const planetKey=canonicalPlanetKey(node);if(planetKey&&typeof runtime.setSelection==='function')runtime.setSelection(planetKey,{planetId:node.kind==='planet'?node.canonicalId||null:null,source});if(typeof runtime.requestStage==='function'&&node.scale)runtime.requestStage(node.scale,{source,transition:true,driveCamera});return runtime.snapshot?.()||null}
 function cancelTransition(reason='OBSOLETE'){if(!state.transition)return false;const cancelled=state.transition;state.transition=null;state.lastCancellation=Object.freeze({id:cancelled.id,reason:String(reason),atSequence:sequence+1});workingSet.cancel('transition:'+cancelled.id,String(reason));emit('transitionCancelled',{transition:cancelled,reason:String(reason)});return true}
 function beginTransition(from,to,{source,mode}){if(state.transition)cancelTransition('RETARGETED');const t=Object.freeze({id:++transitionSequence,fromId:from?.entityId||null,toId:to.entityId,fromScale:from?.scale||null,toScale:to.scale,source:String(source),mode:String(mode),phase:'HANDOFF',startedSequence:sequence+1});state.transition=t;emit('transitionStarted',{transition:t});return t}
 function settleTransition(id=state.transition?.id){if(!state.transition||state.transition.id!==id)return false;const completed=state.transition;state.transition=null;state.lastStable=Object.freeze({nodeId:state.selectedNode?.entityId||null,scale:state.selectedNode?.scale||null,transitionId:completed.id});runtime?.completeTransition?.();emit('transitionCompleted',{transition:completed});return true}
 function commit(node,{source='v1-universal-traversal',mode='TRAVEL',push=true,driveCamera=true,autoComplete=true}={}){node=remember(node,'IMMEDIATE');const previous=state.selectedNode;if(previous&&previous.entityId!==node.entityId&&!related(previous,node)&&mode!=='RETARGET'&&mode!=='RESTORE')throw new Error('unrelated destination requires explicit RETARGET');if(push&&previous&&previous.entityId!==node.entityId)pushHistory(previous);if(mode==='RETARGET')state.retargetCount++;state.travelCount++;beginTransition(previous,node,{source,mode});state.selectedNode=node;state.focusedNodeId=node.entityId;state.cameraTargetId=node.entityId;applyRuntime(node,{source,driveCamera});emit('selectionChanged',{previousId:previous?.entityId||null,nextId:node.entityId,source,mode,identityPreserved:previous?.entityId===node.entityId});if(autoComplete)settleTransition();return publicState()}
 function travel(node,options={}){return commit(node,{...options,mode:options.mode||'TRAVEL'})}
 function retarget(node,options={}){return commit(node,{...options,mode:'RETARGET'})}
 function back({source='v1-back'}={}){if(!history.length)return publicState();const target=history.pop(),current=state.selectedNode;if(current)forward.push(current);state.backCount++;return commit(target,{source,mode:'RESTORE',push:false})}
 function forwardTravel({source='v1-forward'}={}){if(!forward.length)return publicState();const target=forward.pop(),current=state.selectedNode;if(current){history.push(current);if(history.length>maxHistory)history.shift()}state.forwardCount++;return commit(target,{source,mode:'RESTORE',push:false})}
 function focus(nodeOrId){const id=typeof nodeOrId==='string'?nodeOrId:frozenNode(nodeOrId).entityId;if(typeof nodeOrId!=='string')remember(nodeOrId,'HOT');assert(nodes.has(id)||state.selectedNode?.entityId===id,'focus target unknown');state.focusedNodeId=id;emit('focusChanged',{nodeId:id});return publicState()}
 function setCameraTarget(nodeOrId){const id=typeof nodeOrId==='string'?nodeOrId:frozenNode(nodeOrId).entityId;if(typeof nodeOrId!=='string')remember(nodeOrId,'HOT');state.cameraTargetId=id;emit('cameraTargetChanged',{nodeId:id});return publicState()}
 function breadcrumbs(node=state.selectedNode){if(!node)return Object.freeze([]);const ids=[...(node.lineage||[]),node.entityId],items=[];for(const id of ids){const n=nodes.get(id)||workingSet.get('node:'+id);items.push(Object.freeze({entityId:id,kind:n?.kind||'unknown',scale:n?.scale||null,selected:id===node.entityId,available:!!n}))}return Object.freeze(items)}
 function refine(parent,children,{kind='NAVIGATION_REFINEMENT'}={}){parent=frozenNode(parent);assert(Array.isArray(children)&&children.length>0&&children.length<=64,'bounded children');const ids=new Set();for(const c of children){frozenNode(c);assert(c.parentId===parent.entityId,'child parent mismatch');assert(c.universeId===parent.universeId,'universe changed during refinement');assert(!ids.has(c.entityId),'duplicate refined identity');ids.add(c.entityId);remember(c,'WARM')}remember(parent,'HOT');state.refineCount++;const witness=Object.freeze({contract:'ofu-v1-navigation-continuity-1',operation:'REFINE',kind:String(kind),parentId:parent.entityId,childIds:Object.freeze(children.map(c=>c.entityId)),universeId:parent.universeId,status:'PASS',authority:'DERIVED',scientificPromotion:false,digest:V.digest('OFU-V1-NAV-REFINE',parent.entityId,...children.map(c=>c.entityId))});emit('refined',{witness});return witness}
 function project(child){child=frozenNode(child);assert(child.parentId,'child has no parent projection');const witness=Object.freeze({contract:'ofu-v1-navigation-continuity-1',operation:'PROJECT',childId:child.entityId,parentId:child.parentId,universeId:child.universeId,status:'PASS',authority:'DERIVED',scientificPromotion:false,digest:V.digest('OFU-V1-NAV-PROJECT',child.entityId,child.parentId)});emit('projected',{witness});return witness}
 function reconcile(parent,children){const r=refine(parent,children,{kind:'RECONCILE_INPUT'});for(const c of children){const p=project(c);assert(p.parentId===parent.entityId,'projection mismatch')}state.reconcileCount++;const witness=Object.freeze({contract:'ofu-v1-navigation-continuity-1',operation:'RECONCILE',parentId:parent.entityId,children:children.length,status:'PASS',refineDigest:r.digest,authority:'DERIVED',scientificPromotion:false,digest:V.digest('OFU-V1-NAV-RECONCILE',r.digest)});emit('reconciled',{witness});return witness}
 function materialize(requestKey,producer,{lifecycle='WARM',replace=true}={}){assert(typeof producer==='function','materializer');state.lateRequests++;const token=workingSet.request('materialize:'+String(requestKey),async signal=>{signal.throwIfCancelled();const result=await producer(signal);signal.throwIfCancelled();if(Array.isArray(result))for(const n of result)if(n?.version===AS.VERSION)remember(n,lifecycle);else if(result?.version===AS.VERSION)remember(result,lifecycle);return result},{lifecycle,replace});emit('materializationRequested',{requestKey:String(requestKey),requestId:token.id});return token}
 function cancelMaterialization(requestKey,reason='OBSOLETE'){return workingSet.cancel('materialize:'+String(requestKey),reason)}
 function snapshot(){return publicState()}
 if(initialNode){state.selectedNode=remember(initialNode,'IMMEDIATE');state.focusedNodeId=initialNode.entityId;state.cameraTargetId=initialNode.entityId;state.lastStable=Object.freeze({nodeId:initialNode.entityId,scale:initialNode.scale,transitionId:null})}
 return Object.freeze({VERSION,onChange,snapshot,remember,travel,retarget,back,forward:forwardTravel,focus,setCameraTarget,breadcrumbs,cancelTransition,settleTransition,refine,project,reconcile,materialize,cancelMaterialization,related});
}
O.v1UniversalTraversal=Object.freeze({VERSION,MAX_HISTORY,MAX_NODE_INDEX,related,create});
})(typeof globalThis!=='undefined'?globalThis:this);
