import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
globalThis.OFU={};
for(const f of ['src/kernel/sha256.js','src/kernel/p2-unicode.js','src/kernel/p2-canonical.js','src/temporal/p4-temporal.js','src/gameplay/contracts.js','src/gameplay/p2-resource-normalizer.js','src/simulation/cross-domain/causal-engine.js','src/simulation/temporal-adapters/p4-gameplay-bridge.js','src/gameplay/runtime.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const O=globalThis.OFU,P=O.p2,C=O.v2x11GameplayContracts,E=O.v2x11CausalEngine,B=O.v2x11P4GameplayBridge,G=O.v2x11Gameplay;
const id=s=>P.hex(O.sha256.digest(new TextEncoder().encode(s))),universe=id('v2x11-universe'),target=id('v2x11-target'),context={targetId:target,modelWorld:null,source:'TEST'};
let cases=0;
const numericPayload={nested:[60000000n,9007199254740992n],bytes:new Uint8Array([1,2])},normalized=C.safe(numericPayload);
assert.equal(normalized.nested[0],60000000);assert.equal(normalized.nested[1],9007199254740992n);
assert.deepEqual(P.encode(normalized),P.encode(numericPayload));assert.deepEqual(normalized.bytes,numericPayload.bytes);
assert.equal(C.cost({resources:[],timeMicros:60000000n}).timeMicros,60000000);
assert.throws(()=>C.cost({resources:[],timeMicros:BigInt(C.LIMITS.timeMicros)+1n}),/out of range/);
assert.throws(()=>C.cost({resources:[],timeMicros:-1n}),/out of range/);cases+=7;
assert.deepEqual(C.resourceVector([{resourceId:'energy',units:7n}]),[{resourceId:'energy',units:7}]);assert.throws(()=>C.resourceVector([{resourceId:'energy',units:1000000001n}]),/out of range/);cases+=2;
let session=G.createSession({universeIdentity:universe,targetId:target,initialResources:[{resourceId:'energy',units:200},{resourceId:'supplies',units:20},{resourceId:'storage_capacity',units:20}]});
const p1=G.propose({session,actorId:'founder',kind:'SURVEY',parameters:{mode:'baseline'},context}).proposal,p2=G.propose({session,actorId:'founder',kind:'SURVEY',parameters:{mode:'baseline'},context}).proposal;assert.equal(p1.proposalId,p2.proposalId);cases++;
let first=G.perform({session,actorId:'founder',kind:'SURVEY',parameters:{mode:'baseline'},context});session=first.session;assert.equal(first.receipt.status,'ADMITTED');assert.equal(first.receipt.elapsedMicros,1000000);assert.equal(first.execution.status,'APPLIED');cases+=3;
const stale=G.propose({session,actorId:'founder',kind:'MEASURE',parameters:{instrument:'spectrometer'},context});let moved=G.perform({session,actorId:'founder',kind:'SURVEY',parameters:{mode:'follow-up'},context});session=moved.session;const staleExec=E.orchestrate({proposal:stale.proposal,context:stale.context}).execution,staleCommit=B.commit({session,proposal:stale.proposal,execution:staleExec});assert.equal(staleCommit.receipt.status,'REJECTED_PRECONDITION');session=staleCommit.session;cases++;
for(let i=0;i<70;i++){const r=G.perform({session,actorId:'founder',kind:'SURVEY',parameters:{mode:'series-'+i},context});assert.equal(r.receipt.status,'ADMITTED');session=r.session}
const long=B.replay(session);assert(session.world.checkpoint);assert(session.world.events.length<64);assert.equal(long.actions,'73');cases+=3;
const bytes=G.exportSession(session),restored=G.importSession(bytes),bytes2=G.exportSession(restored.session);assert.deepEqual([...bytes2],[...bytes]);assert.equal(restored.revisit.stateDigest,long.stateDigest);cases+=2;
let low=G.createSession({universeIdentity:id('low-universe'),targetId:id('low-target'),initialResources:[{resourceId:'energy',units:1},{resourceId:'supplies',units:0},{resourceId:'storage_capacity',units:0}]});const lowContext={targetId:low.targetId,modelWorld:null};let ok=G.perform({session:low,actorId:'founder',kind:'SURVEY',parameters:{},context:lowContext});low=ok.session;let denied=G.perform({session:low,actorId:'founder',kind:'SURVEY',parameters:{},context:lowContext});assert.equal(denied.receipt.status,'REJECTED_RESOURCE_BUDGET');assert.equal(denied.receipt.resourceBalances.find(x=>x.resourceId==='energy').units,0);cases+=2;
const aid=id('effect-a'),bid=id('effect-b'),a={...C.effect({domain:'evidence',kind:'A',targetId:target,dependsOn:[],authority:C.AUTHORITY,payload:{}}),effectId:aid,dependsOn:[bid]},b={...C.effect({domain:'material',kind:'B',targetId:target,dependsOn:[],authority:C.AUTHORITY,payload:{}}),effectId:bid,dependsOn:[aid]};assert.throws(()=>E.validateEffects([a,b]),/cycle/);cases++;
assert.equal(C.ACTIONS.length,8);assert(G.catalog().every(x=>x.canonicalMutation===false));cases+=2;
console.log(JSON.stringify({status:'PASS',suite:'v2x11-core',cases,stateDigest:long.stateDigest,checkpointCovered:session.world.checkpoint.descriptor.coveredEventCount.toString(),tail:session.world.events.length}));
