(function(root){
'use strict';
const O=root.OFU=root.OFU||{},K=O.v2x09CivilizationCore,S=O.v2x09CivilizationInstitutions;if(!K||!S)throw new Error('V2X-09 core/institutions required');
const {VERSION,MORPHOLOGY_CONTRACT,AUTHORITY,LIMITS,LIMITATIONS,freeze,text,int,clamp,arr,unit,sortId,sourceAuthority,validateCivilization,technologyProfile,deriveId,tradeDegree}=K;
const {institutionProfile}=S;
const EMBODIMENT_CONTRACT='ofu-v2x-09-civilization-embodiment-packet-1';
const EMBODIMENT_LIMITS=Object.freeze({settlements:48,routes:96,infrastructureAssets:256,districtsPerSettlement:12,resourceLinksPerSettlement:8,historyLayersPerSettlement:24,commands:4096,operations:64000});
function targetIds(e){return arr(e?.targetIds).map(text)}
function morphologyForSettlement(state,settlement,economy,tech){
  const sid=text(settlement.settlementId),region=arr(state.regions).find(r=>r.regionId===settlement.regionId)||{},events=arr(state.history?.proposals).filter(e=>targetIds(e).includes(sid)).sort((a,b)=>int(a.epoch)-int(b.epoch)||text(a.eventProposalId).localeCompare(text(b.eventProposalId))),degree=tradeDegree(state,sid),infraAssets=arr(state.infrastructure).filter(x=>x.fromSettlementId===sid||x.toSettlementId===sid||x.settlementId===sid),active=text(settlement.status).toUpperCase()==='ACTIVE'&&int(settlement.population)>0,pop=Math.max(0,int(settlement.population)),infrastructure=clamp(settlement.infrastructurePpm||0),districts=[];
  const add=(kind,basis,weight)=>{if(districts.length<LIMITS.districtsPerSettlement)districts.push(freeze({districtId:deriveId('district',sid,kind),kind,basis,weightPpm:clamp(weight),placement:freeze({u:unit(sid,kind+'u')/1000000,v:unit(sid,kind+'v')/1000000,authority:AUTHORITY.PRESENTATION_ONLY,physicalGeometryClaim:false})}))};
  if(active)add('CORE',['ACTIVE_SETTLEMENT','POPULATION'],220000+Math.min(500000,pop*10));
  if(active&&pop>=150)add('RESIDENTIAL',['POPULATION'],200000+Math.min(600000,pop*8));
  if(active&&clamp(region.biologicalResourcePpm||0)>=120000)add('AGRICULTURAL_HINTERLAND',['BIOLOGICAL_RESOURCE','ACTIVE_SETTLEMENT'],clamp(region.biologicalResourcePpm||0));
  if(active&&tech.activeCapabilities.includes('SPECIALIZED_MATERIALS'))add('PRODUCTION',['TECH:SPECIALIZED_MATERIALS','MATERIAL_RESOURCE'],clamp(region.materialResourcePpm||0));
  if(active&&degree>0&&tech.activeCapabilities.includes('ROUTE_LOGISTICS'))add('MARKET_AND_STORAGE',['TRADE_EDGE','TECH:ROUTE_LOGISTICS'],Math.min(1000000,degree*180000+infrastructure/2));
  if(active&&clamp(region.waterPpm||0)>=450000&&degree>0&&tech.activeCapabilities.includes('WATERBORNE_LOGISTICS'))add('PORT_OR_WATER_TERMINAL',['WATER_ACCESS','TRADE_EDGE','TECH:WATERBORNE_LOGISTICS'],clamp(region.waterPpm||0));
  if(active&&settlement.polityId)add('CIVIC_COORDINATION',['POLITY_MEMBERSHIP'],Math.max(180000,infrastructure));
  const destructive=events.filter(e=>['CONFLICT','SETTLEMENT_DESTROYED','COLLAPSE','RESOURCE_CRISIS'].includes(e.type));
  if(!active||destructive.length)add('RUIN_OR_DAMAGE_LAYER',[!active?'CURRENT_ABANDONMENT':'HISTORY_EVENT'],Math.min(1000000,250000+destructive.length*140000));
  const roadHierarchy=!active?'RELICT_OR_UNSUPPORTED':infraAssets.length>=3||degree>=4?'PRIMARY_AND_SECONDARY_CORRIDORS':infraAssets.length||degree?'LOCAL_OR_REGIONAL_CORRIDORS':'NO_MODELED_CORRIDOR';
  const layout=!active?'ABANDONED_LAYERED':pop>=20000&&degree>=2?'DENSE_NETWORKED_CENTER':pop>=3000&&degree>=1?'CONNECTED_TOWN':degree>=1?'LINEAR_ROUTE_SETTLEMENT':'DISPERSED_SETTLEMENT';
  const layers=[];for(const e of events){let kind=null;if(e.type==='SETTLEMENT_FOUNDATION')kind='FOUNDATION';else if(['CONFLICT','SETTLEMENT_DESTROYED','RESOURCE_CRISIS','COLLAPSE'].includes(e.type))kind='DAMAGE_OR_STRESS';else if(e.type==='ABANDONMENT')kind='ABANDONMENT';else if(e.type==='INFRASTRUCTURE_BUILT')kind='INFRASTRUCTURE_ADDITION';if(kind)layers.push(freeze({layerId:deriveId('layer',sid,e.eventProposalId||e.epoch,kind),kind,epoch:int(e.epoch),sourceEventProposalId:text(e.eventProposalId||''),authority:AUTHORITY.PRESENTATION_ONLY,historyCanonicalClaim:false}));if(layers.length>=LIMITS.historicalLayersPerSettlement)break}
  return freeze({contract:MORPHOLOGY_CONTRACT,settlementId:sid,regionId:text(settlement.regionId),status:text(settlement.status||'UNKNOWN').toUpperCase(),layoutClass:layout,populationBand:pop>=100000?'METROPOLITAN':pop>=20000?'URBAN':pop>=3000?'TOWN':pop>=300?'SETTLEMENT':'SMALL',roadHierarchy,districts,historicalLayers:layers,lod:freeze({regional:freeze({representation:'FOOTPRINT_AND_NETWORK_CUE',districtBudget:Math.min(4,districts.length)}),local:freeze({representation:'DISTRICT_AND_CORRIDOR_DESCRIPTORS',districtBudget:districts.length}),human:freeze({representation:'LANDMARK_AND_EDGE_HINTS_NOT_BUILDING_SIMULATION',landmarkBudget:Math.min(8,districts.length+infraAssets.length)})}),authority:AUTHORITY.PRESENTATION_ONLY,sourceAuthority:sourceAuthority(settlement),claims:freeze({physicalBuildingSimulation:false,physicalRoadGeometry:false,randomRuins:false,historyBackedDamage:destructive.length>0,abandonedCaseHonest:!active})});
}
function cityMorphology(state,{economy=null}={}){
  if(!validateCivilization(state))return freeze({contract:MORPHOLOGY_CONTRACT,status:'NO_MODELED_CIVILIZATION',settlements:[],authority:AUTHORITY.PRESENTATION_ONLY,limitations:LIMITATIONS});
  const tech=technologyProfile(state),rows=sortId(arr(state.settlements),'settlementId').map(s=>morphologyForSettlement(state,s,economy,tech));
  return freeze({contract:MORPHOLOGY_CONTRACT,version:VERSION,status:rows.length?'PROJECTED':'NO_SETTLEMENTS',settlements:rows,technology:tech,authority:AUTHORITY.PRESENTATION_ONLY,bounded:true,limits:LIMITS,claims:freeze({schematicPlacement:true,physicalCityGeometryClaim:false,fullPersistentBuildingSimulation:false,unsupportedInfrastructureNotDecorated:true}),limitations:LIMITATIONS});
}

function cityRenderPlan(state,{settlementId=null}={}){
  const morphology=cityMorphology(state);
  if(morphology.status==='NO_MODELED_CIVILIZATION')return freeze({contract:'ofu-v2x-09-city-render-plan-1',status:'NO_MODELED_CIVILIZATION',commands:[],authority:AUTHORITY.PRESENTATION_ONLY,physicalGeometryClaim:false});
  const selected=settlementId?morphology.settlements.filter(x=>x.settlementId===settlementId):morphology.settlements;
  const commands=[];
  for(const row of selected){
    const cx=unit(row.settlementId,'center-x')/1000000,cy=unit(row.settlementId,'center-y')/1000000;
    commands.push(freeze({kind:'SETTLEMENT_FOOTPRINT_CUE',sourceSettlementId:row.settlementId,x:cx,y:cy,layoutClass:row.layoutClass,populationBand:row.populationBand,status:row.status,authority:AUTHORITY.PRESENTATION_ONLY,physicalPositionClaim:false}));
    for(const d of row.districts)commands.push(freeze({kind:'DISTRICT_CUE',sourceSettlementId:row.settlementId,sourceDistrictId:d.districtId,x:clamp(Math.round((cx+(d.placement.u-.5)*.18)*1000000),0,1000000)/1000000,y:clamp(Math.round((cy+(d.placement.v-.5)*.18)*1000000),0,1000000)/1000000,districtKind:d.kind,weightPpm:d.weightPpm,authority:AUTHORITY.PRESENTATION_ONLY,physicalGeometryClaim:false}));
    for(const layer of row.historicalLayers)commands.push(freeze({kind:'HISTORY_LAYER_CUE',sourceSettlementId:row.settlementId,sourceEventProposalId:layer.sourceEventProposalId,layerKind:layer.kind,epoch:layer.epoch,x:cx,y:cy,authority:AUTHORITY.PRESENTATION_ONLY,historyCanonicalClaim:false}));
  }
  const visibleIds=new Set(selected.map(x=>x.settlementId));
  for(const e of sortId(arr(state?.tradeEdges),'edgeId'))if(visibleIds.has(e.from)&&visibleIds.has(e.to))commands.push(freeze({kind:'CORRIDOR_CUE',sourceEdgeId:text(e.edgeId||deriveId('edge',e.from,e.to)),fromSettlementId:text(e.from),toSettlementId:text(e.to),mode:text(e.mode||'UNSPECIFIED'),status:text(e.status||'ACTIVE'),authority:AUTHORITY.PRESENTATION_ONLY,physicalPathClaim:false}));
  const maxCommands=LIMITS.settlements*(1+LIMITS.districtsPerSettlement+LIMITS.historicalLayersPerSettlement)+LIMITS.tradeEdges;
  if(commands.length>maxCommands)throw new RangeError('V2X-09 render command bound exceeded');
  return freeze({contract:'ofu-v2x-09-city-render-plan-1',version:VERSION,status:commands.length?'PROJECTED':'NO_SUPPORTED_CITY_VISUALS',commands,commandCount:commands.length,maxCommands,authority:AUTHORITY.PRESENTATION_ONLY,bounded:true,physicalGeometryClaim:false,rendererMutationPerformed:false,sharedSceneMutationPerformed:false,requiresConvergenceOwnerComposition:true,limitations:LIMITATIONS});
}

function presentationAnchor(settlementId){return freeze({x:unit(settlementId,'v2-embodiment-x')/1000000,y:unit(settlementId,'v2-embodiment-y')/1000000,authority:AUTHORITY.PRESENTATION_ONLY,physicalPositionClaim:false,placementOwner:'V2X-07_OR_CONVERGENCE'});}
function currentVisualState(settlement){
  const status=text(settlement?.status||'UNKNOWN').toUpperCase(),pop=Math.max(0,int(settlement?.population));
  if(status==='ABANDONED')return 'ABANDONED';
  if(status==='RUINED'||status==='DESTROYED')return 'RUINED';
  if(status==='DAMAGED'||status==='DEGRADED')return 'DAMAGED';
  if(status==='ACTIVE'&&pop>0)return 'ACTIVE';
  return 'UNKNOWN_OR_INACTIVE';
}
function infrastructureVisualState(asset){
  const status=text(asset?.status||'UNKNOWN').toUpperCase(),hasCondition=Number.isFinite(Number(asset?.conditionPpm)),condition=hasCondition?clamp(asset.conditionPpm):null;
  if(status==='ABANDONED')return 'ABANDONED';
  if(status==='RUINED'||status==='DESTROYED')return 'RUINED';
  if(status==='DAMAGED'||status==='DEGRADED')return 'DAMAGED';
  if(hasCondition&&condition<350000)return 'DAMAGED';
  if(status==='ACTIVE')return 'ACTIVE';
  return 'UNKNOWN_OR_INACTIVE';
}
function boundPush(commands,value,counter){counter.count++;if(counter.count>EMBODIMENT_LIMITS.operations)throw new RangeError('V2X-09 embodiment operation bound exceeded');if(commands.length>=EMBODIMENT_LIMITS.commands)throw new RangeError('V2X-09 embodiment command bound exceeded');commands.push(freeze(value));}
function resourceSnapshot(state,economy){const byId=new Map(arr(economy?.resources).map(r=>[text(r.resourceId),r]));return sortId(arr(state?.resources),'resourceId').map(r=>{const e=byId.get(text(r.resourceId))||r;return {...r,amountUnits:e.amountUnits??r.amountUnits,availabilityPpm:e.availabilityPpm??r.availabilityPpm,good:e.good??r.transformsTo};});}
function civilizationEmbodimentPacket(state,{economy=null,advanced=null,settlementId=null}={}){
  if(!validateCivilization(state))return freeze({contract:EMBODIMENT_CONTRACT,status:'NO_MODELED_CIVILIZATION',commands:[],authority:AUTHORITY.PRESENTATION_ONLY,bounded:true,noLegacyFallback:true,requiresConvergenceOwnerComposition:true,limitations:LIMITATIONS});
  if(!advanced||advanced.status!=='MODELED'||advanced.production?.status!=='MODELED'||advanced.urban?.status!=='MODELED'||advanced.resilience?.status!=='MODELED')return freeze({contract:EMBODIMENT_CONTRACT,status:'ADVANCED_MODEL_REQUIRED',commands:[],authority:AUTHORITY.PRESENTATION_ONLY,bounded:true,noLegacyFallback:true,legacyCityRenderPlanUsed:false,requiresAdvancedComposition:true,requiresConvergenceOwnerComposition:true,limitations:LIMITATIONS});
  const allSettlements=sortId(arr(state.settlements),'settlementId');if(allSettlements.length>EMBODIMENT_LIMITS.settlements)throw new RangeError('V2X-09 embodiment settlement bound exceeded');
  const allInfrastructure=sortId(arr(state.infrastructure),'infrastructureId');if(allInfrastructure.length>EMBODIMENT_LIMITS.infrastructureAssets)throw new RangeError('V2X-09 embodiment infrastructure bound exceeded');
  const productionRoutes=sortId(arr(advanced.production.routes),'edgeId');if(productionRoutes.length>EMBODIMENT_LIMITS.routes)throw new RangeError('V2X-09 embodiment route bound exceeded');
  const selected=settlementId?allSettlements.filter(s=>text(s.settlementId)===text(settlementId)):allSettlements,visibleIds=new Set(selected.map(s=>text(s.settlementId))),anchors=new Map(allSettlements.map(s=>[text(s.settlementId),presentationAnchor(text(s.settlementId))])),morph=cityMorphology(state,{economy}),morphById=new Map(morph.settlements.map(x=>[x.settlementId,x])),urbanById=new Map(arr(advanced.urban.settlements).map(x=>[text(x.settlementId),x])),resilienceById=new Map(arr(advanced.resilience.settlements).map(x=>[text(x.settlementId),x])),institutions=institutionProfile(state),resources=resourceSnapshot(state,economy),commands=[],counter={count:0};
  const selectedResourceLinks=new Set(),selectedInfrastructure=new Set(),selectedRouteIds=new Set();
  for(const settlement of selected){
    const sid=text(settlement.settlementId),anchor=anchors.get(sid),m=morphById.get(sid)||null,u=urbanById.get(sid)||null,r=resilienceById.get(sid)||null,inst=arr(institutions.institutions).filter(x=>arr(x.settlementIds).map(text).includes(sid));
    boundPush(commands,{kind:'SETTLEMENT_EMBODIMENT',sourceSettlementId:sid,regionId:text(settlement.regionId),anchor,visualState:currentVisualState(settlement),layoutClass:m?.layoutClass||'UNRESOLVED',populationBand:m?.populationBand||'UNKNOWN',urbanFamily:u?.family||'UNRESOLVED',urbanPhase:u?.phase||'UNRESOLVED',population:Math.max(0,int(settlement.population)),institutionIds:inst.map(x=>text(x.institutionId||x.polityId)).filter(Boolean).sort(),isolationRiskPpm:r?.isolationRiskPpm??null,criticalIncidentRouteIds:arr(r?.criticalIncidentRouteIds).map(text).sort(),evidenceComplete:u?.evidenceComplete!==false&&advanced.evidenceComplete!==false,authority:AUTHORITY.PRESENTATION_ONLY,sourceAuthority:sourceAuthority(settlement),physicalGeometryClaim:false},counter);
    for(const d of arr(m?.districts).slice(0,EMBODIMENT_LIMITS.districtsPerSettlement)){boundPush(commands,{kind:'DISTRICT_EMBODIMENT',sourceSettlementId:sid,sourceDistrictId:text(d.districtId),districtKind:text(d.kind),weightPpm:clamp(d.weightPpm),x:clamp(Math.round((anchor.x+(Number(d.placement?.u||.5)-.5)*.18)*1000000),0,1000000)/1000000,y:clamp(Math.round((anchor.y+(Number(d.placement?.v||.5)-.5)*.18)*1000000),0,1000000)/1000000,authority:AUTHORITY.PRESENTATION_ONLY,physicalGeometryClaim:false},counter)}
    for(const layer of arr(u?.evidenceLayers).slice(0,EMBODIMENT_LIMITS.historyLayersPerSettlement)){boundPush(commands,{kind:'HISTORICAL_STATE_EMBODIMENT',sourceSettlementId:sid,sourceLayerId:text(layer.layerId),layerKind:text(layer.kind),sourceClass:text(layer.sourceClass),sourceIds:arr(layer.sourceIds).map(text).sort(),epoch:layer.epoch??null,severityPpm:clamp(layer.severityPpm||0),x:anchor.x,y:anchor.y,authority:AUTHORITY.PRESENTATION_ONLY,canonicalHistoryClaim:false,physicalArchaeologyClaim:false},counter)}
    const regionalResources=resources.filter(x=>text(x.regionId)===text(settlement.regionId)).slice(0,EMBODIMENT_LIMITS.resourceLinksPerSettlement);for(const resource of regionalResources){const key=sid+'|'+text(resource.resourceId);if(selectedResourceLinks.has(key))continue;selectedResourceLinks.add(key);const salt=text(resource.resourceId);boundPush(commands,{kind:'RESOURCE_RELATIONSHIP_EMBODIMENT',sourceSettlementId:sid,sourceResourceId:text(resource.resourceId),resourceClass:text(resource.resourceClass||'UNKNOWN'),good:text(resource.good||resource.transformsTo||'UNKNOWN'),amountUnits:Math.max(0,int(resource.amountUnits||0)),availabilityPpm:clamp(resource.availabilityPpm||0),relationship:'SAME_MODELED_REGION_ACCESS',from:anchor,to:freeze({x:clamp(Math.round((anchor.x+(unit(salt,'resource-x')/1000000-.5)*.24)*1000000),0,1000000)/1000000,y:clamp(Math.round((anchor.y+(unit(salt,'resource-y')/1000000-.5)*.24)*1000000),0,1000000)/1000000,authority:AUTHORITY.PRESENTATION_ONLY,physicalPositionClaim:false}),authority:AUTHORITY.PRESENTATION_ONLY,sourceAuthority:sourceAuthority(resource),physicalResourceGeometryClaim:false,physicalPathClaim:false},counter)}
  }
  for(const route of productionRoutes){const from=text(route.from),to=text(route.to);if(!visibleIds.has(from)&&!visibleIds.has(to))continue;selectedRouteIds.add(text(route.edgeId));const rr=arr(advanced.resilience.routes).find(x=>text(x.edgeId)===text(route.edgeId))||{};boundPush(commands,{kind:'ROUTE_NETWORK_EMBODIMENT',sourceEdgeId:text(route.edgeId),fromSettlementId:from,toSettlementId:to,from:anchors.get(from)||presentationAnchor(from),to:anchors.get(to)||presentationAnchor(to),operational:route.operational===true,routingEligible:route.routingEligible===true,disableReason:route.disableReason||null,capacityUnits:Math.max(0,int(route.capacityUnits||0)),usedUnits:Math.max(0,int(route.usedUnits||0)),remainingUnits:Math.max(0,int(route.remainingUnits||0)),conditionPpm:clamp(route.conditionPpm||0),degradationPpm:clamp(route.degradationPpm||0),criticalityPpm:clamp(rr.criticalityPpm||0),bridgeLike:rr.bridgeLike===true,alternatePathAvailable:rr.alternatePathAvailable===true,sourceInfrastructureIds:arr(route.sourceInfrastructureIds).map(text).sort(),evidenceClass:text(route.evidenceClass||'UNKNOWN'),authority:AUTHORITY.PRESENTATION_ONLY,modelAuthority:AUTHORITY.MODEL_DERIVED_SIMULATION,physicalPathClaim:false,flowSubstitutionClaim:false},counter)}
  for(const flow of arr(advanced.production.flows)){const from=text(flow.fromSettlementId),to=text(flow.toSettlementId);if(!visibleIds.has(from)&&!visibleIds.has(to))continue;boundPush(commands,{kind:'PRODUCTION_FLOW_EMBODIMENT',sourceFlowId:text(flow.flowId),good:text(flow.good),amountUnits:Math.max(0,int(flow.amountUnits||0)),fromSettlementId:from,toSettlementId:to,from:anchors.get(from)||presentationAnchor(from),to:anchors.get(to)||presentationAnchor(to),pathEdgeIds:arr(flow.pathEdgeIds).map(text),hopCount:Math.max(0,int(flow.hopCount||0)),routingPhase:text(flow.routingPhase||'UNKNOWN'),authority:AUTHORITY.PRESENTATION_ONLY,modelAuthority:AUTHORITY.MODEL_DERIVED_SIMULATION,physicalPathClaim:false},counter)}
  for(const asset of allInfrastructure){const sid=text(asset.settlementId),from=text(asset.fromSettlementId),to=text(asset.toSettlementId);if(!(visibleIds.has(sid)||visibleIds.has(from)||visibleIds.has(to)))continue;const id=text(asset.infrastructureId);if(selectedInfrastructure.has(id))continue;selectedInfrastructure.add(id);const fromAnchor=anchors.get(from)||anchors.get(sid)||null,toAnchor=anchors.get(to)||anchors.get(sid)||fromAnchor;boundPush(commands,{kind:'INFRASTRUCTURE_EMBODIMENT',sourceInfrastructureId:id,infrastructureKind:text(asset.kind||'UNKNOWN'),visualState:infrastructureVisualState(asset),modeledStatus:text(asset.status||'UNKNOWN').toUpperCase(),conditionPpm:Number.isFinite(Number(asset.conditionPpm))?clamp(asset.conditionPpm):null,fromSettlementId:from||null,toSettlementId:to||null,settlementId:sid||null,from:fromAnchor,to:toAnchor,builtEpoch:asset.builtEpoch??null,lastActiveEpoch:asset.lastActiveEpoch??null,authority:AUTHORITY.PRESENTATION_ONLY,sourceAuthority:sourceAuthority(asset),physicalGeometryClaim:false,physicalPathClaim:false},counter)}
  const commandKinds=[...new Set(commands.map(x=>x.kind))].sort();return freeze({contract:EMBODIMENT_CONTRACT,version:VERSION,status:commands.length?'PROJECTED':'NO_SUPPORTED_EMBODIMENT',settlementScope:settlementId?text(settlementId):null,commands,commandCount:commands.length,commandKinds,operations:counter.count,limits:EMBODIMENT_LIMITS,evidenceComplete:advanced.evidenceComplete!==false,authority:AUTHORITY.PRESENTATION_ONLY,modelAuthority:AUTHORITY.MODEL_DERIVED_SIMULATION,bounded:true,noLegacyFallback:true,legacyCityRenderPlanUsed:false,requiresAdvancedComposition:true,requiresV2x07PlacementReconciliation:true,requiresConvergenceOwnerComposition:true,rendererMutationPerformed:false,sharedSceneMutationPerformed:false,persistenceMutationPerformed:false,claims:freeze({physicalCityGeometryClaim:false,physicalTransportGeometryClaim:false,physicalResourceGeometryClaim:false,canonicalHistoryClaim:false,empiricalForecastClaim:false,persistentPersonIdentityClaim:false,deterministicPresentationAnchors:true}),sourceContracts:freeze({advanced:tSafe(advanced.contract),production:tSafe(advanced.production?.contract),urban:tSafe(advanced.urban?.contract),resilience:tSafe(advanced.resilience?.contract)}),consumerHook:freeze({runtimeExport:'OFU.v2x09CivilizationEconomyCity.civilizationEmbodimentPacket',centralAction:'compose packet commands into Living scene through additive V2 rendering packet seam',forbiddenOwnership:['selection','semanticScale','travelDistance','cameraSpatialFrame','sceneComposition','primaryRenderer','inputRouter','persistenceReplay']}),limitations:LIMITATIONS});
}
function tSafe(v){return text(v||'');}

function inspector(state,{settlementId=null}={}){
  if(!validateCivilization(state))return freeze({supported:false,reason:'NO_MODELED_CIVILIZATION',authority:AUTHORITY.DERIVED,limitations:LIMITATIONS});
  const s=settlementId?arr(state.settlements).find(x=>x.settlementId===settlementId):null,tech=technologyProfile(state),inst=institutionProfile(state),morph=cityMorphology(state),selectedMorph=s?morph.settlements.find(x=>x.settlementId===settlementId):null;
  return freeze({supported:true,scope:settlementId?'SETTLEMENT':'CIVILIZATION',settlementId,technologyPrerequisites:tech,institutions:settlementId?inst.institutions.filter(x=>x.settlementIds.includes(settlementId)):inst.institutions,morphology:selectedMorph||null,embodiment:freeze({contract:EMBODIMENT_CONTRACT,runtimeExport:'OFU.v2x09CivilizationEconomyCity.civilizationEmbodimentPacket',requiresAdvancedComposition:true,noLegacyFallback:true,requiresConvergenceOwnerComposition:true,authority:AUTHORITY.PRESENTATION_ONLY}),uncertainty:freeze({authorityBoundary:'MODEL_DERIVED_SIMULATION_PLUS_PRESENTATION_ONLY',limitations:LIMITATIONS,scenarioProbabilityClaim:false,empiricalForecastClaim:false,canonicalHistoryClaim:false}),authority:AUTHORITY.DERIVED});
}

O.v2x09CivilizationMorphology=Object.freeze({EMBODIMENT_CONTRACT,EMBODIMENT_LIMITS,cityMorphology,cityRenderPlan,civilizationEmbodimentPacket,inspector});
})(typeof globalThis!=='undefined'?globalThis:this);
