import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {loadComponents,planComponents} from '../../../tools/extensions/components.mjs';
import {loadConformance,validateCoverage} from '../../../tools/extensions/conformance.mjs';
import {load} from './runtime-helper.mjs';
import {attachWaveAProduct} from '../../../tools/extensions/wave-a-manifest.mjs';
let cases=0;const ok=(v,m)=>{assert.ok(v,m);cases++;};
const plan=loadComponents(),tests=loadConformance(),catalogs=plan.filter(c=>c.id.startsWith('px.providers.')).map(c=>JSON.parse(c.content));
validateCoverage(catalogs,tests);ok(true,'complete owned provider evidence graph');
const ids=plan.map(c=>c.id);ok(new Set(ids).size===ids.length,'component identity uniqueness');const claims=plan.flatMap(c=>c.provides);ok(new Set(claims).size===claims.length,'unique ownership of component capabilities');
const required=['v1.life.provider','v1.civilization.runtime','v1.convergence.world-context','v1.micro.pipeline','v1.exploration.living-runtime','v1.rendering.living-renderer','v1.product.living-universe'];for(const id of required)ok(ids.includes(id),'production graph includes '+id);
const descriptors=plan.map(({id,version,owner,kind,stage,placement,source,dependencies,authority,provenance,provides})=>({id,version,owner,kind,stage,placement,source,dependencies,authority,provenance,provides}));
assert.throws(()=>planComponents([...descriptors,descriptors[0]]),/duplicate|collision/);cases++;
const hash=p=>crypto.createHash('sha256').update(JSON.stringify(p.map(c=>({id:c.id,hash:c.sourceSha256,deps:c.dependencies})))).digest('hex');ok(hash(planComponents([...descriptors].reverse()))===hash(plan),'input fragment order does not alter sealed build order');
const {O}=load(),seal=O.pxProduct.registry.snapshot();ok(seal.sealed&&seal.bindingsSealed,'actual runtime registry metadata and implementations are sealed');ok(seal.entries===seal.bound.length,'no detached unbound providers');
ok(catalogs.every(c=>c.canonicalAdmissions.length===0),'no model provider self-promotes canonical authority');
for(const source of ['src/kernel/p2-canonical.js','src/temporal/p4-temporal.js','src/domains/biosphere/p6-canonical.js'])ok(fs.existsSync(source),'frozen authority root remains in assembly');
for(const source of ['src/shaders/v1/world-shaders.js','src/rendering/v1/webgl2-world.js','src/rendering/v1/living-renderer.js'])vm.runInThisContext(fs.readFileSync(source,'utf8'),{filename:source});
const historical={visualUniverse:{version:'legacy-visual'},planetPresentation:{version:'legacy-planet'},surfacePresentation:{version:'legacy-surface'}};
const product={...historical,productSourceComposition:'frozen+additive',px:{registryManifest:{providers:catalogs.flatMap(c=>c.providers)},registryDigest:seal.manifestDigest}};
attachWaveAProduct(product,plan);
ok(product.px.scope==='FULL_V1_WAVE_A_PRODUCT','production scope is the actual v1 composition');
ok(product.px.registryDigest===seal.manifestDigest,'manifest does not rewrite sealed registry authority');
ok(product.legacyPresentation.primary===false,'legacy presentation is explicitly non-primary');
for(const field of Object.keys(historical))ok(product.legacyPresentation[field]===historical[field],'historical descriptor preserved '+field);
assert.deepEqual(Object.keys(product.visualUniverse.primaryScenePolicy),Array.from(O.v1LivingRuntime.stages));cases++;
ok(Object.values(product.visualUniverse.primaryScenePolicy).every(v=>v===O.v1LivingRenderer.VERSION),'every actual runtime stage has its real foreground renderer');
ok(product.planetPresentation.globeBackend===O.v1WorldWebGL2.VERSION,'globe backend identity is executable');
ok(product.visualUniverse.primarySceneProvider==='v1.scene.living-world','manifest binds actual composed scene');
ok(product.worldConvergence.modelHistoryCommitsCanonicalEvents===false&&product.worldConvergence.canonicalP6Changed===false,'authority separation remains explicit');
assert.throws(()=>attachWaveAProduct({...product},plan.filter(c=>c.id!=='v1.rendering.living-renderer')),/missing/);cases++;
assert.throws(()=>attachWaveAProduct({...product,px:{registryManifest:{providers:[]}}},plan),/sealed scene provider/);cases++;
console.log(JSON.stringify({status:'PASS',suite:'wave-a-graph-seal',cases,components:plan.length,providers:seal.entries,composition:hash(plan),registryDigest:seal.manifestDigest,canonicalAdmissions:0}));
