import { addSafe, asciiCompare, assertRecord, boundedArray, identifier, mulDivFloor, nonNegativeInt, ppm, sumSafe, uniqueIds } from '../reference/bounded-math.mjs';
export const MATTER_LIMITS=Object.freeze({species:64,reactions:128,compartments:32,transportEdges:128,elementsPerSpecies:16,maxAmount:10_000_000_000});
export const MATTER_AUTHORITY='RESEARCH_ONLY_MODEL_DERIVED_SIMULATION';

function composition(s){assertRecord(s.composition,`${s.id}.composition`);const e=Object.entries(s.composition);boundedArray(e,'composition',MATTER_LIMITS.elementsPerSpecies);for(const[k,v]of e){if(!/^[A-Z][a-z]?$/.test(k))throw new Error(`invalid element ${k}`);nonNegativeInt(v,`composition.${k}`,1_000_000);}return s.composition;}
function aggregateTerms(terms,label){boundedArray(terms,label,16);const out=new Map();for(const t of terms){assertRecord(t,`${label} term`);const speciesId=identifier(t.speciesId,`${label}.speciesId`),c=nonNegativeInt(t.coefficient,'coefficient',1_000_000);if(!c)throw new Error('zero coefficient');out.set(speciesId,addSafe(out.get(speciesId)??0,c,`${label}.${speciesId}`));}return out;}
export function validateReactionNetwork(n){assertRecord(n,'network');boundedArray(n.species,'species',MATTER_LIMITS.species);boundedArray(n.reactions,'reactions',MATTER_LIMITS.reactions);const ids=uniqueIds(n.species,'species');uniqueIds(n.reactions,'reactions');const byId=new Map(n.species.map(s=>[s.id,s]));for(const s of n.species)composition(s);for(const r of n.reactions){const reactants=aggregateTerms(r.reactants,'reactants'),products=aggregateTerms(r.products,'products');if(!reactants.size||!products.size)throw new Error(`reaction ${r.id} requires non-empty reactants and products`);ppm(r.extentFractionPpm);const b=new Map(),apply=(terms,sign)=>{for(const[speciesId,c]of terms){if(!ids.has(speciesId))throw new Error('unknown species');for(const[e,k]of Object.entries(byId.get(speciesId).composition)){const term=sign*c*k;if(!Number.isSafeInteger(term))throw new RangeError(`element balance overflow at ${e}`);b.set(e,addSafe(b.get(e)??0,term,`element.${e}`));}}};apply(reactants,-1);apply(products,1);for(const[e,v]of b)if(v!==0)throw new Error(`reaction ${r.id} is element-unbalanced at ${e}`);}return true;}
export function stepReactionNetwork(n,amounts){validateReactionNetwork(n);assertRecord(amounts,'amounts');const stock=new Map(n.species.map(s=>[s.id,nonNegativeInt(amounts[s.id]??0,`amounts.${s.id}`,MATTER_LIMITS.maxAmount)])),evidence=[];for(const r of n.reactions){const reactants=aggregateTerms(r.reactants,'reactants'),products=aggregateTerms(r.products,'products');let maxExtent=MATTER_LIMITS.maxAmount;for(const[speciesId,coefficient]of reactants)maxExtent=Math.min(maxExtent,Math.floor(stock.get(speciesId)/coefficient));const extent=mulDivFloor(maxExtent,r.extentFractionPpm,1_000_000,`extent.${r.id}`);for(const[speciesId,coefficient]of reactants){const consumed=extent*coefficient;if(!Number.isSafeInteger(consumed))throw new RangeError('reaction consumption overflow');const next=stock.get(speciesId)-consumed;if(next<0)throw new Error('reaction produced negative stock');stock.set(speciesId,next);}for(const[speciesId,coefficient]of products){const produced=extent*coefficient;if(!Number.isSafeInteger(produced))throw new RangeError('reaction production overflow');const next=stock.get(speciesId)+produced;if(!Number.isSafeInteger(next)||next>MATTER_LIMITS.maxAmount)throw new RangeError('amount cap');stock.set(speciesId,next);}evidence.push(Object.freeze({reactionId:r.id,extent,operatorOrder:'DECLARED_ARRAY_ORDER_SEQUENTIAL_SPLITTING'}));}return Object.freeze({authority:MATTER_AUTHORITY,amounts:Object.freeze(Object.fromEntries(stock)),evidence:Object.freeze(evidence),kineticClaim:'PER_TICK_FRACTION_IS_SCENARIO_PARAMETER_UNLESS_SOURCE_ADAPTER_SUPPLIES_UNITS_AND_VALIDITY',operatorSemantics:'REACTIONS_APPLY_SEQUENTIALLY_IN_DECLARED_ARRAY_ORDER',permutationInvariantClaim:false,dynamicsClaim:false});}

function allocateSimultaneous(available, requests, label){
  const ordered=[...requests].sort((a,b)=>asciiCompare(a.id,b.id)),total=sumSafe(ordered.map(r=>r.request),`${label}.requestTotal`),out=new Map();
  if(total<=available){for(const r of ordered)out.set(r.id,r.request);return out;}
  let used=0;
  for(const r of ordered){const v=mulDivFloor(available,r.request,total,`${label}.${r.id}`);out.set(r.id,v);used=addSafe(used,v,`${label}.used`);}
  let residual=available-used;
  for(const r of ordered){if(residual===0)break;const room=r.request-out.get(r.id);if(room>0){out.set(r.id,out.get(r.id)+1);residual-=1;}}
  return out;
}

export function stepTransport(state){
  assertRecord(state,'state');boundedArray(state.compartments,'compartments',MATTER_LIMITS.compartments);boundedArray(state.edges,'edges',MATTER_LIMITS.transportEdges);
  const compartmentIds=uniqueIds(state.compartments,'compartments');uniqueIds(state.edges,'transport edges');
  const opening=new Map();
  for(const c of state.compartments){assertRecord(c.amounts,'compartment.amounts');const values=new Map();for(const [speciesId,value] of Object.entries(c.amounts)){identifier(speciesId,'transport speciesId');values.set(speciesId,nonNegativeInt(value,`amount.${c.id}.${speciesId}`,MATTER_LIMITS.maxAmount));}opening.set(c.id,values);}
  const groups=new Map(),edgeMeta=new Map();
  for(const e of state.edges){if(!compartmentIds.has(e.from)||!compartmentIds.has(e.to)||e.from===e.to)throw new Error('invalid transport compartment transition');const speciesId=identifier(e.speciesId,'edge.speciesId'),capacity=nonNegativeInt(e.capacity,'capacity',MATTER_LIMITS.maxAmount),transferPpm=ppm(e.transferPpm),available=opening.get(e.from).get(speciesId)??0,request=Math.min(capacity,mulDivFloor(available,transferPpm,1_000_000,`transportRequest.${e.id}`)),key=`${e.from}\u0000${speciesId}`;if(!groups.has(key))groups.set(key,{from:e.from,speciesId,available,requests:[]});groups.get(key).requests.push({id:e.id,request});edgeMeta.set(e.id,{...e,speciesId,capacity,transferPpm,request});}
  const allocated=new Map();
  for(const [key,group] of groups){const a=allocateSimultaneous(group.available,group.requests,`transport.${key}`);for(const [id,value] of a)allocated.set(id,value);}
  const delta=new Map(state.compartments.map(c=>[c.id,new Map()])),transfers=[];
  const addDelta=(compartmentId,speciesId,value)=>{const m=delta.get(compartmentId);m.set(speciesId,addSafe(m.get(speciesId)??0,value,`transportDelta.${compartmentId}.${speciesId}`));};
  for(const id of [...edgeMeta.keys()].sort(asciiCompare)){const e=edgeMeta.get(id),transfer=allocated.get(id)??0;addDelta(e.from,e.speciesId,-transfer);addDelta(e.to,e.speciesId,transfer);transfers.push(Object.freeze({edgeId:id,from:e.from,to:e.to,speciesId:e.speciesId,requested:e.request,transferred:transfer,sourceCompetitionRejected:e.request-transfer}));}
  const closing=new Map();
  for(const c of state.compartments){const species=new Set([...opening.get(c.id).keys(),...delta.get(c.id).keys()]),m=new Map();for(const speciesId of species){const value=addSafe(opening.get(c.id).get(speciesId)??0,delta.get(c.id).get(speciesId)??0,`closingTransport.${c.id}.${speciesId}`);nonNegativeInt(value,`closingTransport.${c.id}.${speciesId}`,MATTER_LIMITS.maxAmount);m.set(speciesId,value);}closing.set(c.id,m);}
  const speciesIds=new Set();for(const m of opening.values())for(const id of m.keys())speciesIds.add(id);for(const e of edgeMeta.values())speciesIds.add(e.speciesId);
  const conservation={};for(const speciesId of [...speciesIds].sort(asciiCompare)){const open=sumSafe(state.compartments.map(c=>opening.get(c.id).get(speciesId)??0),`opening.${speciesId}`),close=sumSafe(state.compartments.map(c=>closing.get(c.id).get(speciesId)??0),`closing.${speciesId}`);if(open!==close)throw new Error(`transport conservation failure for ${speciesId}`);conservation[speciesId]=Object.freeze({opening:open,closing:close});}
  return Object.freeze({authority:MATTER_AUTHORITY,compartments:Object.freeze(state.compartments.map(c=>Object.freeze({id:c.id,amounts:Object.freeze(Object.fromEntries(closing.get(c.id)))}))),transfers:Object.freeze(transfers),evidence:Object.freeze({conservation:Object.freeze(conservation)}),conservationClaim:'EXACT_INTEGER_TRANSPORT_CONSERVATION_FOR_DECLARED_EDGES',operatorSemantics:'SIMULTANEOUS_OPENING_STATE_ALLOCATION_PER_SOURCE_AND_SPECIES',permutationInvariantClaim:true,dynamicsClaim:false});
}
