import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
const sourceSha=process.env.OFU_SOURCE_SHA;if(!sourceSha)throw new Error('OFU_SOURCE_SHA required');
const browser=await chromium.launch({headless:true});const requests=[],errors=[];
async function run(viewport,{mobile=false}={}){const context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,reducedMotion:'reduce'});const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e.message||e)));page.on('request',r=>{if(!/^(file|blob|data):/.test(r.url()))requests.push(r.url())});await page.goto(pathToFileURL(path.resolve('dist/One_File_Universe.html')).href,{waitUntil:'load'});await page.waitForFunction(()=>OFU?.v1LivingProduct?.snapshot?.().initialized&&OFU?.v2x14ProductExperience?.instance?.(),null,{timeout:30000});const initial=await page.evaluate(()=>{const x=OFU.v2x14ProductExperience.instance().snapshot(),v=document.getElementById('living-view'),current=[...document.querySelectorAll('#living-rail [aria-current="step"]')].map(n=>n.dataset.livingScale),pressed=[...document.querySelectorAll('#living-rail [aria-pressed="true"]')].map(n=>n.dataset.livingScale);return{x,role:v.getAttribute('role'),describedBy:v.getAttribute('aria-describedby'),skip:!!document.getElementById('v2x14-skip-link'),current,pressed}});assert.equal(initial.x.authority,'PRESENTATION_ONLY');assert.equal(initial.x.routesNativeInput,false);assert.equal(initial.role,'region');assert(initial.describedBy.includes('v2x14-live-location'));assert.equal(initial.skip,true);assert.equal(initial.current.length,1);assert.equal(initial.pressed.length,1,'V2X14 must preserve the primary Living pressed scale state');assert.equal(initial.pressed[0],initial.current[0],'additive aria-current must agree with primary Living aria-pressed state');
await page.locator('#living-view').focus();await page.keyboard.press('Home');await page.waitForFunction(()=>OFU.v1LivingProduct.runtime.snapshot().stage==='UNIVERSE');await page.waitForTimeout(30);const universe=await page.evaluate(()=>{const x=OFU.v2x14ProductExperience.instance().snapshot(),current=[...document.querySelectorAll('#living-rail [aria-current="step"]')].map(n=>n.dataset.livingScale),pressed=[...document.querySelectorAll('#living-rail [aria-pressed="true"]')].map(n=>n.dataset.livingScale);return{x,current,pressed}});assert.equal(universe.x.stage,'UNIVERSE');assert.equal(universe.x.breadcrumbs.filter(x=>x.current).length,1);assert.deepEqual(universe.current,['UNIVERSE']);assert.deepEqual(universe.pressed,['UNIVERSE'],'presentation-only Product Experience must not erase primary Living scale semantics after navigation');
const geometry=await page.evaluate(()=>{const v=document.getElementById('living-view').getBoundingClientRect(),ctx=document.getElementById('v2x14-context').getBoundingClientRect();return{innerWidth,scrollWidth:document.documentElement.scrollWidth,viewport:{left:v.left,right:v.right,width:v.width,height:v.height},contextHeight:ctx.height};});assert(geometry.scrollWidth<=geometry.innerWidth+2);assert(geometry.viewport.left>=-1&&geometry.viewport.right<=geometry.innerWidth+1&&geometry.viewport.width>0&&geometry.viewport.height>0);if(mobile)assert(geometry.contextHeight>0);await context.close();return{viewport,mobile,method:mobile?'BROWSER_MOBILE_EMULATION':'DESKTOP_BROWSER',physicalDeviceVerified:false};}
const desktop=await run({width:1365,height:900});const mobile=await run({width:390,height:844},{mobile:true});assert.equal(errors.length,0,errors.join('\n'));assert.equal(requests.length,0,requests.join('\n'));console.log(JSON.stringify({schema:'ofu-v2x14-browser-evidence-1',status:'PASS',exactSourceSha:sourceSha,authority:'PRESENTATION_ONLY',directFile:true,zeroMandatoryNetwork:true,keyboardPrimaryJourney:true,screenReaderSemantics:true,preservesPrimaryScaleSemantics:true,reducedMotion:true,desktop,mobile,physicalDeviceEvidence:'NOT_VERIFIED'}));await browser.close();
