import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ROOT=new URL('../../',import.meta.url),read=p=>fs.readFileSync(new URL(p,ROOT),'utf8');
const sandbox={console,Math,Number,Object,Array,Set,Map,Promise,JSON,setTimeout:()=>1,clearTimeout:()=>{},setInterval:()=>1,clearInterval:()=>{}};sandbox.globalThis=sandbox;vm.createContext(sandbox);
for(const p of ['src/product/v2x14/product-experience.js','src/product/v2x14/discovery.js','src/audio/v2x14/living-audio-context.js','src/audio/v2x14/audio-controller.js'])new vm.Script(read(p),{filename:p});
vm.runInContext(read('src/product/v2x14/product-experience.js'),sandbox,{filename:'product-experience.js'});vm.runInContext(read('src/product/v2x14/discovery.js'),sandbox,{filename:'discovery.js'});vm.runInContext(read('src/audio/v2x14/living-audio-context.js'),sandbox,{filename:'living-audio-context.js'});
const ux=sandbox.OFU.v2x14ProductExperience,map=sandbox.OFU.v2x14LivingAudioContext,discovery=sandbox.OFU.v2x14Discovery;
assert.equal(ux.AUTHORITY,'PRESENTATION_ONLY');assert.equal(map.AUTHORITY,'PRESENTATION_ONLY');assert.equal(discovery.AUTHORITY,'PRESENTATION_ONLY');
const base={stage:'HUMAN',system:{canonicalId:'sys-123456789'},world:{planetIdentity:'planet-123456789',planetology:{atmosphere:{pressureProxyPpm:750000},climate:{precipitationPotentialPpm:200000}},biology:{occupancy:{biosphereEstablished:true}},civilization:{state:'MODELED_CIVILIZATION'}},point:{locationIdentity:'loc-123456789',latMicroDeg:1000000,lonMicroDeg:2000000},selectedObjectId:'obj-123456789',local:{surface:{climate:{}},life:{local:{populations:[{id:1}]}},objects:[{entityId:'obj-123456789',kind:'SETTLEMENT',label:'Site'}]}};
const p=ux.derive(base);assert.equal(p.routesNativeInput,false);assert.equal(p.mutatesCanonicalState,false);assert.equal(p.canonicalSelectionAuthority,false);assert.equal(p.scaleAuthority,false);assert.equal(p.cameraAuthority,false);assert.match(p.currentLocation,/Human scale/);assert.match(p.selection,/Site/);assert.equal(p.breadcrumbs.filter(x=>x.current).length,1);
const a=map.fromLiving(base);assert.equal(a.medium.supportsSound,true);assert.equal(a.life.present,true);assert.equal(a.civilization.present,true);assert.equal(a.claims.scientificEvidence,false);
const thin=map.fromLiving({...base,world:{...base.world,planetology:{atmosphere:{pressureProxyPpm:5000}}}});assert.equal(thin.medium.supportsSound,false);
const vacuum=map.fromLiving({stage:'ORBIT',world:{planetology:{atmosphere:{pressureProxyPpm:750000}}}});assert.equal(vacuum.medium.supportsSound,false);assert.equal(vacuum.medium.vacuum,true);assert.equal(vacuum.life.present,false);assert.equal(vacuum.civilization.present,false);
const unknown=map.fromLiving({stage:'HUMAN'});assert.equal(unknown.medium.supportsSound,false);assert.equal(unknown.medium.knownPressure,false);assert.equal(unknown.life.present,false);assert.equal(unknown.civilization.present,false);
let searchArgs=null,entered=null;const rows=[{planetIdentity:'p-1',canonicalKey:{planet:1},biologyState:'MODELED_BIOSPHERE'}];const fakeRuntime={snapshot:()=>({system:{canonicalId:'sys-1'}}),searchWorlds(args){searchArgs=args;return{candidates:rows,worldsEvaluated:7,nextCursor:'next'};},enterKey(key){entered=key;return 'travelled';}};const d=discovery.create({runtime:fakeRuntime});d.reset('BIOSPHERE');await d.page({limit:99});const ds=d.snapshot();assert.deepEqual(searchArgs,{goal:'BIOSPHERE',cursor:null,maxWorlds:12,maxSystemQueries:128,limit:6});assert.equal(ds.globalEnumeration,false);assert.equal(ds.networkRequired,false);assert.equal(ds.results.length,1);assert.equal(ds.results.length<=ds.bounds.rows,true);assert.equal(d.select('p-1'),'travelled');assert.deepEqual(entered,{planet:1});
for(const descriptor of ['config/components/v2x-14-product-experience.json','config/components/v2x-14-systemic-audio.json']){const parsed=JSON.parse(read(descriptor));assert.equal(parsed.schema,'ofu-components-1');for(const c of parsed.components){assert.equal(c.authority,'PRESENTATION_ONLY');assert(!c.source.startsWith('src/bootstrap/'));}}
const sourceText=['src/product/v2x14/product-experience.js','src/product/v2x14/discovery.js','src/audio/v2x14/living-audio-context.js','src/audio/v2x14/audio-controller.js'].map(read).join('\n');assert(!/fetch\s*\(|XMLHttpRequest|WebSocket|EventSource/.test(sourceText),'no mandatory network API allowed');assert(!/waveIVInputRouter\s*=|v1LivingRuntime\s*=|selectedObjectId\s*=/.test(sourceText),'lane must not create shared runtime authority');
console.log(JSON.stringify({schema:'ofu-v2x14-contract-test-2',status:'PASS',authority:'PRESENTATION_ONLY',nativeInputAuthority:false,unknownStaysUnknown:true,boundedDiscovery:true,networkRequired:false,physicalDeviceEvidence:'NOT_VERIFIED'}));
