(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.v2x11GameplayContracts;
if(!C)throw new Error('V2X-11 causal engine requires gameplay contracts');
const VERSION='ofu-v2x-11-cross-domain-causal-engine-1',adapters=new Map(),issuedPlans=new WeakSet(),issuedExecutions=new WeakSet(),planWitnesses=new WeakMap(),executionWitnesses=new WeakMap();
function fail(message){throw new Error('OFU V2X-11 causal engine: '+message)}
function witness(tag,value){return C.digest(tag,value)}
function registerAdapter(input){C.exact(input,['id','version','domain','authority','plan','apply'],[],'domain adapter');const domain=C.text(input.domain,'adapter.domain',96),id=C.text(input.id,'adapter.id',160),version=C.text(input.version,'adapter.version',64),authority=C.text(input.authority,'adapter.authority',64);if(authority!==C.AUTHORITY&&authority!=='DERIVED')fail('adapter authority mismatch');if(typeof input.plan!=='function'||typeof input.apply!=='function')fail('adapter functions required');if(adapters.has(domain))fail('duplicate domain adapter '+domain);const adapter=Object.freeze({id,version,domain,authority,plan:input.plan,apply:input.apply});adapters.set(domain,adapter);return adapter}
function unregisterAdapter(domain){domain=C.text(domain,'domain',96);return adapters.delete(domain)}
function adapterSnapshot(){return Object.freeze([...adapters.values()].map(a=>Object.freeze({id:a.id,version:a.version,domain:a.domain,authority:a.authority})).sort((a,b)=>C.compareText(a.domain,b.domain)))}
function validateEffects(effects){if(!Array.isArray(effects)||effects.length>C.LIMITS.dagNodes)fail('effect DAG node bound');const byId=new Map();let edges=0;for(const e of effects){if(!e||typeof e!=='object'||typeof e.effectId!=='string')fail('invalid effect');const rebuilt=C.effect({domain:e.domain,kind:e.kind,targetId:e.targetId,dependsOn:e.dependsOn,authority:e.authority,payload:e.payload});if(rebuilt.effectId!==e.effectId)fail('effect digest mismatch');if(byId.has(e.effectId))fail('duplicate effect id');byId.set(e.effectId,e);edges+=e.dependsOn.length;if(edges>C.LIMITS.dagEdges)fail('effect DAG edge bound')}for(const e of effects)for(const dep of e.dependsOn)if(!byId.has(dep))fail('effect dependency outside plan '+dep);const incoming=new Map(effects.map(e=>[e.effectId,e.dependsOn.length])),children=new Map(effects.map(e=>[e.effectId,[]]));for(const e of effects)for(const dep of e.dependsOn)children.get(dep).push(e.effectId);for(const list of children.values())list.sort(C.compareText);const ready=effects.filter(e=>incoming.get(e.effectId)===0).map(e=>e.effectId).sort(C.compareText),order=[];while(ready.length){const id=ready.shift();order.push(byId.get(id));for(const child of children.get(id)){incoming.set(child,incoming.get(child)-1);if(incoming.get(child)===0){ready.push(child);ready.sort(C.compareText)}}}if(order.length!==effects.length)fail('causal dependency cycle');return Object.freeze(order)}
function buildPlan(input){C.exact(input,['proposal','context'],[],'build plan input');const proposal=C.validateProposal(input.proposal),context=C.safe(input.context,'causal context',262144),routes=C.ROUTES[proposal.kind],effects=[],missing=[];for(const domain of routes){const adapter=adapters.get(domain);if(!adapter){missing.push(domain);continue}const planned=adapter.plan(proposal,Object.freeze({context,priorEffects:Object.freeze([...effects])}));if(!Array.isArray(planned))fail('adapter '+domain+' plan must return array');if(planned.length>C.LIMITS.effects)fail('adapter '+domain+' effect bound');for(const raw of planned){const e=C.effect({domain:raw.domain,kind:raw.kind,targetId:raw.targetId,dependsOn:raw.dependsOn,authority:raw.authority,payload:raw.payload});if(raw.effectId&&raw.effectId!==e.effectId)fail('adapter '+domain+' effect digest mismatch');if(e.domain!==domain)fail('adapter '+domain+' emitted foreign domain '+e.domain);effects.push(e);if(effects.length>C.LIMITS.dagNodes)fail('effect DAG node bound')}}const ordered=validateEffects(effects),plan=Object.freeze({contract:VERSION,version:'1.0.0',proposalId:proposal.proposalId,routes:Object.freeze([...routes]),missingDomains:Object.freeze(missing.sort(C.compareText)),effects:ordered,authority:C.AUTHORITY,canonicalMutation:false});issuedPlans.add(plan);planWitnesses.set(plan,witness('OFU-V2X11-PLAN-WITNESS-v1',plan));return plan}
function executePlan(input){C.exact(input,['proposal','plan','context'],[],'execute plan input');const proposal=C.validateProposal(input.proposal),plan=input.plan;if(!plan||!issuedPlans.has(plan))fail('plan was not issued by causal engine');if(planWitnesses.get(plan)!==witness('OFU-V2X11-PLAN-WITNESS-v1',plan))fail('issued plan was mutated');if(plan.contract!==VERSION||plan.proposalId!==proposal.proposalId||plan.canonicalMutation!==false)fail('plan contract mismatch');const ordered=validateEffects([...plan.effects]),context=C.safe(input.context,'execution context',262144),results=[],statusById=new Map();for(const effect of ordered){const blocked=effect.dependsOn.some(id=>statusById.get(id)!=='APPLIED');if(blocked){const r=Object.freeze({effectId:effect.effectId,domain:effect.domain,kind:effect.kind,status:'DEPENDENCY_BLOCKED',authority:effect.authority,payload:null,provenance:Object.freeze({proposalId:proposal.proposalId,dependsOn:effect.dependsOn})});results.push(r);statusById.set(effect.effectId,r.status);continue}const adapter=adapters.get(effect.domain);if(!adapter){const r=Object.freeze({effectId:effect.effectId,domain:effect.domain,kind:effect.kind,status:'UNSUPPORTED_DOMAIN_EFFECT',authority:effect.authority,payload:null,provenance:Object.freeze({proposalId:proposal.proposalId,dependsOn:effect.dependsOn})});results.push(r);statusById.set(effect.effectId,r.status);continue}const raw=adapter.apply(effect,Object.freeze({proposal,context,priorResults:Object.freeze([...results])}));if(!raw||typeof raw!=='object'||Array.isArray(raw))fail('adapter '+effect.domain+' apply result');const status=String(raw.status||'').toUpperCase();if(!['APPLIED','UNSUPPORTED_DOMAIN_EFFECT','DEPENDENCY_BLOCKED'].includes(status))fail('adapter '+effect.domain+' result status');const r=Object.freeze({effectId:effect.effectId,domain:effect.domain,kind:effect.kind,status,authority:effect.authority,payload:raw.payload===undefined?null:C.safe(raw.payload,'effect result payload'),provenance:Object.freeze({proposalId:proposal.proposalId,dependsOn:effect.dependsOn,adapterId:adapter.id,adapterVersion:adapter.version})});results.push(r);statusById.set(effect.effectId,status)}let status='APPLIED';if(plan.missingDomains.length||results.some(r=>r.status==='UNSUPPORTED_DOMAIN_EFFECT'))status='UNSUPPORTED_DOMAIN_EFFECT';else if(results.some(r=>r.status==='DEPENDENCY_BLOCKED'))status='DEPENDENCY_BLOCKED';const execution=Object.freeze({contract:VERSION,version:'1.0.0',proposalId:proposal.proposalId,status,missingDomains:plan.missingDomains,results:Object.freeze(results),authority:C.AUTHORITY,canonicalMutation:false});issuedExecutions.add(execution);executionWitnesses.set(execution,witness('OFU-V2X11-EXECUTION-WITNESS-v1',execution));return execution}
function validateExecution(execution,proposal){const p=C.validateProposal(proposal);if(!execution||!issuedExecutions.has(execution))fail('execution was not issued by causal engine');if(executionWitnesses.get(execution)!==witness('OFU-V2X11-EXECUTION-WITNESS-v1',execution))fail('issued execution was mutated');if(execution.contract!==VERSION||execution.version!=='1.0.0'||execution.proposalId!==p.proposalId||execution.authority!==C.AUTHORITY||execution.canonicalMutation!==false)fail('execution contract mismatch');return execution}
function orchestrate(input){const plan=buildPlan(input),execution=executePlan({proposal:input.proposal,plan,context:input.context});return Object.freeze({plan,execution})}
O.v2x11CausalEngine=Object.freeze({VERSION,registerAdapter,unregisterAdapter,adapterSnapshot,validateEffects,buildPlan,executePlan,validateExecution,orchestrate});
})(typeof globalThis!=='undefined'?globalThis:this);
