import {W1_AUTHORITY} from '../../contracts/w1-observation-contracts.js';
import {COMPARE_ENGINE_VERSION,COMPARE_RESULT_CONTRACT,COMPARE_STATE,createCompareDescriptor,finalizeCompareResult,normalizeCompareLimits,validateCompareDescriptor} from './compare-contracts.js';
import {fingerprintAlignment,identityAlignment,normalizeAtlas,requireAtlasEntry,scaleAlignment,sideProjection,timeAlignment} from './atlas-alignment.js';
import {validateWhyGraph} from './why-validation.js';
import {whyAlignment} from './why-divergence.js';

export {COMPARE_DEFAULT_LIMITS,COMPARE_DESCRIPTOR_CONTRACT,COMPARE_ENGINE_VERSION,COMPARE_RESULT_CONTRACT,COMPARE_STATE,createCompareDescriptor} from './compare-contracts.js';
function overallState(identity,time,scale,fingerprint,why){if(time.state===COMPARE_STATE.INCOMPARABLE||fingerprint.state===COMPARE_STATE.INCOMPARABLE||why.state===COMPARE_STATE.INCOMPARABLE)return COMPARE_STATE.INCOMPARABLE;const values=[identity.state,time.state,scale.state,fingerprint.state,why.state];if(values.every(value=>value===COMPARE_STATE.MATCHED))return COMPARE_STATE.MATCHED;if(values.some(value=>value===COMPARE_STATE.DIVERGENT))return COMPARE_STATE.DIVERGENT;return COMPARE_STATE.UNKNOWN;}
function incomparableReasons(...parts){return Object.freeze(parts.filter(part=>part.state===COMPARE_STATE.INCOMPARABLE).map(part=>part.reason).sort())}
function diffSummary(identity,time,scale,fingerprint,why){const edges=why.edges;return Object.freeze({identityDifferent:identity.state===COMPARE_STATE.DIVERGENT,governedTimeDifferent:time.state===COMPARE_STATE.DIVERGENT||time.state===COMPARE_STATE.INCOMPARABLE,scientificContextDifferent:fingerprint.state===COMPARE_STATE.DIVERGENT||fingerprint.state===COMPARE_STATE.INCOMPARABLE,causalRelationDifferences:edges?.causal.total??0,factualRelationDifferences:edges?.factual.total??0,authorityDifferences:edges?.authority.total??0,provenanceDifferences:edges?.provenance.total??0,knowledgeStatusDifferences:edges?.knowledge.total??0,uncertaintyDifferences:why.uncertainties?.differences.total??0,assumptionDifferences:why.assumptions?.differences.total??0,presentationOnlyDifferences:(scale.state===COMPARE_STATE.DIVERGENT?1:0)+(edges?.presentation.total??0),unknownEvidencePresent:why.state===COMPARE_STATE.UNKNOWN||fingerprint.state===COMPARE_STATE.UNKNOWN||time.state===COMPARE_STATE.UNKNOWN});}
export function compareAtlasEntries({atlas,descriptor=null,leftAtlasEntryId=null,rightAtlasEntryId=null,leftWhy=null,rightWhy=null,limits={}}={}){const source=normalizeAtlas(atlas),bounds=normalizeCompareLimits(limits),d=descriptor===null?createCompareDescriptor({leftAtlasEntryId,rightAtlasEntryId}):validateCompareDescriptor(descriptor);if(descriptor!==null&&(leftAtlasEntryId!==null||rightAtlasEntryId!==null))throw new Error('OFU Compare: provide descriptor or entry ids, not both');const leftEntry=requireAtlasEntry(source,d.left.atlasEntryId,'left'),rightEntry=requireAtlasEntry(source,d.right.atlasEntryId,'right'),leftObs=leftEntry.entry.observation,rightObs=rightEntry.entry.observation,lWhy=validateWhyGraph(leftWhy,'left',leftObs,bounds),rWhy=validateWhyGraph(rightWhy,'right',rightObs,bounds),identity=identityAlignment(leftObs,rightObs),time=timeAlignment(leftObs,rightObs),scale=scaleAlignment(leftObs,rightObs),fingerprint=fingerprintAlignment(leftObs,rightObs),why=whyAlignment(lWhy,rWhy,bounds.maxDifferenceItems),comparisonState=overallState(identity,time,scale,fingerprint,why);const payload=Object.freeze({schemaVersion:1,contract:COMPARE_RESULT_CONTRACT,engineVersion:COMPARE_ENGINE_VERSION,authority:W1_AUTHORITY.ANALYSIS_ONLY,descriptor:d,left:sideProjection(leftEntry),right:sideProjection(rightEntry),comparisonState,synchronized:Object.freeze({time:time.state===COMPARE_STATE.MATCHED,scale:scale.state===COMPARE_STATE.MATCHED}),alignment:Object.freeze({identity,time,scale,scientificFingerprint:fingerprint,scientificWhy:why}),differenceSummary:diffSummary(identity,time,scale,fingerprint,why),incomparableReasons:incomparableReasons(time,fingerprint,why),usage:Object.freeze({leftWhyNodes:lWhy?.nodes.length??0,rightWhyNodes:rWhy?.nodes.length??0,leftWhyEdges:lWhy?.edges.length??0,rightWhyEdges:rWhy?.edges.length??0,maxWhyNodesPerSide:bounds.maxWhyNodesPerSide,maxWhyEdgesPerSide:bounds.maxWhyEdgesPerSide,maxDifferenceItems:bounds.maxDifferenceItems,truncated:Boolean(why.edges&&Object.values(why.edges).some(item=>item.truncated)||why.assumptions?.differences.truncated||why.uncertainties?.differences.truncated)}),exactAtlasReferences:true,mutableWorldCopies:false,generatedCausalExplanation:false,scientificClaimsAdded:false,presentationDifferencesPromotedToScience:false,mutatesWorld:false,mutatesAtlas:false,mutatesSelection:false,mutatesCamera:false,networkRequired:false});return finalizeCompareResult(payload,bounds);}
export function createCompareWorkspace({atlas,limits={}}={}){const source=normalizeAtlas(atlas),bounds=normalizeCompareLimits(limits);return Object.freeze({contract:'ofu-prod-w2-compare-workspace-1',version:COMPARE_ENGINE_VERSION,authority:W1_AUTHORITY.ANALYSIS_ONLY,limits:bounds,createDescriptor:createCompareDescriptor,compare:input=>compareAtlasEntries({...input,atlas:source,limits:bounds}),mutatesWorld:false,mutatesAtlas:false,ownsCamera:false,ownsRenderer:false});}
