import {performance} from 'node:perf_hooks';
import {loadP5Runtime,canonicalContext,findPlanet} from '../p5/p5-test-helpers.mjs';
import {semanticManifestHash,canonicalP5SourceEnvelope,adaptP5EnvironmentV1,adaptP5ResearchExtensionV02,composeResearchEnvironment,createP2BiosphereBindings,generateBiosphereMacro,materializeMeso,materializeIndividual} from '../../research/p6/biosphere-model-v2.mjs';
const O=loadP5Runtime(),P=O.p2,A=O.p3Astronomy,P5=O.p5Planetology,ctx=canonicalContext(A),chosen=findPlanet(A,ctx,s=>s.formation.bulkPriorClass==='TERRESTRIAL'&&s.formation.baselineMassMilliEarth>=1000n&&s.formation.baselineMassMilliEarth<=8000n),snapshot=chosen.snapshot,planet=P5.realizePhysicalPlanet(ctx,P5.adaptP3PlanetaryInputSnapshot(snapshot)),canonical=adaptP5EnvironmentV1(canonicalP5SourceEnvelope(P5,P5.p6EnvironmentalProjection(planet,P5.createTerrainTopology(planet)))),uid=P.universeIdentity(ctx.masterSeed,ctx.semanticManifestHash).digest,bindings=createP2BiosphereBindings({p2:P,masterSeed:ctx.masterSeed,p6SemanticManifestHash:semanticManifestHash(P),canonicalUniverseIdentity:uid});
const CONCEPTUAL_QUERIES=2000,ACTIVE=24;let activeSpecies=0,activeIndividuals=0,digestAccumulator=0;const before=process.memoryUsage().heapUsed,t0=performance.now();
for(let i=0;i<CONCEPTUAL_QUERIES;i++){
  const ext=adaptP5ResearchExtensionV02({version:'p6-environment-research-v0.2',authority:'P5_RESEARCH_DRAFT',planetId:snapshot.planetId,environmentalEpochRef:`BENCHMARK_RESEARCH_${i}`,energy:{baselineInsolationPpm:Number(snapshot.orbit.baselineInsolationPpm)},temperature:{meanK:220+(i%13)*11,minSeasonalK:190+(i%11)*8,maxSeasonalK:260+(i%9)*13,highLatitudeSeasonalityK:15+(i%8)*18},atmosphere:{pressurePa:15000+(i%19)*18000,columnEquivalentPressurePa:15000+(i%19)*18000,pressureInterpretation:'RESEARCH',heavyGasRetentionProxy:0.3+(i%7)*0.09,xuvEscapeKgS:200+(i%23)*90},solvent:{surfaceWaterRegime:i%5===0?'TRACE_OR_ABSENT':'LIQUID_SURFACE_CAPABLE',deepWaterRegime:'RESEARCH'},geology:{activityProxy:0.1+(i%12)*0.09,regimeProxy:'RESEARCH'},terrain:{oceanFractionPpm:i%5===0?0:150000+(i%8)*90000,reliefScaleM:1500+(i%13)*650},radiation:{xuvFractionProxy:0.000001*(1+(i%15))}}),env=composeResearchEnvironment(canonical,ext),macro=generateBiosphereMacro(env,bindings);digestAccumulator=(digestAccumulator+macro.biosphereId[0]+macro.biosphereId[31]+macro.productivity.primaryProductivityU)>>>0;
  if(i<ACTIVE){const indexes=Array.from({length:Math.min(4,macro.commitments.lineageCount)},(_,j)=>j),meso=materializeMeso(env,macro,bindings,{lineageIndexes:indexes,speciesPerLineage:3});activeSpecies+=meso.species.length;for(const species of meso.species.slice(0,4)){const micro=materializeIndividual(env,macro,species,bindings,0);digestAccumulator=(digestAccumulator+micro.individualId[0])>>>0;activeIndividuals++}}
}
const elapsedMs=performance.now()-t0;if(global.gc)global.gc();const after=process.memoryUsage().heapUsed;console.log(JSON.stringify({status:'PASS',scenario:'P6_WAVE2_BOUNDED_RESEARCH_WORKING_SET',canonicalPlanetId:P.hex(snapshot.planetId),conceptualEnvironmentQueries:CONCEPTUAL_QUERIES,simultaneouslyRefinedStates:ACTIVE,activeSpeciesMaterialized:activeSpecies,activeIndividualsMaterialized:activeIndividuals,cacheCount:0,elapsedMs:Number(elapsedMs.toFixed(3)),averageQueryMs:Number((elapsedMs/CONCEPTUAL_QUERIES).toFixed(6)),nodeHeapDeltaBytes:after-before,digestAccumulator,claim:'Conceptual research queries do not require retaining global meso/micro materialization; Node heap is secondary evidence and not browser certification.'},null,2));
