import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
await import('../../src/v1x-05-planet-approach-rendering/planet-approach-provider.js');
const P=globalThis.OFU.v1x05PlanetApproach;
assert.equal(P.contract,'ofu-v1x05-planet-approach-provider-1');
assert.equal(P.authorityClass,'PRESENTATION_ONLY');
assert.equal(P.canonicalPromotion,false);
const physical={contractId:'ofu-p5-planet-physical-v1',status:'SUPPORTED',physical:{meanRadiusM:6371000n,surfaceGravityMicroMs2:9810000n}};
const unknownEnvironment={contractId:'ofu-p5-p6-environment-v2',atmosphere:{epistemicStatus:'UNKNOWN',atmosphericRetainedMassTg:null,provenance:'NO_CANONICAL_VOLATILE_GENESIS'}};
const systemContext={systemId:'fixture:system-01',cameraAbsoluteM:[9.46e23,-1.2e23,3.4e22]};
const t0=performance.now();
const packet=P.project({selectedCanonicalTarget:'planet:test-001',physicalPlanet:physical,environment:unknownEnvironment,frameHandoff:{planetId:'planet:test-001',systemReferenceFrameId:'fixture:system-frame',planetReferenceFrameId:'fixture:planet-centered-frame',cameraPlanetLocalM:[7e11,-4e11,3e11],systemContext},surfaceTarget:{latitudeDeg:37.7749,longitudeDeg:-122.4194,surfaceTargetReferenceFrameId:'fixture:surface-target-frame'},samples:1025});
const elapsedMs=performance.now()-t0;
assert.equal(packet.frames.length,1025);
assert.equal(Object.isFrozen(systemContext),false);
assert.equal(Object.isFrozen(systemContext.cameraAbsoluteM),false);
assert.equal(packet.selectedCanonicalTarget,'planet:test-001');
assert(packet.frames.every(f=>f.selectedCanonicalTarget==='planet:test-001'));
assert(packet.frames.every(f=>f.referenceFrameId==='fixture:planet-centered-frame'));
assert.equal(packet.referenceFrameWitness[0].referenceFrameId,'fixture:system-frame');
assert.equal(packet.referenceFrameWitness[2].referenceFrameId,'fixture:surface-target-frame');
assert(packet.surfaceTarget.anchorToken.startsWith('planet:test-001/nav-anchor/'));
assert.equal(packet.surfaceTarget.canonicalGeodesyClaim,false);
assert.equal(packet.surfaceTarget.elevationClaim,false);
assert.equal(packet.cues.atmosphere.enabled,false);
assert.equal(packet.cues.water.enabled,false);
assert.equal(packet.cues.ice.enabled,false);
assert.equal(packet.cues.material.enabled,false);
assert.equal(packet.continuity.monotonicRadialDescent,true);
assert.equal(packet.continuity.teleportOperationCount,0);
assert(packet.continuity.maxSplitReconstructionErrorM<=1e-6);
assert(packet.frames[0].positionPlanetLocalM.every((v,i)=>Object.is(v,[7e11,-4e11,3e11][i])));
const last=packet.frames.at(-1),lastRadius=Math.hypot(...last.positionPlanetLocalM);
assert(lastRadius>6371000&&lastRadius<6471001);
const maxRelativeStep=packet.continuity.maxStepM/Math.hypot(...packet.frames[0].positionPlanetLocalM);
assert(maxRelativeStep<0.02,'sampled path contains an excessive discontinuity');
const reverse=P.reverseExit(packet);
assert.equal(reverse.selectionPreserved,true);
assert.equal(reverse.selectedCanonicalTarget,'planet:test-001');
assert.deepEqual(reverse.exitHandoff.systemContext.cameraAbsoluteM,[9.46e23,-1.2e23,3.4e22]);
assert.deepEqual(reverse.frames[0].positionPlanetLocalM,packet.frames.at(-1).positionPlanetLocalM);
assert.deepEqual(reverse.frames.at(-1).positionPlanetLocalM,packet.frames[0].positionPlanetLocalM);
const denied=P.cuePolicy(unknownEnvironment,{water:{supported:true,authorityClass:'PRESENTATION_ONLY',sourceId:'fake-water'}});
assert.equal(denied.water.enabled,false);
const modeled=P.cuePolicy(unknownEnvironment,{water:{supported:true,authorityClass:'MODEL_DERIVED_SIMULATION',sourceId:'fixture:model-water',claim:'modeled global water cue'}});
assert.equal(modeled.water.enabled,true);
assert.equal(modeled.water.sourceAuthorityClass,'MODEL_DERIVED_SIMULATION');
assert.equal(modeled.water.scientificEvidence,false);
const knownEnvironment={contractId:'ofu-p5-p6-environment-v2',atmosphere:{epistemicStatus:'KNOWN',atmosphericRetainedMassTg:1000n,provenance:'fixture:known-atmosphere'}};
assert.equal(P.cuePolicy(knownEnvironment).atmosphere.enabled,true);
const zeroAtmosphere={contractId:'ofu-p5-p6-environment-v2',atmosphere:{epistemicStatus:'KNOWN',atmosphericRetainedMassTg:0n,provenance:'fixture:known-airless'}};
assert.equal(P.cuePolicy(zeroAtmosphere).atmosphere.enabled,false);
assert.throws(()=>P.project({selectedCanonicalTarget:'planet:a',physicalPlanet:physical,frameHandoff:{planetId:'planet:b',systemReferenceFrameId:'s',planetReferenceFrameId:'p',cameraPlanetLocalM:[1e8,0,0]},surfaceTarget:{latitudeDeg:0,longitudeDeg:0}}),/identity mismatch/);
const serializedBytes=Buffer.byteLength(JSON.stringify(packet));
assert(serializedBytes<8*1024*1024);
const evidence={schema:'ofu-v1x05-continuity-evidence-1',status:'PASS',authorityClass:'MEASURED_RUNTIME_EVIDENCE',providerContract:P.contract,selectedCanonicalTarget:packet.selectedCanonicalTarget,samples:packet.frames.length,serializedBytes,elapsedMs:Number(elapsedMs.toFixed(3)),maxStepM:packet.continuity.maxStepM,maxRelativeStep,maxSplitReconstructionErrorM:packet.continuity.maxSplitReconstructionErrorM,startDistanceM:Math.hypot(...packet.frames[0].positionPlanetLocalM),endDistanceM:lastRadius,surfaceAnchor:packet.surfaceTarget.anchorToken,unknownAtmosphereVisible:packet.cues.atmosphere.enabled,reverseSelectionPreserved:reverse.selectionPreserved};
console.log(JSON.stringify(evidence));
