(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.planetRenderCore;
if(!C)throw new Error('planet-render-core must load first');
const VERSION='ofu-planet-webgl2-presentation-3',STATES=new WeakMap(),LISTENED=new WeakSet();
const FAMILY_MATERIALS=Object.freeze({
 TERRESTRIAL:Object.freeze({family:'TERRESTRIAL_MINERAL',primary:[0.28,0.40,0.43],secondary:[0.075,0.11,0.16],accent:[0.74,0.52,0.24],banding:0.08,variation:0.92}),
 VOLATILE_RICH:Object.freeze({family:'VOLATILE_RICH_NEUTRAL',primary:[0.30,0.56,0.68],secondary:[0.08,0.18,0.30],accent:[0.72,0.88,0.91],banding:0.45,variation:0.78}),
 ICE_GIANT:Object.freeze({family:'ICE_GIANT_RESTRAINED',primary:[0.32,0.68,0.82],secondary:[0.08,0.22,0.46],accent:[0.78,0.92,0.96],banding:0.72,variation:0.64}),
 GAS_GIANT:Object.freeze({family:'GAS_GIANT_RESTRAINED',primary:[0.76,0.55,0.25],secondary:[0.20,0.08,0.22],accent:[0.96,0.78,0.46],banding:0.95,variation:0.72}),
 UNKNOWN:Object.freeze({family:'UNCLASSIFIED_NEUTRAL',primary:[0.38,0.38,0.58],secondary:[0.10,0.12,0.22],accent:[0.72,0.60,0.82],banding:0.20,variation:0.68})
});
function providerBodyClass(provider){const raw=String(provider?.physical?.upstreamBaseline?.formation?.bulkPriorClass??provider?.physical?.formation?.bulkPriorClass??provider?.bulkPriorClass??'UNKNOWN').toUpperCase();return FAMILY_MATERIALS[raw]?raw:'UNKNOWN'}
function presentationMaterial(provider,override){if(override&&Array.isArray(override.primary)&&Array.isArray(override.secondary)&&Array.isArray(override.accent))return Object.freeze({family:String(override.presentationFamily||override.family||'CUSTOM_PRESENTATION'),primary:override.primary.map(Number),secondary:override.secondary.map(Number),accent:override.accent.map(Number),banding:Number(override.bandingCue??override.banding??0),variation:Number(override.macroVariation??override.variation??.1)});return FAMILY_MATERIALS[providerBodyClass(provider)]||FAMILY_MATERIALS.UNKNOWN}
function hashText(text){let h=2166136261>>>0;for(let i=0;i<String(text).length;i++){h^=String(text).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function presentationSeed(provider){return (hashText(provider?.planetId||provider?.physical?.planetId||providerBodyClass(provider))>>>0)/4294967296}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const e=gl.getShaderInfoLog(s)||'shader compile failed';gl.deleteShader(s);throw new Error(e)}return s}
function program(gl){const vs=shader(gl,gl.VERTEX_SHADER,'#version 300 es\nlayout(location=0) in vec3 p;uniform mat4 vp;uniform vec3 patchOrigin;out vec3 worldDir;void main(){vec3 world=p+patchOrigin;worldDir=normalize(world);gl_Position=vp*vec4(world,1.0);}'),fs=shader(gl,gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;in vec3 worldDir;uniform vec3 materialPrimary;uniform vec3 materialSecondary;uniform vec3 materialAccent;uniform float bandingCue;uniform float macroVariation;uniform float presentationSeed;out vec4 c;float hash31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}float noise3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float n000=hash31(i),n100=hash31(i+vec3(1,0,0)),n010=hash31(i+vec3(0,1,0)),n110=hash31(i+vec3(1,1,0)),n001=hash31(i+vec3(0,0,1)),n101=hash31(i+vec3(1,0,1)),n011=hash31(i+vec3(0,1,1)),n111=hash31(i+vec3(1,1,1));return mix(mix(mix(n000,n100,f.x),mix(n010,n110,f.x),f.y),mix(mix(n001,n101,f.x),mix(n011,n111,f.x),f.y),f.z);}float fbm(vec3 p){float v=0.0,a=.56;for(int i=0;i<5;i++){v+=a*noise3(p);p=p*2.03+vec3(7.1,3.7,5.3);a*=.47;}return v;}void main(){vec3 n=normalize(worldDir);vec3 seed=vec3(presentationSeed*19.7,presentationSeed*31.3,presentationSeed*47.1);float continental=fbm(n*1.75+seed);float broad=fbm(n*3.8+seed.yzx*.61);float medium=fbm(n*9.0+seed.zxy*.43);float fine=fbm(n*24.0+seed.xyz*.19);float warp=(broad-.5)*8.0+(medium-.5)*3.0;float bands=.5+.5*sin(n.y*(21.0+bandingCue*88.0)+warp+n.x*3.0);float regionField=continental*.72+broad*.28;float region=smoothstep(.39,.61,regionField);float transition=1.0-smoothstep(.02,.16,abs(regionField-.50));float ridges=pow(1.0-abs(2.0*medium-1.0),2.2);float macroShape=clamp(region*.82+broad*.26-medium*.08,0.0,1.0);float structured=mix(macroShape,bands*.72+broad*.28,clamp(bandingCue,0.0,1.0));vec3 base=mix(materialSecondary,materialPrimary,clamp(.06+structured*.94,0.0,1.0));float accentMask=clamp((transition*.38+ridges*.26+max(0.0,fine-.56)*.30)*macroVariation,0.0,.52);base=mix(base,materialAccent,accentMask);float polar=pow(abs(n.y),5.0)*(1.0-bandingCue)*.08;base=mix(base,materialAccent,polar);vec3 lightDir=normalize(vec3(-.45,.58,.68));float ndl=dot(n,lightDir);float diffuse=max(ndl,0.0);float night=smoothstep(-.28,.12,ndl);float reliefCue=((broad-.5)*.12+(medium-.5)*.10)*macroVariation;float light=clamp(.13+.88*diffuse+reliefCue,0.055,1.08)*mix(.58,1.0,night);float rim=pow(clamp(1.0-abs(n.z),0.0,1.0),2.4);vec3 lit=base*light+materialAccent*rim*.055;c=vec4(lit,1.0);}'),p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const e=gl.getProgramInfoLog(p)||'program link failed';gl.deleteProgram(p);throw new Error(e)}return p}
class GPURegistry{
 constructor(gl,{maxMeshes=48,maxBytes=8*1024*1024,generation=1}={}){if(!gl||maxMeshes<1||maxBytes<1)throw new Error('invalid GPU registry');this.gl=gl;this.maxMeshes=maxMeshes;this.maxBytes=maxBytes;this.generation=generation;this.map=new Map();this.epoch=0;this.createdBuffers=0;this.deletedBuffers=0;this.deletedMeshes=0;this.invalidatedBuffers=0;this.invalidatedMeshes=0;this.uploadedMeshes=0;this.uploadCpuMs=0;this.peakBytes=0;this.peakMeshes=0;this.valid=true}
 beginFrame(){if(!this.valid)return;this.epoch++;for(const r of this.map.values())r.active=false}
 upload(key,mesh){if(!this.valid)throw new Error('GPU registry invalid');let r=this.map.get(key);if(r){r.active=true;r.lastUse=this.epoch;return r}const clock=typeof performance==='object'&&typeof performance.now==='function'?()=>performance.now():()=>Date.now(),started=clock(),gl=this.gl,vb=gl.createBuffer(),ib=gl.createBuffer();if(!vb||!ib)throw new Error('WebGL buffer allocation failed');gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,mesh.vertices,gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,mesh.indices,gl.STATIC_DRAW);this.uploadCpuMs+=clock()-started;this.uploadedMeshes++;r={key,vb,ib,bytes:mesh.vertexBytes+mesh.indexBytes,count:mesh.indices.length,type:mesh.indices instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,lastUse:this.epoch,active:true,generation:this.generation};this.map.set(key,r);this.createdBuffers+=2;this.trim();this.updatePeaks();return r}
 deleteRecord(key,reason='evict'){const r=this.map.get(key);if(!r)return false;this.map.delete(key);if(this.valid){this.gl.deleteBuffer(r.vb);this.gl.deleteBuffer(r.ib);this.deletedBuffers+=2}this.deletedMeshes++;r.vb=null;r.ib=null;r.deletedReason=reason;return true}
 trim(){if(!this.valid)return;const bytes=()=>{let n=0;for(const r of this.map.values())n+=r.bytes;return n};while(this.map.size>this.maxMeshes||bytes()>this.maxBytes){const candidates=[...this.map.values()].filter(r=>!r.active).sort((a,b)=>a.lastUse-b.lastUse||a.key.localeCompare(b.key));if(!candidates.length)throw new Error('active GPU working set exceeds configured GPU bound');this.deleteRecord(candidates[0].key,'bound')}}
 endFrame(retainedKeys){if(!this.valid)return this.stats();const retain=retainedKeys instanceof Set?retainedKeys:new Set(retainedKeys||[]);for(const [k,r] of [...this.map])if(!r.active&&!retain.has(k))this.deleteRecord(k,'working-set');this.trim();this.updatePeaks();return this.stats()}
 invalidate(){if(!this.valid)return;this.invalidatedBuffers+=this.map.size*2;this.invalidatedMeshes+=this.map.size;for(const r of this.map.values()){r.vb=null;r.ib=null}this.map.clear();this.valid=false}
 dispose(){if(!this.valid)return;for(const k of [...this.map.keys()])this.deleteRecord(k,'dispose');this.valid=false}
 liveBytes(){let n=0;for(const r of this.map.values())n+=r.bytes;return n}
 updatePeaks(){this.peakBytes=Math.max(this.peakBytes,this.liveBytes());this.peakMeshes=Math.max(this.peakMeshes,this.map.size)}
 stats(){return Object.freeze({generation:this.generation,valid:this.valid,maxMeshes:this.maxMeshes,maxBytes:this.maxBytes,liveMeshes:this.map.size,liveBuffers:this.map.size*2,liveTrackedBytes:this.liveBytes(),createdBuffers:this.createdBuffers,deletedBuffers:this.deletedBuffers,deletedMeshes:this.deletedMeshes,invalidatedBuffers:this.invalidatedBuffers,invalidatedMeshes:this.invalidatedMeshes,uploadedMeshes:this.uploadedMeshes,uploadCpuMs:this.uploadCpuMs,peakMeshes:this.peakMeshes,peakTrackedBytes:this.peakBytes,physicalDriverVramBytes:'NOT_AVAILABLE_PORTABLY'})}
}
function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
function norm(a){const m=Math.hypot(...a);return[a[0]/m,a[1]/m,a[2]/m]}
function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let s=0;for(let k=0;k<4;k++)s+=a[k*4+r]*b[c*4+k];o[c*4+r]=s}return o}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far),m=new Float32Array(16);m[0]=f/aspect;m[5]=f;m[10]=(far+near)*nf;m[11]=-1;m[14]=2*far*near*nf;return m}
function lookAt(eye,target=[0,0,0],upHint=[0,1,0]){const z=norm([eye[0]-target[0],eye[1]-target[1],eye[2]-target[2]]),x=norm(cross(upHint,z));let y=cross(z,x);if(!Number.isFinite(x[0])){const alt=[0,0,1],xx=norm(cross(alt,z));y=cross(z,xx);return new Float32Array([xx[0],y[0],z[0],0,xx[1],y[1],z[1],0,xx[2],y[2],z[2],0,-dot(xx,eye),-dot(y,eye),-dot(z,eye),1])}return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1])}
function lifecycleGpu(state){const current=state.registry.stats(),createdBuffers=state.priorCreatedBuffers+current.createdBuffers,deletedBuffers=state.priorDeletedBuffers+current.deletedBuffers,invalidatedBuffers=state.priorInvalidatedBuffers+current.invalidatedBuffers,deletedMeshes=state.priorDeletedMeshes+current.deletedMeshes,invalidatedMeshes=state.priorInvalidatedMeshes+current.invalidatedMeshes,uploadedMeshes=state.priorUploadedMeshes+current.uploadedMeshes,uploadCpuMs=state.priorUploadCpuMs+current.uploadCpuMs;return Object.freeze({...current,createdBuffers,deletedBuffers,invalidatedBuffers,deletedMeshes,invalidatedMeshes,uploadedMeshes,uploadCpuMs,lifecycleAccountingExact:createdBuffers===deletedBuffers+invalidatedBuffers+current.liveBuffers})}
function init(canvas,opts={}){let old=STATES.get(canvas);if(old&&old.gl&&!old.gl.isContextLost())return old;let gl;try{gl=canvas.getContext('webgl2',{antialias:true,alpha:false,depth:true,preserveDrawingBuffer:false})}catch{}if(!gl||gl.isContextLost())return null;const previous=old?lifecycleGpu(old):null,generation=(old?.generation||0)+1,p=program(gl),state={gl,generation,program:p,vp:gl.getUniformLocation(p,'vp'),patchOrigin:gl.getUniformLocation(p,'patchOrigin'),materialPrimary:gl.getUniformLocation(p,'materialPrimary'),materialSecondary:gl.getUniformLocation(p,'materialSecondary'),materialAccent:gl.getUniformLocation(p,'materialAccent'),bandingCue:gl.getUniformLocation(p,'bandingCue'),macroVariation:gl.getUniformLocation(p,'macroVariation'),presentationSeed:gl.getUniformLocation(p,'presentationSeed'),registry:new GPURegistry(gl,{maxMeshes:opts.maxGpuMeshes||48,maxBytes:opts.maxGpuBytes||8*1024*1024,generation}),depthBits:gl.getParameter(gl.DEPTH_BITS),contextLosses:old?.contextLosses||0,contextRestores:old?.contextRestores||0,priorCreatedBuffers:previous?.createdBuffers||0,priorDeletedBuffers:previous?.deletedBuffers||0,priorInvalidatedBuffers:previous?.invalidatedBuffers||0,priorDeletedMeshes:previous?.deletedMeshes||0,priorInvalidatedMeshes:previous?.invalidatedMeshes||0,priorUploadedMeshes:previous?.uploadedMeshes||0,priorUploadCpuMs:previous?.uploadCpuMs||0};STATES.set(canvas,state);if(!LISTENED.has(canvas)){canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();const s=STATES.get(canvas);if(s){s.registry.invalidate();s.contextLosses++;s.gl=null}});canvas.addEventListener('webglcontextrestored',()=>{const s=STATES.get(canvas);if(s)s.contextRestores++});LISTENED.add(canvas)}return state}
function render(canvas,session,cameraSnapshot,{maxGpuMeshes=48,maxGpuBytes=8*1024*1024,fovDeg=55,material=null}={}){const state=init(canvas,{maxGpuMeshes,maxGpuBytes});if(!state)return Object.freeze({backend:'unavailable'});const gl=state.gl,radius=Number(session.provider.physical.physical.meanRadiusM),surfaceRadius=session.provider.presentationBounds?.maxRadiusM||radius,clip=C.dynamicClip(radius,cameraSnapshot.distanceM,surfaceRadius),eye=cameraSnapshot.position,aspect=Math.max(0.1,canvas.width/Math.max(1,canvas.height)),vp=matMul(perspective(fovDeg*Math.PI/180,aspect,clip.near,clip.far),lookAt(eye)),mat=presentationMaterial(session.provider,material),seed=presentationSeed(session.provider);gl.viewport(0,0,canvas.width,canvas.height);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(.006,.010,.020,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(state.program);gl.uniformMatrix4fv(state.vp,false,vp);gl.uniform3fv(state.materialPrimary,mat.primary);gl.uniform3fv(state.materialSecondary,mat.secondary);gl.uniform3fv(state.materialAccent,mat.accent);gl.uniform1f(state.bandingCue,mat.banding);gl.uniform1f(state.macroVariation,mat.variation);gl.uniform1f(state.presentationSeed,seed);state.registry.beginFrame();let drawCalls=0;for(const [id,m] of session.active){const r=state.registry.upload(id,m),origin=[m.localOrigin[0],m.localOrigin[1],m.localOrigin[2]];gl.uniform3f(state.patchOrigin,origin[0],origin[1],origin[2]);gl.bindBuffer(gl.ARRAY_BUFFER,r.vb);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,r.ib);gl.drawElements(gl.TRIANGLES,r.count,r.type,0);drawCalls++}const retained=new Set(session.cache.map.keys());state.registry.endFrame(retained);const glError=gl.getError(),gpu=lifecycleGpu(state);return Object.freeze({version:VERSION,backend:'webgl2',drawCalls,glError,depthBits:state.depthBits,clip,depthStrategy:'HIERARCHICAL_LOCAL_FRAME_DYNAMIC_CLIP',gpu,contextLosses:state.contextLosses,contextRestores:state.contextRestores,palette:mat.family,materialAuthority:'PRESENTATION_ONLY',presentationPattern:'DETERMINISTIC_PLANET_WIDE_MATERIAL_REGIONS_V3',presentationSeed:seed,scientificColorClaim:false,canonicalSurfaceFeatureClaim:false,geologyClaim:false,hydrologyClaim:false,weatherClaim:false,vegetationClaim:false,biosphereClaim:false,culling:'BACK',frontFace:'CCW_DEFAULT'})}
function fallback(canvas,session){let g;try{g=canvas.getContext('2d')}catch{}if(!g)return{backend:'unavailable'};g.fillStyle='#050811';g.fillRect(0,0,canvas.width,canvas.height);g.strokeStyle='#aaa79f';g.lineWidth=1;let drawCalls=0;for(const m of session.active.values()){const c=m.localOrigin,scale=Math.min(canvas.width,canvas.height)/(Number(session.provider.physical.physical.meanRadiusM)*3),cx=canvas.width/2+c[0]*scale*.25,cy=canvas.height/2-c[1]*scale*.25,v=m.vertices,idx=m.indices;for(let i=0;i<idx.length;i+=3){const a=idx[i]*3,b=idx[i+1]*3,d=idx[i+2]*3;g.beginPath();g.moveTo(cx+v[a]*scale,cy-v[a+1]*scale);g.lineTo(cx+v[b]*scale,cy-v[b+1]*scale);g.lineTo(cx+v[d]*scale,cy-v[d+1]*scale);g.closePath();g.stroke();drawCalls++}}return Object.freeze({version:VERSION,backend:'canvas2d',drawCalls,depthStrategy:'PAINTER_FALLBACK',gpu:null,palette:presentationMaterial(session.provider).family,materialAuthority:'PRESENTATION_ONLY',scientificColorClaim:false,canonicalSurfaceFeatureClaim:false,primaryRepresentationFallback:true})}
function renderPortable(canvas,session,camera,opts){const r=render(canvas,session,camera,opts);return r.backend==='webgl2'?r:fallback(canvas,session)}
function stateStats(canvas){const s=STATES.get(canvas);return s?Object.freeze({version:VERSION,generation:s.generation,depthBits:s.depthBits,contextLosses:s.contextLosses,contextRestores:s.contextRestores,gpu:lifecycleGpu(s)}):Object.freeze({version:VERSION,generation:0,gpu:null})}
function dispose(canvas){const s=STATES.get(canvas);if(!s)return Object.freeze({disposed:false,generation:0,gpu:null});if(s.registry.valid)s.registry.dispose();const gpu=lifecycleGpu(s),generation=s.generation;if(gpu.liveMeshes!==0||gpu.liveBuffers!==0||gpu.liveTrackedBytes!==0||gpu.lifecycleAccountingExact!==true)throw new Error('GPU disposal lifecycle accounting mismatch');if(s.gl&&s.program)s.gl.deleteProgram(s.program);STATES.delete(canvas);return Object.freeze({disposed:true,generation,gpu})}
O.planetWebGL2=Object.freeze({VERSION,GPURegistry,FAMILY_MATERIALS,providerBodyClass,presentationMaterial,presentationSeed,render,renderPortable,fallback,stateStats,dispose});
})(typeof globalThis!=='undefined'?globalThis:this);
