(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.planetRenderCore;
if(!C)throw new Error('planet-render-core must load first');
const STATES=new WeakMap(),LISTENED=new WeakSet();
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const e=gl.getShaderInfoLog(s)||'shader compile failed';gl.deleteShader(s);throw new Error(e)}return s}
function program(gl){const vs=shader(gl,gl.VERTEX_SHADER,'#version 300 es\nlayout(location=0) in vec3 p;uniform mat4 vp;uniform vec3 patchOrigin;void main(){gl_Position=vp*vec4(p+patchOrigin,1.0);}'),fs=shader(gl,gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;out vec4 c;void main(){c=vec4(0.20,0.55,0.36,1.0);}'),p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const e=gl.getProgramInfoLog(p)||'program link failed';gl.deleteProgram(p);throw new Error(e)}return p}
class GPURegistry{
 constructor(gl,{maxMeshes=48,maxBytes=8*1024*1024,generation=1}={}){if(!gl||maxMeshes<1||maxBytes<1)throw new Error('invalid GPU registry');this.gl=gl;this.maxMeshes=maxMeshes;this.maxBytes=maxBytes;this.generation=generation;this.map=new Map();this.epoch=0;this.createdBuffers=0;this.deletedBuffers=0;this.deletedMeshes=0;this.invalidatedBuffers=0;this.invalidatedMeshes=0;this.uploadedMeshes=0;this.uploadCpuMs=0;this.peakBytes=0;this.peakMeshes=0;this.valid=true}
 beginFrame(){if(!this.valid)return;this.epoch++;for(const r of this.map.values())r.active=false}
 upload(key,mesh){if(!this.valid)throw new Error('GPU registry invalid');let r=this.map.get(key);if(r){r.active=true;r.lastUse=this.epoch;return r}const clock=typeof performance==='object'&&typeof performance.now==='function'?()=>performance.now():()=>Date.now(),started=clock(),gl=this.gl,vb=gl.createBuffer(),ib=gl.createBuffer();if(!vb||!ib)throw new Error('WebGL buffer allocation failed');gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,mesh.vertices,gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,mesh.indices,gl.STATIC_DRAW);this.uploadCpuMs+=clock()-started;this.uploadedMeshes++;r={key,vb,ib,bytes:mesh.vertexBytes+mesh.indexBytes,count:mesh.indices.length,type:mesh.indices instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,lastUse:this.epoch,active:true,generation:this.generation};this.map.set(key,r);this.createdBuffers+=2;this.trim();this.updatePeaks();return r}
 deleteRecord(key,reason='evict'){const r=this.map.get(key);if(!r)return false;this.map.delete(key);if(this.valid){this.gl.deleteBuffer(r.vb);this.gl.deleteBuffer(r.ib);this.deletedBuffers+=2}this.deletedMeshes++;r.vb=null;r.ib=null;r.deletedReason=reason;return true}
 trim(){if(!this.valid)return;const bytes=()=>{let n=0;for(const r of this.map.values())n+=r.bytes;return n};while(this.map.size>this.maxMeshes||bytes()>this.maxBytes){const candidates=[...this.map.values()].filter(r=>!r.active).sort((a,b)=>a.lastUse-b.lastUse||a.key.localeCompare(b.key));if(!candidates.length)throw new Error('active GPU working set exceeds configured GPU bound');this.deleteRecord(candidates[0].key,'bound')}}
 endFrame(retainedKeys){if(!this.valid)return this.stats();const retain=retainedKeys instanceof Set?retainedKeys:new Set(retainedKeys||[]);for(const [k,r] of [...this.map])if(!r.active&&!retain.has(k))this.deleteRecord(k,'working-set');this.trim();this.updatePeaks();return this.stats()}
 invalidate(){if(!this.valid)return;this.invalidatedBuffers+=this.map.size*2;this.invalidatedMeshes+=this.map.size;for(const r of this.map.values()){r.vb=null;r.ib=null}this.map.clear();this.valid=false}
 dispose(){if(!this.valid)return;for(const k of [...this.map.keys()])this.deleteRecord(k,'dispose');this.valid=false}
 liveBytes(){let n=0;for(const r of this.map.values())n+=r.bytes;return n}
 updatePeaks(){this.peakBytes=Math.max(this.peakBytes,this.liveBytes());this.peakMeshes=Math.max(this.peakMeshes,this.map.size)}
 stats(){return Object.freeze({generation:this.generation,valid:this.valid,maxMeshes:this.maxMeshes,maxBytes:this.maxBytes,liveMeshes:this.map.size,liveBuffers:this.map.size*2,liveTrackedBytes:this.liveBytes(),createdBuffers:this.createdBuffers,deletedBuffers:this.deletedBuffers,deletedMeshes:this.deletedMeshes,invalidatedBuffers:this.invalidatedBuffers,invalidatedMeshes:this.invalidatedMeshes,uploadedMeshes:this.uploadedMeshes,uploadCpuMs:this.uploadCpuMs,peakMeshes:this.peakMeshes,peakTrackedBytes:this.peakBytes,physicalDriverVramBytes:'NOT_AVAILABLE_PORTABLY'})}
}
function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
function norm(a){const m=Math.hypot(...a);return[a[0]/m,a[1]/m,a[2]/m]}
function matMul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let s=0;for(let k=0;k<4;k++)s+=a[k*4+r]*b[c*4+k];o[c*4+r]=s}return o}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far),m=new Float32Array(16);m[0]=f/aspect;m[5]=f;m[10]=(far+near)*nf;m[11]=-1;m[14]=2*far*near*nf;return m}
function lookAt(eye,target=[0,0,0],upHint=[0,1,0]){const z=norm([eye[0]-target[0],eye[1]-target[1],eye[2]-target[2]]),x=norm(cross(upHint,z));let y=cross(z,x);if(!Number.isFinite(x[0])){const alt=[0,0,1],xx=norm(cross(alt,z));y=cross(z,xx);return new Float32Array([xx[0],y[0],z[0],0,xx[1],y[1],z[1],0,xx[2],y[2],z[2],0,-dot(xx,eye),-dot(y,eye),-dot(z,eye),1])}return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1])}
function lifecycleGpu(state){const current=state.registry.stats(),createdBuffers=state.priorCreatedBuffers+current.createdBuffers,deletedBuffers=state.priorDeletedBuffers+current.deletedBuffers,invalidatedBuffers=state.priorInvalidatedBuffers+current.invalidatedBuffers,deletedMeshes=state.priorDeletedMeshes+current.deletedMeshes,invalidatedMeshes=state.priorInvalidatedMeshes+current.invalidatedMeshes,uploadedMeshes=state.priorUploadedMeshes+current.uploadedMeshes,uploadCpuMs=state.priorUploadCpuMs+current.uploadCpuMs;return Object.freeze({...current,createdBuffers,deletedBuffers,invalidatedBuffers,deletedMeshes,invalidatedMeshes,uploadedMeshes,uploadCpuMs,lifecycleAccountingExact:createdBuffers===deletedBuffers+invalidatedBuffers+current.liveBuffers})}
function init(canvas,opts={}){let old=STATES.get(canvas);if(old&&old.gl&&!old.gl.isContextLost())return old;let gl;try{gl=canvas.getContext('webgl2',{antialias:true,alpha:false,depth:true,preserveDrawingBuffer:false})}catch{}if(!gl||gl.isContextLost())return null;const previous=old?lifecycleGpu(old):null,generation=(old?.generation||0)+1,p=program(gl),state={gl,generation,program:p,vp:gl.getUniformLocation(p,'vp'),patchOrigin:gl.getUniformLocation(p,'patchOrigin'),registry:new GPURegistry(gl,{maxMeshes:opts.maxGpuMeshes||48,maxBytes:opts.maxGpuBytes||8*1024*1024,generation}),depthBits:gl.getParameter(gl.DEPTH_BITS),contextLosses:old?.contextLosses||0,contextRestores:old?.contextRestores||0,priorCreatedBuffers:previous?.createdBuffers||0,priorDeletedBuffers:previous?.deletedBuffers||0,priorInvalidatedBuffers:previous?.invalidatedBuffers||0,priorDeletedMeshes:previous?.deletedMeshes||0,priorInvalidatedMeshes:previous?.invalidatedMeshes||0,priorUploadedMeshes:previous?.uploadedMeshes||0,priorUploadCpuMs:previous?.uploadCpuMs||0};STATES.set(canvas,state);if(!LISTENED.has(canvas)){canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();const s=STATES.get(canvas);if(s){s.registry.invalidate();s.contextLosses++;s.gl=null}});canvas.addEventListener('webglcontextrestored',()=>{const s=STATES.get(canvas);if(s)s.contextRestores++});LISTENED.add(canvas)}return state}
function render(canvas,session,cameraSnapshot,{maxGpuMeshes=48,maxGpuBytes=8*1024*1024,fovDeg=55}={}){const state=init(canvas,{maxGpuMeshes,maxGpuBytes});if(!state)return Object.freeze({backend:'unavailable'});const gl=state.gl,clip=C.dynamicClip(session.provider.physical.physical.meanRadiusM?Number(session.provider.physical.physical.meanRadiusM):cameraSnapshot.distanceM/2,cameraSnapshot.distanceM),eye=cameraSnapshot.position,aspect=Math.max(0.1,canvas.width/Math.max(1,canvas.height)),vp=matMul(perspective(fovDeg*Math.PI/180,aspect,clip.near,clip.far),lookAt(eye));gl.viewport(0,0,canvas.width,canvas.height);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.clearColor(.006,.010,.020,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(state.program);gl.uniformMatrix4fv(state.vp,false,vp);state.registry.beginFrame();let drawCalls=0;for(const [id,m] of session.active){const r=state.registry.upload(id,m),origin=[m.localOrigin[0],m.localOrigin[1],m.localOrigin[2]];gl.uniform3f(state.patchOrigin,origin[0],origin[1],origin[2]);gl.bindBuffer(gl.ARRAY_BUFFER,r.vb);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,r.ib);gl.drawElements(gl.TRIANGLES,r.count,r.type,0);drawCalls++}const retained=new Set(session.cache.map.keys());state.registry.endFrame(retained);const glError=gl.getError(),gpu=lifecycleGpu(state);return Object.freeze({backend:'webgl2',drawCalls,glError,depthBits:state.depthBits,clip,depthStrategy:'HIERARCHICAL_LOCAL_FRAME_DYNAMIC_CLIP',gpu,contextLosses:state.contextLosses,contextRestores:state.contextRestores})}
function fallback(canvas,session){let g;try{g=canvas.getContext('2d')}catch{}if(!g)return{backend:'unavailable'};g.fillStyle='#050811';g.fillRect(0,0,canvas.width,canvas.height);g.strokeStyle='#76cba1';g.lineWidth=1;let drawCalls=0;for(const m of session.active.values()){const c=m.localOrigin,scale=Math.min(canvas.width,canvas.height)/(Number(session.provider.physical.physical.meanRadiusM)*3),cx=canvas.width/2+c[0]*scale*.25,cy=canvas.height/2-c[1]*scale*.25,v=m.vertices,idx=m.indices;for(let i=0;i<idx.length;i+=3){const a=idx[i]*3,b=idx[i+1]*3,d=idx[i+2]*3;g.beginPath();g.moveTo(cx+v[a]*scale,cy-v[a+1]*scale);g.lineTo(cx+v[b]*scale,cy-v[b+1]*scale);g.lineTo(cx+v[d]*scale,cy-v[d+1]*scale);g.closePath();g.stroke();drawCalls++}}return Object.freeze({backend:'canvas2d',drawCalls,depthStrategy:'PAINTER_FALLBACK',gpu:null})}
function renderPortable(canvas,session,camera,opts){const r=render(canvas,session,camera,opts);return r.backend==='webgl2'?r:fallback(canvas,session)}
function stateStats(canvas){const s=STATES.get(canvas);return s?Object.freeze({generation:s.generation,depthBits:s.depthBits,contextLosses:s.contextLosses,contextRestores:s.contextRestores,gpu:lifecycleGpu(s)}):Object.freeze({generation:0,gpu:null})}
function dispose(canvas){const s=STATES.get(canvas);if(!s)return;if(s.registry.valid)s.registry.dispose();if(s.gl&&s.program)s.gl.deleteProgram(s.program);STATES.delete(canvas)}
O.planetWebGL2=Object.freeze({GPURegistry,render,renderPortable,fallback,stateStats,dispose});
})(typeof globalThis!=='undefined'?globalThis:this);
