(function(root){
'use strict';
const O=root.OFU=root.OFU||{},C=O.planetRenderCore;
if(!C)throw new Error('planet-render-core must load first');
const AUTHORITY='PRESENTATION_ONLY',VERSION='ofu-planet-surface-frame-1';
const SURFACE_BANDS=Object.freeze(['GLOBAL_SURFACE','REGIONAL_SURFACE','LOCAL_SURFACE','HUMAN']);
const ALL_SCALE_BANDS=Object.freeze(['PLANET_ORBIT','PLANET_APPROACH',...SURFACE_BANDS]);
const CLAIMS=Object.freeze({geologyClaim:false,hydrologyClaim:false,vegetationClaim:false,biosphereClaim:false,physicalTerrainElevationClaim:false,canonicalGeodesyClaim:false,canonicalSurfaceAnchorClaim:false});
const HANDOFF_PRESENTATION_ALTITUDE_M=120000;
const REVERSE_HANDOFF_PRESENTATION_ALTITUDE_M=180000;
const DEFAULT_FLOATING_ORIGIN_THRESHOLD_MM=250000n;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function normalize(v){const m=Math.hypot(Number(v?.[0]),Number(v?.[1]),Number(v?.[2]));if(!(m>0)||!Number.isFinite(m))throw new Error('surface frame requires finite non-zero direction');return Object.freeze([Number(v[0])/m,Number(v[1])/m,Number(v[2])/m])}
function freeze3(v){return Object.freeze([Number(v[0]),Number(v[1]),Number(v[2])])}
function bodyClassOf(source){return String(source?.bodyClass??source?.bulkPriorClass??source?.planet?.facts?.bulkPriorClass??source?.physical?.upstreamBaseline?.formation?.bulkPriorClass??source?.provider?.physical?.upstreamBaseline?.formation?.bulkPriorClass??'UNKNOWN').toUpperCase()}
function surfaceCapability(source){const bodyClass=bodyClassOf(source),provider=source?.provider||source?.presentationProvider||null,planetId=String(source?.planetId??provider?.planetId??'');if(bodyClass!=='TERRESTRIAL')return Object.freeze({authority:AUTHORITY,available:false,bodyClass,planetId,reason:bodyClass==='GAS_GIANT'||bodyClass==='ICE_GIANT'?'NO_SUPPORTED_SOLID_LOCAL_SURFACE':'CANONICAL_SURFACE_MODEL_UNAVAILABLE',claims:CLAIMS});if(!provider?.presentationBounds||!(Number(source?.radiusM??provider?.physical?.physical?.meanRadiusM)>0))return Object.freeze({authority:AUTHORITY,available:false,bodyClass,planetId,reason:'BOUNDED_PLANET_PRESENTATION_PROVIDER_REQUIRED',claims:CLAIMS});return Object.freeze({authority:AUTHORITY,available:true,bodyClass,planetId,reason:null,claims:CLAIMS})}
function anchorToken(planetId,direction){const q=direction.map(v=>Math.round(clamp(v,-1,1)*1e9));return String(planetId||'unknown')+'/nav-anchor/'+q.join(',')}
function tangentBasis(direction){const up=normalize(direction),reference=Math.abs(up[1])<.92?[0,1,0]:[1,0,0],east=normalize(cross(reference,up)),north=normalize(cross(up,east));return Object.freeze({east,north,up,handedness:dot(cross(east,north),up)>0?'RIGHT_HANDED':'INVALID'})}
function createAnchor({planetId,radiusM,viewDirection=[0,0,1]}={}){if(typeof planetId!=='string'||!planetId)throw new Error('surface anchor requires canonical planet identity');if(!(Number(radiusM)>0))throw new Error('surface anchor requires positive presentation radius');const direction=normalize(viewDirection),basis=tangentBasis(direction),anchorPositionM=freeze3(direction.map(v=>v*Number(radiusM)));return Object.freeze({version:VERSION,authority:AUTHORITY,planetId,kind:'PRESENTATION_NAVIGATION_ANCHOR',token:anchorToken(planetId,direction),direction,basis,anchorPositionM,radiusM:Number(radiusM),coordinateMeaning:'LOCAL_TANGENT_PRESENTATION_FRAME_NOT_CANONICAL_GEODESY',claims:CLAIMS})}
function localFromGlobal(anchor,globalPositionM){if(!anchor?.basis||!Array.isArray(globalPositionM))throw new Error('local transform requires anchor and global position');const d=[Number(globalPositionM[0])-anchor.anchorPositionM[0],Number(globalPositionM[1])-anchor.anchorPositionM[1],Number(globalPositionM[2])-anchor.anchorPositionM[2]];return freeze3([dot(d,anchor.basis.east),dot(d,anchor.basis.north),dot(d,anchor.basis.up)])}
function globalFromLocal(anchor,localPositionM){if(!anchor?.basis||!Array.isArray(localPositionM))throw new Error('global transform requires anchor and local position');const e=Number(localPositionM[0]),n=Number(localPositionM[1]),u=Number(localPositionM[2]);return freeze3([anchor.anchorPositionM[0]+anchor.basis.east[0]*e+anchor.basis.north[0]*n+anchor.basis.up[0]*u,anchor.anchorPositionM[1]+anchor.basis.east[1]*e+anchor.basis.north[1]*n+anchor.basis.up[1]*u,anchor.anchorPositionM[2]+anchor.basis.east[2]*e+anchor.basis.north[2]*n+anchor.basis.up[2]*u])}
function bandForAltitude(presentationAltitudeM){const a=Math.max(0,Number(presentationAltitudeM)||0);if(a<=120)return'HUMAN';if(a<=3000)return'LOCAL_SURFACE';if(a<=40000)return'REGIONAL_SURFACE';return'GLOBAL_SURFACE'}
function createLocalCamera(anchor,{presentationAltitudeM=HANDOFF_PRESENTATION_ALTITUDE_M,headingRad=0,pitchRad=-.35}={}){if(!anchor?.token)throw new Error('local camera requires surface anchor');const z=BigInt(Math.round(Math.max(1,Number(presentationAltitudeM))*1000));return {anchorToken:anchor.token,planetId:anchor.planetId,absoluteLocalMm:[0n,0n,z],frameOriginMm:[0n,0n,z],headingRad:Number(headingRad)||0,pitchRad:clamp(Number(pitchRad)||0,-1.5533430342749532,1.5533430342749532),rebases:0,lastRebaseDistanceMm:0n}}
function cameraRelativeMm(camera){return Object.freeze(camera.absoluteLocalMm.map((v,i)=>v-camera.frameOriginMm[i]))}
function localCameraSnapshot(camera){const relative=cameraRelativeMm(camera),absoluteM=Object.freeze(camera.absoluteLocalMm.map(v=>Number(v)/1000)),relativeM=Object.freeze(relative.map(v=>Number(v)/1000)),altitudeM=Math.max(0,absoluteM[2]);return Object.freeze({authority:AUTHORITY,planetId:camera.planetId,anchorToken:camera.anchorToken,absolutePresentationPositionM:absoluteM,cameraRelativePositionM:relativeM,presentationAltitudeM:altitudeM,currentBand:bandForAltitude(altitudeM),headingRad:camera.headingRad,pitchRad:camera.pitchRad,rebases:camera.rebases,coordinateMeaning:'PRESENTATION_ONLY',claims:CLAIMS})}
function nearestGridMm(value,gridMm=1000n){if(gridMm<=0n)throw new Error('floating-origin grid must be positive');const half=gridMm/2n;return value>=0n?((value+half)/gridMm)*gridMm:((value-half)/gridMm)*gridMm}
function rebaseFloatingOrigin(camera,{thresholdMm=DEFAULT_FLOATING_ORIGIN_THRESHOLD_MM,gridMm=1000n}={}){thresholdMm=BigInt(thresholdMm);const delta=camera.absoluteLocalMm.map((v,i)=>v-camera.frameOriginMm[i]),max=delta.reduce((m,v)=>{const a=v<0n?-v:v;return a>m?a:m},0n);if(max<=thresholdMm)return Object.freeze({rebased:false,originMm:Object.freeze([...camera.frameOriginMm]),relativeMm:cameraRelativeMm(camera),distanceMm:max});camera.frameOriginMm=camera.absoluteLocalMm.map(v=>nearestGridMm(v,gridMm));camera.rebases++;camera.lastRebaseDistanceMm=max;return Object.freeze({rebased:true,originMm:Object.freeze([...camera.frameOriginMm]),relativeMm:cameraRelativeMm(camera),distanceMm:max})}
function applyLocalIntent(camera,intent,{moveStepM=20,altitudeStepM=20,lookStepRad=.035}={}){if(!camera||!intent?.type)throw new Error('local renderer intent required');const amount=Number.isFinite(Number(intent.amount))?Number(intent.amount):1,mm=v=>BigInt(Math.round(v*1000));switch(String(intent.type)){case'MOVE_FORWARD':{const d=Number(moveStepM)*amount;camera.absoluteLocalMm[0]+=mm(Math.sin(camera.headingRad)*d);camera.absoluteLocalMm[1]+=mm(Math.cos(camera.headingRad)*d);break}case'MOVE_RIGHT':{const d=Number(moveStepM)*amount;camera.absoluteLocalMm[0]+=mm(Math.cos(camera.headingRad)*d);camera.absoluteLocalMm[1]-=mm(Math.sin(camera.headingRad)*d);break}case'CHANGE_ALTITUDE':camera.absoluteLocalMm[2]=camera.absoluteLocalMm[2]+mm(Number(altitudeStepM)*amount);if(camera.absoluteLocalMm[2]<1000n)camera.absoluteLocalMm[2]=1000n;break;case'LOOK_YAW':camera.headingRad+=Number(lookStepRad)*amount;break;case'LOOK_PITCH':camera.pitchRad=clamp(camera.pitchRad+Number(lookStepRad)*amount,-1.5533430342749532,1.5533430342749532);break;default:throw new Error('unsupported local renderer intent')}rebaseFloatingOrigin(camera);return localCameraSnapshot(camera)}
function handoffFromGlobe(source,{viewDirection,planetId,radiusM}={}){const capability=surfaceCapability(source),id=String(planetId??capability.planetId??source?.planetId??source?.provider?.planetId??''),r=Number(radiusM??source?.radiusM??source?.provider?.physical?.physical?.meanRadiusM),direction=viewDirection??source?.camera?.direction??source?.direction??[0,0,1];if(!capability.available)return Object.freeze({authority:AUTHORITY,ready:false,planetId:id,reason:capability.reason,capability,claims:CLAIMS});const anchor=createAnchor({planetId:id,radiusM:r,viewDirection:direction}),camera=createLocalCamera(anchor);return Object.freeze({authority:AUTHORITY,ready:true,planetId:id,anchor,localCamera:camera,entry:Object.freeze({from:'PLANET_APPROACH',to:'GLOBAL_SURFACE',preservesCanonicalIdentity:true,preservesViewDirection:true,presentationAltitudeM:HANDOFF_PRESENTATION_ALTITUDE_M}),claims:CLAIMS})}
function reverseHandoff(anchor,camera,{presentationSurfaceRadiusM=anchor.radiusM}={}){if(!anchor||!camera||anchor.planetId!==camera.planetId)throw new Error('reverse handoff identity mismatch');const snap=localCameraSnapshot(camera),distanceM=Number(presentationSurfaceRadiusM)+Math.max(REVERSE_HANDOFF_PRESENTATION_ALTITUDE_M,snap.presentationAltitudeM);return Object.freeze({authority:AUTHORITY,planetId:anchor.planetId,to:'PLANET_APPROACH',targetDirection:anchor.direction,distanceM,preservesCanonicalIdentity:true,preservesNavigationDirection:true,claims:CLAIMS})}
function createSurfaceProvider(source,{viewDirection}={}){const capability=surfaceCapability(source),planetId=String(source?.planetId??source?.provider?.planetId??''),radiusM=Number(source?.radiusM??source?.provider?.physical?.physical?.meanRadiusM);let mode='GLOBE',anchor=null,camera=null,resources=Object.freeze({activePatches:0,cpuMeshes:0,gpuMeshes:0,trackedGpuBytes:0});function enter(direction=viewDirection??source?.camera?.direction??[0,0,1]){const h=handoffFromGlobe(source,{viewDirection:direction,planetId,radiusM});if(!h.ready)return h;anchor=h.anchor;camera=h.localCamera;mode='LOCAL';return snapshot()}function leave(){if(!anchor||!camera)return null;const out=reverseHandoff(anchor,camera,{presentationSurfaceRadiusM:Number(source?.provider?.presentationBounds?.maxRadiusM||radiusM)});mode='GLOBE';return out}function intent(i){if(mode!=='LOCAL'||!camera)throw new Error('surface provider is not in local mode');const out=applyLocalIntent(camera,i);return out}function setResources(next){resources=Object.freeze({activePatches:Number(next?.activePatches)||0,cpuMeshes:Number(next?.cpuMeshes)||0,gpuMeshes:Number(next?.gpuMeshes)||0,trackedGpuBytes:Number(next?.trackedGpuBytes)||0});return resources}function snapshot(){const local=camera?localCameraSnapshot(camera):null;return Object.freeze({version:VERSION,authority:AUTHORITY,planetId,mode,ready:true,supportedScaleBands:ALL_SCALE_BANDS,surfaceAvailability:capability.available?'AVAILABLE':'UNAVAILABLE',unsupportedReason:capability.reason,handoffReady:capability.available&&mode==='GLOBE',reverseHandoffReady:mode==='LOCAL',anchor:anchor?Object.freeze({token:anchor.token,kind:anchor.kind,direction:anchor.direction,coordinateMeaning:anchor.coordinateMeaning}):null,camera:local,currentBand:local?.currentBand||null,resourceStats:resources,presentationAuthority:AUTHORITY,claims:CLAIMS})}return Object.freeze({VERSION,AUTHORITY,CLAIMS,capability,enter,leave,intent,setResources,snapshot})}
O.planetSurface=Object.freeze({VERSION,AUTHORITY,CLAIMS,SURFACE_BANDS,ALL_SCALE_BANDS,HANDOFF_PRESENTATION_ALTITUDE_M,REVERSE_HANDOFF_PRESENTATION_ALTITUDE_M,DEFAULT_FLOATING_ORIGIN_THRESHOLD_MM,bodyClassOf,surfaceCapability,tangentBasis,createAnchor,localFromGlobal,globalFromLocal,bandForAltitude,createLocalCamera,localCameraSnapshot,rebaseFloatingOrigin,applyLocalIntent,handoffFromGlobe,reverseHandoff,createSurfaceProvider});
})(typeof globalThis!=='undefined'?globalThis:this);
