(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const AUTHORITY='PRESENTATION_ONLY',VERTICAL_FOV_DEG=55,ORBIT_OCCUPANCY=0.48,APPROACH_OCCUPANCY=0.72;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function projectionFovs(aspect=1,verticalFovDeg=VERTICAL_FOV_DEG){if(!(aspect>0)||!Number.isFinite(aspect)||!(verticalFovDeg>0&&verticalFovDeg<179)||!Number.isFinite(verticalFovDeg))throw new Error('invalid presentation projection');const verticalFovRad=verticalFovDeg*Math.PI/180,horizontalFovRad=2*Math.atan(Math.tan(verticalFovRad/2)*aspect);return Object.freeze({verticalFovDeg,verticalFovRad,horizontalFovRad,horizontalFovDeg:horizontalFovRad*180/Math.PI,limitingFovRad:Math.min(verticalFovRad,horizontalFovRad)});}
function projectedSphere({sphereRadiusM,distanceM,aspect=1,verticalFovDeg=VERTICAL_FOV_DEG}){if(!(sphereRadiusM>0)||!(distanceM>0)||!Number.isFinite(sphereRadiusM)||!Number.isFinite(distanceM))throw new Error('invalid projected sphere');const fovs=projectionFovs(aspect,verticalFovDeg),ratio=clamp(sphereRadiusM/distanceM,0,1),angularRadiusRad=Math.asin(ratio),tanAngular=Math.tan(angularRadiusRad),projectedBodyHeightFraction=tanAngular/Math.tan(fovs.verticalFovRad/2),projectedBodyWidthFraction=tanAngular/Math.tan(fovs.horizontalFovRad/2),limitingOccupancy=Math.max(projectedBodyWidthFraction,projectedBodyHeightFraction),fullLimbExpected=distanceM>sphereRadiusM&&limitingOccupancy<1;return Object.freeze({...fovs,angularRadiusRad,projectedBodyWidthFraction,projectedBodyHeightFraction,limitingOccupancy,fullLimbExpected});}
function distanceForOccupancy({sphereRadiusM,occupancy,aspect=1,verticalFovDeg=VERTICAL_FOV_DEG,minDistanceM=0}){if(!(occupancy>0&&occupancy<1)||!Number.isFinite(occupancy))throw new Error('invalid presentation occupancy');const fovs=projectionFovs(aspect,verticalFovDeg),halfAngle=Math.atan(occupancy*Math.tan(fovs.limitingFovRad/2)),unclampedDistanceM=sphereRadiusM/Math.sin(halfAngle),distanceM=Math.max(unclampedDistanceM,minDistanceM);return Object.freeze({requestedOccupancy:occupancy,distanceM,unclampedDistanceM,safetyClamped:distanceM!==unclampedDistanceM,projection:projectedSphere({sphereRadiusM,distanceM,aspect,verticalFovDeg})});}
function stageFraming(stage,{meanRadiusM,presentationBounds,cameraEnvelope,viewportWidth,viewportHeight,verticalFovDeg=VERTICAL_FOV_DEG}={}){if(!(meanRadiusM>0)||!presentationBounds||!cameraEnvelope)throw new Error('presentation framing requires bounded planet geometry');const width=Math.max(2,Number(viewportWidth)||2),height=Math.max(2,Number(viewportHeight)||2),aspect=width/height,sphereRadiusM=Number(presentationBounds.maxRadiusM),minDistanceM=Number(cameraEnvelope.minDistanceM);let distanceM,requestedOccupancy=null,kind='FIXED_RADIUS';if(stage==='orbit'||stage==='approach'){requestedOccupancy=stage==='orbit'?ORBIT_OCCUPANCY:APPROACH_OCCUPANCY;distanceM=distanceForOccupancy({sphereRadiusM,occupancy:requestedOccupancy,aspect,verticalFovDeg,minDistanceM}).distanceM;kind='PROJECTION_AWARE_OCCUPANCY';}else if(stage==='close'){distanceM=Math.max(meanRadiusM*1.012,minDistanceM);kind='SAFE_CLOSE_RADIUS';}else if(stage==='system'){distanceM=Math.max(meanRadiusM*180,minDistanceM);kind='SYSTEM_CONTEXT_RADIUS';}else throw new Error('unknown product presentation stage');return Object.freeze({authority:AUTHORITY,stage,kind,requestedOccupancy,distanceM,requestedDistanceRadii:distanceM/meanRadiusM,viewport:Object.freeze({width,height,aspect}),presentationMinRadiusM:Number(presentationBounds.minRadiusM),presentationMaxRadiusM:sphereRadiusM,minSafeDistanceM:minDistanceM,verticalFovDeg,projection:projectedSphere({sphereRadiusM,distanceM,aspect,verticalFovDeg})});}
O.planetFraming=Object.freeze({AUTHORITY,VERTICAL_FOV_DEG,ORBIT_OCCUPANCY,APPROACH_OCCUPANCY,projectionFovs,projectedSphere,distanceForOccupancy,stageFraming});
})(typeof globalThis!=='undefined'?globalThis:this);
