(function(root){
'use strict';
const O=root.OFU=root.OFU||{},P=O.p2,A=O.p3Astronomy,P5=O.p5Planetology,E=O.p5EnvironmentV2,B=O.p6Biosphere;
if(!P||!A||!P5||!E||!B)throw new Error('OFU product target adapter requires canonical P2/P3/P5/P6');
const AUTHORITY='PRESENTATION_ONLY';
function normalizePlanetKey(key){if(!key||typeof key!=='object'||Array.isArray(key))throw new Error('canonical planet key required');const names=['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot'],out={};for(const name of names){const value=key[name];if(typeof value!=='bigint')throw new Error('planet key '+name+' must be BigInt');out[name]=value}return Object.freeze(out)}
function resolve(ctx,key){const canonicalKey=normalizePlanetKey(key),planet=A.resolvePlanet(ctx,canonicalKey),snapshot=A.planetaryInputSnapshot(ctx,canonicalKey);if(planet.status!=='PRESENT'||snapshot.status==='ABSENT')return Object.freeze({authority:AUTHORITY,status:'UNSUPPORTED',reason:'P3_ABSENT',key:canonicalKey,planetId:planet?.id?P.hex(planet.id):null,planet,snapshot});const planetId=P.hex(planet.id);if(P.hex(snapshot.planetId)!==planetId)throw new Error('canonical P3 planet identity mismatch');const adapted=P5.adaptP3PlanetaryInputSnapshot(snapshot),physical=P5.realizePhysicalPlanet(ctx,adapted);if(physical.status!=='SUPPORTED')return Object.freeze({authority:AUTHORITY,status:'UNSUPPORTED',reason:'P5_'+physical.reason,key:canonicalKey,planetId,planet,snapshot,physical});if(P.hex(physical.planetId)!==planetId)throw new Error('P5 realization changed canonical planet identity');const topology=P5.createTerrainTopology(physical),environment=E.environmentV2Projection(physical,topology),eligibility=B.eligibility(B.adaptEnvironment(environment)),biology=B.renderingProjection(eligibility);return Object.freeze({authority:AUTHORITY,status:'SUPPORTED',key:canonicalKey,planetId,planet,snapshot,physical,topology,environment,eligibility,biology});}
O.productTarget=Object.freeze({AUTHORITY,normalizePlanetKey,resolve});
})(typeof globalThis!=='undefined'?globalThis:this);
