(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common,R=O.v1MicroRegimeAdapter,A=O.v1x09SourceAnchor;if(!V||!R||!A)throw new Error('V1X-09 experience prerequisites missing');
const VERSION='ofu-v1x-09-micro-matter-experience-1',TRACE_VERSION='ofu-v1x-09-deterministic-journey-1',WITNESS_LIMIT=128,ORDER=Object.freeze(['material','microstructure','molecular','atomic']);
function repId(value){return value?.representationId||value?.materialId||value?.sourceEntityId||null;}
function representationSummary(runtime){const snap=runtime.snapshot(),value=runtime.current();return V.freezeDeep({regime:String(snap.regime).toUpperCase(),sourceEntityId:snap.sourceEntityId,sourceKind:snap.sourceKind,representationId:repId(value),authority:value?.visualAuthority||value?.representationAuthority||value?.chemistryAuthority||value?.authority||runtime.source.authority||'DERIVED',chemistryAuthority:value?.chemistryAuthority||runtime.source.chemistryAuthority||null,coordinateAuthority:value?.coordinateAuthority||null,status:value?.status||'AVAILABLE',featureCount:value?.featureCount??null,unitCount:value?.unitCount??null,atomCount:value?.atomCount??null,quantumBoundary:value?.quantumBoundary||null});}
function makeExperience(runtime,localContext){const anchor=A.create(runtime.source,localContext),witnesses=[];let sequence=0;
 function capture(baseWitness){if(!baseWitness)return null;const value=runtime.current(),summary=representationSummary(runtime),w=V.freezeDeep({contract:'ofu-v1x-09-refinement-witness-1',sequence:sequence++,operation:baseWitness.operation,from:baseWitness.from,to:baseWitness.to,sourceEntityId:baseWitness.sourceEntityId,sourceIdentityPreserved:baseWitness.identityPreserved===true,sourceAnchorDigest:anchor.localContextDigest,semanticMagnification:true,geometricZoomClaim:false,continuity:'SOURCE_ANCHORED_SEMANTIC_REFINEMENT',representationId:repId(value),representationAuthority:summary.authority,chemistryAuthority:summary.chemistryAuthority,coordinateAuthority:summary.coordinateAuthority,resolution:baseWitness.resolution,uncertainty:baseWitness.uncertainty});witnesses.push(w);if(witnesses.length>WITNESS_LIMIT)witnesses.shift();return w;}
 function step(direction){const before=runtime.snapshot().transitionCount,out=runtime.step(direction),after=runtime.snapshot();if(after.transitionCount>before)capture(after.lastWitness);return out;}
 function refine(){return step(-1);}
 function recede(){return step(1);}
 function request(target){target=String(target).toLowerCase();V.assert(ORDER.includes(target),'target regime');const current=runtime.snapshot().regime,ci=current==='local'?-1:ORDER.indexOf(current),ti=ORDER.indexOf(target);V.assert(ti===ci||ti===ci+1,'V1X-09 requests only adjacent forward refinement');if(ti===ci)return snapshot();const before=runtime.snapshot().transitionCount,out=runtime.request(target),after=runtime.snapshot();if(after.transitionCount>before)capture(after.lastWitness);return out;}
 function biologyRefinement(){const source=runtime.source;if(source.kind!=='BIOLOGICAL_TISSUE')return V.freezeDeep({status:'NOT_APPLICABLE',sourceKind:source.kind,authority:'DERIVED'});if(!source.biologicalOrganization)return V.freezeDeep({status:'UNSUPPORTED',reason:'BIOLOGICAL_ORGANIZATION_NOT_SOURCE_BACKED',sourceEntityId:source.sourceEntityId,authority:'DERIVED'});return V.freezeDeep({status:'SUPPORTED_BY_SOURCE_PROVIDER',sourceEntityId:source.sourceEntityId,organismIdentity:source.parentEntityId||null,organization:source.biologicalOrganization,tissueRepresentationId:source.metadata?.legacyTissueRepresentationId||null,cellCount:source.metadata?.legacyCellCount??null,authority:source.authority||'MODEL_DERIVED_SIMULATION',limitations:['V1X-09 does not invent tissue or cell organization; it only exposes organization supplied by an upstream biological provider.']});}
 function resourceWitness(){const s=runtime.snapshot(),p=runtime.portableState();return V.freezeDeep({contract:'ofu-v1x-09-resource-witness-1',sourceEntityId:s.sourceEntityId,regime:s.regime,cacheEntries:s.cacheEntries,cacheLimit:s.cacheLimit,materializations:s.materializations,evictions:s.evictions,caps:p.caps,explicitMicroNodesPersisted:p.explicitMicroNodesPersisted,regeneration:p.regeneration,authority:'DERIVED'});}
 function evict(){const before=resourceWitness(),removed=runtime.evict(),after=resourceWitness();return V.freezeDeep({contract:'ofu-v1x-09-eviction-witness-1',sourceEntityId:anchor.sourceEntityId,removed,before,after,bounded:after.cacheEntries<=after.cacheLimit,authority:'DERIVED'});}
 function returnToSource(){let guard=0;while(runtime.snapshot().regime!=='local'){step(1);guard++;V.assert(guard<=ORDER.length,'return path bounded');}const rec=runtime.reconcile(),restored=A.restore(anchor),exact=A.matches(anchor,restored)&&rec.exactSourceReturn===true&&rec.status==='PASS';return V.freezeDeep({contract:'ofu-v1x-09-reconciliation-witness-1',operation:'RECONCILE',sourceEntityId:anchor.sourceEntityId,sourceAnchorDigest:anchor.localContextDigest,sourceIdentityPreserved:rec.sourceEntityId===anchor.sourceEntityId,exactSourceReturn:exact,localContext:restored,transitionCount:rec.transitionCount,authority:'DERIVED',limitations:anchor.limitations});}
 function snapshot(){const s=runtime.snapshot();return V.freezeDeep({contract:VERSION,sourceAnchor:anchor,regime:String(s.regime).toUpperCase(),representation:representationSummary(runtime),biology:biologyRefinement(),transitionCount:s.transitionCount,lastWitness:witnesses.length?witnesses[witnesses.length-1]:null,resource:resourceWitness(),semanticMagnification:true,geometricZoomClaim:false,authority:'PRESENTATION_ONLY'});}
 function trace(){return V.freezeDeep([...witnesses]);}
 return Object.freeze({VERSION,anchor,runtime,refine,recede,request,snapshot,trace,biologyRefinement,resourceWitness,evict,returnToSource,current:()=>runtime.current()});}
function create(sourceSpec,{localContext={},microOptions={}}={}){return makeExperience(R.create(sourceSpec,microOptions),localContext);}
function fromLegacy(legacyMicroscopic,{localContext={},microOptions={}}={}){return makeExperience(R.fromLegacy(legacyMicroscopic,microOptions),localContext);}
function deterministicJourney(sourceSpec,{localContext={},microOptions={},target='atomic'}={}){target=String(target).toLowerCase();V.assert(ORDER.includes(target),'journey target');const x=create(sourceSpec,{localContext,microOptions}),visited=['LOCAL'];while(x.runtime.snapshot().regime!==target){x.refine();visited.push(String(x.runtime.snapshot().regime).toUpperCase());}const deepest=x.snapshot(),resourceBeforeEviction=x.resourceWitness(),representationDigestBeforeEviction=V.digest('OFU-V1X09-REPRESENTATION',x.current()),eviction=x.evict(),regeneratedRepresentationDigest=V.digest('OFU-V1X09-REPRESENTATION',x.current()),regenerationDeterministic=representationDigestBeforeEviction===regeneratedRepresentationDigest,returned=x.returnToSource(),trace=x.trace();const result={contract:TRACE_VERSION,sourceEntityId:x.anchor.sourceEntityId,sourceAnchorDigest:x.anchor.localContextDigest,target:target.toUpperCase(),visited,deepest,resourceBeforeEviction,eviction,representationDigestBeforeEviction,regeneratedRepresentationDigest,regenerationDeterministic,returned,trace,geometricZoomClaim:false,semanticMagnification:true,authority:'DERIVED'};result.traceDigest=V.digest('OFU-V1X09-JOURNEY',result);return V.freezeDeep(result);}
O.v1x09MicroMatterExperience=Object.freeze({VERSION,TRACE_VERSION,ORDER,WITNESS_LIMIT,create,fromLegacy,deterministicJourney});
})(globalThis);
