(function(root){
'use strict';
const O=root.OFU=root.OFU||{},V=O.v1Common;if(!V)throw new Error('v1 common required before V1X-09 source anchor');
const VERSION='ofu-v1x-09-source-anchor-1',MAX_DEPTH=16,MAX_NODES=4096,MAX_BYTES=65536;
function cloneJson(value){let nodes=0;function visit(v,depth){V.assert(depth<=MAX_DEPTH,'local context depth');nodes++;V.assert(nodes<=MAX_NODES,'local context nodes');if(v===null||typeof v==='string'||typeof v==='boolean')return v;if(typeof v==='number'){V.assert(Number.isFinite(v),'local context finite number');return v;}if(Array.isArray(v))return v.map(x=>visit(x,depth+1));V.assert(v&&typeof v==='object'&&Object.getPrototypeOf(v)===Object.prototype,'local context JSON object');const out={};for(const key of Object.keys(v).sort()){V.assert(v[key]!==undefined&&typeof v[key]!=='function'&&typeof v[key]!=='symbol'&&typeof v[key]!=='bigint','local context JSON value');out[key]=visit(v[key],depth+1);}return out;}const out=visit(value,0),encoded=JSON.stringify(out);V.assert(encoded.length<=MAX_BYTES,'local context bytes');return out;}
function digest(sourceEntityId,context){return V.digest('OFU-V1X09-SOURCE-ANCHOR',sourceEntityId,context);}
function create(source,localContext){V.assert(source&&typeof source.sourceEntityId==='string'&&source.sourceEntityId.length>0,'source entity identity');const exactLocalContext=cloneJson(localContext||{}),localContextDigest=digest(source.sourceEntityId,exactLocalContext);return V.freezeDeep({contract:VERSION,sourceEntityId:source.sourceEntityId,sourceKind:source.kind||'UNKNOWN',parentEntityId:source.parentEntityId||null,localContext:exactLocalContext,localContextDigest,continuity:'EXACT_JSON_SOURCE_CONTEXT',authority:'DERIVED',limitations:['Exact return applies to the captured bounded JSON context, not unmodeled external process state.','The anchor does not claim literal Euclidean continuity across model regimes.']});}
function matches(anchor,localContext){V.assert(anchor&&anchor.contract===VERSION,'source anchor');const exact=cloneJson(localContext||{});return digest(anchor.sourceEntityId,exact)===anchor.localContextDigest;}
function restore(anchor){V.assert(anchor&&anchor.contract===VERSION,'source anchor');return V.freezeDeep(cloneJson(anchor.localContext));}
O.v1x09SourceAnchor=Object.freeze({VERSION,MAX_DEPTH,MAX_NODES,MAX_BYTES,create,matches,restore});
})(globalThis);
