import test from 'node:test';
import assert from 'node:assert/strict';
import { stepEcology, thermodynamicOpportunity } from '../energetics.mjs';
import { deterministicVariant, evaluateSpeciationWitness, selectionStep, validateInnovationGraph } from '../evolution.mjs';
import { routePropagules, successionEligibility } from '../landscape.mjs';

test('thermodynamic opportunity never infers life and source-backed authority requires provenance',()=>{const out=thermodynamicOpportunity({donorAvailable:true,acceptorAvailable:true,freeEnergyGradientProxy:12,pathwayAuthority:'SOURCE_BACKED',source:{id:'ref',reference:'https://example.test/pathway',version:'1'}});assert.equal(out.state,'SOURCE_BACKED_OPPORTUNITY');assert.equal(out.canInferLife,false);assert.equal(out.source.id,'ref');assert.throws(()=>thermodynamicOpportunity({donorAvailable:true,acceptorAvailable:true,freeEnergyGradientProxy:12,pathwayAuthority:'SOURCE_BACKED'}),/source must be a plain record/);});
test('ecology conserves local and global ledgers and responds to shock',()=>{const state={resources:[{id:'r',stock:1000,inflow:0,lossPpm:0}],guilds:[{id:'a',resourceId:'r',population:10,reserve:0,maxUptakePerCapita:10,maintenancePerCapita:8,assimilationPpm:800000,reproductionCost:20,baselineMortalityPpm:0},{id:'b',resourceId:'r',population:10,reserve:0,maxUptakePerCapita:10,maintenancePerCapita:8,assimilationPpm:800000,reproductionCost:20,baselineMortalityPpm:0}]};const control=stepEcology(state);const shock=stepEcology(state,{resourceDelta:{r:-950}});assert.equal(control.resources[0].consumed+control.resources[0].stock+control.resources[0].abioticLoss,1000);assert.equal(control.evidence.totalResourceConsumed,control.evidence.totalUptake);assert.equal(control.evidence.totalUptake,control.evidence.totalAssimilated+control.evidence.totalDissipated);assert.equal(shock.resources[0].consumed+shock.resources[0].stock+shock.resources[0].abioticLoss,50);assert.ok(shock.guilds.reduce((s,g)=>s+g.population,0)<control.guilds.reduce((s,g)=>s+g.population,0));assert.throws(()=>stepEcology(state,{resourceDelta:{typo:-1}}),/unknown resource/);});
test('selection and extinction are criterion driven',()=>{const out=selectionStep([{id:'near',population:1000,trait:100},{id:'far',population:1000,trait:900}],{optimumTrait:100,viabilityWidth:500},{birthPpm:200000,deathPpm:100000});assert.ok(out[0].population>out[1].population);assert.equal(selectionStep([{id:'x',population:1,trait:1000}],{optimumTrait:0,viabilityWidth:1},{birthPpm:0,deathPpm:1000000})[0].extinct,true);});
test('mutation deterministic, length-prefixed policy-bound, and speciation remains non-claim',()=>{const a=deterministicVariant({id:'lin',trait:100},7,{maxMutationStep:20,salt:'s'});assert.deepEqual(a,deterministicVariant({id:'lin',trait:100},7,{maxMutationStep:20,salt:'s'}));const b=deterministicVariant({id:'lin',trait:100},7,{maxMutationStep:21,salt:'s'});assert.notEqual(a.candidateId,b.candidateId);const delimiterA=deterministicVariant({id:'lin',trait:100},7,{version:'x|maxStep:1|salt:y',maxMutationStep:2,salt:'z'}),delimiterB=deterministicVariant({id:'lin',trait:100},7,{version:'x',maxMutationStep:1,salt:'y|maxStep:2|salt:z'});assert.notEqual(delimiterA.candidateId,delimiterB.candidateId);assert.match(a.identityFingerprint64,/^[0-9a-f]{16}$/);const w=evaluateSpeciationWitness({population:100,reproductiveIsolationProxyPpm:900000,persistenceGenerations:100,traitDivergence:500},{minPopulation:50,minIsolationPpm:800000,minPersistenceGenerations:10,minTraitDivergence:100});assert.equal(w.satisfied,true);assert.equal(w.biologicalSpeciesClaim,false);assert.throws(()=>deterministicVariant({trait:100},1,{maxMutationStep:1}),/lineage.id/);});
test('population cap emits rejected-growth witness instead of silent clipping',()=>{const max=1_000_000_000;const o=selectionStep([{id:'cap',population:max,trait:0}],{optimumTrait:0,viabilityWidth:1},{birthPpm:1_000_000,deathPpm:0})[0];assert.equal(o.population,max);assert.equal(o.saturated,true);assert.equal(o.capacityRejectedGrowth,max);assert.equal(o.population+o.capacityRejectedGrowth,max*2);});
test('innovation DAG rejects cycles and duplicate dependencies',()=>{assert.equal(validateInnovationGraph([{id:'a',requires:[]},{id:'b',requires:['a']}]),true);assert.throws(()=>validateInnovationGraph([{id:'a',requires:['b']},{id:'b',requires:['a']}]),/cycle/);assert.throws(()=>validateInnovationGraph([{id:'a',requires:[]},{id:'b',requires:['a','a']}]),/duplicate dependencies/);});
test('dispersal allocation is deterministic under permutation and succession remains nonclaim',()=>{const net={patches:[{id:'p0'},{id:'p1'}],edges:[{id:'e',from:'p0',to:'p1',capacity:10,survivalPpm:500000}]},a=routePropagules(net,[{id:'m1',edgeId:'e',count:10},{id:'m2',edgeId:'e',count:10}]),b=routePropagules(net,[{id:'m2',edgeId:'e',count:10},{id:'m1',edgeId:'e',count:10}]);assert.deepEqual(a,b);assert.equal(a.edgeUse.e,10);assert.equal(a.arrivals.p1,4);assert.equal(a.permutationInvariantGivenUniqueIds,true);assert.throws(()=>routePropagules(net,[{edgeId:'e',count:1}]),/item id is invalid/);const s=successionEligibility({disturbanceAgeTicks:5,resourceIndex:100},{minDisturbanceAgeTicks:2,minResourceIndex:80});assert.equal(s.eligible,true);assert.equal(s.successionStageClaim,false);});
