import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import process from 'node:process';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {chromium,firefox,webkit} from 'playwright';
const require=createRequire(import.meta.url),playwrightVersion=require('playwright/package.json').version;
const name=process.env.BROWSER||'chromium',engines={chromium,firefox,webkit};if(!engines[name])throw new Error('unknown browser '+name);
const browser=await engines[name].launch({headless:true}),file=path.resolve('dist/One_File_Universe.html'),url=pathToFileURL(file).href,build=JSON.parse(fs.readFileSync('dist/p1-p4-build-manifest.json','utf8'));
const context=await browser.newContext(),page=await context.newPage(),requests=[];page.on('request',r=>requests.push({url:r.url(),resourceType:r.resourceType(),navigation:r.isNavigationRequest()}));
await page.addInitScript(()=>{globalThis.__OFU_NET_CALLS__=[];const note=(kind,url)=>globalThis.__OFU_NET_CALLS__.push({kind,url:String(url)});if(globalThis.fetch)globalThis.fetch=(u)=>{note('fetch',u);return Promise.reject(new Error('network disabled by baseline harness'))};if(globalThis.XMLHttpRequest){const X=globalThis.XMLHttpRequest;globalThis.XMLHttpRequest=function(){const x=new X(),open=x.open;x.open=function(m,u,...a){note('xhr',u);return open.call(this,m,u,...a)};return x}}if(globalThis.WebSocket)globalThis.WebSocket=function(u){note('websocket',u);throw new Error('network disabled')};});
async function openWorkspace(workspace){await page.click(`[data-workspace="${workspace}"]`);await page.waitForFunction(name=>{const panel=document.querySelector(`[data-workspace-panel="${name}"]`),tab=document.querySelector(`[data-workspace="${name}"]`);return !!panel&&!panel.hidden&&tab?.getAttribute('aria-selected')==='true'&&globalThis.OFU?.productUI?.state?.workspace===name},workspace,{timeout:10000})}
try{
 await page.goto(url,{waitUntil:'load'});await page.waitForFunction(()=>globalThis.__OFU_BASELINE_REPORT__?.status==='READY'&&globalThis.__OFU_PRODUCT_UI__===globalThis.OFU?.productUI?.state&&globalThis.OFU?.productUI?.state?.workspace==='explore'&&document.documentElement.dataset.workspace==='explore',{timeout:30000});
 const ready=await page.evaluate(()=>globalThis.__OFU_BASELINE_REPORT__);if(ready.sourceCommit!==process.env.OFU_SOURCE_SHA)throw new Error('artifact source pin mismatch');
 await openWorkspace('inspect');
 const first=await page.evaluate(()=>({id:document.getElementById('entity-id').textContent,digest:document.getElementById('entity-digest').textContent,output:document.getElementById('entity-output').textContent}));if(!/^[0-9a-f]{64}$/.test(first.id)||!/^[0-9a-f]{64}$/.test(first.digest))throw new Error('known System was not resolved');
 await page.click('#requery');const reordered=await page.evaluate(()=>({id:document.getElementById('entity-id').textContent,digest:document.getElementById('entity-digest').textContent,output:document.getElementById('entity-output').textContent}));if(reordered.id!==first.id||reordered.digest!==first.digest||!reordered.output.includes('PASS'))throw new Error('P3 query-order invariant failed in shipped UI');
 await page.selectOption('#entity-type','Planet');await page.waitForTimeout(0);await page.click('#query');const planet=await page.evaluate(()=>({id:document.getElementById('entity-id').textContent,digest:document.getElementById('entity-digest').textContent}));if(!/^[0-9a-f]{64}$/.test(planet.id)||planet.id===first.id)throw new Error('known Planet was not resolved distinctly');
 await openWorkspace('lab');await page.click('#world-create');await page.click('#event-submit');await page.click('#world-checkpoint');const temporal=await page.evaluate(()=>({eventId:document.getElementById('event-id').textContent,digest:document.getElementById('world-digest').textContent,text:document.getElementById('temporal-output').textContent}));if(!/^[0-9a-f]{64}$/.test(temporal.eventId)||!/^[0-9a-f]{64}$/.test(temporal.digest)||!temporal.text.includes('coveredEventCount'))throw new Error('P4 event/checkpoint/compact/replay journey failed');
 await page.click('#archive-export');const exported=await page.inputValue('#archive');if(exported.length<20||exported.length%2)throw new Error('archive export missing');const digestBefore=temporal.digest;await page.click('#archive-import');const afterImport=await page.textContent('#world-digest');if(afterImport!==digestBefore)throw new Error('archive round-trip changed mutable digest');
 await page.reload({waitUntil:'load'});await page.waitForFunction(()=>globalThis.__OFU_BASELINE_REPORT__?.status==='READY'&&globalThis.__OFU_PRODUCT_UI__===globalThis.OFU?.productUI?.state&&globalThis.OFU?.productUI?.state?.workspace==='explore'&&document.documentElement.dataset.workspace==='explore',{timeout:30000});await openWorkspace('inspect');await page.selectOption('#entity-type','Planet');await page.click('#query');const reopened=await page.evaluate(()=>({id:document.getElementById('entity-id').textContent,digest:document.getElementById('entity-digest').textContent}));if(reopened.id!==planet.id||reopened.digest!==planet.digest)throw new Error('fresh reopen changed P3 canonical entity');
 const networkCalls=await page.evaluate(()=>globalThis.__OFU_NET_CALLS__||[]),unexpected=requests.filter(r=>!(r.navigation&&r.resourceType==='document'&&r.url===url)&&!r.url.startsWith('data:')&&!r.url.startsWith('blob:')&&!r.url.startsWith('about:'));if(networkCalls.length||unexpected.length)throw new Error('network/single-file invariant failed: '+JSON.stringify({networkCalls,unexpected}));
 const evidence={status:'PASS',test:'P1-P4-SHIPPED-USER-JOURNEY-v1',sourceCommit:process.env.OFU_SOURCE_SHA,browser:name,browserVersion:browser.version(),playwrightVersion,nodeVersion:process.version,platform:process.platform,arch:process.arch,osRelease:os.release(),artifactSha256:build.artifactSha256,artifactBytes:build.artifactBytes,componentManifestHash:build.componentManifestHash,universeIdentity:ready.universeIdentity,workspaceNavigation:true,workspaceReadySignal:true,system:{id:first.id,digest:first.digest},planet,mutableDigest:digestBefore,archiveBytes:exported.length/2,networkRequests:requests.length,unexpectedNetworkRequests:unexpected.length,realSafariIOSVerified:false};fs.mkdirSync('dist/evidence/baseline',{recursive:true});fs.writeFileSync(`dist/evidence/baseline/browser-${process.platform}-${process.arch}-${name}.json`,JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
}finally{await context.close();await browser.close()}
