// V1X-17 research deterministic kernel. Node-only research hash runtime; no shipping authority.
import {createHash} from 'node:crypto';
export const CONTRACT='ofu-v1x17-life-evolution-research-v1',ENV='ofu-v1x17-environment-readiness-research-v1',REPLAY='ofu-v1x17-p4-bound-replay-research-v1',REFINE='ofu-v1x17-aggregate-organism-refinement-research-v1',MODEL='v1x17-life-ecology-evolution-fixed-v1',AUTHORITY='MODEL_DERIVED_SIMULATION',FROZEN_P6='ofu-p6-biosphere-v1',P4='ofu-p4-temporal-v1';
export const ENV_CONTRACT=ENV,REPLAY_CONTRACT=REPLAY,REFINEMENT_CONTRACT=REFINE;
export const LIMIT=Object.freeze({populations:64,lineages:128,edges:256,traits:16,samples:128,replay:1024}),PPM=1000000n,U64=(1n<<64n)-1n,I64MIN=-(1n<<63n),I64MAX=(1n<<63n)-1n,ZERO='0'.repeat(64);
export const bad=m=>{throw Error('V1X17 research: '+m)},txt=(v,n)=>{if(typeof v!=='string'||!v||v!==v.normalize('NFC'))bad(n);return v},u=(v,n)=>{if(typeof v!=='bigint'||v<0n||v>U64)bad(n);return v},ppm=(v,n)=>{u(v,n);if(v>PPM)bad(n);return v},arr=(v,n,m)=>{if(!Array.isArray(v)||v.length>m)bad(n);return v},min=(...x)=>x.reduce((a,b)=>a<b?a:b),add=(a,b,n)=>{u(a,n);u(b,n);let z=a+b;if(z>U64)bad(n+' overflow');return z};
export const mulPpm=(v,q)=>u(v,'value')*ppm(q,'ppm')/PPM;
export function encode(v){if(v===null)return'null';if(typeof v==='boolean')return v?'true':'false';if(typeof v==='string')return JSON.stringify(v.normalize('NFC'));if(typeof v==='bigint')return'{"$bigint":'+JSON.stringify(v.toString())+'}';if(Array.isArray(v))return'['+v.map(encode).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+encode(v[k])).join(',')+'}';bad('non-deterministic value')}
export const digest=(v,d='OFU-V1X17-v1')=>createHash('sha256').update(d+'\0'+encode(v),'utf8').digest('hex'),rid=(k,v)=>'r17:'+k+':'+digest(v,'OFU-V1X17-ID-'+k+'-v1');
export function sci(x,n){if(!x||!['FORMAL','EMPIRICAL_EARTH','APPROXIMATE','HYPOTHETICAL','STYLIZED'].includes(x.classification))bad(n+' class');arr(x.sourceIds,n+' sources',16).forEach(s=>txt(s,n+' source'));['validityDomain','assumptions','fidelity','uncertainty'].forEach(k=>txt(x[k],n+' '+k));return x}
export const METADATA=Object.freeze({authority:AUTHORITY,canonicalPromotion:false,frozenP6:FROZEN_P6,p4Owner:P4,numerics:'BigInt + ppm floor',floatingPointState:false,hashRuntime:'Node SHA-256 research only; promoted/browser form must use OFU hash seam and preserve golden vectors',crossScale:['REFINE','PROJECT','RECONCILE'],unsupported:['abiogenesis','occupancy inference','universal trophic efficiency','network stability inference','universal species threshold','molecular genetics','persistent organisms','alien morphology','direct canonical environment mutation']});
