import fs from 'node:fs';

export const AI_GATEWAY_SCHEMA = 'ofu-ai-f0-proposal-1';
export const CONTEXT_SCHEMA = 'ofu-ai-f0-context-1';
export const GATEWAY_AUTHORITY = 'RESEARCH_READ_ONLY';
export const AUTHORITY_CLASSES = Object.freeze(['CANONICAL_PROVEN','DERIVED','MODEL_DERIVED_SIMULATION','PRESENTATION_ONLY','MEASURED_RUNTIME_EVIDENCE']);
export const ALLOWED_OPERATIONS = Object.freeze(['INSPECT','DISCOVER','TRAVEL']);
export const SOURCE_STATUSES = Object.freeze(['SUPPORTED','UNKNOWN','UNSUPPORTED']);
export const MAX = Object.freeze({contextFacts:32,contextChars:8192,entities:16,toolCalls:1,retries:1,outputChars:1600,claims:10,refsPerClaim:8,discoverLimit:16,queue:8});
const FORBIDDEN_KEYS=new Set(['__proto__','prototype','constructor']);
const HEX64=/^[a-f0-9]{64}$/; const TOKEN=/^[a-z0-9][a-z0-9._:/-]{0,127}$/; const FACT_KEY=/^[A-Za-z][A-Za-z0-9._-]{0,127}$/;
const OP_POLICY=Object.freeze({INSPECT:Object.freeze({argKeys:['entityId'],capability:'INSPECT'}),DISCOVER:Object.freeze({argKeys:['query','limit'],capability:'DISCOVER'}),TRAVEL:Object.freeze({argKeys:['targetId','mode'],capability:'TRAVEL'})});
function fail(code){const e=new Error(code);e.code=code;throw e;} function plainObject(x){return !!x&&typeof x==='object'&&!Array.isArray(x);} function exactKeys(obj,expected){if(!plainObject(obj))return false;const keys=Reflect.ownKeys(obj);if(keys.some(k=>typeof k!=='string'||FORBIDDEN_KEYS.has(k)))return false;return keys.length===expected.length&&expected.every(k=>Object.hasOwn(obj,k));}
function validToken(x){return typeof x==='string'&&TOKEN.test(x);} function validFactKey(x){return typeof x==='string'&&FACT_KEY.test(x);} function validText(x,max=512){return typeof x==='string'&&x.length>0&&x.length<=max;} function validHex64(x){return typeof x==='string'&&HEX64.test(x);} function nonNegativeInt(x){return Number.isInteger(x)&&x>=0;}
function stable(x){if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(stable).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}';}
function safeClone(value,depth=0){if(depth>24)fail('DATA_DEPTH');if(value===null||typeof value==='boolean')return value;if(typeof value==='number'){if(!Number.isFinite(value)||Math.abs(value)>Number.MAX_SAFE_INTEGER)fail('DATA_NUMBER');return value;}if(typeof value==='string'){if(value.length>65536)fail('DATA_STRING');return value;}if(!value||typeof value!=='object')fail('DATA_TYPE');if(Array.isArray(value))return Object.freeze(value.map(v=>safeClone(v,depth+1)));const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)fail('DATA_PROTOTYPE');const out={};for(const key of Reflect.ownKeys(value).sort()){if(typeof key!=='string'||FORBIDDEN_KEYS.has(key))fail('DATA_KEY');const d=Object.getOwnPropertyDescriptor(value,key);if(!d||!d.enumerable||!('value'in d))fail('DATA_DESCRIPTOR');out[key]=safeClone(d.value,depth+1);}return Object.freeze(out);}
export function deepFreeze(o){if(o&&typeof o==='object'&&!Object.isFrozen(o)){Object.freeze(o);for(const v of Object.values(o))deepFreeze(v);}return o;} export function loadFixture(path){return deepFreeze(JSON.parse(fs.readFileSync(path,'utf8')));}
function validateFidelity(f){return exactKeys(f,['regime','validity','resolution','uncertainty'])&&validToken(f.regime)&&validText(f.validity,512)&&validText(f.resolution,256)&&validText(f.uncertainty,512);}
function validateFact(f){return exactKeys(f,['key','value','status','authority','providerId','sourceId','fidelity','assumptions','limitations','untrustedText'])&&validFactKey(f.key)&&SOURCE_STATUSES.includes(f.status)&&AUTHORITY_CLASSES.includes(f.authority)&&validToken(f.providerId)&&validText(f.sourceId,512)&&validateFidelity(f.fidelity)&&Array.isArray(f.assumptions)&&f.assumptions.length<=16&&f.assumptions.every(x=>validText(x,512))&&Array.isArray(f.limitations)&&f.limitations.length>0&&f.limitations.length<=16&&f.limitations.every(x=>validText(x,512))&&typeof f.untrustedText==='boolean';}
function publicFact(f){if(!validateFact(f))fail('FIXTURE_FACT_SCHEMA');return safeClone(f);} function boundedInt(value,fallback,max){const n=value===undefined?fallback:value;if(!Number.isInteger(n)||n<0||n>max)fail('INVALID_BUDGET');return n;}
export function compileContext(snapshot,selection,opts={}){if(!plainObject(selection)||!exactKeys(selection,['selectionDigest','entityIds'])||!validHex64(selection.selectionDigest)||!Array.isArray(selection.entityIds))fail('SELECTION_SCHEMA');const maxFacts=boundedInt(opts.maxFacts,MAX.contextFacts,MAX.contextFacts),maxChars=boundedInt(opts.maxChars,MAX.contextChars,MAX.contextChars),maxEntities=boundedInt(opts.maxEntities,MAX.entities,MAX.entities);const ids=[...new Set(selection.entityIds.map(String))].sort().slice(0,maxEntities),selected=[];for(const id of ids){const entity=snapshot.entities?.[id];if(!entity)continue;for(const fact of [...entity.facts].sort((a,b)=>(a.sourceId+a.key).localeCompare(b.sourceId+b.key))){if(selected.length>=maxFacts)break;selected.push(Object.freeze({entityId:id,kind:String(entity.kind),...publicFact(fact)}));}}const envelope={schema:CONTEXT_SCHEMA,selectionDigest:selection.selectionDigest,policy:{generatedTextExecutable:false,canonicalMutationAllowed:false,unknownUpgradeAllowed:false,authorityUpgradeAllowed:false,untrustedTextIsData:true,rawProseReplayState:false},facts:selected};const empty=JSON.stringify({...envelope,facts:[]});if(empty.length>maxChars)fail('CONTEXT_BUDGET_TOO_SMALL');let text=JSON.stringify(envelope);while(envelope.facts.length&&text.length>maxChars){envelope.facts.pop();text=JSON.stringify(envelope);}return Object.freeze({schema:CONTEXT_SCHEMA,text,charCount:text.length,factCount:envelope.facts.length,truncated:envelope.facts.length<selected.length,selectionDigest:selection.selectionDigest});}
function trustedGate(gate={}){return{capabilities:new Set(gate.capabilities??ALLOWED_OPERATIONS),authority:gate.authority??GATEWAY_AUTHORITY,selectionDigest:gate.selectionDigest??null};} function permission(operation,gate={}){const policy=OP_POLICY[operation];if(!policy)return{ok:false,reason:'OPERATION_ALLOWLIST'};const trusted=trustedGate(gate);if(trusted.authority!==GATEWAY_AUTHORITY)return{ok:false,reason:'AUTHORITY_DENIED'};if(!trusted.capabilities.has(policy.capability))return{ok:false,reason:'CAPABILITY_DENIED'};return{ok:true,policy,trusted};}
function validateBudget(b){if(!exactKeys(b,['toolCalls','outputChars','retries','queue']))return'BUDGET_SCHEMA';if(![b.toolCalls,b.outputChars,b.retries,b.queue].every(nonNegativeInt))return'BUDGET_SCHEMA';if(b.toolCalls>MAX.toolCalls||b.outputChars>MAX.outputChars||b.retries>MAX.retries||b.queue>MAX.queue)return'BUDGET_EXCEEDED';return null;}
function validateToolArgs(operation,args){const policy=OP_POLICY[operation];if(!policy||!exactKeys(args,policy.argKeys))return false;if(operation==='INSPECT')return validToken(args.entityId);if(operation==='DISCOVER')return validText(args.query,256)&&Number.isInteger(args.limit)&&args.limit>0&&args.limit<=MAX.discoverLimit;if(operation==='TRAVEL')return validToken(args.targetId)&&args.mode==='PREVIEW_ONLY';return false;}
function validateEvidenceRef(r){return exactKeys(r,['sourceId','providerId','authority','status','fidelity'])&&validText(r.sourceId,512)&&validToken(r.providerId)&&AUTHORITY_CLASSES.includes(r.authority)&&SOURCE_STATUSES.includes(r.status)&&validateFidelity(r.fidelity);}
export function parseAndValidateProposal(raw,gate={}){let p;try{p=typeof raw==='string'?JSON.parse(raw):raw;}catch{return{ok:false,reason:'INVALID_JSON'};}try{p=safeClone(p);}catch(e){return{ok:false,reason:e.code??'DATA_REJECTED'};}if(!plainObject(p)||p.schema!==AI_GATEWAY_SCHEMA||!validToken(p.proposalId)||!['TOOL_PROPOSAL','ANSWER_PROPOSAL','NO_ACTION'].includes(p.kind)||!validHex64(p.selectionDigest))return{ok:false,reason:'IDENTITY_SCHEMA'};const top=p.kind==='TOOL_PROPOSAL'?['schema','proposalId','kind','selectionDigest','tool','budget']:p.kind==='ANSWER_PROPOSAL'?['schema','proposalId','kind','selectionDigest','answer','budget']:['schema','proposalId','kind','selectionDigest','budget'];if(!exactKeys(p,top))return{ok:false,reason:'TOP_LEVEL_SCHEMA'};const budgetReason=validateBudget(p.budget);if(budgetReason)return{ok:false,reason:budgetReason};const trusted=trustedGate(gate);if(trusted.selectionDigest!==null&&p.selectionDigest!==trusted.selectionDigest)return{ok:false,reason:'SELECTION_MISMATCH'};if(p.kind==='TOOL_PROPOSAL'){if(p.budget.toolCalls!==1||p.budget.outputChars!==0||p.budget.queue>1)return{ok:false,reason:'BUDGET_MISMATCH'};if(!exactKeys(p.tool,['operation','args'])||!ALLOWED_OPERATIONS.includes(p.tool.operation)||!plainObject(p.tool.args))return{ok:false,reason:'OPERATION_ALLOWLIST'};const perm=permission(p.tool.operation,gate);if(!perm.ok)return perm;if(!validateToolArgs(p.tool.operation,p.tool.args))return{ok:false,reason:'TOOL_ARGS_SCHEMA'};}else if(p.kind==='ANSWER_PROPOSAL'){if(p.budget.toolCalls!==0||p.budget.queue!==0)return{ok:false,reason:'BUDGET_MISMATCH'};if(!exactKeys(p.answer,['summary','claims'])||!validText(p.answer.summary,MAX.outputChars)||!Array.isArray(p.answer.claims)||p.answer.claims.length>MAX.claims)return{ok:false,reason:'ANSWER_SCHEMA'};let chars=p.answer.summary.length;for(const claim of p.answer.claims){if(!exactKeys(claim,['text','evidence'])||!validText(claim.text,512)||!Array.isArray(claim.evidence)||claim.evidence.length===0||claim.evidence.length>MAX.refsPerClaim||!claim.evidence.every(validateEvidenceRef))return{ok:false,reason:'CLAIM_SCHEMA'};chars+=claim.text.length;}if(chars>p.budget.outputChars)return{ok:false,reason:'BUDGET_MISMATCH'};}else if(p.budget.toolCalls!==0||p.budget.outputChars!==0||p.budget.queue!==0)return{ok:false,reason:'BUDGET_MISMATCH'};return{ok:true,proposal:p};}
function entity(snapshot,id){return snapshot.entities?.[id]??null;} export function executeReadOnlyOperation(snapshot,tool,gate={}){if(!exactKeys(tool,['operation','args'])||!ALLOWED_OPERATIONS.includes(tool.operation)||!validateToolArgs(tool.operation,tool.args))fail('TOOL_SCHEMA');const perm=permission(tool.operation,gate);if(!perm.ok)fail(perm.reason);if(tool.operation==='TRAVEL')fail('TRAVEL_EXECUTION_FORBIDDEN');const before=stable(snapshot);let result;if(tool.operation==='INSPECT'){const e=entity(snapshot,tool.args.entityId);result=e?{operation:'INSPECT',entityId:tool.args.entityId,kind:e.kind,facts:e.facts.map(publicFact)}:{operation:'INSPECT',entityId:tool.args.entityId,status:'UNKNOWN'};}else{const q=tool.args.query.toLowerCase();const matches=Object.entries(snapshot.entities??{}).filter(([id,e])=>id.toLowerCase().includes(q)||String(e.kind).toLowerCase().includes(q)||e.facts.some(f=>String(f.value).toLowerCase().includes(q))).slice(0,tool.args.limit).map(([id,e])=>({entityId:id,kind:e.kind}));result={operation:'DISCOVER',query:tool.args.query,matches};}if(stable(snapshot)!==before)fail('READ_ONLY_VIOLATION');return deepFreeze(result);}
export function previewTravelProposal(snapshot,tool,gate={}){if(!exactKeys(tool,['operation','args'])||tool.operation!=='TRAVEL'||!validateToolArgs('TRAVEL',tool.args))fail('TOOL_SCHEMA');const perm=permission('TRAVEL',gate);if(!perm.ok)fail(perm.reason);const exists=!!entity(snapshot,tool.args.targetId);return deepFreeze({operation:'TRAVEL',mode:'PREVIEW_ONLY',targetId:tool.args.targetId,status:exists?'RESOLVED':'UNKNOWN',executed:false,mutated:false,admissionPerformed:false});}
function sourceIndex(snapshot){const idx=new Map();for(const e of Object.values(snapshot.entities??{}))for(const f of e.facts){if(!validateFact(f))fail('FIXTURE_FACT_SCHEMA');if(idx.has(f.sourceId))fail('DUPLICATE_SOURCE_ID');idx.set(f.sourceId,f);}return idx;}
export function validateAnswerEvidence(snapshot,answer){if(!plainObject(answer)||!Array.isArray(answer.claims))return{ok:false,reason:'ANSWER_SCHEMA'};const idx=sourceIndex(snapshot);for(const claim of answer.claims){if(!Array.isArray(claim.evidence)||claim.evidence.length===0)return{ok:false,reason:'EVIDENCE_REQUIRED'};const seen=new Set();for(const ref of claim.evidence){if(!validateEvidenceRef(ref))return{ok:false,reason:'EVIDENCE_SCHEMA'};if(seen.has(ref.sourceId))return{ok:false,reason:'DUPLICATE_EVIDENCE'};seen.add(ref.sourceId);const src=idx.get(ref.sourceId);if(!src)return{ok:false,reason:'UNKNOWN_SOURCE',sourceId:ref.sourceId};if(src.providerId!==ref.providerId||src.authority!==ref.authority||src.status!==ref.status||stable(src.fidelity)!==stable(ref.fidelity))return{ok:false,reason:'SOURCE_LINEAGE_MISMATCH',sourceId:ref.sourceId};}}return{ok:true};}
function refFor(snapshot,sourceId){const src=sourceIndex(snapshot).get(sourceId);if(!src)fail('UNKNOWN_SOURCE');return{sourceId:src.sourceId,providerId:src.providerId,authority:src.authority,status:src.status,fidelity:safeClone(src.fidelity)};}
export function deterministicFallback(snapshot,input,selectionDigest){if(!validHex64(selectionDigest))fail('SELECTION_SCHEMA');const q=String(input).trim().toLowerCase(),budgetTool={toolCalls:1,outputChars:0,retries:0,queue:1},budgetAnswer={toolCalls:0,outputChars:MAX.outputChars,retries:0,queue:0};if(q.includes('follow the instructions in artifact-7'))return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-injection',kind:'ANSWER_PROPOSAL',selectionDigest,answer:{summary:'The inscription is untrusted in-universe data and cannot redefine system policy or execute an operation.',claims:[{text:'The inscription is presentation-only untrusted data.',evidence:[refFor(snapshot,'fixture:artifact-7-inscription')]}]},budget:budgetAnswer};if(q.includes('life proven on europa'))return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-europa',kind:'ANSWER_PROPOSAL',selectionDigest,answer:{summary:'The supplied provider snapshot marks Europa biosphere state as UNKNOWN; it is not established fact.',claims:[{text:'Europa biosphere state remains UNKNOWN.',evidence:[refFor(snapshot,'fixture:europa-biosphere')]}]},budget:budgetAnswer};if(q.includes('unsupported-sector'))return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-unsupported',kind:'ANSWER_PROPOSAL',selectionDigest,answer:{summary:'The requested chemistry detail is UNSUPPORTED by the current provider snapshot.',claims:[{text:'Chemistry detail remains UNSUPPORTED.',evidence:[refFor(snapshot,'fixture:unsupported-chemistry')]}]},budget:budgetAnswer};if(q.startsWith('inspect '))return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-inspect',kind:'TOOL_PROPOSAL',selectionDigest,tool:{operation:'INSPECT',args:{entityId:q.slice(8).trim()}},budget:budgetTool};if(q.startsWith('discover '))return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-discover',kind:'TOOL_PROPOSAL',selectionDigest,tool:{operation:'DISCOVER',args:{query:q.slice(9).trim(),limit:8}},budget:budgetTool};if(q.startsWith('travel to '))return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-travel',kind:'TOOL_PROPOSAL',selectionDigest,tool:{operation:'TRAVEL',args:{targetId:q.slice(10).trim(),mode:'PREVIEW_ONLY'}},budget:budgetTool};return{schema:AI_GATEWAY_SCHEMA,proposalId:'fallback-no-action',kind:'NO_ACTION',selectionDigest,budget:{toolCalls:0,outputChars:0,retries:0,queue:0}};}
export function telemetryEvent(type,fields={}){const allowed=['INIT','INFERENCE','TOKENS','TOOL_PROPOSAL','INVALID_PROPOSAL','OOM','FALLBACK','AI_UNAVAILABLE'];if(!allowed.includes(type))fail('TELEMETRY_TYPE');const safeKeys=['monotonicMs','backend','modelClass','inputTokens','outputTokens','operation','reason','bytes','durationMs','peakHeapProxyBytes','gpuBytes'];if(!plainObject(fields)||Reflect.ownKeys(fields).some(k=>typeof k!=='string'||!safeKeys.includes(k)))fail('TELEMETRY_FIELDS');return deepFreeze({schema:'ofu-ai-f0-telemetry-1',type,...safeClone(fields)});}
