import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
globalThis.OFU={};
for(const file of ['src/kernel/sha256.js','src/extensions/contracts.js','src/v1x-11-runtime-streaming-resources/lifecycle.js','src/v1x-11-runtime-streaming-resources/scheduler.js','src/v1x-11-runtime-streaming-resources/resource-manager.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});
const {v1x11Resources,pxContracts:C}=globalThis.OFU,h=x=>crypto.createHash('sha256').update(x).digest('hex');
const defs=[['px.scene.macro','macro'],['px.scene.planet','planet'],['px.scene.surface','surface'],['px.representation.life','life'],['px.representation.civilization','civilization'],['px.representation.micro','micro']],ids=new Set(defs.map(x=>x[0])),registry={descriptor(id){assert(ids.has(id));return{id};}};
function build(){const m=v1x11Resources.create({providerRegistry:registry,budgets:{cpuBytes:1200,gpuBytes:1200,entities:120,draws:120,entries:12,workers:2,queue:8,jobs:10}});for(const [providerId,domain] of defs)m.registerMaterializer({providerId,domain,async load(q){const warm=q.targetState==='WARM';return{identity:q.identity,semanticDigest:q.semanticDigest,state:q.targetState,cpuBytes:64,gpuBytes:warm?0:64,entities:1,draws:warm?0:1,cpuHandle:{},gpuHandle:warm?null:{}};},releaseCpu(){},releaseGpu(){}});return m;}
const path=['macro','planet','surface','life','civilization','micro','surface','planet','macro'],byDomain=new Map(defs.map(([id,d])=>[d,id]));let manager=build(),anchorDigest=null,anchorIdentity=null;
const intent=(domain,name)=>({identity:{providerId:byDomain.get(domain),entityId:h(name),representationId:'primary'},domain,state:'IMMEDIATE',semantic:{stableIdentity:name,historyDigest:h('history-0')},presentation:{requestedQuality:'FULL'},estimate:{cpuBytes:64,gpuBytes:64,entities:1,draws:1}});
for(let journey=0;journey<80;journey++)for(let step=0;step<path.length;step++){const domain=path[step],name=domain==='macro'&&step===path.length-1?'anchor':'j'+journey+'-'+domain+'-'+step,raw=intent(domain,name);const results=await manager.reconcileWorkingSet([raw]);assert(results.every(r=>r.status==='fulfilled'));if(name==='anchor'){const w=results[0].value;if(anchorDigest===null){anchorDigest=w.semanticDigest;anchorIdentity=w.identity.entityId;}else{assert.equal(w.semanticDigest,anchorDigest);assert.equal(w.identity.entityId,anchorIdentity);}}if(journey%10===0&&domain==='surface'&&step===2){manager.contextLoss('webgl2');await manager.contextRestore('webgl2');}}
await manager.reconcileWorkingSet([]);await manager.reconcileWorkingSet([]);await manager.reconcileWorkingSet([]);await manager.drain();const before=manager.snapshot();assert(before.workingSet.entries<=12);assert(before.peak.cpuBytes<=1200);assert(before.peak.gpuBytes<=1200);assert(before.scheduler.metrics.peakQueued<=8);assert(before.metrics.evictions>0);assert(before.metrics.contextRecoveries>0);
const saved={identity:{providerId:'px.scene.macro',entityId:h('anchor'),representationId:'primary'},domain:'macro',state:'IMMEDIATE',semantic:{stableIdentity:'anchor',historyDigest:h('history-0')},presentation:{requestedQuality:'FULL'},estimate:{cpuBytes:64,gpuBytes:64,entities:1,draws:1}},serialized=JSON.stringify(saved),restored=JSON.parse(serialized);manager=build();const after=await manager.request(restored);assert.equal(after.identity.entityId,h('anchor'));assert.equal(after.semanticDigest,C.digest(restored.semantic));assert.equal(after.semanticDigest,anchorDigest);
console.log(JSON.stringify({status:'PASS',oracle:'v1x11-long-traversal-revisit-eviction-context-reload',journeys:80,steps:80*path.length,anchorIdentity,anchorDigest,beforeReload:before,afterReload:manager.snapshot(),physicalDevices:{android:'NOT_VERIFIED',ios:'NOT_VERIFIED'}}));
