(function(root){
'use strict';
const O=root.OFU,C=O&&O.planetRenderCore,G=O&&O.planetWebGL2,A=O&&O.p3Astronomy,P5=O&&O.p5Planetology,E=O&&O.p5EnvironmentV2,B=O&&O.p6Biosphere;
if(!C||!G||!A||!P5||!E||!B||typeof document==='undefined')return;
function previewSelection(){const spec=O.BASELINE_BUILD?.rendering?.previewPlanetKey;if(!spec)throw new Error('certified preview planet selector missing from build manifest');const key=Object.freeze(Object.fromEntries(Object.entries(spec).map(([k,v])=>[k,BigInt(v)]))),snapshot=A.planetaryInputSnapshot({masterSeed:Uint8Array.from({length:32},(_,i)=>i),semanticManifestHash:A.semanticManifestHash()},key);if(snapshot.status==='ABSENT')throw new Error('certified preview planet became ABSENT');return{key,snapshot}}
function boot(){
 const canvas=document.getElementById('planet-view');if(!canvas)return;
 const masterSeed=Uint8Array.from({length:32},(_,i)=>i),ctx={masterSeed,semanticManifestHash:A.semanticManifestHash()},chosen=previewSelection(),adapted=P5.adaptP3PlanetaryInputSnapshot(chosen.snapshot),physical=P5.realizePhysicalPlanet(ctx,adapted);if(physical.status!=='SUPPORTED')throw new Error('preview P5 realization unsupported');
 const expectedId=O.BASELINE_BUILD.rendering.previewPlanetId,actualId=O.p2.hex(physical.planetId);if(actualId!==expectedId)throw new Error('certified preview planet identity drift');
 const provider=C.createP5Provider(ctx,physical,{presentationElevationScale:120}),environment=E.environmentV2Projection(physical,provider.topology),eligibility=B.eligibility(B.adaptEnvironment(environment)),biology=B.renderingProjection(eligibility),radius=Number(physical.physical.meanRadiusM),session=C.createSession(provider,{maxCpuMeshes:48,maxActivePatches:24}),camera=C.createCamera(radius,{distanceRadii:30,targetDirection:[0.18,0.12,1]}),state={ctx,chosen,physical,provider,environment,eligibility,biology,session,camera,lastTime:performance.now(),lastPlanAt:0,backend:'pending',draw:null,frameTimes:[],regime:C.semanticScale(radius,camera.distanceM),disposed:false};
 if(eligibility.state!==O.BASELINE_BUILD.rendering.previewP6EligibilityState||biology.biologyEstablished!==false||O.p2.hex(eligibility.witnessDigest)!==O.BASELINE_BUILD.rendering.previewP6EligibilityWitnessDigest)throw new Error('certified preview P6 state drift');
 const ui={scale:document.getElementById('render-scale'),distance:document.getElementById('render-distance'),patches:document.getElementById('render-patches'),gpu:document.getElementById('render-gpu'),backend:document.getElementById('render-backend'),planet:document.getElementById('render-planet'),depth:document.getElementById('render-depth'),environment:document.getElementById('render-environment'),p6:document.getElementById('render-p6'),biosphere:document.getElementById('render-biosphere')};
 if(ui.planet)ui.planet.textContent=provider.planetId.slice(0,16)+'… / R '+radius.toLocaleString()+' m';
 if(ui.environment)ui.environment.textContent=environment.authority+' / '+environment.contractId;
 if(ui.p6)ui.p6.textContent=eligibility.state;
 if(ui.biosphere)ui.biosphere.textContent=biology.biologyEstablished?'YES':'NO';
 function resize(){const d=Math.min(2,Math.max(1,devicePixelRatio||1)),r=canvas.getBoundingClientRect(),w=Math.max(2,Math.round(r.width*d)),h=Math.max(2,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
 function plan(now){if(now-state.lastPlanAt<100&&state.session.active.size)return;state.lastPlanAt=now;const snap=C.cameraSnapshot(camera),p=C.mixedLodPlan({targetDirection:camera.direction,radiusM:radius,distanceM:snap.distanceM,viewportHeight:canvas.height,maxLevel:9,maxPatches:24,previousLevel:session.previousLevel});C.activate(session,p,{skirts:true});state.plan=p}
 function frame(now){if(state.disposed)return;resize();const elapsed=(now-state.lastTime)/1000,dt=Number.isFinite(elapsed)?Math.max(0,elapsed):0;state.lastTime=now;const snap=C.stepCamera(camera,dt);plan(now);const t0=performance.now(),draw=G.renderPortable(canvas,session,snap,{maxGpuMeshes:48,maxGpuBytes:8*1024*1024}),renderMs=performance.now()-t0;state.draw=draw;state.backend=draw.backend;state.regime=snap.scale;state.frameTimes.push(renderMs);if(state.frameTimes.length>240)state.frameTimes.shift();if(ui.scale)ui.scale.textContent=snap.scale;if(ui.distance)ui.distance.textContent=(snap.distanceM/radius).toFixed(3)+' R';if(ui.patches)ui.patches.textContent=session.active.size+' active / '+session.cache.map.size+' CPU retained';if(ui.gpu)ui.gpu.textContent=draw.gpu?draw.gpu.liveMeshes+' meshes / '+draw.gpu.liveTrackedBytes+' tracked bytes':'fallback';if(ui.backend)ui.backend.textContent=draw.backend;if(ui.depth)ui.depth.textContent=draw.depthStrategy||'fallback';requestAnimationFrame(frame)}
 function target(radii){C.setCameraTarget(camera,{distanceM:radius*radii});}
 document.querySelectorAll('[data-render-target]').forEach(b=>b.addEventListener('click',()=>target(Number(b.dataset.renderTarget))));
 canvas.addEventListener('wheel',e=>{e.preventDefault();const factor=Math.exp(Math.sign(e.deltaY)*0.28),next=Math.max(radius*1.003,Math.min(radius*400,camera.targetDistanceM*factor));C.setCameraTarget(camera,{distanceM:next})},{passive:false});
 let drag=null;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,d:camera.targetDirection};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=(e.clientX-drag.x)/Math.max(200,canvas.clientWidth),dy=(e.clientY-drag.y)/Math.max(200,canvas.clientHeight),base=drag.d,v=[base[0]+dx*1.4,base[1]-dy*1.4,base[2]];C.setCameraTarget(camera,{distanceM:camera.targetDistanceM,direction:v})});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
 state.navigateToRadii=target;state.snapshot=()=>Object.freeze({camera:C.cameraSnapshot(camera),workingSet:C.sessionStats(session),gpu:G.stateStats(canvas),plan:state.plan,depth:C.depthAdjudication(radius),backend:state.backend,frameTimes:Object.freeze([...state.frameTimes]),environment:Object.freeze({authority:environment.authority,contractId:environment.contractId,digest:O.p2.hex(E.environmentDigest(environment))}),p6:Object.freeze({state:eligibility.state,witnessDigest:O.p2.hex(eligibility.witnessDigest),biologyEstablished:biology.biologyEstablished})});state.dispose=()=>{state.disposed=true;G.dispose(canvas)};
 root.__OFU_PLANET_PREVIEW__=state;requestAnimationFrame(frame);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(typeof globalThis!=='undefined'?globalThis:this);
