(function(root){
'use strict';
const O=root.OFU,C=O&&O.planetRenderCore,G=O&&O.planetWebGL2,A=O&&O.p3Astronomy,P5=O&&O.p5Planetology,E=O&&O.p5EnvironmentV2,B=O&&O.p6Biosphere;
if(!C||!G||!A||!P5||!E||!B||typeof document==='undefined')return;
const PLANET_FIELDS=['galaxyX','galaxyY','galaxyZ','sectorX','sectorY','sectorZ','siteX','siteY','siteZ','orbitSlot'];
function sameKey(a,b){return !!a&&!!b&&PLANET_FIELDS.every(k=>a[k]===b[k])}
function copyKey(key){return Object.freeze(Object.fromEntries(PLANET_FIELDS.map(k=>[k,BigInt(key[k])]))) }
function finite(v,fallback=0){return Number.isFinite(Number(v))?Number(v):fallback}
function pointNdc(v){const a=Array.isArray(v)?v:[0,0];return Object.freeze([Math.max(-1.5,Math.min(1.5,finite(a[0]))),Math.max(-1.5,Math.min(1.5,finite(a[1])))])}
function presentationPrimitives(){const version='ofu-render-presentation-primitives-1',authority=C.AUTHORITY;return Object.freeze({version,authority,coordinateSpace:'NORMALIZED_DEVICE_PRESENTATION_ONLY',star:({positionNdc=[0,0],radiusPx=6,emphasis=1}={})=>Object.freeze({version,authority,kind:'STAR',positionNdc:pointNdc(positionNdc),radiusPx:Math.max(1,Math.min(48,finite(radiusPx,6))),emphasis:Math.max(0,Math.min(1,finite(emphasis,1))),scientificColorClaim:false}),orbitGuide:({centerNdc=[0,0],radiusNdc=.4,thicknessPx=1,emphasis=.35}={})=>Object.freeze({version,authority,kind:'ORBIT_GUIDE',centerNdc:pointNdc(centerNdc),radiusNdc:Math.max(.01,Math.min(2,finite(radiusNdc,.4))),thicknessPx:Math.max(.5,Math.min(6,finite(thicknessPx,1))),emphasis:Math.max(0,Math.min(1,finite(emphasis,.35))),physicalOrbitScaleClaim:false}),selectedHighlight:({positionNdc=[0,0],radiusPx=14}={})=>Object.freeze({version,authority,kind:'SELECTED_HIGHLIGHT',positionNdc:pointNdc(positionNdc),radiusPx:Math.max(4,Math.min(72,finite(radiusPx,14))),scientificColorClaim:false}),bodyMarker:({positionNdc=[0,0],radiusPx=4}={})=>Object.freeze({version,authority,kind:'BODY_MARKER',positionNdc:pointNdc(positionNdc),radiusPx:Math.max(2,Math.min(28,finite(radiusPx,4))),physicalSizeClaim:false})})}
function previewSelection(){const spec=O.BASELINE_BUILD?.rendering?.previewPlanetKey;if(!spec)throw new Error('certified preview planet selector missing from build manifest');const key=Object.freeze(Object.fromEntries(Object.entries(spec).map(([k,v])=>[k,BigInt(v)]))),snapshot=A.planetaryInputSnapshot({masterSeed:Uint8Array.from({length:32},(_,i)=>i),semanticManifestHash:A.semanticManifestHash()},key);if(snapshot.status==='ABSENT')throw new Error('certified preview planet became ABSENT');return{key,snapshot}}
function realize(ctx,inputKey){const key=copyKey(inputKey),planet=A.resolvePlanet(ctx,key),snapshot=A.planetaryInputSnapshot(ctx,key);if(planet.status!=='PRESENT'||snapshot.status==='ABSENT')return{status:'UNSUPPORTED',reason:'P3_ABSENT',key,planetId:planet?.id?O.p2.hex(planet.id):null};const planetId=O.p2.hex(planet.id);if(O.p2.hex(snapshot.planetId)!==planetId)throw new Error('P3 planet identity mismatch');const adapted=P5.adaptP3PlanetaryInputSnapshot(snapshot),physical=P5.realizePhysicalPlanet(ctx,adapted);if(physical.status!=='SUPPORTED')return{status:'UNSUPPORTED',reason:'P5_'+physical.reason,key,planetId};if(O.p2.hex(physical.planetId)!==planetId)throw new Error('renderer source identity drift');const provider=C.createP5Provider(ctx,physical);if(provider.planetId!==planetId)throw new Error('P5 provider identity drift');const environment=E.environmentV2Projection(physical,provider.topology),eligibility=B.eligibility(B.adaptEnvironment(environment)),biology=B.renderingProjection(eligibility);return{status:'SUPPORTED',key,planetId,planet,snapshot,physical,provider,environment,eligibility,biology}}
function boot(){
 const canvas=document.getElementById('planet-view');if(!canvas)return;canvas.tabIndex=0;canvas.removeAttribute('role');canvas.setAttribute('aria-label','Interactive canonical planet viewport. Focus for arrow-key direction, plus and minus zoom, and Home reset.');
 const masterSeed=Uint8Array.from({length:32},(_,i)=>i),ctx={masterSeed,semanticManifestHash:A.semanticManifestHash()},chosen=previewSelection(),initial=realize(ctx,chosen.key);if(initial.status!=='SUPPORTED')throw new Error('preview P5 realization unsupported');
 const expectedId=O.BASELINE_BUILD.rendering.previewPlanetId;if(initial.planetId!==expectedId)throw new Error('certified preview planet identity drift');if(initial.eligibility.state!==O.BASELINE_BUILD.rendering.previewP6EligibilityState||initial.biology.biologyEstablished!==false||O.p2.hex(initial.eligibility.witnessDigest)!==O.BASELINE_BUILD.rendering.previewP6EligibilityWitnessDigest)throw new Error('certified preview P6 state drift');
 const ui={scale:document.getElementById('render-scale'),distance:document.getElementById('render-distance'),patches:document.getElementById('render-patches'),gpu:document.getElementById('render-gpu'),backend:document.getElementById('render-backend'),planet:document.getElementById('render-planet'),depth:document.getElementById('render-depth'),environment:document.getElementById('render-environment'),p6:document.getElementById('render-p6'),biosphere:document.getElementById('render-biosphere')};
 const reducedQuery=typeof matchMedia==='function'?matchMedia('(prefers-reduced-motion: reduce)'):null,primitives=presentationPrimitives();
 const state={ctx,chosen:null,physical:null,provider:null,environment:null,eligibility:null,biology:null,session:null,camera:null,cameraEnvelope:null,radius:0,lastTime:performance.now(),lastPlanAt:0,lastUiAt:0,uiUpdates:0,backend:'pending',draw:null,frameTimes:[],regime:'SYSTEM_VIEW',disposed:false,targetStatus:'UNINITIALIZED',targetReason:null,targetTestOnly:false,targetSwitches:0,presentationReleases:0,lastRelease:null,releaseHistory:[],reducedMotion:!!reducedQuery?.matches,pointerActive:false,viewport:Object.freeze({cssWidth:0,cssHeight:0,backingWidth:canvas.width,backingHeight:canvas.height,devicePixelRatio:1,effectiveDpr:1}),presentationPrimitives:primitives};
 reducedQuery?.addEventListener?.('change',e=>{state.reducedMotion=e.matches});
 function updateHud(){if(state.targetStatus!=='SUPPORTED'){const label=state.targetTestOnly?'TEST-ONLY NEGATIVE FIXTURE':(state.chosen?.planetId||'canonical target');if(ui.planet)ui.planet.textContent=label+' · UNSUPPORTED';if(ui.environment)ui.environment.textContent='UNSUPPORTED';if(ui.p6)ui.p6.textContent='NOT_EVALUATED';if(ui.biosphere)ui.biosphere.textContent='NO CLAIM';if(ui.patches)ui.patches.textContent='0 active';if(ui.gpu)ui.gpu.textContent='released';if(ui.backend)ui.backend.textContent='target unsupported';O.productUI?.sync?.();return}if(ui.planet)ui.planet.textContent=state.provider.planetId.slice(0,12)+'…'+state.provider.planetId.slice(-8);if(ui.environment)ui.environment.textContent=state.environment.authority+' / '+state.environment.contractId;if(ui.p6)ui.p6.textContent=state.eligibility.state;if(ui.biosphere)ui.biosphere.textContent=state.biology.biologyEstablished?'YES':'NO';O.productUI?.sync?.()}
 function updateFrameHud(now,snap,draw){if(now-state.lastUiAt<250)return;state.lastUiAt=now;state.uiUpdates++;if(ui.scale)ui.scale.textContent=snap.scale;if(ui.distance)ui.distance.textContent=(snap.distanceM/state.radius).toFixed(3)+' R';if(ui.patches)ui.patches.textContent=state.session.active.size+' active / '+state.session.cache.map.size+' CPU retained';if(ui.gpu)ui.gpu.textContent=draw.gpu?draw.gpu.liveMeshes+' meshes / '+draw.gpu.liveTrackedBytes+' tracked bytes':'fallback';if(ui.backend)ui.backend.textContent=draw.backend;if(ui.depth)ui.depth.textContent=draw.depthStrategy||'fallback';O.productUI?.sync?.()}
 function paintUnsupported(){let gl=null;try{gl=canvas.getContext('webgl2')}catch{}if(gl){gl.clearColor(.02,.025,.035,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);return}let g=null;try{g=canvas.getContext('2d')}catch{}if(g){g.fillStyle='#050811';g.fillRect(0,0,canvas.width,canvas.height)}}
 function releasePresentation(){const planetId=state.provider?.planetId||state.chosen?.planetId||null,cpuBefore=state.session?C.sessionStats(state.session):null,gpuBefore=G.stateStats(canvas).gpu;if(state.session){state.session.active.clear();state.session.cache.clear()}const cpuAfter=state.session?C.sessionStats(state.session):null,disposed=G.dispose(canvas);if(cpuAfter&&(cpuAfter.activePatches!==0||cpuAfter.cpuMeshes!==0))throw new Error('target CPU presentation state did not clear transactionally');if(disposed?.gpu&&(disposed.gpu.liveMeshes!==0||disposed.gpu.liveTrackedBytes!==0||disposed.gpu.lifecycleAccountingExact!==true))throw new Error('target GPU presentation state did not dispose transactionally');const record=Object.freeze({planetId,cpuMeshesBefore:cpuBefore?.cpuMeshes||0,activePatchesBefore:cpuBefore?.activePatches||0,cpuMeshesAfter:cpuAfter?.cpuMeshes||0,activePatchesAfter:cpuAfter?.activePatches||0,gpuMeshesBefore:gpuBefore?.liveMeshes||0,gpuTrackedBytesBefore:gpuBefore?.liveTrackedBytes||0,gpuLifecycleBeforeExact:gpuBefore?gpuBefore.lifecycleAccountingExact===true:null,gpuDisposed:disposed?.disposed===true,gpuMeshesAfter:disposed?.gpu?.liveMeshes??0,gpuTrackedBytesAfter:disposed?.gpu?.liveTrackedBytes??0,gpuLifecycleAfterExact:disposed?.gpu?disposed.gpu.lifecycleAccountingExact===true:null});state.presentationReleases++;state.lastRelease=record;state.releaseHistory.push(record);if(state.releaseHistory.length>32)state.releaseHistory.shift();state.session=null;state.camera=null;state.cameraEnvelope=null;state.provider=null;state.physical=null;state.environment=null;state.eligibility=null;state.biology=null;state.radius=0;state.draw=null;state.plan=null;state.backend='released';return record}
 function settleCamera(){if(!state.camera||!state.reducedMotion)return;state.camera.distanceM=Math.max(state.camera.minDistanceM,state.camera.targetDistanceM);state.camera.direction=state.camera.targetDirection}
 function install(target,{preserveScale=true,testOnly=false}={}){const hadTarget=!!state.chosen,oldCamera=state.camera,oldRadius=state.radius,oldScale=oldCamera&&oldRadius?oldCamera.targetDistanceM/oldRadius:30,oldDirection=oldCamera?[...oldCamera.targetDirection]:[0.18,0.12,1];if(hadTarget)releasePresentation();if(target.status!=='SUPPORTED'){state.chosen={key:copyKey(target.key),planetId:target.planetId};state.targetStatus='UNSUPPORTED';state.targetReason=target.reason;state.targetTestOnly=!!testOnly;if(hadTarget)state.targetSwitches++;paintUnsupported();updateHud();O.productUI?.announce?.('Selected target cannot be visualized: '+String(target.reason));return false}state.chosen={key:copyKey(target.key),snapshot:target.snapshot,planetId:target.planetId};state.physical=target.physical;state.provider=target.provider;state.environment=target.environment;state.eligibility=target.eligibility;state.biology=target.biology;state.radius=Number(target.physical.physical.meanRadiusM);state.cameraEnvelope=C.cameraEnvelope(target.provider);state.session=C.createSession(target.provider,{maxCpuMeshes:56,maxActivePatches:28});const desired=preserveScale?Math.max(state.cameraEnvelope.minDistanceRadii,Math.min(400,oldScale)):30;state.camera=C.createCamera(state.radius,{distanceRadii:desired,targetDirection:oldDirection,meshBoundingRadiusM:state.cameraEnvelope.meshBoundingRadiusM,clearanceFraction:state.cameraEnvelope.clearanceFraction});state.targetStatus='SUPPORTED';state.targetReason=null;state.targetTestOnly=false;state.lastPlanAt=0;state.lastUiAt=0;state.lastTime=performance.now();if(hadTarget)state.targetSwitches++;updateHud();return true}
 install(initial,{preserveScale:false});
 function resize(){const raw=Math.max(1,Number(root.devicePixelRatio)||1),d=Math.min(2,raw),r=canvas.getBoundingClientRect(),cssWidth=Math.max(2,r.width),cssHeight=Math.max(2,r.height),w=Math.max(2,Math.round(cssWidth*d)),h=Math.max(2,Math.round(cssHeight*d));state.viewport=Object.freeze({cssWidth,cssHeight,backingWidth:w,backingHeight:h,devicePixelRatio:raw,effectiveDpr:d});if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
 function plan(now){if(!state.session||!state.camera)return;if(now-state.lastPlanAt<100&&state.session.active.size)return;state.lastPlanAt=now;const snap=C.cameraSnapshot(state.camera),viewportHeight=Math.max(2,state.viewport.cssHeight||canvas.clientHeight||canvas.height),p=C.mixedLodPlan({targetDirection:snap.direction,radiusM:state.radius,surfaceRadiusM:state.provider.presentationBounds.maxRadiusM,distanceM:snap.distanceM,viewportHeight,maxLevel:9,maxPatches:28,previousLevel:state.session.previousLevel});if(p.coverageComplete!==true)throw new Error('presentation LOD plan failed visible-horizon coverage invariant');C.activate(state.session,p,{skirts:true});state.plan=p}
 function inspectorTarget(){const s=O.inspectorTest?.state?.current;if(!s||s.type!=='Planet'||!s.key)return;if(sameKey(s.key,state.chosen?.key)&&!state.targetTestOnly)return;install(realize(ctx,s.key),{preserveScale:true})}
 function frame(now){if(state.disposed)return;resize();inspectorTarget();if(state.targetStatus!=='SUPPORTED'||!state.camera||!state.session){requestAnimationFrame(frame);return}const elapsed=(now-state.lastTime)/1000,dt=Number.isFinite(elapsed)?Math.max(0,elapsed):0;state.lastTime=now;const snap=state.reducedMotion?(settleCamera(),C.cameraSnapshot(state.camera)):C.stepCamera(state.camera,dt);if(snap.penetratingPresentationGeometry)throw new Error('camera penetrated presentation geometry');plan(now);const t0=performance.now(),draw=G.renderPortable(canvas,state.session,snap,{maxGpuMeshes:48,maxGpuBytes:8*1024*1024}),renderMs=performance.now()-t0;state.draw=draw;state.backend=draw.backend;state.regime=snap.scale;state.frameTimes.push(renderMs);if(state.frameTimes.length>240)state.frameTimes.shift();updateFrameHud(now,snap,draw);requestAnimationFrame(frame)}
 function setTarget(distanceM,direction){if(!state.camera)return;C.setCameraTarget(state.camera,{distanceM,direction:direction||state.camera.targetDirection});settleCamera()}
 function target(radii){if(state.camera)setTarget(state.radius*radii)}
 function rotate(dx,dy){if(!state.camera)return;const d=state.camera.targetDirection;setTarget(state.camera.targetDistanceM,[d[0]+dx,d[1]+dy,d[2]])}
 document.querySelectorAll('[data-render-target]').forEach(b=>b.addEventListener('click',()=>target(Number(b.dataset.renderTarget))));
 canvas.addEventListener('wheel',e=>{if(!state.camera)return;e.preventDefault();const factor=Math.exp(Math.sign(e.deltaY)*0.28),next=Math.max(state.camera.minDistanceM,Math.min(state.radius*400,state.camera.targetDistanceM*factor));setTarget(next)},{passive:false});
 let drag=null;function endPointer(e){drag=null;state.pointerActive=false;if(e&&canvas.hasPointerCapture?.(e.pointerId))try{canvas.releasePointerCapture(e.pointerId)}catch{}}
 canvas.addEventListener('pointerdown',e=>{if(!state.camera)return;if(e.pointerType==='mouse'&&e.button!==0)return;canvas.focus({preventScroll:true});drag={x:e.clientX,y:e.clientY,d:state.camera.targetDirection,id:e.pointerId};state.pointerActive=true;try{canvas.setPointerCapture(e.pointerId)}catch{}});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId||!state.camera)return;const dx=(e.clientX-drag.x)/Math.max(200,canvas.clientWidth),dy=(e.clientY-drag.y)/Math.max(200,canvas.clientHeight),base=drag.d;setTarget(state.camera.targetDistanceM,[base[0]+dx*1.4,base[1]-dy*1.4,base[2]])});canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('lostpointercapture',()=>{drag=null;state.pointerActive=false});
 canvas.addEventListener('keydown',e=>{if(!state.camera)return;let handled=true;if(e.key==='ArrowLeft')rotate(-.12,0);else if(e.key==='ArrowRight')rotate(.12,0);else if(e.key==='ArrowUp')rotate(0,.12);else if(e.key==='ArrowDown')rotate(0,-.12);else if(e.key==='+'||e.key==='=')target(Math.max(state.camera.minDistanceM/state.radius,state.camera.targetDistanceM/state.radius*.75));else if(e.key==='-'||e.key==='_')target(Math.min(400,state.camera.targetDistanceM/state.radius*1.35));else if(e.key==='Home')setTarget(state.radius*30,[0.18,0.12,1]);else handled=false;if(handled){e.preventDefault();e.stopPropagation()}});
 state.navigateToRadii=target;state.retarget=key=>install(realize(ctx,key),{preserveScale:true});state.testOnlyUnsupportedFixture=()=>install({status:'UNSUPPORTED',reason:'TEST_ONLY_NEGATIVE_FIXTURE',key:state.chosen.key,planetId:'TEST_ONLY_NEGATIVE_FIXTURE'},{preserveScale:true,testOnly:true});state.snapshot=()=>Object.freeze({authority:C.AUTHORITY,targetStatus:state.targetStatus,targetReason:state.targetReason,targetTestOnly:state.targetTestOnly,targetSwitches:state.targetSwitches,presentationReleases:state.presentationReleases,lastRelease:state.lastRelease,releaseHistory:Object.freeze([...state.releaseHistory]),planetId:state.provider?.planetId||state.chosen?.planetId||null,resourceBinding:state.session&&state.provider?Object.freeze({providerPlanetId:state.provider.planetId,sessionProviderPlanetId:state.session.provider.planetId,sameProvider:state.session.provider===state.provider}):null,camera:state.camera?C.cameraSnapshot(state.camera):null,cameraTarget:state.camera?Object.freeze({distanceM:state.camera.targetDistanceM,direction:Object.freeze([...state.camera.targetDirection])}):null,cameraEnvelope:state.cameraEnvelope,presentationBounds:state.provider?.presentationBounds||null,workingSet:state.session?C.sessionStats(state.session):null,gpu:G.stateStats(canvas),plan:state.plan||null,clip:state.draw?.clip||null,renderer:Object.freeze({backend:state.backend,palette:state.draw?.palette||'FALLBACK_OR_PENDING',culling:state.draw?.culling||null,frontFace:state.draw?.frontFace||null}),viewport:state.viewport,depth:state.radius?C.depthAdjudication(state.radius):null,backend:state.backend,frameTimes:Object.freeze([...state.frameTimes]),environment:state.environment?Object.freeze({authority:state.environment.authority,contractId:state.environment.contractId,digest:O.p2.hex(E.environmentDigest(state.environment))}):null,p6:state.eligibility?Object.freeze({state:state.eligibility.state,witnessDigest:O.p2.hex(state.eligibility.witnessDigest),biologyEstablished:state.biology.biologyEstablished,canGenerateBiosphere:state.eligibility.canGenerateBiosphere}):null,presentationPrimitives:Object.freeze({version:primitives.version,authority:primitives.authority,kinds:Object.freeze(['STAR','ORBIT_GUIDE','SELECTED_HIGHLIGHT','BODY_MARKER'])}),uiUpdates:state.uiUpdates,reducedMotion:state.reducedMotion,pointerActive:state.pointerActive});state.dispose=()=>{state.disposed=true;if(state.chosen)releasePresentation()};
 root.__OFU_PLANET_PREVIEW__=state;requestAnimationFrame(frame);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(typeof globalThis!=='undefined'?globalThis:this);
