(function(root){
'use strict';
const O=root.OFU=root.OFU||{},AUTHORITY='PRESENTATION_ONLY';
const SCALES=Object.freeze({GALAXY:'GALAXY',REGION:'REGION',NEIGHBORHOOD:'NEIGHBORHOOD',SYSTEM:'SYSTEM',ORBIT:'ORBIT',PLANET:'PLANET',APPROACH:'APPROACH',GLOBAL_SURFACE:'GLOBAL_SURFACE',REGIONAL_SURFACE:'REGIONAL_SURFACE',LOCAL_SURFACE:'LOCAL_SURFACE',HUMAN:'HUMAN',LIFE:'LIFE',CIVILIZATION:'CIVILIZATION',MATERIAL:'MATERIAL',MICROSTRUCTURE:'MICROSTRUCTURE',MOLECULAR:'MOLECULAR',ATOMIC:'ATOMIC'});
const CAPS=Object.freeze({galaxies:64,systems:48,stars:8,planets:24,moons:32,surfacePatches:192,ecologyPopulations:96,settlements:128,tradeEdges:192,microNodes:512,totalObjects:768,totalLinks:384});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0)),ppm=(v,f=0)=>clamp(v===undefined?f:v,0,1000000);
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v)||ArrayBuffer.isView(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function hash(t){let h=2166136261>>>0;for(const c of String(t)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return h>>>0}
function rand(seed,i=0){let x=(hash(seed)+Math.imul(i+1,0x9e3779b1))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/4294967296}
function id(v,f='unknown'){return String(v?.canonicalId||v?.galaxyIdentity||v?.galacticRegionIdentity||v?.stellarObjectIdentity||v?.stellarSystemIdentity||v?.planetIdentity||v?.populationId||v?.settlementId||v?.cellIdentity||v?.complexIdentity||v?.representationId||v?.id||f)}
function src(v){const a=v?.authority;return typeof a==='string'?a:String(a?.class||a?.domain||'UNSPECIFIED_SOURCE_AUTHORITY')}
function pid(role,s){return'v1-present:'+role+':'+hash(role+'|'+s).toString(16).padStart(8,'0')}
const color=(r,g,b)=>Object.freeze([clamp(r,0,1),clamp(g,0,1),clamp(b,0,1)]),palette=Object.freeze({rockA:color(.43,.34,.27),rockB:color(.67,.54,.39),ocean:color(.08,.29,.48),ice:color(.72,.86,.94),gasA:color(.71,.57,.40),gasB:color(.42,.35,.31),iceGiantA:color(.36,.66,.72),iceGiantB:color(.58,.79,.84),life:color(.30,.67,.45),civilization:color(.92,.68,.31),ruin:color(.47,.40,.36)});
function object(kind,s,source,visual,extra={}){return freeze({objectId:pid(kind,s),kind,sourceId:String(s),authority:AUTHORITY,sourceAuthority:src(source),selectable:extra.selectable!==false,decorative:false,visual,...extra,claims:Object.freeze({visualEncodingIsScientificTruth:false,screenGeometryCanonical:false,literalPhotography:false,...extra.claims})})}
function decorative(seed,n=48){const out=[];for(let i=0;i<Math.min(96,n);i++)out.push(freeze({objectId:'v1-decorative:'+hash(seed+'|'+i).toString(16),kind:'DECORATIVE_DEPTH',authority:AUTHORITY,sourceAuthority:'NONE',selectable:false,decorative:true,visual:{x:rand(seed,i*4),y:rand(seed,i*4+1),depth:rand(seed,i*4+2),sizePx:.45+rand(seed,i*4+3)*1.2,opacity:.08+rand(seed,i*5+4)*.34},claims:{canonicalEntity:false,physicalPosition:false,physicalBrightness:false}}));return Object.freeze(out)}
function scene(scale,s,objects,links=[],layers=[],meta={}){if(objects.length>CAPS.totalObjects||links.length>CAPS.totalLinks)throw new Error('v1 presentation cap exceeded');return freeze({version:'ofu-v1-world-presentation-1',contract:'ofu-v1-world-presentation-scene-1',scale,status:'READY',authority:AUTHORITY,sourceId:String(s||'none'),objects:Object.freeze(objects),links:Object.freeze(links),layers:Object.freeze(layers),bounds:CAPS,informationHierarchy:Object.freeze(['UNIVERSE','LOCATION','OBJECT','PHENOMENON']),technicalEvidenceSurface:'INSPECT_LAB',...meta})}
O.v1PresentationCore=Object.freeze({AUTHORITY,SCALES,CAPS,clamp,ppm,freeze,hash,rand,id,src,pid,color,palette,object,decorative,scene});
})(globalThis);
