(function(root){
'use strict';
const O=root.OFU=root.OFU||{};
const VERSION='ofu-v1-render-provider-adapter-1',AUTHORITY='PRESENTATION_ONLY';
function freeze(v){if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const k of Object.keys(v))freeze(v[k]);return Object.freeze(v)}
function response(value,provider='direct',authority='UNSPECIFIED'){return freeze({provider,authority,value})}
function unwrap(input){if(!input)return null;return Object.hasOwn(input,'value')&&Object.hasOwn(input,'provider')?input.value:input}
function assemble({planetIdentity=null,astronomy=null,planetology=null,biology=null,civilization=null,microscopic=null}={}){const p=unwrap(planetology),b=unwrap(biology),c=unwrap(civilization),m=unwrap(microscopic),a=unwrap(astronomy);return freeze({planetIdentity:planetIdentity||p?.planetIdentity||b?.worldIdentity||c?.worldIdentity||null,astronomy:a||null,planetology:p||null,biology:b?.ecosystem?b:b?{ecosystem:b.ecosystem||b}:null,civilization:c||null,microscopic:m?.supported===false?null:m||null,renderAdapter:{version:VERSION,authority:AUTHORITY,canonicalPromotion:false}})}
function sceneRequest({scale,responses={},world=null,mobile=false,selectedId=null,selectedPlanetId=null,selectedSystemId=null,cells=null,visual=null}={}){const upper=String(scale||'').toUpperCase(),req={scale:upper,mobile};if(upper==='GALAXY'){req.discovery=unwrap(responses.galaxies||responses.astronomy);req.selectedId=selectedId;return freeze(req)}if(upper==='REGION'){req.region=unwrap(responses.region);req.systems=unwrap(responses.systems)||[];req.selectedSystemId=selectedSystemId;return freeze(req)}if(upper==='NEIGHBORHOOD'){req.systems=unwrap(responses.systems)||[];req.selectedSystemId=selectedSystemId;req.centerId=selectedId||'stellar-neighborhood';return freeze(req)}if(['SYSTEM','ORBIT'].includes(upper)){req.system=unwrap(responses.system);req.selectedPlanetId=selectedPlanetId;return freeze(req)}req.world=world||assemble({planetIdentity:responses.planetIdentity,astronomy:responses.astronomy,planetology:responses.planetology,biology:responses.biology,civilization:responses.civilization,microscopic:responses.microscopic});if(cells)req.cells=cells;if(visual)req.visual=visual;if(['MATERIAL','MICROSTRUCTURE','MOLECULAR','ATOMIC'].includes(upper)&&responses.microRepresentation)req.representation=unwrap(responses.microRepresentation);return freeze(req)}
function compile(args){if(!O.v1WorldPresentation)throw new Error('v1 world presentation required');return O.v1WorldPresentation.compose(sceneRequest(args))}
O.v1RenderProviderAdapter=Object.freeze({VERSION,AUTHORITY,response,unwrap,assemble,sceneRequest,compile});
})(globalThis);
